### ISSUE TITLE
az devops CLI - where to download

### ISSUE THREAD

**Issue by kprpg** [Azure/azure-cli-extensions#1008]
Where should one go to get the devops cli. When I type "az devops", I get az: 'devops' is not in the 'az' command group. See 'az --help'. And so searching for the devops cli download turns empty. This is frustrating that one cannot find any where in the Microsoft portal where to get the devops cli. I have installed Azure DevOps server 2019 on my laptop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9e855a-abc5-14d9-ba73-4ab527ffee16
* Version Independent ID: 85a46540-4b25-94f4-2c0e-29e1f8fefe35
* Content: [az devops](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops?view=azure-cli-latest#ext-azure-devops-az-devops-configure)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jmhardison** [comment]
You can view available extensions using:
`az extension list-available`

And install an extension with:
`az extension add --name <extname>`

So in your case, you would use:
`az extension add --name azure-devops`

Also, here is the documentation on it: [Azure CLI Extensions Docs](https://docs.microsoft.com/en-us/cli/azure/extension?view=azure-cli-latest)

**Comment by zikalino** [comment]
I think this issue can be closed?

**Comment by geverghe** [comment]
I think the broader issue is the experience of locating an extension and how to download. May be the azure cli team can have a look into this on whether to tackle this problem. On receiving az devops and understanding the extension is not installed, instead of az --help, may be there can be better error handling to point to learning how to add extensions or finding an extension by a particular name.

**Comment by fengzhou-msft** [comment]
Error message is enhanced with https://github.com/Azure/azure-cli/pull/11492.
Now the message is like this:

> az: 'devops' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview

Ideally, we should tell users which extension to install with the extension add command. But only when we load all extensions do we know that which extension the command is coming from, which may not be worth the effort.
