### ISSUE TITLE
Any ETA for release of this feature?

### ISSUE THREAD

**Issue by mildsar** [Azure/azure-cli-extensions#1012]
These cmdlts is still labeled as PREVIEW. When it is going into release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba39ac35-94ff-5cda-dede-4834d174ee4c
* Version Independent ID: 93f1ab7d-610b-0fc4-c247-c31dd7752f60
* Content: [az pipelines variable-group](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/variable-group?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines/variable-group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines/variable-group.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Need to triage.

**Comment by RakeshMohanMSFT** [comment]
@mildsar Apologies for the delay in acknowledging and responding. This is GA. Closing this thread now.
