### ISSUE TITLE
artifact download failed

### ISSUE THREAD

**Issue by tiruhub** [Azure/azure-cli-extensions#1015]
Below command failed (which used to be success a few weeks ago).

az artifacts universal download --organization "https://dev.azure.com/windowspartners/" --feed "mcdm_intel_drops" --name "pix" --version "19.10.22" --path .

Attached the screenshot of the failure
![Azure_failure](https://user-images.githubusercontent.com/35935618/67525115-e7f1ee80-f666-11e9-930f-7e2c910d4736.PNG)

**Comment by yonzhan** [comment]
@zikalino, need to triage.

**Comment by ishitam8** [comment]
Please check the updates on the linked issue where we are tracking this - Azure/azure-devops-cli-extension#871

**Comment by geverghe** [comment]
Closing this issue as we are tracking it our repo, under https://github.com/Azure/azure-devops-cli-extension/issues/871 . Please follow the issue for all future updates.
