### ISSUE TITLE
"az aks get-versions" is failing with no reason

### ISSUE THREAD

**Issue by waltlp** [Azure/azure-cli-extensions#1027]
## Describe the bug

**Command Name**
`az aks get-versions
Extension Name: aks-preview. Version: 0.4.11.`

**Errors:**
```
APIVersion 2019-08-01 is not available
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/container_service_client.py, ln 169, in container_services
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-08-01 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-versions --location {} --output {}`

## Expected Behavior
To show which kubernetes versions are available in the chosen region.

## Environment Summary
```
Linux-4.4.0-165-generic-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

Extensions:
aks-preview 0.4.11

```
## Additional Context
I ran the command as:
az aks get-versions --location eastus --output table

**Comment by fengzhou-msft** [comment]
@waltlp can you describe how you installed azure-cli? The error message seems to be some issue related to packaging.

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Feel free to reopen the issue if it still exists.
