### ISSUE TITLE
az monitor app-insights query Execute a simple query over past 3.5 days.

### ISSUE THREAD

**Issue by alexkoepke** [Azure/azure-cli-extensions#1041]
## Describe the bug
Trying to query Application Insights via the example provided via the [az monitor app-insights query](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights?view=azure-cli-latest#ext-application-insights-az-monitor-app-insights-query) docs.

**Command Name**
`az monitor app-insights query
Extension Name: application-insights. Version: 0.1.1.`

**Errors:**
```
unsupported operand type(s) for -: 'datetime.datetime' and 'str'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cliextensions/application-insights/azext_applicationinsights/util.py, ln 40, in get_timespan
    start_time = (dateutil.parser.parse(end_time) - offset).isoformat()
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'str'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor app-insights query --app <Your-GUID> --analytics-query 'requests | summarize count() by bin(timestamp, 1h)' --offset P3DT12H`

## Expected Behavior
Execute a simple query over the past 3.5 days.

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

Extensions:
application-insights 0.1.1
log-analytics 0.1.3

```

**Comment by MyronFanQiu** [comment]
@alexkoepke Thanks. I'm looking at this issue.

**Comment by yonzhan** [comment]
add to S171
