### ISSUE TITLE
improve ci to catch problem with metadata import

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-cli-extensions#1052]
Because of misspelling in setup.py, metadata was not imported and was not propagated to index, just like here:

https://github.com/Azure/azure-cli-extensions/pull/1048

**Comment by zikalino** [comment]
ip-group extension has wrong metadata because of the same reason, and this needs to be fixed

**Comment by fengzhou-msft** [comment]
@haroldrandom please take a look.

**Comment by haroldrandom** [comment]
Added one case the consequence without this check https://github.com/Azure/azure-cli-extensions/pull/1631 -- no, azext_metadata.json content in index.json.

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S171
