### ISSUE TITLE
Clear expiration with update cmd doesn't work as documentated

### ISSUE THREAD

**Issue by softwarecraft** [Azure/azure-cli-extensions#1053]
Under Update cmd for expiration argument it says "To unset the expiration for the banner, supply an empty value to this argument.".

I tried
* --expiration
* --expiration ''
* --expiration ""

as in 
* az devops admin banner update --id '<guid>' --org https://dev.azure.com/MyOrgUrl/ --expiration ''

None of these worked, got an error msg:
* az : ERROR: az devops admin banner update: error: argument --expiration: expected one argument

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c28dc091-8cff-450b-14a8-ef2399b80a25
* Version Independent ID: 85f56f24-276c-a2d7-eccd-cb877c65b1d6
* Content: [az devops admin banner](https://docs.microsoft.com/en-ca/cli/azure/ext/azure-devops/devops/admin/banner?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/admin/banner.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/admin/banner.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by softwarecraft** [comment]
I raised two related issues that went under a different page path for some reason, perhaps this one should move under the same path:
* https://docs.microsoft.com/en-us/cli/azure/devops/admin/banner

**Comment by softwarecraft** [comment]
As this may be a bug, I opened an issue in the code repo, https://github.com/Azure/azure-devops-cli-extension/issues/867.

**Comment by geverghe** [comment]
Closing this issue as you have created an issue in our repo - https://github.com/Azure/azure-devops-cli-extension/issues/867. Please track that issue for all future updates.
