### ISSUE TITLE
What does "show" mean?

### ISSUE THREAD

**Issue by softwarecraft** [Azure/azure-cli-extensions#1056]
Under Add cmd it says "Add a new banner and immediately show it." which indicates that "show" means "make this banner definition the active one".

Under Show cmd it says "Show details for a banner." which could mean
* "display the properties for one specific banner definition, whether or not it is active"

or it could mean 

* "make this specific banner definition the active one"

I tried to use Show cmd to change the active banner back to a prior banner definition (which is shown by the List cmd)
* az devops admin banner show --id '&lt;old-banner-guid&gt;' --org https://dev.azure.com/MyOrg/

but this didn't work, the current banner remained the active one and the old banner was not activated.

This is a replacement for issue https://github.com/Azure/azure-cli/issues/11047.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c28dc091-8cff-450b-14a8-ef2399b80a25
* Version Independent ID: 85f56f24-276c-a2d7-eccd-cb877c65b1d6
* Content: [az devops admin banner](https://docs.microsoft.com/en-ca/cli/azure/ext/azure-devops/devops/admin/banner?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/admin/banner.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/admin/banner.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ishitam8** [comment]
@softwarecraft , Please check the updates on the linked issue where we are tracking this - Azure/azure-devops-cli-extension#870

**Comment by geverghe** [comment]
Closing this issue as it is being tracked in https://github.com/Azure/azure-devops-cli-extension/issues/870 - Please follow the issue for all updates.
