### ISSUE TITLE
What HTML markup is allowed in message?

### ISSUE THREAD

**Issue by softwarecraft** [Azure/azure-cli-extensions#1057]
The anchor tag is supported in the message text and a hyperlink is display in AzDevOps web pages but various formatting tags (bold, strong, font, span, div) are ignored and not rendered, although they are preserved in the message text when you list the messages.

Please update the docs to indicate which HTML markup is supported.

It would be very useful to allow formatting tags to be rendered.

This is a replacement for https://github.com/Azure/azure-cli/issues/11048.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c28dc091-8cff-450b-14a8-ef2399b80a25
* Version Independent ID: 85f56f24-276c-a2d7-eccd-cb877c65b1d6
* Content: [az devops admin banner](https://docs.microsoft.com/en-ca/cli/azure/ext/azure-devops/devops/admin/banner?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/admin/banner.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/admin/banner.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ishitam8** [comment]
@softwarecraft  , Please check the updates on the linked issue where we are tracking this - Azure/azure-devops-cli-extension#869

**Comment by geverghe** [comment]
Closing this issue as it is being tracked in https://github.com/Azure/azure-devops-cli-extension/issues/869 - Please follow this issue for all updates.
