### ISSUE TITLE
Travis CI should test against dev of azure-cli

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-cli-extensions#1058]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Description of issue (in as much detail as possible)
Why does Travis CI use `git clone azure-cli` to install azure cli as shown https://github.com/Azure/azure-cli-extensions/blob/master/scripts/ci/verify_modified_index.sh#L6?

It should use the published version.
-----

**Comment by fengzhou-msft** [comment]
@haroldrandom please take a look.

**Comment by Juliehzl** [comment]
Add more infomation  https://travis-ci.org/Azure/azure-cli-extensions/jobs/606089636?utm_medium=notification&utm_source=github_status

**Comment by haroldrandom** [comment]
release branch has more stable features but dev has more advantages and easily fix and quickly move on.

Remain dev as discussion offline.

Feel free to reopn if any further question.  :)
