### ISSUE TITLE
Add a sas-definition for a container sas-token

### ISSUE THREAD

**Issue by arkiaconsulting** [Azure/azure-cli-extensions#1063]
Please add an example for creating a Sas definition based on a container Sas token template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb4f675-e758-034e-eb29-7feb1d26ba40
* Version Independent ID: 29bc7e09-ef46-df68-7fbe-3d2c641134e0
* Content: [az keyvault storage sas-definition](https://docs.microsoft.com/en-us/cli/azure/ext/keyvault-preview/keyvault/storage/sas-definition?view=azure-cli-latest#ext-keyvault-preview-az-keyvault-storage-sas-definition-create)
* Content Source: [latest/docs-ref-autogen/ext/keyvault-preview/keyvault/storage/sas-definition.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/keyvault-preview/keyvault/storage/sas-definition.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment]
@jiasli Can you have a look at this issue?
