### ISSUE TITLE
Create sample command invalid

### ISSUE THREAD

**Issue by algattik** [Azure/azure-cli-extensions#1069]
The sample command `az spring-cloud create -n MyService -g MyResourceGroup -l westus` is invalid:
- The resource name is invalid. It can contain only lowercase letters, numbers and hyphens.
- The service is not yet available in westus.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a04094f3-af8c-1d4e-ef46-c1053ef283b3
* Version Independent ID: df8bb2c7-b842-690d-dc63-b5fb9155d821
* Content: [az spring-cloud](https://docs.microsoft.com/en-us/cli/azure/ext/spring-cloud/spring-cloud?view=azure-cli-latest#ext-spring-cloud-az-spring-cloud-create)
* Content Source: [latest/docs-ref-autogen/ext/spring-cloud/spring-cloud.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/spring-cloud/spring-cloud.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
Thanks for feedback!

**Comment by lilyjma** [comment]
hi @algattik is this still a problem that you're experiencing?

**Comment by RakeshMohanMSFT** [comment]
This is working and can deploy to west us. Please upgrade to latest version of azure cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
`az spring-cloud create -n issue1069springcloud -g Issue1069 -l westus`
![image](https://user-images.githubusercontent.com/49954584/183707906-298ebc2e-d9c3-4358-8a75-454316d01836.png)
