### ISSUE TITLE
'app-insights' is not in the 'az monitor' command group

### ISSUE THREAD

**Issue by gaburn** [Azure/azure-cli-extensions#1071]
When running any 'az monitor app-insights' commands on this page I get the following error:

az monitor: 'app-insights' is not in the 'az monitor' command group. See 'az monitor --help'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 333d37d2-61e2-0184-d253-157ee236439c
* Version Independent ID: 9b0e976f-3cb5-e813-9f33-e9cea7a8df8c
* Content: [az monitor app-insights component](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights/component?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/component.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/component.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by gaburn** [comment]
It looks like you need to install the 'application-insights' extension first:
az extension add --name application-insights

Maybe these instructions could be added to the error message?

**Comment by fengzhou-msft** [comment]
@MyronFanQiu please take a look.

**Comment by MyronFanQiu** [comment]
@gaburn Thanks! We will discuss about this issue later. It's not easy to add the potential extension into the error message. But we should figure out a better error message.
