### ISSUE TITLE
az network firewall ip-config create: cannot have more than one subnet reference

### ISSUE THREAD

**Issue by naikajah** [Azure/azure-cli-extensions#1074]
## Describe the bug
Extension Name: azure-firewall. Version: 0.1.4.

> $ az --version
> azure-cli                         2.0.76

**Command Name**
`az network firewall ip-config create --firewall-name test-fw --name poc2 --public-ip-address fw-poc2-pip --resource-group lz-uksouth-rg --vnet-name hub-vnet 
`

**Errors:**
```
Azure Firewall /subscriptions/xx-xx-xx-xx/resourceGroups/lz-uksouth-rg/providers/Microsoft.Network/azureFirewalls/test-fw cannot have more than one subnet reference, please ensure only one IpConfiguration contains a subnet reference
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network firewall ip-config create --firewall-name {} --name {} --public-ip-address {} --resource-group {} --vnet-name {} --debug`

## Expected Behavior
Add secondary public ip configuration to azure firewall

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 2.7.17
Shell: bash

azure-cli 2.0.76

Extensions:
azure-firewall 0.1.4
azure-devops 0.12.0

```

**Comment by fengzhou-msft** [comment]
@MyronFanQiu please take a look.

**Comment by Faheemitian** [comment]
I am getting this error as well. Any ideas what might be going on? Our build agents are Linux based can't try the Powershell commands.

**Comment by MyronFanQiu** [comment]
@naikajah Thanks for reporting this issue. Are you trying to create the second firewall ip-config for a firewall? I want to know the user scenario to see what I can do for you. I tested to create a ip-config for a firewall and it succeed.

**Comment by timja** [comment]
> @naikajah Thanks for reporting this issue. Are you trying to create the second firewall ip-config for a firewall? I want to know the user scenario to see what I can do for you. I tested to create a ip-config for a firewall and it succeed.

(I work with @naikajah) Yes that's what we were trying to do, 

It's failing because you can only set a subnet ID on the first ip configuration

it's probably because of this line:
https://github.com/Azure/azure-cli-extensions/blob/master/src/azure-firewall/azext_firewall/custom.py#L85

the subnet is defaulted to existing, and I can't see a way to unset it through the CLI, although I can't quite see how the function is invoked, possibly you can  pass an argument through to set it to empty?

**Comment by Faheemitian** [comment]
Same here. The first ip-config gets created without any errors. The second config throws the error. The Powershell module seems to work correctly as documented here - https://docs.microsoft.com/en-us/azure/firewall/deploy-multi-public-ip-powershell#add-a-public-ip-address-to-an-existing-firewall

**Comment by MyronFanQiu** [comment]
@Faheemitian @timja Thanks! I see. Let me check how to fix it and update the status later.
