### ISSUE TITLE
"private-ip-address" option dose not work well.

### ISSUE THREAD

**Issue by hisasima** [Azure/azure-cli-extensions#1084]
I could use this parameter with "az network firewall ip-config create". I can not find this parameter by powershell or ARM templete. Is this parameter correct ?

https://docs.microsoft.com/en-us/powershell/module/az.network/new-azfirewall?view=azps-3.0.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a309da7-b5b4-3aa1-e546-174af6270e4d
* Version Independent ID: f62e6045-1dd9-677f-f4df-5b29338f29dc
* Content: [az network firewall ip-config](https://docs.microsoft.com/en-us/cli/azure/ext/azure-firewall/network/firewall/ip-config?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-firewall/network/firewall/ip-config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-firewall/network/firewall/ip-config.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@MyronFanQiu please take a look.

**Comment by MyronFanQiu** [comment]
@hisasima I'm not sure about powershell. If you cannot find this parameter, you can file an issue in powershell's repo. For ARM template, it should work to use privateIpAddress in the part of AzureFirewallIPConfiguration

**Comment by hisasima** [comment]
Could you check wheter this parameter is right or not ? I tried to use this parameter but it dose not work well. Could you check it ?

**Comment by MyronFanQiu** [comment]
@hisasima Hello. I'm not familiar with ARM template. Based on my knowledge, it should work. In the python SDK, 
https://github.com/Azure/azure-sdk-for-python/blob/3e878ffbaea57bae4537fd362aacf35cc43a934b/sdk/network/azure-mgmt-network/azure/mgmt/network/v2019_09_01/models/_models.py#L2971
You can try this `privateIPAddress` again. If you still encounter problem, I can invite service team to take a look at this issue.

**Comment by hisasima** [comment]
I can not use the option. Please see bellow.

az network firewall ip-config create \
>     --firewall-name Test-FW01 \
>     --name FW-config \
>     --public-ip-address fw-pip \
>     --resource-group Test-FW-RG \
>     --vnet-name Test-FW-VN \
>     --private-ip-address 10.0.1.11
{
  "etag": "W/\"d75ba453-4799-4cc0-86ad-05c2f1b47864\"",
  "id": "/subscriptions/66bef1e6-a2cb-xxx-xxx-eaacf5ae1be3/resourceGroups/Test-FW-RG/providers/Microsoft.Network/azureFirewalls/Test-FW01/azureFirewallIpConfigurations/FW-config",
  "name": "FW-config",
  "privateIpAddress": "10.0.1.4",
  "provisioningState": "Succeeded",
  "publicIpAddress": {
    "id": "/subscriptions/66bef1e6-a2cb-xxx-xxx-eaacf5ae1be3/resourceGroups/Test-FW-RG/providers/Microsoft.Network/publicIPAddresses/fw-pip",
    "resourceGroup": "Test-FW-RG"
  },
  "resourceGroup": "Test-FW-RG",
  "subnet": {
    "id": "/subscriptions/66bef1e6-a2cb-xxx-xxx-eaacf5ae1be3/resourceGroups/Test-FW-RG/providers/Microsoft.Network/virtualNetworks/Test-FW-VN/subnets/AzureFirewallSubnet",
    "resourceGroup": "Test-FW-RG"
  },
  "type": "Microsoft.Network/azureFirewalls/azureFirewallIpConfigurations"
}

**Comment by hisasima** [comment]
$ az network firewall update \
>     --name Test-FW01 \
>     --resource-group Test-FW-RG
{
  "applicationRuleCollections": [],
  "etag": "W/\"d75ba453-4799-4cc0-86ad-05c2f1b47864\"",
  "id": "/subscriptions/66bef1e6-a2cb-4f94-a009-eaacf5ae1be3/resourceGroups/Test-FW-RG/providers/Microsoft.Network/azureFirewalls/Test-FW01",
  "ipConfigurations": [
    {
      "etag": "W/\"d75ba453-4799-4cc0-86ad-05c2f1b47864\"",
      "id": "/subscriptions/66bef1e6-a2cb-4f94-a009-eaacf5ae1be3/resourceGroups/Test-FW-RG/providers/Microsoft.Network/azureFirewalls/Test-FW01/azureFirewallIpConfigurations/FW-config",
      "name": "FW-config",
      "privateIpAddress": "10.0.1.4",
      "provisioningState": "Succeeded",
      "publicIpAddress": {
        "id": "/subscriptions/66bef1e6-a2cb-4f94-a009-eaacf5ae1be3/resourceGroups/Test-FW-RG/providers/Microsoft.Network/publicIPAddresses/fw-pip",
        "resourceGroup": "Test-FW-RG"
      },
      "resourceGroup": "Test-FW-RG",
      "subnet": {
        "id": "/subscriptions/66bef1e6-a2cb-4f94-a009-eaacf5ae1be3/resourceGroups/Test-FW-RG/providers/Microsoft.Network/virtualNetworks/Test-FW-VN/subnets/AzureFirewallSubnet",
        "resourceGroup": "Test-FW-RG"
      },
      "type": "Microsoft.Network/azureFirewalls/azureFirewallIpConfigurations"
    }
  ],
  "location": "eastus",
  "name": "Test-FW01",
  "natRuleCollections": [],
  "networkRuleCollections": [],
  "provisioningState": "Succeeded",
  "resourceGroup": "Test-FW-RG",
  "tags": null,
  "threatIntelMode": "Alert",
  "type": "Microsoft.Network/azureFirewalls",
  "zones": null
}

**Comment by MyronFanQiu** [comment]
@hisasima Sorry for my misunderstanding. I used to think the PS or ARM could not work but CLI can. I just checked the code. In the latest python sdk version, this property cannot be updated anymore.
https://github.com/Azure/azure-sdk-for-python/blob/3d7a5d92812c3393a180882a343bfecf1a9a55d2/sdk/network/azure-mgmt-network/azure/mgmt/network/v2019_09_01/models/_models_py3.py#L2964
I will invite the service team to answer the question and to see if I need to remove this argument.

**Comment by MyronFanQiu** [comment]
@hisasima Sorry for my misunderstanding. I used to think the PS or ARM could not work but CLI can. I just checked the code. In the latest python sdk version, this property cannot be updated anymore.
https://github.com/Azure/azure-sdk-for-python/blob/3d7a5d92812c3393a180882a343bfecf1a9a55d2/sdk/network/azure-mgmt-network/azure/mgmt/network/v2019_09_01/models/_models_py3.py#L2964
I will invite the service team to answer the question and to see if I need to remove this argument.

**Comment by MyronFanQiu** [comment]
@tejasshah7 Hello. Could you help us about this issue? We just found that `private-ip-address` has become readonly in the lastest api version. Is there any reason? Should I deprecate this argument?

**Comment by yonzhan** [comment]
@tejasshah7 any update?

**Comment by MyronFanQiu** [comment]
@tejasshah7 Hello. Could you share some information with us?

**Comment by tejasshah7** [comment]
@yonzhan and @MyronFanQiu I apologize for the delay. I was on vacation and just returned back.
- What API version s being used here?
- Also what is the use case to even set this field?

**Comment by MyronFanQiu** [comment]
@tejasshah7 Thanks. Waiting for your confirmation.

**Comment by yonzhan** [comment]
@tejasshah7  any update for this issue? Can we close it?

**Comment by tejasshah7** [comment]
@yonzhan  I apologize for the delay. I will get to you on this by EOD.

**Comment by tejasshah7** [comment]
@yonzhan I confirmed that this field is not needed and can be removed from Az CLI as well.

**Comment by MyronFanQiu** [comment]
@tejasshah7 good to know. @hisasima Hello. The service team has confirmed that this field is not needed. I will deprecate this argument later.

**Comment by hisasima** [comment]
Thank you for your support. I understand.

**Comment by KarenHammons** [comment]
This option will be removed from the Azure CLI.  Thank you for bringing this to our attention!
