### ISSUE TITLE
az artifacts universal publish fails to download ArtifactTool_win10-x64_0.2.128

### ISSUE THREAD

**Issue by nayanshah** [Azure/azure-cli-extensions#1095]
### az artifacts universal publish fails to download ArtifactTool_win10-x64_0.2.128

Re-running the command attempts to download the tool again and fails midway. 

## Describe the bug

**Command Name**
`az artifacts universal publish
Extension Name: azure-devops. Version: 0.10.0.`

**Errors:**
```
('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 297, in recv_into
pip-install-ygnynjtx\pyOpenSSL\OpenSSL\SSL.py, ln 1822, in recv_into
pip-install-ygnynjtx\pyOpenSSL\OpenSSL\SSL.py, ln 1639, in _raise_ssl_error
OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

...

    for chunk in response.iter_content(chunk_size=1024 * 512):
pip-install-ygnynjtx\requests\requests\models.py, ln 753, in generate
requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal publish --organization {} --feed {} -n {} -v {} --path {}`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.66 *

Extensions:
azure-devops 0.10.0

```

**Comment by atbagga** [comment]
@nayanshah  Copied the issue to azure-devops extension repo. Please follow the above linked issue for updates. 

I will be closing this one since it is easier to track it in the extension repo.
