### ISSUE TITLE
Getting error submitting commands for front-end endpoint with dots. 

### ISSUE THREAD

**Issue by convergine** [Azure/azure-cli-extensions#1100]
Good day, 
We have a front-end front door endpoint which is a subdomain like  something.abc.com. There were no issues adding such front-end host through azure portal, however, when we tried executing few commands through azure cli - we get validation error stating that endpoint cannot have dots in the name:

validation error: Parameter 'frontend_endpoint_name' must conform to the following pattern: '^[a-zA-Z0-9]+(-*[a-zA-Z0-9])*$'.

Perhaps somebody stumbled upon the same issue and could assist with advice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 822f5f1f-85b1-6a84-6b30-14aa69c1b489
* Version Independent ID: 3f4f7cb1-c1ff-c40a-93c0-8c60137815e2
* Content: [az network front-door frontend-endpoint](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/frontend-endpoint?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door/frontend-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door/frontend-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@MyronFanQiu please take a look.

**Comment by MyronFanQiu** [comment]
@convergine I need check the reason behind the validation process.

**Comment by MyronFanQiu** [comment]
@convergine Hello. I checked the usage again. `--name` should be the name of endpoint instead of the `host-name`. You should use `az network front-door frontend-endpoint create` to create a endpoint and then enable the https for it.

**Comment by MyronFanQiu** [comment]
@convergine Hello. I think it's a usage question. If you don't have more question, I will close this issue in this week. 😄

**Comment by convergine** [comment]
@MyronFanQiu I don't. Please close it.
Thank you
