### ISSUE TITLE
Export IoT Device with Authorization Keys

### ISSUE THREAD

**Issue by JakubW88** [Azure/azure-cli-extensions#1119]
Hi,
I want to use this script "az iot hub device-identity export --bcu --hub-name  --ik {false, true}] [--resource-group] " 
but I don't know what it is exactly mean. 
It's mean that when will be exporting all iot device with device authorization keys to file then these keys will be remove in iot hub and moved to Storage ? Or they will be just only do cloned ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c92565-2490-7306-fa08-b16aa2a402a6
* Version Independent ID: 73f40753-0f05-7e45-ca7d-f0a9d2a276ce
* Content: [az iot hub device-identity](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub/device-identity?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-hub-device-identity-export)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub/device-identity.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub/device-identity.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jlian** [comment]
https://docs.microsoft.com/azure/iot-hub/iot-hub-bulk-identity-mgmt#export-devices

The keys will not be removed from your IoT Hub, they will be copied to a .txt file

**Comment by jlian** [comment]
I assume this answers your question? Please open again if not
