### ISSUE TITLE
'az boards query' supports only flat queries

### ISSUE THREAD

**Issue by ashamrai** [Azure/azure-cli-extensions#1120]
'az boards query' supports only flat queries. The tree and direct links are not supported. However, there is no any information on docs or command output. The command returns an empty answer for wiql with links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d535510f-f15c-3c79-c44d-34b7742a1544
* Version Independent ID: 334f9fc5-2811-f125-4faa-3fb90ec19559
* Content: [az boards](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards?view=azure-cli-latest#ext-azure-devops-az-boards-query)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/boards.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/boards.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@ashamrai I am opening a new issue in the azure-devops extension repo for better  tracking. Please follow the linked issue for further updates. 

Closing this issue in favor of tracking it in the specific extension repo.
