### ISSUE TITLE
attempting to copy image from east us to west india

### ISSUE THREAD

**Issue by greendx** [Azure/azure-cli-extensions#1135]
## Describe the bug

**Command Name**
`az image copy
Extension Name: image-copy-extension. Version: 0.2.2.`

**Errors:**
```
Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'UBwebvm1-image-20191208132623_os_disk_snapshot', '--resource-group', 'HAtestRG', '--source', '/subscriptions/772e1a43-6fac-4b49-b991-3022f3a1cb3e/resourceGroups/HAtestRG/providers/Microsoft.Compute/disks/UBwebvm1_disk1_8d8a4b4ac6164b12b2361795242dea7c', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image copy --source-resource-group {} --source-object-name {} --target-location {} --target-resource-group {} --cleanup`

## Environment Summary
```
Linux-4.15.0-1064-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

Extensions:
image-copy-extension 0.2.2

```

**Comment by tamirkamara** [comment]
@greendx can you run the command with the --debug flag and post the output so I could see where the detailed error?

**Comment by haroldrandom** [comment]
@qwordy Please take a look

**Comment by qwordy** [comment]
Did you delete the disk? You need to keep it. A image stores the reference of disk(s).

**Comment by tamirkamara** [comment]
This is likely the same as https://github.com/Azure/azure-cli-extensions/issues/1097
Please try version 76 of azure cli until a proper fix will be available for the extension.

**Comment by greendx** [comment]
Hi - The error message posted here was auto generated prompting me to post it here. I was trying to make a copy of the image via the cloud shell in azure portal. At this point I don't remember exactly what instructions I was following to attempt to make a copy and ended up copying my image via shared image gallery.

**Comment by qwordy** [comment]
image-copy 0.2.3 is released. It should fix this issue.
Azure/azure-cli-extensions#1211
