### ISSUE TITLE
What are the License values for Basic & Basic + Test Plans (Azure DevOps)

### ISSUE THREAD

**Issue by basyar02** [Azure/azure-cli-extensions#1136]
Based on the documentation for adding user here : https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/user?view=azure-cli-latest#ext-azure-devops-az-devops-user-add

The only accepted values being mentioned there are :
--license-type 
accepted values: advanced, earlyAdopter, express, professional, stakeholder

My Question is, what value should I put for 1) Basic and 2) Basic + Test Plans license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84e9b38-b9da-f69f-c9d7-b0c1a1e8683a
* Version Independent ID: bfd383ce-2ee6-64ec-8ff6-a4e8c88fd516
* Content: [az devops user](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/user?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/user.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/user.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ishitam8** [comment]
Hi @basyar02 ,

You can use following license types:
Basic- > express
Basic + Test Plans -> advanced

Let me know if you face any issues.

**Comment by atbagga** [comment]
Closing the issue since it has been inactive for long. Please feel free to raise a new on [here ](https://github.com/Azure/azure-devops-cli-extension/issues)if you have any issues.
