### ISSUE TITLE
AKS Create error when trying to attach acr and using aks-preview

### ISSUE THREAD

**Issue by GeeWee** [Azure/azure-cli-extensions#1139]
## Describe the bug
When running the command below, an error is simply returned. Turning the `aks-preview` extension off makes the command work as expected.

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.4.24.`

**Errors:**
`az aks create: error: 'Namespace' object has no attribute 'detach_acr'`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
- `az aks create --node-count 1 -g <MyResourceGroup> -n <MyAksName> --attach-acr <AcrName>`

## Expected Behavior
It creates an AKS instance with the correct permissions

## Environment Summary
```
Linux-5.3.13-300.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
Python 3.7.5
Shell: bash

azure-cli 2.0.75 *

Extensions:
aks-preview 0.4.24
azure-devops 0.15.0

```

**Comment by jluk** [comment]
@sauryadas can you take a look at this?

**Comment by sauryadas** [comment]
Correct. This command is not available in the CLI extension. It is only a part of the core CLI

**Comment by jluk** [comment]
Closing this ticket in favor of the AKS driven one opened here given they are the same issue. https://github.com/Azure/AKS/issues/1349
