### ISSUE TITLE
End user friendly clarification required for az aks get credentials command.

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/azure-cli-extensions#1146]
About --admin parameter it does work but a complex configuration has to be followed step by step to have it working. Basically if AD /RBAC has been configured properly the --admin will give you administrator access only if the integration with AD was done and configured correctly. 
see: 
https://docs.microsoft.com/en-us/azure/aks/azure-ad-rbac

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea52f6a-7414-7aa2-3708-7b802f243a16
* Version Independent ID: cf003f17-b9f7-04d4-89c2-770273b40533
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks?view=azure-cli-latest#ext-aks-preview-az-aks-get-credentials)
* Content Source: [latest/docs-ref-autogen/ext/aks-preview/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/aks-preview/aks.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by palma21** [comment]
Please open tickets on our official CLI
https://github.com/Azure/azure-cli 

Is this a CLI ask or a Documentation ask? 
I'll schedule something to be added to the doc below to clarify that point
https://docs.microsoft.com/en-us/azure/aks/control-kubeconfig-access
