### ISSUE TITLE
How to set daily cap?

### ISSUE THREAD

**Issue by evertonmc** [Azure/azure-cli-extensions#1154]
is there a cli command or param for this? https://github.com/Azure/azure-rest-api-specs/blob/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentFeaturesAndPricing_API.json#L37

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 333d37d2-61e2-0184-d253-157ee236439c
* Version Independent ID: 9b0e976f-3cb5-e813-9f33-e9cea7a8df8c
* Content: [az monitor app-insights component](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights/component?view=azure-cli-latest#ext-application-insights-az-monitor-app-insights-component-create)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/component.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/component.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@MyronFanQiu Please take a look

**Comment by MyronFanQiu** [comment]
@evertonmc Looks like we don't have these commands right now. We can put it into our planning.
