### ISSUE TITLE
Missing information on policy file format

### ISSUE THREAD

**Issue by ivd-git** [Azure/azure-cli-extensions#1155]
Missing information on what the policy file format should be when using the following command with --config or --policy-configuration:

https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/policy?view=azure-cli-latest#ext-azure-devops-az-repos-policy-create

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82177ae5-9144-27f7-47c0-5fa076636a69
* Version Independent ID: f89f4b34-692e-1b3f-0314-33ef141243c2
* Content: [az repos](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/repos.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/repos.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
Documentation is auto updated from the code. Seems like the documentation is not updated according to the latest code. 

If you run ```az repos policy create -h```  you will get the link to documentation on the file structure. 
Pasting the link here for your quick reference - https://aka.ms/azure-devops-cli-docs-policy-file

I will take care of following up on the documentation update. 
If you have any follow up questions or issues, please file an issue [here ](https://github.com/Azure/azure-devops-cli-extension/issues)for quick response.
