### ISSUE TITLE
It looks like the documentation may be out of date for volume creation

### ISSUE THREAD

**Issue by JonShelley** [Azure/azure-cli-extensions#1158]
This is the error that I receive when trying to create a volume. It is asking for --file-path but I don't see that as an option in the documentation above. After further review it looks like --creation-token was replaced with --file-path

az netappfiles volume create: error: the following arguments are required: --file-path
usage: az netappfiles volume create [-h] [--verbose] [--debug]
                                    [--output {json,jsonc,table,tsv,yaml,none}]
                                    [--query JMESPATH]
                                    [--subscription _SUBSCRIPTION]
                                    --account-name ACCOUNT_NAME --pool-name
                                    POOL_NAME --volume-name VOLUME_NAME
                                    --resource-group RESOURCE_GROUP_NAME
                                    --location LOCATION --file-path FILE_PATH
                                    --usage-threshold USAGE_THRESHOLD --vnet
                                    VNET [--subnet SUBNET]
                                    [--service-level {Standard,Premium,Ultra}]
                                    [--protocol-types [PROTOCOL_TYPES [PROTOCOL_TYPES ...]]]
                                    [--tags [TAGS [TAGS ...]]]
[azcatuser@bench-pbs HBv2-CUS]$ az --version
azure-cli                         2.0.78

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847fc003-40cc-3f88-7e10-7ac9622f0cac
* Version Independent ID: 7ba81f29-c4fb-7440-f94b-bbe2725c168f
* Content: [az netappfiles volume](https://docs.microsoft.com/en-us/cli/azure/ext/netappfiles-preview/netappfiles/volume?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/netappfiles-preview/netappfiles/volume.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/netappfiles-preview/netappfiles/volume.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@JonShelley Hello. I'm not sure whether this issue could be noticed by correct person. Since the label is not shown automatically. Could you please open a same issue in https://github.com/Azure/azure-cli/issues ?
