### ISSUE TITLE
Add ability to edit Front Door routing rules

### ISSUE THREAD

**Issue by bradcavanagh-ffs** [Azure/azure-cli-extensions#1159]
It is currently possible to create and delete Front Door routing rules via the az cli. I would like to be able to disable caching on a routing rule after it has been created, but to do that would require deleting the routing rule and then re-creating it with caching turned off.

The rationalization for this is that I am creating the Front Door routing rules using Terraform, which does not currently allow you to disable caching when you create them. To mitigate this, I was hoping to run the az cli after the fact to disable caching, but found that I cannot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc41d7b5-ab21-fe9b-2f2e-93ac02e5af86
* Version Independent ID: 67398425-8b96-f515-72af-22255ea1ae49
* Content: [az network front-door routing-rule](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/routing-rule?view=azure-cli-latest#ext-front-door-az-network-front-door-routing-rule-show)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@bradcavanagh-ffs Hello. There is a argument `--caching` in the `az network front-door routing-rule create` command which you can set to `Disabled`. But we cannot update an existed command. You should delete the old one and create a new one.

**Comment by MyronFanQiu** [comment]
@bradcavanagh-ffs There might be a tricky solution. 😄  You can try to create an existing routing rule. It should be able to update it.

**Comment by MyronFanQiu** [comment]
@bradcavanagh-ffs Hello. Do you have more questions?

**Comment by bradcavanagh-ffs** [comment]
> @bradcavanagh-ffs Hello. Do you have more questions?

Only an ETA for when I might be able to have an explicit 'edit' or 'modify' command. 'create' should really only be used to create a routing rule, in my opinion.
