### ISSUE TITLE
Commands seem to be modifying a different Routing table than the AZ Portal.

### ISSUE THREAD

**Issue by annerajb** [Azure/azure-cli-extensions#1169]
When you go into a virtual hub routing information the routes and tables shown there are different from the ones shown and returned by this command.
az network vhub route-table list 

This tables don't seem to affect the branches or the Vnets they are attached too.
Is this a preview command for future functionality that is not yet implemented in the portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1cb32b-6079-1c88-b236-6c0cd3e45ed9
* Version Independent ID: 2864c2f3-4739-729a-5827-ac3bb5e65f9e
* Content: [az network vhub route-table](https://docs.microsoft.com/en-us/cli/azure/ext/virtual-wan/network/vhub/route-table?view=azure-cli-latest#ext-virtual-wan-az-network-vhub-route-table-list)
* Content Source: [latest/docs-ref-autogen/ext/virtual-wan/network/vhub/route-table.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/virtual-wan/network/vhub/route-table.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bim-msft** [comment]
@MyronFanQiu Please take a look.

**Comment by MyronFanQiu** [comment]
@annerajb Hello. currently, routes and route-table are different commands right now. Based on my knowledge, it should call route-v2. I'm not sure about the portal. @dedhar Could you please take a look at this issue and answer the question?

**Comment by MyronFanQiu** [comment]
@annerajb Hi. Do you still have question about these commands? I'm not sure about portal, you can try original command `az network vhub route` to see whether it modify the same route table with Azure Portal or not. But from my perspective view, it should be different.

**Comment by annerajb** [comment]
I ended up opening a support request and finding out a different command
yes.

**Comment by MyronFanQiu** [comment]
@annerajb Good to know. 😄
