### ISSUE TITLE
List Virtual Directories in a Given Container

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-cli-extensions#1179]
### Extension name (the extension in question)
storage-preview

### Description of issue (in as much detail as possible)
Is it possible to list all the directories in a given blob container?

I can see alot of commands around 'az storage blob directory' but none of those commands would provide the ability to list all the folders within a container.

**Comment by bim-msft** [comment]
@Juliehzl Please take a look.

**Comment by yonzhan** [comment]
add to S167

**Comment by Juliehzl** [comment]
Hi @nofunatall, to utilize directory list command, you need to make sure your storage account with hierarchical namespace enabled. For more information, please refer to https://github.com/Azure/azure-cli-extensions/tree/master/src/storage-preview#adls-gen2-support.
