### ISSUE TITLE
tried and failed, escaping quot. marks

### ISSUE THREAD

**Issue by VaclavK** [Azure/azure-cli-extensions#1182]
Installed application-insights               0.1.1

tried to run basic queries e.g. 
C:\Windows\System32&gt;az monitor app-insights query --app tooling  --analytics-query 'exceptions'

but getting an error that does not provide much direction

PathNotFoundError - The requested path does not exist

the actual query I wanted to run was something like 

"exceptions
| where problemId == "Newtonsoft.Json.JsonReaderException at Newtonsoft.Json.JsonTextReader.ReadStringValue" 
| order by timestamp desc
| take 1"

how do you escape quot. marks? I tried few ways but nothing would seem to work - perhaps because the extension itself is unhealthy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bce0dc5-da82-717a-70cf-e392c05904a3
* Version Independent ID: a5cb6492-d731-0c98-7691-64d1d7a14a5c
* Content: [az monitor app-insights](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S165.

**Comment by jsntcy** [comment]
@MyronFanQiu , please help take a look.

**Comment by MyronFanQiu** [comment]
@VaclavK Hello. Which terminal are you using? Could you try this one? It should work in Powershell.
```
--analytics-query 'exceptions | where problemId == \"Newtonsoft.Json.JsonReaderException at Newtonsoft.Json.JsonTextReader.ReadStringValue\" | order by timestamp desc | take 1'
```

**Comment by VaclavK** [comment]
@MyronFanQiu thanks for this.. I tried powershell initially but due to the runtime failure would not see the result so could not verify

eentually ran it with --debug (why did I not do that in the first place..) and decyphered the message.. I was passing pure name of the AI instance - not fully qualified - so the message (PathNotFoundError - The requested path does not exist) turned out to be from the API call

passing guid fixes that so happy to report this now returns the result

so perhaps my suggestion would be to translate the raw error from the API call to something more descriptive
