### ISSUE TITLE
Hi, I find an issue in this page.

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [Azure/azure-cli-extensions#1210]
With a lot of testing in both Windows/Linux, I find an issue in the update command.
It's necessary using ' replace " to envelop the token. Please have a check.

az devops security permission update  --allow-bit 7 --namespace-id            52d39943-cb85-4d7f-8fa8-c6baac873819 --subject user@fabrikam.com            --token '$PROJECT:vstfs:///Classification/TeamProject/e479xxxx-2be8-xxxx-bb0b-3a0209cxxxx'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a283a450-7f6b-ceef-6fbd-f4e1d5129383
* Version Independent ID: 7361dfa6-28ed-1074-783e-baa233c3a308
* Content: [az devops security permission](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/security/permission?view=azure-cli-latest#ext-azure-devops-az-devops-security-permission-update)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/security/permission.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/security/permission.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ishitam8** [comment]
Hi @AlexChongMicrosoft ,

I am not sure what is the issue that you are facing.
Could you please give some more details,

Double quotes (") would be required if user is running commands in Powershell.
So, the single quotes vs double quotes is not specific to this command or Azure DevOps CLI, it's a general inconsistency observed across CLIs.

**Comment by AlexChongMicrosoft** [comment]
@ishitam8 Thank you for your attention. Actually, I worked with a customer for a long time on this issue. When using double quotes "", the string "$PROJECT:vstfs:///Classification/TeamProject/e479xxxx-2be8-xxxx-bb0b-3a0209cxxxx" would not be detected correctly. But when using single quotes, '$PROJECT:vstfs:///Classification/TeamProject/e479xxxx-2be8-xxxx-bb0b-3a0209cxxxx', it will be considered as a single string. 

Here I paste my screenshot in powershell. Hope it could help.
![double quotes](https://user-images.githubusercontent.com/45751478/72789542-edaf9e00-3c6e-11ea-9ae2-19ed04087177.jpg)
![single quote](https://user-images.githubusercontent.com/45751478/72789546-ef796180-3c6e-11ea-8960-0e4c32fbb9d9.jpg)

for you.

**Comment by ishitam8** [comment]
Sorry for the typo. I meant, **Single quotes** (') would be required if user is running commands in Powershell.

So, this is specific to powershell, since the command contains a dollar sign and we want to pass the dollar sign as a string, the required string needs to be wrapped around in single quotes.

Usually dollar signs are associated with variables and Powershell would try to resolve these, but if you use single quotes (') instead of double quotes ("), It prevents PowerShell expanding $ into a variable.

What i was trying to convey here is that this behavior is not speciifc to Azure DevOps CLI, these are common escape characters associated with the different command prompts.

**Comment by AlexChongMicrosoft** [comment]
@ishitam8 really appreciate your explanation. It makes sense.

Actually, with you explanation, I can understand its meaning. But for some of our users, when they follow this doc and use double quotes " in Linux, there is no notification of $ variable. It's what exactly makes them confused. And after a lot of testing, we found it should be a single quote here in both Linux bash and windows powershell.

I just raise my suggestion here and let you know the scenario. Double quotes " and single quote ' are the same in most of the scenarios, but here in my experience single quote ' is better because there will be less confusion when exactly following this doc. Or could you add a detailed explanation in this doc if possible?

It depends on you. Thank you very much for this good doc.

**Comment by ishitam8** [comment]
Thanks @AlexChongMicrosoft  , for the detailed explanation of why it would be common for linux users to get confused here.

@geverghe  , Do we need to change the doc to include single quotes.?
Which in -turn will create issues for the users who are working on Windows command prompt.
Can we have any guidelines related to this in our docs or help texts?

**Comment by geverghe** [comment]
@AlexChongMicrosoft, @ishitam8  - I believe this is an issue across azure cli and there is a page in azure cli docs that tackles this precise problem -https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues . I am dropping the devops extension tag. Call out to the Azure CLI team to include this page as part of official doc.

**Comment by pietergheysens** [comment]
> @ishitam8 Thank you for your attention. Actually, I worked with a customer for a long time on this issue. When using double quotes "", the string "$PROJECT:vstfs:///Classification/TeamProject/e479xxxx-2be8-xxxx-bb0b-3a0209cxxxx" would not be detected correctly. But when using single quotes, '$PROJECT:vstfs:///Classification/TeamProject/e479xxxx-2be8-xxxx-bb0b-3a0209cxxxx', it will be considered as a single string.
> 
> Here I paste my screenshot in powershell. Hope it could help.
> ![double quotes](https://user-images.githubusercontent.com/45751478/72789542-edaf9e00-3c6e-11ea-9ae2-19ed04087177.jpg)
> ![single quote](https://user-images.githubusercontent.com/45751478/72789546-ef796180-3c6e-11ea-8960-0e4c32fbb9d9.jpg)
> 
> for you.

The double quotes for passing the token have also blocked me for quite some time. Due to the fact that the command returns a successful result, I didn't think about this possibility of a quoting issue. It would be nice if the documentation clearly mentions the quoting issue for the token argument and maybe even better: the command should return a failure when passing an invalid token argument with double quotes.

**Comment by RakeshMohanMSFT** [comment]
Could be fixed by this PR https://github.com/Azure/azure-devops-cli-extension/pull/1333

**Comment by RakeshMohanMSFT** [comment]
This PR https://github.com/Azure/azure-devops-cli-extension/pull/1333 will fix the issue
