### ISSUE TITLE
[X-Post from azure-cli] az commands can trigger 429 / "too many requests" failures and provides no recourse for recovery. 

### ISSUE THREAD

**Issue by isaacrlevin** [Azure/azure-cli-extensions#1222]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az aks preview

### Description of issue (in as much detail as possible)
https://github.com/Azure/azure-cli/issues/11891
-----

**Comment by jluk** [comment]
This is not specific to the cli extension, please avoid duplicating issues on purpose it will not help resolution faster. The AKS team is aware of the service throttles and the CLI team has already been pinged on the other issue. Closing this as duplicate.
