### ISSUE TITLE
Duleep

### ISSUE THREAD

**Issue by dduleep** [Azure/azure-cli-extensions#1223]
`az pipelines variable-group variable create --group-id` in not clear what is --group-id and how its usecase in group variable.

---
#### Detalji dokumenta

⚠ *Ne uređujte ovu sekciju. Ona je neophodna za povezivanje problema slijedom docs.microsoft.com ➟ GitHub.*

* ID: fc3b2e1e-81e2-75fa-12f2-dc742bac7301
* Version Independent ID: 5ea78738-cbcb-139c-1ce0-7cfbb42c3a08
* Content: [az pipelines variable-group variable](https://docs.microsoft.com/bs-latn-ba/cli/azure/pipelines/variable-group/variable?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/pipelines/variable-group/variable.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/pipelines/variable-group/variable.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
--group-id --> Id of the variable group.
If you list variable groups ```az pipelines variable-group list``` you will get all the variable groups with the ids. The command ```az pipelines variable-group variable create --group-id``` will then require the group id as input to add a variable in that variable group.

@dduleep  Can you elaborate on the issue or share any suggestions to the help text you have which would have made it clearer.

**Comment by yonzhan** [comment]
devops

**Comment by geverghe** [comment]
@dduleep - Closing this for now. Feel free to open an issue in https://github.com/Azure/azure-devops-cli-extension/issues in case the explanation does not suffice.
