### ISSUE TITLE
What does `--squash` do?

### ISSUE THREAD

**Issue by danebou** [Azure/azure-cli-extensions#1224]
`--squash` doesn't appear to do anything. I would expect it to automatically update the merge type to squash commit just before completing the PR (when the complete PR button is pressed in the DevOps PR view)., but this doesn't appear to be the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3324c35b-f381-8db4-b168-6f73e20c1f3e
* Version Independent ID: 7a3e8656-7741-8365-e56c-44056f034b31
* Content: [az repos pr](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/pr?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/repos/pr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/repos/pr.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ashamrai** [comment]
That`s not in the merge logic of PRs ([Review code with pull requests](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops)). If you want use the squash merge type, you can [Enforce a merge strategy](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#enforce-a-merge-strategy) in the branch policies. Additionally, we can use the squash merge: 

- while completing a PR:

`az repos pr update --id <PR_ID> --status completed --squash true`

- to set the auto-complete:

`az repos pr update --id <PR_ID> --auto-complete true --squash true`

**Comment by atbagga** [comment]
@ashamrai  Thanks for chipping in.
@danebou  Hope that helps.. Also do keep in mind the known [issue](https://github.com/Azure/azure-devops-cli-extension/issues/546) in the command.

**Comment by atbagga** [comment]
If you still have some concern, please raise an issue [here](https://github.com/Azure/azure-devops-cli-extension/issues).
