### ISSUE TITLE
Missing example of referencing secret from KeyVault

### ISSUE THREAD

**Issue by djsowa** [Azure/azure-cli-extensions#1225]
Hi.

Do You have any example of adding reference to KeyVault using CLI ?

M.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb3ec9f2-e5cd-d79e-ebd7-8d726f3d90df
* Version Independent ID: 287f4d1d-00c5-1686-8aa4-e198ff196a05
* Content: [az appconfig kv](https://docs.microsoft.com/en-us/cli/azure/ext/appconfig/appconfig/kv?view=azure-cli-latest#ext-appconfig-az-appconfig-kv-set)
* Content Source: [latest/docs-ref-autogen/ext/appconfig/appconfig/kv.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/appconfig/appconfig/kv.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
https://github.com/Azure/azure-cli/issues/new/choose @djsowa Hello. Could you open an issue in our main repo? `az appconfig` is not an extension.

**Comment by MyronFanQiu** [comment]
@bim-msft Hello. Sorry I cannot find the label for appconfig in this repo. Add you as assignee for short.

**Comment by MyronFanQiu** [comment]
@djsowa I cannot add correct label and assign the corresponding people in this repo.

**Comment by djsowa** [comment]
This is how to add KeyVault reference in App Config:
`az appconfig kv set -n APP_CONFIG_NAME --key KEY_NAME --label LABEL_VALUE --value '{ uri = "https://KEY_VAULT_URL/SecretName\SECRET_VERSION" }' --yes --content-type "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8"`

**Comment by djsowa** [comment]
Can be closed. Documentation updated with latest command for KeyVault secret referencing.
