### ISSUE TITLE
Unable to create multiple rules under a single collection.

### ISSUE THREAD

**Issue by frehnejc** [Azure/azure-cli-extensions#1226]
There doesn't seem to be functionality to create multiple rules under a single collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a90f7721-6e37-012e-a118-277d5c113f65
* Version Independent ID: c89a7d07-fc9d-748c-d562-2ec9f0295e15
* Content: [az network firewall network-rule](https://docs.microsoft.com/en-us/cli/azure/ext/azure-firewall/network/firewall/network-rule?view=azure-cli-latest#ext-azure-firewall-az-network-firewall-network-rule-create)
* Content Source: [latest/docs-ref-autogen/ext/azure-firewall/network/firewall/network-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-firewall/network/firewall/network-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@MyronFanQiu please take a look.

**Comment by MyronFanQiu** [comment]
@frehnejc Sorry for the delay. The rules must be the same types(nat rule/network rule/app rule). I just had a test and it worked.

**Comment by yonzhan** [comment]
add to S168

**Comment by MyronFanQiu** [comment]
@frehnejc I added more tests. If you still encounter such problem, could you give us more details about it?

**Comment by MyronFanQiu** [comment]
Close this one due to no response. Feel free to open new issue if you have any more question.

**Comment by vbrinza** [comment]
I can confirm the behaviour.
"az network firewall network-rule create --resource-group test-fw-rg --firewall-name test-fw --collection-name AKS_Global_Required --action allow --priority 104 --name aks-global-required-22-9000 --source-addresses '*' --protocols TCP --destination-ports 22 9000 --destination-fqdns test-k8s1-westeurope-blalbla.hcp.westeurope.azmk8s.io test-k8s2-westeurope-blalbla.hcp.westeurope.azmk8s.io" -

this one worked

Next one coming right after is giving the error:

"az network firewall network-rule create --resource-group test-fw-rg --firewall-name test-fw --collection-name AKS_Global_Required --action allow --priority 105 --name aks-global-required-1194 --source-addresses '*' --protocols UDP --destination-ports 1194 --destination-fqdns test-k8s1-westeurope-blalbla.hcp.westeurope.azmk8s.io test-k8s2-westeurope-blalbla.hcp.westeurope.azmk8s.io
Rule collection 'AKS_Global_Required' already exists.
usage error: --collection-name EXISTING_NAME | --collection-name NEW_NAME --priority INT --action ACTION"

**Comment by MyronFanQiu** [comment]
> I can confirm the behaviour.
> "az network firewall network-rule create --resource-group test-fw-rg --firewall-name test-fw --collection-name AKS_Global_Required --action allow --priority 104 --name aks-global-required-22-9000 --source-addresses '*' --protocols TCP --destination-ports 22 9000 --destination-fqdns test-k8s1-westeurope-blalbla.hcp.westeurope.azmk8s.io test-k8s2-westeurope-blalbla.hcp.westeurope.azmk8s.io" -
> 
> this one worked
> 
> Next one coming right after is giving the error:
> 
> "az network firewall network-rule create --resource-group test-fw-rg --firewall-name test-fw --collection-name AKS_Global_Required --action allow --priority 105 --name aks-global-required-1194 --source-addresses '*' --protocols UDP --destination-ports 1194 --destination-fqdns test-k8s1-westeurope-blalbla.hcp.westeurope.azmk8s.io test-k8s2-westeurope-blalbla.hcp.westeurope.azmk8s.io
> Rule collection 'AKS_Global_Required' already exists.
> usage error: --collection-name EXISTING_NAME | --collection-name NEW_NAME --priority INT --action ACTION"
Hi. Based on the usage error, the second time, you should not input `--action` and `--priority` again if `--collection-name` has already existed.

**Comment by vbrinza** [comment]
I run:
az network firewall nat-rule create --resource-group rg --firewall-name fw --collection-name OPEN_TR_MGR_HEALTH_CHK --priority 200 --action dnat --name dnat-to-srvc-sftp --protocol TCP --source-addresses 40.68.30.66/32 --destination-addresses PIP --destination-port 22 --translated-address 192.168.0.10 --translated-port 22

I get:
Rule collection 'OPEN_TR_MGR_HEALTH_CHK' already exists.
usage error: --collection-name EXISTING_NAME | --collection-name NEW_NAME --priority INT --action ACTION

I run:
az network firewall nat-rule create --resource-group rg --firewall-name fw --collection-name OPEN_TR_MGR_HEALTH_CHK --name dnat-to-srvc-sftp --protocol TCP --source-addresses 40.68.30.66/32  --destination-addresses PIP --destination-port 22 --translated-address 192.168.0.10 --translated-port 22

I get:
AzureFirewallRuleCollection /subscriptions/asdad/resourceGroups/rg/providers/Microsoft.Network/azureFirewalls/fw/natRuleCollections/OPEN_TR_MGR_HEALTH_CHK contains at least two rules with the same name (dnat-to-srvc-sftp).

Isn't the above "you should not input --action and --priority again if --collection-name has already existed." working in case of dnat?
If not, what should I do to make it work? :)

**Comment by MyronFanQiu** [comment]
Your second try is correct. The error message has changed. It told you there is already a rule called `dnat-to-srvc-sftp` in the `OPEN_TR_MGR_HEALTH_CHK`. So for the second command, you should choose another name. For example
```
az network firewall nat-rule create --resource-group rg --firewall-name fw --collection-name OPEN_TR_MGR_HEALTH_CHK --name dnat-to-srvc-sftp-2 --protocol TCP --source-addresses 40.68.30.66/32 --destination-addresses PIP --destination-port 22 --translated-address 192.168.0.10 --translated-port 22
```

**Comment by vbrinza** [comment]
I am trying to update the existing rule with different source addresses.
I do not want to create a new rule just for that.
I thought that I can use the same non-obvious approach as you suggested for
the 'regular' network rules.
Why is the 'update' via the same approach working in case of 'az network
firewall network-rule create' rules and doesn't in case of 'az network
firewall network-rule create'?
When do you plan to have an obvious way of doing changes, like for ex 'az
network firewall network-rule update' and 'az network firewall network-rule
update'?
Thanks.

**Comment by MyronFanQiu** [comment]
@vbrinza Is it ok to raise a new issue for your feature request? Currently, the solution is to remove the old rule and add new one.

**Comment by vbrinza** [comment]
To me it sounds for of a problem then a feature request, but yes you can
raise it as required by your internal process.
