### ISSUE TITLE
suggestion: add hint on pages about extension command to install extension 

### ISSUE THREAD

**Issue by NoNameProvided** [Azure/azure-cli-extensions#1227]
When coming from Google search result there is no indication on the pages describing extension commands about the installation requirement. So when a user tries to run the commands the CLI will throw a command not found error. 

```
az postgres: 'show-connection-string' is not in the 'az postgres' command group. See 'az postgres --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
``` 

The CLI error itself advises to check if the command is part of an extension or not, but since I was browsing the same site I browse for the regular commands I  thought this command is part of the core CLI. 

So I would suggest adding an infobox  on top of the page with a text something like: 
&gt; This command is part of the XY extension. Please make sure you install it before using it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5fd0414-755e-459e-85bc-ef3fcd31432b
* Version Independent ID: ad239037-3b15-1acf-d08d-fe20d31110c6
* Content: [az postgres](https://docs.microsoft.com/en-us/cli/azure/ext/db-up/postgres?view=azure-cli-latest#ext-db-up-az-postgres-show-connection-string)
* Content Source: [latest/docs-ref-autogen/ext/db-up/postgres.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/db-up/postgres.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rachel-msft** [comment]
Hi @NoNameProvided. Thank you. We'll review your feedback and get back.

**Comment by rachel-msft** [comment]
This falls under the db-up extension's commands . The page is under the Extension Refernces section of the documentation. The command itself uses the 'az postgres' naming scheme because it is an extension for PostgreSQL.

![image](https://user-images.githubusercontent.com/32173602/75299001-c8233080-57e8-11ea-9790-3b3430d2f0b5.png)

Our apologies for any confusion.

**Comment by yonzhan** [comment]
@rachel-msft your team owns this command, right?

**Comment by rachel-msft** [comment]
No, @achandmsft's team owns this
