### ISSUE TITLE
Error: Before you can run Azure DevOps commands, you need to run the login command

### ISSUE THREAD

**Issue by Jyoti492** [Azure/azure-cli-extensions#1230]
## Extension name (the extension in question)
azure-devops

### Description of issue (in as much detail as possible)
Even If I am setting the PAT token as env variable as below. I am facing an error that the pipeline asks to login.

Pipeline :
- bash:
  displayName: 'Set PAT token as env variable'
  env:
    AZURE_DEVOPS_EXT_PAT: $(pat_token)

- task: AzureCLI@1
  displayName: 'Create Docker Registry service connection'
  inputs:
    azureSubscription: 'mcp01-d-rg'
    scriptLocation: inlineScript
    inlineScript: |
      az extension add --name azure-devops
      az devops service-endpoint create --service-endpoint-configuration '$(System.ArtifactsDirectory)\jsonconfig\docker-registry.json' --detect true

Error:
ERROR: Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.

While the microsoft page(https://docs.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=unix)  says 'Now run any command without having to sign in explicitly. Each command will try to use the PAT in the environment variable for authentication'
-----

**Comment by atbagga** [comment]
Your bash task is not setting up the env variable persistently. It is an independent task and when you set the env variable in yaml like that it only gives access to the env variable to that individual task.

You can add the env variable declaration to the AzureCLI task and that should work. 
```
env:
AZURE_DEVOPS_EXT_PAT: $(pat_token)
```

For alternate way to do it.. checkout [this ](https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops)for help on how to run devops login in the pipeline.

**Comment by atbagga** [comment]
@Jyoti492 The above comment should help resolve the issue. If you still face an issue feel free to file new one [here](https://github.com/Azure/azure-devops-cli-extension/issues) for quicker turn around.
