### ISSUE TITLE
There is no option to create a pull request from a forked repository

### ISSUE THREAD

**Issue by ashamrai** [Azure/azure-cli-extensions#1233]
It is general situation when we have to create a new pull request from a forked repo. However, no any keys (like `--source-repo` or `--forked-repo`) are present in the `pr create` command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3324c35b-f381-8db4-b168-6f73e20c1f3e
* Version Independent ID: 7a3e8656-7741-8365-e56c-44056f034b31
* Content: [az repos pr](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/pr?view=azure-cli-latest#ext-azure-devops-az-repos-pr-create)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/repos/pr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/repos/pr.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@ashamrai This is already in the backlog - https://github.com/Azure/azure-devops-cli-extension/issues/743. Do vote for the issue there to get it prioritized sooner. 

You can also checkout the invoke command and write a small utility script to use the rest api in the meanwhile to achieve this from CLI.
