### ISSUE TITLE
`front-door backend-pool backend remove` negative indexes allowed/mishandled

### ISSUE THREAD

**Issue by despian** [Azure/azure-cli-extensions#1234]
### Extension name (the extension in question)

front-door

### Description of issue (in as much detail as possible)

Negative integers passed to the `--index` parameter of the `front-door backend-pool backend remove` command are permitted and remove the element `length - index - 1`

This could be quite bad since I guess a common use case would be to use `indexOf` to get an index and that returns a `-1` if not found. Which could result in an item being incorrectly removed if the result isn't tested before use.

E.g. given the following backends

```
[0]: backend1
[1]: backend2
[2]: backend3
[3]: backend4
```
passing in `-1` will result in `backend3` at position `[2]` being removed.

```
az network front-door backend-pool backend remove -g <RG> -f <FD> --pool-name <POOL> --index -1
```

-----

This seems to be an issue with the use of the `pop` function which allows removing elements from the rear of the array when negative values are passed in. Along with the added complication that the `backend remove` command expects indexes starting from 1.

https://github.com/Azure/azure-cli-extensions/blob/862c3659a15a34ff4e0a5570c7d2aaf7013ef39f/src/front-door/azext_front_door/custom.py#L428

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
add to S168
