### ISSUE TITLE
Error: az aks get-credentials

### ISSUE THREAD

**Issue by lzredes** [Azure/azure-cli-extensions#1236]
## Describe the bug

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.4.27.`

**Errors:**
```
'clusters'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 2236, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 2180, in _handle_merge
    if existing[key] is None:
KeyError: 'clusters'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Linux-5.3.0-29-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77 *

Extensions:
aks-preview 0.4.27

```

**Comment by jluk** [comment]
@lzredes I'm not able to reproduce this with the same preview ext and latest CLI build. Could you please try upgrading the CLI version and re-running the get-creds cmd?

**Comment by lzredes** [comment]
Hi, jluk


## Describe the bug

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.4.27.`

**Errors:**
```
'clusters'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 2236, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 2180, in _handle_merge
    if existing[key] is None:
KeyError: 'clusters'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Expected Behavior

## Environment Summary
```
Linux-5.3.0-29-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.80

Extensions:
aks-preview 0.4.27

```
## Additional Context

**Comment by Jen7714** [comment]
Hello! Please try again with the latest Azure CLI version. Feel free to reopen an issue if it still doesn't work.

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
