### ISSUE TITLE
Azdev publish extension error

### ISSUE THREAD

**Issue by gtracer** [Azure/azure-cli-extensions#1244]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Aks-preview

### Description of issue (in as much detail as possible)

##Attempting to use azdev to publish a new extension via the command:

`azdev extension publish aks-preview --storage-account mysa --storage-subscription mysub --storage-container mycontainer --update-index`

##Seeing the following error

```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/ganeshathirumurthi/go/src/github.com/env/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/ganeshathirumurthi/go/src/github.com/env/lib/python3.7/site-packages/knack/invocation.py", line 208, in execute
    cmd_result = parsed_args.func(params)
  File "/Users/ganeshathirumurthi/go/src/github.com/env/lib/python3.7/site-packages/knack/commands.py", line 139, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/ganeshathirumurthi/go/src/github.com/env/lib/python3.7/site-packages/knack/commands.py", line 246, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/Users/ganeshathirumurthi/go/src/github.com/env/lib/python3.7/site-packages/azdev/operations/extensions/__init__.py", line 296, in publish_extensions
    exists = json.loads(cmd(command).result)['exists']
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## I have tried:
1. Updating azdev by installing the latest version here: https://pypi.org/project/azdev/
2. Re-setting up my environment via `azdev setup`
3. Ensured my versions are all up to date - see below
4. Tried running from master branch

My versions:
`azure-cli                         2.0.81

command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
alias                              0.5.2
azure-firewall                     0.1.6
aks-preview                       0.4.27 (dev) .../azure-cli-extensions/src/aks-preview`

Any guidance would be appreciated 

-----

**Comment by yonzhan** [comment]
@haroldrandom please take a look at this.

**Comment by gtracer** [comment]
@haroldrandom I will be online for another 1.5 hours - do you have a moment to look at this together?

**Comment by haroldrandom** [comment]
@gtracer My alias is jianhui. Feel free to ping me at Teams.

**Comment by haroldrandom** [comment]
@gtracer You may encounter a problem that don't have priviledge to upload. We could help you to do it if you have made sure you command's style, linter and PR is merge. 
I will help you upload and update index.json

**Comment by haroldrandom** [comment]
Another guess is based on what you gave above,
```
File "/Users/ganeshathirumurthi/go/src/github.com/env/lib/python3.7/site-packages/azdev/operations/extensions/__init__.py", line 296, in publish_extensions
    exists = json.loads(cmd(command).result)['exists']
```

Basically, I guess is there already a wheel file with same name in you conntainer?

**Comment by gtracer** [comment]
@haroldrandom I have owner privilege on the sub and container and have previously had no problem pushing so although it is a good hypothesis, unfortunately I don't think it is the case here

Re: an existing whl. Looking at the code in that file it does seem to be that way but it doesn't seem to line up with these signals:
a) In the past whenever I push a whl with the same version # it just overrides the existing one -- we do this during development when we get PR feedback. Is this existing check new?
b) I also confirmed that  it isn't the case by setting the version # to a much larger number than the current (4.31) in `setup.py` and it still gave me the same error 
c) If I force it with `--yes` it uploads properly and I can see this entry aks_preview-0.4.31-py2.py3-none-any.whl | 2/5/2020, 9:06:08 AM in our container but then it fails becaues the whl doesn't have https in front (isn't a valid link I guess):  
if not extension.endswith('.whl') or not extension.startswith('https:'):
            raise CLIError('usage error: only URL to a WHL file currently supported.')


What do you think are next steps for investigating? Do you own any extensions that you can try and repro on with the same setup? I am OOF until Tuesday but will try and check back each evening to respond as the investigation continues. 

CC: @jluk

**Comment by haroldrandom** [comment]
Thanks for the feedback.

For a),
> a) In the past whenever I push a whl with the same version # it just overrides the existing one -- we do this during development when we get PR feedback. Is this existing check new?
We didn't make changes on this part.

For c), `azdev extension publish` is bugy, it has many unreasonable checks which is hard to reproduce.

As a workaround and you have owner priviledge on this container,
  1. I suggest you upload wheel file manually via `azdev extension build` to build wheel file locally, and upload to your container.
  2. Update index.json via `azdev extension update-index`, and commit them.
That's basically what `azdev extension publish` done, I just publish an extension in this way.

**Comment by gtracer** [comment]
@haroldrandom thanks - building, uploading and updating the index separately worked. Appreciate the guidance.
