### ISSUE TITLE
Support new RP Alertsmanagement

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli-extensions#1247]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Alertsmanagement

### Description of issue (in as much detail as possible)
Please support new RP Alertsmanagement in Azure CLI

-----

**Comment by yungezz** [comment]
moved to main repo, close this one.
