### ISSUE TITLE
How do you specify that an Enrollment Group is for IoT Edge devices?

### ISSUE THREAD

**Issue by grizzljt** [Azure/azure-cli-extensions#1248]
In the GUI, there is a toggle to specify that the group is for IoT Edge devices.  How can that be toggled through the Az CLI ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a3283c-e190-c2a7-fc50-41d9ba6a8d2e
* Version Independent ID: 473e67d0-b090-c5c2-285c-7c194b3af844
* Content: [az iot dps enrollment-group](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/dps/enrollment-group?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-dps-enrollment-group-create)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/dps/enrollment-group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/dps/enrollment-group.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
@grizzljt , Thanks for reporting, we are looking at it.

**Comment by grizzljt** [comment]
When I trace the API via Fiddler, I see the following:
POST: https://main.iothub.ext.azure.com/api/dataPlane/put
```
...
"capabilities":{"iotEdge":true}
...
```

But I have not found a way to replicate that via az cli.  Is this possible?

**Comment by arrownj** [comment]
Hi @digimaun , could you please help with this ?

**Comment by digimaun** [comment]
This issue is on our radar. We will release a new version of the extension to resolve this problem as soon as we can.

**Comment by digimaun** [comment]
We've released a new version of the IoT extension that covers this capability. Please [go here](https://github.com/Azure/azure-iot-cli-extension/issues/131#issuecomment-592266064) for more info. One missing element is waiting on the [extension index PR](https://github.com/Azure/azure-cli-extensions/pull/1315).

**Comment by digimaun** [comment]
#close

**Comment by jlian** [comment]
Thanks!

**Comment by jlian** [comment]
FYI @digimaun I think the magic word is `#please-close`

**Comment by digimaun** [comment]
@jlian  thanks for clarifying that.
