### ISSUE TITLE
Issues of image-copy: can't find command; update help

### ISSUE THREAD

**Issue by KanikaGMS** [Azure/azure-cli-extensions#1254]
I had faced 2 issues in running this on my cli 
1. The copy parameter is not available even after upgrade. I checked command "az image --help":
Group
    az image : Manage custom virtual machine images.

Commands:
    create : Create a custom Virtual Machine Image from managed disks or snapshots.
    delete : Deletes an Image.
    list   : List custom VM images.
    show   : Gets an image.

2. Please add a comment that when using this command we need to have the disk from which the image is created

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1806a2fb-e007-03d5-ac2d-277da130d29b
* Version Independent ID: f8583594-0ed8-ff4d-33a8-2f7c9f41c288
* Content: [az image](https://docs.microsoft.com/en-us/cli/azure/ext/image-copy-extension/image?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/image-copy-extension/image.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/image-copy-extension/image.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
thanks for reporting the issue. we'll investigate it.

**Comment by qwordy** [comment]
1. Have you installed image-copy extension? It's not installed by default. Users need to install it manually. `az extension add -n image-copy`
2. Yes. I'll add it. I also met this problem once a time.

**Comment by qwordy** [comment]
Quote from doc team,
> This logic did not change for quite a long time, which was designed to hide long summary long time ago(2 years ago) as many long summary was empty or duplicate as short summary at that time.

**Comment by qwordy** [comment]
I have updated help of image-copy.
