### ISSUE TITLE
Description is not exportable currently

### ISSUE THREAD

**Issue by aeghbal1** [Azure/azure-cli-extensions#1256]
Seems like the description is currently not exportable.  Can you please include the description as well?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb3ec9f2-e5cd-d79e-ebd7-8d726f3d90df
* Version Independent ID: 287f4d1d-00c5-1686-8aa4-e198ff196a05
* Content: [az appconfig kv](https://docs.microsoft.com/en-us/cli/azure/ext/appconfig/appconfig/kv?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/appconfig/appconfig/kv.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/appconfig/appconfig/kv.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
HI @shenmuxiaosen could you pls help to look? Thanks.

**Comment by shenmuxiaosen** [comment]
Are we trying to generate doc for App Configuration CLI? If so, I am wondering should be based on the official CLI repo https://github.com/Azure/azure-cli instead of the CLI extension? As we don't ship extension any more and we have already merged to main CLI.

**Comment by yonzhan** [comment]
Maybe we can close this one and create a new issue in azure-cli main repo?

**Comment by yungezz** [comment]
@shenmuxiaosen @yonzhan  it's ok for me to move the issue to CLI main repo, as long as context there.

**Comment by yonzhan** [comment]
@aeghbal1 could you please help close this issue and create a similar on in CLI main repo?

**Comment by aeghbal1** [comment]
Can you please send me the link where I need to

**Comment by aeghbal1** [comment]
another issue is created for this:
https://github.com/Azure/azure-cli/issues/12238
