### ISSUE TITLE
storage blob directory list fails when using --num-results

### ISSUE THREAD

**Issue by ShawnMcGough** [Azure/azure-cli-extensions#1257]
**Command Name**
`az storage blob directory list
Extension Name: storage-preview. Version: 0.2.10.`

**Errors:**
```
unsupported operand type(s) for -: 'str' and 'int'
Traceback (most recent call last):
pip-install-1o1fsnhi\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 608, in execute
cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
cli\core\commands\__init__.py, ln 657, in _run_job
cliextensions\storage-preview\azext_storage_preview\__init__.py, ln 244, in new_handler
    handler(ex)
...
    return list(result)
azure_adls_storage_preview\v2019_02_02_preview\common\models.py, ln 89, in __iter__
    max_results = max_results - len(self.items)
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob directory list -c {} -d {} --account-name {} --num-results {}`

## Expected Behavior
The results are returned without error.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.81

Extensions:
azure-devops 0.12.0
resource-graph 1.0.0
storage-preview 0.2.10

```
## Additional Context
The command works fine when `--num-results` is omitted.

**Comment by ShawnMcGough** [comment]
After investigation, this is a result of the following line:
https://github.com/Azure/azure-cli-extensions/blob/3e79944b0de8e8677f626065a0e203ba8a1ebdc8/src/storage-preview/azext_storage_preview/vendored_sdks/azure_adls_storage_preview/v2019_02_02_preview/common/models.py#L87

should be cast to an int:
`            max_results = int(self._list_kwargs.get('max_results'))`

**Comment by yonzhan** [comment]
add to S169

**Comment by zhoxing-ms** [comment]
@ShawnMcGough Do you have `--marker` in your parameters? I found that after adding `--marker`, the command will go through this logic and report the same error. Please kindly show your specific parameters if it is convenient~

**Comment by Juliehzl** [comment]
Hi @ShawnMcGough, for blob directory list, are you using ADL Gen2 account? If yes, you can use `az storage fs directory list`to list all directories and `az storage fs file list` to list all files and directories.
