### ISSUE TITLE
aks-preview future plans 

### ISSUE THREAD

**Issue by tscully49** [Azure/azure-cli-extensions#1260]
### Extension name (the extension in question)

aks-preview

### Description of the issue (in as much detail as possible)

Moreso a question of if there are plans for this extension to be out of preview.  We had to install this extension to create aks clusters with a custom nodeResourceGroup name.  We are a little hesitant to be using a CLI extension that is in preview and wanted to know if there were plans for this extension to be adopted into the azure CLI codebase.  Thank you!

-----

**Comment by arrownj** [comment]
@tscully49 , thanks for reporting, we are looking at this.

**Comment by TomGeske** [comment]
are you asking about [thise one](https://docs.microsoft.com/en-us/azure/aks/faq#can-i-provide-my-own-name-for-the-aks-node-resource-group)? 

In general aks-preview extension is used to ship preview features of our CLI experience. Once a feature graduates we move functionality from aks-preview into cli core.

@jluk may comment on "custom naming of AKS node resource group"

**Comment by jluk** [comment]
Yes, we will move the custom rg name commands into the core CLI build in the coming month. That's been delayed a bit but we will get it closed.

If this is strictly about that command, we can rename this issue to that scope and use this as the tracker.

**Comment by navba-MSFT** [comment]
@tscully49 Apologies for the late reply. I hope you had a chance to look at the above comments. This issue is open for quite sometime. Please let us know if you have any further questions or need any further assistance on this issue. Awaiting your reply.
