### ISSUE TITLE
az monitor app-insights component show --subscription is choosing a different subscription

### ISSUE THREAD

**Issue by Tyriar** [Azure/azure-cli-extensions#1269]
### Extension name (the extension in question)

application-insights

### Description of issue (in as much detail as possible)

When I run this:

```ps
$vSubscription = "abc"
az monitor app-insights component show --subscription $vSubscription
```

It returns results for a completely different subscription. I can give more details about the subscriptions in question if you reach out on Teams.

This is blocking me from using the extension to pull the instrumentation key via the CLI.

**Comment by arrownj** [comment]
Hi @MyronFanQiu , could you please help take a look at it ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by MyronFanQiu** [comment]
ref https://github.com/Azure/azure-rest-api-specs/issues/8501
