### ISSUE TITLE
The hack is not completing the key creation process

### ISSUE THREAD

**Issue by bsletten** [Azure/azure-cli-extensions#1271]
## Describe the bug

**Command Name**
`az hack create
Extension Name: hack. Version: 0.4.1.`

**Errors:**
```
Unable to get API version for type 'None' in profile 'latest'
Traceback (most recent call last):
cli/core/profiles/_shared.py, ln 296, in get_api_version
    api_version = AZURE_API_PROFILES[api_profile][resource_type]
KeyError: None

...

cli/core/profiles/_shared.py, ln 303, in get_api_version
    raise APIVersionException(resource_type, api_profile)
azure.cli.core.profiles._shared.APIVersionException: Unable to get API version for type 'None' in profile 'latest'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az hack create --name {} --runtime {} --location {} --ai --output {}`
az hack create --name reactor --runtime python --location northcentralus --ai --output yaml

## Environment Summary
```
macOS-10.15.2-x86_64-i386-64bit
Python 3.8.1
Shell: bash

azure-cli 2.0.81

Extensions:
hack 0.4.1

```

**Comment by arrownj** [comment]
Hi @GeekTrainer , could you please help take a look at this ?

**Comment by GeekTrainer** [comment]
Examining this now. Thanks for reporting @bsletten

**Comment by GeekTrainer** [comment]
PR #1309 will resolve this once merged

**Comment by lilyjma** [comment]
Hi, since the problem in issue will be addressed by the PR, I'm closing it now. Thanks!
