### ISSUE TITLE
More agent and pool verbs (?)

### ISSUE THREAD

**Issue by timmkrause** [Azure/azure-cli-extensions#1273]
What do you think about adding the following commands?
Is it worth the effort?

`az pipelines agent delete --pool-id --agent-id`
`az pipelines agent enable --pool-id --agent-id`
`az pipelines agent disable --pool-id --agent-id`
`az pipelines pool delete --pool-id`
`az pipelines pool create --name`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 537b1871-1f6d-737e-d942-332434cb9926
* Version Independent ID: b5df6c17-66b1-fee5-64d3-7888fd134e35
* Content: [az pipelines agent](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/agent?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines/agent.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines/agent.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
Hi @gauravsaralMs , could you please help take a look at this ?

**Comment by timmkrause** [comment]
Wrong repo.
