### ISSUE TITLE
az network front-door routing-rule create --caching is not supported

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli-extensions#1275]
Parameter --caching is documented, but not supported: `az: error: unrecognized arguments: --caching Enabled`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc41d7b5-ab21-fe9b-2f2e-93ac02e5af86
* Version Independent ID: 67398425-8b96-f515-72af-22255ea1ae49
* Content: [az network front-door routing-rule](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/routing-rule?view=azure-cli-latest#ext-front-door-az-network-front-door-routing-rule-create)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
HI @MyronFanQiu  could you pls have a look? thanks.

**Comment by yonzhan** [comment]
add to S167.

**Comment by MyronFanQiu** [comment]
@wasker It's quite a strange error. I check the code and this argument is indeed supported. Did you still meet such issue? Do you have some strings containing `"` or `'`?

**Comment by wasker** [comment]
The argument might be supported, but it doesn't accept documented values. I.e., `--caching Enabled` fails with the error from the initial report.

**Comment by MyronFanQiu** [comment]
@wasker I just tried the command with `--caching` and it works. Could you please check it again?
```
az network front-door routing-rule create -f clitest -g 20200304 --frontend-endpoints DefaultFrontendEndpoint --route-type Forward --backend-pool DefaultBackendPool -n forwardRoutingrule1 --patterns /forward1 --caching Enabled
```

**Comment by wasker** [comment]
```
$ az version
This command is in preview. It may be changed/removed in a future release.
{
  "azure-cli": "2.0.81",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.0.81",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.27",
    "front-door": "0.1.7",
    "resource-graph": "1.0.0"
  }
}
```

I've manually created a frontdoor instance, then:

`az network front-door frontend-endpoint create --resource-group qwe --front-door-name test03042020 --name MsdxDomainName --host-name <my.cname.that.points.to.fd>`

and a routing rule:

`az network front-door routing-rule create --resource-group qwe --front-door-name test03042020 --name MsdxDomainRouting --frontend-endpoints MsdxDomainName --backend-pool mypool --route-type Forward --forwarding-protocol HttpsOnly --accepted-protocols Http Https --caching Enabled --dynamic-compression Enabled --query-parameter-strip-directive StripNone`

Result:

```
az: error: unrecognized arguments: --caching Enabled
```

**Comment by MyronFanQiu** [comment]
@wasker emmm... I still can create the routing-rule with `--caching Enabled`. I just copied your command and changed the `--frontend-endpoints`. which version of front-door are you using? Which OS and terminal?

**Comment by MyronFanQiu** [comment]
meanwhile, the latest version of front-door should be 1.0.2. Could you please re-install the extension? `az extension remove -n front-door` and `az extension add -n front-door`.

**Comment by wasker** [comment]
Using ext version 1.0.2 fixes the issue, thanks.
