### ISSUE TITLE
az network front-door routing-rule create --backend-pool is mandatory

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli-extensions#1276]
Parameter --backend-pool is documented as optional, but it is mandatory: `BadRequest - Property 'FrontdoorEntity.RoutingRules[1].Properties.RouteConfiguration.BackendPool' is required but it was not set` is the error, if argument was not supplied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc41d7b5-ab21-fe9b-2f2e-93ac02e5af86
* Version Independent ID: 67398425-8b96-f515-72af-22255ea1ae49
* Content: [az network front-door routing-rule](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/routing-rule?view=azure-cli-latest#ext-front-door-az-network-front-door-routing-rule-create)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
HI @MyronFanQiu  could you pls have a look? thanks.

**Comment by yonzhan** [comment]
add to S167.

**Comment by MyronFanQiu** [comment]
@wasker Thanks. We will fix it later.

**Comment by MyronFanQiu** [comment]
@wasker I just checked the code. `--backend-pool` is required when you try to create a Forward routing rule. But it's not required for a Redirect rule. So it's by design to mark it as optional. I updated the help message.
