### ISSUE TITLE
Workitem description field format is not consistent between `show` & `create`

### ISSUE THREAD

**Issue by mydiemho** [Azure/azure-cli-extensions#1279]
I ran the `show` command to retrieve some existing work items from one organization that I wanted to clone to a different organization.

The `show` command give me a json response with the `description` field with data that contains html style.  When I set those same value as the description in the `create` command, nothing is display in the UI, but I can see the description field has those value set in the API response.

One thing to note is that the `create` and `update` command do not have a `repro steps` field, only description so that's why I'm using the `description` field for `type=Bug` workitem

For example:

The description from an existing workitem looks like this

```
"&lt;div&gt;&lt;strong&gt;&lt;span style="color:rgba(0, 0, 0, 0.901961);font-family:&quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;font-size:15px;font-weight:normal;text-align:left;display:inline !important;"&gt;As a user, I am able to re-use the same vanity URL to create multiple url-lists via the Urlist service.&lt;/span&gt;&lt;br&gt;&lt;/strong&gt;&lt;/div&gt;&lt;div&gt;&lt;strong&gt;&lt;span style="color:rgba(0, 0, 0, 0.901961);font-family:&quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;font-size:15px;font-weight:normal;text-align:left;display:inline !important;"&gt;&lt;br&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/div&gt;&lt;strong&gt;Steps to re-produce:&lt;/strong&gt;&lt;ol style="margin:0px;padding-left:32px;"&gt;&lt;li&gt;Do a POST request to the /api/Links endpoint using some vanity URL.&lt;/li&gt;&lt;li style="margin-top:4px;"&gt;&lt;span style=""&gt;Do a POST request to the /api/Links endpoint using&lt;/span&gt;&lt;span style=""&gt;&nbsp;&lt;/span&gt;&lt;strong style=""&gt;the same&lt;/strong&gt;&lt;span style=""&gt;&nbsp;&lt;/span&gt;&lt;span style=""&gt;vanity URL you used in step 1.&lt;/span&gt;&lt;br&gt;&lt;/li&gt;&lt;li style="margin-top:4px;"&gt;Do a GET request to the /api/Links endpoint to retrieve the list you just created.&lt;/li&gt;&lt;/ol&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;Behaviour:&lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;ul style="padding:0px 0px 0px 32px;margin:0px;color:rgba(0, 0, 0, 0.901961);font-family:&quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;font-size:15px;text-align:left;"&gt;&lt;li&gt;&lt;b&gt;Actual&lt;/b&gt;: the POST request in step #2 above succeeds and the GET request in step #3 fails with 500 HTTP status code.&lt;/li&gt;&lt;li style="margin-top:4px;"&gt;&lt;b&gt;Expected&lt;/b&gt;: the POST request in step #2 fails with 409 HTTP status code and an error message indicating a duplicate vanity URL.&lt;/li&gt;&lt;/ul&gt;&lt;br&gt;&lt;/div&gt;&lt;br&gt;"
```

## Expected Results
<img width="810" alt="Screen Shot 2020-02-15 at 23 43 13" src="https://user-images.githubusercontent.com/1634185/74600941-18fa9280-504d-11ea-9716-ed5c32573391.png">

## Actual
<img width="525" alt="Screen Shot 2020-02-15 at 23 44 35" src="https://user-images.githubusercontent.com/1634185/74600949-26178180-504d-11ea-9353-197928cc7678.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c5f488f-0ed7-6585-72c4-54095f30e1d3
* Version Independent ID: b1a48b12-cbb0-416a-1a71-2715d8dd8057
* Content: [az boards work-item](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards/work-item?view=azure-cli-latest#ext-azure-devops-az-boards-work-item-create)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/boards/work-item.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/boards/work-item.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
Hi @gauravsaralMs , could you please help with this ?

**Comment by gauravsaralMs** [comment]
@ishitam8 : can you please help with this?
@arrownj : I am not actively working on devops CLI part.

**Comment by mydiemho** [comment]
I figured it out, the `repro steps` is set in the `fields` flag and not the description flag
