### ISSUE TITLE
Add iteration - what is --id

### ISSUE THREAD

**Issue by wi5nia** [Azure/azure-cli-extensions#1282]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az boards

### Description of issue (in as much detail as possible)
I try to add an iteration with this command https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards/iteration/team?view=azure-cli-latest#ext-azure-devops-az-boards-iteration-team-add

But no matter what I enter in the --id parameter I get:
"This command group is in preview. It may be changed/removed in a future release.
Id
Please see https://aka.ms/azure-devops-cli-troubleshooting for more information on troubleshooting common errors. "
-----

**Comment by arrownj** [comment]
Hi @ishitam8 , could you please help with this ?

**Comment by ishitam8** [comment]
Hi,

You need to pass **identifier** [and not the ID] of the iteration as id in "boards iteration team add" command.

You can fetch the identifier of iteration you need from project iteration commands
`az boards iteration project list -p <YOUR_PROJECT_NAME> --org <ORG_URL> `

**Comment by geverghe** [comment]
@wi5nia - I am closing this issue. I hope the guidance provided by @ishitam8  worked for you. Feel free to raise an issue in https://github.com/azure/azure-devops-cli-extension for any issue/feedback.
