### ISSUE TITLE
No "basic" license type

### ISSUE THREAD

**Issue by mydiemho** [Azure/azure-cli-extensions#1286]
I wanted to add users with "basic" license type but there's no such option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84e9b38-b9da-f69f-c9d7-b0c1a1e8683a
* Version Independent ID: bfd383ce-2ee6-64ec-8ff6-a4e8c88fd516
* Content: [az devops user](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/user?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/user.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/user.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
devops.

**Comment by carmando62** [comment]
basic used to work from cli but no longer.  When I try "express" or "advanced"  I receive an error.  
az : ERROR: You are trying to invite a user from outside your directory, but the security setting of this organization 
doesn’t allow it.  The users I am trying to add are NOT outside our directory.

**Comment by geverghe** [comment]
@ishitam8 - could you follow up on this?

**Comment by ishitam8** [comment]
@carmando62 ,

Sorry for the delay.
Could you try the same command with --debug switch and share those logs?

**Comment by carmando62** [comment]
Thanks.  Will do.

**Comment by mydiemho** [comment]
SOLVE: `basic` has been replaced with `express`
