### ISSUE TITLE
az boards iteration project create path parameter example

### ISSUE THREAD

**Issue by oulasvirta** [Azure/azure-cli-extensions#1294]
Currently parameter has exmple of: ProjectNameIterationIterationName. Please give more detailed example what is the syntax here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1193c19c-ea84-5cd9-9efd-3d4baebb20cf
* Version Independent ID: 359fe52c-2d60-b6ba-492e-5eea79b0a74a
* Content: [az boards iteration project](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards/iteration/project?view=azure-cli-latest&source=docs#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/boards/iteration/project.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/boards/iteration/project.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by oulasvirta** [comment]
Here is example of working syntax:

az boards iteration project create --name "S01" `
--start-date "2020-01-01" `
--finish-date "2020-01-14" `
--path "\MyProject\Iteration\ParentIterarionPath" `
--org $org `
--project $project`

There needs to be always hardcoded path part ...\Iteration\... between your Azure DevOps project name and the parent iteration.

**Comment by ishitam8** [comment]
hi @oulasvirta ,

I am opening the same [issue](https://github.com/Azure/azure-devops-cli-extension/issues/965) in extension repo, so that it can be tracked in the repo itself.

**Comment by RakeshMohanMSFT** [comment]
Solution is provided here https://github.com/Azure/azure-devops-cli-extension/issues/965
