### ISSUE TITLE
app-insights' is not in the 'az monitor' command group

### ISSUE THREAD

**Issue by chbe8475** [Azure/azure-cli-extensions#1303]
I got the error 'app-insights' is not in the 'az monitor' command group' when running az monitor app-insights component show

Also the az monitor --help does not display app-insights.

Do you need to update documentation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7f5f91-5e89-9082-8c70-6431f0025f37
* Version Independent ID: 298daf64-db32-8b64-9a45-2c4c5e189522
* Content: [az monitor](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S167.

**Comment by MyronFanQiu** [comment]
hi. You should use `az extension add application-insights`. This is an cli extension and you should add it before using it.

**Comment by MyronFanQiu** [comment]
close this one since it's a question and should be answered. Feel free to reopen it or open a new issue if you still have any question.

**Comment by mleziva** [comment]
use `az extension add --name application-insights` on linux. See here: https://docs.microsoft.com/en-us/cli/azure/extension?view=azure-cli-latest#az-extension-add
