### ISSUE TITLE
azdev style aks-preview failed

### ISSUE THREAD

**Issue by gtxistxgao** [Azure/azure-cli-extensions#1305]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

aks-preview

### Description of issue (in as much detail as possible)

-----

When running "azdev style aks-preview", the check failed with following error. The check is required but skipped in this PR: https://github.com/Azure/azure-cli-extensions/pull/1217

```
===============
| Style Check |
===============

Extensions: aks-preview

Running flake8 on extensions...
Running pylint on extensions...


 Results 
=========

Flake8: PASSED

************* Module azext_aks_preview.custom
src/aks-preview/azext_aks_preview/custom.py:784:12: R1720: Unnecessary "else" after "raise" (no-else-raise)

-------------------------------------------------------------------
Your code has been rated at 9.99/10 (previous run: 10.00/10, -0.00)


Pylint: FAILED
```

**Comment by yonzhan** [comment]
aks-preview.

**Comment by gtxistxgao** [comment]
passed now. we can close this one.
