### ISSUE TITLE
Resource group 'myRG' could not be found

### ISSUE THREAD

**Issue by chbe8475** [Azure/azure-cli-extensions#1306]
az monitor app-insights component show
does not recognize my resource-group. I have double checked and the resource group exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 333d37d2-61e2-0184-d253-157ee236439c
* Version Independent ID: 9b0e976f-3cb5-e813-9f33-e9cea7a8df8c
* Content: [az monitor app-insights component](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights/component?view=azure-cli-latest#ext-application-insights-az-monitor-app-insights-component-show)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/component.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/component.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S167.

**Comment by MyronFanQiu** [comment]
@chbe8475 Hi. Sorry for the delay. Can you paste the error message? It's a quite simple command and it should work without such error.

**Comment by MyronFanQiu** [comment]
@chbe8475 Hi. Are you still meeting this error?

**Comment by MyronFanQiu** [comment]
close this issue since no response. Feel free to open a new issue if you encounter any problem.
