### ISSUE TITLE
az cli front-door delete - fails

### ISSUE THREAD

**Issue by podedra92** [Azure/azure-cli-extensions#1311]
I dont believe this is linked to my resources as Ive deleted against different FrontDoors in different subscriptions - Deleting endpoints via cli seems to take a long time due to waiting for getting the results which seems to fail, despite endpoints having been deleted 

"extensionType": "whl"
"name": "front-door"
"version": "1.0.2"

Example Running:
 az network front-door routing-rule delete --front-door-name  --name  --resource-group 

Routing rule and endpoints do get deleted, maybe I should use --no-wait if supported but it takes 17mins for one deletion and Get frontdooroperationresults/?api-version=2019-05-01' returns

msrest.http_logger : Response status: 200
msrest.http_logger :     'Date': 'Sun, 23 Feb 2020 20:15:36 GMT'
msrest.http_logger : Response content:
msrest.http_logger : {
  "status":"Failed","error":{
    "code":"InternalError","message":"Sorry, it looks like there was an error on our end. Please contact Support if you keep having this problem."
  }
}
msrest.exceptions : Sorry, it looks like there was an error on our end. Please contact Support if you keep having this problem.
cli.azure.cli.core.util : Sorry, it looks like there was an error on our end. Please contact Support if you keep having this problem.
Sorry, it looks like there was an error on our end. Please contact Support if you keep having this problem.
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2587 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
command ran in 1749.062 seconds.

**Comment by yungezz** [comment]
HI @MyronFanQiu could you pls help to look at the issue? thanks.

**Comment by yonzhan** [comment]
add to S166.

**Comment by MyronFanQiu** [comment]
@podedra92 Looks like it's a service issue. I tried to invite the service's help.
