### ISSUE TITLE
Authenticate SDK control channel

### ISSUE THREAD

**Issue by glautrou** [Azure/azure-cli-extensions#1340]
This documentation specify how to add read/write properties, but not how to add "Authenticate SDK control channel".
The only workaround is to not set both read/write properties. Now on my Azure portal the SDK is correctly checked but read/write as well and I don't want the latter.
How to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8baafade-06ad-e452-af14-7798fb17209f
* Version Independent ID: 45201db1-8a1c-f2f9-9771-32a179db6b73
* Content: [az monitor app-insights api-key](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights/api-key?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/api-key.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/api-key.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S167.

**Comment by MyronFanQiu** [comment]
@glautrou Hi. Could you share the context about your issue? What's the meaning of "Authenticate SDK control channel"?

**Comment by MyronFanQiu** [comment]
@glautrou kindly ping.

**Comment by glautrou** [comment]
Hi @MyronFanQiu
This is the option checked in the screenshot below taken from the Azure portal.
![image](https://user-images.githubusercontent.com/3740780/76194679-ede80680-61e6-11ea-9173-d7daa707a404.png)

[Link to the documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream#secure-the-control-channel).

**Comment by MyronFanQiu** [comment]
@glautrou Let me check. I'm not sure whether we can do it in Azure CLI or not. Sometimes, there are some "magic" operations for Portal only. I will keep you posted.

**Comment by MyronFanQiu** [comment]
@glautrou Hi. I just check the code. You should be able to set 
```
--read-properties AuthenticateSDKControlChannel
```
to achieve same goal with the portal. Please have a try and let me know whether it work or not.

**Comment by glautrou** [comment]
Hi MyronFanQiu,

Thanks for your help. The SDK checkbox is now checked.

However that also check "Write annotations" by default. This is the command I ran:
`az monitor app-insights api-key create --api-key MyName -g MyRg --app MyApp --read-properties AuthenticateSDKControlChannel`

Result:
![image](https://user-images.githubusercontent.com/3740780/77417147-46adc680-6dc5-11ea-9753-419ef08617e2.png)

=> Is it possible to separate the "Write annotations" option?

**Comment by MyronFanQiu** [comment]
it should work by this command.
```
az monitor app-insights api-key create --api-key MyName -g MyRg --app MyApp --read-properties AuthenticateSDKControlChannel --write-properties ""
```

**Comment by glautrou** [comment]
> 
> 
> it should work by this command.
> 
> ```
> az monitor app-insights api-key create --api-key MyName -g MyRg --app MyApp --read-properties AuthenticateSDKControlChannel --write-properties ""
> ```

No, this throw the error:

> az monitor app-insights api-key create: error: argument --write-properties: expected at least one argument

**Comment by MyronFanQiu** [comment]
@glautrou Are you using powershell? Please change it to `--write-preperties "''"`

**Comment by glautrou** [comment]
@MyronFanQiu Yes with Powershell, but still doesn't work: `az: error: unrecognized arguments: --write-preperties ''`

![image](https://user-images.githubusercontent.com/3740780/78261828-05719100-7500-11ea-973e-3a1e81ca9683.png)

> 
> 
> > it should work by this command.
> > ```
> > az monitor app-insights api-key create --api-key MyName -g MyRg --app MyApp --read-properties AuthenticateSDKControlChannel --write-properties ""
> > ```
> 
> No, this throw the error:
> 
> > az monitor app-insights api-key create: error: argument --write-properties: expected at least one argument

If I re-run my previous attempt above we now get our new error `az: error: unrecognized arguments: --write-preperties`

**Comment by MyronFanQiu** [comment]
> @MyronFanQiu Yes with Powershell, but still doesn't work: `az: error: unrecognized arguments: --write-preperties ''`
> 
> ![image](https://user-images.githubusercontent.com/3740780/78261828-05719100-7500-11ea-973e-3a1e81ca9683.png)
> 
> > > it should work by this command.
> > > ```
> > > az monitor app-insights api-key create --api-key MyName -g MyRg --app MyApp --read-properties AuthenticateSDKControlChannel --write-properties ""
> > > ```
> > 
> > 
> > No, this throw the error:
> > > az monitor app-insights api-key create: error: argument --write-properties: expected at least one argument
> 
> If I re-run my previous attempt above we now get our new error `az: error: unrecognized arguments: --write-preperties`

@glautrou Hi. there is a typo error. But I found another error. Let me update it first.

**Comment by MyronFanQiu** [comment]
@glautrou Hi. `--write-properties '""'` should work after I merge the PR.
