### ISSUE TITLE
`az network firewall ip-config create` is taking too much time

### ISSUE THREAD

**Issue by mathieu-benoit** [Azure/azure-cli-extensions#1354]
### Extension name (the extension in question)

`azure-firewall - 0.3.0`

### Description of issue (in as much detail as possible)

When running `az network firewall ip-config create` is taking too long time. In my case it took 1h09min... is there any way to optimize this?

**Comment by yonzhan** [comment]
add to S167.

**Comment by MyronFanQiu** [comment]
can we close this one and we can discuss in #1355. It's should be the same problem.

**Comment by mathieu-benoit** [comment]
Makes sense if you think it's related, continuing the discussion there #1355, thanks.
