### ISSUE TITLE
Doc should point out that 'az iotcentral' is deprecated 

### ISSUE THREAD

**Issue by wickste** [Azure/azure-cli-extensions#1356]
Please add a note that 'az iotcentral' is deprecated and instead 'az iot central' should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1bb68fd-f7ec-b129-9617-3ca02fc99340
* Version Independent ID: 9fb673ac-1cfe-f9ee-9da4-86fbcbe39dd7
* Content: [azure-cli-iot-ext](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/index.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/index.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
thanks for reporting, we're looking at it.

**Comment by digimaun** [comment]
We've added deprecation/removal messages for the legacy iot extension "azure-cli-iot-ext" which had the deprecated `az iotcentral` root command group that this issue references. There are also warnings shown when running commands from the deprecated extension.

https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/?view=azure-cli-latest


https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest
![image](https://user-images.githubusercontent.com/28658112/92657659-0d511080-f2aa-11ea-8dd8-5dc9071024b2.png)
