### ISSUE TITLE
[Proposal] Show extension version in extension reference docs

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-cli-extensions#136]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
All extensions

### Description of issue (in as much detail as possible)
-----
The auto generating reference docs for extensions is a fantastic feature and alleviates extension teams having to build their own system for it.

However it is difficult to tell the extension version used. Theoretically the latest version should be used but given delays in syncing it would be nice to have the version somewhere obvious on the page so there is no second guessing. Not to mention having a version to point at for customers.

**Comment by yonzhan** [comment]
add to S165.

**Comment by haroldrandom** [comment]
It is implmented already. Please veriy if it's what you want. https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest.

Feel free to reopen if I was mistaken anything. :)
