### ISSUE TITLE
az image copy taking forever to copy 256 Gb

### ISSUE THREAD

**Issue by tbarry-acs** [Azure/azure-cli-extensions#1362]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
image copy

### Description of issue (in as much detail as possible)

have a Windows image with a 256 Gb SSD disk that lives in West US, and trying to copy to west us 2, its taken 40 minutes and is at 4 %. 

This should never be the case, I have copied 1TB down to my laptop faster than this.
-----

**Comment by yonzhan** [comment]
@qwordy  please take a look

**Comment by qwordy** [comment]
What is the final result of the command? Does it finish? I haven't copied image of such size.

**Comment by qwordy** [comment]
@Juliehzl Does `storage blob copy` support large object such as 256G?

**Comment by Juliehzl** [comment]
`az storage blob copy` will take long time, too. You can have a try with `az storage copy`.

**Comment by qwordy** [comment]
Would you please share what's the difference between them?
