### ISSUE TITLE
hack is not compatible with CLI Core > 2.1.0, current version is 2.2.0

### ISSUE THREAD

**Issue by berndverst** [Azure/azure-cli-extensions#1375]
### Extension name (the extension in question)

Hack

### Description of issue (in as much detail as possible)

az hack is not compatible with CLI Core > 2.1.0, current version is 2.2.0 #15

**Comment by berndverst** [comment]
This issue will be addressed by merging #1309

**Comment by berndverst** [comment]
Manual install instructions for the new version waiting to be merged:

```bash
az extension remove --name hack
az extension add --source https://azhackcli.blob.core.windows.net/whl/hack-0.4.2-py2.py3-none-any.whl
```

**Comment by GeekTrainer** [comment]
#1309 will address this

**Comment by fengzhou-msft** [comment]
PR merged and now you can run `az extension update -n hack` to upgrade to the latest version if you have an existing incompatible one. Sorry for the delay.
