### ISSUE TITLE
error: error in setup.cfg: command 'bdist_wheel' has no such option 'azure_namespace_package'

### ISSUE THREAD

**Issue by harleypig** [Azure/azure-cli-extensions#1395]
Describe the bug

I am trying to build the wheel for azure-cli and the build fails with the message
"error: error in setup.cfg: command 'bdist_wheel' has no such option 'azure_namespace_package'" in several dependant packages which I am trying to list here:

azure-mgmt-billing
azure-mgmt-applicationinsights
azure-mgmt-consumption
azure-mgmt-datalake-analytics
azure-mgmt-relay

To Reproduce

$ pip wheel --no-binary :all: azure-cli

Expected behavior

Environment summary

Building the wheel with "pip wheel" on Fedora 31 with python 3.7.7.

Additional context

I believe the issue is similar to https://github.com/Azure/azure-cli/issues/10232.

**Comment by yungezz** [comment]
thansk for reporting, we'll look at it.

**Comment by yungezz** [comment]
hi @harleypig could you pls share more context? Are you developing azure-cli locally https://github.com/Azure/azure-cli/blob/dev/doc/configuring_your_machine.md? If yes, pls use `azdev` tool to setup environment. Or are you trying to use Azure CLI as end user? then pls follow official instruction guideline https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by harleypig** [comment]
I was trying to install it. At that point in time I was unable to get permission to add the necessary repositories and install that way.

That has since changed. You can close this bug, unless someone else is also having issues.

**Comment by yungezz** [comment]
hi @harleypig thanks for the info. To install Azure CLI, you don't need to build from scratch by yourself, you can follow the instruction at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest to choose proper install way per your OS type and package manager,  or pip. 

Will close the issue for now, feel free to create new one if any other issue met. thanks.

**Comment by LianwMS** [comment]
@harleypig Another issues are the same as current: https://github.com/Azure/azure-sdk-for-python/issues/12612 . May i know if it is opened by you, too?
