### ISSUE TITLE
[Proposal] Extension docs to support custom styling/rendering rules

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-cli-extensions#140]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Description of issue (in as much detail as possible)

-----
Aside from the syncing new extension doc updates in a timely fashion, it would be great to have a process for how to customize the rendering rules of text.  For example for the IoT extension (and this applies to the command module as well), the IoT command space name on the left hand reference menu should 'IoT' and not 'Iot'. 'C2d' needs to be 'C2D', 'D2c' needs to be 'D2C'...

These rules probably won't need to change often.

**Comment by yonzhan** [comment]
add to S165.

**Comment by haroldrandom** [comment]
it's a convention naming in Azure CLI. Closed as low-priority.
