### ISSUE TITLE
az aks nodepool add for windows node pools is failing with ARM template error

### ISSUE THREAD

**Issue by r-dilip** [Azure/azure-cli-extensions#1420]
_**PS C:\WINDOWS\system32> az aks nodepool add --resource-group dilipr-win --cluster-name dilipr-win --os-type Windows --name winnp --node-count 1 --kubernetes-version 1.15.7**_

Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for Agent Pool winnp failed. Error: {
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The provided value 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Common.Entities.TemplateGenericProperty`1[Newtonsoft.Json.Linq.JToken]' for the template parameter 'mobyVersion' at line '1' and column '9329' is not valid. The parameter value is not part of the allowed value(s): '3.0.1,3.0.2,3.0.3,3.0.4,3.0.5,3.0.6,3.0.7,3.0.8'.'."
 }

To me, it looks like the underlying ARM template has a bad value. Is that the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92444562-0540-adf6-3c3e-33b181bd10d4
* Version Independent ID: 3267c97e-819b-d945-fc28-2b75e35f2647
* Content: [az aks nodepool](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks/nodepool?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aks

**Comment by Jen7714** [comment]
Hello! Please try again with the latest Azure CLI version. Feel free to reopen an issue if it still doesn't work.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
