### ISSUE TITLE
toc az devops invoke format issue

### ISSUE THREAD

**Issue by Styxxy** [Azure/azure-cli-extensions#1436]
The description in the table for `az devops invoke` command has invalid formatting, eg the html is shown as plain text:

> This command will invoke request for any DevOps area and resource. Please use only json output as the response of this command is not fixed. Helpful docs - &lt;a href="https://docs.microsoft.com/en-us/rest/api/azure/devops/"&gt;https://docs.microsoft.com/en-us/rest/api/azure/devops/&lt;/a&gt;.

![screenshot](https://user-images.githubusercontent.com/1635825/77325454-a00bec00-6d18-11ea-9f2e-2623a1ec6d98.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9e855a-abc5-14d9-ba73-4ab527ffee16
* Version Independent ID: 85a46540-4b25-94f4-2c0e-29e1f8fefe35
* Content: [az devops](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
devops

**Comment by RakeshMohanMSFT** [comment]
This is fixed.
