### ISSUE TITLE
[aks-preview] Getting JSON instead of dashboard UI

### ISSUE THREAD

**Issue by aelij** [Azure/azure-cli-extensions#1446]
### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
I just updated the extension to version **0.4.37** because I was having problems accessing the dashboard using `az aks browse`, and after the upgrade I get a JSON document when browsing to http://127.0.0.1:8001/ (instead of the dashboard):

```
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/",
    "/apis/aadpodidentity.k8s.io",
    "/apis/aadpodidentity.k8s.io/v1",
    "/apis/admissionregistration.k8s.io",
    "/apis/admissionregistration.k8s.io/v1",
    "/apis/admissionregistration.k8s.io/v1beta1",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/apis/apiregistration.k8s.io",
    "/apis/apiregistration.k8s.io/v1",
    "/apis/apiregistration.k8s.io/v1beta1",
    "/apis/apps",
    "/apis/apps/v1",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1",
    "/apis/authorization.k8s.io/v1beta1",
```
etc.

Edit: Looks like this URL allows accessing the dashboard: http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by bpdohall** [comment]
I can reproduce this behavior, but it doesn't appear to be related to the `aks-preview` extension. The bare URL http://127.0.0.1:8001 returns JSON in either case.

The documentation is a bit ambiguous, it seems to suggest that navigating to the bare URL which is output by the `az aks browse` command will get you to the dashboard. https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#start-the-kubernetes-dashboard

Suggest updating the docs or updating the output to include the full URL which will route to the dashboard.

**Without Extension Installed**
Running `az aks browse` opens a browser window to http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ which shows the dashboard.

Manually navigating to http://127.0.0.1:8001 returns JSON doc,as reported.

```
$ az --version
azure-cli                          2.6.0

command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
interactive                        0.4.3
```

**Extension Installed**
Ran `az extension add --name aks-preview` (returned minor version 50)
Running `az aks browse` opens a browser window to http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ which shows the dashboard.

Manually navigating to http://127.0.0.1:8001 returns JSON doc,as reported.

```
$ az --version
azure-cli                          2.6.0

command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
aks-preview                       0.4.50
interactive                        0.4.3
```

**Comment by aelij** [comment]
The documentation has been updated to address this issue. Closing.
https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard
