### ISSUE TITLE
BadRequest/InvalidQuery when using the --include parameter in az graph query and simultaneously specifying a table.

### ISSUE THREAD

**Issue by bakedonion** [Azure/azure-cli-extensions#1449]
### Extension name (the extension in question)
resource-graph (1.0.0)

Additional information:
```
$ az --version
azure-cli                          2.2.0

command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
resource-graph                     1.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/bakedonion/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Mar  6 2020, 14:41:37)
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.
```

### Description of issue (in as much detail as possible)
Using the `--include displayNames` parameter in an `az graph query` while also specifying a resource graph table results in an error.

Working:
```
az graph query --include displayNames -q "where type =~ 'microsoft.compute/virtualmachines'"
```

Failing:
```
az graph query --include displayNames -q "resources | where type =~ 'microsoft.compute/virtualmachines'"
az graph query --include displayNames -q "resourcecontainers | where type =~ 'microsoft.resources/subscriptions'"
```

Error:
```
{
    "error": {
        "code": "BadRequest",
        "message": "Please provide below info when asking for support: timestamp = 2020-03-25T12:17:45.1528587Z, correlationId = fa8f06d3-a4de-45ae-aeee-0c1c246aa4
96.",
        "details": [
            {
                "code": "InvalidQuery",
                "message": "Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying."
            },
            {
                "code": "ParserFailure",
                "message": "ParserFailure",
                "additionalProperties": {
                    "characterPositionInLine": 329,
                    "line": 1,
                    "token": "resourcecontainers"
                }
            }
        ]
    }
}
```
-----

**Comment by yonzhan** [comment]
resource-graph

**Comment by bakedonion** [comment]
I had the opportunity, to investigate the problem a bit further just now. I think line 52 in [/src/resource-graph/azext_resourcegraph/custom.py](https://github.com/Azure/azure-cli-extensions/blob/93f3ab87a01952798904a952fb777b526504c46a/src/resource-graph/azext_resourcegraph/custom.py#L52) is the perpetrator here.

When using `--include displayName` then if we take the following query as an example

```
az graph query --include displayNames -q "resourcecontainers | where type =~ 'microsoft.resources/subscriptions'"
```

then it would just get expanded to

```
extend subscriptionDisplayName=case(subscriptionId=='00000000-0000-0000-0000-000000000000', 'My Subscription Name', '') | extend tenantDisplayName=case(tenantId=='00000000-0000-0000-0000-000000000001', 'My Tenant Name', '') | resourcecontainers | where type =~ 'microsoft.resources/subscriptions'
```

when it should actually be

```
resourcecontainers | extend subscriptionDisplayName=case(subscriptionId=='00000000-0000-0000-0000-000000000000', 'My Subscription Name', '') | extend tenantDisplayName=case(tenantId=='00000000-0000-0000-0000-000000000001', 'My Tenant Name', '') | where type =~ 'microsoft.resources/subscriptions'
```

or

```
resourcecontainers | where type =~ 'microsoft.resources/subscriptions' | extend subscriptionDisplayName=case(subscriptionId=='00000000-0000-0000-0000-000000000000', 'My Subscription Name', '') | extend tenantDisplayName=case(tenantId=='00000000-0000-0000-0000-000000000001', 'My Tenant Name', '')
```

or something similar. At least the given resource graph table should remain at the beginning.

A quick test shows, that appending instead of prepending works, but I don't know if this might break in other cases.

Maybe it is a better idea to test whether the first part is a resource graph table and if so add the `extend` stuff after it, but before anything else?

Cheers

**Comment by bakedonion** [comment]
On another note [_get_cached_detailed_tenant()](https://github.com/Azure/azure-cli-extensions/blob/93f3ab87a01952798904a952fb777b526504c46a/src/resource-graph/azext_resourcegraph/custom.py#L104) or the request response seems to be broken as well.

At least during my testing the JSON object in the response does not contain a `displayName` key (or any other key with the tenant name).

This will result in an error if the cache file is older than a day.

Not sure if this should be a separate issue or not?

**Comment by bakedonion** [comment]
Please have a look at #1452 which should fix the initial BadRequest/InvalidQuery error. The missing `displayName` key for service principals remains.

**Comment by leylakazemi** [comment]
Thanks for the feedback. We put this in our backlog to fix. We will update our documentation once this is fixed.  Here is the link to the documenation:
https://docs.microsoft.com/en-us/azure/governance/resource-graph/samples/advanced?tabs=azure-cli#include-the-tenant-and-subscription-names-with-displaynames
