### ISSUE TITLE
"az pipelines runs artifact download" fail for containers that need to be downloaded as a zip file.

### ISSUE THREAD

**Issue by BrianMouncer** [Azure/azure-cli-extensions#1466]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az pipelines runs artifact download

### Description of issue (in as much detail as possible)
I need to be able to download the "containers" from the build run artifacts as a zip file (the same as I can from the web UI).

However the above command fails with error "Artifact with name 'Android' was found, but is of type 'Container'".  I've tried mapping into the container to download an individual file, but that also fail with a can't find file error.  I have also tried adding on "Android&$format=zip" that the rest api uses in it's download URI, but this also fails.

I've also posted this issue to Stock Overflow.

https://stackoverflow.com/questions/60942336/az-pipelines-runs-artifact-download-fails-with-error-artifact-was-found-but

**Comment by yonzhan** [comment]
pipelines

**Comment by geverghe** [comment]
@BrianMouncer - I have raised the same issue on our repo azure/azure-devops-cli-extension. I am closing this issue and you can track the issue - https://github.com/Azure/azure-devops-cli-extension/issues/982 on our repo for further updates.

**Comment by BrianMouncer** [comment]
Yes, we are using the Publish Build Artifacts task, and after several attempts, I am still unable to get "az pipelines runs artifact download --run-id" to work with any files that are in a "container".

I did a quick experiment today, and if I switch our build system to use PublishPipelineArtifact@1 task, then the AZ Clie command will work and download the files, though no longer as a zip file, but as an uncompressed set of files on disk.

I could adapts our scripts to this easy enought, but the blocking issue is that PublishPipelineArtifact@1 does not seem to be able to upload files from multiple agents to the same artifact name.

Our build system is distributed, so our windows binaries all builds on different agents.
e..g one agent will builds X64, while others builds arm and x86 binaries.
in the current system, each uploads a folder to an atrifact names "Windows", which later gets pulled down as a whole, and used to create our SDKs multi-platform nuget package.

The documentation on PublishPipelineArtifact@1 is a bit light.
Can you tell me how to configure PublishPipelineArtifact so that it can upload multiple parts to the same artifact name?
without hitting the "##[error]Artifact XYZ already exists for build ####" errors?

thanks...

**Comment by FrancescElies** [comment]
@geverghe, @BrianMouncer had a fair point could we clarify this, reopen?

`az pipelines runs artifact download --artifact-name $name --path ~/Downloads --run-id $run_id`

gives back a `Artifact with name 'mock-name' was found, but is of type 'Container'.` 

I know that moving forward one should use pipeline-artifacts instead of build-artifacts, but would be great to be able to download old artifacts from the command line too.
