### ISSUE TITLE
Please provide the JSON examples for --service-endpoint-configuration

### ISSUE THREAD

**Issue by ngnmhieu** [Azure/azure-cli-extensions#1495]
I've had hard time figuring out how to create a service connection to ACR Container Registry with Azure Devops CLI. Please provide an example for that. The JSON that that I've used for `--service-endpoint-configuration`  is:
```
{
  "administratorsGroup": null,
  "authorization": {
    "parameters": {
      "loginServer": "$ACR_REGISTRY_NAME.azurecr.io",
      "role": "8311e382-0749-4cb8-b61a-304f252e45ec", 
      "scope": "$ACR_REGISTRY_ID",
      "servicePrincipalId": "",
      "tenantId": "$TENANT_ID"
    },
    "scheme": "ServicePrincipal"
  },
  "data": {
    "appObjectId": "",
    "azureSpnPermissions": "",
    "azureSpnRoleAssignmentId": "",
    "registryId": "$ACR_REGISTRY_ID",
    "registrytype": "ACR",
    "spnObjectId": "",
    "subscriptionId": "$SUBSCRIPTION_ID",
    "subscriptionName": "$SUBSCRIPTION"
  },
  "description": "ACR Service Connection created by automated infrastructure pipeline.",
  "groupScopeId": null,
  "isReady": true,
  "isShared": false,
  "name": "$SERVICE_CONNECTION_NAME",
  "operationStatus": {
    "state": "Ready",
    "statusMessage": ""
  },
  "owner": "Library",
  "readersGroup": null,
  "serviceEndpointProjectReferences": null,
  "type": "dockerregistry",
  "url": "https://hub.docker.com/"
}
```
Note: the `"role": "8311e382-0749-4cb8-b61a-304f252e45ec"` is the roleId for "AcrPush" role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ecb62a2-f74c-a539-d3a8-c8fde7c2de06
* Version Independent ID: 5760936e-90a1-4129-6f6f-6dd4194bb73c
* Content: [az devops service-endpoint](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/service-endpoint?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
devops

**Comment by rmaziarka** [comment]
@ngnmhieu you put this JSON in a separate file?

**Comment by ngnmhieu** [comment]
@rmaziarka yes, and reference it in the command
```
az devops service-endpoint create --service-endpoint-configuration <PATH-TO-JSON>
```

**Comment by AaliAlikoski** [comment]
Any news on this? I am struggling with the same problem. So, an example of JSON needed for creating a service connection for ACR is what I am looking for.

**Comment by RakeshMohanMSFT** [comment]
@AaliAlikoski @ngnmhieu Apologies for this long delay! but i believe you are looking for this.

```
{
  "data": {},
  "name": "issue1495registrysvcconnconfig",
  "type": "dockerregistry",
  "url": "issue1495registry.azurecr.io",
  "authorization": {
    "parameters": {
      "loginServer": "issue1495registry.azurecr.io",
      "role": "8311e382-0749-****",
      "scope": "/subscriptions/<subid>/resourceGroups/Issue1495/providers/Microsoft.ContainerRegistry/registries/issue1495registry",
      "servicePrincipalId": "beb836f5-8c90-***",
      "servicePrincipalKey": "tokenkey",
      "tenantId": "****-41af-91ab-2d7cd011db47"
    },
    "scheme": "ServicePrincipal"
  },
  "isShared": false,
  "isReady": true,
  "serviceEndpointProjectReferences": [
    {
      "projectReference": {
        "id": "****-98ac-f7b359a9cbe8",
        "name": "Issue1698Repo"
      },
      "name": "issue1495registrysvcconnconfig"
    }
  ]
}
```

**Comment by arindam0310018** [comment]
Hello @ngnmhieu, @yonzhan, @rmaziarka,  @RakeshMohanMSFT, 
I stumbled into this thread when I was looking for a solution to create DevOps Service Connection of type "Docker Registry Using Basic Authentication". 
The MS Documentation https://learn.microsoft.com/en-us/azure/devops/cli/service-endpoint?view=azure-devops is not at all very clear. 

Below is my config.JSON file - 

`
{
  "data": {},
  "name": "AM-ACR-Srv-Connection",
  "type": "dockerregistry",
  "authorization": {
    "parameters": {
      "username": "ampocapplacr",
      "password": "XXXXXXXXXXXXXXXXXXXXXXXXX",
      "email": "mail2arindam2003@yahoo.com",
      "registry": "https://ampocapplacr.azurecr.io"
    },
    "scheme": "UsernamePassword"
  },
  "isShared": false,
  "isReady": true,
  "serviceEndpointProjectReferences": [
    {
      "projectReference": {
        "id": "36aaac58-e06f-47ed-8b98-003ad670ee3c",
        "name": "AMCLOUD"
      },
      "name": "AM-ACR-Srv-Connection"
    }
  ]
}
`
For More details, please refer below - 
Blog: https://dev.to/arindam0310018/create-docker-regisry-service-connection-using-devops-cli-1an8
Github: https://github.com/arindam0310018/30-Jan-2023-DevOpsCLI__Create-Docker-Registry-Service-Connection

The Final output Screenshot is mentioned below:-
![8](https://user-images.githubusercontent.com/29681063/215496710-3cd0d38d-fb81-4199-bbfa-db9049de13b0.jpg)

Hope this helps who ever visits this thread again.

Many Thanks
Regards, Arindam Mitra

**Comment by ri-we** [comment]
I'm trying to create a Docker service connection for an Azure Container Registry with a WorkloadIdentityFederation is this possible? Can't get it to work, can you provide an example?

**Comment by devdeer-yashas** [comment]
> I'm trying to create a Docker service connection for an Azure Container Registry with a WorkloadIdentityFederation is this possible? Can't get it to work, can you provide an example?

@ri-we Did you happen to find an example for WorkloadIdentityFederation
