### ISSUE TITLE
Please provide more information about the behavior of the creation and removal service-endpoint 

### ISSUE THREAD

**Issue by ngnmhieu** [Azure/azure-cli-extensions#1497]
In the effort to automate the deletion and creation of ACR service endpoint, I've had hard time figuring out the following behaviors of the creation and removal of a service endpoint:
- An app registration and service principal (as well as a role assignment) is created automatically upon creation of the service endpoint for ACR Container Registry
- When the service endpoint is deleted, the app registration / service principal and role assignment associated with that service endpoint don't get cleaned up

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ecb62a2-f74c-a539-d3a8-c8fde7c2de06
* Version Independent ID: 5760936e-90a1-4129-6f6f-6dd4194bb73c
* Content: [az devops service-endpoint](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/service-endpoint?view=azure-cli-latest#ext-azure-devops-az-devops-service-endpoint-create)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
devops

**Comment by geverghe** [comment]
@ngnmhieu - I have created an issue in azure devops cli extension repo - https://github.com/Azure/azure-devops-cli-extension/issues/986 to follow up on this. I am closing this issue. Kindly follow progress on the mentioned issue.
