### ISSUE TITLE
az blueprint import fails with long resource group name expression

### ISSUE THREAD

**Issue by wasabii** [Azure/azure-cli-extensions#1529]
### Extension name (the extension in question)
blueprint

### Description of issue (in as much detail as possible)
```
validation error: Parameter 'ResourceGroupDefinition.name' must have length less than 90.
```

This message is received when attempting to execute a blueprint with a `resourceGroup.name` property that is longer than 90 characters, despite that resource group name being a function expression containing `[]` which would ultimately not expand to 90 characters. For instance, the following fails:

```
        "resourceGroups": {
            "ApplicationResourceGroup": {
                "location": "[parameters('l')]",
                "name": "[concat(parameters('u'),'-',parameters('e'),'-',parameters('d'),'-',parameters('a'),'-rg')]"
            }
        }
```

It appears validation is happening directly on the `name` property. It is my belief that it should not be validated if it is an expansion expression, at all, as the CLI cannot know the final expansion.

-----

**Comment by yonzhan** [comment]
blueprint

**Comment by wasabii** [comment]
Azure/azure-sdk-for-net#11257 is a related issue in the .NET SDK which also effects the `Az.Blueprint` PowerShell module. For separate tracking.

I assume the validation logic is all generated off of the same source, and so this flows into everything.

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look? thanks.

**Comment by alex-frankel** [comment]
This is a swagger issue with the blueprints service, so it's not an issue specific to any of our clients, CLI or otherwise.

@wasabii - we are looking into it

**Comment by alex-frankel** [comment]
Going to close as this is not an issue with the az cli command
