### ISSUE TITLE
Error firewall network-rule create when trying to create a rule in a Firewall Manager

### ISSUE THREAD

**Issue by arcs002** [Azure/azure-cli-extensions#1543]
### Describe the bug

This happens when trying to add rule to a firewall manager resource:
https://docs.microsoft.com/en-us/azure/firewall-manager/overview

**Command Name**
`az network firewall network-rule create
Extension Name: azure-firewall. Version: 0.3.0.`

**Errors:**
```
'NoneType' object is not iterable
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cliextensions/azure-firewall/azext_firewall/custom.py, ln 252, in _upsert_af_rule
    collection_match = next((x for x in collection if x.name.lower() == collection_name.lower()), None)
TypeError: 'NoneType' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network firewall network-rule create -g {} --firewall-name {} --collection-name {} --destination-addresses {} --destination-ports {} --name {} --protocols {} --source-addresses {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

Extensions:
hack 0.4.2
front-door 1.0.4
azure-firewall 0.3.0

```

**Comment by qianwens** [comment]
@MyronFanQiu please help take a look.

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171

**Comment by MyronFanQiu** [comment]
@arcs002 Hi. The name of your collection should be wrong. I will fix the error message. Thanks for opening this issue.

**Comment by MyronFanQiu** [comment]
@arcs002 I believe this one is a rare edge case. Maybe you use other tools to manage same firewall manager before. I would fix this potential issue and refine error message. Thanks for opening this issue.
