### ISSUE TITLE
az artifacts universal download very slow - 'No such host is known' / 'Task was requested to be canceled' errors

### ISSUE THREAD

**Issue by abarger-bss** [Azure/azure-cli-extensions#1551]
### Extension name (the extension in question)
azure-devops

Output of `az --version`

```
azure-cli                          2.3.1

command-modules-nspkg              2.0.3
core                               2.3.1
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.18.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\---\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```

### Description of issue (in as much detail as possible)

Downloads for universal packages run extremely slowly on my home wifi network (testing with ethernet is not practical for me). Internet speed test shows I get 105 megabits / 13.5 megabytes downloaded / sec, but a 26.8 MB universal package took 80.7 seconds to download. See attached debug logs: [az-artifacts-install-log-redacted.txt](https://github.com/Azure/azure-cli-extensions/files/4488085/az-artifacts-install-log-redacted.txt). I can reproduce this problem for any package in my organization, from any machine connected to my home network. I cannot reproduce it at work. Some things I tend to notice when debugging this issue at home:

- First 50-75% of the package downloads without issue
- I begin encountering dozens of errors like:
```
[https://kxqvsblobprodcus376.blob.core.windows.net/db381d23d8538e453b959c59aacbfd5d6f/831435699CC93BDE54F74A08406B5E6E8
EFB857A401EEB3C0326B7378D95445E01?sv=2017-04-17&sr=b&sig=mXzDfAK8xpUqM1NKD%2FcPfWQmWADr1zQm70gHLM2DSAg%3D&spr=https&se=
2020-04-17T15%3A30%3A42Z&sp=r&rscl=x-e2eid-bd8d187c-ee374a96-b6401e9f-cd73f349-session-b15ff545-d0b54150-9d98956e-ce0f0
e89] Try 1/5, retryable exception caught. Retrying in 00:00:01. Details:
No LastRequestResponse on exception HttpRequestException: No such host is known.
```
- Following the 'No such host is known' error, I get dozens of errors like:
```[https://nn8vsblobprodcus340.blob.core.windows.net/db381d23d8538e453b959c59aacbfd5d6f/7EE43499D4CBD0EE2D270694888FB81C1
F21054A2403FB4EE1CCF44F63E756B502?sv=2017-04-17&sr=b&sig=7C6emAan06z6fXyag5fZn1oRefZxMmF0SCQIjNcsLFM%3D&spr=https&se=20
20-04-17T15%3A29%3A43Z&sp=r&rscl=x-e2eid-bd8d187c-ee374a96-b6401e9f-cd73f349-session-b15ff545-d0b54150-9d98956e-ce0f0e8
9] Try 1/5, non-retryable exception caught. Throwing. Details:
Task was requested to be canceled.
```
- The download finally completes.

I mention my network setup because this issue on Developer Community seems similar: [Cancelled requests when downloading artifact](https://developercommunity.visualstudio.com/content/problem/815111/cancelled-requests-when-downloading-artifact.html). Here is some information about my wifi network. This is not my specialty - I can provide more detail if requested.

```
Router Make/Model: Netgear R6250
Band: 5GHz
Channel: 153
Mode: Up to 1300 Mpbs
Security: WPA2-PSK [AES]
Metering: None
```

-----

**Comment by yonzhan** [comment]
devops

**Comment by johnterickson** [comment]
Hmm sounds familiar to https://github.com/dotnet/runtime/issues/31247

**Comment by abarger-bss** [comment]
I opened a support ticket with MS about this issue. They collected a few netsh traces from me and identified packet loss during my artifact download attempts, and requested I have my ISP check my equipment. My ISP (Spectrum, a division of Charter, if that helps anyone in the future) noted my modem was manufactured in 2014 and requested I replace it. Since replacing my modem, I still receive errors like 'No such host is known', but they seem transient now, and my artifact downloads complete in a reasonable amount of time. Since a hardware update fixed the problem I am going to close this issue.
