### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by smolesen** [Azure/azure-cli-extensions#1561]
I your example you write:

az eventgrid event-subscription create --name es1 \
    --source-resource-id /subscriptions/{SubID}/resourceGroups/{RG}/providers/Microsoft.EventGrid/topics/topic1 \
    --endpoint https://contoso.azurewebsites.net/api/f1?code=code
    --azure_active_directory_tenant_id azureactivedirectorytenantid
    --azure_active_directory_application_id_or_uri azureactivedirectoryapplicationidoruri

however further down the azure_active_directory_tenant_id and azure_active_directory_application_id_or_uri are with '-' instead of '_'

Also when I try to run the module, I get:

Warning: 'azure-active-directory-tenant-id' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'azure-active-directory-application-id-or-uri' is not in the list of known options, but still passed to Electron/Chromium.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: a9a33eda-23a9-dfa1-8056-9ad8f57e0a89
* Version Independent ID: 02e69365-44f7-6568-0c7f-64fa9a42bbb9
* Content: [az eventgrid event-subscription](https://docs.microsoft.com/da-dk/cli/azure/ext/eventgrid/eventgrid/event-subscription?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/eventgrid/eventgrid/event-subscription.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/eventgrid/eventgrid/event-subscription.yml)
* Service: **event-grid**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
eventgrid

**Comment by ahamad-MS** [comment]
Thanks for reporting the issue . We are investigation now!

**Comment by ahamad-MS** [comment]
The correct values are the ones listed in the parameters, namely

    --azure-active-directory-application-id-or-uri : The Azure Active Directory Application Id or
                                                     Uri to get the access token that will be
                                                     included as the bearer token in delivery
                                                     requests. Applicable only for webhook as a
                                                     destination.
    --azure-active-directory-tenant-id             : The Azure Active Directory Tenant Id to get the
                                                     access token that will be included as the
                                                     bearer token in delivery requests. Applicable
                                                     only for webhook as a destination.


The example has a typo. We will fix these in next revision of the extension. In the meantime, please use the parameters with - not _

thahnks

**Comment by smolesen** [comment]
How about the second part:
Warning: 'azure-active-directory-tenant-id' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'azure-active-directory-application-id-or-uri' is not in the list of known options, but still passed to Electron/Chromium.

why do I get these warnings?

**Comment by ahamad-MS** [comment]
Not sure what I means honestly and whether it is CLI specific warning given that you are not using -- .. Maybe someone in CLI team can help. 

However, please let us know if using the correct parameters format is having any issue. Also, please use latest eventgrid extension version 0.4.8  in your repro.
