### ISSUE TITLE
EventGrid subscription with authentication

### ISSUE THREAD

**Issue by smolesen** [Azure/azure-cli-extensions#1572]
Hi
I'm trying to create an EventGrid subscription with authentication, I'm issuing the below command, but I'm getting these warnings, and I don't see any token in the validation request header.

```
Warning: 'azure-active-directory-tenant-id' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'azure-active-directory-application-id-or-uri' is not in the list of known options, but still passed to Electron/Chromium.
```

`az --version`

gives me:

```
Extensions:
eventgrid                          0.4.8
```

Command:
`az eventgrid event-subscription create --name es1
--source-resource-id /subscriptions/{SubID}/resourceGroups/{RG}/providers/Microsoft.EventGrid/topics/topic1
--endpoint https://contoso.azurewebsites.net/api/f1?code=code
--azure-active-directory-tenant-id azureactivedirectorytenantid
--azure-active-directory-application-id-or-uri azureactivedirectoryapplicationidoruri
`

What is the correct command to create an EventGrid subscription with Authentication?

**Comment by yonzhan** [comment]
eventgrid

**Comment by ahamad-MS** [comment]
Investigating...

**Comment by ahamad-MS** [comment]
Hello @smolesen  .. I am not sure how different is this issue from this other reported issue https://github.com/Azure/azure-cli-extensions/issues/1561 

Anyhow, I am using latest eventgrid extension and command works fine for me. here is the command I am using and output I am getting:

ashraf@Azure:~$ az extension list
[
  {
    "extensionType": "whl",
    "name": "eventgrid",
    "version": "0.4.8"
  }
]


ashraf@Azure:~$ az eventgrid event-subscription create --source-resource-id /subscriptions/{subId}/resourceGroups/{rg}/providers/Microsoft.EventGrid/topics/{topicName} --name {ESName} --endpoint-type webhook --endpoint https://{funName}.azurewebsites.net/api/{funName}?code={Code} --azure-active-directory-tenant-id {guid1} --azure-active-directory-application-id-or-uri {guid2}

The behavior of this command has been altered by the following extension: eventgrid
If the provided endpoint does not support subscription validation handshake, navigate to the validation URL that you receive in the subscription validation event, in orderto complete the event subscription creation or update. For more details, please visit http://aka.ms/esvalidation
{
  "deadLetterDestination": null,
  "deadLetterWithResourceIdentity": null,
  "deliveryWithResourceIdentity": null,
  "destination": {
    "azureActiveDirectoryApplicationIdOrUri": {guid1},
    "azureActiveDirectoryTenantId": {guid1},
    "endpointBaseUrl": "https://{funcName}.azurewebsites.net/api/{Func}",
    "endpointType": "WebHook",
    "endpointUrl": null,
    "maxEventsPerBatch": 1,
    "preferredBatchSizeInKilobytes": 64
  },
  "eventDeliverySchema": "EventGridSchema",
  "expirationTimeUtc": null,
  "filter": {
    "advancedFilters": null,
    "includedEventTypes": null,
    "isSubjectCaseSensitive": null,
    "subjectBeginsWith": "",
    "subjectEndsWith": ""
  },
  "id": "/subscriptions/{subId}/resourcesGroups/}rg}/providers/Microsoft.EventGrid/topics/{topicName}/providers/Microsoft.EventGrid/eventSubscriptions/{ESName}",
  "labels": null,
  "name": {ESName},
  "provisioningState": "Succeeded",
  "resourceGroup": "amh",
  "retryPolicy": {
    "eventTimeToLiveInMinutes": 1440,
    "maxDeliveryAttempts": 30
  },
  "topic": "/subscriptions/{subId}/resourceGroups/{rg}/providers/microsoft.eventgrid/topics/{topicName}",
  "type": "Microsoft.EventGrid/eventSubscriptions"
}

Can you please use this command and report if you still have an issue. I believe you are not using the parameters properly.

**Comment by smolesen** [comment]
Hi
Yes, 1571 is more or less the same as 1561. 1561 was just being closed, so I thought I'd create a new one instead of continuing 1561

Think I figured out what is wrong, the endpoint I need to use for the webhook, contains an '&' 

`--endpoint https://8432ac02.ngrok.io/runtime/webhooks/EventGrid?functionName=AlertRaisedHandler&code=11111112C2GGXQ2RIAJ9a6BxsnUZ0UaWBFnSfUji8aP7cpQ9wVbtSg==`

but how do I escape the '&' ? I've tried:

using double quotes:
`--endpoint "https://8432ac02.ngrok.io/runtime/webhooks/EventGrid?functionName=AlertRaisedHandler&code=11111112C2GGXQ2RIAJ9a6BxsnUZ0UaWBFnSfUji8aP7cpQ9wVbtSg=="`

using single quotes:
`--endpoint 'https://8432ac02.ngrok.io/runtime/webhooks/EventGrid?functionName=AlertRaisedHandler&code=11111112C2GGXQ2RIAJ9a6BxsnUZ0UaWBFnSfUji8aP7cpQ9wVbtSg=='`

using double and single quotes:
`--endpoint "'https://8432ac02.ngrok.io/runtime/webhooks/EventGrid?functionName=AlertRaisedHandler&code=11111112C2GGXQ2RIAJ9a6BxsnUZ0UaWBFnSfUji8aP7cpQ9wVbtSg=='"`

using \\&:
`--endpoint https://8432ac02.ngrok.io/runtime/webhooks/EventGrid?functionName=AlertRaisedHandler\&code=11111112C2GGXQ2RIAJ9a6BxsnUZ0UaWBFnSfUji8aP7cpQ9wVbtSg==`

Non of it seems to work...

**Comment by smolesen** [comment]
Figured it out, you'd have to use both single- and double quotes, but single quotes first:

`--endpoint '"https://8432ac02.ngrok.io/runtime/webhooks/EventGrid?functionName=AlertRaisedHandler\&code=11111112C2GGXQ2RIAJ9a6BxsnUZ0UaWBFnSfUji8aP7cpQ9wVbtSg=="'`

**Comment by ahamad-MS** [comment]
Glad this issue is resolved for you. thx
