### ISSUE TITLE
Command 'component show' for the extension application-insights is broken

### ISSUE THREAD

**Issue by dkmiller** [Azure/azure-cli-extensions#1578]
### Extension name (the extension in question)

`application-insights`

### Description of issue (in as much detail as possible)

-----

The most recent update (0.1.6 &mapsto; 0.1.7) to the `application-insights` Azure CLI extension broke the command `az monitor app-insights component show`. Before that update, calling

```
az monitor app-insights component show --app my_app_name -g my_resource_group_name
```
would result in JSON containing the instrumentation key and other information. Now, that command results in a failure:

> No registered resource provider found for location 'westus2' and API version '2020-02-02-preview' for type 'components'. The supported api-v
ersions are '2014-04-01, 2014-08-01, 2014-12-01-preview, 2015-05-01, 2018-05-01-preview'. The supported locations are ', eastus, southcentra
lus, northeurope, westeurope, southeastasia, westus2, uksouth, canadacentral, centralindia, japaneast, australiaeast, koreacentral, francece
ntral, centralus, eastus2, eastasia, westus, southafricanorth, northcentralus, brazilsouth, switzerlandnorth, australiasoutheast'.

I have reproduced this issue with versions 2.3.1 and 2.4.0 of the Azure CLI.

**Comment by devaradhanm** [comment]
How do we unblock ourselves in release pipeline, till this issue is fixed. We cannot specify version when installing application-insights using the az command "az extension add -n application-insights"

**Comment by gusnaughton** [comment]
> @MyronFanQiu How do we unblock ourselves in release pipeline, till this issue is fixed. We cannot specify version when installing application-insights using the az command "az extension add -n application-insights"

It would be fantastic if Microsoft began to tag Azure CLI Extension releases and support version pinning. It seems like currently the only way to achieve this is to store the desired commit SHA alongside your code's version, and at build time pulling down this extensions repository against that SHA and using the [--source parameter on az extension](https://docs.microsoft.com/en-us/cli/azure/extension?view=azure-cli-latest#az-extension-add) to add the versioned extension. Certainly not ideal.

**Comment by yonzhan** [comment]
add to S169

**Comment by MyronFanQiu** [comment]
@dkmiller Sorry for this issue. There are new features in the new version of extension. However, the service has whitelist and is not public right now. Let me confirm with service team. If the service cannot be public soon, I would revert the version back to 0.1.6 first.

**Comment by manishsat** [comment]
@MyronFanQiu Thx for the confirmation, please revert it as soon as possible our release pipelines are blocked.

**Comment by liuy-tnz** [comment]
@MyronFanQiu Thank you. We get this issue too. It blocks our deployment.

**Comment by MyronFanQiu** [comment]
We have reverted the version back. I will sync with service team and find out a solution for this issue later.

**Comment by devaradhanm** [comment]
> > @MyronFanQiu How do we unblock ourselves in release pipeline, till this issue is fixed. We cannot specify version when installing application-insights using the az command "az extension add -n application-insights"
> 
> It would be fantastic if Microsoft began to tag Azure CLI Extension releases and support version pinning. It seems like currently the only way to achieve this is to store the desired commit SHA alongside your code's version, and at build time pulling down this extensions repository against that SHA by using the [--source parameter on az extension](https://docs.microsoft.com/en-us/cli/azure/extension?view=azure-cli-latest#az-extension-add) to add the versioned extension.

Since this issue was closed without addressing this question, I have created a bug for this - https://github.com/Azure/azure-cli-extensions/issues/1587
