### ISSUE TITLE
az image copy dangerous cleanup with temporary_resource_group_name

### ISSUE THREAD

**Issue by suppix** [Azure/azure-cli-extensions#1584]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az image copy

### Description of issue (in as much detail as possible)

With the option cleanup you simply delete the whole temporary resource group, but with the option 
--temporary_resource_group_name it can be dangerous.  I think it's better to delete only what you really create. With this option cleanup and temporary_resource_group_name you can delete my existing resource group which can contain important data.

**Comment by yonzhan** [comment]
@qwordy  please take a look

**Comment by qwordy** [comment]
If you omit `--temporary-resource-group-name`, a temporary resource group image-copy-rg will be used. I suggest omit it or use a different temporary resource group from source resource group.

**Comment by suppix** [comment]
az image copy --help
