### ISSUE TITLE
az network front-door routing-rule create fails for redirect rule

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli-extensions#1592]
Command 

`az network front-door routing-rule create --front-door-name myfd --name Hello --resource-group myrg --backend-pool DefaultBackendPool --frontend-endpoints myfd.azurefd.net --route-type Redirect --redirect-type Moved --redirect-protocol HttpsOnly`

results in 

"_usage error: [--redirect-type {Moved,Found,TemporaryRedirect,PermanentRedirect}][--redirect-protocol {HttpOnly,HttpsOnly,MatchRequest}] [--custom-host CUSTOM_HOST] [--custom-path CUSTOM_PATH] [--custom-fragment CUSTOM_FRAGMENT] [--custom-query-string CUSTOM_QUERY_STRING]_".

Command 

`az network front-door routing-rule create --front-door-name myfd --name Hello --resource-group myrg --backend-pool DefaultBackendPool --frontend-endpoints myrg.azurefd.net --route-type Redirect --redirect-type Moved --redirect-protocol HttpsOnly --custom-host "" --custom-path "" --custom-fragment "" --custom-query-string ""` 

results in the same error.

How to create redirect rule?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc41d7b5-ab21-fe9b-2f2e-93ac02e5af86
* Version Independent ID: 67398425-8b96-f515-72af-22255ea1ae49
* Content: [az network front-door routing-rule](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/routing-rule?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@wasker these arguments `--custom-host "" --custom-path "" --custom-fragment "" --custom-query-string ""` should have valid values.

**Comment by wasker** [comment]
I want to achieve the config as shown below.

According to the [documentation](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/routing-rule?view=azure-cli-latest#ext-front-door-az-network-front-door-routing-rule-create), I should either not include --custom-xxx args (my first attempt in my original message), or use empty string values to use incoming request info (my second attempt in my original message). Either of options doesn't work.

![afd-redirect](https://user-images.githubusercontent.com/1999365/80241889-42b9d200-8619-11ea-9ee3-02f488b360d6.png)

**Comment by MyronFanQiu** [comment]
@wasker Sorry for the delay. I just check detailed logic. For a redirect rule, you should not include --backend-pool DefaultBackendPool.

**Comment by MyronFanQiu** [comment]
@aramesh-msft Please take a look as well.

**Comment by aramesh-msft** [comment]
```az network front-door routing-rule create --help``` shows exactly the accepted arguments for redirect rule under "Redirect Routing Rule Arguments".

```
Redirect Routing Rule Arguments
    --custom-fragment                 : Fragment to add to the redirect URL. Fragment is the part of
                                        the URL that comes after #. Do not include the #.
    --custom-host                     : Host to redirect. Leave empty to use use the incoming host
                                        as the destination host.
    --custom-path                     : The full path to redirect. Path cannot be empty and must
                                        start with /. Leave empty to use the incoming path as
                                        destination path.
    --custom-query-string             : The set of query strings to be placed in the redirect URL.
                                        Setting this value would replace any existing query string;
                                        leave empty to preserve the incoming query string. Query
                                        string must be in <key>=<value> format. The first ? and &
                                        will be added automatically so do not include them in the
                                        front, but do separate multiple query strings with &.
    --redirect-protocol               : The protocol of the destination to where the traffic is
                                        redirected.  Allowed values: HttpOnly, HttpsOnly,
                                        MatchRequest.  Default: MatchRequest.
    --redirect-type                   : The redirect type the rule will use when redirecting
                                        traffic.  Allowed values: Found, Moved, PermanentRedirect,
                                        TemporaryRedirect.  Default: Moved.
```
So as @MyronFanQiu  mentioned ```--backend-pool``` is not an argument that is acceptable for route-type redirect.

We can close this issue.

**Comment by wasker** [comment]
@aramesh-msft  @MyronFanQiu 

Sorry, but this is not an acceptable resolution of this issue. The documentation (below) is confusing: there's nothing that indicates that `--backend-pool` is not needed for "redirect routing rule". The argument just hangs in there, not making any pointers as to when it is needed, and the error message doesn't tell the user that `--backend-pool` is the issue.

If it's only for forwarding rule, then it should be under "forwarding rule arguments" section.

```
$ az network front-door routing-rule create --help

Command
    az network front-door routing-rule create : Create a Front Door routing rule.

[...]

Arguments
    --front-door-name -f   [Required] : Name of the Front Door.
    --frontend-endpoints   [Required] : Space-separated list of frontend endpoint names or IDs.
    --name -n              [Required] : Name of the routing rule.
    --resource-group -g    [Required] : Name of resource group. You can configure the default group
                                        using `az configure --defaults group=<name>`.
    --accepted-protocols              : Space-separated list of protocols to accept. Default: Http.
    --backend-pool                    : Name or ID of a backend pool.
    --disabled                        : Create in a disabled state.  Allowed values: false, true.
    --forwarding-protocol             : Protocol to use for forwarding traffic.
    --patterns                        : Space-separated list of patterns to match. Default: '/*'.

Forward Routing Rule Arguments

[...]

Redirect Routing Rule Arguments
    --custom-fragment                 : Fragment to add to the redirect URL. Fragment is the part of
                                        the URL that comes after #. Do not include the #.
    --custom-host                     : Host to redirect. Leave empty to use use the incoming host
                                        as the destination host.
    --custom-path                     : The full path to redirect. Path cannot be empty and must
                                        start with /. Leave empty to use the incoming path as
                                        destination path.
    --custom-query-string             : The set of query strings to be placed in the redirect URL.
                                        Setting this value would replace any existing query string;
                                        leave empty to preserve the incoming query string. Query
                                        string must be in <key>=<value> format. The first ? and &
                                        will be added automatically so do not include them in the
                                        front, but do separate multiple query strings with &.
    --redirect-protocol               : The protocol of the destination to where the traffic is
                                        redirected.  Allowed values: HttpOnly, HttpsOnly,
                                        MatchRequest.  Default: MatchRequest.
    --redirect-type                   : The redirect type the rule will use when redirecting
                                        traffic.  Allowed values: Found, Moved, PermanentRedirect,
                                        TemporaryRedirect.  Default: Moved.

Routing Rule Arguments
    --route-type           [Required] : Route type to define how Front Door should handle requests
                                        for this route i.e. forward them to a backend or redirect
                                        the users to a different URL.  Allowed values: Forward,
                                        Redirect.
```

**Comment by wasker** [comment]
...and removing `--backend-pool` still doesn't work.

`$ az network front-door routing-rule create --front-door-name myfd --name Hello --resource-group myrg --frontend-endpoints myfd.azurefd.net --route-type Redirect --redirect-type Moved --redirect-protocol HttpsOnly`

```
BadRequest - Missing Hostname for FrontendEndpoint /subscriptions/065f744f-6b6e-4284-a33a-930c139e4f16/resourceGroups/myrg/providers/Microsoft.Network/Frontdoors/myfd/frontendEndpoints/myfd.azurefd.net in RoutingRule Hello.;
A resource reference was invalid: "/subscriptions/065f744f-6b6e-4284-a33a-930c139e4f16/resourceGroups/myrg/providers/Microsoft.Network/Frontdoors/myfd/frontendEndpoints/myfd.azurefd.net"
```

**Comment by aramesh-msft** [comment]
> @aramesh-msft @MyronFanQiu
> 
> Sorry, but this is not an acceptable resolution of this issue. The documentation (below) is confusing: there's nothing that indicates that `--backend-pool` is not needed for "redirect routing rule". The argument just hangs in there, not making any pointers as to when it is needed, and the error message doesn't tell the user that `--backend-pool` is the issue.
> 
> If it's only for forwarding rule, then it should be under "forwarding rule arguments" section.
> 
> ```
> $ az network front-door routing-rule create --help
> 
> Command
>     az network front-door routing-rule create : Create a Front Door routing rule.
> 
> [...]
> 
> Arguments
>     --front-door-name -f   [Required] : Name of the Front Door.
>     --frontend-endpoints   [Required] : Space-separated list of frontend endpoint names or IDs.
>     --name -n              [Required] : Name of the routing rule.
>     --resource-group -g    [Required] : Name of resource group. You can configure the default group
>                                         using `az configure --defaults group=<name>`.
>     --accepted-protocols              : Space-separated list of protocols to accept. Default: Http.
>     --backend-pool                    : Name or ID of a backend pool.
>     --disabled                        : Create in a disabled state.  Allowed values: false, true.
>     --forwarding-protocol             : Protocol to use for forwarding traffic.
>     --patterns                        : Space-separated list of patterns to match. Default: '/*'.
> 
> Forward Routing Rule Arguments
> 
> [...]
> 
> Redirect Routing Rule Arguments
>     --custom-fragment                 : Fragment to add to the redirect URL. Fragment is the part of
>                                         the URL that comes after #. Do not include the #.
>     --custom-host                     : Host to redirect. Leave empty to use use the incoming host
>                                         as the destination host.
>     --custom-path                     : The full path to redirect. Path cannot be empty and must
>                                         start with /. Leave empty to use the incoming path as
>                                         destination path.
>     --custom-query-string             : The set of query strings to be placed in the redirect URL.
>                                         Setting this value would replace any existing query string;
>                                         leave empty to preserve the incoming query string. Query
>                                         string must be in <key>=<value> format. The first ? and &
>                                         will be added automatically so do not include them in the
>                                         front, but do separate multiple query strings with &.
>     --redirect-protocol               : The protocol of the destination to where the traffic is
>                                         redirected.  Allowed values: HttpOnly, HttpsOnly,
>                                         MatchRequest.  Default: MatchRequest.
>     --redirect-type                   : The redirect type the rule will use when redirecting
>                                         traffic.  Allowed values: Found, Moved, PermanentRedirect,
>                                         TemporaryRedirect.  Default: Moved.
> 
> Routing Rule Arguments
>     --route-type           [Required] : Route type to define how Front Door should handle requests
>                                         for this route i.e. forward them to a backend or redirect
>                                         the users to a different URL.  Allowed values: Forward,
>                                         Redirect.
> ```

Please update your installation of Azure CLI (at least 2.4x) and front-door extension (1.0.6)

I see correct arguments

```
Forward Routing Rule Arguments
    --backend-pool                    : Name or ID of a backend pool. It's required to create a
                                        Forward routing rule.
    --caching                         : Whether to enable caching for this route.  Allowed values:
                                        Disabled, Enabled.
    --custom-forwarding-path          : Custom path used to rewrite resource paths matched by this
                                        rule. Leave empty to use incoming path.
    --dynamic-compression             : Use dynamic compression for cached content.  Allowed values:
                                        Disabled, Enabled.
    --forwarding-protocol             : Protocol to use for forwarding traffic.
    --query-parameter-strip-directive : Treatment of URL query terms when forming the cache key.
                                        Allowed values: StripAll, StripAllExcept, StripNone,
                                        StripOnly.
```

**Comment by wasker** [comment]
@aramesh-msft 

Success!

My front-door ext was 1.0.4 and the last attempt to create a rule didn't use frontend *name*.

Upgraded to 1.0.6 and used correct *name* - worked out.

Thank you!

**Comment by loga0060** [comment]
Hello, is there a way in AFD where we can preserve the key and add to the query string
example request www.abc.com/billing?cm_cat=exacttarget should be routed to something like www.def.com/my-account/login?brand=test&cm_cat=exacttarget  so is there a way to append to the query string and also preserve the query string in request?
