### ISSUE TITLE
AZ Storage-preview download directory doesn't work

### ISSUE THREAD

**Issue by auramirea** [Azure/azure-cli-extensions#1597]
## Describe the bug

**Command Name**
`az storage blob directory download
Extension Name: storage-preview. Version: 0.2.10.`

**Errors:**
```
[Errno 2] No such file or directory: '/home/aura/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.3.1/azcopy copy https://<removed>.blob.core.windows.net/vendors/vendor1?se=2020-04-25T10%3A39%3A01Z&sp=<removed>&sv=2018-03-28&ss=b&srt=sco&sig=<removed> /home/aura/store --recursive': '/home/aura/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.3.1/azcopy copy https://<removed>.blob.core.windows.net/vendors/vendor1?se=2020-04-25T10%3A39%3A01Z&sp=<removed>&sv=2018-03-28&ss=b&srt=sco&sig=<removed> /home/aura/store --recursive'
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob directory download -d {} -s {} -c {} --recursive --account-name {}`

## Expected Behavior
Download directory

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5

azure-cli 2.2.0 *
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1
azure-devops 0.12.0
spring-cloud 0.1.0
storage-preview 0.2.10

```

**Comment by yonzhan** [comment]
add to S170

**Comment by Juliehzl** [comment]
Hi @auramirea, I cannot reproduce your issue now. Could you share log file with me to help figure out the issue in your scenario?
