### ISSUE TITLE
publish is failing without change notes

### ISSUE THREAD

**Issue by brennaman** [Azure/azure-cli-extensions#1598]
az blueprint publish is failing when --change-notes are not supplied even though parameter is optional.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82aa0874-eb79-9bed-f3fc-3a0e6d923c50
* Version Independent ID: 1971ba1e-c071-587c-2673-70d0a659cc32
* Content: [az blueprint](https://docs.microsoft.com/en-us/cli/azure/ext/blueprint/blueprint?view=azure-cli-latest#ext-blueprint-az-blueprint-publish)
* Content Source: [latest/docs-ref-autogen/ext/blueprint/blueprint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/blueprint/blueprint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look
