### ISSUE TITLE
CI should capture bug that a folder don't have __init__.py but want to include it as a Python package

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-cli-extensions#1608]
### Extension name (the extension in question)
portal

### Description of issue (in as much detail as possible)
If a folder don't have a \_\_init\_\_.py and use `find_packages()` in setup.py, then the build tool won't regard it as a valid Python Package, the the built wheel won't pack it into the wheel file.

For example this warning from Azure/azure-cli PR stage:
![image](https://user-images.githubusercontent.com/14357159/80340254-e235c980-8892-11ea-8019-81cfc8a4cc2c.png)
it's caused by the `portal` extension which doesn't have a \_\_init\_\_.py under `src/portal/azext_portal/generated/`

CI should block and give warning

**Comment by yonzhan** [comment]
add to S170

**Comment by haroldrandom** [comment]
Closed as plan to onboard pytest to azure-cli-extension CI.
