### ISSUE TITLE
How can a query be saved using the Azure CLI?

### ISSUE THREAD

**Issue by mikemowgli** [Azure/azure-cli-extensions#1613]
How can a query be saved using the Azure CLI so that it appears in the Query explorer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0fd6a58-ac1a-fa45-8d96-579b4af36499
* Version Independent ID: 4098ca97-1b85-eb29-18e9-e6f0495fd030
* Content: [az monitor log-analytics](https://docs.microsoft.com/en-us/cli/azure/ext/log-analytics/monitor/log-analytics?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@mikemowgli Hi. Currently we don't support this one. It should be CRUD for SavedSearches. I would mark it as feature request and put this one into our working list.

**Comment by yonzhan** [comment]
add to backlog
