### ISSUE TITLE
blueprints extension listed in .whl but not available in CLI

### ISSUE THREAD

**Issue by kfprugger** [Azure/azure-cli-extensions#1614]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
blueprint

### Description of issue (in as much detail as possible)
Candidates ['blueprint-0.1.0-py3-none-any.whl']
Skipping 'blueprint-0.1.0-py3-none-any.whl' as not universal wheel.We do not currently support platform specific extension detection. They can be installed with the full URL https://azurecliprod.blob.core.windows.net/cli-extensions/blueprint-0.1.0-py3-none-any.whl
Candidates []
Candidates []
No suitable extensions found.

-----
![image](https://user-images.githubusercontent.com/20729981/80423055-406fa600-88ad-11ea-9443-1667bae60a7b.png)

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
@kfprugger can you upgrade to the latest Azure CLI? The extension is not compatible with 2.2.0.

**Comment by kfprugger** [comment]
Thanks, Feng!

I had to "reboot" the shell in Azure and the new Az CLI was installed when it came back online. 

Could we consider auto-rebooting the shells weekly to ensure that all customers don't have this same experience by having an out-of-date CLI instance on their Azure Cloud Shells?

The documentation for updating the shell on MS Docs include 'sudo' and sudo is denied on the Cloud Shell as you know.

Thanks for the help!

**Comment by fengzhou-msft** [comment]
@kfprugger Azure Cloud Shell has a release cadence of every three weeks. That seems to be the only way to update Azure CLI on it now. Azure CLI usually keeps pace with Cloud Shell except when there's code freeze in Cloud Shell (freezed for 2.3.0, so you upgraded from 2.2.0 to 2.4.0, I guess) or Azure CLI has some urgent release such as the latest 2.5.0. 

As for the auto reboot of Cloud Shell, @maertendMSFT can we do it with some configurations now?
