### ISSUE TITLE
Details on --overwrite param of upload command

### ISSUE THREAD

**Issue by mariamedp** [Azure/azure-cli-extensions#1625]
It would be nice to have more details on the --overwrite param. My first reaction was trying to use it as a flag (just --overwrite, with no value), but then I found out it had to be set to "true". I think that should be explicitly mentioned in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c99b13-9888-31ac-9e22-4bac0cb3956a
* Version Independent ID: 7aef098d-0f55-e080-cce4-91ad6265d974
* Content: [az ml datastore](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-ml/ml/datastore?view=azure-cli-latest#ext-azure-cli-ml-az-ml-datastore-upload)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-ml/ml/datastore.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-ml/ml/datastore.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
machine learning commands, routing to appropriate team

**Comment by meyetman** [comment]
Hi @mariamedp, we recommend everyone to use file dataset upload directory https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.dataset_factory.filedatasetfactory?view=azure-ml-py#upload-directory-src-dir--target--pattern-none--overwrite-false--show-progress-true- to upload data, not datastore upload. File dataset does allow overwrite to be true/false. Thanks! #please-close
