### ISSUE TITLE
Set retention time in application-insights

### ISSUE THREAD

**Issue by seriema** [Azure/azure-cli-extensions#1638]
### Extension name (the extension in question)
application-insights

### Description of issue (in as much detail as possible)
There does not seem to be a flag or command to change the default 90 days retention period to something else. Currently we have to fallback to the PowerShell Azure module to set the retention period on the Application Insight resource created with the AZ CLI. It would be preferable to use the CLI.

```powershell
# Install extension
az extension add -n application-insights
# Create the AI resource
az monitor app-insights component create -a $appInsights -l $location -g $rgTelemetry

# All this to change the retention day from default 90:
$retentionInDays = 730 # 730 is the maximum
$aiInstance = Get-AzResource -ResourceGroupName $rgTelemetry -Name $appInsights -ResourceType "microsoft.insights/components"
if($($aiInstance.properties | Get-Member -Name "RetentionInDays" -MemberType Properties))
{
    $aiInstance.properties.RetentionInDays = $retentionInDays 
}
else
{
    $aiInstance.properties | Add-Member -Type NoteProperty -Name "RetentionInDays" -Value $retentionInDays
}

$aiInstance | Set-AzResource -Force
```

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@jsntcy  Could you take a look?

**Comment by Tyriar** [comment]
It also doesn't seem to be anywhere in an exported ARM template which would be the easier way for me.
