### ISSUE TITLE
"az devops security permission update" doesn't update the permission in the web UI?

### ISSUE THREAD

**Issue by pietergheysens** [Azure/azure-cli-extensions#1639]
### Extension name (the extension in question)
az devops

### Description of issue (in as much detail as possible)
Goal: set Team Project permission "View project-level information" to Allow for a newly created security group in an existing Team Project.

1. running the update command and passing id, subject and token

`az devops security permission update --id "52d39943-cb85-4d7f-8fa8-c6baac873819" --subject "vssgp.<descriptorvalue>" --token "$PROJECT:vstfs:///Classification/TeamProject/<teamprojectid>" --allow-bit 1
`
2. result from command ... All good!

![image](https://user-images.githubusercontent.com/1761094/80976909-51c42f80-8e24-11ea-9900-ab390747ec3f.png)

3. result from web UI ... permission not set?!

![image](https://user-images.githubusercontent.com/1761094/80976985-6a344a00-8e24-11ea-902f-92b49c2047a6.png)

Hard refreshing, Logging out/in, incognito window ... nothing shows the updated permission in the web UI. What am I doing wrong to correctly update the "project" permission of the security group? From the command, all looks fine. Looking for help!

**Comment by yonzhan** [comment]
devops

**Comment by pietergheysens** [comment]
I fixed my issue using single quotes instead of double quotes for the token argument: --token '$PROJECT:vstfs:///Classification/TeamProject/<teamprojectid>'. Still not sure why the command seemed to succeed with double quotes and showing the correct result in the command window? Happy to have finally found a solution, but this has been a very frustrating experience!
