### ISSUE TITLE
Configure continuous export with application-insights

### ISSUE THREAD

**Issue by seriema** [Azure/azure-cli-extensions#1640]
### Extension name (the extension in question)
application-insights

### Description of issue (in as much detail as possible)
There does not seem to be a flag or command to set up a continuous export from an AI resource. Currently we have to fallback to the PowerShell Azure module to set up continuous export from the Application Insight to the Blob Storage, both resources created with the AZ CLI. It would be preferable to use the CLI all the way.

```powershell
# Install extension
az extension add -n application-insights
# Create the AI resource
az monitor app-insights component create -a $appInsights -l $location -g $rgTelemetry
# Create the blob storage
az storage account create -n $persistentStorageAccount -l $location -g $rgTelemetryStorage --sku $sku
az storage container create --name $persistentStorageContainer --account-name $persistentStorageAccount

# All this to set up continuous export:
$storageAccount = Get-AzStorageAccount -Name $persistentStorageAccount -ResourceGroup $rgTelemetryStorage
$sasuri = New-AzStorageContainerSASToken -Name $persistentStorageContainer -Context $storageAccount.Context -Permission w -FullUri -ExpiryTime (Get-Date).AddYears(50)

$continuousExportParams = @{
    'Name'              = $appInsights;
    'ResourceGroupName' = $rgTelemetry;
    'StorageAccountId'  = $storageAccount.Id;
    'StorageLocation'   = $location;
    'StorageSASUri'     = $sasuri;
    'DocumentType'      = "Request", "Exception", "Custom Event", "Trace", "Metric", "Page Load", "Page View", "Dependency", "Availability", "Performance Counter";
}

$instance = Get-AzApplicationInsightsContinuousExport -Name $location -ResourceGroupName $rgTelemetry -ErrorAction SilentlyContinue

if ($instance) {
    Set-AzApplicationInsightsContinuousExport @continuousExportParams -ExportId $instance.exportId
}
else {
    New-AzApplicationInsightsContinuousExport @continuousExportParams
}
```

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentContinuousExport_API.json

**Comment by angusmack-altius** [comment]
Hi. Does this mean it's on the backlog for Sprint 172? Just checking when we can expect this to be released?

The above tagging is a bit confusing to me!  :-)

Thanks!

**Comment by MyronFanQiu** [comment]
> Hi. Does this mean it's on the backlog for Sprint 172? Just checking when we can expect this to be released?
> 
> The above tagging is a bit confusing to me! :-)
> 
> Thanks!

Hi @angusmack-altius We don't have enough resource to do it right now and we move it to backlog. I don't know the ETA as well.

**Comment by MyronFanQiu** [comment]
@angusmack-altius There is an incoming Ignite Event and we focus on that. I think we should be able to do it after that but I cannot guarantee. I will keep you posted once we make a plan for this feature request.
