### ISSUE TITLE
When will the option node-resource-group be available in azure cli?

### ISSUE THREAD

**Issue by yene** [Azure/azure-cli-extensions#1646]
hi,

I used the `--node-resource-group` parameter for a few times now and it seems really useful to provide your own naming scheme. Will this feature be ported to the normal az cli?

thanks

**Comment by yonzhan** [comment]
@yene  what is the scope of this parameter?

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by yungezz** [comment]
hi @yene could you pls share which az commands you're using?AKS? thanks.

**Comment by yene** [comment]
Thanks for the responses.
The parameter `--node-resource-group` allows us to provide a more readable RG name (like `rg-company-prod-aksmanaged`), and follow the companies naming convention.

Without it will generate a name like: `MC_rg-company-prod_aks-company-prod_eastus`

```bash
az aks create \
    --resource-group rg-company-prod \
    --name aks-company-prod \
    --node-count 1 \
    --node-resource-group rg-company-prod-aksmanaged
```

**Comment by lgmorand** [comment]
same need here. It's been in preview for six months

**Comment by lgmorand** [comment]
@yene if I'm not wrong, I got this well-placed info that it should be **included this month**. We still keep the limitation of providing a non-existing RG, because AKS need a dedicated RG to stores its resources

**Comment by yene** [comment]
Thank you to everyone involved. Good work!

**Comment by scottstout** [comment]
This flag still seems to be only available in the preview module?
