### ISSUE TITLE
Set primary key and second key doesn't work

### ISSUE THREAD

**Issue by yixwang** [Azure/azure-cli-extensions#1647]
Trying to deploy the model with primary key and second key set. The following command doesn't work. (PRIMARY_KEY and SECONDARY_KEY along with others are string values.)
```
az ml model deploy -m ${SVD_MODEL_ID} -m ${TFIDF_MODEL_ID} -m ${KMEAN_MODEL_ID} -n ${ACI_PREFIX}-aci --workspace-name ${WORKSPACE} --resource-group ${RESOURCEGROUP_NAME} --ic ./inferenceconfig.json --dc ./deploymentconfig.json --auth-enabled True --primary-key ${PRIMARY_KEY} --secondary-key ${SECONDARY_KEY}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8825dded-3381-d6ed-3473-6cc67086b1b1
* Version Independent ID: 78430b7b-24a7-a0bf-c429-dc97a2c4f55a
* Content: [az ml model](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-ml/ml/model?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-ml/ml/model.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-ml/ml/model.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by yixwang** [comment]
Let's clarify a bit. The model is deployed successfully. However, the primary and secondary are still the generated values instead of the values I set in the command

**Comment by azureml-github** [comment]
@Inference Area<mailto:inferencetrack@microsoft.com>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Bozhong68** [comment]
Hi all, this should work now in the latest SDK.

**Comment by Bozhong68** [comment]
@DebFro please close, not sure why I couldn't close it.
