### ISSUE TITLE
Unable to install AEM on SUSE 15 SP1

### ISSUE THREAD

**Issue by narookak** [Azure/azure-cli-extensions#1650]
## Describe the bug

**Command Name**
`az vm aem set
Extension Name: aem. Version: 0.1.1.`

**Errors:**
```
'account_name'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aem/azext_aem/custom.py, ln 32, in set_aem
    aem.enable()
cliextensions/aem/azext_aem/custom.py, ln 62, in enable
    pub_cfg, pri_cfg = self._build_extension_cfgs(self._get_disk_info())
cliextensions/aem/azext_aem/custom.py, ln 237, in _build_extension_cfgs
    'disk.connminute' + suffix: disk['account_name'] + '.minute',
KeyError: 'account_name'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm aem set -g {} -n {}`

## Expected Behavior
AEM installed without error
## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

Extensions:
aem 0.1.1

```

**Comment by victorrodilla** [comment]
I receive same error for SLES VM. I tried to install with PowerShell

Set-AzureRMVMAEMExtension -ResourceGroupName $resourceGroupName -VMName $vmName

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by qwordy** [comment]
I run the following commands and no error.
```
az vm aem set -g fytest4 -n vm1
az vm create -g fytest4 -n vm1 --image SUSE:sles-15-sp1:gen1:2020.02.26
```
How do you create the VM? Can you share your command?

**Comment by narookak** [comment]
we use terraform to launch the instance. 
Still having the issue, tried using PowerShell and cloudshell. without any luck. Let me know if need anything else to resolve this.

**Comment by qwordy** [comment]
`disk['account_name']` should be `storage_account_name` according the source code.
"Still having the issue, tried using PowerShell and cloudshell. without any luck". It indicates that it is not only a problem in Azure CLI. Could you try using Azure CLI instead of Terraform to see if it still happens?

**Comment by yungezz** [comment]
hi @narookak is there any update?

**Comment by narookak** [comment]
We manage to resolve this using the latest extension for SLES 15.  
Anyone still having the issue, Please follow the updated [SAP deployment guide](http://docs.microsoft.com/azure/virtual-machines/workloads/sap/deployment-guide)


### Install using Powershell or Azure CLI
#The following links describe how you can install the new extension using PowerShell or Azure CLI
```
http://docs.microsoft.com/azure/virtual-machines/workloads/sap/deployment-guide#2ad55a0d-9937-4943-9dd2-69bc2b5d3de0
http://docs.microsoft.com/azure/virtual-machines/workloads/sap/deployment-guide#c8749c24-fada-42ad-b114-f9aae2dc37da
 ```

**Comment by qwordy** [comment]
Glad to know that. Close this issue.

**Comment by yungezz** [comment]
cc @fengzhou-msft for awareness
