### ISSUE TITLE
'az hack create' Issue encountered running lab @ https://github.com/microsoft/Reactors/tree/master/AI_1

### ISSUE THREAD

**Issue by prfinnie** [Azure/azure-cli-extensions#1653]
## Describe the bug

**Command Name**
`az hack create`

**Errors:**
```
invalid syntax (_database_utils.py, line 30)
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
cliextensions/hack/azext_hack/custom.py, ln 12, in <module>
    from ._database_utils import Database
cliextensions/hack/azext_hack/_database_utils.py, ln 30
    def __init__(self, name: str, delegate, params):
                           ^
SyntaxError: invalid syntax
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az hack create --name {} --runtime {} --location {} -a{} --output {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
Python 2.7.15+
Shell: bash

azure-cli 2.0.81

Extensions:
hack 0.4.1

```

**Comment by GeekTrainer** [comment]
The challenge is the version of Python. This extension (as does the CLI as a whole) requires Python 3.

@jsntcy

**Comment by jsntcy** [comment]
@prfinnie, could you upgrade to python3+ to see if this issue is solved as this extension is using python3?

@GeekTrainer, thanks for your help.

**Comment by jsntcy** [comment]
@prfinnie, did you have a chance to try python3?

**Comment by jsntcy** [comment]
I closed this issue now as it's not an issue in CLI.
@prfinnie, please try python 3, if the issue still exists, please reopen this issue.
