### ISSUE TITLE
az iot device c2d-message send message count is not available

### ISSUE THREAD

**Issue by ankur198** [Azure/azure-cli-extensions#1654]
Running 
`az iot device c2d-message send --hub-name $hubName --device-id $deviceId --msg-count 5`

gives an error az: error: unrecognized arguments: --msg-count 5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf700574-7619-93a3-5da4-d7274160ad80
* Version Independent ID: fecb6e3e-5b4d-07b1-df6c-01ec7cc87ba6
* Content: [az iot device](https://docs.microsoft.com/en-us/cli/azure/ext/azure-iot/iot/device?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-iot/iot/device.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-iot/iot/device.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ankur198** [comment]
![image](https://user-images.githubusercontent.com/19951777/81161233-e22b7d00-8fa8-11ea-95a2-a7cb5e959fe6.png)

message count does not show up as an option in vs code as well

**Comment by ankur198** [comment]
![image](https://user-images.githubusercontent.com/19951777/81161379-1e5edd80-8fa9-11ea-826b-bbf1ff0c2bc4.png)

Message count option does not show up in vs code as well

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by yiyiguo** [comment]
@Azure/azure-iot-cli-triage

**Comment by prbans** [comment]
@ankur198 what version of CLI are you using?
