### ISSUE TITLE
timeseriesinsights - timeSeriesIdPropertyName is not parsed properly

### ISSUE THREAD

**Issue by riserrad** [Azure/azure-cli-extensions#1657]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
timeseriesinsights

### Description of issue (in as much detail as possible)
When creating a new longterm Environment, the `timeSeriesIdPropertyName` is not parsed properly.

For example, if we use the following command, exactly as documented:

```
az timeseriesinsights environment longterm create -g $rg --name $env_lt --location westus --sku-name L1 --sku-capacity 1 --data-retention 7 --time-series-id-properties DeviceId1 --storage-account-name $storage --storage-management-key $key
```
The one timeSeriesIdProperty we would have should be named `DeviceId`. But it ends up like this:

```
"timeSeriesIdProperties": [
{
  "name": "['DeviceId1']",
  "type": "String"
}
```
-----

**Comment by yonzhan** [comment]
add to S170
