### ISSUE TITLE
timeseriesinsights - When creating a new Standard Environment, data-retention-time is not properly documented

### ISSUE THREAD

**Issue by riserrad** [Azure/azure-cli-extensions#1658]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
timeseriesinsights

### Description of issue (in as much detail as possible)
When creating a new Standard Environment, data-retention-time is not properly documented. The command sample is:

```
az timeseriesinsights environment standard ... --data-retention-time P31D ...
```

When it should be
```
az timeseriesinsights environment standard ... --data-retention-time 31 ...
```
-----

**Comment by yonzhan** [comment]
add to S170
