### ISSUE TITLE
README.md for resource-graph is incorrect

### ISSUE THREAD

**Issue by bquantump** [Azure/azure-cli-extensions#1663]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Resource-graph

### Description of issue (in as much detail as possible)
The README.md says it is a readme for Blueprint when it should say it is for resource graph:

![image](https://user-images.githubusercontent.com/53361486/81325876-da71e400-904d-11ea-99bd-a2f4b80ab7bb.png)

-----

**Comment by yonzhan** [comment]
resource-graph

**Comment by yungezz** [comment]
fixed
