### ISSUE TITLE
timeseriesinsights - Have an exponential backoff when the request sent fails

### ISSUE THREAD

**Issue by riserrad** [Azure/azure-cli-extensions#1664]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
timeseriesinsights

### Description of issue (in as much detail as possible)
When the deployment hits an issue (i.e., no resources available to provision the given Sku in the region), the CLI keeps resending the request until it fails with the error `'too many 500 response'`.

We should have an exponential backoff in this case.
-----

**Comment by yungezz** [comment]
hi @jiasli could you have a look?

**Comment by jiasli** [comment]
When **no resources available to provision the given Sku in the region** happens, what is the HTTP status code? Is it 429? Does the response have `Retry-After` header?

I believe the retry logic is controlled by Python SDK and [msrest](https://github.com/Azure/msrest-for-python), thus out of CLI's control. msrest does honor `Retry-After` header.

The default retry policy of msrest is

https://github.com/Azure/msrest-for-python/blob/9e2e6529ac3cc91454a859c01775493872b20e92/msrest/universal_http/requests.py#L343-L349

```py
    def __init__(self):
        self.policy = Retry()
        self.policy.total = 3
        self.policy.connect = 3
        self.policy.read = 3
        self.policy.backoff_factor = 0.8
        self.policy.BACKOFF_MAX = 90
```

**Comment by yonzhan** [comment]
add to S170

**Comment by riserrad** [comment]
> When **no resources available to provision the given Sku in the region** happens, what is the HTTP status code? Is it 429? Does the response have `Retry-After` header?
> 
> I believe the retry logic is controlled by Python SDK and [msrest](https://github.com/Azure/msrest-for-python), thus out of CLI's control. msrest does honor `Retry-After` header.
> 
> The default retry policy of msrest is
> 
> https://github.com/Azure/msrest-for-python/blob/9e2e6529ac3cc91454a859c01775493872b20e92/msrest/universal_http/requests.py#L343-L349
> 
> ```python
>     def __init__(self):
>         self.policy = Retry()
>         self.policy.total = 3
>         self.policy.connect = 3
>         self.policy.read = 3
>         self.policy.backoff_factor = 0.8
>         self.policy.BACKOFF_MAX = 90
> ```

No, it returns 503 (Internal Server Error) with the `InsufficientInternalResources` error code. No `Retry-After` header is added to the response.

`no resources available to provision the given Sku in the region` is not a throttling error. It means that we don't have resources to provision the Environment.

The requests are throttled automatically by ARM. What I meant is that we shouldn't retry failed requests - not only this one, probably all of them - without a Retry Policy with an exponential backoff, otherwise the routine is going to be throttled and the original error is going to be swallowed by the throttling error from ARM.

**Comment by riserrad** [comment]
Hi @jiasli ,

According to the e-mail thread we've been through, I've updated the description of the issue.

The expected behavior is to have an exponential backoff and that it should not fail this fast when getting errors 500, like it happens when we try the same action in Azure Portal.

As you mentioned, while we don't migrated to track 2 SDK and Azure Core, we can't have more control over the retry logic.

Can we keep this issue open for tracking purposes so we tackle it as soon as you migrate?

**Comment by riserrad** [comment]
And here's the log we've been looking into, with redacted information:

```
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/riserrad-insufficient-resources?api-version=2018-08-15-preview HTTP/1.1" 500 7971
urllib3.util.retry : Incremented Retry for (url='/subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/riserrad-insufficient-resources?api-version=2018-08-15-preview'): Retry(total=3, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/riserrad-insufficient-resources?api-version=2018-08-15-preview
urllib3.connectionpool : Resetting dropped connection: management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/riserrad-insufficient-resources?api-version=2018-08-15-preview HTTP/1.1" 500 7971
urllib3.util.retry : Incremented Retry for (url='/subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/riserrad-insufficient-resources?api-version=2018-08-15-preview'): Retry(total=2, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview
urllib3.connectionpool : Resetting dropped connection: management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview HTTP/1.1" 500 7971
urllib3.util.retry : Incremented Retry for (url='/subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview'): Retry(total=1, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview
urllib3.connectionpool : Resetting dropped connection: management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview HTTP/1.1" 500 7971
urllib3.util.retry : Incremented Retry for (url='/subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview'): Retry(total=0, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview
urllib3.connectionpool : Resetting dropped connection: management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview HTTP/1.1" 500 7971
msrest.exceptions : Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview (Caused by ResponseError('too many 500 error responses',))
cli.azure.cli.core.util : request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview (Caused by ResponseError('too many 500 error responses',))
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<REDACTED SUB ID>/resourceGroups/<REDACTED RG NAME>/providers/Microsoft.TimeSeriesInsights/environments/<REDACTED ENV NAME>?api-version=2018-08-15-preview (Caused by ResponseError('too many 500 error responses',))
```

**Comment by jiasli** [comment]
Azure CLI internally relies on `urllib3`'s retry logic. As `500` is returned by ARM, we need further ARM log to investigate.
