### ISSUE TITLE
az batch pool create 

### ISSUE THREAD

**Issue by mandargujrathi** [Azure/azure-cli-extensions#1668]
## Describe the bug

**Command Name**
`az batch pool create
Extension Name: azure-batch-cli-extensions. Version: 3.0.3.`

**Errors:**
```
Template missing required 'pool' element
Traceback (most recent call last):
azext\batch\operations\pool_operations.py, ln 46, in expand_template
    return expanded_pool_object['pool']
KeyError: 'pool'

...

azext\batch\operations\pool_operations.py, ln 48, in expand_template
    raise ValueError("Template missing required 'pool' element")
ValueError: Template missing required 'pool' element
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az batch pool create --template {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.64 *

Extensions:
azure-batch-cli-extensions 3.0.3

```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by bgklein** [comment]
Do you have a sample of your template? The template functions has an explicit syntax which isn't simply the --json-file argument.

You can find a sample at https://github.com/Azure/azure-batch-cli-extensions/blob/master/samples/hello-world/create-pool-and-job/pool.json

**Comment by bgklein** [comment]
Closing due to no response
