### ISSUE TITLE
Unable to delete IP group asscoiated to non-existing resource

### ISSUE THREAD

**Issue by aggerritsen** [Azure/azure-cli-extensions#1670]
Hi,

When using 

&gt; az network ip-group delete -n azure-all -g management-rg (az version 2.5.1 and earlier)

it seems impossible to delete an IP Group that used to be associates to a Azure Firewall Rule set that no longer exist. 

Error: IpGroupsHasResourceReferences - IpGroups '/subscriptions/***/resourcegroups/Management-rg/providers/Microsoft.Network/ipGroups/AZURE-ALL' cannot be deleted since there are other Azure Resources using this resource. Subsequently the Resource Group where this IP Group resides can not be deleted neither.

Please advise, because we are stuck on remove old stuff now.

Kind regards, Arjen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cacec59-2882-a074-136b-a4a1896e97c1
* Version Independent ID: 1c0fbb79-e36c-2e18-0293-67ebff1a53e7
* Content: [az network ip-group](https://docs.microsoft.com/en-us/cli/azure/ext/ip-group/network/ip-group?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/ip-group/network/ip-group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/ip-group/network/ip-group.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by aggerritsen** [comment]
I ended up with creating some a dummy firewall with identical names, added network rules and deleting them. Atfter this I w2as able to delete the IP group And deleted the dummy firewall.

Kind regards, Arjen
