### ISSUE TITLE
az resource-graph extension 1.1.0 doesn't support --include displayNames

### ISSUE THREAD

**Issue by sunnyjit** [Azure/azure-cli-extensions#1673]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.3.1
2.5.0

**Describe the bug**
az graph query --first 1 -q "Resources | where type =~ 'microsoft.compute/disks' | where properties.diskState =~ 'Unattached' "  --include displayNames
It gives the result but without including subscription names 

"Failed to include displayNames to result. Error: 'displayName' " .

**To Reproduce**

**Expected behavior**
It should display subscription name along with Subscription name .
It is working fine with azure cli 2.3.1 and graph extension version 1.0.0
**Environment summary**
azure-cli                          2.3.1 *

command-modules-nspkg              2.0.3
core                               2.3.1 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
resource-graph                     1.1.0

Python location '/usr/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Jun 11 2019, 15:15:01) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Additional context**

**Comment by yungezz** [comment]
hi @MyronFanQiu  @bquantump could you have a look?

**Comment by yonzhan** [comment]
add to S170

**Comment by bquantump** [comment]
I cannot seem to reproduce the problem so far. @sunnyjit is there any information you can provide in the reproduce section that may help?

**Comment by MyronFanQiu** [comment]
@sunnyjit Kindly ping.

**Comment by yonzhan** [comment]
@sunnyjit any update?

**Comment by sunnyjit** [comment]
Hi,
Sorry for replying late but I came to know that this is a known issue .
Generally when we run a graph query we get subscription id which is an alphanumeric type of string.
When we use --include displayname parameter the actual subscription name is also displayed as subscriptiondisplayname : <name of subsccription> .

This reply from support team says it will take time

```
This is a known bug in the newer
versions of the CLI extension of the resource graph. Unfortunately this fix seems
to need a significant refactoring of the module and the engineering team now
decided to de-prioritize this as there seems to be more critical updates in the
pipeline for resource graph 
``` 

however what surprised me is that with same az cli version on mac it works fine, it works fine on azure cloud shell also ( az cli 2.4.1) but on RHEL instances 7.0 and >7.0 even old cli don't support this functionality.

**Comment by snaheth** [comment]
Hi @sunnyjit -- I'm on the Azure Resource Graph team. Thanks for opening this issue. We've known about  `--include displayNames` being broken and we're planning to deprecate it or rewrite it to correctly assemble the query (currently preferring the former).

This approach checks a local cache (which can be problematic on its own as we see in the Exception you shared). We recommend that you utilize the ```ResourceContainers``` table directly in your query to get what you're looking for from Resource Group (+ this data is up-to-date). Here's an example:
```
Resources
| take 50 // write your main query here
| join kind=leftouter
	(
		ResourceContainers
		| where type=='microsoft.resources/subscriptions'
		| project subscriptionDisplayName = name, subscriptionId
	) on subscriptionId
| project id, type, name, subscriptionDisplayName
```
