### ISSUE TITLE
Execute a saved/shared query by providing its name?  

### ISSUE THREAD

**Issue by mpchen** [Azure/azure-cli-extensions#1678]
Is it possible to execute a saved/shared query by providing its name as the parameter? This would be very helpful when I have a complex query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75d1021b-9184-56de-3a65-4680868c9143
* Version Independent ID: f2fb2ab8-c0c6-5350-a99a-5a5b90e2b14b
* Content: [az graph](https://docs.microsoft.com/en-us/cli/azure/ext/resource-graph/graph?view=azure-cli-latest#ext-resource-graph-az-graph-query)
* Content Source: [latest/docs-ref-autogen/ext/resource-graph/graph.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/resource-graph/graph.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
resource graph

**Comment by pposkrobko** [comment]
Good news, it is possible! The feature is still in preview though, so keep in mind that usage might change. The current way to use it is as follows - just run below as your query (against regular **resources** endpoint)
`{{/subscriptions/<SUB_ID>/resourceGroups/<RG_NAME>/providers/microsoft.resourcegraph/queries/<QUERY_NAME>}}`

You can use Resource Graph Explorer in Azure Portal for it, REST API, etc.

You can also mix those references with 'literal' queries, e.g.

`resources | where location == 'eastus' | {{/subscriptions/<SUB_ID>/resourceGroups/<RG_NAME>/providers/microsoft.resourcegraph/queries/<QUERY_NAME>}} | summarize count() by type`

**Comment by mpchen** [comment]
Thanks for the reply. Will this work for private query as well? Shared queries are stored in a RG. It is not clear to me where private query are stored.

**Comment by mpchen** [comment]
Also, could you provide more details? If I want to run it via REST API, is it a "GET", "POST" or "PUT"? I tried "GET" and it returns the details of the query. And "POST" and "PUT" are not supported. Which API version should I use? thnx.

**Comment by chiragg4u** [comment]
@mpchen please find the Swagger information @ https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resourcegraph/resource-manager/Microsoft.ResourceGraph/preview/2018-09-01-preview/graphquery.json 
Would appreciate if you can vote @ https://feedback.azure.com/forums/915958-azure-governance?category_id=345061 for any feedback and features.

**Comment by chiragg4u** [comment]
> Thanks for the reply. Will this work for private query as well? Shared queries are stored in a RG. It is not clear to me where private query are stored.

Private query is a portal only construct, and kept in Portal User metadata.

**Comment by pposkrobko** [comment]
@mpchen, by REST API I meant */resources* endpoint, you run it like you would run a regular 'text literal' query: https://docs.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph(2019-04-01)/resources/resources
