### ISSUE TITLE
AKS Private-Cluster fails with Nonetype stackTrace via Jumpbox

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/azure-cli-extensions#1679]
### Extension name (the extension in question)

* `aks-preview`

### Description of issue (in as much detail as possible)

_Before I detail_: This is placeholder issue for transparency, plus to log and correctly identify the `aks private-cluster` behavior to rectify the code. If this is Network \ Storage issue then its worth to identify that as well and involve right folks to identify correct fix for it.

**Steps to Reproduce**:

* Create az-aks Private cluster: https://docs.microsoft.com/en-us/azure/aks/private-clusters
	* Obviously from the local dev box the `privatelink` will not be visible so pursue the `jumpbox` vm approach. i.e. create vm in same subnet as aks private cluster.
* After creating jumpbox vm > install and run `az cli` and add > `aks=preview` extension.
* Run `AKS Kollect` command for the private cluster from the jumpbox, the [`aks_kollect` call ](https://github.com/Azure/azure-cli-extensions/blob/master/src/aks-preview/azext_aks_preview/custom.py#L1321) **fails to get any result for line** `1332` -- `client.get` call in `custom.py`  gives empty result for the `private cluster` hence the error like below where it tries toaccess `fqdn` (fullyqualified domain name) but it is `None` or refer to screenshot. This might very well be connected to a portal issue where for the `private ak cluster` the **Properties** tab shows empty API Server address.

* This issue needs deeper investigation and then right solution needs to be implemented. If you know much about how `Private-Cluster` behave please feel free to reachout.
    * Further: if its the case where >> `kollect` command do not support `private-cluster` we should update docs to represent that.

Please feel free to assign back to me, but this is added for mere transparency and to get right folks eyes for comments.

Just as fyi: @Jen7714 and @yunjchoi 

```
  File "/root/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1485, in aks_kollect
    normalized_fqdn = mc.fqdn.replace('.', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
```

![image](https://user-images.githubusercontent.com/6233295/81518926-a66f2980-9393-11ea-8223-5070acc0ee39.png)

Sample command: 

```
az aks kollect 
-g MyResourceGroup
-n **Private_ManagedCluster**
--storage-account MyStorageAccount
--sas-token "MySasToken"
```

**Comment by yonzhan** [comment]
AKS

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by jluk** [comment]
@yunjchoi looks like you might be aware of this, but could your team take a look?

**Comment by feiskyer** [comment]
Filed PR https://github.com/Azure/azure-cli-extensions/pull/1685.
