### ISSUE TITLE
Please provide a JSON example for --service-endpoint-configuration using an aks (azure kubernetes service)

### ISSUE THREAD

**Issue by ezequielramos** [Azure/azure-cli-extensions#1690]
I dont know which information is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ecb62a2-f74c-a539-d3a8-c8fde7c2de06
* Version Independent ID: 5760936e-90a1-4129-6f6f-6dd4194bb73c
* Content: [az devops service-endpoint](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/service-endpoint?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ezequielramos** [comment]
BTW, I just figured out that the `--service-endpoint-configuration` has the same content that the value send throw POST request on the DevOps Portal/Platform application when you are adding a service-connection from there.

**Comment by yonzhan** [comment]
devops

**Comment by survivant** [comment]
Someone have a example how to create a Kubernetes service connection from Azure CLI ?

**Comment by survivant** [comment]
I added a new issue with a payload example here https://github.com/Azure/azure-cli-extensions/issues/5385

**Comment by RakeshMohanMSFT** [comment]
@survivant You should be able to use the command like this `az devops service-endpoint create --service-endpoint-configuration ./aksServiceConnection.json --org "https://dev.azure.com/issue1698Org" --project "Issue1698Project"`
![image](https://user-images.githubusercontent.com/49954584/211250731-234a0088-61fd-4c3a-8fd1-53039de5d9c1.png).

You can create a file using the request body mentioned in issue #5385. We will add the same in azure samples. (Adding different kind of json template in the actual document will be difficult).
