### ISSUE TITLE
Azure CLI - Extension for Application-insights fails to install

### ISSUE THREAD

**Issue by plooploops** [Azure/azure-cli-extensions#1695]
## Describe the bug

**Command Name**
`az extension add -n application-insights`

**Errors:**
```
An error occurred. Pip failed with status code 3221226505. Use --debug for more information.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension add -n application-insights`

## Expected Behavior

Able to install extension for application-insights for az cli.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

```
## Additional Context

![image](https://user-images.githubusercontent.com/2498998/81883917-56d35e00-954b-11ea-8f0e-ecc04fe99eb8.png)

**Comment by yungezz** [comment]
hi @MyronFanQiu could you pls have a look

**Comment by MyronFanQiu** [comment]
Could you run it with debug? Do you have python in your machine? There is a similar issue. https://github.com/Azure/azure-devops-cli-extension/issues/596. I just tried to install it and works.

**Comment by yonzhan** [comment]
add to S170

**Comment by plooploops** [comment]
@MyronFanQiu - I do have python on my machine (including 3.7.5).  Looks like az cli includes 3.6.6 as well, but not sure if there's conflicts in which pip it's using to pull down the whl for the extension.

**Comment by MyronFanQiu** [comment]
add @fengzhou-msft who is expert on packing. Based on my knowledge, it should be ok since we use the full path of python. According to your log, looks like you're using local python 3.7. I'm not sure whether we can fix it or not. @plooploops Is it ok to remove the local python? or re-install azure-cli through pip instead of msi.
![image](https://user-images.githubusercontent.com/49134743/82167364-247c8480-98ee-11ea-9df6-fb7dd7f2a447.png)

**Comment by plooploops** [comment]
I'm using python 3.7.x for other development so would prefer keeping that around if possible.

For the pip re-install I'm assuming it would be pip install azure-cli?

**Comment by MyronFanQiu** [comment]
yes. You can use `pip install azure-cli` to install azure-cli. Please uninstall msi-based azure-cli first. https://pypi.org/project/azure-cli/

**Comment by MyronFanQiu** [comment]
@plooploops Did you solve your issue?

**Comment by yonzhan** [comment]
@plooploops any update for above?

**Comment by MyronFanQiu** [comment]
removed myself since it's an installation issue.

**Comment by plooploops** [comment]
@yonzhan @MyronFanQiu 

Looks like this will work now.

```powershell
python -m pip install azure-cli
az extension add -n application-insights
```

**Comment by MyronFanQiu** [comment]
@plooploops Hi. Could you please uninstall ml extension and install it again? We don't have this file in the latest azure cli. It should be a compatible issue.

**Comment by plooploops** [comment]
@MyronFanQiu 

We're still seeing the message.  Here's the steps taken so far:

```powershell
az extension remove -n azure-cli-ml # Fails because of permissions on C:\users\myuser\.azure\cliextensions
az extension add -n azure-cli-ml # this will install but we're still seeing the ml message.
```
For now I have moved the C:\users\myuser\.azure\cliextenisons\azure-cli-ml folder and re-installed.  We're still seeing the error message for 'Error Loading command module ml'.

![image](https://user-images.githubusercontent.com/2498998/85351606-0d1a5380-b4b9-11ea-826f-65fd3693b681.png)

**Comment by MyronFanQiu** [comment]
@j-so Hi. Could you please take a look since we cannot check the source code for ml extension. In azure cli core, I cannot find `help_files`.

**Comment by j-so** [comment]
@MyronFanQiu ml extension has no reference in our code to `azure.cli.core.help_files`. Closest we have to is an import from knack: `from knack.help_files import helps`

**Comment by MyronFanQiu** [comment]
@jiasli Do you know any potential reason? I cannot file this `help_files` at all, even in the history of two years ago.

**Comment by scgbear** [comment]
<details>
<summary>Internal Tracking</summary>
devdivcsef 358504
</details>

**Comment by RakeshMohanMSFT** [comment]
This is fixed
