### ISSUE TITLE
This command needs examples

### ISSUE THREAD

**Issue by rguthriemsft** [Azure/azure-cli-extensions#1698]
An example would be really helpful for this command.  Multiple examples would be better.  I assume I need to provide an http url for the public repo but its not clear how the service connection is used.  Is that used to import a private repository?  Do I also set requires-authorization in that case to true?  What is the username format if the repo is private?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ec496e-0aa8-1dcb-93cb-584fa83fdc0d
* Version Independent ID: 9151bc57-0eac-bf3a-9110-17908d62eeb6
* Content: [az repos import](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/import?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/repos/import.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/repos/import.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
devops

**Comment by RakeshMohanMSFT** [comment]
This will be fixed once the PR is merged.
