### ISSUE TITLE
Notification-Hub not working for APNS update

### ISSUE THREAD

**Issue by pauloortins** [Azure/azure-cli-extensions#1702]
azure-cli - 2.3.1 *
notification-hub - 0.2.0

When I try to run the following command:
az notification-hub credential apns update `
--resource-group xxxx `
--namespace-name xxxx `
--notification-hub-name xxxx `
--app-id 'xxxx' `
--app-name 'xxxxx' `
--key-id 'xxxxxx' `
--token 'xxxxxx' `
--endpoint "gateway.sandbox.push.apple.com"

I'm seeing the following error: 

SubCode=40000. Failed to validate credentials with APNS. Invalid URI: The format of the URI could not be determined

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by efrederickmb** [comment]
Please advise. We are working on an automation solution as we create custom apps per customer with a notification-hub per customer. We have 100's of these to configure and really could leverage the automation. 

I'm seeing the same error:

az notification-hub credential apns update --debug \
--resource-group "myresourcegroupname" \
--namespace-name "myhubnamespace" \
--notification-hub-name "myhubname" \
--token "the_very_long_apple_developer_account_token" \
--app-name "the_bundle_id" \
--app-id "app_id_from_developer_account" \
--key-id "key_id_from_developer_account" \
--endpoint "gateway.sandbox.push.apple.com"

This is a snippet of the debug output including response:
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Length': '256'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-request-id': '76b6f155-d72e-4043-968a-63e7384aff14_M11CH3_M11CH3'
msrest.http_logger :     'Server-SB': 'Service-Bus-Resource-Provider/CH3'
msrest.http_logger :     'Server': 'Service-Bus-Resource-Provider/CH3, Microsoft-HTTPAPI/2.0'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-correlation-request-id': '4e384be8-1e49-4be6-83c8-9d04e8b5b370'
msrest.http_logger :     'x-ms-routing-request-id': 'CENTRALUS:20200708T131628Z:4e384be8-1e49-4be6-83c8-9d04e8b5b370'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Wed, 08 Jul 2020 13:16:27 GMT'
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"message":"SubCode=40000. Failed to validate credentials with APNS. Invalid URI: The format of the URI could not be determined...TrackingId:76b6f155-d72e-4043-968a-63e7384aff14_M11CH3_M11CH3_G8,TimeStamp:7/8/2020 1:16:28 PM","code":"BadRequest"}}
msrest.exceptions : SubCode=40000. Failed to validate credentials with APNS. Invalid URI: The format of the URI could not be determined...TrackingId:76b6f155-d72e-4043-968a-63e7384aff14_M11CH3_M11CH3_G8,TimeStamp:7/8/2020 1:16:28 PM
cli.azure.cli.core.util : SubCode=40000. Failed to validate credentials with APNS. Invalid URI: The format of the URI could not be determined...TrackingId:76b6f155-d72e-4043-968a-63e7384aff14_M11CH3_M11CH3_G8,TimeStamp:7/8/2020 1:16:28 PM
SubCode=40000. Failed to validate credentials with APNS. Invalid URI: The format of the URI could not be determined...TrackingId:76b6f155-d72e-4043-968a-63e7384aff14_M11CH3_M11CH3_G8,TimeStamp:7/8/2020 1:16:28 PM
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x1033228b0>]
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 6017 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "/usr/local/Cellar/azure-cli/2.8.0/libexec/bin/python /usr/local/Cellar/azure-cli/2.8.0/libexec/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py /Users/eddiefrederick/.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
Command ran in 3.747 seconds (init: 0.070, invoke: 3.677)

Below is my azure-cli version details:
azure-cli                          2.8.0

command-modules-nspkg              2.0.3
core                               2.8.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.18.0
notification-hub                   0.2.0

Python location '/usr/local/Cellar/azure-cli/2.8.0/libexec/bin/python'
Extensions directory '/Users/eddiefrederick/.azure/cliextensions'

Python (Darwin) 3.8.3 (default, May 27 2020, 20:54:22) 
[Clang 11.0.3 (clang-1103.0.32.59)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Comment by pierregarcia** [comment]
It seems the Endpoint Urls have changed
`gateway.push.apple.com` is now `https://api.development.push.apple.com:443/3/device`
`gateway.sandbox.push.apple.com` is now `https://api.sandbox.push.apple.com:443/3/device`

This will work:
```
az notification-hub credential apns update --resource-group xxxx
--namespace-name xxxx --notification-hub-name xxxx
--app-id 'xxxx' --app-name 'xxxxx'
--key-id 'xxxxxx' --token 'xxxxxx'
--endpoint "https://api.sandbox.push.apple.com:443/3/device"
```

**Comment by fengzhou-msft** [comment]
@tjsomasundaram can you confirm @pierregarcia's comment about the change of APNS endpoint URLs?

**Comment by tjsomasundaram** [comment]
Hi, the sandbox url is right and the format provided by @pierregarcia is accurate. Thanks for providing the info!

For production, this is the endpoint url: "api.push.apple.com", not the development endpoint noted above (https://api.development.push.apple.com:443/3/device). So you would need to use: `https://api.push.apple.com:443/3/device`

According to Apple, you can also use port 2197 (instead of port 443) on either server when communicating with APNs. For reference, here is the documentation from Apple: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/

**Comment by yungezz** [comment]
hi @pauloortins does above information helpful to you?

**Comment by airobot60** [comment]
> azure-cli - 2.3.1 *
> 
> notification-hub - 0.2.0
> 
> 
> 
> When I try to run the following command:
> 
> az notification-hub credential apns update `
> 
> --resource-group xxxx `
> 
> --namespace-name xxxx `
> 
> --notification-hub-name xxxx `
> 
> --app-id 'xxxx' `
> 
> --app-name 'xxxxx' `
> 
> --key-id 'xxxxxx' `
> 
> --token 'xxxxxx' `
> 
> --endpoint "gateway.sandbox.push.apple.com"
> 
> 
> 
> I'm seeing the following error: 
> 
> 
> 
> SubCode=40000. Failed to validate credentials with APNS. Invalid URI: The format of the URI could not be determined

**Comment by navba-MSFT** [comment]
@pauloortins Apologies for the late reply. Could you please let us know if the above suggestions were helpful ? This issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.
