### ISSUE TITLE
"az create pipeline ..." does not create a valid pipeline... attempt to edit resulting pipeline within dev.azure.com portal fails.

### ISSUE THREAD

**Issue by greghenderson** [Azure/azure-cli-extensions#1703]
## Describe the bug

**Command Name**
`az pipelines create
Extension Name: azure-devops. Version: 0.18.0.`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- In dev.azure.com UI create a sample organization / project (private). Reference "https://dev.azure.com/gkh-test-001/_git/gkh-test-001-a" created by "adm_ghenderson@ansell.com".
- In Repos blade, initialize the default repository.
- In Pipelines blade, create and save a starter pipeline to create a sample azure-pipelines.yml file in master branch.
- In Profiles screen create a full-access personal access token for the sample organization.
- Back to terminal with the access token...
- `az devops login`
- `az devops configure --defaults organization=https://dev.azure.com/gkh-test-001 project=gkh-test-001-a`
- `az pipelines create --name asdf --repository gkh-test-001-a --repository-type tfsgit --branch master --yml-path "azure-pipelinesyml" --skip-first-run`
- Back to the dev.azure.com UI...
- Navigate to the Pipelines blade, find the created "asdf" pipeline and attempt to "Edit" via the popup menu from the "..." icon.
- Receives following error:

```
An unexpected error has occurred within this region of the page.
You can try reloading this component or refreshing the entire page.

Error: Cannot read property 'manageUrl' of undefined
Stack
in h
    in f
    in div
    in v
    in h
    in div
    in n
    in f
    in div
    in n
    in f
    in div
    in n
    in f
    in div
    in v
    in g
```

## Expected Behavior
Expect to see the pipeline yaml file editing screen.

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.3.1 *

Extensions:
azure-devops 0.18.0
application-insights 0.1.7

```

**Comment by Kadungon** [comment]
i am also facing this same issue tried with both azure cli and azure api to create pipeline.

**Comment by sojwil** [comment]
Same issue on https://dev.azure.com/ GUI

**Comment by Neoff224** [comment]
It is happening at least since last Thursday, it is an issue, because I have edited these pipelines before.Therefore, it seems that some change has been made.

**Comment by jayasimhamadhira** [comment]
We are also facing the same issue since Thursday , can you please suggest me the fix..

**Comment by parag1231** [comment]
Getting same error! unable to edit the pipeline from last weekend. Let us know the fix. Cleared cache of browser as well and changed the browser as well. Still same issue persists.
Attached screenshot of error. 
![Annotation 2020-05-18 150117](https://user-images.githubusercontent.com/46993628/82197363-8c47c500-9918-11ea-81a3-3d19ad42eaf4.png)

**Comment by santosh3702** [comment]
i am also getting the same issue.

**Comment by BlueBasher** [comment]
I am also encountering this issue.
Receiving this error with multiple pipelines that previously could be edited without error.
The Project has multiple pipelines, some pipelines give this error and others can be edited just fine.

**Comment by jkewley** [comment]
Us as well. Reported it here 
https://developercommunity.visualstudio.com/content/problem/1034787/devops-pipelines-created-through-cli-cant-be-edite.html?childToView=1036474

**Comment by Bhanu88** [comment]
we are also facing the same issue

**Comment by kanwaldeepBhangu** [comment]
I created build defination using azure devops rest api but not able to edit from Browser..Trigger of pipeline is working but edit is showing the exact same error as mentioned above

**Comment by birchb1024** [comment]
Me Too. It _used_ to work before the outage we had in the Australia region. That might just be a coincidence. Workaround is to edit elsewhere.

**Comment by shehanWeer** [comment]
Exact same issue. Pipelines deployed in South India region

**Comment by darthwillis** [comment]
@greghenderson This appears to have been hotfixed. Are you still seeing the issue?

**Comment by greghenderson** [comment]
Just ran a quick simple test, looks good.  Have several pipeline configurations to create, will report back results.

**Comment by greghenderson** [comment]
Created several pipelines, able to edit as expected in Azure Devops portal.  All good. :-)
