### ISSUE TITLE
timeseriesinsights - --timestamp-property-name should be made optional

### ISSUE THREAD

**Issue by riserrad** [Azure/azure-cli-extensions#1712]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

timeseriesinsights

### Description of issue (in as much detail as possible)

When creating an Event Source, the `--timestamp-property-name` should be an _optional_ parameter.

Please let us know if there's something on the Service's swagger side that needs to be reviewed to make this possible.

-----

**Comment by yonzhan** [comment]
add to S170
