### ISSUE TITLE
Event-Subscription for Azure Functions does not accept azurefunction as an option

### ISSUE THREAD

**Issue by ebrucucen** [Azure/azure-cli-extensions#1713]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
`az eventgrid event-subscription create`

### Description of issue (in as much detail as possible)
The example and the parameter for `azurefunction` as a parameter to `endpoint-type` fails with :
```
az eventgrid event-subscription create: 'azurefunction' is not a valid value for '--endpoint-type'. See 'az eventgrid event-subscription create --help'.
```

I have tested 2.3.1, 2.4.0, 2.5.1

-----

**Comment by yonzhan** [comment]
eventgrid

**Comment by ahamad-MS** [comment]
Hello @ebrucucen  Can you please let me know if you are using CLI Extension or mainstream CLI?

The azurefunction as destination is currently available in CLI extension and we are in process of adding it to mainstream cli.

To get this functionality, please do the following.

1. Remove any eventgrid extension.

2. Install latest eventgrid extension.

3. Make sure the eventgrid extension's version is 0.4.8


ashraf@Azure:~$ az extension list
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "eventgrid",
    "preview": true,
    "version": "0.4.8"
  }
]

4. azurefunction is part of event subscription create command.

ashraf@Azure:~$ az eventgrid event-subscription create -h
The behavior of this command has been altered by the following extension: eventgrid

Command
    az eventgrid event-subscription create : Create a new event subscription.

Arguments
    --endpoint                                     : Endpoint where EventGrid should deliver events
                                                     matching this event subscription. For webhook
                                                     endpoint type, this should be the corresponding
                                                     webhook URL. For other endpoint types, this
                                                     should be the Azure resource identifier of the
                                                     endpoint.
    --endpoint-type                                : The type of the destination endpoint.  Allowed
                                                     values: azurefunction, eventhub,
                                                     hybridconnection, servicebusqueue,
                                                     servicebustopic, storagequeue, webhook.
                                                     Default: webhook.

**Comment by ahamad-MS** [comment]
Please try the latest extension per comment above and let us know if you are having any issues.

**Comment by ebrucucen** [comment]
Yes, this is perfect! Can we update the pages as it does not mention the requirement/installation of the extension. 
https://docs.microsoft.com/en-us/cli/azure/ext/eventgrid/eventgrid/event-subscription?view=azure-cli-latest
Thank you!

**Comment by ahamad-MS** [comment]
Hello @ebrucucen ..Happy that your issue is resolved. We are closing the issue but if you still need anything, please feel free to reopen it.

As for your suggestion for adding the extension installation info to the event-subscription page, it will not be appropriate to add this info in the command help page. however, we have a new feature work that is coming soon where there will be no need to install any extension for event grid soon. Hope this helps.

thanks
