### ISSUE TITLE
`front-door` is not in the `az network` command group

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli-extensions#1715]
When running `az network front-door` ... and any of the commands listed in this article, Azure returns:
"az network: 'front-door' is not in the 'az network' command group. See 'az network --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1b5ddd-0054-0175-b689-d20a1349bedb
* Version Independent ID: 72ccc1b6-814f-b780-99cd-ab48dfdecb66
* Content: [az network front-door](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door?view=azure-cli-latest#ext-front-door-az-network-front-door-show)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by awentzel** [comment]
Please refer to https://github.com/Azure/azure-cli/issues/7535#issuecomment-440090849 noticing extensions are required, I'd recommend updating the top of this page to call out the pre-requisite.  https://github.com/Azure/azure-cli-extensions/tree/master/src/front-door  Thanks

**Comment by yonzhan** [comment]
front-door

**Comment by samsmithnz** [comment]
I just ran into this with a customer today. Another vote to include extra documentation at the top of the page to describe the extensions required.

**Comment by yonzhan** [comment]
@dbradish-microsoft may help you with this.

**Comment by samsmithnz** [comment]
All you need is - Prereq:

`az extension add --name front-door`

**Comment by dbradish-microsoft** [comment]
@samsmithnz / @awentzel , We have been working to auto-gen more extension reference information in our reference docs.  This is one of our top priorities for reference doc improvement.

Kindly,

Delora
