### ISSUE TITLE
az arc issue

### ISSUE THREAD

**Issue by cosmos0703** [Azure/azure-cli-extensions#1753]
## Describe the bug

**Command Name**
`az connectedk8s connect
Extension Name: connectedk8s. Version: 0.2.1.`

**Errors:**
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
lib/python3.6/json/decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.6/json/decoder.py, ln 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {} --location {}`

## Environment Summary
```
Linux-5.3.0-1020-azure-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.6.0

Extensions:
maintenance 1.0.1
aks-preview 0.4.44
azure-devops 0.16.0
connectedk8s 0.2.1

```

**Comment by cosmos0703** [comment]
my helm version is like this
cosmos@cosmos-new-vm:~$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

**Comment by yonzhan** [comment]
connectedk8s

**Comment by palma21** [comment]
Removing AKS as this is connected clusters

**Comment by palma21** [comment]
Cc @slack

**Comment by yungezz** [comment]
HI hi @akashkeshari could you pls look at this issue?

**Comment by Mikhail2k15** [comment]
Looks like I have the same issue https://github.com/Azure/azure-cli-extensions/issues/1758

**Comment by akashkeshari** [comment]
@cosmos0703 ,

I think you have the similar issue: https://github.com/Azure/azure-cli-extensions/issues/1758

**Comment by akashkeshari** [comment]
@cosmos0703 ,

This issue has been fixed. Please update the connectedk8s extension to version 0.2.4 and try again:
Update using this cmd: 'az extension update -n connectedk8s'

**Comment by RakeshMohanMSFT** [comment]
This is fixed. Closing it.
