### ISSUE TITLE
whitelisting private onpremise ips not possible with aks-preview extension

### ISSUE THREAD

**Issue by ivanthelad** [Azure/azure-cli-extensions#1764]
-
### Extension name (the extension in question)

aks-preview
### Description of issue (in as much detail as possible)

I'm  facing an issue that i cannot whitelist the onpremise ips using the --api-server-authorized-ip-ranges  feature.  Anything in the reserved  range 10.x.x.x/8 it would seem. 

Looking into this. The docs state onpremise private  ips should be possible, taken from our docs 

- “These IP address ranges are usually address ranges used by your on-premises networks or public IPs. ”

- https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges#create-an-aks-cluster-with-api-server-authorized-ip-ranges-enabled

But on the other hand the cli explicitly ignores private ip ranges with the is_global check and throws an exceptions when a 10.,x.x.x range is passed  https://github.com/Azure/azure-cli-extensions/blob/master/src/aks-preview/azext_aks_preview/_validators.py#L131
-	According to the python docs for the lib ip_network. the method is_global method is called is behaving as expected.  It checks the special registry of ip   https://docs.python.org/3.7/library/ipaddress.html#ipaddress.IPv4Address.is_global
-	The 10.x.x.x range is reserved and in the registry so the cli extension will classify this as not public so it will throw an error. The expect exception “"--api-server-authorized-ip-ranges must be global non-reserved addresses or CIDRs” is then thrown   https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml

The cli extension logic doesn’t seem to make sense here to me. Is this a bug`?

**Comment by yonzhan** [comment]
aks-preview

**Comment by ivanthelad** [comment]
Reading the aks official documentation i have to wonder if it is simply poorly written documentation. 

- "These IP address ranges are usually address ranges used by your on-premises networks or public IPs. ”

where "on-premise networks" means public ips owned by a company and are not internal onpremise network. its a bit unclear what the documentation means here

**Comment by palma21** [comment]
That's the case please do open a doc improvement.
API allow IP ranges need to be public to be recognized as they arrive at the public control plane
