### ISSUE TITLE
HTML issue in the description of "az devops invoke"?

### ISSUE THREAD

**Issue by MS-Trev** [Azure/azure-cli-extensions#1781]
This looks like a type-o or HTML issue:

![image](https://user-images.githubusercontent.com/17113604/83160138-d11bea80-a0d4-11ea-8272-e5d670514e72.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9e855a-abc5-14d9-ba73-4ab527ffee16
* Version Independent ID: 85a46540-4b25-94f4-2c0e-29e1f8fefe35
* Content: [az devops](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by RakeshMohanMSFT** [comment]
@MS-Trev This is fixed.
