### ISSUE TITLE
Error running az connectedk8s connect

### ISSUE THREAD

**Issue by vtomsa83** [Azure/azure-cli-extensions#1789]
## Describe the bug

**Command Name**
`az connectedk8s connect
Extension Name: connectedk8s. Version: 0.2.1.`

**Errors:**
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
lib/python3.6/json/decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.6/json/decoder.py, ln 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {}`

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.6.0

Extensions:
k8sconfiguration 0.1.8
connectedk8s 0.2.1

```

**Comment by yonzhan** [comment]
connectedk8s

**Comment by akashkeshari** [comment]
Hi @vtomsa83 ,

Could you share the debug logs for this. Please run 'az connectedk8s connect --name {} --resource-group () --debug' and share the output.

**Comment by akashkeshari** [comment]
@vtomsa83 ,

This issue has been fixed. Please update the connectedk8s extension to version 0.2.4 and try again:
Update using this cmd: 'az extension update -n connectedk8s'

Let us know if you still face this issue

**Comment by navba-MSFT** [comment]
@akashkeshari Apologies for the late reply. Could you please let us know if you had a chance to look at the above comment ? This issue is open for quite sometime. Please let me know if you need any further assistance on this. Awaiting your reply.
