### ISSUE TITLE
[hardware security] outdated Network API block CI

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-cli-extensions#1790]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

hardware security

### Description of issue (in as much detail as possible)

-----

Since this PR is outdated, https://github.com/Azure/azure-cli-extensions/pull/1626 and Fan has bumped Network SDK version, and the merge time is later than it. So, currently, it will block our CI now for hardware security extension is using outdated Network API.

**Comment by fengzhou-msft** [comment]
@bquantump can you take a look at this issue?

**Comment by bquantump** [comment]
@haroldrandom can you give some more information on this? I assume this is in regards to the test scenario VNET creation. I though I had fixed this in the PR:

> Recently, azure-mgmt-network has bumped to a newer version.
> Locally, you are using the older one, but CI will follow the latest one, That's why it failed on here network API.

I updated the test scenario based on your comment above, and seemed to have fixed the CI issue. Has the network SDK bumped again?

**Comment by haroldrandom** [comment]
@bquantump 
Did you record the test YAML file against the latest azure-mgmt-network? 
If that so, could you fire a PR to fix it?

**Comment by bquantump** [comment]
Is azure-mgmt-network 10.1.0 the correct version ? That’s the one I ran the test on that allowed the CI to pass in the PR.

**Comment by haroldrandom** [comment]
> Is azure-mgmt-network 10.1.0 the correct version ? That’s the one I ran the test on that allowed the CI to pass in the PR.

It's azure-mgmt-network. The virtual network API is 2020-04-01

**Comment by bquantump** [comment]
Uh ic ok, so the yaml is out of date with the network API. I’ll rerun with 10.2.0 then. It will take a bit since HSMs need a lot of pre-setup  to provision. Then the HSM provision itself  is about 20 mins.
