### ISSUE TITLE
Cli conditional params support

### ISSUE THREAD

**Issue by DevenWalia** [Azure/azure-cli-extensions#1791]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
NA

### Description of issue (in as much detail as possible)

-----
My team has an usecase which allows us to have a cli extension & I have a quick question regarding conditional params support in clis. 

Consider this :-

```
az mycli --conditional-param <value1> --a <> 
(a is mandatory param if value of --condional-param is value1)

az mycli --conditional-param <value2> --b <> 
(b is mandatory param if value of --condional-param is value2)
```

Sure I can go for subcmds pattern where I can have subcmds :- 
```
az mycli conditional-param_value1 --a <>
az mycli conditional-param_value2 --b <> 
```

But is there any other way ? 
If we have 2-3 layers of conditional params we can see that the number of subcmds will quickly grow to a large number.

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by jiasli** [comment]
Unfortunately, this complicated relationship between parameters is not supported by [argparse](https://docs.python.org/3/library/argparse.html) on which Azure CLI is built. It is also impossible to show such conditional "mandatory" in `--help` message in the built-in way of argparse.

As a workaround, you may make all of them optional and use `_validators.py` (such as [vm/_validators.py](https://github.com/Azure/azure-cli/blob/b686fed3266fa52dae3acee9d5c72571bf049174/src/azure-cli/azure/cli/command_modules/vm/_validators.py)) or `custom.py` (such as [vm/_validators.py](https://github.com/Azure/azure-cli/blob/b686fed3266fa52dae3acee9d5c72571bf049174/src/azure-cli/azure/cli/command_modules/vm/custom.py)) to do the check and prompt the correct usage.

Here is some more info about **validators**: https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#validators
