### ISSUE TITLE
Intellisense not working for azure cli

### ISSUE THREAD

**Issue by kazimsomji** [Azure/azure-cli-extensions#1794]
### Extension name

Azure cli extension version 0.5.0
azure cli version 2.6.0

### Description of issue

In VS code, Intellisense is not working and I have no code completion.  I also have powershell on this machine and intellisense works with no problems.  I can run code via the terminal but I just don't get code completion.

Environment summary

windows 10 Version 10.0.18363.8361909
VS Code Version: 1.45.1 (user setup) with Azure CLI extension v 0.5.0
azure cli version 2.6.0
power shell 7

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by kazimsomji** [comment]
Thank you @yonzhan @XiaoningLiu

**Comment by arrownj** [comment]
Hi @kazimsomji , please kindly be noted that CLI do not support code completion on Windows. You can try code completion on Linux.

**Comment by kazimsomji** [comment]
> Hi @kazimsomji , please kindly be noted that CLI do not support code completion on Windows. You can try code completion on Linux.

Hi,

I have another Windows 10 machine and code completion works on that one.

**Comment by yungezz** [comment]
hi @kazimsomji did you met code completion issue in VSCode? If yes, it's azure cli VSCode extension issue. This repo is azure cli extension of different commands. Could you pls track the issue in VSCode Azure CLI extension repo? thanks. cc @arrownj

**Comment by yungezz** [comment]
hi @kazimsomji could you pls help to clarify is this issue about autocomplete in VSCode?

**Comment by kazimsomji** [comment]
Yes this is autocomplete in VS Code.

**Comment by yungezz** [comment]
> Yes this is autocomplete in VS Code.

thanks for confirmation. will close the issue now. Feel free to create new issue if any error when using azure cli.
