### ISSUE TITLE
Disable AFD Backend Pool's Backend Host with Azure Cli

### ISSUE THREAD

**Issue by gaz91au** [Azure/azure-cli-extensions#1823]
Im trying to update an existing backend host of a AFD backend pool to have its status from Enabled to Disabled.

Is there a way to update existing backend host using the Azure cli?

Currently, i can only see `add`, `list` and `remove` in the docs:
- `az network front-door backend-pool backend add`
- `az network front-door backend-pool backend list`
- `az network front-door backend-pool backend remove`

Is there one for `update`?

FYI, im trying to toggle the below setting.

![image](https://user-images.githubusercontent.com/12619249/83723464-16668c00-a682-11ea-8c7f-f2b4b8d54da9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16042b8-fdcd-262b-64b4-7703e926db42
* Version Independent ID: f9b55bda-90a5-40ed-f837-c0dee291693f
* Content: [az network front-door backend-pool backend](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/backend-pool/backend?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door/backend-pool/backend.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door/backend-pool/backend.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
@gaz91au Hi. Sorry that currently we can just add a rule and remove a rule. I checked this toggle. We haven't support it right now. I would mark this issue as feature request and plan for it. @aramesh-msft FYI as well.

**Comment by gaz91au** [comment]
thanks @yonzhan and @MyronFanQiu 

i found that i can update the backend status by using the azure rest api.

```
We can use Rest API to set the backend pool backend status to Disabled for the backend pool using the below commands:
Firstly, run the GET command on Azure FrontDoor. Using that command we can see the properties for the backend pool backend status. In which, we can set the property – enabledState=Disabled to disable to backend pool and further on running the Create or update API command, the state of the backend pool will also be updated.
 
Example:
   "backends":[
            { "address":"web.azurewebsites.net","httpPort":80,"httpsPort":443,"priority":1,"weight":50,"backendHostHeader":"web.azurewebsites.net","enabledState":"Disabled"
Here are the articles for reference:

Get Command: https://docs.microsoft.com/en-us/rest/api/frontdoorservice/frontdoor/frontdoors/get
Create or Update: https://docs.microsoft.com/en-us/rest/api/frontdoorservice/frontdoor/frontdoors/createorupdate
```
