### ISSUE TITLE
Allow Azure Extensions to be installed from a private registry

### ISSUE THREAD

**Issue by gusnaughton** [Azure/azure-cli-extensions#1836]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Affects all extensions

### Description of issue (in as much detail as possible)
In the past, new releases of Azure-CLI-Extensions have included breaking changes in unrelated places without test coverage. Today, there is not a way to select a version of an individual extension to install to rollback a node on the latest version.

This issue is for supporting private registries of all Azure Extensions (and the support of custom ones).

https://github.com/Azure/azure-cli/pull/13789 includes a fix for specifying a version of an extension. This issue is to track the entire scope of work by request of @haroldrandom. 

-----
### Related Issues
https://github.com/Azure/azure-cli-extensions/issues/1578
https://github.com/Azure/azure-cli-extensions/issues/1587

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
With Azure CLI 2.20.0+, now you can configure a private extension registry, for instance you can refer it to an `index.json` file on a git branch:
`az config set extension.index_url=https://raw.githubusercontent.com/Azure/azure-cli-extensions/master/src/index.json`

**Comment by gusnaughton** [comment]
Thank you, friends!!
