### ISSUE TITLE
Unable to create read only api key for app-insights

### ISSUE THREAD

**Issue by romiih** [Azure/azure-cli-extensions#1841]
### Extension name (the extension in question)
application-insights

### Description of issue (in as much detail as possible)
I want to create a read only API key for Application Insight.
I tried below command but the created key had two permissions "Read telemetry, Write annotations".
```
az monitor app-insights api-key create --app my_app -g my_resource_group --api-key test_api_key --read-properties ReadTelemetry
```
without `--read--properties`, api key had three permissions "Read telemetry, Write annotations, Authenticate SDK control channel".
Can I create api key that only has Read telemetry permission?

my cli version:
```
> az version
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "application-insights": "0.1.8",
    "azure-devops": "0.18.0"
  }
}
```

Thanks,

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
Please add `--write-properties '""'` and have a try.

**Comment by romiih** [comment]
Yes, I'm using PowerShell, and already tried `--write-properties ""` but didn't work.
`--write-properties '""'` solved my problem! Thank you for your quick reply.
