### ISSUE TITLE
Broken /cli/azure/ext/azure-cli-ml/ml/datastore links

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli-extensions#1855]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

**The following extension reference has two broken links:**
https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-ml/ml/datastore

### Description of issue (in as much detail as possible)

**The following links are no longer valid:**
https://storage.azure.com/
https://datalake.azure.net/

**Comment by yonzhan** [comment]
add to S172

**Comment by meyetman** [comment]
Thanks @dbradish-microsoft ! We have committed this change and it should appear in the docs within 2 weeks.
