### ISSUE TITLE
[AKS] az aks get-upgrades --output table fails on extensions

### ISSUE THREAD

**Issue by marwanad** [Azure/azure-cli-extensions#1866]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
Running
```
az aks get-upgrades -g {{RG_NAME}} -n {{CLUSTER_NAME}} --output table
```
fails with

```
preview/azext_aks_preview/_format.py", line 72, in aks_upgrades_table_format
    find_preview_versions(result.get('agentPoolProfiles', [{}])[0])
TypeError: 'NoneType' object is not subscriptable

cli.azure.cli.core.util : Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
```

The fix is to not use the agentPoolProfile when formatting the table since the field is nil. We need to update the formatter.

Issue is only when using extensions and the -o table. Works fine on CLI core.
-----

**Comment by yonzhan** [comment]
AKS

**Comment by marwanad** [comment]
fyi: the issue is opened by AKS team and tracked internally
