### ISSUE TITLE
Example for sharing a blob folder.

### ISSUE THREAD

**Issue by lolzyloz** [Azure/azure-cli-extensions#1868]
[Enter feedback here]
Could we include an example on how to share a blob folder? Suppose within a container i have a file c under the path a/b/c and also a folder c under the path a/b/c, how do i share folder c instead of file c?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443539f0-7b45-4e8d-6ea9-1d62a74e9839
* Version Independent ID: d410fbac-4da6-b6a8-6645-0740984c7f15
* Content: [az datashare dataset](https://docs.microsoft.com/en-us/cli/azure/ext/datashare/datashare/dataset?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/datashare/datashare/dataset.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/datashare/datashare/dataset.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
Here is an example: 
```
az datashare dataset create --account-name MyAccount --name MyDataset 
--resource-group MyResourceGroup --share-name MyShare 
--dataset "{\"kind\":\"BlobFolder\",\"properties\":{\"containerName\":\"C1\",\"prefix\":\"folder21\",\"resourceGroup\": \
\"SampleResourceGroup\",\"storageAccountName\":\"storage2\",\"subscriptionId\":\"00000000-0000-0000-0000-000000000000\"}}"
```
