### ISSUE TITLE
Python Dependencies for an Azure CLI extension do not work

### ISSUE THREAD

**Issue by trevors20** [Azure/azure-cli-extensions#1877]
Hi.  I am creating an extension where I need to grab some certificates from an Azure KeyVault that I own.  As well, be able to use EventHub to send some telemetry of my extension.

For this, I am trying to leverage the Python modules "azure-keyvault-certificates" and "azure-eventhub".  But, even though I have installed these modules on my system I am unable to use them in my extension.  I get the following kind of errors when trying to run my extension:

Unable to load extension '<myextensionname: No module named 'azure.eventhub''. Use --debug for more information.

Don't know if it matters or not, but I'm creating this on the Mac.  But fully intend for my extension to work on Windows+Linux.

Outside of the extension I am able to use these modules just fine in a stand alone pything script.  Does the AZ CLI have it's own location for storing Python modules and that is why I am unable to use these modules? 

What is the recommendation here?  Is there a specific location where I need to install these python modules for my extension to work?  If yes, do you know where and how I can do that?

Any other recommendations or advice on how I could create my extension to work using these external python modules?  Work arounds?

Thanks for the help!

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
This is a known issue that CLI cannot import namespace packages starting with `azure` installed in extension directories. 

With this [PR](https://github.com/Azure/azure-cli/pull/13163), you can now call `add_extension_to_path` to extend the `azure` namespace with extension directories and use packages installed there. You can add the call in the `load_command_table` method of your extension.

**Comment by yungezz** [comment]
hi @trevors20 does above solution work for you? Is it ok to close the issue now since it's supported? thanks.

**Comment by fengzhou-msft** [comment]
Latest azure-cli uses PEP420 now and this issue is resolved. Please update azure-cli and try again.
