### ISSUE TITLE
Can't list datashare accounts

### ISSUE THREAD

**Issue by vbliznikov** [Azure/azure-cli-extensions#1900]
## Describe the bug
I just installed datashare extension and trying to play a little to get familiar with it. The first command throws and exception.

**Command Name**
`az datashare account list
Extension Name: datashare. Version: 0.1.0.`

**Errors:**
```
'expiresIn'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
    result = func(*args, **kwargs)
core/pipeline/policies/_authentication.py, ln 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
azure/cli/core/adal_authentication.py, ln 64, in get_token
    return AccessToken(token, int(full_token['expiresIn'] + time.time()))
KeyError: 'expiresIn'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datashare account list --resource-group {}`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

Extensions:
datashare 0.1.0

```

**Comment by fengzhou-msft** [comment]
@jiasli can you take a look at the AccessToken error message? Is it related to https://github.com/Azure/azure-cli/issues/9427?

**Comment by Juliehzl** [comment]
It is caused by track2 support issue in azure cli core and I am fixing it now.

**Comment by Juliehzl** [comment]
The fix https://github.com/Azure/azure-cli/pull/14187 is done. please try with azure cli 2.9.1.
