### ISSUE TITLE
test_azure_firewall_management_ip_config failed.

### ISSUE THREAD

**Issue by MyronFanQiu** [Azure/azure-cli-extensions#1905]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

test_azure_firewall_management_ip_config failed. I think released package should fail.
### Description of issue (in as much detail as possible)

    E           Message: AzureFirewall af1 management IP configuration cannot be added to an existing firewall. Redeploy with a management IP configuration if you want to use forced tunneling support.

msrestazure.azure_exceptions.CloudError: Azure Error: AzureFirewallManagementIpConfigCannotBeAdded

-----

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
close this issue since it's been solved
