### ISSUE TITLE
az storage blob: 'directory' is not in the 'az storage blob'

### ISSUE THREAD

**Issue by werton13** [Azure/azure-cli-extensions#1907]
[Enter feedback here]

Hi there,
I find this article regarding  creating a directory in a storage blob container,
but it seems this doc: (https://docs.microsoft.com/en-us/cli/azure/ext/storage-preview/storage/blob/directory?view=azure-cli-latest) is not actual, cause when I trying to run it, I receiving the following error:

az storage blob: 'directory' is not in the 'az storage blob' command group. See 'az storage blob --help'.
I working with Azure Stack
My Az cli version is:
``` bash
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}

```
How even can I create a directory in a container through a cli? I finded what it is now possible via storage explorer but I need to use it in automation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47613ea1-91af-6900-1867-19e08b116908
* Version Independent ID: 17534203-877d-b510-666b-452d4e6382bc
* Content: [az storage blob directory](https://docs.microsoft.com/en-us/cli/azure/ext/storage-preview/storage/blob/directory?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/storage-preview/storage/blob/directory.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/storage-preview/storage/blob/directory.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S172

**Comment by werton13** [comment]
I'm sorry, cause i skipped this:
To use the directory commands, please make sure your storage account type is StorageV2.
Azure Stack support only v1 Storage accounts, so the article is correct.
