### ISSUE TITLE
Application Insights daily data cap cannot be set to fractional number via CLI

### ISSUE THREAD

**Issue by ComradeCow** [Azure/azure-cli-extensions#1910]
## Describe the bug

The daily data cap in Application Insights can be set to a non-integer number (eg. 0.1).   The `az monitor app-insights component billing update` command only allows integer numbers. 

When using `az monitor app-insights component billing show`, the data volume cap is returned as a non-integer number. 

The `billing update` command should be updated to accept fractional numbers to match the behavior of the portal.

**Command Name**
`az monitor app-insights component billing update`
`Extension Name: application-insights. Version: 0.1.8.`

**Errors:**

```
> az monitor app-insights component billing update --app $appName --resource-group $resourceGroup --cap 0.1
az monitor app-insights component billing update: error: argument --cap: invalid int value: '0.1'
```

## To Reproduce:

- `az monitor app-insights component create --app $appName --resource-group $resourceGroup`
- `az monitor app-insights component billing update --app $appName --resource-group $resourceGroup --cap 0.1`

## Expected Behavior

The `--cap` value should accept non-integer numbers.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.2.0 *

Extensions:
application-insights 0.1.8

```

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
@ComradeCow Thanks for raising this issue. Let me reproduce and fix it.
