### ISSUE TITLE
azcopy does not exists in storage?

### ISSUE THREAD

**Issue by tspi** [Azure/azure-cli-extensions#1934]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6c18f2-5519-f5c1-a384-fd9a5f80fd66
* Version Independent ID: 95ddbc9e-85fa-1554-d2c0-db38393e9e3b
* Content: [az storage azcopy blob](https://docs.microsoft.com/en-us/cli/azure/ext/storage-preview/storage/azcopy/blob?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/storage-preview/storage/azcopy/blob.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/storage-preview/storage/azcopy/blob.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S173

**Comment by Juliehzl** [comment]
it exists. you can use `az storage copy/remove` and `az storage blob sync` in latest azure cli.
`az storage azcopy blob` exists in `storage-preview` extension. you need to install the extension with `az extension add -n storage-preview` first. 
But the first one in azure cli should be the same and recomended.
