### ISSUE TITLE
az login in PowerShell fails with "Please ensure you have network connection"

### ISSUE THREAD

**Issue by adithya203** [Azure/azure-cli-extensions#1936]
when I'm trying login Azure portal in Power Shell through az login command I'm unable to login 

I'm attaching the error message!!
<img width="601" alt="Capture" src="https://user-images.githubusercontent.com/67480678/85889247-12c5b100-b7b9-11ea-8bbd-41b3a3de93c8.PNG">

I tried with different proxy settings but didn't worked..

**Comment by yonzhan** [comment]
add to S173

**Comment by jiasli** [comment]
It looks like the connection to https://login.microsoft.com/ has been blocked by your network. Could you try visiting it in a browser and try command:

```pwsh
& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python" -c "import urllib.request; print(urllib.request.urlopen('https://login.microsoft.com/').info())"
```

**Comment by adithya203** [comment]
Hi,

I got some Traceback and timeout error: winerror 10060.

**Comment by adithya203** [comment]
This is the error I'm getting with that command

![image](https://user-images.githubusercontent.com/67480678/86030172-2021ac00-ba02-11ea-9308-759ff2d60230.png)

**Comment by jiasli** [comment]
Does https://login.microsoftonline.com/ work in the browser?

The error from `python` indicates you don't have access to https://login.microsoftonline.com/, you may contact your organization administrator or ISP to make sure you can open https://login.microsoftonline.com/ correctly.

**Comment by yonzhan** [comment]
Solution provided.
