### ISSUE TITLE
az cli application-insights api-key creates with wrong permissions

### ISSUE THREAD

**Issue by melborp** [Azure/azure-cli-extensions#1945]
### Description of issue

The default behavior of creating an api-key with the az cli application-insights extension is that it will add full permissions if  None is supplied.
If i would like to create a read only or write only api-key, then i cant seem to do it with the az cli. 

1) `az monitor app-insights api-key create --read-properties ReadTelemetry ..` 
would always result in WriteAnnotations as well, because nothing is provided for --write-properties and the default is WriteAnnotations

2) `az monitor app-insights api-key create --write-properties WriteAnnotations  .. `
would always result in ReadTelemetry and  AuthenticateSDKControlChannel as well, because nothing is provided for --read-properties and the default is 'ReadTelemetry', 'AuthenticateSDKControlChannel'.

My assumption and as it seems to behave everywhere else is that i need to say the permission set i want or if i supply no read and write permissions, then default is all. IF i supply my permission set, then only that will be used. 

I believe the bug is here:
https://github.com/Azure/azure-cli-extensions/blob/master/src/application-insights/azext_applicationinsights/custom.py

Line 142-145:
```
    if read_properties is None:
        read_properties = ['ReadTelemetry', 'AuthenticateSDKControlChannel']
    if write_properties is None:
        write_properties = ['WriteAnnotations']
```

**Comment by yonzhan** [comment]
add to S173

**Comment by MyronFanQiu** [comment]
> ### Extension name: **application-insights**
> ### Description of issue
> The default behavior of creating an api-key with the az cli application-insights extension is that it will add full permissions if None is supplied.
> If i would like to create a read only or write only api-key, then i cant seem to do it with the az cli.
> 
> 1. `az monitor app-insights api-key create --read-properties ReadTelemetry ..`
>    would always result in WriteAnnotations as well, because nothing is provided for --write-properties and the default is WriteAnnotations
> 2. `az monitor app-insights api-key create --write-properties WriteAnnotations  .. `
>    would always result in ReadTelemetry and  AuthenticateSDKControlChannel as well, because nothing is provided for --read-properties and the default is 'ReadTelemetry', 'AuthenticateSDKControlChannel'.
> 
> My assumption and as it seems to behave everywhere else is that i need to say the permission set i want or if i supply no read and write permissions, then default is all. IF i supply my permission set, then only that will be used.
> 
> I believe the bug is here:
> https://github.com/Azure/azure-cli-extensions/blob/master/src/application-insights/azext_applicationinsights/custom.py
> 
> Line 142-145:
> 
> ```
>     if read_properties is None:
>         read_properties = ['ReadTelemetry', 'AuthenticateSDKControlChannel']
>     if write_properties is None:
>         write_properties = ['WriteAnnotations']
> ```

@melborp Hi. You could use `--read-properties '""' --write-properties '""'` to remove all permissions.  I would add one more example at least.

**Comment by melborp** [comment]
@MyronFanQiu I tested with the '""' value and it does work with it. Thank you. 

I still believe its wrong to set default permissions for writing, when i am supplying permissions for reading and nothing for writing. 

Further, In the az powershell module they dont separate read and write permissions and the appinsights api key creation in portal doesnt separate it either. Its just a list of permissions. I wonder if that would simplify the usage.

**Comment by MyronFanQiu** [comment]
> @MyronFanQiu I tested with the '""' value and it does work with it. Thank you.
> 
> I still believe its wrong to set default permissions for writing, when i am supplying permissions for reading and nothing for writing.
> 
> Further, In the az powershell module they dont separate read and write permissions and the appinsights api key creation in portal doesnt separate it either. Its just a list of permissions. I wonder if that would simplify the usage.

Agree that we should not set default permission for writing. But they have been there for a long time. Removing permission would be a breaking change. I would add example first and add warning about the incoming breaking change. Then open another issue to track this one. Thanks for your suggestion.

**Comment by melborp** [comment]
@MyronFanQiu makes sense to take it in steps to handle the breaking change and the workaround is working.
