### ISSUE TITLE
Copied example has extra spaces

### ISSUE THREAD

**Issue by ekpgh** [Azure/azure-cli-extensions#1946]
When I copy the az hpc-cache create example, the result has line breaks which turn into spaces when I paste it into another text document. There are spaces/line breaks in "re source_group" and "sub nets"

az hpc-cache create --resource-group "scgroup" --name "sc1" --location "eastus" \
--cache-size-gb "3072" --subnet "/subscriptions/{{ subscription_id }}/resourceGroups/{{ re
source_group }}/providers/Microsoft.Network/virtualNetworks/{{ virtual_network_name }}/sub
nets/{{ subnet_name }}" --sku-name "Standard_2G"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebed8772-af1e-78c9-750d-341fe346aaf3
* Version Independent ID: 59e765a7-734c-ba8a-3fff-43d5c13e28d4
* Content: [az hpc-cache](https://docs.microsoft.com/en-us/cli/azure/ext/hpc-cache/hpc-cache?view=azure-cli-latest#ext-hpc-cache-az-hpc-cache-create)
* Content Source: [latest/docs-ref-autogen/ext/hpc-cache/hpc-cache.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/hpc-cache/hpc-cache.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S173

**Comment by jiasli** [comment]
Thanks for the feedback. We have removed the extra line breaks from the examples. The document will be updated in the next CLI release.
