### ISSUE TITLE
az network vpn-site not in 2.8.0

### ISSUE THREAD

**Issue by dwrusse** [Azure/azure-cli-extensions#1959]
PS C:\Users> az network vpn-site
az network: 'vpn-site' is not in the 'az network' command group. See 'az network --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
PS C:\Users> az --version
azure-cli                          2.8.0

command-modules-nspkg              2.0.3
core                               2.8.0
nspkg                              3.0.4
telemetry                          1.0.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bc92fbe-8731-dc15-c23e-5b58163ee03a
* Version Independent ID: 48314a31-ffc3-6896-38c2-aa3fa811c1af
* Content: [az network vpn-site](https://docs.microsoft.com/en-us/cli/azure/ext/virtual-wan/network/vpn-site?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/virtual-wan/network/vpn-site.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/virtual-wan/network/vpn-site.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S173

**Comment by MyronFanQiu** [comment]
it's in azure cli extension. Please run `az extension add -n virtual-wan` first.

**Comment by MyronFanQiu** [comment]
close this issue since it's usage issue and should be solved.
