### ISSUE TITLE
az kusto cluster create failing

### ISSUE THREAD

**Issue by nfsbendix** [Azure/azure-cli-extensions#1963]
# Describe the bug

**Command Name**
`az kusto cluster create
Extension Name: kusto. Version: 0.1.0.`

**Errors:**
```
'expiresIn'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
    result = func(*args, **kwargs)
core/pipeline/policies/_authentication.py, ln 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
azure/cli/core/adal_authentication.py, ln 64, in get_token
    return AccessToken(token, int(full_token['expiresIn'] + time.time()))
KeyError: 'expiresIn'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a resource group in an azure subscription
- Open an azure shell
- Run the command:  `az kusto cluster create --cluster-name mykustocluster --resource-group myresourcegroup --location westeurope --sku name="Standard_D11_v2" tier="Standard"`

## Expected Behavior

Would expect cluster to be created.

## Environment Summary
Azure shell
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0
azure-cli-iot-ext 0.8.0

Extensions:
kusto 0.1.0
azure-cli-iot-ext 0.8.0

```

**Comment by yungezz** [comment]
routing to appropriatea team

**Comment by radennis** [comment]
Adding @ilayrn 
@yungezz  How do we change who is cced on Kusto changes? It is being routed to the incorrect person currently.

**Comment by yungezz** [comment]
hi @radennis could you share the right contact point?

**Comment by radennis** [comment]
Please add @ilayrn for now and remove me. @ilayrn is there anyone else you want to be on the contacts?

**Comment by ilayrn** [comment]
@nfsbendix, there's a new version for Azure CLI with up-to-date support for all the functionality provided by Kusto. To install it, run the command: "az extension add -n kusto". After it's installed, the command should work - docs can be found here: https://docs.microsoft.com/en-us/cli/azure/ext/kusto/kusto?view=azure-cli-latest

@yungezz, please add @orhasban as well

**Comment by navba-MSFT** [comment]
@nfsbendix Apologies for the late reply. az kusto module is not supported starting January 1, 2021. Please execute "az extension add -n kusto" to install the supported Kusto extension. More Info here:
https://docs.microsoft.com/en-us/cli/azure/kusto?view=azure-cli-latest

Please let us know if you face any issues. Awaiting your reply.
