### ISSUE TITLE
Can't upload directory from Azure CLI (latest)

### ISSUE THREAD

**Issue by alexsorokoletov** [Azure/azure-cli-extensions#1966]
## Describe the bug

**Command Name**
`az storage blob directory upload
Extension Name: storage-preview. Version: 0.2.10.`

**Errors:**
```
[Errno 2] No such file or directory: '/Users/alex/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_darwin_amd64_10.3.1/azcopy copy ./ https://blimgtdata.blob.core.windows.net/maps/maps/map2/?se=2020-07-03T20%3A47%3A26Z&sp=rwdlacup&sv=2018-03-28&ss=b&srt=sco&sig=BjVrnU5XqtSmxrWMvMAWeueGtqdEtgrqyNxOa%2BBDy54%3D --recursive'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob directory upload --account-name {} -c {} -d {} --recursive -s {}`

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.8.0

Extensions:
storage-preview 0.2.10

```
## Additional Context

![image](https://user-images.githubusercontent.com/1788581/86408042-40609d80-bc84-11ea-961c-d6f3e8f92d19.png)

ran the same command in cmdline and it seems to work

![image](https://user-images.githubusercontent.com/1788581/86408184-7c93fe00-bc84-11ea-8c69-c42b2e33e70b.png)

**Comment by yonzhan** [comment]
add to S173

**Comment by jmostella** [comment]
I believe I ran into the same issue when running on __Linux__. I have submitted a PR https://github.com/Azure/azure-cli-extensions/pull/2005

(technical explanation of the root cause is in my PR comment)

**Comment by Juliehzl** [comment]
fix in new release. please upgrade the extension version with `az extension update -n storage-preview`

**Comment by ggg333** [comment]
I ran in to the same issue, and did the update of the extension and now running in to Permission Denied 

[Errno 13] Permission denied

**Comment by ggg333** [comment]
`{
  "extensionType": "whl",
  "metadata": {
    "author": "Microsoft Corporation",
    "author_email": "azpycli@microsoft.com",
    "azext.isPreview": true,
    "azext.minCliCoreVersion": "2.0.67",
    "classifiers": [
      "Development Status :: 4 - Beta",
      "Intended Audience :: Developers",
      "Intended Audience :: System Administrators",
      "Programming Language :: Python",
      "Programming Language :: Python :: 2",
      "Programming Language :: Python :: 2.7",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3.4",
      "Programming Language :: Python :: 3.5",
      "Programming Language :: Python :: 3.6",
      "License :: OSI Approved :: MIT License"
    ],
    "description": "An Azure CLI Extension for storage preview features. This will replace the full storage module.\n\n\n",
    "filename": "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/storage_preview-0.2.11.dist-info",
    "home_page": "https://github.com/Azure/azure-cli-extensions/tree/master/src/storage-preview",
    "license": "MIT",
    "metadata_version": "2.0",
    "name": "storage-preview",
    "platforms": [
      "UNKNOWN"
    ],
    "summary": "Provides a preview for upcoming storage features.",
    "version": "0.2.11"
  },
  "name": "storage-preview",
  "path": "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview",
  "version": "0.2.11"
}`

**Comment by jmostella** [comment]
@ggg333 Yes I also saw this one as well. It looks like the Darwin binary was originally checked in without the execute flag set.

It is incidentally fixed in another PR https://github.com/Azure/azure-cli-extensions/pull/2020/files

Would you mind opening a separate issue?

**Comment by jmostella** [comment]
@ggg333 Could you try it again? The other PR I mentioned above has been merged this morning.

**Comment by ggg333** [comment]
@jmostella Still running in to the same issue

`The command failed with an unexpected error. Here is the traceback:

[Errno 13] Permission denied: '/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_darwin_amd64_10.3.1/azcopy'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 244, in new_handler
    handler(ex)
  File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 186, in handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 20, in storage_blob_upload
    storage_blob_copy(azcopy, source, _add_url_sas(destination, azcopy.creds.sas_token), recursive=recursive)
  File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 15, in storage_blob_copy
    azcopy.copy(source, destination, flags=flags)
  File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 47, in copy
    self.run_command(['copy', source, destination] + flags)
  File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 43, in run_command
    subprocess.call(command, env=dict(os.environ, **env_kwargs))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_darwin_amd64_10.3.1/azcopy'`

**Comment by jmostella** [comment]
> @jmostella Still running in to the same issue
> 
> `The command failed with an unexpected error. Here is the traceback:
> 
> [Errno 13] Permission denied: '/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_darwin_amd64_10.3.1/azcopy'
> Traceback (most recent call last):
> File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
> cmd_result = self.invocation.execute(args)
> File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/**init**.py", line 654, in execute
> raise ex
> File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/**init**.py", line 718, in _run_jobs_serially
> results.append(self._run_job(expanded_arg, cmd_copy))
> File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/**init**.py", line 709, in _run_job
> cmd_copy.exception_handler(ex)
> File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/**init**.py", line 244, in new_handler
> handler(ex)
> File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/**init**.py", line 186, in handler
> raise ex
> File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/**init**.py", line 688, in _run_job
> result = cmd_copy(params)
> File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/**init**.py", line 325, in **call**
> return self.handler(*args, **kwargs)
> File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/**init**.py", line 545, in default_command_handler
> return op(**command_args)
> File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 20, in storage_blob_upload
> storage_blob_copy(azcopy, source, _add_url_sas(destination, azcopy.creds.sas_token), recursive=recursive)
> File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 15, in storage_blob_copy
> azcopy.copy(source, destination, flags=flags)
> File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 47, in copy
> self.run_command(['copy', source, destination] + flags)
> File "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 43, in run_command
> subprocess.call(command, env=dict(os.environ, **env_kwargs))
> File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
> with Popen(*popenargs, **kwargs) as p:
> File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> PermissionError: [Errno 13] Permission denied: '/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_darwin_amd64_10.3.1/azcopy'`


@ggg333 So the last line shows its still pointing to azcopy `v10.3.1`, the last update should be pointing to `v10.5.0`

Theres a few things you can try, given that you have already run `az extension update -n storage-preview` again (after the last merge)

1. check that `/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_darwin_amd64_10.5.0/` exists if it doesn't then there's likely a problem with the update command.
1. remove your `/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview` directory altogether and reinstall the extension.

Let me know how it works out.

**Comment by ggg333** [comment]
@jmostella i removed the folder like you shared and then did "az extension add -n storage-preview" and tried "az extension update -n storage-preview". When listed the folder /Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/ i see only the following and not the 10.5.0

2154IADGANP:solutioninsight ganesh.palanisamy$ cd /Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/
02154IADGANP:azcopy ganesh.palanisamy$ ls
__init__.py			__pycache__			azcopy_darwin_amd64_10.3.1	azcopy_linux_amd64_10.3.1	azcopy_windows_amd64_10.3.1	util.py

**Comment by ggg333** [comment]
@jmostella : the way i fixed it is by downloading the azcopy_darwin_amd64_10.5.1 and extract it under "/Users/ganesh.palanisamy/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/" and deleted the azcopy_darwin_amd64_10.3.1 and created a symlink to azcopy_darwin_amd64_10.5.1 as azcopy_darwin_amd64_10.3.1. Now it works. But this isn't the right way to fix though. Not sure why update isn't pulling the right version

**Comment by jmostella** [comment]
@ggg333 Yeah definitely not the way we want to solve it. I tested on my Mac and see the same thing happening. Definitely looks like an issue with `az extension add\update`.

Will open an issue about this later, and add you.

**Comment by jmostella** [comment]
Tested out today on `OSX`, and verified the latest version is available and working 

```json
{
  "azure-cli": "2.8.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.8.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "storage-preview": "0.2.12"
  }
}
```

```console
Azcopy command: ['/Users/*******/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_darwin_amd64_10.5.0/azcopy', 'copy', '/Users/*******/Downloads/dist/*******/**', 'https://*******.blob.core.windows.net/$web/?se=2020-08-02T13%3A58%3A31Z&sp=rwdlacup&sv=2018-03-28&ss=b&srt=sco&sig=*******', '--recursive']
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 5bb3621b-42ea-7d4b-4d2f-1a41a10d0840 has started
Log file is located at: /Users/*******/.azcopy/5bb3621b-42ea-7d4b-4d2f-1a41a10d0840.log

INFO: azcopy: A newer version 10.5.1 is available to download

0.0 %, 0 Done, 0 Failed, 16 Pending, 0 Skipped, 16 Total, 


Job 5bb3621b-42ea-7d4b-4d2f-1a41a10d0840 summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 16
Number of Folder Property Transfers: 0
Total Number of Transfers: 16
Number of Transfers Completed: 16
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 820923
Final Job Status: Completed
```

Apologies for the confusion. Looks like the [site](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest) doesn't get updated with the latest versions automatically. But the latest versions are visible via the cli

**Comment by ggg333** [comment]
@jmostella : Appreciate all your help. Looks like its working as it should. I removed and re-added the extension.

az extension show -n storage-preview -o table
ExtensionType    Name             Path                                                           Version
---------------  ---------------  -------------------------------------------------------------  ---------
whl              storage-preview  /Users/ganesh.palanisamy/.azure/cliextensions/storage-preview  0.2.12

Thanks,
Ganesh.
