### ISSUE TITLE
Not able to run aks get-versions command 

### ISSUE THREAD

**Issue by tomaszms** [Azure/azure-cli-extensions#1972]
## Describe the bug

**Command Name**
`az aks get-versions
Extension Name: aks-preview. Version: 0.4.47.`

**Errors:**
```
APIVersion 2020-04-01 is not available
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/container_service_client.py, ln 219, in container_services
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2020-04-01 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-versions --location {} --output {}`

## Environment Summary
```
macOS-10.15.2-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.8.0

Extensions:
aks-preview 0.4.47
interactive 0.4.4

```

**Comment by yonzhan** [comment]
aks

**Comment by atulaggarwal** [comment]
As stated in [github issue](https://github.com/Azure/azure-cli-extensions/issues/1783#issuecomment-635786889), That was a bug in 0.4.47, it's fixed in the following versions.

**Comment by Jen7714** [comment]
Closing since this issue has been fixed.
