### ISSUE TITLE
"Unexpected keyword argument 'junction'" when I didn't pass argument 'junction'

### ISSUE THREAD

**Issue by ekpgh** [Azure/azure-cli-extensions#1997]
## Complaint about junction when it was not passed?

I had trouble getting a storage target update command to work - it timed out - possibly errors in the junction syntax when I was trying to change a junction. So I stopped trying to change a junction and tried to change the usage model. 

Command I issued to get this response was $ az hpc-cache nfs-storage-target update --cache-name doc-cache0629 --name nfsd1 --nfs3-usage-model READ_HEAVY_INFREQ

**Command Name**
`az hpc-cache nfs-storage-target update
Extension Name: hpc-cache. Version: 0.1.0.`

**Errors:**
```
update_hpc_cache_nfs_storage_target() got an unexpected keyword argument 'junction'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 545, in default_command_handler
    return op(**command_args)
TypeError: update_hpc_cache_nfs_storage_target() got an unexpected keyword argument 'junction'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az hpc-cache nfs-storage-target update --cache-name {} --name {} --nfs3-usage-model {}`

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.7.0 *

Extensions:
hpc-cache 0.1.0

```

**Comment by yonzhan** [comment]
add to S173
