### ISSUE TITLE
No Databricks extension installation instructions.

### ISSUE THREAD

**Issue by JamesEarle** [Azure/azure-cli-extensions#2008]
I was able to find the extension installation instructions in the `README.md` [here](https://github.com/Azure/azure-cli-extensions/blob/e6df9392bf1a03b0213293a51865cbb64e46e301/src/databricks/README.md) but this is not documented using Microsoft Docs, even though many tutorials and other information is. The existence of the reference for `az workspace` [here](https://docs.microsoft.com/en-us/cli/azure/ext/databricks/?view=azure-cli-latest) implies that this by default under `az` but that is not the case. It would great to have instructions here to clearly indicate how to install and verify that it's been installed correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87c06327-d2bd-2888-6537-f64c1d2f04c1
* Version Independent ID: b34420fe-226a-78a7-f3cc-bbd904d317f1
* Content: [databricks](https://docs.microsoft.com/en-us/cli/azure/ext/databricks/?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/databricks/index.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/databricks/index.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @JamesBirdsall is this helpful https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview?view=azure-cli-latest#install-extensions?

**Comment by JamesEarle** [comment]
@yungezz I believe you meant to @ me, not James Birdsall?

This does provide extension installation instructions, but nowhere in the documentation for DataBricks as it specifically mentioned that an extension installation is required because it is not under `az` by default. It would be nice to add this detail somewhere so it's clear that if using `az` CLI you're required to perform this step

**Comment by fengzhou-msft** [comment]
The following note is added in MS doc:
> This reference is part of the **databricks** extension for Azure CLI and requires version 2.3.1 or higher. The extension will automatically install the first time you run an **databricks** command. [Learn more](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview) about extensions.
