### ISSUE TITLE
Example needed showing how to update property value containing a space ' ' character

### ISSUE THREAD

**Issue by pskelley55** [Azure/azure-cli-extensions#2009]
Platform: Windows 10  PowerShell CLI
Assume Device Twin holds:
"time_settings": {
"timezone_id_name": "Mountain Standard Time",
"utc_offset": "-07:00",
"dst_observed": true,
"dst_active": true
}
Show how to update property "timezone_id_name" using value "Pacific Standard Time"

Expecting answer to be of this form (please correct as needed):
PS C:\> az iot hub device-twin update --hub-name sznacaiottest --device-id 000680082b53 --set properties.desired.time_settings='{\"timezone_id_name\":\"Pacific Standard Time\",\"dst_observed\":true,\"utc_offset\":\"-07:00\",\"dst_active\":true}'

Using Windows 10 PowerShell, can you provide an example of the CORRECT way to update a property with a value containing a space?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485cbe25-33b0-fc0a-c884-5674379f59f3
* Version Independent ID: 5b20df05-be9f-045c-c020-a21cc37721f1
* Content: [az iot hub module-twin](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub/module-twin?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub/module-twin.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub/module-twin.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by pskelley55** [comment]
Sorry, forgot to add the above question centers around Azure CLI device-twin property modification using PowerShell.
Hopefully, this question will get to the correct expert. :-)

**Comment by pskelley55** [comment]
Never mind. Found my answer:
az iot hub device-twin update --hub-name sznacaiottest --device-id 000680082b53 --set properties.desired='{\"time_settings\":{\"timezone_id_name\": \"Pacific Standard Time\", \"dst_observed\":true, \"utc_offset\":\"-07:00\", \"dst_active\":true}}'

With the help of this web-page:
https://github.com/Azure/azure-iot-cli-extension/wiki/Tips 

Resolved.  Thanks anyway.

**Comment by yonzhan** [comment]
iot hub
