### ISSUE TITLE
Extend image-copy to allow copying images between different subscriptions

### ISSUE THREAD

**Issue by beezly** [Azure/azure-cli-extensions#203]
### Extension name (the extension in question)

image-copy

### Description of issue (in as much detail as possible)

It would be great if image-copy could copy images between different subscriptions.
-----

**Comment by tamirkamara** [comment]
@beezly You are talking about subscriptions in the same tenant. right?

**Comment by beezly** [comment]
Yes :)

**Comment by dominik-lekse** [comment]
This feature would be very helpful

**Comment by raghav8888** [comment]
Any update on this or ETA? This would be really cool for managing images across different subscriptions.
