### ISSUE TITLE
Wrong query example

### ISSUE THREAD

**Issue by amitkumarcn** [Azure/azure-cli-extensions#2036]
[Enter feedback here]

az graph query -q "where type =~ "Microsoft.Compute" | project name, tags" --subscriptions 11111111-1111-1111-1111-111111111111, 22222222-2222-2222-2222-222222222222

Above mention query does not execute, for multiple subscriptions, subscriptions should be space seperated, rather then comma seperated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75d1021b-9184-56de-3a65-4680868c9143
* Version Independent ID: f2fb2ab8-c0c6-5350-a99a-5a5b90e2b14b
* Content: [az graph](https://docs.microsoft.com/en-us/cli/azure/ext/resource-graph/graph?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/resource-graph/graph.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/resource-graph/graph.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
resource graph

**Comment by snaheth** [comment]
Hi @amitkumarcn -- I'm a bit confused. Are you requesting that the subscriptions parameter should be space separated OR are you running into issues with comma separated subscriptions? If it's the latter, please retry it. I was able to run this successfully just now. If you still hit an error, please share the output here and include a correlationId so we can take a look.

**Comment by Klaas-** [comment]
Hi,
I can say that the comma seperated values do not work for me either (RHEL7, bash, azure-cli 2.19)

--subscriptions 11111111-1111-1111-1111-111111111111, 22222222-2222-2222-2222-222222222222, 33333333-3333-3333-3333-333333333333

will give an error
"message": "Subscription ids have to be valid GUIDs. Given: '11111111-1111-1111-1111-111111111111,,22222222-2222-2222-2222-222222222222,'."

when seperating with spaces it works fine.

**Comment by fenwickt** [comment]
Hi @Klaas- thank you for the feedback. We are updating our CLI module and will fix this example in the help file.

**Comment by snaheth** [comment]
Closing this as @fenwickt's pull request https://github.com/Azure/azure-cli-extensions/pull/3344 updates the help file, which results in the right  `--subscriptions` parameter example showing up in the Azure CLI documentation for Resource Graph.
