### ISSUE TITLE
request: "az ml computetarget create aks" why hardcoded "load-balancer-subnet" name?

### ISSUE THREAD

**Issue by karlti** [Azure/azure-cli-extensions#2039]
[Enter feedback here]

Hello,
when creating an AKS cluster via **"az ml"** CLI extension, apparently the subnet name  in **"--load-balancer-subnet"** has to be **"aks-subnet"**. This seems to be mandatory.

This conflicts with naming-conventions in big corporations!

Can this not be changed to choose a custom subnet name?

Thank you  in advance.

Karl Tietze

EMEA CSS Azure Machine Learning Service
Tel:  ++49 (89) 3176-4358
Email: karlti@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e203eb0b-1c78-a76e-62e7-eddeeffdf0e3
* Version Independent ID: 38721d5a-59f3-24d0-3a76-fdcda10bd9c7
* Content: [az ml computetarget create](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-ml/ml/computetarget/create?view=azure-cli-latest#ext-azure-cli-ml-az-ml-computetarget-create-aks)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-ml/ml/computetarget/create.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-ml/ml/computetarget/create.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by lostmygithubaccount** [comment]
@sauryadas

**Comment by sauryadas** [comment]
@karlti this i believe is specifically for an  AKS with a BYO VNET. It is this VNET that the aml inferencing pods (scoring fe, deployment) are deployed on. They cannot be deployed on a different vnet. 

Feel free to close this and send me an email internally

**Comment by swatig007** [comment]
closing per above comment
