### ISSUE TITLE
botservice extension never seems to be able to provision MS Apps.

### ISSUE THREAD

**Issue by changesbyjames** [Azure/azure-cli-extensions#204]
### Extension name (the extension in question)
botservice

### Description of issue (in as much detail as possible)
Regardless of the account (corporate AD account, ADFS account, microsoft account) the CLI extension can never provision a MS App Id & password in order to create a bot.

I can confirm that I can get a token because I've looked into the source code of the extension and used the same details to get a code. The access code appears to be valid but on any call to `https://dev.botframework.com/api/botApp/provisionConvergedApp` returns with a 403 forbidden and never succeeds. As you can imagine this stops bot channel registrations being created automatically, which is exactly what we want to do with the cli.

I can provide any more details needed to debug this. 

Thanks,
James

-----

**Comment by strangecyan** [comment]
A quick update; if I edit the extension to use `72f988bf-86f1-41af-91ab-2d7cd011db47` as the tenantId (the one that the Azure Portal uses when calling the same url) it works.
