### ISSUE TITLE
"az network firewall network-rule delete" note

### ISSUE THREAD

**Issue by sarah026** [Azure/azure-cli-extensions#2066]
Hi, 
If there is only one rule in the collection then this command won't let you delete the rule... because then the collection will have no rules, which seems to be a requirement.
**az network firewall network-rule delete**  

`az : AzureFirewallRuleCollection /subscriptions/[removed] must contain at least one rule
At line:1 char:1
+ az network firewall network-rule delete --verbose --firewall-name $fi ...
`

Please add that to the documentation, it confused me for a bit.
Thanks

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: a90f7721-6e37-012e-a118-277d5c113f65
* Version Independent ID: c89a7d07-fc9d-748c-d562-2ec9f0295e15
* Content: [az network firewall network-rule](https://docs.microsoft.com/de-ch/cli/azure/ext/azure-firewall/network/firewall/network-rule?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-firewall/network/firewall/network-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-firewall/network/firewall/network-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S174
