### ISSUE TITLE
Support an already existing node resource group on 'az aks create' with custom resource group names for infrastructure resources

### ISSUE THREAD

**Issue by mguster** [Azure/azure-cli-extensions#2072]
Assuming there is an already existing resource group 'MyAks-Nodes' created by IT department with some policies and role assignments and this resource group is foreseen as target for the aks node resources. 

When creating the cluster with $NodeResourceGroupName = 'MyAks-Nodes' ...

```
az aks create `
    --subscription $SubscriptionId `
    --resource-group $ResourceGroupName `
    --node-resource-group $NodeResourceGroupName `
    --nodepool-name nplin `
    --name $AksClusterName `
    --node-count 1 `
    --enable-addons monitoring `
    --generate-ssh-keys `
    --windows-admin-password $WindowsPassword `
    --windows-admin-username $WindowsAdminUser `
    --enable-vmss `
    --network-plugin azure `
    --attach-acr $ContainerRegistryName`
```
The following error is reported:
```
Operation failed with status: 'Bad Request'. Details: Node resource group 'MyAks-Nodes' under subscription 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx' already exists, please provide a new one.
```

Is there a reason why the k8s node resources should not be applied to an already existing resource group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea52f6a-7414-7aa2-3708-7b802f243a16
* Version Independent ID: cf003f17-b9f7-04d4-89c2-770273b40533
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks?view=azure-cli-latest#ext-aks-preview-az-aks-create)
* Content Source: [latest/docs-ref-autogen/ext/aks-preview/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/aks-preview/aks.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aks

**Comment by TomGeske** [comment]
Not all cluster resources we create in nodes resource have unique names. 

@jluk for visibility

**Comment by mguster** [comment]
I see. But it would be nice to leave this to the users responsibility and just return a warning instead of error and abort.

**Comment by jluk** [comment]
A major risk in supporting existing resource groups to pass in as a custom infrastructure RG is that AKS cannot easily detect if there are existing resources and upon deletion of AKS, which resources should be deleted / impacted. Today AKS assumes we own the entire RG, as result we limit new RGs only to be passed as a custom RG to host IaaS for a cluster.

Hopefully this gives some insight into the decision, it's not on the roadmap at the moment to support existing RGs for this scenario but we're listening to scenarios blocked on it.

**Comment by samssann** [comment]
Azure/AKS#1896
