### ISSUE TITLE
Should have bias free warning

### ISSUE THREAD

**Issue by GossiTheDog** [Azure/azure-cli-extensions#2080]
Important

Bias-free communication
Microsoft supports a diverse and inclusionary environment. This article contains references to the words allowlist and blacklist. The Microsoft style guide for bias-free communication recognizes this as an exclusionary word. The word is used in this article for consistency because it’s currently the word that appears in the software. When the software is updated to remove the word, this article will be updated to be in alignment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773c713c-34d2-c74c-8c58-5cf273cbb25a
* Version Independent ID: 0b6343a9-bbcd-2f54-b21e-cf9222c21e9f
* Content: [az network firewall threat-intel-whitelist](https://docs.microsoft.com/en-us/cli/azure/ext/azure-firewall/network/firewall/threat-intel-whitelist?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-firewall/network/firewall/threat-intel-whitelist.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-firewall/network/firewall/threat-intel-whitelist.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S174
