### ISSUE TITLE
az datafactory pipeline create fails

### ISSUE THREAD

**Issue by vladris** [Azure/azure-cli-extensions#2082]
I've been trying to use az datafactory pipeline create passing it a .json file with ```@json```.

I tried to eliminate issues with the JSON so I picked a very simple one from the unit tests here: https://github.com/Azure/azure-cli-extensions-pr/blob/305e20c86670c03eedac152cf7aa3ca85752ebe9/src/datafactory/azext_datafactory/manual/tests/latest/test_datafactory_scenario.py

Json file is:
```
{
    "activities": [
        {
            "name":"Wait1",
            "type":"Wait",
            "dependsOn":[],
            "userProperties": [],
            "typeProperties": {
                "waitTimeInSeconds": 5
            }
        }
    ],
    "annotations": []
}
```

Command is:

```
 az datafactory pipeline create --factory-name "adfvladris" --name "pipeline1" --resource-group adf-rg --pipeline '@pipeline.json'
```

I am not sure what is missing here. I get the below error:

**Command Name**
`az datafactory pipeline create
Extension Name: datafactory. Version: 0.1.0.`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, TypeError: 'NoneType' object is not iterable, DeserializationError: Unable to deserialize to object: type, TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
pip-install-yh2ypeu1\msrest\msrest\serialization.py, ln 1291, in _deserialize
pip-install-yh2ypeu1\msrest\msrest\serialization.py, ln 1077, in rest_key_case_insensitive_extractor
pip-install-yh2ypeu1\msrest\msrest\serialization.py, ln 1099, in attribute_key_case_insensitive_extractor
...
pip-install-yh2ypeu1\msrest\msrest\serialization.py, ln 1099, in attribute_key_case_insensitive_extractor
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, TypeError: 'NoneType' object is not iterable, DeserializationError: Unable to deserialize to object: type, TypeError: 'NoneType' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datafactory pipeline create --factory-name {} --name {} --resource-group {} --pipeline {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.9.1

Extensions:
datafactory 0.1.0

```

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
The issue is caused by the generated SDK flattening a three-layer property `properties.folder.name`, it caused trouble when being serialized. 

I'm checking with codegen team to disable the flattening through configuration and regenerate the SDK.

**Comment by vladris** [comment]
Thanks a lot @fengzhou-msft, any idea when the extension will be updated to address the issue?
