### ISSUE TITLE
image-copy-extension seems to ignore --subscription paramater

### ISSUE THREAD

**Issue by golaat** [Azure/azure-cli-extensions#2083]
Issuing an `az image copy`  without any parameters shows an optional `--subscription` parameter. Setting the --subscription parameter seems to be ignored in favor to what the default subscription is set to.

So, if I set my default subscription to via `az account set --subscription foo` and then try to run the following command, it fails to find my source resource group of fhi-lab-shared-hub-rg

`az image copy --subscription fhi-lab-hub-sub --source-resource-group fhi-lab-shared-hub-rg --target-subscription fhi-lab-sub --target-resource-group fii-lab-bisd-golaat-rg --source-object-name pbig-image --source-type image --target-name pbig-image --target-location eastus2`

If I do a `az account set --subscription fhi-lab-hub-sub` it finds the fhi-lab-shared-hub-rg

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by qwordy** [comment]
`--subscription` is not used in code. Don't use this parameter. It has no effect. I am trying to remove this global parameter in this command.

**Comment by qwordy** [comment]
I  met some technical issue to remove a global parameter. I need more time to figure out if it is possible.

**Comment by qwordy** [comment]
It is removed now! Download the latest version and give a try.
