### ISSUE TITLE
Add support for allowBlobPublicAccess flag for Storage accounts creation

### ISSUE THREAD

**Issue by mpchen** [Azure/azure-cli-extensions#2084]
[Enter feedback here]

Can we add cli support for the "allowBlobPublicAccess" flag? this is a new setting (https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-prevent). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8607c4-c478-8fba-09d5-91bf30939bfc
* Version Independent ID: 0ab8cdfd-867c-4205-b8a4-90df2a17cd9f
* Content: [az storage account](https://docs.microsoft.com/en-us/cli/azure/ext/storage-preview/storage/account?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/storage-preview/storage/account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/storage-preview/storage/account.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
Hi @Juliehzl , could you please help with this issue ? Thanks

**Comment by yonzhan** [comment]
add to S174

**Comment by Juliehzl** [comment]
Done in https://github.com/Azure/azure-cli/pull/14422.

Please use main azure cli with latest version and make sure storage-preview extension not installed.
