### ISSUE TITLE
"project" not an optional parameter

### ISSUE THREAD

**Issue by kaletkamk** [Azure/azure-cli-extensions#2089]
`Project` is specified in documentation as optional parameter, but it's required.

`az pipelines queue show --id 4529`
`--project must be specified. The value should be the ID or name of a team project. You can set a default value by running: az devops configure --defaults project=<ProjectName>.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd59e661-68c6-4c64-e2e3-a4d8e158e5bb
* Version Independent ID: 6aad853f-c13f-758b-8c1b-25f8b6b0b4d1
* Content: [az pipelines queue](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/queue?view=azure-cli-latest#ext-azure-devops-az-pipelines-queue-show)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines/queue.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines/queue.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
pipelines

**Comment by RakeshMohanMSFT** [comment]
These params are required if they are not configured as default values.

--org --organization
Azure DevOps organization URL. You can configure the default organization using az devops configure -d organization=ORG_URL. **Required** if not configured as default or picked up via git config. Example: https://dev.azure.com/MyOrganizationName/.

--project -p
Name or ID of the project. You can configure the default project using az devops configure -d project=NAME_OR_ID. **Required** if not configured as default or picked up via git config.
