### ISSUE TITLE
Az Front door - Load balancing - How can I set the latency to force round robin from az cli

### ISSUE THREAD

**Issue by flyingUnderTheRadar** [Azure/azure-cli-extensions#2093]
Info or functionality missing
- Page needs info on how I can tweak the default load balancer (Didn't see an update) latency settings. 
- Additionally since I can't update I created another one. What is the behavior when there are more than one load balancers set up? 
- Can I choose which load balancer is active at any point of time?

When I try to delete the default loadbalancer that is created I get this response
BadRequest - A resource reference was invalid: "BackendPool DefaultBackendPool contains an invalid reference to LoadBalancingSettings: "/subscriptions/<subscriptionId>/resourceGroups/<rg-Name>/providers/Microsoft.Network/frontdoors/<fd-name>/loadBalancingSettings/DefaultLoadBalancingSettings""

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ef449d-9483-7b14-a2e7-c81e9c6da7c0
* Version Independent ID: 3cc41ba9-a937-d947-d709-8ec329163cf8
* Content: [az network front-door load-balancing](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/load-balancing?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door/load-balancing.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door/load-balancing.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
Hi @MyronFanQiu , could you please help with this issue ? Thanks

**Comment by yonzhan** [comment]
add to S174

**Comment by flyingUnderTheRadar** [comment]
As an update I was able to get around it by creating a new load balancer, creating a new backend pool with this load balancer and the default health probe and then deleting the default backend pool. That's a pretty round about way to update latency. It would be really helpful if either 
- No default pools are created 
- Update functionality for backend pool includes load balancer OR load balancer has update

**Comment by MyronFanQiu** [comment]
@flyingUnderTheRadar Hi. Thanks for the suggestion. I would investigate this issue and improve the user experience based on your suggestion later.

**Comment by MyronFanQiu** [comment]
@flyingUnderTheRadar Hi, Here are the answers from my perspective. If you have any more question, I can invite service team to answer since they have more knowledge.
- It's a good suggestion. We will support `update` command later. Currently, we can only set the latency at the creation step.
- Regarding to this question, If I understand it correctly, I think you want to add LB Settings into a backend pool through `az network front-door backend-pool backend add`
- Based on my knowledge, the active load balancer is chosen by `routing-rules`.
