### ISSUE TITLE
az boards iteration team list, where to get the Team ID?

### ISSUE THREAD

**Issue by FilBot3** [Azure/azure-cli-extensions#2107]
Looking at the documentation for `az boards iteration team list` it requires a team id for it to list. However, there doesn't seem to be a way to list the teams without knowing first the id. Where can we get that ID? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 876612e4-7fe4-0078-24e9-110ad121f526
* Version Independent ID: 38f3144e-39e2-952d-2f7b-5e5c406d6d83
* Content: [az boards iteration team](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards/iteration/team?view=azure-cli-latest#ext-azure-devops-az-boards-iteration-team-list)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/boards/iteration/team.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/boards/iteration/team.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
devops

**Comment by FilBot3** [comment]
> devops

I'm not sure I follow. Can you elaborate as to what you're saying?

**Comment by yonzhan** [comment]
devops service team should look into this.

**Comment by RakeshMohanMSFT** [comment]
You should be able to use the team "name" not necessary to use the id. Please reopen if you have further questions
![image](https://user-images.githubusercontent.com/49954584/210940488-d5ed584f-548b-4772-bfe5-21c0dc1797fe.png)
