### ISSUE TITLE
Error creating an application rule from az firewall

### ISSUE THREAD

**Issue by abarrionuevodevops** [Azure/azure-cli-extensions#2108]
## Describe the bug

**Command Name**
`az network firewall application-rule create
Extension Name: azure-firewall. Version: 0.5.0.`

**Errors:**
```
Unable to build a model: Unable to deserialize response data. Data: 80', int, ValueError: invalid literal for int() with base 10: "80'", DeserializationError: Unable to deserialize response data. Data: 80', int, ValueError: invalid literal for int() with base 10: "80'"
Traceback (most recent call last):
pip-install-yh2ypeu1\msrest\msrest\serialization.py, ln 1437, in deserialize_data
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network firewall application-rule create -g {} -f {} --collection-name {} -n {} --source-addresses {} --protocols {} {} --fqdn-tags {} --action {} --priority {}`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.9.1

Extensions:
aks-preview 0.4.57
azure-firewall 0.5.0

```

**Comment by yonzhan** [comment]
add to S174

**Comment by MyronFanQiu** [comment]
Based on your error message, there is a quote together with 80. Could you confirm your script to remove the `'`?

**Comment by MyronFanQiu** [comment]
@abarrionuevodevops Did you solve this issue? If so, I would close this issue later.

**Comment by MyronFanQiu** [comment]
close this one since it should be usage error. Feel free to reopen it if you still encounter any problem.
