### ISSUE TITLE
Unable to addon IngressGateway 

### ISSUE THREAD

**Issue by rajkrishnamurthy** [Azure/azure-cli-extensions#2109]
## Describe the bug

**Command Name**
`az aks enable-addons
Extension Name: aks-virtual-node. Version: 0.2.0.`

**Errors:**
```
'ingressAppGW'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aks-virtual-node/azext_aksvirtualnode/commands.py, ln 43, in enable_addon_override
    instance = _update_addons_extension(cmd, instance, subscription_id, resource_group_name, addons, enable=True,
cliextensions/aks-virtual-node/azext_aksvirtualnode/commands.py, ln 79, in _update_addons_extension
    addon = ADDONS[addon_arg]
KeyError: 'ingressAppGW'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons -n {} -g {} -a {}`

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.4
Installer: HOMEBREW

azure-cli 2.9.1

Extensions:
aks-preview 0.4.57
aks-virtual-node 0.2.0

```

**Comment by yonzhan** [comment]
aks

**Comment by TomGeske** [comment]
aks-virtual-node extension shouldn't be needed anymore. Can you remove it and try again?

`az extension remove -n aks-virtual-node`

**Comment by navba-MSFT** [comment]
@TomGeske Apologies for the late reply. I hope you had a chance to look at the above comment. Also refer [this](https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing) article for more info. Could you please let us know if you still need any assistance on this issue ? Awaiting your reply.
