### ISSUE TITLE
need to find out if az datafactory pipeline create-run  command finishes - need a show of run_id

### ISSUE THREAD

**Issue by hansolo2218** [Azure/azure-cli-extensions#2110]
[Enter feedback here]

--- 
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bd249-9305-3c25-8bca-d911c5b86880
* Version Independent ID: f50fd6b7-c141-982c-5362-f123b9e5bf04
* Content: [az datafactory pipeline](https://docs.microsoft.com/en-us/cli/azure/ext/datafactory/datafactory/pipeline?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/datafactory/datafactory/pipeline.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/datafactory/datafactory/pipeline.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by hansolo2218** [comment]
data factory create-run command doesn't tell you if it ran successfully.  get command or show command doesn't filter for run_id success - there is  no monitor command

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
@hansolo2218 There is the [az datafactory pipeline-run show](https://docs.microsoft.com/en-us/cli/azure/ext/datafactory/datafactory/pipeline-run?view=azure-cli-latest#ext_datafactory_az_datafactory_pipeline_run_show) command. Can you try it and see if it meets your needs?

**Comment by fengzhou-msft** [comment]
Please let us know if you still have questions.
