### ISSUE TITLE
az monitor app-insights api-key show --> is this still valid?

### ISSUE THREAD

**Issue by ronikurnia1** [Azure/azure-cli-extensions#2114]
[Enter feedback here]

Hi,
Just tried to show the API-Key with the following command on Azure Cloud CLI, but got the following message:

```
PS /home/xxxx> az monitor app-insights api-key show --app BlazingXXXXXInsights -g blazingXXXXX
az monitor: 'app-insights' is not in the 'az monitor' command group. See 'az monitor --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8baafade-06ad-e452-af14-7798fb17209f
* Version Independent ID: 45201db1-8a1c-f2f9-9771-32a179db6b73
* Content: [az monitor app-insights api-key](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights/api-key?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/api-key.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/api-key.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S174

**Comment by MyronFanQiu** [comment]
@ronikurnia1 Hi. I think you didn't install the extension. Please run `az extension add -n application-insights` first. Recently we're solving such issue to auto install extension.

**Comment by MyronFanQiu** [comment]
close this issue since it's known issue and we're solving it.
