### ISSUE TITLE
Parameter 'ManagedClusterWindowsProfile.admin_password' regex missing numbers

### ISSUE THREAD

**Issue by lindhe** [Azure/azure-cli-extensions#2115]
https://github.com/Azure/azure-cli-extensions/blob/1f559cd4089d4220c509181ff7f933c6a7aa5110/src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2019_04_01/models/managed_cluster_windows_profile.py#L29

I found that the regex that governs the `ManagedClusterWindowsProfile.admin_password` is incorrect. It says [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements#reference) that it may include "Base 10 digits (0 through 9)" but the regex does not allow numbers.

### az version

```
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.58",
    "azure-devops": "0.18.0"
  }
}
```

**Comment by yonzhan** [comment]
aks

**Comment by TomGeske** [comment]
@lindhe: Can you make sure to update to latest CLI (2.9.1) and retry?

**Comment by lindhe** [comment]
No, that's too much of a bother.

**Comment by TomGeske** [comment]
This functionality moved from cli-extension to CLI core. I just run the command below with az cli 2.9.1 and it worked:

`az aks create -g <rg-name> -n <cluster-name> --windows-admin-password 'passW)RD1234' --windows-admin-username master --generate-ssh-keys -c 1 --network-plugin azure`
