### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by SQLDataSide** [Azure/azure-cli-extensions#2116]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0565525-2293-b262-845d-4817331be5d6
* Version Independent ID: 41bff8c3-e3bc-e5a4-8c56-00e415ce710b
* Content: [az kusto database](https://docs.microsoft.com/en-us/cli/azure/ext/kusto/kusto/database?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/kusto/kusto/database.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/kusto/kusto/database.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SQLDataSide** [comment]
Hi 
I am trying to use "az kusto database add-principal" having the fqn="msauser=myEmail@Email.com" and same for "az kusto database remove-principal"
they are not working with any msauser

I am using KUSTO Explorer and i need access also i need to have a msauser defined in the permission in the Database, other users/accounts dont work even the admin (funny)......
please check [this link ](https://stackoverflow.com/questions/58802770/azure-data-explorer-cluster-details-access-to-the-resource-is-forbidden)

I do not want to g to the Portal and run 
.add database IoTAnalyticsApplicationDB users ('msauser=myEmail@email.com') 'Test user (live.com)'
how can i do this using AZURE CLI?
it looks like that the CLI doesn;t support msauser but you can do this through the portal???? am i missing something????
thanks.

the error that i am getting is ....


az : Command group 'kusto database' is experimental and not covered by customer support. Please use with discretion.
At line:1 char:1
+ az kusto database remove-principal --cluster-name $AzureDataExplorer  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Command group '...ith discretion.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
(BadRequest) Database principal FQN is not valid. FQN pattern must be one of ( 'aaduser=...' / 'aadgroup=...', 'aadapp=...').

**Comment by yonzhan** [comment]
kusto

**Comment by orhasban** [comment]
We don't support managing msauser(s) at the moment through Kusto management API.
Currently it could be done only against the cluster itself (KQL command against the cluster as you mentioned -_.add database IoTAnalyticsApplicationDB users ('msauser=myEmail@email.com')_).
We'll add it to our backlog but don't expect it to be supported soon.

**Comment by asagarw** [comment]
I am facing the same error with data factory. When i use the below query in PowerShell it works fine but it fails when used in a @[AzureCLIV2](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureCLIV2/Readme.md) task  

az datafactory factory show --name xyz --resource-group rg --subscription sub --query identity.principalId --output tsv
![image](https://user-images.githubusercontent.com/20365086/89619456-d28b3100-d842-11ea-986c-31df45ffb173.png)

**Comment by navba-MSFT** [comment]
@sqldataside Apologies for the late reply. We are looking into this issue and we will provide an update on this once we have more details.

@ilayrn, @orhasban, @astauben Could you please provide an update on this ?Awaiting your reply.

**Comment by RakeshMohanMSFT** [comment]
Please use the new/updated command for the same [`az kusto database-principal-assignment create`](https://learn.microsoft.com/en-us/cli/azure/kusto/database-principal-assignment?view=azure-cli-latest#az-kusto-database-principal-assignment-create)
![image](https://user-images.githubusercontent.com/49954584/210967863-f475fc69-5ec8-4bd4-806f-7e1b25df1f70.png)
