### ISSUE TITLE
Cannot change Logic App state without providing definition

### ISSUE THREAD

**Issue by simonvane** [Azure/azure-cli-extensions#2123]
### Extension name (the extension in question)
logic

### Description of issue (in as much detail as possible)
I would like to change the state of my Logic App (disable it in this case) without changing the definition. I want to do this in an ADO release pipeline so that nothing can call it while the functions etc. it calls are updated.

I thought I would be able to do that with the following:
`az logic workflow update --resource-group <resource group name> --name <logic app name> --state Disabled`

But I receive the following error message:
`az logic workflow update: error: the following arguments are required: --definition`

**Comment by yonzhan** [comment]
Logic App
