### ISSUE TITLE
when running az aks create with aks-preview extension  get error:The request content was invalid and could not be deserialized: 'Could not find member 'template' on object of type 'DeploymentDefinition'. Path 'template', line 1, position 12.'. 

### ISSUE THREAD

**Issue by kshke** [Azure/azure-cli-extensions#2133]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
aks-preview
### Description of issue (in as much detail as possible)
-----
when running az extension add --name aks-preview --version 0.4.37, get following error:

The request content was invalid and could not be deserialized: 'Could not find member 'template' on object of type 'DeploymentDefinition'. Path 'template', line 1, position 12.'. 
 
    at Object.exports.exec (/home/lmackie/g/operations/src/provisionCloud/helpers/utils.ts:14:9)
    at Object.<anonymous> (/home/lmackie/g/operations/src/provisionCloud/helpers/processSteps.ts:124:7)
    at Generator.next (<anonymous>)
    at fulfilled (/home/lmackie/g/operations/src/provisionCloud/helpers/processSteps.ts:4:58)

**Comment by yonzhan** [comment]
aks

**Comment by kshke** [comment]
Azure CLI version 2.9.1

**Comment by kshke** [comment]
az aks create   --node-resource-group xxx  --resource-group xxx     --kubernetes-version 1.18.6     --name xxx    --load-balancer-sku basic     --enable-addons monitoring     --generate-ssh-keys

**Comment by TomGeske** [comment]
Why are you trying version 0.4.37 and not latest? does it work if you remove --version 0.4.37?

**Comment by kshke** [comment]
> Why are you trying version 0.4.37 and not latest? does it work if you remove --version 0.4.37?

@TomGeske Because the latest version seems has a bug that when I create basic sku load balancer, it will be set to standard. 

below is the output:
    },
    "loadBalancerSku": "Standard",
    "networkMode": null,
    "networkPlugin": "kubenet",
    "networkPolicy": null,
    "outboundType": "loadBalancer",
    "podCidr": "10.244.0.0/16",
    "serviceCidr": "10.0.0.0/16"
  },


I need to use old version of extension to create cluster with basic loadbalance..

**Comment by TomGeske** [comment]
Why do you require Basic LB?

If you want to use Basic LB you need to use  --vm-set-type AvailabilitySet. By default we use VMSS  --vm-set-type which requires Standard LB.
