### ISSUE TITLE
Does any documentation exist for the json file used in az ml dataset register?

### ISSUE THREAD

**Issue by sollozzo2** [Azure/azure-cli-extensions#2135]
I've been trying to register a dataset with the register command in the ml extension.
However I couldn't find much information on how to specify the type of each column in a schema for a tabular dataset through the json file.

"az ml dataset register --show-template" provides a template but isn't very clear.

In the AML portal there is a user interface for assigning each column a type (e.g. integer, decimal, date, etc.) but there is no specification for doing so through the CLI. I'd really like a doc or at least an intuitive template that shows how the schema is written in the json file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcb8c9fd-e2a3-6c50-628d-4f0a49c4ee1b
* Version Independent ID: a40172d3-61eb-b17e-c6cc-0df35d091411
* Content: [az ml dataset](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-ml/ml/dataset?view=azure-cli-latest#ext-azure-cli-ml-az-ml-dataset-register)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-ml/ml/dataset.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-ml/ml/dataset.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ml

**Comment by RakeshMohanMSFT** [comment]
Please reopen if you are still facing this issue
