### ISSUE TITLE
Does `az monitor log-analytics query` still exist?

### ISSUE THREAD

**Issue by andrebriggs** [Azure/azure-cli-extensions#2146]
My version of `az`: 
```console
$ az version
{
  "azure-cli": "2.10.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.10.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "azure-devops": "0.14.0"
  }
}
```

```console
$ az monitor log-analytics query
az monitor log-analytics: 'query' is not in the 'az monitor log-analytics' command group. See 'az monitor log-analytics --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0fd6a58-ac1a-fa45-8d96-579b4af36499
* Version Independent ID: 4098ca97-1b85-eb29-18e9-e6f0495fd030
* Content: [az monitor log-analytics](https://docs.microsoft.com/en-us/cli/azure/ext/log-analytics/monitor/log-analytics?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S175

**Comment by andrebriggs** [comment]
Never mind. This issue seems to be I didn't have the extension installed `az extension add --name log-analytics`. The reference doesn't seem to mention that

**Comment by MyronFanQiu** [comment]
@andrebriggs We're trying to solve such issue by auto-installing the extension and should be available later.
