### ISSUE TITLE
Microsoft.CostManagement/query service is expecting "dataSet.filter.dimensions" not "dataSet.filter.dimension"

### ISSUE THREAD

**Issue by GarrettGeorge** [Azure/azure-cli-extensions#2148]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

costmanagement

### Description of issue (in as much detail as possible)

The extension currently creates an HTTP POST body similar to

```
{
  dataSet: {
    filter: {
      dimension: { ... }
    }
}
```
however after looking at the requests that the Azure portal itself is making for the cost management queries, it's doing
```
{
  dataSet: {
    filter: {
      dimensions: { ... }
    }
}
```
here using the plural form instead of singular.

The biggest problem is the docs themselves for Microsoft.CostManagement/query say it's `dimension` and not `dimensions`.
https://docs.microsoft.com/en-us/rest/api/cost-management/query/usagebyexternalcloudprovidertype#queryfilter

This can be verified by changing the `QueryFilter` model in https://github.com/Azure/azure-cli-extensions/blob/96dcf6cc56499849715bc0fc5b2ba3b7328ac41d/src/costmanagement/azext_costmanagement/vendored_sdks/costmanagement/models/_models_py3.py#L1444 to use `dimensions` instead of `dimension`.

I edited the file myself using `dimensions` and the result from Microsoft is the same from the CLI as it is in the Azure Portal in browser.

-----

**Comment by yonzhan** [comment]
add to S175

**Comment by haroldrandom** [comment]
Is this blocking getting correct response from server or missing data?

**Comment by jochav** [comment]
Thank you for looking at this, we are working on updating the documentation.

**Comment by jochav** [comment]
ETA for documentation update is Jan 2021.

**Comment by mrlepat** [comment]
Documentation updated
