### ISSUE TITLE
I do not have az kusto data-connection in my azure CLI

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-cli-extensions#2150]
Using Az CLI v 2.10.1, `data-connection` is not an option for `az kusto`

~~~
C:\Users\Brandon\kusto> az kusto
az kusto: error: the following arguments are required: _subcommand
usage: az kusto [-h] {cluster,database} ...
C:\Users\Brandon\kusto> az --version
azure-cli                         2.10.1

command-modules-nspkg              2.0.3
core                              2.10.1
nspkg                              3.0.4
telemetry                          1.0.4
~~~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a519e7-8538-33ea-ef2a-9ef908076a78
* Version Independent ID: 5116ad82-155f-e281-fe0c-7a99b0d442e8
* Content: [az kusto data-connection](https://docs.microsoft.com/en-us/cli/azure/ext/kusto/kusto/data-connection?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/kusto/kusto/data-connection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/kusto/kusto/data-connection.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
kusto

**Comment by orhasban** [comment]
+@astauben to answer

**Comment by astauben** [comment]
Hi @brandonh-msft can you run 'az extension add -n kusto' and try again please?

**Comment by brandonh-msft** [comment]
that worked perfectly; There should be a `note` tag at the top of the commands which require this external, unsupported extension, IMO directing users they need to do this first.

**Comment by RakeshMohanMSFT** [comment]
The extension gets automatically installed now. Please upgrade to latest version of azure cli [2.43.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli)
![image](https://user-images.githubusercontent.com/49954584/210959688-55506379-7743-4d6c-a83d-03b09eca5406.png)
