### ISSUE TITLE
ip-group command does not exist in 'az network' 

### ISSUE THREAD

**Issue by RoweJHR** [Azure/azure-cli-extensions#2183]
Hi, 

Despite the listing in the article 'ip-group' is not available via the cli.  Any ideas when it will be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cacec59-2882-a074-136b-a4a1896e97c1
* Version Independent ID: 1c0fbb79-e36c-2e18-0293-67ebff1a53e7
* Content: [az network ip-group](https://docs.microsoft.com/en-us/cli/azure/ext/ip-group/network/ip-group?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/ip-group/network/ip-group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/ip-group/network/ip-group.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S175

**Comment by haroldrandom** [comment]
@RoweJHR Do you install ? ip-group is an extension of Azure CLI, have to install it first `az extension add -n ip-group`, then it will actually be working.

**Comment by haroldrandom** [comment]
Closed as long time inactive
