### ISSUE TITLE
eventgrid to azure function does not work with deployment slots

### ISSUE THREAD

**Issue by miqm** [Azure/azure-cli-extensions#2184]
### Extension name (the extension in question)
eventgrid v0.4.9

### Description of issue (in as much detail as possible)
I tried to create a subscription between eventgrid and azure function running on a slot. I put correct ARM Ids but It gave me the Invalid ARM Id error.
Also, on the portal I was able to select Production slot only.
Using webhook worked.

The command I was trying to use:
```
az eventgrid event-subscription create --name "$evtSubName" \
--source-resource-id "/subscriptions/$azSub/resourceGroups/$azRG/providers/Microsoft.EventGrid/topics/$evtTopic" \
--endpoint "/subscriptions/$azSub/resourceGroups/$azRG/providers/Microsoft.Web/sites/$funcApp/slots/$funcAppSlot/functions/$funcName" \
--endpoint-type azurefunction
```

```
>az extension list
[
  {
    "extensionType": "whl",
    "name": "eventgrid",
    "version": "0.4.9"
  }
]
```
-----

**Comment by yonzhan** [comment]
eventgrid

**Comment by jfggdl** [comment]
@miqm, thank you for creating this issue. The documentation on Event Grid does not mention anything about support for functions running in another slot besides production. We will get back to you with an answer. Would you please share with us the exact error message (" Invalid ARM Id error")? Thanks.

**Comment by jfggdl** [comment]
Event Grid does not have full support for functions deployment slots, unfortunately. I invite you to file this as a feature request in https://feedback.azure.com/forums/909934-azure-event-grid. The votes for each requested feature will inform our feature roadmap. Please let me know if you have any other questions.

**Comment by jfggdl** [comment]
@miqm, I am going to close this issue, but please request to be reopen if you have any other questions.

**Comment by wmmihaa** [comment]
As there is a select slot drop-down but only populated with "Production" this must be categorized as a bug. There has been an open request for this fix this bug for 18 months now (https://github.com/Azure/azure-cli-extensions/issues/2184). 

This should not be a feature request!

Please fix

**Comment by nomuramasanori** [comment]
It seems not to fix yet, does anyone have solution?

**Comment by szollosi-biotia** [comment]
I agree, this should be fixed, it is an important feature to be able to test event grid triggered functions, and there is a dropdown on the UI to choose deployment slot

**Comment by felixnext** [comment]
+1 on this. Testing in deployment slots is really essential!

**Comment by vany0114** [comment]
@jfggdl any update on this?

**Comment by C-Wal** [comment]
Five years later and this is still a problem.  Any update?

**Comment by vany0114** [comment]
+1 Yeah that's unbelievable
