### ISSUE TITLE
Adding -v flag to az ml endpoint realtime list causes error

### ISSUE THREAD

**Issue by plzm** [Azure/azure-cli-extensions#2185]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az ml

### Description of issue (in as much detail as possible)
Running az ml endpoint realtime list works. Adding the -v flag emits an error. See the identical outputs (obfuscated for privacy) below.

I have used -v with other az ml commands without error, output is expanded/verbose as expected. This seems to be a bug in this command specifically. Ran apt-get update/upgrade and confirmed with az --version that everything up to date.

1.
az ml endpoint realtime list -g $resource_group_name --workspace-name $ml_workspace_name

Output:
[
  {
    "computeType": "ACI",
    "name": "aciservice",
    "properties": {
      "hasHttps": "False",
      "hasInferenceSchema": "False"
    },
    "scoringUri": "http://OBFUSCATED.eastus.azurecontainer.io/score",
    "state": null,
    "tags": "",
    "updatedAt": "2020-08-12T21:17:25.303081+00:00"
  }
]

2. Add only -v with no other changes
az ml endpoint realtime list -g $resource_group_name --workspace-name $ml_workspace_name -v

Output:
{'Azure-cli-ml Version': '1.9.0', 'Error': AttributeError("'bool' object has no attribute 'lower'",)}

-----

**Comment by yonzhan** [comment]
ml

**Comment by RakeshMohanMSFT** [comment]
Please use V2 of ML https://learn.microsoft.com/en-us/cli/azure/ml?view=azure-cli-latest and also upgrade to latest version of auzre cli [2.43.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli)
