### ISSUE TITLE
Adding multiple rules in a network-rule collection not supported

### ISSUE THREAD

**Issue by RoweJHR** [Azure/azure-cli-extensions#2186]
Creating a network-rule collection with multiple rules does not work.  The command reports the collection already exists but there appears no way to add more than one rule via Az CLI:

usage error: --collection-name EXISTING_NAME | --collection-name NEW_NAME
|
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a90f7721-6e37-012e-a118-277d5c113f65
* Version Independent ID: c89a7d07-fc9d-748c-d562-2ec9f0295e15
* Content: [az network firewall network-rule](https://docs.microsoft.com/en-us/cli/azure/ext/azure-firewall/network/firewall/network-rule?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-firewall/network/firewall/network-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-firewall/network/firewall/network-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S175

**Comment by MyronFanQiu** [comment]
@RoweJHR Hi. We can do that. If you want to add the second rule into one collection, you just need to give the name of existing collection without priority. 
https://github.com/Azure/azure-cli-extensions/blob/59507b6db9d295417527f873ec9e2f847583d5e8/src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py#L211-L217

**Comment by MyronFanQiu** [comment]
@RoweJHR Hi. Is this issue solved?

**Comment by Gurpanthport** [comment]
Any update on this issue?
