### ISSUE TITLE
"az vm repair create" fails if subscription has policy to block IP addresses

### ISSUE THREAD

**Issue by rjmccallumbigl** [Azure/azure-cli-extensions#2207]
### Extension name (the extension in question)
Repair

### Description of issue (in as much detail as possible)
A few months ago, I recommended az vm repair to help create a rescue vm. When running az vm repair create from the subscription, the operation fails because they had a policy to block Public IP addresses. I propose an optional switch that gives the option to not give the repair VM a Public IP. This way, the operation will complete on such a subscription and the VM will have a Private IP. Then depending on the user's setup, they can still access the Repair VM via the private IP. https://docs.microsoft.com/en-us/cli/azure/ext/vm-repair/vm/repair?view=azure-cli-latest#ext-vm-repair-az-vm-repair-create

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0c5cd11-36e0-b233-4f0c-3d432a9925a1
* Version Independent ID: 99b6e064-4f75-9cce-b6e0-0ad1943552b9
* Content: [az vm repair](https://docs.microsoft.com/en-us/cli/azure/ext/vm-repair/vm/repair?view=azure-cli-latest#ext-vm-repair-az-vm-repair-create)
* Content Source: [latest/docs-ref-autogen/ext/vm-repair/vm/repair.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/vm-repair/vm/repair.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy, could you pls help to have a look?

**Comment by qwordy** [comment]
@swbae31 Can you have a look? Thanks

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
Assigning to Avi to look into the issue.

**Comment by avirishuv** [comment]
hi @rjmccallumbigl thanks for the recommendation, we are adding this to the feature backlog, however we do not have a timeframe to share right now for when this will be picked up.

**Comment by rjmccallumbigl** [comment]
That's awesome! Thanks team.

**Comment by rjmccallumbigl** [comment]
Posting idea here and closing thread: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/42952551-use-az-vm-repair-extension-to-create-repair-vm-w
