### ISSUE TITLE
`--spot_max_price can only include up to 5 decimal places`

### ISSUE THREAD

**Issue by keyz182** [Azure/azure-cli-extensions#2212]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
Running this command:
```pwsh
> az aks nodepool add -g Development --cluster-name DevelopmentKubernetes --name spotnodepool --priority Spot --eviction-policy Delete --spot-max-price 0.068 --enable-cluster-autoscaler --min-count 1 --max-count 3 --no-wait
The behavior of this command has been altered by the following extension: aks-preview
--spot_max_price can only include up to 5 decimal places
```
-----

1) I've tried setting `--spot-max-price` to 0.07, 0.0680, 0.06800, to no avail, same error. Am I misunderstanding what I'm supposed to put in, or is it an issue with the command?
2) The error has underscores rather than dashes in the command - trying the command with underscores gives an error `az: error: unrecognized arguments: --spot_max_price 0.068`

**Comment by yonzhan** [comment]
aks-preview
