### ISSUE TITLE
az hpc-cache create / debug flag turned on / sometimes 201 on initial call sometimes 200.

### ISSUE THREAD

**Issue by rebecca-makar** [Azure/azure-cli-extensions#2231]
This is some what a strange bug(?) unsure if we even want to call it this. **I am also unsure of the azcli is doing something in the background such as retrying commands quickly.**

I am testing az hpc-cache create and the storage target command as well. 

I am seeing http output because I have the -debug flag on. 
I brought it up to my team (hpc cache team) and we always return 201 on inital put, and then we are seeing a second put call 1 second after that would return the 200. (still in creating though)

When create caches or storage targets, with the new automation tests we have for AZ  CLI, we sometimes on an initial PUT request will receive a 200 instead of a 201.
Most times we do receive a 201 on the Put, but once or twice a day we are receiving a 200.
In our logs for the RP we send back the 201, then there is a second put call 1 or 2 seconds later that then we return 200, but in the tests we are NOT running a second put call.

On our side of the tests, one received a 200 and the other a 201. 

Cache Create initial PUT - Return 200:
pipeline results: [200](https://msazure.visualstudio.com/One/_build/results?buildId=33991523&view=logs&j=4a45f0e9-7fcb-51c0-695d-db68bce19b11&t=625bde4f-2881-579e-8bc2-662912230fa8&l=382)

Cache Create initial PUT - Return 201:
pipelines run: this is link to passing test, because it did received a 201. (test failure in this is example of ST create bc again expected 201 but got 200) [201-no error for create cache](https://msazure.visualstudio.com/One/_build/results?buildId=33992796&view=logs&j=4a45f0e9-7fcb-51c0-695d-db68bce19b11&t=625bde4f-2881-579e-8bc2-662912230fa8&l=27
)

**Comment by yonzhan** [comment]
add to S175

**Comment by zhoxing-ms** [comment]
Since the operation of creating HPC cache is a long running operation, by default, after request the asynchronous API and get the 201 status code, CLI will keep retrying until status 200 is obtained
If you want CLI to return the result without retrying after getting the 201 status code, you can add the parameter `--no-wait`.
Do you have any other questions?
