### ISSUE TITLE
doc: Failed to only upgrade node images of AKS

### ISSUE THREAD

**Issue by mainred** [Azure/azure-cli-extensions#2236]
[Enter feedback here]

`--node-image-only` under `az aks update` supports only vmss, which is not documented
```
➜  ~ az aks upgrade   --resource-group qinhao-upgrade --name upgrade-test  --node-image-only

The behavior of this command has been altered by the following extension: aks-preview
Kubernetes may be unavailable during cluster upgrades.
 Are you sure you want to perform this operation? (y/N): y
This node image upgrade operation will run across every node pool in the cluster and might take a while, do you wish to continue? (y/N): y
This cluster is not using VirtualMachineScaleSets. Node image upgrade only operation can only be applied on VirtualMachineScaleSets cluster.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea52f6a-7414-7aa2-3708-7b802f243a16
* Version Independent ID: cf003f17-b9f7-04d4-89c2-770273b40533
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/aks-preview/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/aks-preview/aks.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
AKS

**Comment by mlearned** [comment]
doc update is pushed and will be live today
#please-close
