### ISSUE TITLE
Incorrect text for sku-id on az account subscription commands doc page

### ISSUE THREAD

**Issue by michael-baraboo-datastax** [Azure/azure-cli-extensions#2239]
The --sku-id argument in the doc has a small typo.
```
--sku-id
The SKU ID of the Azure plan. Azure plan determines the pricing and service-level agreement of the subscription. Use 001 for Microsoft Azure Plan and 002 for Microsoft Azure Plan for DevTest.
```
001 and 002 should be 0001 and 0002.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 813c4506-a534-296b-cf67-5b91d51d33ae
* Version Independent ID: 19ed3baf-e3fd-42f6-1d6f-57fddc6fc284
* Content: [az account subscription](https://docs.microsoft.com/en-us/cli/azure/ext/account/account/subscription?view=azure-cli-latest#ext-account-az-account-subscription-create)
* Content Source: [latest/docs-ref-autogen/ext/account/account/subscription.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/account/account/subscription.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S175

**Comment by yungezz** [comment]
hi @arrownj could you pls fix the extension? thanks

**Comment by anuragdalmia** [comment]
Taking a look.

**Comment by anuragdalmia** [comment]
You are right. Thanks for catching the typo. We will fix it.

**Comment by yungezz** [comment]
hi @anuragdalmia is there any update on this? thanks

**Comment by arrownj** [comment]
The doc has been updated in https://github.com/MicrosoftDocs/azure-docs-cli/commit/c7d0fc1db1a7491b2b2097b55650d54242416065#diff-389258f97efd98c6085e047fe3f0cecfe2c3f9ea1a164eb15098cdaaef3bcbf0, and the typo no longer exists.
