### ISSUE TITLE
Please specify extension prerequisite

### ISSUE THREAD

**Issue by SP-SuperPoney** [Azure/azure-cli-extensions#2281]
Please specify that theses commands needs the following extention:
az extension add -n azure-firewall

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc2adff3-2bac-3c0a-e31a-5c5c40716a47
* Version Independent ID: b6a4a504-0f37-eca9-3987-1fcf7162a696
* Content: [az network firewall](https://docs.microsoft.com/en-us/cli/azure/ext/azure-firewall/network/firewall?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-firewall/network/firewall.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-firewall/network/firewall.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S175

**Comment by haroldrandom** [comment]
In which way you would like?

**Comment by SP-SuperPoney** [comment]
Sorry my remark was not clear enought.
Can you add a remark in the following documenation at:
https://docs.microsoft.com/en-us/cli/azure/ext/azure-firewall/network/firewall?view=azure-cli-latest

And precise that those cli commands requires the azure firewall extension:
az extension add -n azure-firewall

**Comment by yonzhan** [comment]
@dbradish-microsoft could you please help with this?

**Comment by dbradish-microsoft** [comment]
Hello, @SP-SuperPoney , 

We agree that this is much-needed information, and we have been working to add this information to all of our extension reference documents.

Kindly,

Delora

**Comment by jsntcy** [comment]
@SP-SuperPoney, thanks for your suggestions.
Beside the improvements on docs, now we have a new feature "auto-install" for extension, if you run a command that is in an extension which is not installed, CLI will prompt the following hint message and if you input 'y', that extension will be installed automatically, and the command will be executed successfully then. You can try this feature in latest version [2.12.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest).

![image](https://user-images.githubusercontent.com/16348853/94094028-21bc0e00-fe51-11ea-8bcd-d72c02c85cb0.png)
