### ISSUE TITLE
Typo exist

### ISSUE THREAD

**Issue by eltociear** [Azure/azure-cli-extensions#2286]
I found 2 typo in this document.
enviroment→environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2301603-c858-06c0-21fc-f89b82c4645d
* Version Independent ID: ba29613d-2ac0-8744-6d56-c70decb9ea15
* Content: [az ml computetarget](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-ml/ml/computetarget?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-ml/ml/computetarget.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-ml/ml/computetarget.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ml

**Comment by RakeshMohanMSFT** [comment]
This is fixed. https://docs.microsoft.com/en-us/cli/azure/ml(v1)/computetarget?view=azure-cli-latest
