### ISSUE TITLE
AKS tests failed in CI environment

### ISSUE THREAD

**Issue by arrownj** [Azure/azure-cli-extensions#2287]
In PR [Add acc sgx addon cli support ](https://github.com/Azure/azure-cli-extensions/pull/2253), 2 tests are marked as `live_only`.

Let's use this issue to trace it and make it go through in CI environment.

- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Description of issue (in as much detail as possible)

-----

**Comment by arrownj** [comment]
Hi @bowang-666 , could you please help with this issue ? Thanks

**Comment by bowang-666** [comment]
Issue fixed in https://github.com/Azure/azure-cli-extensions/pull/2681
https://github.com/Azure/azure-cli-extensions/pull/2681/files#diff-e52249226257440da9c5b786000c888c8ef692b06bc2bad03fb7807492a417c0
FYI @arrownj
