### ISSUE TITLE
aks-preview 0.4.62 -  The checksum of the extension does not match the expected value

### ISSUE THREAD

**Issue by TomGeske** [Azure/azure-cli-extensions#2302]
### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
I'm trying to run:

`az extension add --name aks-preview`

and I get:

```
Validating the extension /tmp/tmpckzu4u3z/aks_preview-0.4.62-py2.py3-none-any.whl
Invalid checksum for /tmp/tmpckzu4u3z/aks_preview-0.4.62-py2.py3-none-any.whl. Expected '52f8c14aae3f9aa76714bdf007976a04037cf1e7d18bf3e83f2cba2a5184ec43', computed '41538793759b3aae977c3c0e6263a271b20ea130467d89c0dee19877198f0703'.
cli.azure.cli.core.util : The checksum of the extension does not match the expected value. Use --debug for more information.
The checksum of the extension does not match the expected value. Use --debug for more information.
```

CLI version

```
{
  "azure-cli": "2.11.1",
  "azure-cli-core": "2.11.1",
  "azure-cli-telemetry": "1.0.5",
  "extensions": {
    "dev-spaces": "1.0.5"
  }
}
```

-----

cc:  @bowang-666

**Comment by yonzhan** [comment]
aks-preview

**Comment by bergerx** [comment]
previous similar issues:
* https://github.com/MicrosoftDocs/azure-docs/issues/37818
* https://github.com/MicrosoftDocs/azure-docs/issues/37826
* https://github.com/MicrosoftDocs/azure-docs/issues/46000

this seems to be regular transient issue.

**Comment by rajarshi-singh** [comment]
Thanks @bergerx . @jakaruna-MSFT Can you please look into why this error keeps happening every now so often? We might need to investigate permanent resolution.

**Comment by bowang-666** [comment]
I can reproduce locally. This seems widely impacted. Could you look into this?

**Comment by marwanad** [comment]
Does the following workaround work:

```
az extension add --source https://azurecliprod.blob.core.windows.net/cli-extensions/aks_preview-0.4.61-py2.py3-none-any.whl
```
?

**Comment by bowang-666** [comment]
> Does the following workaround work:
> 
> ```
> az extension add --source https://azurecliprod.blob.core.windows.net/cli-extensions/aks_preview-0.4.61-py2.py3-none-any.whl
> ```
> 
> ?

Thanks Marwan. This looks working as workaround.

**Comment by marlowp** [comment]
> Does the following workaround work:
> 
> ```
> az extension add --source https://azurecliprod.blob.core.windows.net/cli-extensions/aks_preview-0.4.61-py2.py3-none-any.whl
> ```
> 
> ?

If you're attempting this workaround using a Ubuntu 18 Azure-hosted agent then I've found you need to manually [update the azure-cli version](https://docs.microsoft.com/en-gb/cli/azure/install-azure-cli-apt?view=azure-cli-latest#update) to the latest version (currently the latest is 2.11.1, but the [hosted agent version](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) is 2.10.1) otherwise I got the following error even with the '--yes' flag set:

```python
Traceback (most recent call last):
   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
     cmd_result = self.invocation.execute(args)
   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 630, in execute
     self.resolve_confirmation(cmd, parsed_args)
   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 812, in resolve_confirmation
     if confirm and not cmd._user_confirmed(cmd.confirmation, parsed_args):  # pylint: disable=protected-access
   File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 153, in _user_confirmed
     return confirmation(command_args)
   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/extension/__init__.py", line 27, in ext_add_has_confirmed
     return bool(not command_args.get('source') or prompt_y_n('Are you sure you want to install this extension?'))
   File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 73, in prompt_y_n
     return _prompt_bool(msg, 'y', 'n', default=default, help_string=help_string)
   File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 81, in _prompt_bool
     verify_is_a_tty()
   File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 30, in verify_is_a_tty
     raise NoTTYException()
 knack.prompting.NoTTYException
```

**Comment by LostinCloud** [comment]
I am getting the same error when attempted workaround.

+ az extension add --source https://azurecliprod.blob.core.windows.net/cli-extensions/aks_preview-0.4.61-py2.py3-none-any.whl
The command failed with an unexpected error. Here is the traceback:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 630, in execute
    self.resolve_confirmation(cmd, parsed_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 812, in resolve_confirmation
    if confirm and not cmd._user_confirmed(cmd.confirmation, parsed_args):  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 153, in _user_confirmed
    return confirmation(command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/extension/__init__.py", line 27, in ext_add_has_confirmed
    return bool(not command_args.get('source') or prompt_y_n('Are you sure you want to install this extension?'))
  File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 73, in prompt_y_n
    return _prompt_bool(msg, 'y', 'n', default=default, help_string=help_string)
  File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 81, in _prompt_bool
    verify_is_a_tty()
  File "/opt/az/lib/python3.6/site-packages/knack/prompting.py", line 30, in verify_is_a_tty
    raise NoTTYException()
knack.prompting.NoTTYException

To open an issue, please run: 'az feedback'

----
+ az version
{
  "azure-cli": "2.11.1",
  "azure-cli-core": "2.11.1",
  "azure-cli-telemetry": "1.0.5",
  "extensions": {}
}

**Comment by arrownj** [comment]
Hi @TomGeske @LostinCloud @bergerx @marlowp @bowang-666 , please try to install the extension again. It should be OK now. Thanks

**Comment by bowang-666** [comment]
> Hi @TomGeske @LostinCloud @bergerx @marlowp @bowang-666 , please try to install the extension again. It should be OK now. Thanks

Thanks @arrownj this is now working for me.

**Comment by TomGeske** [comment]
LGTM

`az extension add -n aks-preview`
`The installed extension 'aks-preview' is in preview.`
```
{
  "azure-cli": "2.11.1",
  "azure-cli-core": "2.11.1",
  "azure-cli-telemetry": "1.0.5",
  "extensions": {
    "aks-preview": "0.4.62",
    "dev-spaces": "1.0.5"
  }
}
```
Thanks for fixing it quickly!

**Comment by rajarshi-singh** [comment]
I'm hoping we don't see this issue pop up again, it seems like a recurring one. Thanks for fixing.

**Comment by SimonHarrisonSH** [comment]
I've just got this again.
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
az extension add --name aks-preview
.
.
Unpacking azure-cli (2.45.0-1~bionic) ...
Setting up azure-cli (2.45.0-1~bionic) ...
ERROR: The checksum of the extension does not match the expected value. Use --debug for more information.

Is there not just a set of binaries that I can install which are known to be compatible?
