### ISSUE TITLE
aks-preview 0.4.62 - The checksum of the extension does not match the expected value

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli-extensions#2313]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
User failed to install aks-preview extension due to checksum failed. 

IcM : https://portal.microsofticm.com/imp/v3/incidents/details/203612575/home
Original issue: https://github.com/Azure/azure-cli-extensions/issues/2302

### Actions replay ###

[2020-09-03 09:31:00] Feature PR [ Add acc sgx addon cli support](https://github.com/Azure/azure-cli-extensions/pull/2253) merged.

[2020-09-03 12:58:00] Release PR [Release aks-preview 0.4.62 ](https://github.com/Azure/azure-cli-extensions/pull/2294) merged.

[2020-09-03 13:01:00] Index PR 1 [[Release] Update index.json for extension [ aks-preview ]](https://github.com/Azure/azure-cli-extensions/pull/2297) genereated.
> whl (checksum: 52f8c14aae3f9aa76714bdf007976a04037cf1e7d18bf3e83f2cba2a5184ec43) is uploaded to storage

[2020-09-03 14:12:00] Index PR 2[ [Release] Update index.json for extension [ aks-preview ]](https://github.com/Azure/azure-cli-extensions/pull/2298) manually trigged.
> whl (checksum: 41538793759b3aae977c3c0e6263a271b20ea130467d89c0dee19877198f070, override 52fc...) is uploaded to storage

![Jietu20200908-092651](https://user-images.githubusercontent.com/2927207/92423991-9f2b2180-f1b5-11ea-9787-d6162c0a95d8.jpg)

[2020-09-03 14:13:00] Index PR 2[ [Release] Update index.json for extension [ aks-preview ]](https://github.com/Azure/azure-cli-extensions/pull/2298) manually closed.
> checksum 41538793759b3aae977c3c0e6263a271b20ea130467d89c0dee19877198f070 abandoned in index.json

[2020-09-03 17:48:00] Index PR 1 [[Release] Update index.json for extension [ aks-preview ]](https://github.com/Azure/azure-cli-extensions/pull/2297) merged.
>checksum 52f8c14aae3f9aa76714bdf007976a04037cf1e7d18bf3e83f2cba2a5184ec43 merged into index.json, which cause the conflict.

### Summary ###
The root cause is that we have a manual trigged Index PR which override previous whl file but did not update the index.json file.

### How to improve ###

- Never override existing whl file while uploading to storage
pros: less changes in pipeline
cons: need to use a new version after Release PR gets merged.

- Change build whl program, if the commit is the same,  make sure the checksum is the same too.
pros: less changes in azdev

- Upload whl to an temp storage first, move to final storage after merge index.json PR
pros: do not need to use a new version
cons: more work to do, changed existing process

- Refactor current extension release process (create a new process just like current azure-cli ones, can manually trigger or timely trigger. 
pros: more natural. solve the checksum problem from the root.
cons: max work to do. The whole release process is changed.

-----

**Comment by arrownj** [comment]
We had an internal discussion and have a conclusion now. 

The root cause of this problem is that there are 2 index PRs for one extension at the same time. And there is no need to support 2 index PRs in our extension release process. So we will add a validation for this before uploading whl to storage. In this validation, we will check if there is already an open index PR, if yes, this pipeline will fail and notify Azure CLI team.

And if we actually want to use a new index PR, we can close the old one first and manually trigger a new one.

**Comment by yungezz** [comment]
thanks @arrownj, will you make the change?

**Comment by arrownj** [comment]
The extension release pipeline has been updated.
