### ISSUE TITLE
Show command does not show the scoped resource group name

### ISSUE THREAD

**Issue by mohamed-elbeltagy** [Azure/azure-cli-extensions#2316]
Hello,

I have service principals created using automatic method and scoped to specific resource groups.

When trying to use 'show' or 'list' commands to get service connection details, it always shows "resourceGroupName" empty.

Output example:

"data": {
    "appObjectId": "6a5c17f0-9954-4fbc-a4ff-7fd63a63c368",
    "azureSpnPermissions": "[{\"roleAssignmentId\":\"d632670e-33ce-4ef3-a118-998f608009c8\",\"resourceProvider\":\"Microsoft.RoleAssignment\",\"provisioned\":true}]",
    "azureSpnRoleAssignmentId": "ce589c8a-d0bb-4bce-8280-b85fd6c4bf6c",
    "creationMode": "Automatic",
    "environment": "AzureCloud",
    "managementGroupId": "",
    "managementGroupName": "",
    "mlWorkspaceLocation": "",
    "mlWorkspaceName": "",
    "oboAuthorization": "",
    "resourceGroupName": "",
    "resourceId": "",
    "scopeLevel": "Subscription",
    "spnObjectId": "949012df-62e6-4f07-90d8-cf35e68d7601",
    "subscriptionId": "9fc58495-92b3-41aa-ac00-9666f778357b",
    "subscriptionName": "SubscriptionName"
  }

Is it possible to show the scoped resource groups? or this is by design?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ecb62a2-f74c-a539-d3a8-c8fde7c2de06
* Version Independent ID: 5760936e-90a1-4129-6f6f-6dd4194bb73c
* Content: [az devops service-endpoint](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/service-endpoint?view=azure-cli-latest#ext-azure-devops-az-devops-service-endpoint-show)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
devops

**Comment by RakeshMohanMSFT** [comment]
Please reopen if you are still facing this issue.
