### ISSUE TITLE
az monitor app-insights (bug while using the preview in the cloud-shell)

### ISSUE THREAD

**Issue by amkuipers** [Azure/azure-cli-extensions#2317]
## Describe the bug

**Command Name**
`az monitor app-insights events show
Extension Name: application-insights. Version: 0.1.10.`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor app-insights events show --app {} -g {} --event {} --type {}`

## Environment Summary
```
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.11.1

Extensions:
application-insights 0.1.10
ai-examples 0.2.3

```

**Comment by yonzhan** [comment]
add to S176

**Comment by jsntcy** [comment]
@amkuipers, we can not reproduce the issue, please share more details.

You can also try `az extension update -n application-insights` to upgrade to latest version, then retry to see it's resolved. 
From the error you provided, it seems it's client error related to your token. Try logout and login again.

**Comment by jsntcy** [comment]
There is no response from customer more than two weeks, so close this issue.
