### ISSUE TITLE
List all branches of a repo

### ISSUE THREAD

**Issue by tehho** [Azure/azure-cli-extensions#2318]
Would like a command to list all active branches of a repo.

az repos show-branches or something

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82177ae5-9144-27f7-47c0-5fa076636a69
* Version Independent ID: f89f4b34-692e-1b3f-0314-33ef141243c2
* Content: [az repos](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/repos.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/repos.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tehho** [comment]
Found it az repos ref list

**Comment by Krivobarac** [comment]
@pradeepradyumna  Is it for repos or branches?
