### ISSUE TITLE
Error while adding Ingress Add-on

### ISSUE THREAD

**Issue by akurathimohan** [Azure/azure-cli-extensions#2320]
## Describe the bug

**Command Name**
`az aks enable-addons
Extension Name: aks-preview. Version: 0.4.62.`

**Errors:**
```
'IngressApplicationGateway'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 2468, in aks_enable_addons
    _add_ingress_appgw_addon_role_assignment(result, cmd)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 742, in _add_ingress_appgw_addon_role_assignment
    config = result.addon_profiles[CONST_INGRESS_APPGW_ADDON_NAME].config
KeyError: 'IngressApplicationGateway'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons -n {} -g {} -a {} --appgw-id {}`

## Environment Summary
```
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.11.1

Extensions:
aks-preview 0.4.62
ai-examples 0.2.3

```

**Comment by yonzhan** [comment]
aks

**Comment by wpx7** [comment]
+1

It then works after removing and then re-adding the add-on...

**Comment by VijayRod** [comment]
Issue does not occur in my environment with below versions. Does not occur in Cloud Shell too for me. 
please update azure-cli and aks-preview, and retry.

azure-cli                         2.12.1
aks-preview                       0.4.63

**Comment by adinaclaudia** [comment]
I get same error when i do `az aks create ... --enable-addons ingress-appgw  --appgw-name {} --appgw-subnet-prefix {}`
Versions used:
```
{
  "azure-cli": "2.14.2",
  "azure-cli-core": "2.14.2",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.66"
  }
}
```
Any way to work around this?

**Comment by arun-022** [comment]
I also have the same issue when i try to enable the addons 

Versions used:
{
  "azure-cli": "2.15.1",
  "azure-cli-core": "2.15.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.67"
  }
}

**Comment by adinaclaudia** [comment]
> I get same error when i do `az aks create ... --enable-addons ingress-appgw --appgw-name {} --appgw-subnet-prefix {}`
> Versions used:
> 
> ```
> {
>   "azure-cli": "2.14.2",
>   "azure-cli-core": "2.14.2",
>   "azure-cli-telemetry": "1.0.6",
>   "extensions": {
>     "aks-preview": "0.4.66"
>   }
> }
> ```
> 
> Any way to work around this?

I fixed this by adding `--enable-managed-identity`. It seems this is mandatory, although it is not clearly specified in the documentation: the documentation says it supports managed identities, not that it's required.

**Comment by miwithro** [comment]
@akshaysngupta can you comment here?

**Comment by akshaysngupta** [comment]
Can you try updating the extension using `az aks extension update -n aks-preview` and see if the problem persists ? Latest version is `.69`.

**Comment by navba-MSFT** [comment]
@akurathimohan Apologies for the late reply. Could you please let me know if you had a chance to try the above action plan ? This issue is open for quite sometime. Please let us know if you need any assistance on this. Awaiting your reply.
