### ISSUE TITLE
'app-insights' is not in the 'az monitor' command group

### ISSUE THREAD

**Issue by pachecolp** [Azure/azure-cli-extensions#2322]
Before using `az monitor app-insights` commands it is necessary to add the Application Insights extension to AZ CLI.
This should be mentioned somewhere for those that reach the page from a search engine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7f5f91-5e89-9082-8c70-6431f0025f37
* Version Independent ID: 298daf64-db32-8b64-9a45-2c4c5e189522
* Content: [az monitor](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S176

**Comment by jsntcy** [comment]
Now extension can be loaded automatically and you don't need install it manually.

![image](https://user-images.githubusercontent.com/16348853/127249983-df577d9b-6f4f-44fd-9ed8-900dda2f89f0.png)

**Comment by jsntcy** [comment]
duplicated with #2475
