### ISSUE TITLE
error when running: az datamodel create -n retailidm --model-directives ./retailidm.json

### ISSUE THREAD

**Issue by DONGZHUPENG** [Azure/azure-cli-extensions#2329]
## Describe the bug

**Command Name**
`az datamodel create
Extension Name: aidls. Version: 0.1.20200902.385.`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
...
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datamodel create -n {} --model-directives {} --subscription {} -g {} --synapse-workspace {} --verbose`

## Environment Summary
```
Linux-4.15.0-1093-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.11.1
azure-cli-iot-ext 0.8.9

Extensions:
aidls 0.1.20200902.385
azure-cli-iot-ext 0.8.9
ai-examples 0.2.3

```

**Comment by yungezz** [comment]
hi @DONGZHUPENG could you pls try run `az login` to workaround? this is a known issue in Cloudshell https://github.com/Azure/azure-cli/issues/11749

**Comment by maertendMSFT** [comment]
Known issue, please close as a dupe.
