### ISSUE TITLE
commands after az extension add -n xxx are not run in batch script on windows

### ISSUE THREAD

**Issue by qiaodalei** [Azure/azure-cli-extensions#2335]
### Description of issue (in as much detail as possible)

I tried to run a batch script on windows with ```az extension add --name alias``` in. However I found the script stopped at this command and other commands didn't run. Like this:

script in try.bat:
python test.py
az extension add --name alias
python test.py

When I run try.bat, the output is like this:
![image](https://user-images.githubusercontent.com/40512977/92708389-a9e9e000-f388-11ea-9bb4-575f07f248d3.png)

And I have checked for sure that ```python test.py``` didn't run for the second time.
I also tried with another extension and had the same problem. And this problem doesn't exist on Linux. 

Here is az version info:
![image](https://user-images.githubusercontent.com/40512977/92708547-c9810880-f388-11ea-8a2a-2ad3ba6dd260.png)

Is there anything I can do to run batch script successfully? Thanks

**Comment by fengzhou-msft** [comment]
Thanks for reporting the issue. We'll take a look.

**Comment by fengzhou-msft** [comment]
CMD has some [bizarre behavior](https://superuser.com/a/318041). You need to add call to each of the command to avoid termination after running the commad. So you should have the follwoing in try.bat:

> call python test.py
> call az extension add --name alias
> call python test.py
>

**Comment by fengzhou-msft** [comment]
Close as this issue is not caused by CLI commands.
