### ISSUE TITLE
some parameter explaination still are ambiguous 

### ISSUE THREAD

**Issue by andywangqt** [Azure/azure-cli-extensions#2347]
[Enter feedback here]
as to this command :
az network vpn-site update 
one parameter : --address-prefixes

this is the explanation from microsoft: 
--address-prefixes
Space-separated list of CIDR address prefixes.

this is the address of remote VPN site prefixes or local prefixes?

I suggest that you can draw a topology , every explaination is based on the topology IP. So it will be clear to reader

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bc92fbe-8731-dc15-c23e-5b58163ee03a
* Version Independent ID: 48314a31-ffc3-6896-38c2-aa3fa811c1af
* Content: [az network vpn-site](https://docs.microsoft.com/en-us/cli/azure/ext/virtual-wan/network/vpn-site?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/virtual-wan/network/vpn-site.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/virtual-wan/network/vpn-site.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S176

**Comment by haroldrandom** [comment]
@andywangqt Could you explain more plain about what you wish us to improve?

**Comment by haroldrandom** [comment]
Closed as inactive
