### ISSUE TITLE
Make test_static platform agnostic

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-extensions#235]
The PR template asks you to run test_static.sh, which can only be run on Linux. If you develop on Windows using CMD, you can't run the script (and just trying to hop into WSL to run it doesn't turn out well either).  Consider something like `azdev style` for the extensions repo.

**Comment by tjprescott** [comment]
@williexu this is incredibly annoying. Not only can you not run the shell scripts in CMD, but even when it runs in the CI it doesn't give you all the errors, so you end up re-running the CI multiple times to find the issues.

**Comment by williexu** [comment]
I'll take a look once I have some bandwidth available.

**Comment by tjprescott** [comment]
azdev now works on extensions and it is platform-agnostic, so this can be closed.
