### ISSUE TITLE
z ml datastore attach-blob```  command is throwing unrecognized arguments

### ISSUE THREAD

**Issue by sfilipi** [Azure/azure-cli-extensions#2360]
The  ```az ml datastore attach-blob```  command is throwing unrecognized arguments for: 
 --storage-account-subscription-id
--storage-account-resource-group

```
az : ERROR: az: error: unrecognized arguments: --storage-account-subscription-id XXXXXXX --storage-account-resource-group YYYYYYYYYY
At C:\scripts\run_experiment.ps1:75 char:2
+     az ml datastore attach-blob `
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az: erro...ommend-usea-dev:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {ml} ...
az : ERROR: az: error: unrecognized arguments: --storage-account-subscription-id XXXXXXX --storage-account-resource-group YYYYYYYYYYYY
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c99b13-9888-31ac-9e22-4bac0cb3956a
* Version Independent ID: 7aef098d-0f55-e080-cce4-91ad6265d974
* Content: [az ml datastore](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-ml/ml/datastore?view=azure-cli-latest#ext_azure_cli_ml_az_ml_datastore_attach_blob)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-ml/ml/datastore.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-ml/ml/datastore.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ml

**Comment by SturgeonMi** [comment]
Hi Senja,

The arguments should be like below. And you can find [document here.](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-ml/ml/datastore?view=azure-cli-latest#ext_azure_cli_ml_az_ml_datastore_attach_blob)
az ml datastore attach-blob --account-name
                            --container-name
                            --name
                            [--account-key]
                            [--endpoint]
                            [--grant-workspace-msi-access]
                            [--include-secret]
                            [--output-metadata-file]
                            [--path]
                            [--protocol]
                            [--resource-group]
                            [--sas-token]
                            [--storage-account-resource-group]
                            [--storage-account-subscription-id]
                            [--subscription-id]
                            [--workspace-name]

**Comment by SturgeonMi** [comment]
Are you still getting this error?

**Comment by v-strudm-msft** [comment]
Should you still have questions regarding this issue, please comment here and reopen it. We're closing it for now.
