### ISSUE TITLE
 ```az ml workspace create ```does not throw if unsupported argument ```-subscription-id``` is supplied

### ISSUE THREAD

**Issue by sfilipi** [Azure/azure-cli-extensions#2378]
Most az ml workspace, and the az ml commands in general have a -subscription or a -subscription-id argument, which is defines the subscription to operate on. 

The ```az ml workspace create``` does not have such argument and operates on the default subscription.  
1- This is inconsistent with the other commands, and needs to be stated in the docs.
2 - It also does not throw if such an argument is supplied, which can lead to confusion and require debugging. 
3- In general some of the ```az ml``` use ```-subscription-id``` as argument, and some others az extensions, like ```az storage account keys list``` uses ```-subscription```. It would be good to standardize across extensions. I think ```subscription-id``` is a more descriptive name.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f00d6d4-067d-e325-0605-5206a9c71473
* Version Independent ID: 3e63b88b-b258-ef46-a57a-21dce3d64c3e
* Content: [az ml workspace](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-ml/ml/workspace?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-ml/ml/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-ml/ml/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ml

**Comment by rastala** [comment]
Routing to MLOps area to look at the CLI consistency issues.

**Comment by paulshealy1** [comment]
Thanks for the feedback! This is for the v1 CLI. We'll be sure to address this in the v2 CLI: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli
