### ISSUE TITLE
The list script for windows or the lists script with certain description does not work.

### ISSUE THREAD

**Issue by diegodct** [Azure/azure-cli-extensions#2380]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0c5cd11-36e0-b233-4f0c-3d432a9925a1
* Version Independent ID: 99b6e064-4f75-9cce-b6e0-0ad1943552b9
* Content: [az vm repair](https://docs.microsoft.com/en-us/cli/azure/ext/vm-repair/vm/repair?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/vm-repair/vm/repair.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/vm-repair/vm/repair.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hello @swbae31  could you pls look at this issue about vm-repair? thanks

**Comment by swbae31** [comment]
For what script does the 'az vm repair list-script' not work? @diegodct ? I will be glad to look into it if you can explain the issue more in detail.

**Comment by qwordy** [comment]
> 
> 
> For what script does the 'az vm repair list-script' not work? @diegodct ? I will be glad to look into it if you can explain the issue more in detail.

@diegodct

**Comment by qwordy** [comment]
Close it since no reply.
