### ISSUE TITLE
add clarification.

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/azure-cli-extensions#2457]
[Enter feedback here]
--vnet-subnet-id

The ID of a subnet in an existing VNet into which to deploy the cluster.

can you clarify is the full URI for the subnet , not just the name of the subnet or the vnet alone, is the full path.

thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92444562-0540-adf6-3c3e-33b181bd10d4
* Version Independent ID: 3267c97e-819b-d945-fc28-2b75e35f2647
* Content: [az aks nodepool](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks/nodepool?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aks
