### ISSUE TITLE
How to download VPN client using az network p2s-vpn-gateway?

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/azure-cli-extensions#2465]
I did not see an option to download VPN client for a P2S VPN connection with virtual WAN.

Is there any CLI/PS command to download it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a6c1383-f4e8-ef8d-321f-d82a27a404a3
* Version Independent ID: 3969750e-97aa-78c0-575f-8966d624ed29
* Content: [az network](https://docs.microsoft.com/en-us/cli/azure/ext/virtual-wan/network?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/virtual-wan/network.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/virtual-wan/network.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S177

**Comment by haroldrandom** [comment]
It's a feature request.  We'll make a plan for it soon.

**Comment by haroldrandom** [comment]
@Mahesh-MSFT You could upgrade the extension and try `az network p2s-vpn-gateway vpn-client generate` to get the URL to download VPN client configuration
