### ISSUE TITLE
App Insights subgroup not available

### ISSUE THREAD

**Issue by a11smiles** [Azure/azure-cli-extensions#2475]
Using HomeBrew to install the CLI. The `app-insights` subgroup is not part of the `az monitor` subgroup.
I'm currently using:
```json
{
  "azure-cli": "2.12.1",
  "azure-cli-core": "2.12.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8baafade-06ad-e452-af14-7798fb17209f
* Version Independent ID: 45201db1-8a1c-f2f9-9771-32a179db6b73
* Content: [az monitor app-insights api-key](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights/api-key?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/api-key.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/api-key.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S177

**Comment by jsntcy** [comment]
@a11smiles Now extension can be loaded automatically and you don't need install it manually.

Please use `az upgrade` to upgrade to latest CLI version.

![image](https://user-images.githubusercontent.com/16348853/127250214-00e2649c-15dd-46a5-9bdd-2274c4b476cf.png)

**Comment by jsntcy** [comment]
There is no response from customer more than two weeks, so close this issue.
