### ISSUE TITLE
az monitor log-analytics query fails with PathNotFoundError

### ISSUE THREAD

**Issue by plzm** [Azure/azure-cli-extensions#2479]
## Describe the bug

az monitor log-analytics query fails with PathNotFoundError. The workspace exists; the query was working in Azure portal, Log Analytics, and was copy-pasted from there to bash.

cli.azure.cli.core.azclierror : ServiceError: code: PathNotFoundError - , The requested path does not exist
ServiceError: code: PathNotFoundError - , The requested path does not exist

**Command Name**
`az monitor log-analytics query
Extension Name: log-analytics. Version: 0.2.1.`

**Errors:**
```
ServiceError: code: PathNotFoundError - , The requested path does not exist
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az monitor log-analytics query --workspace {} --analytics-query {} -t {} --verbose --debug`

=====THIS is the full bash script (subscription ID and resource ID to query for excluded):
subscription_id="(excluded)"
location="eastus"
log_analytics_resource_group_name="(excluded)"
log_analytics_workspace_name="(excluded)"
resource_id="{resource ID to query for (excluded)}"

# Variables
workspace_resource_id="$(az monitor log-analytics workspace show --subscription "$subscription_id" -g "$log_analytics_resource_group_name" -n "$log_analytics_workspace_name" -o tsv --query 'id')"

query_text="AzureDiagnostics | where ResourceId == '$resource_id' | order by TimeGenerated desc | limit 1"

echo "Install Azure CLI Log Analytics extension"

az extension add --name log-analytics

echo "Query the workspace"

az monitor log-analytics query --workspace "$workspace_resource_id" --analytics-query "$query_text" -t "P3DT12H" --verbose --debug

=====

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.12.0 *
azure-cli-ml 1.9.0

Extensions:
azure-cli-ml 1.9.0
interactive 0.4.4
log-analytics 0.2.1

```

**Comment by yonzhan** [comment]
add to S177
