### ISSUE TITLE
image copy fails to create snapshot

### ISSUE THREAD

**Issue by niwsa** [Azure/azure-cli-extensions#248]
### Extension name (the extension in question)
image-copy-extension

### Description of issue (in as much detail as possible)
The image copy extension fails as its not able to locate the os disk when creating the snapshot.
```Getting os disk id of the source vm/image
Creating source snapshot
command failed: ['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'xxxx-yyyy-image-westus_os_disk_snapshot', '--resource-group', 'Operations', '--source', '/subscriptions/xxxxxxxx/resourceGroups/image-copy-rg/providers/Microsoft.Compute/snapshots/xxxx-yyyy-image_os_disk_snapshot-westus', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ERROR: Resource xxxx-yyyy-image_os_disk_snapshot-westus is not found.
```

The snapshot creation succeeds on --location flag which at the moment seems to be missing with the extension

-----

**Comment by niwsa** [comment]
The resource group happens to be in a different location.This is a non issue.

**Comment by viveks84** [comment]
There should be an option to use the existing resource group, it will be more beneficial. Not everyone will have create resource group permissions.

**Comment by tamirkamara** [comment]
@viveks84 you can have the extension use a resource group you named and if it already exists nothing will happen... check the help text.

**Comment by viveks84** [comment]
Yeah cli had existing resource group but didnt see the cli use that instead
it tried to create a new one
