### ISSUE TITLE
Typo exist in document.

### ISSUE THREAD

**Issue by eltociear** [Azure/azure-cli-extensions#2485]
2 line
enviroment -> environment

[Escreva aqui os seus comentários]

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: e2301603-c858-06c0-21fc-f89b82c4645d
* Version Independent ID: ba29613d-2ac0-8744-6d56-c70decb9ea15
* Content: [az ml computetarget](https://docs.microsoft.com/pt-pt/cli/azure/ext/azure-cli-ml/ml/computetarget?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-ml/ml/computetarget.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/azure-cli-ml/ml/computetarget.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by paulshealy1** [comment]
Thanks for the feedback! We'll address this in the next release.

**Comment by RakeshMohanMSFT** [comment]
This is fixed
