### ISSUE TITLE
Unable to create vhub connection when remote vnet is in different subscription

### ISSUE THREAD

**Issue by bq1756** [Azure/azure-cli-extensions#2487]
I have a Virtual WAN and associated Virtual Hub that span 2 subscriptions, e.g. Production and Non-Production subscriptions.  The Virtual Hub is hosted in the Production subscription.  I want to create VNET Connections to VNETs that are hosted in the Non-Production subscription.

I am following the current implementation of ```az network vhub connection create``` , documented at https://docs.microsoft.com/en-us/cli/azure/ext/virtual-wan/network/vhub/connection?view=azure-cli-latest.  According to the documentation, there is no way to specify "subscription".

Testing:
Test 1: az account set --subscription "Production"
I get an error message stating ```Remote Virtual Network 'foo' not found for hub VNET connection 'bar'```

Test 1: az account set --subscription "Non-Production"
I get an error message stating ```The Resource 'Microsoft.Network/virtualHubs/foo-vhub' under resource group 'bar-rg' was not found```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19fef5c5-b3a5-31af-ccab-580959df37bd
* Version Independent ID: a9a8cb89-574f-9266-af7d-eb1c9cfcf275
* Content: [az network vhub connection](https://docs.microsoft.com/en-us/cli/azure/ext/virtual-wan/network/vhub/connection?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/virtual-wan/network/vhub/connection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/virtual-wan/network/vhub/connection.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S177

**Comment by haroldrandom** [comment]
Does --remote-vnet work for your purpose?

**Comment by yonzhan** [comment]
@bq1756 any feedback?

**Comment by haroldrandom** [comment]
close as inactive
