### ISSUE TITLE
`az network firewall nat-rule list --output table` fails to list rules

### ISSUE THREAD

**Issue by kingces95** [Azure/azure-cli-extensions#2506]
I expect
```
az network firewall nat-rule list 
  --resource-group myResourceGroup 
  --firewall-name myFirewall 
  --collection-name myNatRuleCollection
```
to return a list of rules, but I actually get a "list" of collection names, eg
```
Name                 Priority    ProvisioningState    ResourceGroup
-------------------  ----------  -------------------  ---------------
myNatRuleCollection  200         Succeeded            myResourceGroup
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1232025d-31e4-0789-1dfb-78f59e7ae093
* Version Independent ID: e2f69d85-cd20-c868-e647-6b4316a2ef08
* Content: [az network firewall nat-rule](https://docs.microsoft.com/en-us/cli/azure/ext/azure-firewall/network/firewall/nat-rule?view=azure-cli-latest#ext_azure_firewall_az_network_firewall_nat_rule_list)
* Content Source: [latest/docs-ref-autogen/ext/azure-firewall/network/firewall/nat-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/azure-firewall/network/firewall/nat-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S177

**Comment by haroldrandom** [comment]
@kingces95 Are you convinced that you didn't provide the `--output table` argument?

Because I am a bit confused that in the PR title you mentioned `--output table` but in the PR body didn't.

**Comment by yonzhan** [comment]
@kingces95  any update?

**Comment by haroldrandom** [comment]
Closed as inactive.

If what you mean is to list more properties than current when displaying as a table. Feel free to reopen and I will change the PR title.
