### ISSUE TITLE
--max-surge does not exist.

### ISSUE THREAD

**Issue by n3rd253** [Azure/azure-cli-extensions#2511]
Hello Friends

Your documentation specifies a fancy flag --max-surge.  We would like to make use of this flag, however it doesn't seem to exist in the actual public offering

https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks/nodepool?view=azure-cli-latest#ext_aks_preview_az_aks_nodepool_update

<img width="1247" alt="Screen Shot 2020-10-12 at 4 12 50 PM" src="https://user-images.githubusercontent.com/20586952/95798294-68f62b80-0ca6-11eb-91af-08a043be5765.png">

For prosperity, all commands shown in the screenshot have also been attempted with -u for update-autoscaler

Thanks!

Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92444562-0540-adf6-3c3e-33b181bd10d4
* Version Independent ID: 3267c97e-819b-d945-fc28-2b75e35f2647
* Content: [az aks nodepool](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks/nodepool?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aks

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of azure cli and extension and retry the operation.
