### ISSUE TITLE
There are no examples for Linux customScript.

### ISSUE THREAD

**Issue by ManasaDevadas** [Azure/azure-cli-extensions#2513]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277bceda-f654-bb36-a443-b32d6216ea03
* Version Independent ID: 3a1cbaf3-efd8-2bc8-6cf6-5450213fe21a
* Content: [az connectedmachine machine-extension](https://docs.microsoft.com/en-us/cli/azure/ext/connectedmachine/connectedmachine/machine-extension?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/connectedmachine/connectedmachine/machine-extension.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/connectedmachine/connectedmachine/machine-extension.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ManasaDevadas** [comment]
az connectedmachine machine-extension create --machine-name "<machinename>" --extension-name "customScript" --location "eastus" --resource-group "myRG"  --settings '{"fileUris": ["<fileuri>"],"commandToExecute": "sh install.sh"}'
this command is failing with ValidationError: (HCRP400) ExtensionInsufficientBody.

**Comment by yonzhan** [comment]
connectedmachine
