### ISSUE TITLE
[Kusto] Allow *cluster* permissions to be set via CLI

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-cli-extensions#2560]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Kusto

### Description of issue (in as much detail as possible)
With the Kusto extension we can set _database_ permissions today (e.g. `az kusto database add-principal`), but these are only useful if a superset of those permissions also exist on the cluster. However, we can't set cluster permissions via CLI. This capability should be added.

**Comment by yonzhan** [comment]
Kusto

**Comment by orhasban** [comment]
@brandonh-msft Thanks for reaching out.

In order to add cluster level principals ( "AllDatabasesAdmin" / "AllDatabasesViewer" ) , you can use the following command:
`az kusto cluster-principal-assignment create `

Example:
```
az kusto cluster-principal-assignment create 
--cluster-name "kustoclusterrptest4" 
--principal-id "87654321-1234-1234-1234-123456789123" 
--principal-type "App" 
--role "AllDatabasesAdmin" 
--tenant-id "12345678-1234-1234-1234-123456789123" 
--principal-assignment-name "kustoprincipal1" 
--resource-group "kustorptest"
```

For more details, please run: 
`az kusto cluster-principal-assignment create -h `

**Comment by brandonh-msft** [comment]
Thanks, it wasn't clear to me if that was creating a principal (like a managed identity) for the cluster or a permission on it; I think the naming could be better....

**Comment by brandonh-msft** [comment]
Also I find it a bit cumbersome that for this permission I need to use PrincipalId and TenantId but for _database_ permission (`az kusto database add-principal`) I can simply use email address (much more affordable). Any chance we could look at adding a similar path for `az kusto cluster`?

**Comment by orhasban** [comment]
You can pass email address in principalId ? It should work

**Comment by brandonh-msft** [comment]
> Did you tried to pass email address in principalId ? It should work

@orhasban would I still require `tenantId`?

**Comment by orhasban** [comment]
`tenantId` is not mandatory field. If you don't specify it, we assume its the tenant id of the cluster.

**Comment by brandonh-msft** [comment]
excellent i'll give using email address as principal ID w/o any tenant ID a shot and see how it goes

**Comment by brandonh-msft** [comment]
all was successful - thanks!
