### ISSUE TITLE
[az webapp up] - Improve error message when duplicate name conflict exists

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-cli-extensions#257]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

It seems that there was already a `node-hello` in azure, but the error message was not entirely clear on this. Would be nice to have better failure messages

### Extension name (the extension in question)

`az webapp up`

### Description of issue (in as much detail as possible)

Run `az webapp up -n node-hello`

-----

### Error

```
▶az webapp up -n node-hello
Resource group 'appsvc_rg_Linux_CentralUS' already exists.
App service plan 'appsvc_asp_Linux_CentralUS' already exists.
Creating app 'node-hello' ....
Operation failed with status: 'Conflict'. Details: 409 Client Error: Conflict for url: https://management.azure.com/subscriptions/cfd12dd7-4872-4b83-8cd8-2ed6083047d7/resourceGroups/appsvc_rg_Linux_CentralUS/providers/Microsoft.Web/sites/node-hello?api-version=2016-08-01
```

@ahmedelnably @fiveisprime

**Comment by panchagnula** [comment]
we added a validation API in general & moved the command to core as well. if there is more specific feedback please file a new issue on azure-cli
