### ISSUE TITLE
Error the create databricks with --tags

### ISSUE THREAD

**Issue by Tomelin** [Azure/azure-cli-extensions#2578]
[Enter feedback here]

Hi,

I'm creating databricks using az cli and it works perfectly if I don't use the --tags option.
If I use the --tags parameter, it returns an error stating that the key has to be an integer, but I made several attempts with an integer, string and nothing worked.

 az databricks workspace create --resource-group myRSG --managed-resource-group myRSGMG --name nameOfDBR --location eastus2 --sku standard --private-subnet MySubnetPrivate --public-subnetmySubnetPublic  --tags test=test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6413355c-3c5f-bec4-8994-4dc9732bf627
* Version Independent ID: d07de386-0d04-68c3-3be6-9b1e28646e69
* Content: [az databricks workspace](https://docs.microsoft.com/en-us/cli/azure/ext/databricks/databricks/workspace?view=azure-cli-latest#ext_databricks_az_databricks_workspace_create)
* Content Source: [latest/docs-ref-autogen/ext/databricks/databricks/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/databricks/databricks/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to have a look?thanks

**Comment by fengzhou-msft** [comment]
The issue is fixed in the latest `databricks 0.7.1`, please update the extension and retry.
