### ISSUE TITLE
[Feature Request] Databricks create new cluster/obtain cluster Id of existing cluster

### ISSUE THREAD

**Issue by michaelhambe** [Azure/azure-cli-extensions#2588]
Is it possible to create a new cluster or obtain the cluster ID of an existing cluster using the az cli?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25bc2eac-683a-3e2f-0bfb-e6f204d27482
* Version Independent ID: 52493963-9247-59d6-1f1f-359bdfaa9da4
* Content: [az databricks](https://docs.microsoft.com/en-us/cli/azure/ext/databricks/databricks?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/databricks/databricks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/databricks/databricks.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
databricks

**Comment by michaelhambe** [comment]
Sorry, yes - a databricks cluster

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to check: creating new cluster is supported right?

**Comment by fengzhou-msft** [comment]
@michaelhambe Azure CLI only supports workspace management operations for now. You may use the [databricks-cli](https://docs.microsoft.com/en-us/azure/databricks/scenarios/databricks-cli-from-azure-cloud-shell) to manage clusters.
