### ISSUE TITLE
Azure Blueprint Artifact Update

### ISSUE THREAD

**Issue by bashscr** [Azure/azure-cli-extensions#2594]
Hi,

Going through the Azure CLI for using the Blueprint module, I see that you can add a --depends-on to a specific artifact. However, the CLI doesn't seem to support removing this property or setting it to be empty: []. When you try to set the artifact's "dependsOn" property to empty or "", it gives an error when trying to publish the new blueprint. The only way to fix this, that I have found so far, is by exporting the entire Blueprint with artifacts using Powershell and removing the "dependsOn" property manually inside of the artifact file. Then publishing a new version works as expected.

Is there any documentation to direct me in the right direction? I can't seem to find anything, and I would prefer to use the Azure CLI if possible rather than having to use both. Thank you!

V/r

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47abba92-7835-67eb-8d1d-4c6a812ddd6d
* Version Independent ID: de3d0485-5660-44d7-8c80-7f5843a66fde
* Content: [az blueprint artifact template](https://docs.microsoft.com/en-us/cli/azure/ext/blueprint/blueprint/artifact/template?view=azure-cli-latest#ext_blueprint_az_blueprint_artifact_template_update)
* Content Source: [latest/docs-ref-autogen/ext/blueprint/blueprint/artifact/template.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/blueprint/blueprint/artifact/template.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to look at the issue? thanks

**Comment by bashscr** [comment]
Hi, I just wanted to check back in @yungezz @fengzhou-msft with both of you. I see a new issue has been created and awaiting a merge. I'm glad to see the progress here. Additionally, I would like to inquire about being able to export the blueprint and artifacts from the Azure CLI like you can with `Export-AzBlueprintWithArtifact`. Is there any plans for this? We are trying to keep consistency and use the Azure CLI as much as possible, and would prefer not to rely on having to install PowerShell modules for other users if we can do everything through the Azure CLI. Thanks.

**Comment by yungezz** [comment]
thanks for the feedback @bashscr . Linked PR will merged soon after reviewing finished. To export the blueprint and artifacts, do you mind to create a new issue to track the request so that we can planning it accordingly? thanks.

**Comment by bashscr** [comment]
> 
> 
> thanks for the feedback @bashscr . Linked PR will merged soon after reviewing finished. To export the blueprint and artifacts, do you mind to create a new issue to track the request so that we can planning it accordingly? thanks.

Sure thing, and thank you @yungezz I just made a new issue here: [Export Blueprints](https://github.com/Azure/azure-cli-extensions/issues/2723)

**Comment by fengzhou-msft** [comment]
@bashscr blueprint 0.2.1 is released. Now you should be able to remove the dependency with `--depends-on` appending no values in update commands.

**Comment by bashscr** [comment]
Can confirm everything is working from my end, thanks a lot! @fengzhou-msft
