### ISSUE TITLE
Is it possible to query Log Analytics via the az cli with a saved query?

### ISSUE THREAD

**Issue by GitMje** [Azure/azure-cli-extensions#2596]
I can’t tell from the documentation, is it possible to run a saved Log Analytics Query from this CLI command?  

If not, a useful enhancement would be to enable the use a saved query in addition to the ability to execute queries in-line.  The queries get long and cumbersome to maintain outside of Log Analytics.

If it is, however, possible to run a saved query, would you mind updating the documentation here?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0fd6a58-ac1a-fa45-8d96-579b4af36499
* Version Independent ID: 4098ca97-1b85-eb29-18e9-e6f0495fd030
* Content: [az monitor log-analytics](https://docs.microsoft.com/en-us/cli/azure/ext/log-analytics/monitor/log-analytics?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S179

**Comment by kairu-ms** [comment]
Hi @GitMje, do you mean to read the saved query from a file?

**Comment by GitMje** [comment]
@kairu-ms I was hoping to use a saved query like one from the `saved queries` or `solutions queries`.  This would be similar to how azure devops can run team queries via the API.  Rather than having to hard code a query into the az cli command/scripts.  

Please see image below:
<img width="838" alt="001974-" src="https://user-images.githubusercontent.com/8420128/103233150-53d68380-490a-11eb-81a9-99c8547590df.png">

**Comment by kairu-ms** [comment]
@GitMje I got it. It's a very good question. Saved query is supported by command group 
```bash
az monitor log-analytics workspace saved-search -h
``` 
You can fetch the query string like this command
```bash
QUERY = $(az monitor log-analytics workspace saved-search show -g resource-group --workspace-name workspacename --name query-name --query query)
```
However you can not use the $QUERY like this
```bash
az monitor log-analytics query --workspace workspace-custom-id --analytics-query $QUERY
```
Because --analytics-query cannot correctly parse a query with "\n" and "\t" now. 

We will fix it in next release.

**Comment by zioalex** [comment]
Hi, the above command it isn't supported anymore. Is there any other way to run a simple query, not a saved one, from the CLI?
