### ISSUE TITLE
[webapp up] when updating, show success message and version in output

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-cli-extensions#260]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az webapp up

### Description of issue (in as much detail as possible)

When I updated there was no console output. I wasnt expecting to see "Updated successfully to version x.y.z". Can we do that?

Output of current extension
```
▶az webapp up -n papa-node-hello-003
Resource group 'appsvc_rg_Linux_CentralUS' already exists.
App service plan 'appsvc_asp_Linux_CentralUS' already exists.
Creating app 'papa-node-hello-003' ....
Webapp creation complete
Updating app settings to enable build after deployment
Creating zip with contents of dir /Users/papa/_git/node-hello ...
Preparing to deploy and build contents to app.
Fetching changes.
Fetching changes.
All done.
{
  "app_url": "https://papa-node-hello-003.azurewebsites.net",
  "location": "Central US",
  "name": "papa-node-hello-003",
  "os": "Linux",
  "resourcegroup": "appsvc_rg_Linux_CentralUS ",
  "serverfarm": "appsvc_asp_Linux_CentralUS",
  "sku": "BASIC",
  "src_path": "/Users/papa/_git/node-hello ",
  "version_detected": "0.0",
  "version_to_create": "node|8.9"
}

```

**Comment by panchagnula** [comment]
we made a few changes in this space & moved the command to core - please file new issue on azure-cli if there is more feedback. Thank you.
