### ISSUE TITLE
The parameter for --administration-members is incorrectly stated as optional 

### ISSUE THREAD

**Issue by DaveRuijter** [Azure/azure-cli-extensions#2613]
For the function 'az powerbi embedded-capacity create', the parameter for --administration-members is incorrectly stated as optional.
If you leave this parameter out, it will give this error:
**BadRequestError: At least one capacity administrator is required**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edf4a4a9-8ff1-c276-3e51-d5e83c180879
* Version Independent ID: de63a28e-4d16-2270-595f-1a67f5e682bd
* Content: [az powerbi embedded-capacity](https://docs.microsoft.com/en-us/cli/azure/ext/powerbidedicated/powerbi/embedded-capacity?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/powerbidedicated/powerbi/embedded-capacity.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/powerbidedicated/powerbi/embedded-capacity.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
powerbi
