### ISSUE TITLE
update to @autorest/python 5.x for vmware

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli-extensions#2630]
### Extension name (the extension in question)
vmware

### Description of issue (in as much detail as possible)
The autorest python version needs to be updated. It is currently using [3.0.62](https://www.npmjs.com/package/@microsoft.azure/autorest.python/v/3.0.62), but it has a problem creating empty json Azure/autorest.python#653.  Newer versions like [5.4.0](https://www.npmjs.com/package/@autorest/python/v/5.4.0) do not have that problem. A workaround was put in place to Swagger API spec, but that workaround causes problems with Swagger KPI correctness. The workaround Swagger API spec will be removed next week in the 2020-03-20 API when https://github.com/Azure/azure-rest-api-specs/pull/11486 is merged.

To be clear, the existing generated code that is committed will continue to work. Using autorest.python 3.x with the updated spec and new AVS specs will not work due to Azure/autorest.python#653 bug.

**Comment by yonzhan** [comment]
vmware

**Comment by yonzhan** [comment]
@jsntcy for awareness.
