### ISSUE TITLE
Service Principal fails to create subscription using az cli

### ISSUE THREAD

**Issue by aniesz** [Azure/azure-cli-extensions#2656]
I used the description from:
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription?tabs=rest-getEnrollments%2Cazure-cli-EA%2Crest-getBillingAccounts%2Crest-getBillingProfiles%2Cazure-cli-MCA%2Crest-getBillingAccount-MPA%2Crest-getCustomers%2Crest-getIndirectResellers%2Crest-MPA

to create a "Subscription under a specific enrollment account" with a ServicePrincipal, through the az CLI command:

az account alias create --name "myAlias" --billing-scope "/providers/Microsoft.Billing/enrollmentAccounts/........-....-....-....-............" --display-name "my Subscription" --workload "DevTest"

This ends up with the error from below:

## Describe the bug

**Command Name**
`az account alias create
Extension Name: account. Version: 0.2.1.`

**Errors:**
```
cannot import name 'ARMHttpLoggingPolicy'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azext_account/vendored_sdks/subscription/_subscription_client.py, ln 20, in <module>
    from ._configuration import SubscriptionClientConfiguration
azext_account/vendored_sdks/subscription/_configuration.py, ln 13, in <module>
    from azure.mgmt.core.policies import ARMHttpLoggingPolicy
ImportError: cannot import name 'ARMHttpLoggingPolicy'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- login with a Service Principal; a Subscription does not exist yet
- `az account alias create --name {} --billing-scope {} --display-name {} --workload {}`

## Environment Summary
```
Linux-3.10.0-1127.el7.x86_64-x86_64-with-redhat-7.8-Maipo
Python 3.6.8
Installer: RPM

azure-cli 2.10.1 *

Extensions:
account 0.2.1
alias 0.5.2

```

**Comment by yonzhan** [comment]
add to S179

**Comment by yungezz** [comment]
reassign to @fengzhou-msft , this is account extension.

**Comment by fengzhou-msft** [comment]
@aniesz can you update to the latest version of Azure CLI? It looks like that the `account` extension relies on a newer version of `azure-mgmt-core`.

**Comment by aniesz** [comment]
Thank you @fengzhou-msft , this solved the issue.
I should have updated to the latest az CLI version before opening the issue.
