### ISSUE TITLE
az network firewall network-rule create not working

### ISSUE THREAD

**Issue by yckwan** [Azure/azure-cli-extensions#2673]
Command stuck
![image](https://user-images.githubusercontent.com/52000447/99203551-e35a2400-27ed-11eb-88c2-a499df60c7e7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a90f7721-6e37-012e-a118-277d5c113f65
* Version Independent ID: c89a7d07-fc9d-748c-d562-2ec9f0295e15
* Content: [az network firewall network-rule](https://docs.microsoft.com/en-us/cli/azure/ext/azure-firewall/network/firewall/network-rule?view=azure-cli-latest#ext_azure_firewall_az_network_firewall_network_rule_create)
* Content Source: [latest/docs-ref-autogen/ext/azure-firewall/network/firewall/network-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/azure-firewall/network/firewall/network-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yckwan** [comment]
az : Command arguments: ['network', 'firewall', 'network-rule', 'create', '--collection-name', 'DEV-DMS', '--destination-ports', '80, 443, 8080', 
'--firewall-name', 'SEA-SHARED-FE-AF', '--name', 'web', '--protocols', 'TCP, UDP, ICMP, Any', '--resource-group', 'SEA-SHARED-NETWORK-RG', '--debug']
At C:\Portable\Github\FirewallRules\Execute.ps1:24 char:1
+ az network firewall network-rule create --collection-name $RuleCollec ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Command argumen...RG', '--debug']:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x02E9D978>, <function OutputProducer.on_global_arguments at 
0x02F2CDF8>, <function CLIQuery.on_global_arguments at 0x02F50DF8>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'network': ['azure.cli.command_modules.natgateway', 'azure.cli.command_modules.network', 
'azure.cli.command_modules.privatedns']
Loading command modules:
Name                  Load Time    Groups  Commands
natgateway                0.004         3         6
network                   0.032       120       550
privatedns                0.007        14        66
Total (3)                 0.043       137       622
Loaded 135 groups, 622 commands.
Could not find a match in the command or command group table for 'network firewall network-rule create'. The index may be outdated.
Loading all modules and extensions
Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 
'botservice', 'cdn', 'cloud', 'cognitiveservices', 'config', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 
'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 
'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 
'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
Loading command modules:
Name                  Load Time    Groups  Commands
acr                       0.008        25       103
acs                       0.013         7        48
advisor                   0.003         3         6
ams                       0.006        19        86
apim                      0.005         9        48
appconfig                 0.004         7        33
appservice                0.276        61       213
aro                       0.010         1         7
backup                    0.005        13        49
batch                     0.032        31        90
batchai                   0.006        10        32
billing                   0.003         4         6
botservice                0.005        12        42
cdn                       0.005        17        62
cloud                     0.002         1         7
cognitiveservices         0.003         5        17
config                    0.002         2         7
configure                 0.002         3         9
consumption               0.004         8         9
container                 0.004         1        11
cosmosdb                  0.012        32       123
deploymentmanager         0.004         7        30
dla                       0.006        23        62
dls                       0.006         7        41
dms                       0.004         3        21
eventgrid                 0.006        18        61
eventhubs                 0.007        14        51
extension                 0.003         1         7
feedback                  0.002         1         1
find                      0.002         1         1
hdinsight                 0.004         7        36
interactive               0.002         1         1
iot                       0.005        15        68
iotcentral                0.003         2         5
keyvault                  0.012        19       112
kusto                     0.004         3        14
lab                       0.004        11        34
managedservices           0.003         3         8
maps                      0.003         3         7
monitor                   0.010        30       130
natgateway                0.000         3         6
netappfiles               0.004         8        31
network                   0.024       120       550
policyinsights            0.004         6        12
privatedns                0.003        14        66
profile                   0.003         2         9
rdbms                     0.011        42       177
redis                     0.003         4        24
relay                     0.005        10        37
reservations              0.003         5        12
resource                  0.010        34       158
role                      0.020        17        61
search                    0.005         4        10
security                  0.007        28        67
servicebus                0.007        17        64
servicefabric             0.004        21        51
signalr                   0.003         5        16
sql                       0.009        36       149
sqlvm                     0.004         4        17
storage                   0.049        51       229
synapse                   0.007        13        45
util                      0.002         1         3
vm                        0.016        43       218
Total (63)                0.707       928      3710
Loaded 918 groups, 3710 commands.
Updated command index in 0.005 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x031D9C48>]
az_command_data_logger : command args: network {} {} {} --collection-name {} --destination-ports {} --firewall-name {} --name {} --protocols {} 
--resource-group {} --debug
metadata file logging enabled - writing logs to 'C:\Users\KwanYeowChyuan\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x032EA4F8>, <function 
register_global_query_examples_argument.<locals>.register_query_examples at 0x032EAC00>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x032EAC48>, <function 
register_cache_arguments.<locals>.add_cache_arguments at 0x032EACD8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x044EE108>]

**Comment by yonzhan** [comment]
network

**Comment by yckwan** [comment]
az extension add -n azure-firewall
Run this to resolve.
