### ISSUE TITLE
Add information about values for 'nfs3-usage-model'

### ISSUE THREAD

**Issue by ekpgh** [Azure/azure-cli-extensions#2695]
There's a required usage model option, but no information about what the options are. 

> --nfs3-usage-model  [Required] : Identifies the primary usage model to be used for this Storage Target.

We need to tell users two things
1) what strings can be used
2) what the strings mean so they can choose the correct one (Descriptions are here - https://docs.microsoft.com/en-us/azure/hpc-cache/hpc-cache-add-storage?tabs=azure-cli#choose-a-usage-model - but the names in the portal are probably different from the names used in the CLI)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c13670-0f8e-087c-95fa-60372ba2e9aa
* Version Independent ID: da003115-724d-2e62-c6d7-06006d05952b
* Content: [az hpc-cache nfs-storage-target](https://docs.microsoft.com/en-us/cli/azure/ext/hpc-cache/hpc-cache/nfs-storage-target?view=azure-cli-latest#ext_hpc_cache_az_hpc_cache_nfs_storage_target_add)
* Content Source: [latest/docs-ref-autogen/ext/hpc-cache/hpc-cache/nfs-storage-target.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/hpc-cache/hpc-cache/nfs-storage-target.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
hpc cache

**Comment by ekpgh** [comment]
Is this done? I see that there's an hpc-cache usage-model list command in the AZ CLI now.
