### ISSUE TITLE
image-copy invalid for some regions

### ISSUE THREAD

**Issue by jfred147** [Azure/azure-cli-extensions#2699]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
image-copy

### Description of issue (in as much detail as possible)
Some locations appear to be invalid inputs as target locations. For example, running --target-location brazilsoutheast, gives

output: BadRequestError: The provided location 'brazilsoutheast' is not available for resource group. List of available regions is 'centralus,eastasia,southeastasia,eastus,eastus2,westus,westus2,northcentralus,southcentralus,westcentralus,northeurope,westeurope,japaneast,japanwest,brazilsouth,australiasoutheast,australiaeast,westindia,southindia,centralindia,canadacentral,canadaeast,uksouth,ukwest,koreacentral,koreasouth,francecentral,southafricanorth,uaenorth,australiacentral,switzerlandnorth,germanywestcentral,norwayeast,australiacentral2'. 

#### However, Azure's[ website ](https://azure.microsoft.com/en-us/global-infrastructure/services/?products=managed-disks,storage,resource-mover,azure-automanage,mysql&regions=all)says that disk storage / managed disks are allowed in brazilsoutheast, so I am wondering if this is caused by a part of the extension which has yet to be updated. 
-----

**Comment by yungezz** [comment]
hi @qwordy could you pls help to have a look? thanks

**Comment by qwordy** [comment]
@jfred147 Can you add "--debug" to command and attach output here? I'll check which step fails.
