### ISSUE TITLE
Export Azure Blueprint with Artifacts

### ISSUE THREAD

**Issue by bashscr** [Azure/azure-cli-extensions#2723]
Hi @yungezz,

I am creating a separate issue for easier tracking. I see a new issue has been created and awaiting a merge. I would like to inquire about being able to export the blueprint and artifacts from the Azure CLI like you can with Export-AzBlueprintWithArtifact. We are trying to keep consistency and use the Azure CLI as much as possible, and would prefer not to rely on having to install PowerShell modules for other users if we can do everything through the Azure CLI. Thanks!

V/r

**Comment by yungezz** [comment]
thanks for the request. will plan accordingly.

**Comment by bashscr** [comment]
Thanks for the swift response @yungezz - have a great, safe holiday!

**Comment by yungezz** [comment]
hi @08nholloway could you pls help on this? thanks

**Comment by 08nholloway** [comment]
@yungezz yes I can

**Comment by yungezz** [comment]
hi @08nholloway what's status of the issue? thanks.

**Comment by 08nholloway** [comment]
@yungezz nearly finished. One last thing to finish in the scenario test, should have PR submitted by tonight
