### ISSUE TITLE
aks-preview always requires a SP even if you want to use managed identities

### ISSUE THREAD

**Issue by jloaiza** [Azure/azure-cli-extensions#2729]
### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
The extension requires AAD permissions to create a service principal even when you want to use a managed identity.
AKS managed-identity creation procedure differs from the extension to the general availability command.

Here is the line that **always** checks for the service principal, no matter if it is a managed identity: 
https://github.com/Azure/azure-cli-extensions/blob/a05d404fce609fb3d0580949c7b8edcd5cd73fa1/src/aks-preview/azext_aks_preview/custom.py#L990

You can see that line have a condition in the regular CLI:
https://github.com/Azure/azure-cli/blob/6e6731455a79dc41b973adb9742ff3a8b5391b73/src/azure-cli/azure/cli/command_modules/acs/custom.py#L1843

**Comment by yonzhan** [comment]
aks-preview

**Comment by RakeshMohanMSFT** [comment]
This is working as expected. Please reopen if you are still facing issue
![image](https://user-images.githubusercontent.com/49954584/211041988-182d19b7-2486-41ab-a8f6-11c448cdc922.png)
