### ISSUE TITLE
How to send binary data with "az iot device c2d-message"?

### ISSUE THREAD

**Issue by hitochan777** [Azure/azure-cli-extensions#2734]
Can I send binary data with `az iot device c2d-message`, that is represented with HEX like `0x86 0x54 0x32`?
I converted a string to another with backslash escapes interpreted and then feed it to `az iot device c2d-message` command.
But I got UnicodeEncodeError as shown below. Will it work if I specify proper content encoding?

```console
$ CMD = "\x86\x54\x32"
$ OUTPUT="$(echo -e $CMD)"
$ az iot device c2d-message send --device-id $DEVICE_ID -n $NAME --data $OUTPUT
...
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc86' in position 0: surrogates not allowed
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e29f7349-f5b6-06f7-ec43-8fe07f1f0e32
* Version Independent ID: 734eca1d-555d-da8f-9763-a6a61459ab18
* Content: [az iot device c2d-message](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/device/c2d-message?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/device/c2d-message.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/device/c2d-message.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
iot

**Comment by hitochan777** [comment]
I think this issue is more of an enhancement request in `az iot` command and it is not related to documentation.
So I will close this issue and instead open new issue in [iot cli extension repository](https://github.com/Azure/azure-iot-cli-extension).
