### ISSUE TITLE
Incorrect examples

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-extensions#276]
Ported from:
https://github.com/Azure/azure-cli/issues/7187

### Extension name (the extension in question)
management-groups

### Description of issue (in as much detail as possible)
The examples use the following:
az managementgroups group update --group-name GroupName --display
This does not exist in the Azure CLI, it should be "az management-group"

-----

cc/ @Always-Wright

**Comment by MyronFanQiu** [comment]
close it since it has been removed.
