### ISSUE TITLE
how to change between production and sandbox

### ISSUE THREAD

**Issue by abelal83** [Azure/azure-cli-extensions#2769]
Does not detail how to change APNS from production to sandbox, any params available for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c327e6d0-f90d-3fa5-611e-660b6e266849
* Version Independent ID: a415a08c-9f0d-1726-1c2f-71b3c63f39d6
* Content: [az notification-hub credential apns](https://docs.microsoft.com/en-us/cli/azure/ext/notification-hub/notification-hub/credential/apns?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/notification-hub/notification-hub/credential/apns.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/notification-hub/notification-hub/credential/apns.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a  look?
