### ISSUE TITLE
Error when attempting to deploy schema

### ISSUE THREAD

**Issue by TrevorLOlson** [Azure/azure-cli-extensions#2776]
## Describe the bug

**Command Name**
`az datamodel deploy-schema
Extension Name: aidls. Version: 0.1.20201120.672.`

**Errors:**
```
list index out of range
Traceback (most recent call last):
azext_aidls\dev\helpers\sql_executer_helper.py, ln 85, in execute_schema_using_connection_string
    cursor.execute(schema)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement failed. Column 'CurrencySymbol' has a data type that cannot participate in a columnstore index. (35343) (SQLExecDirectW)")

...

azext_aidls\dev\helpers\sql_executer_helper.py, ln 26, in _get_ip
    r'\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b', e)[0]
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datamodel deploy-schema --name {} --server-name {} --database-name {} --user-id {} --password {} --target-type {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.16.0

Extensions:
aidls 0.1.20201120.672

```

**Comment by yonzhan** [comment]
datamodel

**Comment by TrevorLOlson** [comment]
[TestRetailWithWeb.zip](https://github.com/Azure/azure-cli-extensions/files/5677229/TestRetailWithWeb.zip)

Here is the model I created using IDW

**Comment by yonzhan** [comment]
It seemed the source code is not in cli extension repo.

**Comment by Juliehzl** [comment]
Hi @TrevorLOlson, may I know how you install the extension? could you find the repo host the extension source code?

**Comment by TrevorLOlson** [comment]
I downloaded it from here https://github.com/Azure/azure-aidls-cli-extension/releases

[aidlswhl.zip](https://github.com/Azure/azure-cli-extensions/files/5677287/aidlswhl.zip)

**Comment by Juliehzl** [comment]
then you could create an issue in https://github.com/Azure/azure-aidls-cli-extension and they could help you.
