### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by perkops** [Azure/azure-cli-extensions#2816]
The line "Note that an endpoint must first be configred before adding an event route."

should be: "Note that an endpoint must first be configured before adding an event route."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a140c57-f5be-81da-9026-000d7641f524
* Version Independent ID: 71160dff-08d2-826f-affa-674216e5acc3
* Content: [az dt route](https://docs.microsoft.com/en-us/cli/azure/ext/azure-iot/dt/route?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-iot/dt/route.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/azure-iot/dt/route.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
iot
