### ISSUE TITLE
Cannot Install CLI; Hangs Indefinitely

### ISSUE THREAD

**Issue by BhargaviAnnadevara-MSFT** [Azure/azure-cli-extensions#2824]
_Originally posted by @lazarillo in https://github.com/MicrosoftDocs/azure-docs/issues/67963#issue-772176250_

### Extension name (the extension in question)
azure-cli-ml

### Description of issue (in as much detail as possible)
Here are the details:

When I try to install the extension, I get the `Downloading`, then `Installing` messages, but then it freezes indefinitely.

Methods:

1. `az extension add --name azure-cli-ml`
2. `az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.19.0-py3-none-any.whl`

Extensions already successfully installed:

1. `azure-devops` (version 0.16.0)
2. `storage-preview` (version 0.2.12)

OS Details:

```bash
❯ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 11.1 (20C69)
      Kernel Version: Darwin 20.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2:23
```
Additional details:
- Yes, I am able to install via the Azure Cloud Shell.
- No, I do not see the extension listed in `az extension list` (see above)
- Yes, I do see the extension in `az extension list-available`
- No, I am still unable to install on my local machine.
  - I have waited up to 4 hours for the install to finish; I am quite sure the problem is not that I simply have not waited long enough.

Please let me know the status and if you need any further details.  This is a fairly significant blocker for my work with Azure right now.

**Comment by yonzhan** [comment]
azure-cli-ml

**Comment by lazarillo** [comment]
Any updates on this?  I tried to install again, still just hangs.  :(

**Comment by yonzhan** [comment]
machine learning service team should look into this issue.

**Comment by lazarillo** [comment]
@yonzhan How do I contact the ML service team?  I actually thought this was the means by which to do that.

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/issues?q=ML+label%3A%22Machine+Learning%22
We are routing this to the appropriate team for follow-up. cc @azureml-github.

**Comment by matthewhall210** [comment]
I have this same issue. @lazarillo did you ever get a resolution?

**Comment by paulshealy1** [comment]
Closing v1 CLI issues. If this continues to occur, please re-open.

**Comment by lazarillo** [comment]
No, @matthewhall210 , I never found a resolution.

To be fair, the problem somewhat "solved itself"... 99% of the time what I needed was the ML SDK.  I only needed the CLI stuff briefly.  And I haven't needed it again.
