### ISSUE TITLE
COSTMANAGEMENT - parameter `dataset-configuration` doesn't work

### ISSUE THREAD

**Issue by michalmar** [Azure/azure-cli-extensions#2826]
I am running `az costmangement quey` and trying to use `dataset-configuration` parameter but it is no applied to the query.

Query: 
`az costmanagement query --type "Usage" --dataset-configuration columns="ServiceName"  --timeframe "TheLastMonth" --scope "subscriptions/xxx"`

Output:
```
Command group 'costmanagement' is experimental and not covered by customer support. Please use with discretion.
{
  "columns": [
    {
      "name": "UsageDate",
      "type": "Number"
    },
    {
      "name": "Currency",
      "type": "String"
    }
  ],
  "eTag": null,
  "id": "subscriptions/xxx/providers/Microsoft.CostManagement/query/1c528a60-fbb0-4f6f-a777-71c1cc4e8761",
  "location": null,
  "name": "1c528a60-fbb0-4f6f-a777-71c1cc4e8761",
  "nextLink": null,
  "rows": [
    [
      20201101,
      "USD"
    ],
    [
      20201102,
      "USD"
    ],
   ...
    [
      20201130,
      "USD"
    ]
  ],
  "sku": null,
  "tags": null,
  "type": "Microsoft.CostManagement/query"
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78dd527c-ac00-130c-f91e-994fe74937e0
* Version Independent ID: 654e9d57-70f1-e053-d377-4647b14df3cc
* Content: [az costmanagement](https://docs.microsoft.com/en-us/cli/azure/ext/costmanagement/costmanagement?view=azure-cli-latest#ext_costmanagement_az_costmanagement_query)
* Content Source: [latest/docs-ref-autogen/ext/costmanagement/costmanagement.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/costmanagement/costmanagement.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
costmanagement

**Comment by haroldrandom** [comment]
dup as https://github.com/Azure/azure-cli-extensions/issues/2021

**Comment by michalmar** [comment]
How this is duplication? I am not running export. Also there is no
resolution or is it?

**Comment by haroldrandom** [comment]
@michalmar Sorry, just the moment I thought it was dup, I found it was not. We are digging whether it's a bug of server-side or CLI-side.

**Comment by michalmar** [comment]
@yonzhan @haroldrandom hi, what is the status of this? has this been identified as bug? any ETA? thanks a lot!

**Comment by yonzhan** [comment]
@michalmar This issue should be looked into by costmangement service team.

**Comment by mrlepat** [comment]
Hello @michalmar 
dataset-configuration is not supported by query. We will update the documentation to reflect that.

You can use dataset-grouping instead:
az costmanagement query --type "Usage" --dataset-aggregation "{\"totalCost\":{\"name\":\"PreTaxCost\",\"function\":\"Sum\"}}" --dataset-grouping name="ServiceName" type="Dimension" --timeframe "TheLastMonth"  --scope "subscriptions/****"

My apologies for any confusion this may have caused.

**Comment by brianstringfellow** [comment]
I tried the aggregation and grouping settings in the query above. The call gives the error `UnrecognizedArgumentError: unrecognized arguments: totalCost:{name:PreTaxCost,function:Sum}}`.

**Comment by M0ns1gn0r** [comment]
There are some `\` missing in the @mrlepat query. The correct one is:

`az costmanagement query --type "Usage" --dataset-aggregation "{\"totalCost\":{\"name\":\"PreTaxCost\",\"function\":\"Sum\"}}" --dataset-grouping name="ServiceName" type="Dimension" --timeframe "TheLastMonth" --scope "subscriptions/****"`

**Comment by JFolberth** [comment]
Thie above example queries do not work for me. Both one provided by @mrlepat and @M0ns1gn0r I still get:
`unrecognized arguments: totalCost\:{\name\:\PreTaxCost\,\function\:\Sum\}}`

In addition documentation has not been updated to show that dataset-configuration is not supported.

**Comment by jsntcy** [comment]
@JFolberth, @brianstringfellow 
You should use `'{\"totalCost\":{\"name\":\"PreTaxCost\",\"function\":\"Sum\"}}'` (use quote instead of double quote)

**Comment by michalmar** [comment]
I understand that the answer for original question is - not supported as @mrlepat stated.
