### ISSUE TITLE
prompt for az vmware private-cloud delete

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli-extensions#2831]
Similar to https://github.com/Azure/azure-powershell/issues/13824, per internal [work item 9019400](https://msazure.visualstudio.com/One/_workitems/edit/9019400/), please add a confirmation prompt for deleting a private cloud.  If there is room for a warning, the warning should match the Portal UI with:

> Deleting the private cloud is an irreversible operation. Once the private cloud is deleted, the data cannot be recovered, as it terminates all running workloads and components and destroys all private cloud data and configuration settings, including public IP addresses.

**Comment by yungezz** [comment]
hi @ctaggart assigned the issue to you. Are you still owning the vmware extesnion?

**Comment by ctaggart** [comment]
@yungezz, the goal of moving it in to azure-cli-extensions was to pass over ownership as well.

**Comment by ctaggart** [comment]
Fixed by #2932
