### ISSUE TITLE
Enabling AAD in AKS cluster results in error

### ISSUE THREAD

**Issue by P47K0** [Azure/azure-cli-extensions#2838]
I have to mention that 'az aks update' also gave this warning:
The behavior of this command has been altered by the following extension: aks-preview

I want to make use of the AAD-V2 feature which I had to register (why I don't know, I thought this was GA already)

I was following this How To guide:
https://docs.microsoft.com/en-us/azure/aks/managed-aad#upgrading-to-aks-managed-azure-ad-integration

## Describe the bug

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.4.71.`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/cli/core/__init__.py, ln 784, in default_command_handler
    return op(**command_args)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1495, in aks_update
    monitoring_addon_enabled = CONST_MONITORING_ADDON_NAME in instance.addon_profiles and \
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -g {} -n {} --enable-aad --aad-admin-group-object-ids {} --aad-tenant-id {}`

## Expected Behavior
AAD enabled in cluster
## Environment Summary
```
Linux-4.15.0-1102-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.16.0

Extensions:
aks-preview 0.4.71
ai-examples 0.2.5

```

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
https://github.com/azure/azure-cli/issue/14287

**Comment by miwithro** [comment]
@P47K0 can you share details of the AKS cluster you are trying to upgrade?

**Comment by P47K0** [comment]
**patrick@Azure:~$** az aks show --name aks-rpms --resource-group rg-web
```
The behavior of this command has been altered by the following extension: aks-preview
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 1,
      "enableAutoScaling": null,
      "enableNodePublicIp": false,
      "kubeletConfig": null,
      "linuxOsConfig": null,
      "maxCount": null,
      "maxPods": 110,
      "minCount": null,
      "mode": "System",
      "name": "nodepool1",
      "nodeImageVersion": "AKSUbuntu-1804containerd-2020.11.11",
      "nodeLabels": {},
      "nodeTaints": null,
      "orchestratorVersion": "1.19.3",
      "osDiskSizeGb": 128,
      "osDiskType": "Managed",
      "osType": "Linux",
      "podSubnetId": null,
      "powerState": {
        "code": "Running"
      },
      "provisioningState": "Succeeded",
      "proximityPlacementGroupId": null,
      "scaleSetEvictionPolicy": null,
      "scaleSetPriority": null,
      "spotMaxPrice": null,
      "tags": null,
      "type": "VirtualMachineScaleSets",
      "upgradeSettings": null,
      "vmSize": "Standard_A2_v2"
    },
    {
      "availabilityZones": null,
      "count": 1,
      "enableAutoScaling": false,
      "enableNodePublicIp": false,
      "kubeletConfig": null,
      "linuxOsConfig": null,
      "maxCount": null,
      "maxPods": 110,
      "minCount": null,
      "mode": "User",
      "name": "spotpool01",
      "nodeImageVersion": "AKSUbuntu-1804containerd-2020.11.11",
      "nodeLabels": {
        "kubernetes.azure.com/scalesetpriority": "spot"
      },
      "nodeTaints": [
        "kubernetes.azure.com/scalesetpriority=spot:NoSchedule"
      ],
      "orchestratorVersion": "1.19.3",
      "osDiskSizeGb": 128,
      "osDiskType": "Managed",
      "osType": "Linux",
      "podSubnetId": null,
      "powerState": {
        "code": "Running"
      },
      "provisioningState": "Succeeded",
      "proximityPlacementGroupId": null,
      "scaleSetEvictionPolicy": "Delete",
      "scaleSetPriority": "Spot",
      "spotMaxPrice": -1.0,
      "tags": null,
      "type": "VirtualMachineScaleSets",
      "upgradeSettings": null,
      "vmSize": "Standard_A2_v2"
    }
  ],
  "apiServerAccessProfile": null,
  "autoScalerProfile": null,
  "autoUpgradeProfile": null,
  "diskEncryptionSetId": null,
  "dnsPrefix": "rpms",
  "enablePodSecurityPolicy": null,
  "enableRbac": true,
  "fqdn": "rpms-f5a0677f.hcp.westeurope.azmk8s.io",
  "id": "/subscriptions/...",
  "identity": null,
  "identityProfile": null,
  "kubernetesVersion": "1.19.3",
  "linuxProfile": {
    "adminUsername": "azureuser",
    "ssh": {
      "publicKeys": [
        {
          "keyData": "ssh-rsa ..."
        }
      ]
    }
  },
  "location": "westeurope",
  "maxAgentPools": 10,
  "name": "aks-rpms",
  "networkProfile": {
    "dnsServiceIp": "10.0.0.10",
    "dockerBridgeCidr": "172.17.0.1/16",
    "loadBalancerProfile": {
      "allocatedOutboundPorts": null,
      "effectiveOutboundIps": [
        {
          "id": "/subscriptions/...",
          "resourceGroup": "MC_rg-web_aks-rpms_westeurope"
        }
      ],
      "idleTimeoutInMinutes": null,
      "managedOutboundIps": {
        "count": 1
      },
      "outboundIpPrefixes": null,
      "outboundIps": null
    },
    "loadBalancerSku": "Standard",
    "networkMode": null,
    "networkPlugin": "kubenet",
    "networkPolicy": null,
    "outboundType": "loadBalancer",
    "podCidr": "10.244.0.0/16",
    "serviceCidr": "10.0.0.0/16"
  },
  "nodeResourceGroup": "MC_rg-web_aks-rpms_westeurope",
  "podIdentityProfile": null,
  "powerState": {
    "code": "Running"
  },
  "privateFqdn": null,
  "provisioningState": "Succeeded",
  "resourceGroup": "rg-web",
  "servicePrincipalProfile": {
    "clientId": "..."
  },
  "sku": {
    "name": "Basic",
    "tier": "Free"
  },
  "type": "Microsoft.ContainerService/ManagedClusters",
  "windowsProfile": null
}
```

**Comment by miwithro** [comment]
Hello,
  I have this running on my system, and was not able to reproduce the error.

  "azure-cli": "2.16.0",
  "azure-cli-core": "2.16.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "aks-preview": "0.4.70"

The biggest difference between your cluster and my test cluster is that your is running on a SP and mine is running via MSI.  Can you upgrade your cluster to MSI and then try again?

https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#update-an-aks-cluster-to-managed-identities-preview

**Comment by P47K0** [comment]
Well I tried to upgrade the cluster to MSI but then I got another error:

az feature register --namespace Microsoft.ContainerService -n MigrateToMSIClusterPreview

(waited several minutes)
az provider register -n Microsoft.ContainerService

az aks update -g rg-web -n aks-rpms --enable-managed-identity
The behavior of this command has been altered by the following extension: aks-preview
Your cluster is using service principal, and you are going to update the cluster to use systemassigned managed identity.
After updating, your cluster's control plane and addon pods will switch to use managed identity, but kubelet will KEEP USING SERVICE PRINCIPAL until you upgrade your agentpool.
 Are you sure you want to perform this operation? (y/N): y

CLIInternalError: The command failed with an unexpected error. Here is the traceback:
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/home/patrick/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1495, in aks_update
    monitoring_addon_enabled = CONST_MONITORING_ADDON_NAME in instance.addon_profiles and \
TypeError: argument of type 'NoneType' is not iterable

**Comment by P47K0** [comment]
This is what az --version gives back in my cluster:
azure-cli                         2.16.0 *
core                              2.16.0 *
telemetry                          1.0.6

Extensions:
aks-preview                       0.4.71
ai-examples                        0.2.5

Python location '/opt/az/bin/python3'
Extensions directory '/home/patrick/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.6/site-packages/azure-cli-extensions'

Python (Linux) 3.6.10 (default, Dec  4 2020, 12:35:06)
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 updates available. They will be updated with the next build of Cloud Shell.

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of azure cli and reopen this issue if you are still facing it.
