### ISSUE TITLE
az graph query ingores underlying API error and returns incorrect results

### ISSUE THREAD

**Issue by lesterw1** [Azure/azure-cli-extensions#2844]
The CLI command **az graph query -q** *$query* (in resource-graph extension) ignores the underlying error returned by the REST API and returns the incorrect data. While the API should not return "bad" data, the Azure CLI also should catch the error and display it. Instead, it simply displays the bad data.

The Azure CLI uses the rest API endpoint:
https://management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=2019-04-01
and includes the subscriptions and query in the body of the call. See **execute_query()** in https://github.com/Azure/azure-cli-extensions/blob/master/src/resource-graph/azext_resourcegraph/custom.py. 

### Extension name (the extension in question)
resource-graph

### Description of issue (in as much detail as possible)
This issue came about due to a complicated query which lists all VMs and their associated NSGs (quite useful to see at a glance). The query works fine in the Azure ARM portal, but fails when used via the REST API. But when tested with the Azure CLI, it mysteriously returned results without any error. On further investigation, the results were incorrect, so it *appears* that the error is being ignored by the CLI extension.

To reproduce this issue, use the following within PowerShell (to make it easy to pass the large $query to AZ CLI):

```
$query = 'Resources
| where type =~ "microsoft.network/networkinterfaces"
| mv-expand ipConfigurations = properties.ipConfigurations
| extend ipCount = array_length(properties.ipConfigurations)
| extend privateIPType = tostring(ipConfigurations.properties["privateIPAllocationMethod"])
| extend privateIP = tostring(ipConfigurations.properties["privateIPAddress"])
| extend subnetId = tostring(ipConfigurations.properties.subnet["id"])
| extend publicIPid = tostring(ipConfigurations.properties["publicIPAddress"].id)
| extend nicId = tostring(id)
| join kind=leftouter (Resources  
	| where type contains "publicIPAddresses" and isnotempty(properties.ipAddress)
	| extend publicIP = tostring(properties.ipAddress),
		publicIPid = tostring(id)) on publicIPid
| join kind=leftouter (Resources | where type == "microsoft.network/networksecuritygroups"
	| mv-expand nics = properties.networkInterfaces
	| extend nicId = tostring (nics.id),
		nicNSG = name,
		nicNSGgroup = resourceGroup  ) on nicId
| join kind=leftouter (Resources
	| where type == "microsoft.compute/virtualmachines" and isnotempty(properties.networkProfile.networkInterfaces)
	| extend vmName = name
	| extend vmSize = tostring(properties.hardwareProfile.vmSize)
	| extend osType = tostring(properties.storageProfile.osDisk.osType)
	| mv-expand nics = properties.networkProfile.networkInterfaces
	| extend nicId = tostring (nics.id) ) on nicId
| join kind=leftouter (Resources | where type == "microsoft.network/networksecuritygroups"
	| mv-expand subnets = properties.subnets
	| extend subnetId = tostring(subnets.id),
		vnetName = split(tostring(subnets.id),"/")[8],
		subnetName = split(tostring(subnets.id),"/")[10],
		subnetNSG = name,
		subnetNSGgroup = resourceGroup
	) on subnetId
| project subscriptionId, nicName=name, resourceGroup, vmName, vmSize, osType, vnetName, subnetName, nicNSG, subnetNSG, location, ipCount, privateIPType, privateIP, publicIP, tags, subnetId, nicId'

# The output does NOT match the prject statement and no error was displayed:
PS C:\> $r = az graph query -q $query
PS C:\> $r1[0]

extendedLocation : 
id               : /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/DataCatalogs-EastUS/providers/Microsoft.DataCatalog/catalogs/MyDC
identity         : 
kind             : 
location         : eastus
managedBy        : 
name             : MyDC
plan             : 
properties       : @{admins=System.Object[]; enableAutomaticBillingUnitAdjustment=False; provisioningState=Succeeded; sku=Standard; users=System.Object[]}
resourceGroup    : datacatalogs-eastus
sku              : 
subscriptionId   : 00000000-0000-0000-1111-000000000000
tags             : @{CreatedBy=Joe; CreatedTime=11/21/2020 01:28:24}
tenantId         : 00000000-0000-0000-0000-000000000000
type             : microsoft.datacatalog/catalogs
zones            : 
 

# Just to show that the same $query fails in PowerShell Search-AzGraph which uses the same API version:

PS C:\> Search-AzGraph -Query $query
Search-AzGraph : {
  "error": {
    "code": "BadRequest",
    "message": "Please provide below info when asking for support: timestamp = 2020-12-28T14:05:36.2981641Z, correlationId = c20308c2-a874-4fe1-a063-8a4f963a2378.",
    "details": [
      {
        "code": "InvalidQuery",
        "message": "Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying."
      },
      {
        "code": "TooManyMvExpandColumns",
        "message": "The query invokes mvexpand on 4 columns, and has exceeded the limit of 2. Please consider simplifying the query logic."
      },
      {
        "code": "TooManyJoins",
        "message": "The query uses 4 join operators, and has exceeded the limit of 3. Please consider simplfying the query logic."
      }
    ]
  }
}
At line:1 char:1
+ Search-AzGraph -Query $query
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Search-AzGraph], ErrorResponseException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Azure.Commands.ResourceGraph.Cmdlets.SearchAzureRmGraph

PS C:\>  
```

### Version
```
# Version of AZ tool on Windows 10 Desktop: 
PS C:\> az version
{
  "azure-cli": "2.15.1",
  "azure-cli-core": "2.15.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "resource-graph": "1.1.0"
  }
}
```

### Additional Notes
Note that the query itself works perfectly well in the Azure ARM portal but fails when used via the API. 
A separate bug https://github.com/Azure/azure-powershell/issues/13845 has been opened for this issue to address the separate  REST API quota issue. But this bug does not resolve the fact that the Azure CLI ignored the error.

-----

**Comment by yonzhan** [comment]
resource-graph

**Comment by chiragg4u** [comment]
As captured in another [thread](https://github.com/Azure/azure-powershell/issues/13845) we have more limits in the ARG CLI. Please provide feedback in our uservoice channel so that we can prioritize most important features @ https://feedback.azure.com/forums/915958-azure-governance?category_id=345061

**Comment by snaheth** [comment]
Since @chiragg4u addressed the throttling/limits aspect of the question, let me close this by addressing the incorrect results issue you're seeing when you use Azure CLI within PowerShell.

Background: From [Azure CLI "Issues with PS" page](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md), we see that "In order for a symbol to be received by Azure CLI, you will have to take both PowerShell and Command Prompt's parsing into consideration".

Incorrect Results Explanation: When you run `az graph query -q $query` - the CLI reads only the first line `Resources` and sends that to our service. This is why you see an incorrect result returned from your request to Azure Resource Graph when using the Azure CLI within PowerShell.

To fix this -- you can run the snippet below and you will retrieve the correct result.
 
```bash
$query | az graph query -q "@-"
```
