### ISSUE TITLE
CLI switch for az iot hub monitor-events -n <iothub> 

### ISSUE THREAD

**Issue by Soren1974** [Azure/azure-cli-extensions#2883]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
CLI - "az iot hub monitor-events -n <iothub>"

### Description of issue (in as much detail as possible)
I would like a to set the number of events to be captured instead of the infinite loop. Perhaps a switch could use -1 for infinite loop.
-----

**Comment by yonzhan** [comment]
iot hub

**Comment by digimaun** [comment]
This is supported, please use `--message-count` with the `monitor-events` command.
