### ISSUE TITLE
would be nice to use existing RGs instead of transient ones.  our environment does not allow RG creation/removal

### ISSUE THREAD

**Issue by manekja** [Azure/azure-cli-extensions#291]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
image copy

### Description of issue (in as much detail as possible)
in our environment, the rapid spawn of Resource Groups necessitated the eliminating of creating RG's, instead permission'ing to pre-existing RGs was done.
It would be advantageous, read as we can't use this great tool, w/o being able to use pre-existing RGs as the temporary/transient RG.  currently the tool just assumes it can create/delete an RG named 'image-copy-rg'
-----

**Comment by tamirkamara** [comment]
Hi @manekja 
so adding a switch **--source-resource-group** to the command will be helpful in your situation. right?

**Comment by manekja** [comment]
Yes, if that is where the transient RG is created/removed when doing the image copy.  Using a pre-provisioned RG would solve my problems at either/both the source and target Locations if RG's are being created/removed during the copy process.

Thank you for the response.

**Comment by tamirkamara** [comment]
Now there's an option which enable you to name the temp resource group used.
@williexu this issue is resolved and can be closed

**Comment by manekja** [comment]
Thank you.  I’ll download, install and test it out.  Thanks.

**Comment by manekja** [comment]
if there is a new options that allows specifying a pre-defined temporary resource group, I can't find it and nothing obvious shows up in an 'az image copy --help.  
could you please assist me with  what the parameter is or if this fix made into the production tree.

**Comment by tamirkamara** [comment]
@manekja The version with the new option is 0.2.1 and is going to be published soon. please watch #669 and after it is merged, update your installed extension.
