### ISSUE TITLE
automatic installation suggestion does not work

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-cli-extensions#2918]
The documentation claims "The extension will automatically install the first time you run an `az monitor app-insights` command."

Actual results:
```
CommandNotFoundError: 'app-insights' is misspelled or not recognized by the system.
Try this: 'az extension add --name <anextension>'
Still stuck? Run 'az monitor --help' to view all commands or go to 'https://aka.ms/cli_ref' to learn more
``` 

This was with azure-cli version 2.18.0 installed.

From here, I manually installed the extension.
```
az extension add --name application-insights
```

Once it was installed, it worked as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bce0dc5-da82-717a-70cf-e392c05904a3
* Version Independent ID: a5cb6492-d731-0c98-7691-64d1d7a14a5c
* Content: [az monitor app-insights](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
automatic installation

**Comment by kairu-ms** [comment]
Hi @bmc-msft, I cannot reproduce it, that command can work on my machine. Can you provide environment information? Thanks.

**Comment by bmc-msft** [comment]
Ubuntu 20.20 in WSL, from `az --version`

```
azure-cli                         2.15.1 *

core                              2.15.1 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.17.0
resource-graph                     1.1.0

Python location '/usr/bin/python3'
Extensions directory '/home/USERNAME/.azure/cliextensions'

Python (Linux) 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]
```

**Comment by kairu-ms** [comment]
Automatic installation works now.

**Comment by bmc-msft** [comment]
@kairu-ms, this does not work as expected following the documentation:

https://docs.microsoft.com/en-us/cli/azure/monitor/app-insights?view=azure-cli-latest

The documentation states:
> The extension will automatically install the first time you run an `az monitor app-insights` command.

```
❯ az --version
azure-cli                         2.26.1

core                              2.26.1
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
resource-graph                     2.1.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/USERNAME/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Jul 14 2021, 08:09:30)
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
❯ az monitor app-insights
'app-insights' is misspelled or not recognized by the system.

TRY THIS:
az extension add --name anextension
Add extension by name

https://docs.microsoft.com/en-US/cli/azure/extension#az_extension_add
Read more about the command in reference docs
```

**Comment by kairu-ms** [comment]
If it's a command group. Please add `-h` to trigger automatic installation detection.

![image](https://user-images.githubusercontent.com/69238381/127257080-aec030b2-ff5b-4fa8-aea7-e6633d9bb843.png)
