### ISSUE TITLE
need compute type for computetarget in ml extension

### ISSUE THREAD

**Issue by hyssh** [Azure/azure-cli-extensions#2940]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
__azure-cli-ml__

### Description of issue (in as much detail as possible)
<code>az ml computetarget list </code> does not provide the type of compute in the result of the command.

For example, when I run the computetarget list, it shows only following info:
* location
* name
* provisioningError
* provisioningState

It is hard to manage a particular type of compute target without property that indicating type of compute. 

-----

**Comment by yonzhan** [comment]
ml

**Comment by brendalee** [comment]
Thanks for sharing your input. We are working on v2 of our dev platform including CLI commands, and will be incorporating this feedback.

**Comment by brendalee** [comment]
#pls-close
