### ISSUE TITLE
az repos pr list --include-links does not list linked work items

### ISSUE THREAD

**Issue by timvink** [Azure/azure-cli-extensions#2946]
### az repos

I want to see the linked work items of all pull requests. The [documentation](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/pr?view=azure-cli-latest#ext_azure_devops_az_repos_pr_list) states that I can do with with `--include-links`:

```shell
az repos pr list --repository {repository_name} --include-links
```

However the JSON returned contains `"workItemRefs": null`. 

My current workaround is looping over all the pull requests with `az repos pr work-item list --id {pr_id} --query '[].id'`, but this is slow and inefficient.

Context: I want to list all work items in a given iteration, and their linked PR id's in a table.

**Comment by yonzhan** [comment]
repos

**Comment by timvink** [comment]
Just tested this again, same issue is still present. Would appreciate a follow-up!

**Comment by timvink** [comment]
Looks like this issue is more relevant tot he azure devops extension repo, re-posted here: https://github.com/Azure/azure-devops-cli-extension/issues/1120
