### ISSUE TITLE
az network firewall nat-rule create --translated-address doesnt accept IP address

### ISSUE THREAD

**Issue by djr1991** [Azure/azure-cli-extensions#2989]
## Describe the bug
Errors out in AZ CLI 2.18 (cloud-shell bash),  Feedback and error from cloudshell.

--translated-address does not accept an IP Address as value.  Have tried wrapping '', "", and parametizing value.  

**Command Name**
`az network firewall nat-rule create
Extension Name: azure-firewall. Version: 0.9.0.`

**Errors:**
```
BadRequestError: AzureFirewallRule SpringCloudIngressDNAT: Invalid IP address value or range or Service Tag clouddrive.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
run command to create DNAT rule/collection.  

- _Put any pre-requisite steps here..._
- `az network firewall nat-rule create --collection-name {} --destination-ports {} --firewall-name {} --name {} --protocols {} --translated-port {} --action {} --resource-group {} --destination-addresses {} --source-addresses {} --priority {} --translated-address {} --debug`

## Expected Behavior
DNAT rule created on the Azure Firewall

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.18.0
azure-cli-ml 1.20.0

Extensions:
azure-firewall 0.9.0
ai-examples 0.2.5
azure-cli-ml 1.20.0

```

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
I can't reproduce your issue. It works for me.
![image](https://user-images.githubusercontent.com/69238381/127106599-ced6dd6b-b9a2-4920-a80c-87bc14cc99ad.png)


Please upgrade cli and firewall by command
```
az upgrade
```
