### ISSUE TITLE
az aks browse error

### ISSUE THREAD

**Issue by Snorky35** [Azure/azure-cli-extensions#2997]
## Describe the bug

**Command Name**
`az aks browse
Extension Name: aks-preview. Version: 0.5.0.`

**Errors:**
```
'CloudEndpoints' object has no attribute 'portal'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 635, in aks_browse
    cmd.cli_ctx.cloud.endpoints.portal +  # Azure Portal URL (https://portal.azure.com for public cloud)
azure/cli/core/cloud.py, ln 100, in __getattribute__
    val = object.__getattribute__(self, name)
AttributeError: 'CloudEndpoints' object has no attribute 'portal'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --name {} --resource-group {}`

## Environment Summary
```
Linux-5.8.0-41-generic-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
aks-preview 0.5.0
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
aks

**Comment by aneeshbhat23** [comment]
Ran into the same issue for the aks browse command.

**Environment Details:**

azure-cli                          2.8.0

command-modules-nspkg              2.0.3
core                               2.8.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
aks-preview                        0.5.5

Python location '/opt/az/bin/python3'
Extensions directory '/home/aneesh/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Jun 19 2020, 07:14:24) 
[GCC 5.4.0 20160609]

**Comment by Snorky35** [comment]
I resolved this issue by executing the following command :

az aks get-credentials --resource-group $RSS_GROUP_NAME --name $AKS_CLUSTER --admin -a

Hope it will help

**Comment by robbiezhang** [comment]
@Snorky35 @aneeshbhat23 thanks for reporting. I cannot repro the issue with azure-cli 2.22.0 + aks-preview extension, but I did repro it with azure-cli 2.8.0 + aks-preview extension.
I guess your azure-cli version is too old, which doesn't contain the "portal" property in the CloudEndpoints.

**Comment by robbiezhang** [comment]
Looks like it's added in azure-cli 2.13, and verified it's working. Please upgrade your azure-cli version
https://github.com/Azure/azure-cli/commit/bade99898a9ce6b321c53ef5be3633b1eedc508c

**Comment by aneeshbhat23** [comment]
@robbiezhang After upgrading to the latest version (azure-cli: 2.22.0, aks-preview: 0.5.5), it is working fine. Thanks.

**Comment by RakeshMohanMSFT** [comment]
Closing the issue
