### ISSUE TITLE
Scheduled-query create example throws BadRequest error

### ISSUE THREAD

**Issue by Blackbaud-ChrisBlythe** [Azure/azure-cli-extensions#3002]
I tried playing around the scheduled-query cli commands and kept running into issues parsing the LogAnalytics query we were attempting to use in the condition. So, I simply tried using the condition provided in the examples and it had similar issues.

```
C:\Users\XXXXX>az monitor scheduled-query create -g <RG> -n Another-Alert --scopes <RESOUCE ID> --description "This is a description" --condition "count 'union Event, Syslog | where TimeGenerated > ago(1h) | where EventLevelName=="Error" or SeverityLevel=="err"' > 360 resource id _ResourceID at least 1 violations out of 5 aggregated points"
BadRequest: {
  "error": {
    "message": "The request had some invalid properties",
    "code": "BadArgumentError",
    "correlationId": "fb91e6e3-85e8-4a34-a2c3-c5c76468f26a",
    "innererror": {
      "code": "SemanticError",
      "message": "A semantic error occurred.",
      "innererror": {
        "code": "SEM0100",
        "message": "'where' operator: Failed to resolve column or scalar expression named 'Error'"
      }
    }
  }
```

Any help or guidance would be greatly appreciated...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445d2458-1e27-7cf4-8a04-95ec798ebdc1
* Version Independent ID: 3f80ed4a-d3c4-d15c-3e5d-50a48e0eb72c
* Content: [az monitor scheduled-query](https://docs.microsoft.com/en-us/cli/azure/ext/scheduled-query/monitor/scheduled-query?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/scheduled-query/monitor/scheduled-query.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/scheduled-query/monitor/scheduled-query.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
The bug is fixed by PR. It's in code review stage and will be released soon. Currently I made an edge build for that extension. Please install by the following commands and try again:
```
az extension remove -n scheduled-query
az extension add --source https://kairu.blob.core.windows.net/kairu/scheduled_query-0.2.2-py2.py3-none-any.whl
```
BTW please use following value for `--condition`
```
--condition "count 'union Event, Syslog | where TimeGenerated > ago(1h) | where EventLevelName==\'Error\' or SeverityLevel==\'err\'' > 360 resource id _ResourceID at least 1 violations out of 5 aggregated points"
```
