### ISSUE TITLE
az cli Log Analytics example doesnt work

### ISSUE THREAD

**Issue by kelvin-ko** [Azure/azure-cli-extensions#3003]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Log Analystics

### Description of issue (in as much detail as possible)
I got errors when running the query example provided in this page even I have log analytics extension installed.

 https://docs.microsoft.com/en-us/cli/azure/ext/log-analytics/monitor/log-analytics?view=azure-cli-latest#ext_log_analytics_az_monitor_log_analytics_query

az monitor log-analytics query -w <my workspace id>--analytics-query "AzureActivity | summarize count() by bin(timestamp, 1h)" -t P3DT12H

-----

**Comment by kelvin-ko** [comment]
The error message:

UnknownError: code: BadArgumentError - , The request had some invalid properties

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
Please try `TimeGenerated` instead of `timestamp`.
