### ISSUE TITLE
[Managed Identities] No information or examples

### ISSUE THREAD

**Issue by cristian-eriomenco** [Azure/azure-cli-extensions#3006]
The web version from [the docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#:~:text=for%20the%20connection.-,In%20Azure%20DevOps%2C%20open%20the%20Service%20connections%20page%20from%20the,the%20Managed%20Identity%20Authentication%20option.)

Clearly shows possibility of adding a service connection by using managed identities. 

At the moment is unclear whether there is any support via CLI ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99f009a0-d8e9-4077-f78f-9f56c6cc0a8b
* Version Independent ID: 7a02d2f3-db65-e8d2-6948-a97b830a0164
* Content: [az devops service-endpoint azurerm](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/service-endpoint/azurerm?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint/azurerm.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint/azurerm.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
devops

**Comment by RakeshMohanMSFT** [comment]
You can use this command for the same `[az devops service-endpoint azurerm create](https://learn.microsoft.com/en-us/cli/azure/devops/service-endpoint/azurerm?view=azure-cli-latest)`
