### ISSUE TITLE
Public-configuration list command throws error

### ISSUE THREAD

**Issue by jshaptic** [Azure/azure-cli-extensions#3008]
When command `az maintenance public-configuration list` is executed it throws a python error.

**Command Name**
`az maintenance public-configuration list
Extension Name: maintenance. Version: 1.1.0.`

**Errors:**
```
Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-0bxt5m_r\msrest\serialization.py, ln 1416, in _deserialize
Temp\pip-unpacked-wheel-0bxt5m_r\msrest\serialization.py, ln 1160, in rest_key_extractor
AttributeError: 'str' object has no attribute 'get'

...

Temp\pip-unpacked-wheel-0bxt5m_r\msrest\serialization.py, ln 1416, in _deserialize
Temp\pip-unpacked-wheel-0bxt5m_r\msrest\serialization.py, ln 1160, in rest_key_extractor
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az maintenance public-configuration list`

## Expected Behavior
List of public configurations are visible

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

Extensions:
maintenance 1.1.0
scheduled-query 0.2.1

```

**Comment by yonzhan** [comment]
maintenance

**Comment by jshaptic** [comment]
What do you mean? There is some maintenance work happening in Azure right now?

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of azure cli. It is working now.

**Comment by jshaptic** [comment]
My current version of azure-cli is **2.41.0** and I can confirm that in this version, bug is not reproduced anymore.
