### ISSUE TITLE
[storage-preview]: RemoteException while download single blob file

### ISSUE THREAD

**Issue by v-caxian** [Azure/azure-cli-extensions#3018]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

storage-preview

### Description of issue (in as much detail as possible)

az storage azcopy blob download failed.

script:
```powershell
az extension add --name storage-preview
az storage azcopy blob download --container $containerName --source $blobName --destination $file --connection-string $connectionString
```

error: 
```
+ az storage azcopy blob download --container $containerName --source $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Azcopy command:...x-v3-perf.zip']:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
-----

**Comment by yonzhan** [comment]
storage-preview

**Comment by Juliehzl** [comment]
Hi @v-caxian, could you provide more debug information with `--debug` in your command?

**Comment by Juliehzl** [comment]
In addition, may I know why you want to use `azcopy download` instead of  `az storage blob download`?

**Comment by yonzhan** [comment]
Hi @v-caxian, any update?
