### ISSUE TITLE
Error when trying to install Azure AEM Extension for SAP

### ISSUE THREAD

**Issue by janeallianz** [Azure/azure-cli-extensions#3019]
## Describe the bug

**Command Name**
`az vm aem set
Extension Name: aem. Version: 0.1.1.`

**Errors:**
```
'str' object has no attribute 'value'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 664, in execute
    raise ex
cli/core/commands/__init__.py, ln 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 720, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aem/azext_aem/custom.py, ln 31, in set_aem
    skip_storage_analytics=skip_storage_analytics)
cliextensions/aem/azext_aem/custom.py, ln 57, in __init__
    os_type = self._vm.storage_profile.os_disk.os_type.value.lower()
AttributeError: 'str' object has no attribute 'value'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm aem set -g {} -n {}`

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.19.0 *

Extensions:
aem 0.1.1
ai-examples 0.2.5

```

**Comment by yungezz** [comment]
hi @MSSedusch could you pls look at the issue? thanks

**Comment by MSSedusch** [comment]
@janeallianz there is a known issue when installing the old version of the VM extension for SAP on SLES 15. Can you please try to install the new version of the extension via the following command? Please make sure to use the lastest version of the aem extension for Azure CLI (0.2.0 or higher)

`az vm aem set --resource-group <resource group name> --name <vm name> --install-new-extension`

**Comment by janeallianz** [comment]
hi @MSSedusch, thanks for the information. I tried to install the new extension but I get a LinkedAuthorizationFailed error because I don't have read permissions on the image used to create the VM (different subscription). Is this really needed? I didn't need it for previous installations of the old extension. Thanks.

**Comment by MSSedusch** [comment]
The new extension uses the Azure REST API to get the information required by the SAP Host Agent. So the VM needs read permission on the VM, NICs and disks attached to the VM. I will have a look why read access to the VM also required read access on linked resources.

**Comment by janeallianz** [comment]
Hi @MSSedusch is there any update? Thanks.

**Comment by MSSedusch** [comment]
no, not yet. Still looking into it. Sorry for the delay

**Comment by MSSedusch** [comment]
@janeallianz I found a workaround and will provide a fix next week

**Comment by janeallianz** [comment]
@MSSedusch thanks for the update. Could you please tell me when the fix will be available on CLI? Many thanks.

**Comment by MSSedusch** [comment]
The fix was merged. Once PR https://github.com/Azure/azure-cli-extensions/pull/3179 is merged too, aem version 0.2.2 will be published and you can use it after updating to this version with e.g.

`az upgrade`

**Comment by janeallianz** [comment]
@MSSedusch thanks.. any idea how long that will take? is it possible to apply the fix myself or do I have to wait for the update?

**Comment by MSSedusch** [comment]
@janeallianz PR was merged. AEM 0.2.2 is now available. Please give it a try and let me know if this version solves your issue.

**Comment by janeallianz** [comment]
@MSSedusch thanks for the quick response. I tried it but now get a roleAssignments error:

The client 'JANE.TOOKE@ALLIANZ.DE' with object id '3edc8f0d-e909-4613-90b6-6fdc0ede3422' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/dd7199db-bdad-49c9-b25c-b6520490e0f2/resourceGroups/RG-PO-ALL/providers/Microsoft.Authorization/roleAssignments/d664dbac-3d8e-42f9-99b4-e6150df656a1' or the scope is invalid. If access was recently granted, please refresh your credentials.

I have Contributor Role for the subscription mentioned.

**Comment by MSSedusch** [comment]
You need to have Owner privileges or User Access Administrator to be able to install the extension. You need to have these privileges either on the resource group or, if you call az vm aem set with parameter --set-access-to-individual-resources, you need to have these privileges on the VM and all relevant resources, like disks and network interfaces that are used by the VM.
The reason is that the installation enables a Managed Identity on the VM and gives that Managed Identity access to these resources.
