### ISSUE TITLE
Where the extension issues should be submitted?

### ISSUE THREAD

**Issue by marcindulak** [Azure/azure-cli-extensions#3063]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Description of issue (in as much detail as possible)

-----

Above is the issue template. What is meant by `If the issue is to do with Azure CLI 2.0 in-particular`?
Does it suggest that **all** issues related to az 2.0 extensions should be submitted to the `azure-cli` repository, or just asks to submit issues judged as belonging to the **core** of az to the `azure-cli` repository, and keep the extensions issues here?

**Comment by yonzhan** [comment]
core will be to the azure-cli repo and keep the extensions issues here.

**Comment by marcindulak** [comment]
Can the issue template be modified to clarify this intent?
