### ISSUE TITLE
Running az aks kollect on AKS cluster returns in error

### ISSUE THREAD

**Issue by 01011011** [Azure/azure-cli-extensions#3066]
## Describe the bug

**Command Name**
`az aks kollect
Extension Name: aks-preview. Version: 0.5.0.`

**Errors:**
```
Command '['kubectl', '--kubeconfig', 'C:\\Users\\niivetic\\AppData\\Local\\Temp\\tmpclxeff3r', 'get', 'apd', '-n', 'aks-periscope', '--no-headers']' returned non-zero exit status 1.
Traceback (most recent call last):
Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py, ln 233, in invoke
cli\core\commands\__init__.py, ln 664, in execute
cli\core\commands\__init__.py, ln 727, in _run_jobs_serially
cli\core\commands\__init__.py, ln 720, in _run_job
Local\Temp\pip-unpacked-wheel-rg200gj8\six.py, ln 703, in reraise
...
subprocess.py, ln 438, in run
subprocess.CalledProcessError: Command '['kubectl', '--kubeconfig', 'C:\\Users\\niivetic\\AppData\\Local\\Temp\\tmpclxeff3r', 'get', 'apd', '-n', 'aks-periscope', '--no-headers']' returned non-zero exit status 1.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks kollect -g {} -n {} --storage-account {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

Extensions:
aks-preview 0.5.0
dev-spaces 1.0.4

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Tatsinnit** [comment]
💡 Hiya and thanks for follow-up on this. I tried to reproduce this and was unable to, hence sharing my initial findings: 

Can you share more details for reproducing this please: with the extension version `0.5.0` I am not able reproduce this error. I tried by uninstalling the `kubectl` as well.

From the error it looks like the az cli level - core process had a failure that the given time when the above command was tried and it failed.

I will reach out to more folks and if this is reproducible at their end. Thanks heaps.

**Comment by 01011011** [comment]
I believe it had to do with the storage account.  I was just choosing the defaults initially in the cluster, maybe look into that.

**Comment by Tatsinnit** [comment]
Hiya @01011011  (nikola) thanks for reply, I tried with default storage, using the storage account in diagnostics settings for your managed cluster. But seems to be behaving as expected. 

* I will try it again, with new account.
* In the mean time if you have reproducible replication steps then please feel free to share.

thank you.

**Comment by Tatsinnit** [comment]
💡 loop back to update that I tried few ways, but not able to re-pro this issue, even with the resource missing I get the following error as mentioned below.

Also, if we look at the issue the actual problem is not the `aks` command it is the `kubectl` invocation which failed with non-zero exit-code. If we have a repro, we could investigate this further otherwise we can close this issue for now

Thank you so much.

<img width="1770" alt="Screen Shot 2021-04-28 at 9 44 14 AM" src="https://user-images.githubusercontent.com/6233295/116316786-8f288680-a806-11eb-885f-d7458e90df1a.png">

**Comment by 01011011** [comment]
Sounds good, I did not have time to look into it again, if I run into the issue again I will post it.
