### ISSUE TITLE
Not able to enable "az aks update --resource-group labeddie --name testingress --uptime-sla"

### ISSUE THREAD

**Issue by edervaldonetoMS** [Azure/azure-cli-extensions#3069]
## Describe the bug
After creating a new AKS clsuter version 1.20.3, I was trying to enable "--uptime-sla" and recevies the following error below.

![image](https://user-images.githubusercontent.com/56553626/109393448-97a13580-7919-11eb-9ce7-2c0165dce1db.png)

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.0.`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 664, in execute
    raise ex
cli/core/commands/__init__.py, ln 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/cli/core/__init__.py, ln 816, in default_command_handler
    return op(**command_args)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1554, in aks_update
    monitoring_addon_enabled = CONST_MONITORING_ADDON_NAME in instance.addon_profiles and \
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group labeddie --name testingress --uptime-sla`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.19.1

Extensions:
aks-preview 0.5.0

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14287

**Comment by edervaldonetoMS** [comment]
By disabling the **AKS-preview** it works fine...once enabled does not work. Perhaps some kind of the integration of "AKS-Preview" with "AZ-CLI".

**Comment by RakeshMohanMSFT** [comment]
This is working now. Please reopen if you are still facing this issue.
![Uploading image.png…]()
