### ISSUE TITLE
Example for Recurrence Type Once needed

### ISSUE THREAD

**Issue by PCNZ** [Azure/azure-cli-extensions#3072]
Please add an example were the occurrence type is set to once.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2083273-b3ba-6507-f038-b55d0b90f753
* Version Independent ID: 12395969-8d39-0889-05b2-5717adc221b8
* Content: [az monitor action-rule](https://docs.microsoft.com/en-us/cli/azure/ext/alertsmanagement/monitor/action-rule?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/alertsmanagement/monitor/action-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/alertsmanagement/monitor/action-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
monitor
