### ISSUE TITLE
Transition to GA: powerbidedicated

### ISSUE THREAD

**Issue by evelyn-ys** [Azure/azure-cli-extensions#3089]
Command module `powerbidedicated` has been released for a long time and is using stable sdk version `2017-10-01`.

Please check [Extension GA guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/onboarding_guide.md#preview-extension-to-ga-extension) and remove `preview` tag if necessary.

**Comment by yonzhan** [comment]
powerbidedicated

**Comment by Juliehzl** [comment]
`preview` is a tag for CLI code readiness. As `storage-preview` is using table api version, but it is till in preview. For `powerbidedicted`, as the code is auto-generated and we received issue for command design, I will prefer keeping it here for several months.

**Comment by evelyn-ys** [comment]
> `preview` is a tag for CLI code readiness. As `storage-preview` is using table api version, but it is till in preview. For `powerbidedicted`, as the code is auto-generated and we received issue for command design, I will prefer keeping it here for several months.

Got it!
