### ISSUE TITLE
Transition to GA: stack-hci

### ISSUE THREAD

**Issue by evelyn-ys** [Azure/azure-cli-extensions#3090]
Command module `stack-hci` has been released for a long time and is using stable sdk version `2020-10-01`.

Please check [Extension GA guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/onboarding_guide.md#preview-extension-to-ga-extension) and remove `experimental` tag if necessary.

**Comment by yonzhan** [comment]
stack-hci

**Comment by zhoxing-ms** [comment]
Stack HCI has been already GA by this PR: #2938
