### ISSUE TITLE
Transition to GA: storagesync

### ISSUE THREAD

**Issue by evelyn-ys** [Azure/azure-cli-extensions#3091]
Command module `storagesync` has been released for a long time and is using stable sdk version `2019-06-01`.

Please check [Extension GA guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/onboarding_guide.md#preview-extension-to-ga-extension) and remove `experimental` tag if necessary.

**Comment by yonzhan** [comment]
storagesync
