### ISSUE TITLE
Transition to GA: timeseriesinsights

### ISSUE THREAD

**Issue by evelyn-ys** [Azure/azure-cli-extensions#3092]
Command module `timeseriesinsights` has been released for a long time and is using stable sdk version `2020-05-15`.

Please check [Extension GA guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/onboarding_guide.md#preview-extension-to-ga-extension) and remove `experimental` tag if necessary.

**Comment by yonzhan** [comment]
timeseriesinsights
