### ISSUE TITLE
Documentation does not specify if this function is recursive

### ISSUE THREAD

**Issue by nickpainter** [Azure/azure-cli-extensions#3106]
Documentation for this command does not specify if the command is recursive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c04bff2-7465-3a25-0484-efe05354b015
* Version Independent ID: ab9c14dd-c6c5-e28d-ad30-8e2caf9fc811
* Content: [az storage blob copy](https://docs.microsoft.com/en-us/cli/azure/ext/storage-blob-preview/storage/blob/copy?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/storage-blob-preview/storage/blob/copy.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/storage-blob-preview/storage/blob/copy.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @nickpainter, do you mean `az storage blob copy start-batch`? It is recursive one and we also print all blobs to copy in terminal.

**Comment by yonzhan** [comment]
Hi @nickpainter, any feedback or update?
