### ISSUE TITLE
Failure running command - az logic

### ISSUE THREAD

**Issue by marciobarbato** [Azure/azure-cli-extensions#3125]
## Describe the bug

**Command Name**
`az logic workflow list
Extension Name: logic. Version: 0.1.2.`

**Errors:**
```
Unable to deserialize to object: type, KeyError: 'FlowAccessControlConfiguration'
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 1430, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
python3.6/site-packages/msrest/serialization.py, ln 1588, in deserialize_data
    obj_type = self.dependencies[data_type]
KeyError: 'FlowAccessControlConfiguration'

...

python3.6/site-packages/msrest/serialization.py, ln 1588, in deserialize_data
    obj_type = self.dependencies[data_type]
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: 'FlowAccessControlConfiguration'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login
- `az account set --subscription XXXX
- `az logic workflow list`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.16.0

Extensions:
logic 0.1.2

```

**Comment by yonzhan** [comment]
logic

**Comment by RakeshMohanMSFT** [comment]
@martincoetzer We sincerely apologies for the delay, can you upgrade to the latest version of az cli [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and try running the command again.
