### ISSUE TITLE
Deploy models from az ml deploy using custom base images 

### ISSUE THREAD

**Issue by prateekchawla** [Azure/azure-cli-extensions#3127]
### Extension name (the extension in question)
ml

### Description of issue (in as much detail as possible)
We have our custom model images built already in azure container registry. We need to utilize those images with our az ml deploy command.
Currently, when we are doing` az ml model deploy -n $serviceName --ct $computename  --bi $baseimagename --ir abc.azurecr.io` 
The error says to pass the model names & entry scripts & when I do so, something like below command
`az ml model deploy -n $serviceName --ct $computename  --bi $baseimagename --ir abc.azurecr.io   -m $modelName1 --ic ./inferenceconfig.json --dc ./deploymentconfig.json `

It throws error 
> Error converting value \\"abc.azurecr.io\\" to type \'Microsoft.MachineLearning.EnvironmentManagement.Contracts.ContainerRegistry\'. Path \'docker.baseImageRegistry\', line 1, position 2532.","target":"docker.baseImageRegistry"}],

I am not sure if this is the right way to do this, but need a solution which helps to deploy models in aks using custom base images
-----

**Comment by yungezz** [comment]
route to appropriate team

**Comment by snpdev** [comment]
Just a hunch... In [Deploy a model using a custom Docker base image](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-custom-docker-image#use-an-image-with-the-machine-learning-cli), we see the example `az cli` as follows:
```
az ml model deploy -n myservice -m mymodel:1 --ic inferenceconfig.json --dc deploymentconfig.json --ct akscomputetarget
```
Notice that there are no `--bi` and  `--ir` options.

The documentation states, "Before deploying a model using the Machine Learning CLI, create an environment that uses the custom image. Then create an inference configuration file that references the environment. " In the example inference configuration, the base image is referenced:
```
"baseImage": "mcr.microsoft.com/azureml/o16n-sample-user-base/ubuntu-miniconda:latest",
```

**Comment by shivanissambare** [comment]
Yup, 
you'd need to create an environment that uses the custom image. Then create an inference configuration file that references the environment. You can also define the environment directly in the inference configuration file.

inference config example: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-and-where?tabs=python#define-an-inference-configuration

Use an image with the Machine Learning CLI: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-custom-docker-image#use-an-image-with-the-machine-learning-cli

**Comment by shivanissambare** [comment]
Please let us know if you have any other questions.

**Comment by shivanissambare** [comment]
#please-close

**Comment by prateekchawla** [comment]
Thanks @shivanissambare
