### ISSUE TITLE
db-up does not return correct PostgreSQL host for Azure Government

### ISSUE THREAD

**Issue by ryanhofdotgov** [Azure/azure-cli-extensions#3143]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

db-up

### Description of issue (in as much detail as possible)

-----

When I run:
```
$ az cloud set --name AzureUSGovernment
$ az postgres show-connection-string \
    --server-name myserver \
    --query host \
    -o tsv
```
I expect to get:
```
myserver.postgres.database.usgovcloudapi.net
```

Instead, I incorrectly get the commercial Azure (`AzureCloud`) host:
```
myserver.postgres.database.azure.com
```

**Comment by yonzhan** [comment]
db-up

**Comment by Juliehzl** [comment]
You need to set your cloud env to AZURE_US_GOV_CLOUD with `az cloud set -n AZURE_US_GOV_CLOUD` and run related commands
