### ISSUE TITLE
How to specify "Latest" in --secret-version argument?

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli-extensions#3151]
## Describe the bug

When viewed in Azure Portal, custom domain functionality of AFD recommends using latest version of certificate to avoid service interruption:

![image](https://user-images.githubusercontent.com/1999365/110867031-f4d2aa80-827a-11eb-8b64-fb35bba784e2.png)

Apparently, it's impossible to specify "Latest" version from the CLI.

**Command Name**
```
az network front-door frontend-endpoint enable-https

Extension Name: front-door. Version: 1.0.11.
```

**Errors:**

## To Reproduce:

Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Either

`az network front-door frontend-endpoint enable-https --resource-group myrg --front-door-name myfd --name domainname --certificate-source AzureKeyVault --vault-id /subscriptions/my-sub-id/resourceGroups/myrg/providers/Microsoft.KeyVault/vaults/mykv --secret-name cert--ssl-frontdoor`

or 

`az network front-door frontend-endpoint enable-https --resource-group myrg --front-door-name myfd --name domainname --certificate-source AzureKeyVault --vault-id /subscriptions/my-sub-id/resourceGroups/myrg/providers/Microsoft.KeyVault/vaults/mykv --secret-name cert--ssl-frontdoor --secret-version Latest`

or 

`az network front-door frontend-endpoint enable-https --resource-group myrg --front-door-name myfd --name domainname --certificate-source AzureKeyVault --vault-id /subscriptions/my-sub-id/resourceGroups/myrg/providers/Microsoft.KeyVault/vaults/mykv --secret-name cert--ssl-frontdoor --secret-version ""`

result in

`ERROR: usage error: --certificate-source AzureKeyVault --vault-id ID --secret-name NAME --secret-version VERSION`

## Expected Behavior

Use latest version of the certificate.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.20.0

Extensions:
aks-preview 0.5.5
front-door 1.0.11
log-analytics 0.2.1
resource-graph 1.1.0

```

**Comment by yonzhan** [comment]
front-door

**Comment by t-bzhan** [comment]
Just update the front-door extension to 1.0.13, the secret version parameter is now optional and your certificate will be auto-rotated when a new version of secret generated if secret version is not specified.

**Comment by mossywell** [comment]
Note for anyone reading this: if you find it still failing, update the front-door extension as you are probably still running an old version:
`az extension add --name "front-door" --upgrade`
Then it will work.
