### ISSUE TITLE
Connection error when listing targets in CLI

### ISSUE THREAD

**Issue by cgranade** [Azure/azure-cli-extensions#3167]
(Transferring issue reported by @giobb from https://github.com/microsoft/Quantum/issues/466.)

Hi everyone

I always get the issue below on my work machine. This machine is the standard issue that's connecting to corpnet via MS VPN from home. It doesn't happen on my personal machine though. If it's not Quantum-CLI related, I'm just wondering why it's only on this particular subcommand, (the **workspace set** obviously works)

![Quantum - another issue](https://user-images.githubusercontent.com/15137038/107689280-7aa00d80-6c5d-11eb-8ca5-466192785d5b.png)

Cheers!
gio

**Comment by yonzhan** [comment]
quantum

**Comment by giobb** [comment]
This is already working for me

**Comment by ricardo-espinoza** [comment]
Resolving this issue since it has been fixed with newer releases of the extension.
