### ISSUE TITLE
Note is misleading

### ISSUE THREAD

**Issue by pjboardman** [Azure/azure-cli-extensions#3203]
The note at the top of this page states:
"Note

This reference is part of the application-insights extension for Azure CLI and requires version 2.0.79 or higher. The extension will automatically install the first time you run an az monitor app-insights component command. Learn more about extensions."

However, I am running `az monitor app-insights component create` in an Azure Devops AzureCLI@2 task (az cli v2.20.0) and the extension is not automatically installed. I still have to manually install the extension

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 333d37d2-61e2-0184-d253-157ee236439c
* Version Independent ID: 9b0e976f-3cb5-e813-9f33-e9cea7a8df8c
* Content: [az monitor app-insights component](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights/component?view=azure-cli-latest#ext_application_insights_az_monitor_app_insights_component_create)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/component.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/component.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by kairu-ms** [comment]
Automatically installation is available now.
