### ISSUE TITLE
How to update vendored_sdks with python track2 package?

### ISSUE THREAD

**Issue by fenwickt** [Azure/azure-cli-extensions#3208]
Hi,

I'm trying to update existing CLI extension (resource-graph) with the new vendored sdk, but azdev tool just doesn't work. Could you please advise a proper way to update the extension to use the newest sdk version?

There is a python package that was generated using autorest track2 configuration. But since it has different structure (_version.py instead of version.py, etc.), azdev doesn't recognize it as an installable package and fails with "Unable to find client files."
Package is located here: https://pypi.org/project/azure-mgmt-resourcegraph/

Also the docs are great on how to create a new extension, but seems like no docs are there for how to update the existing extension to use the new sdk package. Could you please consider adding such a section?

**Comment by yonzhan** [comment]
update vendored_sdks

**Comment by jsntcy** [comment]
> Hi,
> 
> I'm trying to update existing CLI extension (resource-graph) with the new vendored sdk, but azdev tool just doesn't work. Could you please advise a proper way to update the extension to use the newest sdk version?
> 
> There is a python package that was generated using autorest track2 configuration. But since it has different structure (_version.py instead of version.py, etc.), azdev doesn't recognize it as an installable package and fails with "Unable to find client files."
> Package is located here: https://pypi.org/project/azure-mgmt-resourcegraph/
> 
> Also the docs are great on how to create a new extension, but seems like no docs are there for how to update the existing extension to use the new sdk package. Could you please consider adding such a section?

@fenwickt, thanks for your good suggestion and we'll update the docs. As a quick guidance for you, you can copy the track 2 SDK from `https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/resources/azure-mgmt-resourcegraph/azure/mgmt` to replace SDK in `https://github.com/Azure/azure-cli-extensions/tree/master/src/resource-graph/azext_resourcegraph/vendored_sdks` (delete all files and folders under `vendored_sdks` first before copying track 2 SDK here)

**Comment by fenwickt** [comment]
Thank you! Deleting everything including the pycache before copying the SDK worked.
