### ISSUE TITLE
Not able to deploy AzureDatabricksDeltaLake for ADF linked service by az datafactory linked-service create

### ISSUE THREAD

**Issue by miohtsub** [Azure/azure-cli-extensions#3223]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az datafactory linked-service create

### Description of issue (in as much detail as possible)
AzureDatabricksDeltaLake has been newly added as a liked service resource in ADF and it is currently not supported with Azure CLI deployment.
Can you please consider if AzureDatabricksDeltaLake can be deployed with Azure CLI?

-----

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look?
