### ISSUE TITLE
Az CLI Issues

### ISSUE THREAD

**Issue by samb0803** [Azure/azure-cli-extensions#3252]
## Describe the bug

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.7.`

**Errors:**
```
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 660, in execute
    raise ex
cli/core/commands/__init__.py, ln 723, in _run_jobs_serially
...
cli/core/commands/__init__.py, ln 694, in _run_job
    result = cmd_copy(params)
cli/core/commands/__init__.py, ln 331, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 811, in default_command_handler
    return op(**command_args)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1739, in aks_update
    azure_keyvault_secrets_provider_addon_profile = instance.addon_profiles.get(
AttributeError: 'NoneType' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group {} --name {} --auto-upgrade-channel {} --subscription {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.9
Installer: HOMEBREW

azure-cli 2.21.0

Extensions:
aks-preview 0.5.7

```

**Comment by yonzhan** [comment]
route to service team

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14287

**Comment by RakeshMohanMSFT** [comment]
@samb0803 We sincerely apologies for the delay, can you try upgrading to the latest version of az cli [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and try running the command again?
