### ISSUE TITLE
Az SSH error when using private key path

### ISSUE THREAD

**Issue by khaosdoctor** [Azure/azure-cli-extensions#3283]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 0.1.4.`

**Errors:**
```
stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 660, in execute
    raise ex
cli/core/commands/__init__.py, ln 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 716, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/ssh/azext_ssh/custom.py, ln 107, in _check_or_create_public_private_files
    if not os.path.isfile(public_key_file):
az/lib/python3.6/genericpath.py, ln 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm -g {} --private-key-file {} -n {}`

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.20.0 *

Extensions:
ssh 0.1.4

```

**Comment by yungezz** [comment]
hi @N6UDP could you look at the issue? thanks

**Comment by N6UDP** [comment]
@khaosdoctor you need to specify the public key file too -- that said we should probably produce a more reasonable error / validate the args before we get to that point so I will go fix that.

**Comment by N6UDP** [comment]
fwiw, you also don't need to specify private key (only public key is required) in the event your key is in ssh-agent.  #3286 adds a user facing error for this.

**Comment by N6UDP** [comment]
@yungezz once #3286 is in this can be resolved (I don't have perms to do so)

**Comment by khaosdoctor** [comment]
> @khaosdoctor you need to specify the public key file too -- that said we should probably produce a more reasonable error / validate the args before we get to that point so I will go fix that.

Even if I have my public key set up on the VM as well? I may be getting it wrong, but then the flow gets a bit confusing to me, since all that's needed to SSH into the VM is the private key file, isn't it?

**Comment by N6UDP** [comment]
@khaosdoctor the public key is sent to Azure AD and then signed to create an openssh certificate which is presented to a VM with AAD VM login setup.  If you've directly provisioned a public key on the VM then that's not the AAD auth flow and this extension is not what you want to be calling into.  A private key alone is not sufficient for the AAD flow.

**Comment by N6UDP** [comment]
There was a discussion I had about the fact the "ssh" name of the extension is a bit misleading as the extension is exclusively for AAD login - see https://docs.microsoft.com/en-us/azure/virtual-machines/linux/login-using-aad for more details.

**Comment by khaosdoctor** [comment]
Oh ok that clarified things to me! I'm logging in as plain SSH, I do not intend to have AAD integration. Thanks a lot for explaining!

**Comment by N6UDP** [comment]
@yungezz / @khaosdoctor now that the PR is in we can close this :)

**Comment by khaosdoctor** [comment]
Closing :D

**Comment by N6UDP** [comment]
We now also attempt to find a public key file as part of #3698
