### ISSUE TITLE
Unable to run kollect command

### ISSUE THREAD

**Issue by sunilthemaster** [Azure/azure-cli-extensions#3294]
## Describe the bug

**Command Name**
`az aks kollect
Extension Name: aks-preview. Version: 0.4.70.`

**Errors:**
```
Command '['kubectl', '--kubeconfig', '/tmp/tmph1p1bims', 'get', 'apd', '-n', 'aks-periscope', '--no-headers']' returned non-zero exit status 1.
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 231, in invoke
    cmd_result = self.invocation.execute(args)
...
    universal_newlines=True
az/lib/python3.6/subprocess.py, ln 356, in check_output
    **kwargs).stdout
az/lib/python3.6/subprocess.py, ln 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['kubectl', '--kubeconfig', '/tmp/tmph1p1bims', 'get', 'apd', '-n', 'aks-periscope', '--no-headers']' returned non-zero exit status 1.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks kollect -g {} -n {} --storage-account {}`

## Environment Summary
```
Linux-4.15.0-1113-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.22.0 *

Extensions:
aks-preview 0.4.70
resource-graph 1.1.0
image-copy-extension 0.2.8
ai-examples 0.2.5
ssh 0.1.4

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by RakeshMohanMSFT** [comment]
This is working with the latest version of azure cli. Please reopen if you are still facing the issue
![image](https://user-images.githubusercontent.com/49954584/211055636-a8afacf4-21c6-49e4-995f-7ca6c9c1d700.png)
