### ISSUE TITLE
az network front-door routing-rule update removes caching configuration

### ISSUE THREAD

**Issue by fdebuire** [Azure/azure-cli-extensions#3314]
### Extension name (the extension in question)
front-door

### Description of issue (in as much detail as possible)
I am using ```az network front-door routing-rule update``` to add a rules engine to a routing rule, using ```--rules-engine``` parameter, to an already existing routing-rule and the caching configuration is also updated to ```null```.

What I am expecting is that the routing rule will only be updated with what was passed in parameters, leaving the caching configuration untouched.

```
az network front-door routing-rule update \
    --front-door-name "${FRONT_DOOR_NAME}" \
    --resource-group "${RESOURCE_GROUP_NAME}" \
    --name ${routing_rule} \
    --rules-engine ${RULES_ENGINE_NAME}
```

$ az --version
azure-cli                         2.22.1
Extensions:
front-door                        1.0.14

-----

**Comment by yonzhan** [comment]
route to service team
