### ISSUE TITLE
Potential Bug: log-analytics-solution extension is getting Unknown error while trying to delete a solution. 

### ISSUE THREAD

**Issue by tzachie** [Azure/azure-cli-extensions#3316]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
GA Log Analytics Solution

### Description of issue (in as much detail as possible)
while trying to delete a solution operation fails with Unknown error.

-----

tzachi@Azure:~$ az monitor log-analytics solution delete -g la-pl -n AgentHealthAssessment
Command group 'monitor log-analytics solution' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus

#Command with debug flag

tzachi@Azure:~$ az monitor log-analytics solution delete -g la-pl -n AgentHealthAssessment --debug
cli.knack.cli: Command arguments: ['monitor', 'log-analytics', 'solution', 'delete', '-g', 'la-pl', '-n', 'AgentHealthAssessment', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f07c6335c80>, <function OutputProducer.on_global_arguments at 0x7f07c62667b8>, <function CLIQuery.on_global_arguments at 0x7f07c62818c8>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'monitor': ['azure.cli.command_modules.monitor', 'azext_log_analytics_solution']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: monitor                   0.128        32       132
cli.azure.cli.core: Total (1)                 0.128        32       132
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: log-analytics-solution      0.016         3         5  /home/tzachi/.azure/cliextensions/log-analytics-solution
cli.azure.cli.core: ai-examples               0.142         1         1  /opt/az/lib/python3.6/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (2)                 0.157         4         6
cli.azure.cli.core: Loaded 34 groups, 138 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : monitor log-analytics solution delete
cli.azure.cli.core: Command table: monitor log-analytics solution delete
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f07c5dbea60>]
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f07c5d55048>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f07c5d55e18>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f07c5d55f28>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f07c5ced0d0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f07c6266840>, <function CLIQuery.handle_query_parameter at 0x7f07c6281950>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f07c5d55ea0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f07c5ced048>]
Command group 'monitor log-analytics solution' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Are you sure you want to perform this operation? (y/n): y
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=OperationsManagementClient
msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
cli.azure.cli.core.commands.client_factory: Adding custom headers to the client:
cli.azure.cli.core.commands.client_factory:     'x-ms-client-request-id': '5e38eac6-a854-11eb-a7d1-0a580af4b830'
cli.azure.cli.core.commands.client_factory:     'CommandName': 'monitor log-analytics solution delete'
cli.azure.cli.core.commands.client_factory:     'ParameterSetName': '-g -n --debug'
msrest.service_client: Accept header absent and forced to application/json
cli.azure.cli.core.adal_authentication: AdalAuthentication.signed_session invoked by Track 1 SDK
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2206
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2206
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/a55da7c0-c08f-45dc-95f9-98cde685719d/resourcegroups/la-pl/providers/Microsoft.OperationsManagement/solutions/AgentHealthAssessment?api-version=2015-11-01-preview'
msrest.http_logger: Request method: 'DELETE'
msrest.http_logger: Request headers:
msrest.http_logger:     'accept-language': 'en-US'
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'User-Agent': 'python/3.6.10 (Linux-4.15.0-1113-azure-x86_64-with-debian-10.2) msrest/0.6.21 cloud-shell/1.0 msrest_azure/0.6.3 azure-mgmt-operationsmanagement/0.1.0 Azure-SDK-For-Python AZURECLI/2.22.0 (DEB)'
msrest.http_logger: Request body:
msrest.http_logger: None
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "DELETE /subscriptions/a55da7c0-c08f-45dc-95f9-98cde685719d/resourcegroups/la-pl/providers/Microsoft.OperationsManagement/solutions/AgentHealthAssessment?api-version=2015-11-01-preview HTTP/1.1" 204 0
msrest.http_logger: Response status: 204
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-deletes': '14999'
msrest.http_logger:     'x-ms-request-id': '67f40dc0-4fb1-4fff-baa9-c0d8514807b2'
msrest.http_logger:     'x-ms-correlation-request-id': '67f40dc0-4fb1-4fff-baa9-c0d8514807b2'
msrest.http_logger:     'x-ms-routing-request-id': 'WESTUS:20210428T190312Z:67f40dc0-4fb1-4fff-baa9-c0d8514807b2'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Date': 'Wed, 28 Apr 2021 19:03:11 GMT'
msrest.http_logger: Response content:
msrest.http_logger:
msrest.exceptions: Unknown error
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 807, in default_command_handler
    return op(**command_args)
  File "/home/tzachi/.azure/cliextensions/log-analytics-solution/azext_log_analytics_solution/custom.py", line 57, in delete_monitor_log_analytics_solution
    return sdk_no_wait(no_wait, client.delete, resource_group_name=resource_group_name, solution_name=solution_name)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 648, in sdk_no_wait
    return func(*args, **kwargs)
  File "/home/tzachi/.azure/cliextensions/log-analytics-solution/azext_log_analytics_solution/vendored_sdks/operationsmanagement/operations/_solutions_operations.py", line 313, in delete
    **operation_config
  File "/home/tzachi/.azure/cliextensions/log-analytics-solution/azext_log_analytics_solution/vendored_sdks/operationsmanagement/operations/_solutions_operations.py", line 279, in _delete_initial
    raise models.CodeMessageErrorException(self._deserialize, response)
azext_log_analytics_solution.vendored_sdks.operationsmanagement.models._models_py3.CodeMessageErrorException: Unknown error

cli.azure.cli.core.azclierror: Unknown error
az_command_data_logger: Unknown error
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f07c5dbec80>]
cli.__main__: Command ran in 5.139 seconds (init: 0.161, invoke: 4.979)

![image](https://user-images.githubusercontent.com/32248613/116460384-ae0f3300-a86f-11eb-8bca-0ba32d562111.png)
![image](https://user-images.githubusercontent.com/32248613/116460444-bf583f80-a86f-11eb-9270-5b5f87a08a9b.png)

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
Hi @msyyc, this error is caused by service error response is empty. Does SDK need to support it?

**Comment by zhoxing-ms** [comment]
> urllib3.connectionpool: https://management.azure.com:443 "DELETE /subscriptions/a55da7c0-c08f-45dc-95f9-98cde685719d/resourcegroups/la-pl/providers/Microsoft.OperationsManagement/solutions/AgentHealthAssessment?api-version=2015-11-01-preview HTTP/1.1" 204 0
msrest.http_logger: Response status: 204

This issue is because when the return status of service is `204`, the returned response content is empty, resulting in an error in constructing `CodeMessageErrorException`. [code link](https://github.com/Azure/azure-sdk-for-python/blob/release/v3/sdk/operationsmanagement/azure-mgmt-operationsmanagement/azure/mgmt/operationsmanagement/operations/_solutions_operations.py#L278)

However, when I execute the command locally or in `CloudShell`, the return status is always `200`, so this issue cannot be reproduced.
![Screenshot 2021-04-29 151933](https://user-images.githubusercontent.com/16612065/116517740-f119e680-a901-11eb-9362-8e9ae5f18fad.png)

 @dougbrad Hi, could you please help to see why the service sometimes returns the status code of `204`? 
**x-ms-correlation-request-id: 67f40dc0-4fb1-4fff-baa9-c0d8514807b2**

And please help to confirm that when the status code is `204`, the response content is empty, is this in line with expectations? 
If so, we may need to consider modifying the processing logic of the track 1 SDK for status `204`, or consider migrating the SDK to track 2.

**Comment by tzachie** [comment]
Seem customer didn't use the full solution name (that should be including the workspace name with the solution name).
thank you @dougbrad.

Correct syntax : tzachi@Azure:~$ az monitor log-analytics solution delete -g la-pl -n "AgentHealthAssessment**(tzachieworkspace-WE)**" --debug

Incorrect syntax:tzachi@Azure:~$ az monitor log-analytics solution delete -g la-pl -n AgentHealthAssessment

So now we just need to figure the correct http status to return in that case and maybe consider adjusting the error to more understandable.

**Comment by tzachie** [comment]
As feedback provided in
https://github.com/Azure/azure-cli-extensions/pull/3309
"Considering further - it is likely this RP will start deprecation process in next 6 months, the replacement functionality might GA in this time. So it might be best to leave this as experimental."
