### ISSUE TITLE
Azure-ml-cli error when get toekn

### ISSUE THREAD

**Issue by tianchijushi** [Azure/azure-cli-extensions#3339]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Azure-ml-cli 1.0.0a1

### Description of issue (in as much detail as possible)
All the az ml command failed with error below, this error is not there when using public preview azure-ml-cli version

AzureCliCredential.get_token failed: The system cannot find the path specified.
{
  ****,
  "expiresOn": "2021-05-06 00:37:21.955898",
  "subscription": "5f08d643-1910-4a38-a7c7-84a39d4f42e0",
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "tokenType": "Bearer"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/identity/_internal/decorators.py", line 27, in wrapper
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/identity/_credentials/azure_cli.py", line 58, in get_token
azure.core.exceptions.ClientAuthenticationError: The system cannot find the path specified.
{
  ****,
  "expiresOn": "2021-05-06 00:37:21.955898",
  "subscription": "5f08d643-1910-4a38-a7c7-84a39d4f42e0",
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "tokenType": "Bearer"
}

The system cannot find the path specified.
{
  ****,
  "expiresOn": "2021-05-06 00:37:21.955898",
  "subscription": "5f08d643-1910-4a38-a7c7-84a39d4f42e0",
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "tokenType": "Bearer"
}
-----
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/8260446/117252626-15daf600-adfb-11eb-9ae0-c2aaadb21611.png)

**Comment by yungezz** [comment]
route to appropriate team

**Comment by singankit** [comment]
@tianchijushi can you please the exact command and you are running which causes this error ? Also can you please share the output of **az extension list** command
