### ISSUE TITLE
What happened to the command group "graph shared-group" in resource-graph 2.0.0?

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-cli-extensions#3384]
### Extension name (the extension in question)
resource-graph 2.0.0

### Description of issue (in as much detail as possible)

What happened to the command group "graph shared-group" in resource-graph 2.0.0?
That command group was present in 1.1.0. Removal is not documented in history.rst.

**Comment by yonzhan** [comment]
route to service team

**Comment by dramuy** [comment]
This is resolved. We have published latest version that unblocks usage of shared-query. 
![image](https://user-images.githubusercontent.com/7453992/123855386-b79b3280-d8d4-11eb-941d-cd947d7ec3a3.png)
