### ISSUE TITLE
[az-cli-ml] MemoryError when deploying model locally

### ISSUE THREAD

**Issue by oottka** [Azure/azure-cli-extensions#3404]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
azure-cli-ml 1.28.0

### Description of issue (in as much detail as possible)

When deploying a model with `az ml deploy` I get an MemoryError. Full relevant debug output can be found [here](https://gist.github.com/oottka/d38163b31a5a672df0cd418ef0a13f1a).

Steps to reproduce:

1) In a python console, run

```python
import torch
model = torch.hub.load('pytorch/vision:v0.9.0', 'resnet101', pretrained=True)
```

2) `az ml model register --n resnet101_pytorch -p <path-to-downloaded-resnet-pth-file>`
3) `az ml model deploy --debug --verbose -n resnet101service -m resnet101_pytorch:1 --overwrite --ic simpleinferencingconfiguration.json --dc deploymentconfig.json`
4) The command results in `{'Azure-cli-ml Version': '1.28.0', 'Error': MemoryError()}`

The configuration files can be found [here](https://gist.github.com/oottka/d38163b31a5a672df0cd418ef0a13f1a).

Environment:

Tested on Windows 10, Docker 20.10.6, WSL2 Docker backend,

```az --version
azure-cli                         2.23.0

core                              2.23.0
telemetry                          1.0.6

Extensions:
azure-cli-ml                      1.28.0
```

Also tested on Ubuntu 20.04 inside WSL2, Docker 19.03.8, with same results.

At no point during execution is RAM usage exceptionally high or near the RAM capacity.

-----

**Comment by harneetvirk** [comment]
From the logs, it seems the container is experiencing the MemoryError while copying files/folder to a container's filesystem as part of copying the local assets. Could you try to passing --memory-gb flag with some higher configuration in the deployment configuration please?

Next week, we are shipping a preview version of v2 CLI extension for ml, if you are willing to upgrade to v2 ml extension (with the caveat that it is not GA, whereas the v1 CLI is).

**Comment by shivanissambare** [comment]
thanks Harneet!
@oottka does this solve your issue?

**Comment by shivanissambare** [comment]
please feel free to re-open the issue, if you have more questions!

**Comment by shivanissambare** [comment]
#please-close
