### ISSUE TITLE
`az ml job create` fails with non-descriptive error message

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azure-cli-extensions#3436]
## Describe the bug

**Command Name**
`az ml job create
Extension Name: ml. Version: 2.0.0a1.`

**Errors:**
 
![image](https://user-images.githubusercontent.com/54814569/119680259-ddc14480-bdf5-11eb-98ff-9bf704441950.png)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
git clone https://github.com/Azure/azureml-examples
gh pr checkout 542
cd cli
az ml job create -f jobs/train/r/accident-prediction/accident_r_job.yml
```

## Expected Behavior

more descriptive error message

## Environment Summary
```
Linux-5.4.0-1047-azure-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.22.1 *

Extensions:
ml 2.0.0a1

```

**Comment by needuv** [comment]
File not found errors have been made more specific to specify for which entity the file cannot be found.
