### ISSUE TITLE
remove "Code" column from table view

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azure-cli-extensions#3444]
## Describe the bug

![image](https://user-images.githubusercontent.com/54814569/120088316-0bcbb080-c0a4-11eb-98b8-d0e5cb435b72.png)

even on a widescreen monitor, the `az ml job list` command is not very pretty (see above). I think we should remove the `Code` column as a simple fix, and more rigorously ensure that our list/show outputs are useful from the CLI. also, this command seems to trigger other `az account` commands when running `az feedback`

**Command Name**
`az ml job list -r 5
Extension Name: ml. Version: 2.0.0a1.`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ml job list -r {}`

## Environment Summary
```
Linux-5.10.25-linuxkit-x86_64-with-debian-10.9
Python 3.6.10
Installer: DEB

azure-cli 2.24.0

Extensions:
ml 2.0.0a1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by paulshealy1** [comment]
Thanks for the feedback! We have some work in progress to update the default set of columns for tabular output.
