### ISSUE TITLE
az next failed to connect  to 'https://cli-recommendation.azurewebsites.net/api/RecommendationService' with status code '500'

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-cli-extensions#3478]
## Describe the bug

`az next` returns: 
az next failed to connect  to 'https://cli-recommendation.azurewebsites.net/api/RecommendationService' with status code '500'

**Command Name**
`az next
Extension Name: next. Version: 0.1.2.`

**Errors:**
```
Failed to connect to 'https://cli-recommendation.azurewebsites.net/api/RecommendationService' with status code '500' and reason 'Internal Server Error'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az next --debug`

cli.knack.cli: Command arguments: ['next', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Init colorama.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x030840B8>, <function OutputProducer.on_global_arguments at 0x031EFF10>, <function CLIQuery.on_global_arguments at 0x03215B20>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'next': ['azext_next']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Loading all modules and extensions
cli.azure.cli.core: Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'config', 'configure', 'consumption', 'container', 'cosmosdb', 'databoxedge', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'marketplaceordering', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acr                       0.014        27       113
cli.azure.cli.core: acs                       0.361         8        53
cli.azure.cli.core: advisor                   0.003         3         6
cli.azure.cli.core: ams                       0.007        20        90
cli.azure.cli.core: apim                      0.006         9        50
cli.azure.cli.core: appconfig                 0.006         7        33
cli.azure.cli.core: appservice                0.014        62       221
cli.azure.cli.core: aro                       0.012         1         7
cli.azure.cli.core: backup                    0.006        13        49
cli.azure.cli.core: batch                     0.051        31        90
cli.azure.cli.core: batchai                   0.006        10        32
cli.azure.cli.core: billing                   0.014        19        52
cli.azure.cli.core: botservice                0.007        12        42
cli.azure.cli.core: cdn                       0.013        39       132
cli.azure.cli.core: cloud                     0.004         1         7
cli.azure.cli.core: cognitiveservices         0.005         5        17
cli.azure.cli.core: config                    0.003         2         7
cli.azure.cli.core: configure                 0.004         3         9
cli.azure.cli.core: consumption               0.006         8         9
cli.azure.cli.core: container                 0.005         1        11
cli.azure.cli.core: cosmosdb                  0.014        36       140
cli.azure.cli.core: databoxedge               0.011         5        27
cli.azure.cli.core: deploymentmanager         0.005         7        30
cli.azure.cli.core: dla                       0.008        23        62
cli.azure.cli.core: dls                       0.008         7        41
cli.azure.cli.core: dms                       0.005         3        22
cli.azure.cli.core: eventgrid                 0.007        18        61
cli.azure.cli.core: eventhubs                 0.007        14        51
cli.azure.cli.core: extension                 0.003         1         7
cli.azure.cli.core: feedback                  0.002         1         1
cli.azure.cli.core: find                      0.003         1         1
cli.azure.cli.core: hdinsight                 0.006         7        36
cli.azure.cli.core: interactive               0.001         1         1
cli.azure.cli.core: iot                       0.033        16        71
cli.azure.cli.core: keyvault                  0.011        19       117
cli.azure.cli.core: kusto                     0.004         3        14
cli.azure.cli.core: lab                       0.007        11        34
cli.azure.cli.core: managedservices           0.004         3         8
cli.azure.cli.core: maps                      0.003         3         7
cli.azure.cli.core: marketplaceordering       0.007         1         2
cli.azure.cli.core: monitor                   0.013        32       133
cli.azure.cli.core: natgateway                0.005         3         6
cli.azure.cli.core: netappfiles               0.041        13        54
cli.azure.cli.core: network                   0.062       135       622
cli.azure.cli.core: policyinsights            0.004         6        12
cli.azure.cli.core: privatedns                0.007        14        66
cli.azure.cli.core: profile                   0.005         2         9
cli.azure.cli.core: rdbms                     0.086        43       188
cli.azure.cli.core: redis                     0.005         4        24
cli.azure.cli.core: relay                     0.005        10        37
cli.azure.cli.core: reservations              0.005         5        12
cli.azure.cli.core: resource                  0.015        37       176
cli.azure.cli.core: role                      0.007        17        61
cli.azure.cli.core: search                    0.005         7        22
cli.azure.cli.core: security                  0.007        36        81
cli.azure.cli.core: servicebus                0.007        17        64
cli.azure.cli.core: servicefabric             0.009        26        75
cli.azure.cli.core: signalr                   0.005         5        16
cli.azure.cli.core: sql                       0.014        42       169
cli.azure.cli.core: sqlvm                     0.006         4        17
cli.azure.cli.core: storage                   0.048        53       246
cli.azure.cli.core: synapse                   0.011        34       143
cli.azure.cli.core: util                      0.004         2         4
cli.azure.cli.core: vm                        0.042        44       225
cli.azure.cli.core: Total (64)                1.116      1052      4225
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: next                      0.006         1         1  C:\Users\dcaro\.azure\cliextensions\next
cli.azure.cli.core: Total (1)                 0.006         1         1
cli.azure.cli.core: Loaded 1042 groups, 4226 commands.
cli.azure.cli.core: next                      1.224         1         1  C:\Users\dcaro\.azure\cliextensions\next
cli.azure.cli.core: Total (1)                 1.224         1         1
cli.azure.cli.core: Loaded 1042 groups, 4226 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : next
cli.azure.cli.core: Command table: next
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x035CEF58>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\xxx\.azure\commands\2021-06-08.17-39-12.next.27884.log'.
az_command_data_logger: command args: next --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x036230B8>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x03633778>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x036337C0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03633850>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x041F8658>]
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x031EFF58>, <function CLIQuery.handle_query_parameter at 0x03215B68>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x03633730>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03633808>, <function handler at 0x046E84F0>]
az_command_data_logger: extension name: next
az_command_data_logger: extension version: 0.1.2
This command is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
urllib3.connectionpool: Starting new HTTPS connection (1): cli-recommendation.azurewebsites.net:443
urllib3.connectionpool: https://cli-recommendation.azurewebsites.net:443 "POST /api/RecommendationService HTTP/1.1" 500 0
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\xxx\.azure\cliextensions\next\azext_next\custom.py", line 38, in handle_next
    recommends = get_recommend_from_api(command_history, request_type,
  File "C:\xxx\.azure\cliextensions\next\azext_next\requests.py", line 39, in get_recommend_from_api
    raise RecommendationError(
azure.cli.core.azclierror.RecommendationError: Failed to connect to 'https://cli-recommendation.azurewebsites.net/api/RecommendationService' with status code '500' and reason 'Internal Server Error'

cli.azure.cli.core.azclierror: Failed to connect to 'https://cli-recommendation.azurewebsites.net/api/RecommendationService' with status code '500' and reason 'Internal Server Error'
az_command_data_logger: Failed to connect to 'https://cli-recommendation.azurewebsites.net/api/RecommendationService' with status code '500' and reason 'Internal Server Error'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x035D00B8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 3.859 seconds (init: 0.633, invoke: 3.226)
telemetry.save: Save telemetry record of length 3160 in cache
telemetry.check: Negative: The C:\xxx\.azure\telemetry.txt was modified at 2021-06-08 17:37:24.541847, which in less than 600.000000 s

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.2

Extensions:
next 0.1.2

```

**Comment by yonzhan** [comment]
az next

**Comment by zhoxing-ms** [comment]
@dcaro Hi, this issue has been fixed, please try it again~
If you have any issues about `az next` in the future, please submit them to [it's own repo](https://github.com/hackathon-cli-recommendation/cli-recommendation/issues)

By the way, due to our recent reorg, we have lost the permission to access related Telemetry, so the recommended data has not been updated for a while.
