### ISSUE TITLE
AKS Node Config Not Consuming Logging Settings

### ISSUE THREAD

**Issue by ericmattingly** [Azure/azure-cli-extensions#3482]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
aks-preview  0.5.17

### Description of issue (in as much detail as possible)

When passing a kubeletconfig file with contents:

{
    "containerLogMaxFiles": 10,
    "containerLogMaxSizeMb": 500
}

to az aks create:

az aks create --name erimatakstest14 --kubernetes-version 1.20.5 --resource-group erimatakstest --kubelet-config .\kubeletconfig.json

The settings are not actually picked up and used

-----

**Comment by ericmattingly** [comment]
I have created a PR to address, not sure why I am unable to link this issue with the PR - https://github.com/Azure/azure-cli-extensions/pull/3483

**Comment by xuto2** [comment]
https://github.com/Azure/azure-cli-extensions/pull/3483

**Comment by yonzhan** [comment]
route to service team

**Comment by palma21** [comment]
PR linked
