### ISSUE TITLE
az postgres up does not create the resource group

### ISSUE THREAD

**Issue by BhargaviAnnadevara-MSFT** [Azure/azure-cli-extensions#3496]
## Describe the bug
**Tutorial link:** [Deploy a Django web app with PostgreSQL in Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/tutorial-python-postgresql-app?tabs=cmd%2Cclone)

It is expected that the `az postgres up` command creates the resource group if it does not already exist, as mentioned in the [doc](https://docs.microsoft.com/en-us/azure/app-service/tutorial-python-postgresql-app?tabs=cmd%2Cclone#3-create-postgres-database-in-azure).

Running this command on Azure CLI version **2.22.1** and `db-up` extension version **0.2.3** works as expected.
![image](https://user-images.githubusercontent.com/44050820/121654952-de2b3200-cabb-11eb-9d67-de07c7d20097.png)

However, this does not work with the latest Azure CLI version **2.24.2** and `db-up` extension version **0.2.3**.

**Command Name**
`az postgres up
Extension Name: db-up. Version: 0.2.3.`

**Errors:**
```
(ResourceGroupNotFound) Resource group 'DjangoPostgres-tutorial-rg-2242' could not be found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Install Azure CLI version `2.24.2`.
- `az postgres up --resource-group {} --location {} --sku-name {} --server-name {} --database-name {} --admin-user {} --admin-password {} --ssl-enforcement {}`

## Expected Behavior
The command should create the specified resource group and proceed with provisioning the postgres db server, as shown in the screenshot above.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.2
azure-cli-ml 1.24.0

Extensions:
azure-cli-ml 1.24.0
azure-devops 0.18.0
azure-iot 0.10.9
db-up 0.2.3
mesh 0.10.6
resource-graph 1.1.0
scheduled-query 0.2.0
spring-cloud 1.1.1

```
## Additional Context
GitHub Issue: https://github.com/MicrosoftDocs/azure-docs/issues/76722

**Comment by yonzhan** [comment]
postgres up

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Juliehzl Confirming this works on the latest version of `db-up` `0.2.4`. Thanks for the fix!
