### ISSUE TITLE
AppService Kubernetes Arc-Extension

### ISSUE THREAD

**Issue by mohsinonxrm** [Azure/azure-cli-extensions#3503]
### Extension name (the extension in question)
az appservice kube

### Description of issue (in as much detail as possible)
Trying to setup an App Service Kubernetes environment by following: https://docs.microsoft.com/en-us/azure/app-service/manage-create-arc-environment

Cluster Config:
3 Raspberry Pi 4 B (Ubuntu 20.04 ARM64) (k3s v1.19.11+k3s1) (1 master, 2 workers)
1 Rock Pi X (Ubuntu 20.04 AMD64) (k3s v1.19.11+k3s1) (1 worker)

I've been able to set up and configure the mixed-arch k3s cluster with Azure Arc, however when creating the App Service Kubernetes environment it fails. The provisioningState never succeeds.

Investigating the pods and logs: exec format error
![image](https://user-images.githubusercontent.com/21046804/121990006-f0be9900-cd51-11eb-8130-125a2111cc94.png)

Looks like I need arm64 versions of the following containers:
mcr.microsoft.com/k8se/app-controller:1.0.20
mcr.microsoft.com/k8se/envoy:1.0.20
mcr.microsoft.com/k8se/fluent-bit:1.0.20
mcr.microsoft.com/azure-functions/kedacore/keda:v2
mcr.microsoft.com/azure-functions/kedacore/keda-metrics-apiserver:v2
mcr.microsoft.com/k8se/img-cacher:1.0.20
mcr.microsoft.com/k8se/http-scaler:1.0.20
mcr.microsoft.com/k8se/activator:1.0.20

Any plans to provide ARM64 versions of the above-mentioned containers?

**Comment by yonzhan** [comment]
route to service team

**Comment by mohsinonxrm** [comment]
@yonzhan , can you please let me know if there's any update on this? or can I even expect any? part of the roadmap, not part of the roadmap? docker buildx or even ACR provides multi-targeting capabilities.

**Comment by yonzhan** [comment]
appservice service team should look into this

**Comment by mohsinonxrm** [comment]
@yonzhan , any update on this?

**Comment by yonzhan** [comment]
@mohsinonxrm app service team could provide update for this.

**Comment by mohsinonxrm** [comment]
@yonzhan , can you mention or have this assigned to someone here, so I can follow up?

**Comment by yonzhan** [comment]
@panchagnula Could you please route to the correct owner for this issue?

**Comment by apwestgarth** [comment]
Hi, I'm the PM Owner of App Service on Kubernetes with Azure Arc.  At this point providing ARM based containers, or supporting deployment onto ARM based Kubernetes Clusters is not supported.  It's an interesting request which we will take customer feedback on.  

We will update the documentation to highlight that we do not support this scenario, to avoid additional customers running into this same issue.
