### ISSUE TITLE
az ssh: infer public key from private key

### ISSUE THREAD

**Issue by roy-work** [Azure/azure-cli-extensions#3519]
### Extension name (the extension in question)

`az ssh`

### Description of issue (in as much detail as possible)

`az ssh` supports providing an SSH private/public keypair via the `-i` and `-p` options. `-p` (the public key) is required. Since `ssh` users almost always store the public key under the same filename as the private key with `.pub` suffixed to the end, could the necessary value for `-p` perhaps be inferred, if `-i` is provided and `-p` is not?

(Alternatively or additionally, it is also possible to compute the public portion of the key from the private key.)

**Comment by yonzhan** [comment]
VM SSH

**Comment by N6UDP** [comment]
Should be fixed in #3698

**Comment by maertendMSFT** [comment]
closing as it is called out as fixed.
