### ISSUE TITLE
az sql mi-arc list returns generic output

### ISSUE THREAD

**Issue by bweissman** [Azure/azure-cli-extensions#3655]
## Describe the bug

**Command Name**
`az sql mi-arc list
Extension Name: arcdata. Version: 0.0.2.`

**Errors:**
This command returns a generic output:

Col
-----
val1
val2

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az sql mi-arc list --namespace {} -o table`

## Expected Behavior

the output should contain the MIs in that namespace

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
account 0.2.1
arcdata 0.0.2
storage-preview 0.7.4
subscription 0.1.4

```

**Comment by yonzhan** [comment]
route to service team

**Comment by twright-msft** [comment]
Thanks for reporting this @bweissman.  It will be fixed in the next release of the extension.  @yonzhan - please close.
