### ISSUE TITLE
az arcdata has mixed up shortened parameters

### ISSUE THREAD

**Issue by bweissman** [Azure/azure-cli-extensions#3656]
## Describe the bug

**Command Name**
`az arcdata dc create`
Extension Name: arcdata. Version: 0.0.2.

same applies to `az sql mi-arc create`

**Errors:**
This command has been ported from azdata arc dc create
The old command used -ns for namespace and -s for subscription
The new command uses -s for namespace and no shortened parameter for subscription

I assume, this is by mistake :)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az arcdata dc create`

## Expected Behavior

the shortened parameters should be in line with other commands as well as previous azdata commands

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
account 0.2.1
arcdata 0.0.2
storage-preview 0.7.4
subscription 0.1.4

```

**Comment by yonzhan** [comment]
route to service team

**Comment by twright-msft** [comment]
Thanks for reporting this @bweissman.  It will be fixed in the next release of the extension.  @yonzhan - please close.

The --namespace parameter will be renamed to --k8s-namespace/-k.
