### ISSUE TITLE
Uploading ML models with spaces in the name causes issues

### ISSUE THREAD

**Issue by meken** [Azure/azure-cli-extensions#3659]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

ml (v2)

### Description of issue (in as much detail as possible)

It is possible to upload model file(s) to an ML workspace through the CLI or yml file using the local_path option. However, if the files contain any spaces in their names, these end up with %2520, causing problems. If the files are uploaded from the GUI, they are stored with %20 which is handled properly. It looks like there's double encoding (space to %20 and then percent sign is encoded to %25 leading to %2520) somewhere in the process.

-----

**Comment by yonzhan** [comment]
route to service team

**Comment by diondrapeck** [comment]
Hi @meken - I wasn't able to reproduce this. Could you please provide some screenshots of your example? Where are you seeing the double encoding - is this in the GUI or in an error or log response?
