### ISSUE TITLE
az arcdata dc debug copy-logs returns error

### ISSUE THREAD

**Issue by bweissman** [Azure/azure-cli-extensions#3660]
## Describe the bug

**Command Name**
`az arcdata dc debug copy-logs
Extension Name: arcdata. Version: 0.0.2.`

**Errors:**
```
validate_copy_logs() missing 1 required positional argument: 'args'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az arcdata dc debug copy-logs --namespace {}`

## Expected Behavior
this should dump the namespace's logs just as `azdata arc dc debug copy-logs --namespace`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
account 0.2.1
arcdata 0.0.2
connectedk8s 1.1.5
customlocation 0.1.2
k8s-configuration 1.0.0
k8s-extension 0.5.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by twright-msft** [comment]
Thanks for reporting this @bweissman.  It will be fixed in the next release of the extension.  @yonzhan - please close.
