### ISSUE TITLE
Unable to upgrade to the latest azure-devops extension (v0.19.0)

### ISSUE THREAD

**Issue by Lddeiva** [Azure/azure-cli-extensions#3668]
### Extension name (the extension in question)

azure-devops

### Description of issue (in as much detail as possible)

The devops cli extension has the latest release tag set to v0.19.0 [Releases · Azure/azure-devops-cli-extension (github.com)](https://github.com/Azure/azure-devops-cli-extension/releases) but we are unable to upgrade to it from v0.18.0. Please investigate the reason why it shows no upgrade available.

![image](https://user-images.githubusercontent.com/61077834/126196723-811a5c2b-5a02-4d9f-a412-6b4578cd02b0.png)

![image](https://user-images.githubusercontent.com/61077834/126196829-feef812a-bce8-4c0e-b56e-a565415955db.png)

 

 

 

 

-----

**Comment by yonzhan** [comment]
route to service team

**Comment by Lddeiva** [comment]
I'm closing this as this is old enough to be closed.
