### ISSUE TITLE
ERROR: Could not grant Managed Identity Operator permission for cluster

### ISSUE THREAD

**Issue by felfa01** [Azure/azure-cli-extensions#3679]
### Extension name (the extension in question)
aks-preview

## Bug description
While running `az aks pod-identity --resource group $AKS_RG --cluster-name $AKS_NAME --namespace $NS --name $name --identity-resource-id /subscriptions/$SUBID/resourceGroups/$UAI_RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/$IDENTITY_NAME ` on a cluster with configured with User-Assigned Managed Identity there is a check done to verify that the AKS Identity has "Managed Identity Operator" role on the Identity we want to include as pod identity. The issue is that it is not enough with having the role on the Resource group of the Identity ($UAI_RG) but you must have it specifically on the Identity resource $IDENTITY_NAME. 

This should be classified as a bug since a resource inherits from its resource group, but the script does take inheritance in account but instead requires the resource to have the role assignment.

### To reproduce:
- Existing AKS Cluster (v1.21.1) running with User-Assigned Managed Identity
- Identity (that you want to add as Pod Identity) created in separate resource group
- Run az aks pod-identity add command on AKS cluster 

### Workarounds:
1.  Assign "Managed Identity Operator" role specifically on resource $IDENTITY_NAME ($UAI_RG is not enough)
2. Assign "User Access Administrator" role for the AKS UAI on $UAI_RG, thus enabling AKS UAI to grant "Managed Identity Operator" role on the resource
-----

**Comment by yonzhan** [comment]
route to service team

**Comment by felfa01** [comment]
@noamichael Seems to be similar to what I experienced, with the role assignment being expected to be on the specific resource rather than granted through inheritance (like it should for you given it is `Contributor `on the whole RG).

**Service team:** Any updates on this? My implemented work-around adds access requirements that I'd rather not grant at this specific level.

**Comment by jobbnas** [comment]
Having the exact same issue, it still tries to do a role assignment even if the cluster identity has "Managed Identity Operator" on subscription level.

Is there a possibility to fix this, so `az aks pod-identity add`  can handle if we set "Managed Identity Operator" for the cluster identity on a Subscription/Resource group-level? 

Setting "Managed Identity Operator" on the specific identity to be used is not really feasible in my case

**Comment by miwithro** [comment]
@bcho can you look into this?

**Comment by bcho** [comment]
Ack, this is because in the cli side, we listed only role assignments at identity level scope: https://github.com/Azure/azure-cli-extensions/blob/cc860fcc385634fb8d503240f41922832d082ba8/src/aks-preview/azext_aks_preview/custom.py#L4162 , where scope is the identity id). In this case we are unable to see the role assignments inherited from resource group / subscription.

I am working on a fix for this case, will post updates here.

cc @norshtein for the kubelet identity issue

**Comment by norshtein** [comment]
The same issue for kubelet identity one. It is checking permission using identity resource ID as the scope, and cannot see the inherited permission. Will fix it..

**Comment by jobbnas** [comment]
Has this been released to aks-preview yet?

**Comment by SatyKrish** [comment]
> Has this been released to aks-preview yet?

Released with `0.5.34` version.

`$ az extension show --name aks-preview --query version`
`"0.5.34"`

**Comment by msanchosoto** [comment]
Hey! 

While trying to solve the issue I used the wrong Manage Identity. Using the same managed identity that was the control plane identity to have Managed Identity Operator at the subscription scope fixed our issue.
