### ISSUE TITLE
Is this deprecation warning correct? (Storage)

### ISSUE THREAD

**Issue by ishepherd** [Azure/azure-cli-extensions#3705]
## Describe the bug

**Command Name**
`az storage blob list
Extension Name: storage-preview. Version: 0.7.1.`

**Errors:**
```
This command has been deprecated and will be removed in future release. Use 'az storage fs file list' instead. For more information go to https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/docs/ADLS%20Gen2.md
The behavior of this command has been altered by the following extension: storage-preview
Next Marker: ...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage blob list --account-name {} -c {} --num-results {}`

## Expected Behavior

No removal warning.

My understanding was that `az storage fs` is only for ADLS enabled storage accounts?

Is there some other command I should use? I just want a listing of the blob container.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
storage-preview 0.7.1

```

**Comment by yonzhan** [comment]
Storage

**Comment by evelyn-ys** [comment]
The deprecation warning is just for ADLS storage accounts. Feel free to keep using `az storage blob list`😊

**Comment by ishepherd** [comment]
@evelyn-rs thanks for quick reply

There may be something to fix here? The warning misleads me to thinking that I am using the wrong command, and that the one I am using will be removed; neither is correct.

**Comment by evelyn-ys** [comment]
> There may be something to fix here? The warning misleads me to thinking that I am using the wrong command, and that the one I am using will be removed; neither is correct.

We may need to specify that the warning message is just for ADLS storage accounts. Thanks for reporting!

**Comment by suineglive13** [comment]
@evelyn-ys Hi there, why was the issue closed?
We use StorageV2 and azure-cli 2.58.0, but I still see that same warning.
