### ISSUE TITLE
ssh extension not working in chinese azure

### ISSUE THREAD

**Issue by Klaas-** [Azure/azure-cli-extensions#3735]
### Extension name (the extension in question)
ssh

### Description of issue (in as much detail as possible)
The Azure-CLI ssh extension is not working properly. The first issue I am running into is that it seems to be using azure global pas service instead of azure china one.
https://github.com/Azure/azure-cli-extensions/blame/main/src/ssh/azext_ssh/custom.py#L53

https://pas.windows.net/CheckMyAccess/Linux/.default should be https://pas.chinacloudapi.cn/CheckMyAccess/Linux/.default according to Azure China support.

Highlighting the author: @fengzhou-msft

Error message:
`AADSTS500011: The resource principal named https://pas.windows.net/CheckMyAccess/Linux was not found in the tenant named [...]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.`

-----

**Comment by yonzhan** [comment]
route to service team

**Comment by N6UDP** [comment]
#3698 should fix this.

**Comment by Klaas-** [comment]
I've left a comment on the PR, you seem to be using the wrong url for china.

**Comment by Klaas-** [comment]
So there were some backend changes, this now works with extension version 0.1.8
