### ISSUE TITLE
enable-addons --addons confcom Error

### ISSUE THREAD

**Issue by prajwal11** [Azure/azure-cli-extensions#3752]
## Describe the bug

**Command Name**
`az aks enable-addons
Extension Name: aks-preview. Version: 0.4.22.`

**Errors:**
```
'confcom'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1958, in aks_enable_addons
    workspace_resource_id=workspace_resource_id, subnet_name=subnet_name, no_wait=no_wait)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1998, in _update_addons
    addon = ADDONS[addon_arg]
KeyError: 'confcom'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --addons {} --name {} --resource-group {}`

## Environment Summary
```
Linux-5.4.0-80-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.14.2 *

Extensions:
aks-preview 0.4.22

```

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@prajwal11 We sincerely apologies for the delay. Can you try to upgrade to the latest version of Az cli [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)? it should work then.
