### ISSUE TITLE
aks-preview: az aks update --enable-pod-identity fails with 'Bad Request'

### ISSUE THREAD

**Issue by markrzasa** [Azure/azure-cli-extensions#3807]
### Description of issue

Running the following command using a cluster that does not have an autoUpgradeProfile configured fails with a BadRequest error:
`az aks update -n cluster-name -g cluster-resource-group --enable-managed-identity --enable-pod-identity`

Here is the error:
`ERROR: (BadRequest) Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features.`

The problem may be caused by this if block:
https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azext_aks_preview/custom.py#L1793

If this if block is commented out the command succeeds.

**Comment by yonzhan** [comment]
route to service team

**Comment by markrzasa** [comment]
In case it helps, the following commit looks like it may fix this issue:
https://github.com/Azure/azure-cli-extensions/pull/3808/files

**Comment by markrzasa** [comment]
This problem looks to be fixed in version 0.5.31 of the aks-preview extension.

**Comment by markrzasa** [comment]
This problem looks to be fixed in version 0.5.31 of the aks-preview extension.
