### ISSUE TITLE
image-copy resets image hyper-v generation to V1

### ISSUE THREAD

**Issue by sbonds** [Azure/azure-cli-extensions#3826]
### Extension name (the extension in question)

image-copy

### Description of issue (in as much detail as possible)

Why copying an image created for Hyper-V generation 2 VMs the resulting copy made with the image-copy extension has its generation reset back to Hyper-V generation 1.

### Workaround

Avoid using `--cleanup`. Export the image ARM template, change the hyper-V generation, delete the copied image, and deploy the ARM template with the correct generation.

**Comment by zhoxing-ms** [comment]
This issue seems to be duplicated with https://github.com/Azure/azure-cli-extensions/issues/2476, so close this one and let's focus on another issue for discussion

**Comment by sbonds** [comment]
I agree-- looks like a perfect duplicate. Sorry I missed that in my pre-submission search for existing issues.
