### ISSUE TITLE
'enrollment-group' is not in the 'az iot dps' command group

### ISSUE THREAD

**Issue by NissanAloni** [Azure/azure-cli-extensions#387]
Trying to run these commands with latest AZ CLI gives the following error:
az iot dps: 'enrollment-group' is not in the 'az iot dps' command group. See 'az iot dps --help'.

AZ CLI version is:
c:\&gt;az --version
azure-cli (2.0.49)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a3283c-e190-c2a7-fc50-41d9ba6a8d2e
* Version Independent ID: 473e67d0-b090-c5c2-285c-7c194b3af844
* Content: [az iot dps enrollment-group](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/dps/enrollment-group?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/dps/enrollment-group.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/dps/enrollment-group.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rsre** [comment]
I'm having the same problem. `az -v` gives the following answer:

azure-cli                         2.0.61

acr                                2.2.3
acs                               2.3.20
advisor                            2.0.0
ams                                0.4.3
appservice                        0.2.16
backup                             1.2.2
batch                              4.0.0
batchai                            0.4.8
billing                            0.2.1
botservice                         0.1.9
cdn                                0.2.1
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.15
core                              2.0.61
cosmosdb                           0.2.9
dla                                0.2.5
dls                                0.1.8
dms                                0.1.3
eventgrid                          0.2.2
eventhubs                          0.3.4
extension                          0.2.4
feedback                           2.1.4
find                               0.3.1
hdinsight                          0.3.2
interactive                        0.4.2
iot                                0.3.7
iotcentral                         0.1.6
keyvault                          2.2.13
kusto                              0.2.1
lab                                0.1.6
maps                               0.3.4
monitor                           0.2.11
network                            2.3.5
nspkg                              3.0.3
policyinsights                     0.1.2
profile                            2.1.4
rdbms                              0.3.9
redis                              0.4.2
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.12
role                               2.4.3
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4
servicefabric                     0.1.15
signalr                            1.0.0
sql                                2.2.0
sqlvm                              0.1.1
storage                            2.3.2
telemetry                          1.0.2
vm                                2.2.17

Python location '/usr/local/Cellar/azure-cli/2.0.61/libexec/bin/python'
Extensions directory '/Users/<user>/.azure/cliextensions'

Python (Darwin) 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by tjprescott** [comment]
You have to install extensions before you can use them. 

Run:
`az extension add -n azure-cli-iot-ext`
