### ISSUE TITLE
Az ssh vm not working as expected, requests password instead of using generated certificate

### ISSUE THREAD

**Issue by ascott12humanacom** [Azure/azure-cli-extensions#3922]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 0.1.6.`

**Errors:**
```
Command should log me into the VM with the generated credential, not ask for a password.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --name {} -g {} --prefer-private-ip --debug`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1 *

Extensions:
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by ascott12humanacom** [comment]
I've upgraded to 2.29.0, which is the newest available to me on Windows and it is now working properly, thank you!
