### ISSUE TITLE
`az aks enable-addons` failes with an exception

### ISSUE THREAD

**Issue by mattthias** [Azure/azure-cli-extensions#3925]
## Describe the bug
The comand to enable the addon ´azure-keyvault-secrets-provider`  finished with an exception. 

Running the command again shows that the addon is enable for the cluster. So it looks like the command worked. 

**Command Name**
`az aks enable-addons
Extension Name: aks-preview. Version: 0.5.33.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'rpartition'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/schmitz/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2802, in aks_enable_addons
    cmd, result, random_agent_pool.vnet_subnet_id)
  File "/home/schmitz/.azure/cliextensions/aks-preview/azext_aks_preview/addonconfiguration.py", line 866, in add_virtual_node_role_assignment
    vnet_id = vnet_subnet_id.rpartition('/')[0]
AttributeError: 'NoneType' object has no attribute 'rpartition'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

I followed this documentation: https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver 

What steps i did: 

- Enable feature in the subscription:
   `az feature register --namespace "Microsoft.ContainerService" --name "AKS-AzureKeyVaultSecretsProvider"`
- Installed the aks-preview cli extension:
  `az extension add --name aks-preview` 
- Enabled the addon in my already running aks cluster:
   `az aks enable-addons --addons azure-keyvault-secrets-provider --name my-aks --resource-group my-aks`

## Expected Behavior
Addon activated with a success message that contains the client-id of the user-assigned managed identity.

## Environment Summary
```
Linux-5.10.0-8-amd64-x86_64-with-debian-11.0, Debian GNU/Linux 11 (bullseye)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
aks-preview 0.5.33

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@mattthias Apologies for the late reply. Apologies for late reply. I was able to run the below command and it ran successfully.

>az aks enable-addons --addons azure-keyvault-secrets-provider --name myAKSCluster --resource-group myResourceGroup

I am sending you the az version that I had used. Could you please try with the same and let me know if you face any issues? Awaiting your reply.

>az version
{
"azure-cli": "2.32.0",
"azure-cli-core": "2.32.0",
"azure-cli-telemetry": "1.0.6",
"extensions": {
"aks-preview": "0.5.51",
"application-insights": "0.1.14",
"blueprint": "0.3.1",
"storage-blob-preview": "0.6.1"
}
}

**Comment by navba-MSFT** [comment]
@mattthias This is a quick follow-up to check if you had a chance to follow my above action plan. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mattthias We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
