### ISSUE TITLE
python error when entering interactive mode on macos

### ISSUE THREAD

**Issue by drum7** [Azure/azure-cli-extensions#395]
**Describe the bug**
When entering interactive (az interactive) - shell throws several errors seemingly related to python.

**To Reproduce**
Install azure-cli following homebrew installation method discussed [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest)
type "az interactive" to enter interactive mode

**Expected behavior**
should be able to run in interactive mode with shell complete

**Environment summary**
Install Method: Homebrew
CLI version: 2.0.38
OS version: macOS 10.13.5 (High Sierra)
Shell Type: bash (Terminal)

**Additional context**
See attached log for error.
[azurecli-error.txt](https://github.com/Azure/azure-cli/files/2161203/azurecli-error.txt)

Also attempted to perform the Python relink mentioned in the [troubleshooting section](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest#troubleshooting) of the Microsoft guide has no effect / is incorrect syntax.
[azurecli-pythonrelinkerror.txt](https://github.com/Azure/azure-cli/files/2161204/azurecli-pythonrelinkerror.txt)

**Comment by tjprescott** [comment]
These should be fixed as of the 2.0.50 release. Please open if these problems recur.
