### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by brbrockel** [Azure/azure-cli-extensions#3967]
## Describe the bug

Every so often I get the following error.  The only way I know of to resolve is to reboot. Why does this occur and what is the best way to resolve

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.5.5.`

**Errors:**
```
Error occurred in request., SSLError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/ac38cd59-fdc9-4e2e-9d7a-1d18d3d35af3/resourceGroups/wsfg-rg/providers/Microsoft.ContainerService/managedClusters/wsfg-aks/listClusterUserCredential?api-version=2021-02-01 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.20.0

Extensions:
aks-preview 0.5.5

```

**Comment by navba-MSFT** [comment]
@brbrockel Apologies for the late reply. Is there a proxy in your environment ? Could you please try to run the command on another machine which is on a different network and check if that works fine ? If this is not feasible, you can append your corporate proxy certificate(s) to the end of the certifi library's cacert.pem file. Sharing the location of this on Windows: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi\cacert.pem

Please let me know if you face any issue while testing this. Awaiting your reply.
