### ISSUE TITLE
The `az aks get-credentials` command is failing for me

### ISSUE THREAD

**Issue by davidack** [Azure/azure-cli-extensions#3973]
### **The `az aks get-credentials` command is failing for me**

The command fails with the error below.

I also tried rotating the cluster certs with `az aks rotate-certs` but I still get this error.

In case it is related, please note that we enabled **Modern auth** and turned on **Security defaults** for our tenant this past Monday (11 Oct).

## Describe the bug

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.5.24.`

**Errors:**
```
'name'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 3807, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'users', replace)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 3749, in _handle_merge
    if i['name'] == j['name']:
KeyError: 'name'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials -g {} -n {}`

## Environment Summary
```
macOS-10.13.6-x86_64-i386-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.17.1 *

Extensions:
aks-preview 0.5.24

```

**Comment by phealy** [comment]
Can you try either removing aks-preview (`az extension remove -n aks-preview`) or updating it (`az extension update -n aks-preview`), as we're up to 0.5.34?

**Comment by navba-MSFT** [comment]
@davidack Apologies for the late reply. You can check under the user profile for file ~/.kube/config. There are 3 required sections which must be present: clusters, contexts and users. I feel there seems to be an issue to read this config file. You can try to rename or delete the file and run the az aks get-credentials command and check if that works.

Alternatively you can pass the --file or --overwrite-existing parameter and run the command again. More Info [here](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials).

Please let us know if you still need any assistance on this. Awaiting your reply.

**Comment by davidack** [comment]
I am familiar with the proper format of my `~/.kube/config` file. It has the 3 required sections, and each of the sections contains many entries with some variation in content because I manage multiple clusters from multiple cloud vendors. I am not sure what is causing `az aks get-credentials` to have trouble merging the new set of credentials into the existing ones, but I suspect one of the existing non-AKS entries contains data that `az aks get-credentials` does not expect.

As noted above, running `az aks get-credentials -g GROUPNAME -n CLUSTER -f FILE` to output the new credentials into a new file, then hand-merging the contents of that file into my real `~/.kube/config`, works fine as a workaround. I will continue to do that until this problem is fixed.

**Comment by navba-MSFT** [comment]
@davidack Apologies for the late reply. Could you confirm if you have tried [ --overwrite-existing](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials) parameter and checked if that helps ? Awaiting your reply.

**Comment by davidack** [comment]
I am unable to test this with the current Azure CLI version (2.36.0) on the machine where I originally reported it, because Azure CLI on MacOS only supports Homebrew as an install method, and Homebrew no longer supports MacOS 10.13.

I did try this using Azure CLI 2.36.0 on one of my newer machines, which is running MacOS 11.6. On that machine, `az aks get-credentials` is able to merge the new set of credentials into my existing large `.kube/config`.

I am not sure if it is the newer MacOS version or some change in the newer Azure CLI version that fixed the problem, but in any case it seems to be working OK now. Thanks for checking back.

**Comment by navba-MSFT** [comment]
@davidack Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
