### ISSUE TITLE
cli-translator is unable to connect to portal2cli.azurewebsites.net:443

### ISSUE THREAD

**Issue by donbee** [Azure/azure-cli-extensions#3998]
### Extension name (the extension in question)
cli-translator

### Description of issue (in as much detail as possible)

 cli-translator command fails for all resource groups.
**Steps to reproduce:**
Export an arm Template, then try this command:
az cli-translator arm translate --debug --target-subscription SUBSCRIPTION --resource-group ANY_RESOURCE_GROUP --template template.json --parameters parameters.json

When trying to connect to: portal2cli.azurewebsites.net:443
Yields: 
502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

**Comment by yonzhan** [comment]
cli-translator

**Comment by jsntcy** [comment]
don't support this extension any longer.

**Comment by racinmat** [comment]
If it's no longer supported, then it should be reflected in https://learn.microsoft.com/en-us/cli/azure/cli-translator/arm?view=azure-cli-latest#az-cli-translator-arm-translate 

because the page says that it's experimental, but currently this extension seems completely dead.
