### ISSUE TITLE
Failure using AAD SSH

### ISSUE THREAD

**Issue by jschrap** [Azure/azure-cli-extensions#4061]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 0.1.5.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'Profile' object has no attribute 'get_msal_token'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/joanna.schrap@cobase.local/.azure/cliextensions/ssh/azext_ssh/custom.py", line 22, in ssh_vm
    public_key_file, private_key_file, use_private_ip, ssh_utils.start_ssh_connection)
  File "/home/joanna.schrap@cobase.local/.azure/cliextensions/ssh/azext_ssh/custom.py", line 48, in _do_ssh_op
    cert_file, username = _get_and_write_certificate(cmd, public_key_file, None)
  File "/home/joanna.schrap@cobase.local/.azure/cliextensions/ssh/azext_ssh/custom.py", line 58, in _get_and_write_certificate
    _, certificate = profile.get_msal_token(scopes, data)
AttributeError: 'Profile' object has no attribute 'get_msal_token'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm -n {} -g {} --prefer-private-ip`

## Environment Summary
```
Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-redhat-7.9-Maipo, Red Hat Enterprise Linux Server 7.9 (Maipo)
Python 3.6.8
Installer: RPM

azure-cli 2.30.0

Extensions:
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jschrap** [comment]
Patch Update of az cli appears to be the cause.
Rolling back to 2.29.2  fixes it.

**Comment by Klaas-** [comment]
maybe also try to update the ssh extension, latest version should be 0.1.8

**Comment by jschrap** [comment]
> maybe also try to update the ssh extension, latest version should be 0.1.8

It's not available yet in westeurope. 


az vm extension image list -l westeurope --publisher Microsoft.Azure.ActiveDirectory --output table
Name                 Publisher                                 Version
-------------------  ----------------------------------------  ----------
AADLoginForLinux     Microsoft.Azure.ActiveDirectory.LinuxSSH  1.0.1368.2
AADLoginForLinux     Microsoft.Azure.ActiveDirectory.LinuxSSH  1.0.1509.3
AADLoginForLinux     Microsoft.Azure.ActiveDirectory.LinuxSSH  1.0.1528.1
AADLoginForLinux     Microsoft.Azure.ActiveDirectory.LinuxSSH  1.0.1588.3
AADLoginForWindows   Microsoft.Azure.ActiveDirectory           0.3.0.0
AADLoginForWindows   Microsoft.Azure.ActiveDirectory           0.3.1.0
AADLoginForWindows   Microsoft.Azure.ActiveDirectory           0.4.1.0
AADLoginForWindows   Microsoft.Azure.ActiveDirectory           0.4.1.1
AADLoginForWindows   Microsoft.Azure.ActiveDirectory           1.0.0.0
AADLoginForWindows   Microsoft.Azure.ActiveDirectory           1.0.0.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1553.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1560.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1588.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1595.1
AADSSHLoginForLinux  Microsoft.Azure.ActiveDirectory           1.0.1713.1

**Comment by Klaas-** [comment]
no, client side :) `az extension update --name ssh` or something like that

**Comment by AndrewFromMelbourne** [comment]
@Klass- I had the same error using  azure-cli version 2.30.0. Updating the ssh extension to 0.1.8 fixed the issue for me.

**Comment by BasLangenberg** [comment]
Hi! I'm a colleague of @jschrap - We've tried to update the client-side ssh extension, and this has fixed the issue for us! Thanks for helping out.

**Comment by maertendMSFT** [comment]
closing as it is called out as fixed.
