### ISSUE TITLE
"az ml job list -o table" no longer working?

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azure-cli-extensions#4067]
## Describe the bug

**Command Name**
`az ml job list
Extension Name: ml. Version: 2.0.2.`

**Errors:**
```
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ml job list -o table`

## Expected Behavior

Lists jobs in table, sorted by creation time.

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.29.2 *

Extensions:
ml 2.0.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
Apologies for the delay. The command expects certain parameters like this

`az ml job list --query "[].{Name:name,Jobstatus:status}" --output table --resource-group my-resource-group --workspace-name my-workspace`
