### ISSUE TITLE
az network vpn-gateway connection ipsec-policy deprecated. Not Documented, no alternative? 

### ISSUE THREAD

**Issue by DavidWeshen** [Azure/azure-cli-extensions#4074]
## Describe the bug

Appears that the Ipsec-Policies flag was deprecated at some point (though not documented in the release notes as far as I can tell. https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli) Further the "in-support" property that's referenced isnt found anywhere in the same release documentation, nor any of the GitHub repo's associated with Azure CLI. Are you expecting customers to move to AzPowershell to perform Ipsec-Policy operations on their Vwan Hub Sitelink/Connections? Or is this an oversite? 

**Command Name**
`az network vpn-gateway connection ipsec-policy add
Extension Name: virtual-wan. Version: 0.2.10.`

**Errors:**
```
(VpnConnectionPropertyIsDeprecated) Update request for VpnConnection /subscriptions/REMOVED/resourceGroups/repro/providers/Microsoft.Network/vpnGateways/f680a856e135418ead5f9523a422e8c3-northcentralus-gw/vpnConnections/Connection-testNCUS contains deprecated property IpsecPolicies. Please use corresponding VpnSiteLinkConnection property instead.
Code: VpnConnectionPropertyIsDeprecated
Message: Update request for VpnConnection /subscriptions/REMOVED/resourceGroups/repro/providers/Microsoft.Network/vpnGateways/f680a856e135418ead5f9523a422e8c3-northcentralus-gw/vpnConnections/Connection-testNCUS contains deprecated property IpsecPolicies. Please use corresponding VpnSiteLinkConnection property instead.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- You'll need a VWAN, Hub and Site Connection for this to run. Fill in the required details for the command to accept the syntax and the error will return as noted above. 
- `az network vpn-gateway connection ipsec-policy add --connection-name {} --gateway-name {} --resource-group {} --dh-group {} --ike-encryption {} --ike-integrity {} --ipsec-encryption {} --ipsec-integrity {} --pfs-group {} --sa-lifetime {} --sa-data-size {}`

## Expected Behavior
- expectation is that if the action was deprecated correctly, the alternate or 'in support' property would be available.
## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
virtual-wan 0.2.10
ai-examples 0.2.5
ssh 0.1.8

```
## Additional Context
NA

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
We are not notified these property will be dropped. We will support the now property ASAP.
https://github.com/Azure/azure-cli/issues/19233
