### ISSUE TITLE
online-deployment issue "The Managed Inference service creation is taking longer than our normal time"

### ISSUE THREAD

**Issue by bhushangholave** [Azure/azure-cli-extensions#4088]
az --version
azure-cli   2.29.0 *

### az extension list
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "ml",
    "path": "/home/icertisadmin/.azure/cliextensions/ml",
    "preview": true,
    "version": "2.0.2"
  }
]

### Description of issue (in as much detail as possible)
 Command:- az ml online-deployment create --name blue --endpoint advanced-ner-endpoint-demo -f deployment.yml --all-traffic
Exception details
Creating or updating online_deployments
Check: endpoint advanced-endpoint exists
The deployment request bhushan-workspace-advanced-ner-endpoint-demo-8612672 was accepted. ARM deployment URI for reference:
https://ms.portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2F2b044625-9119-453a-8f50-53426430883b%2
Registering model version (ad2f42d3-xxxx-xxxx-be9f-2e20ef135c16 1 ) Done (1s)
Registering code version (c665e43f-xxxx-xxxx-a98d-a84911248e91 1 ) Done (1s)
Registering environment version (32890045-xxxx-48d3-a43c-6f2ec0323d08 1 ) Done (6s)
Creating deployment blue ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Code: ResourceDeploymentFailure
Message: The resource operation completed with terminal provisioning state 'Failed'.
Exception Details: (DeploymentTimedOut) The Managed Inference service creation is taking longer than our normal time.

-----

**Comment by yonzhan** [comment]
route to service team

**Comment by diondrapeck** [comment]
Acknowledged - beginning investigation and will reach out for more information if needed.

**Comment by vs-li** [comment]
Hi @bhushangholave! We found an error stating that the operation timed out waiting for an image build to complete. If you check the Azure portal, are you able to find an image build error under operation details?

**Comment by vizhur** [comment]
AzureML doesn't have access to the image build log because of the privacy. Though it is available for the user from the storage associated with the workspace or from the container registry associated with user workspace (ACR task runs). Timeout issue from the image build usually means poor environment specification and pip fails to resolve the conflicts in user dependencies with a reasonable time.

Solution from the user end would be to inspect the dependencies and fix conflicts. Should be easily repro-ed locally by materializing environment from conda spec.

Temporary workaround that might work is to pin pip<=20.2.4 to use older resolver that ignores some of the conflicts

**Comment by bhushangholave** [comment]
@vs-li and @vizhur  thank you for your comments.
Looks like some timeout issue to me but it reproducing every time.
Error details in ARM deployments are 
```
{
    "status": "Failed",
    "error": {
        "code": "DeploymentTimedOut",
        "message": "The Managed Inference service creation is taking longer than our normal time.",
        "details": [],
        "additionalInfo": []
    }
}
```
![ARM Failure](https://user-images.githubusercontent.com/3125166/141249777-b8045449-c591-435a-8b9e-79b24f9b1561.PNG)
![Details](https://user-images.githubusercontent.com/3125166/141249782-48115530-e329-4092-bd4c-eb88ab736453.PNG)

**Comment by bhushangholave** [comment]
@vs-li In Azure portal Environment tab it is still stuck at installing pip dependencies.
Same environment is working on our other workspace.

> 2021/11/11 10:05:42 Downloading source code...
2021/11/11 10:05:43 Finished downloading source code
2021/11/11 10:05:43 Creating Docker network: acb_default_network, driver: 'bridge'
2021/11/11 10:05:44 Successfully set up Docker network: acb_default_network
2021/11/11 10:05:44 Setting up Docker configuration...
2021/11/11 10:05:44 Successfully set up Docker configuration
2021/11/11 10:05:44 Logging in to registry: 02f210dd14eb4df1a8d3ac2f948c3ede.azurecr.io
2021/11/11 10:05:45 Successfully logged into 02f210dd14eb4df1a8d3ac2f948c3ede.azurecr.io
2021/11/11 10:05:45 Executing step ID: acb_step_0. Timeout(sec): 5400, Working directory: '', Network: 'acb_default_network'
2021/11/11 10:05:45 Scanning for dependencies...
2021/11/11 10:05:46 Successfully scanned dependencies
2021/11/11 10:05:46 Launching container with name: acb_step_0
Sending build context to Docker daemon  68.61kB

Step 1/19 : FROM mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest@sha256:fda0c9dd1702f56aa5ce42ebeeda6af6b768d1cb18c04380af3ded4184eedb09
mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest@sha256:fda0c9dd1702f56aa5ce42ebeeda6af6b768d1cb18c04380af3ded4184eedb09: Pulling from azureml/openmpi3.1.2-ubuntu18.04
284055322776: Already exists
4c683b87b3fa: Pulling fs layer
1577eaefa27a: Pulling fs layer
8b473b71c2c4: Pulling fs layer
7f9f8de2dc06: Pulling fs layer
f8839526f541: Pulling fs layer
f3bffb23c6c4: Pulling fs layer
ecddeb6524fc: Pulling fs layer
a417bd11e4b2: Pulling fs layer
7f9f8de2dc06: Waiting
f8839526f541: Waiting
f3bffb23c6c4: Waiting
ecddeb6524fc: Waiting
a417bd11e4b2: Waiting
8b473b71c2c4: Verifying Checksum
8b473b71c2c4: Download complete
1577eaefa27a: Verifying Checksum
1577eaefa27a: Download complete
f8839526f541: Verifying Checksum
f8839526f541: Download complete
f3bffb23c6c4: Verifying Checksum
f3bffb23c6c4: Download complete
ecddeb6524fc: Verifying Checksum
ecddeb6524fc: Download complete
a417bd11e4b2: Verifying Checksum
a417bd11e4b2: Download complete
4c683b87b3fa: Verifying Checksum
4c683b87b3fa: Download complete
7f9f8de2dc06: Verifying Checksum
7f9f8de2dc06: Download complete
4c683b87b3fa: Pull complete
1577eaefa27a: Pull complete
8b473b71c2c4: Pull complete
7f9f8de2dc06: Pull complete
f8839526f541: Pull complete
f3bffb23c6c4: Pull complete
ecddeb6524fc: Pull complete
a417bd11e4b2: Pull complete
Digest: sha256:fda0c9dd1702f56aa5ce42ebeeda6af6b768d1cb18c04380af3ded4184eedb09
Status: Downloaded newer image for mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest@sha256:fda0c9dd1702f56aa5ce42ebeeda6af6b768d1cb18c04380af3ded4184eedb09
 ---> 02c62b48927a
Step 2/19 : USER root
 ---> Running in 9dacaa1d14ad
Removing intermediate container 9dacaa1d14ad
 ---> 6fde3ca80c55
Step 3/19 : RUN mkdir -p $HOME/.cache
 ---> Running in 55edcd44085d
Removing intermediate container 55edcd44085d
 ---> f8c35f9a9cb8
Step 4/19 : WORKDIR /
 ---> Running in 2e91d46f7cc4
Removing intermediate container 2e91d46f7cc4
 ---> 907a8123f6b3
Step 5/19 : COPY azureml-environment-setup/99brokenproxy /etc/apt/apt.conf.d/
 ---> df36fc224f0c
Step 6/19 : RUN if dpkg --compare-versions `conda --version | grep -oE '[^ ]+$'` lt 4.4.11; then conda install conda==4.4.11; fi
 ---> Running in b09508eaf72e
Removing intermediate container b09508eaf72e
 ---> 43c921cbf924
Step 7/19 : COPY azureml-environment-setup/mutated_conda_dependencies.yml azureml-environment-setup/mutated_conda_dependencies.yml
 ---> c14f668617bf
Step 8/19 : RUN ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_996e6ced9a072187393391a560ac11f8 -f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROOT_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} + && ldconfig
 ---> Running in 7c1f90ce87ae
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages

readline-8.1         | 362 KB    |            |   0% 
readline-8.1         | 362 KB    | ########## | 100% 

_libgcc_mutex-0.1    | 3 KB      |            |   0% 
_libgcc_mutex-0.1    | 3 KB      | ########## | 100% 

ca-certificates-2021 | 115 KB    |            |   0% 
ca-certificates-2021 | 115 KB    | ########## | 100% 

ncurses-6.3          | 782 KB    |            |   0% 
ncurses-6.3          | 782 KB    | ########## | 100% 
ncurses-6.3          | 782 KB    | ########## | 100% 

six-1.16.0           | 18 KB     |            |   0% 
six-1.16.0           | 18 KB     | ########## | 100% 

tk-8.6.11            | 3.0 MB    |            |   0% 
tk-8.6.11            | 3.0 MB    | ########## | 100% 
tk-8.6.11            | 3.0 MB    | ########## | 100% 

scikit-learn-1.0.1   | 5.5 MB    |            |   0% 
scikit-learn-1.0.1   | 5.5 MB    | ########## | 100% 
scikit-learn-1.0.1   | 5.5 MB    | ########## | 100% 

ld_impl_linux-64-2.3 | 586 KB    |            |   0% 
ld_impl_linux-64-2.3 | 586 KB    | ########## | 100% 

intel-openmp-2021.4. | 4.2 MB    |            |   0% 
intel-openmp-2021.4. | 4.2 MB    | ########## | 100% 
intel-openmp-2021.4. | 4.2 MB    | ########## | 100% 

numpy-base-1.21.2    | 4.8 MB    |            |   0% 
numpy-base-1.21.2    | 4.8 MB    | ########## | 100% 
numpy-base-1.21.2    | 4.8 MB    | ########## | 100% 

threadpoolctl-2.2.0  | 16 KB     |            |   0% 
threadpoolctl-2.2.0  | 16 KB     | ########## | 100% 

joblib-1.1.0         | 211 KB    |            |   0% 
joblib-1.1.0         | 211 KB    | ########## | 100% 

blas-1.0             | 6 KB      |            |   0% 
blas-1.0             | 6 KB      | ########## | 100% 

libgfortran-ng-7.5.0 | 22 KB     |            |   0% 
libgfortran-ng-7.5.0 | 22 KB     | ########## | 100% 

setuptools-58.0.4    | 775 KB    |            |   0% 
setuptools-58.0.4    | 775 KB    | ########## | 100% 

mkl-2021.4.0         | 142.6 MB  |            |   0% 
mkl-2021.4.0         | 142.6 MB  | 6          |   6% 
mkl-2021.4.0         | 142.6 MB  | #          |  10% 
mkl-2021.4.0         | 142.6 MB  | #8         |  18% 
mkl-2021.4.0         | 142.6 MB  | ##2        |  22% 
mkl-2021.4.0         | 142.6 MB  | ###1       |  31% 
mkl-2021.4.0         | 142.6 MB  | ####       |  40% 
mkl-2021.4.0         | 142.6 MB  | ####8      |  49% 
mkl-2021.4.0         | 142.6 MB  | #####7     |  58% 
mkl-2021.4.0         | 142.6 MB  | ######6    |  66% 
mkl-2021.4.0         | 142.6 MB  | #######4   |  75% 
mkl-2021.4.0         | 142.6 MB  | ########3  |  84% 
mkl-2021.4.0         | 142.6 MB  | #########2 |  93% 
mkl-2021.4.0         | 142.6 MB  | ########## | 100% 

zlib-1.2.11          | 103 KB    |            |   0% 
zlib-1.2.11          | 103 KB    | ########## | 100% 

libffi-3.3           | 50 KB     |            |   0% 
libffi-3.3           | 50 KB     | ########## | 100% 

wheel-0.37.0         | 33 KB     |            |   0% 
wheel-0.37.0         | 33 KB     | ########## | 100% 

libgcc-ng-9.3.0      | 4.8 MB    |            |   0% 
libgcc-ng-9.3.0      | 4.8 MB    | ########## | 100% 
libgcc-ng-9.3.0      | 4.8 MB    | ########## | 100% 

sqlite-3.36.0        | 990 KB    |            |   0% 
sqlite-3.36.0        | 990 KB    | ########## | 100% 

libgfortran4-7.5.0   | 995 KB    |            |   0% 
libgfortran4-7.5.0   | 995 KB    | ########## | 100% 

_openmp_mutex-4.5    | 22 KB     |            |   0% 
_openmp_mutex-4.5    | 22 KB     | ########## | 100% 

mkl_fft-1.3.1        | 172 KB    |            |   0% 
mkl_fft-1.3.1        | 172 KB    | ########## | 100% 

libgomp-9.3.0        | 311 KB    |            |   0% 
libgomp-9.3.0        | 311 KB    | ########## | 100% 

xz-5.2.5             | 341 KB    |            |   0% 
xz-5.2.5             | 341 KB    | ########## | 100% 

python-3.7.11        | 45.3 MB   |            |   0% 
python-3.7.11        | 45.3 MB   | ##2        |  22% 
python-3.7.11        | 45.3 MB   | ####9      |  49% 
python-3.7.11        | 45.3 MB   | #######6   |  76% 
python-3.7.11        | 45.3 MB   | #########8 |  98% 
python-3.7.11        | 45.3 MB   | ########## | 100% 

mkl_random-1.2.2     | 287 KB    |            |   0% 
mkl_random-1.2.2     | 287 KB    | ########## | 100% 

mkl-service-2.4.0    | 56 KB     |            |   0% 
mkl-service-2.4.0    | 56 KB     | ########## | 100% 

pip-21.2.2           | 1.8 MB    |            |   0% 
pip-21.2.2           | 1.8 MB    | ########## | 100% 
pip-21.2.2           | 1.8 MB    | ########## | 100% 

libstdcxx-ng-9.3.0   | 3.1 MB    |            |   0% 
libstdcxx-ng-9.3.0   | 3.1 MB    | ########## | 100% 
libstdcxx-ng-9.3.0   | 3.1 MB    | ########## | 100% 

scipy-1.7.1          | 16.4 MB   |            |   0% 
scipy-1.7.1          | 16.4 MB   | ######7    |  67% 
scipy-1.7.1          | 16.4 MB   | ########## | 100% 
scipy-1.7.1          | 16.4 MB   | ########## | 100% 

openssl-1.1.1l       | 2.5 MB    |            |   0% 
openssl-1.1.1l       | 2.5 MB    | ########## | 100% 
openssl-1.1.1l       | 2.5 MB    | ########## | 100% 

numpy-1.21.2         | 23 KB     |            |   0% 
numpy-1.21.2         | 23 KB     | ########## | 100% 

certifi-2021.10.8    | 151 KB    |            |   0% 
certifi-2021.10.8    | 151 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... 

    Installed package of scikit-learn can be accelerated using scikit-learn-intelex.
    More details are available here: https://intel.github.io/scikit-learn-intelex

    For example:

        $ conda install scikit-learn-intelex
        $ python -m sklearnex my_application.py

    

done
Installing pip dependencies: ...working...

**Comment by vizhur** [comment]
@bhushangholave  you have dependencies conflict. Unfortunately conda swallows pip's log and you cannot see pips struggles. if you pip install -r requirements.txt with those deps with the latest pip you should see where pip gets stuck. There are a bunch of tuckets for pip for those kind of issues, feel free to file one too.

just to unblock yourself you can try to pin pip<=20.2.4 to use old resolver that ignores some of the conflicts

**Comment by bhushangholave** [comment]
@vizhur you are right, corrected my dependencies file and it worked. But portal or deployment creation needs to throw correct error and logs for debug.

**Comment by RakeshMohanMSFT** [comment]
@bhushangholave Since the work around helped. Closing this thread for now.
