### ISSUE TITLE
Question: Support for ParallelRunStep in Azure ML CLI Components

### ISSUE THREAD

**Issue by alexszym** [Azure/azure-cli-extensions#4126]
### Extension name (the extension in question)
Azure ML CLI V2

### Description of issue (in as much detail as possible)
-----
The new [Components feature](https://docs.microsoft.com/en-us/azure/machine-learning/reference-yaml-component-command) of the Azure ML CLI V2 looks great! 
I would like to know if there is a plan to support Component types other than commands. The Python SDK equivalent has lots of options. I'm particularly interested in [ParallelRunStep](https://docs.microsoft.com/en-us/python/api/azureml-contrib-pipeline-steps/azureml.contrib.pipeline.steps.parallelrunstep?view=azure-ml-py). Any information would be appreciated. Thanks!

**Comment by yonzhan** [comment]
route to service team

**Comment by alexszym** [comment]
Any updates? Is this the right location to post this or is there a different repo I should be posting this on?

**Comment by cloga** [comment]
@alexszym thanks for reaching out.

Parallel run step support in AzureML CLI v2 is in the list of GA features. You can post AzureML CLI v2 specific issue and requirements here: https://github.com/Azure/azureml-examples/issues

**Comment by alexszym** [comment]
Thanks @cloga that's great news. I'm going to close this issue.
