### ISSUE TITLE
AAD authentication fails with az network bastion ssh 

### ISSUE THREAD

**Issue by perttulaurila** [Azure/azure-cli-extensions#4148]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

Following the instructions here:
https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows

### Extension name (the extension in question)
network bastion ssh

### Description of issue (in as much detail as possible)

Certificate based authentication fails with bastion to linux vm.

## Command
az network bastion ssh --name "<BastionName>" --resource-group "<ResourceGroupName>" --target-resource-id "<VMResourceId>" --auth-type AAD

## Errors:

Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
_check_or_create_public_private_files() missing 1 required positional argument: 'credentials_folder'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 7801, in ssh_bastion_host
TypeError: _check_or_create_public_private_files() missing 1 required positional argument: 'credentials_folder'
To open an issue, please run: 'az feedback'

-----

**Comment by yonzhan** [comment]
network

**Comment by aavalang** [comment]
this is an issue with changes to ssh and az beyond versions 2.26 and 0.1.5 for ssh.

**Comment by pbeckendorf-gkgab** [comment]
Any News or temporal horizon when a Solution might rise up on this Issue?

**Comment by aavalang** [comment]
this is tagged in the wrong repo. THis has been fixed in azure-cli as this is not part of cli-extensions yet.

**Comment by alex200789** [comment]
@aavalang 
You sure that this is a duplicate? Stacktrace looks completely different to me.
I'm getting exact same Error with CLI 2.31.0 and ssh extension 1.0.0
![image](https://user-images.githubusercontent.com/39398964/147916984-7f25700e-7b45-4c41-9437-a6b6cd6876c8.png)

**Comment by aavalang** [comment]
@alex200789 yes, fix for the mentioned issue is for this as well.

This is fixed with 2.32 I believe.

**Comment by navba-MSFT** [comment]
@perttulaurila Apologies for the late reply. Could you please use the most recent version of AzCLI and test again ? Please let me know if you have any further questions on this. Awaiting your reply.

**Comment by davidkarlsen** [comment]
```
az version
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ssh": "1.0.0"
  }
}
```

```
/var/folders/7t/p2jt5jv57r3f0_2c0l__09vc0000gn/T/aadsshcerttks350cb/id_rsa.pub-aadcert.pub

Exception in thread Thread-1 (_start_tunnel):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 8232, in _start_tunnel
    tunnel_server.start_server()
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/tunnel.py", line 184, in start_server
    self._listen()
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/tunnel.py", line 117, in _listen
    auth_token = self._get_auth_token()
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/tunnel.py", line 104, in _get_auth_token
    raise exp
msrestazure.azure_exceptions.CloudError: Tunneling is disabled
```

**Comment by navba-MSFT** [comment]
@davidkarlsen  if native client support is not enabled on your Bastion host, you'll receive the error "msrestazure.azure_exceptions.CloudError: Tunneling is disabled". More Info [here](https://techcommunity.microsoft.com/t5/itops-talk-blog/how-to-transfer-files-to-your-azure-vm-with-no-public-open-rdp/ba-p/3166230).

Similar issue is discussed here https://github.com/Azure/azure-cli/issues/20735

**Comment by davidkarlsen** [comment]
@navba-MSFT I had the wrong SKU, it works fine now from a mac box, when I have the Standard SKU for the bastion!

**Comment by aavalang** [comment]
It’s not tied to sku alone, there’s also a feature you have to enable on the bastion in the configuration page

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davidkarlsen** [comment]
> It’s not tied to sku alone, there’s also a feature you have to enable on the bastion in the configuration page
> 
> Get Outlook for iOS<https://aka.ms/o0ukef>
> ________________________________
> From: David J. M. Karlsen ***@***.***>
> Sent: Wednesday, March 23, 2022 5:48:42 AM
> To: Azure/azure-cli-extensions ***@***.***>
> Cc: Aakash Radhakrishnan ***@***.***>; Mention ***@***.***>
> Subject: Re: [Azure/azure-cli-extensions] AAD authentication fails with az network bastion ssh (Issue #4148)
> 
> 
> @navba-MSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnavba-MSFT&data=04%7C01%7CAakash.Valangaiman%40microsoft.com%7C0e78c6b946584d4624fa08da0ccb768f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637836365267642003%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pJwMWb8sqOGC5m%2F9GTajMTJ5bYWSa603GoVs7xizRo0%3D&reserved=0> I had the wrong SKU, it works fine now from a mac box, when I have the Standard SKU for the bastion!
> 
> —
> Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli-extensions%2Fissues%2F4148%23issuecomment-1076337404&data=04%7C01%7CAakash.Valangaiman%40microsoft.com%7C0e78c6b946584d4624fa08da0ccb768f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637836365267642003%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yzD2pRN1v9zH%2BfPFu3ux2jMRawHnzrCkXOLDW%2BqKACo%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOED6A5VYG47K2B2KYDFUTVBMHKVANCNFSM5ITFGJ7Q&data=04%7C01%7CAakash.Valangaiman%40microsoft.com%7C0e78c6b946584d4624fa08da0ccb768f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637836365267642003%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YNf2vMl2DT1skUHaNqDh584%2FdLvk3zvtHtT%2FalmZFW8%3D&reserved=0>.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
> 

Yes. But in order to make that available you need the right sku

**Comment by mateialexandru** [comment]
Please make sure the error description specifies both requirements + a help link? 
Requirements are:
- Standard SKU
- checkbox for native support
