### ISSUE TITLE
ML Extension v2.0.3 - Unable to authenticate: 'AccountKeyCredentials'` object has no attribute 'key'

### ISSUE THREAD

**Issue by MickayG** [Azure/azure-cli-extensions#4149]
### Extension name (the extension in question)
ml, version 2.0.3

### Description of issue (in as much detail as possible)
Attempting to download a pipeline run's artifacts fails and raises an exception:

```
'AccountKeyCredentials'` object has no attribute 'key'
```

Example command:

```
az ml job download -n <RUN_ID> -g <RG> -w <WORKSPACE_NAME> --include-children false
```

In this instance, the Azure CLI is authenticated via a service principal. 
Version 2.0.2 does not raise an exception and completes successfully.

-----

**Comment by yonzhan** [comment]
route to service team

**Comment by diondrapeck** [comment]
@MickayG This should be fixed in a re-release of that version. Please run 
```
az extension remove -n ml
az extension add -n ml
```
to get the update version and try the job download again.

**Comment by diondrapeck** [comment]
@yonzhan please close
