### ISSUE TITLE
az webaapp up: Add time stamp to the console messages

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli-extensions#416]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Description of issue (in as much detail as possible)

-----

**Comment by tjprescott** [comment]
@panchagnula the `webapp up` issues should be transferred to  the main CLI repo.

**Comment by panchagnula** [comment]
Yes will do , we are not yet sure if we will be doing this. But all the issues we want to track for the up moving forward I will move to core. Thank you.

**Comment by tjprescott** [comment]
@panchagnula you should have the "Transfer this issue" Beta feature in Github that should make this a snap.

**Comment by panchagnula** [comment]
closing this since we are not going to support at this time
