### ISSUE TITLE
No Custom time-period available for 'Yesterday' in 'az costmanagement export create'

### ISSUE THREAD

**Issue by RustedGears18** [Azure/azure-cli-extensions#4176]
## Describe the bug

**(1)** Unable to use `az costmanagement export create` to generate Yesterday's (Custom) billing data on a daily schedule. No dynamic time-period variable could be found, like _--time-period from=(date -d "yesterday 00:00" '+%Y-%m-%dT00:00:00+00:00') to=(date -d "today 00:00" '+%Y-%m-%dT00:00:00+00:00')_

**(2) OR -lack of documentation-**

**Command Name**
`az costmanagement export create
Extension Name: costmanagement. Version: 0.1.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Cannot deserialize datetime object., ValueError: Invalid datetime string: , DeserializationError: Cannot deserialize datetime object., ValueError: Invalid datetime string:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1946, in deserialize_iso
    raise ValueError("Invalid datetime string: " + attr)
ValueError: Invalid datetime string: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1398, in _deserialize
    self._deserialize(local_type, value)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1613, in deserialize_data
    data_val = self.deserialize_type[data_type](data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1965, in deserialize_iso
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1946, in deserialize_iso
    raise ValueError("Invalid datetime string: " + attr)
msrest.exceptions.DeserializationError: Cannot deserialize datetime object., ValueError: Invalid datetime string: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/ryates087/.azure/cliextensions/costmanagement/azext_costmanagement/manual/custom.py", line 66, in costmanagement_export_create
    recurrence_period=schedule_recurrence_period)
  File "/home/ryates087/.azure/cliextensions/costmanagement/azext_costmanagement/vendored_sdks/costmanagement/operations/_export_operations.py", line 288, in create_or_update
    body_content = self._serialize.body(_parameters, 'Export')
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 623, in body
    SerializationError, "Unable to build a model: "+str(err), err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1398, in _deserialize
    self._deserialize(local_type, value)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1613, in deserialize_data
    data_val = self.deserialize_type[data_type](data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1965, in deserialize_iso
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1946, in deserialize_iso
    raise ValueError("Invalid datetime string: " + attr)
msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize datetime object., ValueError: Invalid datetime string: , DeserializationError: Cannot deserialize datetime object., ValueError: Invalid datetime string: 

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Full command used was:
az costmanagement export create --name "YesterdayData" \
                                --scope "xxxxxxxxxxxxxxxxxxxx"\
                                --storage-account-id "xxxxxxxxxxxxx" \
                                --storage-container "xxxxxxxxxxxxx" \
                                --timeframe "Custom" \
				--dataset-configuration columns="Date"  columns="MeterId" columns="InstanceId" columns="ResourceLocation" columns="PreTaxCost" \
				--dataset-grouping name="SubscriptionName" type="Dimension" \
                                --recurrence "Daily" \
                                --recurrence-period from="2021-12-01T01:00:00" \
                                --schedule-status "Active" \
                                --storage-directory "xxxxxxxxxxxx" \
                                --type "ActualCost" \
				--time-period from=(date -d "yesterday 00:00" '+%Y-%m-%dT00:00:00+00:00') to=(date -d "today 00:00" '+%Y-%m-%dT00:00:00+00:00')
The sensitive parameters of scope, storage-account-id, storage-container, and storage-directory were removed

- _Put any pre-requisite steps here..._
- `az costmanagement export create --name {} --scope {} --storage-account-id {} --storage-container {} --timeframe {} --dataset-configuration {} {} {} {} {} --dataset-grouping {} {} --recurrence {} --recurrence-period {} --schedule-status {} --storage-directory {} --type {} --time-period {}`

## Expected Behavior
!! We're expecting `az costmanagement export create` to create an export with data from yesterday only, but there doesn't seem to be a way to set the custom timeperiod to 'yesterday' dynamically.
!!

## Environment Summary
```
Linux-5.4.0-1063-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
customlocation 0.1.3
resource-graph 2.1.0
appservice-kube 0.2.2
costmanagement 0.1.1
ai-examples 0.2.5
ssh 0.1.8

```
## Additional Context

**Please** 
(1) Add a "Yesterday" context to the `--timeframe` parameter or allow a dynamic `--time-period` parameter
or (2) if this functionality exists, expand on documentation /&/ provide example.
**Thank you**

**Comment by yonzhan** [comment]
route to service team

**Comment by RustedGears18** [comment]
@jsntcy thank you for looking at this

**Comment by RustedGears18** [comment]
Note: We discovered that there is often a 72hour holding period for billing records; so instead of 'Yesterday' we are now interested in something like a 7 day rolling log instead. In the Azure portal UI we have the option to select "Last7Days" for the timeframe, but this option is unavailable when attempting to create an export through the cloudshell CLI.

![az_costmanagement_portal_create_export_last7days](https://user-images.githubusercontent.com/42483392/144489427-3400881f-e5a4-42e4-b552-a1c8a944df62.jpg)

This image shows the option we choose in the portal to create a report with the last 7 days of data (only can be run weekly). 

![az_costmanagement_list_timeframe_value](https://user-images.githubusercontent.com/42483392/144488717-64aa95c1-bbbc-4e22-a860-12b745c568d6.jpg)
This image shows what we see when we use `az costmanagement list` to retrieve how the export is stored in costmanagement. 

Example command and error response when trying to create same export (on a daily basis) in the cloudshell portal: 
`az costmanagement export create 
--name "7DayRollingLogTest1" 
--scope "****************" 
--storage-account-id "*********************" 
--storage-container "*************" 
**--timeframe "TheLast7Days"** 
--recurrence "Daily" 
--schedule-status "Active" 
--recurrence-period from="2021-12-01T22:45:00" to="2050-12-01T00:00:00" 
--type "Usage" 
--storage-directory "*************"`

And the error we receive is: 
_az costmanagement export create: 'TheLast7Days' is not a valid value for '--timeframe'. Allowed values: MonthToDate, BillingMonthToDate, TheLastMonth, TheLastBillingMonth, WeekToDate, Custom._

So how can we set a dynamic Timeframe for either 'yesterday' or 'TheLast7Days' or another custom, changing timeframe in the CLI? If we choose 'Custom' how can we insert a variable into that command to make it dynamic/changing based on the current datetime?
Thank you

**Comment by jsntcy** [comment]
@RustedGears18 
Can you try to use `--timeframe "Custom"` with correct `--time-period` format (as example below) to see if it resolves your issue?

```
        "from": "2020-09-01T00:00:00Z",
        "to": "2020-10-31T00:00:00Z"
```
Please see more details in CLI command [docs](https://docs.microsoft.com/en-us/cli/azure/costmanagement/export?view=azure-cli-latest#az_costmanagement_export_create-examples).

BTW, we don't have value `TheLast7Days` for `--timeframe` and what you saw in Azure portal is portal specific (Service API doesn't support it and you can see details [here](https://docs.microsoft.com/en-us/rest/api/cost-management/exports/create-or-update#timeframetype)). Anyway, we can consider supporting `TheLast7Days` as a convenient argument for the users.

**Comment by TiagoCrewGitHubIssues** [comment]
Please refer to the exports documentation here it does support various timeframes.
https://docs.microsoft.com/en-us/rest/api/cost-management/exports/create-or-update#timeframetype
Exports API documentation
https://docs.microsoft.com/en-us/rest/api/cost-management/exports/create-or-update

if the cli is not working correctly, can someone from the Azure SDK team help here to update the cli
@yonzhan

**Comment by tujamg** [comment]
Please refer to the exports documentation here it does support various timeframes.
https://docs.microsoft.com/en-us/rest/api/cost-management/exports/create-or-update#timeframetype
Exports API documentation
https://docs.microsoft.com/en-us/rest/api/cost-management/exports/create-or-update

if the cli is not working correctly, can someone from the Azure SDK team help here to update the cli
@yonzhan
