### ISSUE TITLE
Example doesn't work.

### ISSUE THREAD

**Issue by wgv-ebishop** [Azure/azure-cli-extensions#418]
$ az monitor log-analytics query -w b8317023-66e4-4edc-8a5b-7c002b22f92f --analytics-query "AzureActivity | summarize count() by bin(timestamp, 1h)" -t P3DT12H
az monitor: 'log-analytics' is not in the 'az monitor' command group. See 'az monitor --help'.

Please, advise. Your example doesn't work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0fd6a58-ac1a-fa45-8d96-579b4af36499
* Version Independent ID: 4098ca97-1b85-eb29-18e9-e6f0495fd030
* Content: [az monitor log-analytics](https://docs.microsoft.com/en-us/cli/azure/ext/log-analytics/monitor/log-analytics?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jebgarcia** [comment]
You probably need to add the extension then you can use it.

az extension add --name log-analytics

**Comment by TryTryAgain** [comment]
This `az extension add --name log-analytics` should be included in the documentation https://docs.microsoft.com/en-us/cli/azure/ext/log-analytics/monitor/log-analytics?view=azure-cli-latest#ext-log-analytics-az-monitor-log-analytics-query ... I had the same issue and wasted a lot of time before I found this solution here.
