### ISSUE TITLE
bad regex for front door name?

### ISSUE THREAD

**Issue by defong** [Azure/azure-cli-extensions#420]
https://github.com/Azure/azure-cli-extensions/blob/5bc1beeeaaaf5f1d19f80e905380e7a277cf76e3/src/front-door/azext_front_door/vendored_sdks/operations/frontend_endpoints_operations.py#L70

see
https://regexr.com/433lh

**Comment by timabell** [comment]
example output:
```
$ az network front-door create --resource-group bat-dev-rgroup --name fd-something-here --backend-address something-here-app.azurewebsites.net
Parameter 'front_door_name' must conform to the following pattern: '^[a-zA-Z0-9]+([-a-zA-Z0-9][a-zA-Z0-9])$'.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
```
This is a perfectly valid name in the portal.

**Comment by timabell** [comment]
This regex is repeated many times. https://github.com/Azure/azure-cli-extensions/search?q=frontDoorName&unscoped_q=frontDoorName

**Comment by tjprescott** [comment]
This is an issue with the underlying Swagger in the REST API specs repo, as that is what the SDK is generated from.

**Comment by tjprescott** [comment]
I believe this has been fixed. Please reopen if this is not the case.
