### ISSUE TITLE
Validation for CommandJobSchema fails for valid YAML passed to `az ml job create`

### ISSUE THREAD

**Issue by thomasoliveira** [Azure/azure-cli-extensions#4207]
## Describe the bug

**Command Name**
`az ml job create
Extension Name: ml. Version: 2.0.1a5.`

**Errors:**
```
Validation for CommandJobSchema failed:

 {
  "compute": {
    "_schema": [
      "Invalid input type."
    ]
  }
} 

 If the job type is incorrect, change the 'type' property.

```

## To Reproduce:

- YAML file:

$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: test
environment: azureml:my_env:1
compute: azureml:my_compute

- `az ml job create -f file_above.yml --resource-group {} --workspace-name {} --query name`

## Expected Behavior

Validation for CommandJobSchema should not fail. String 'azureml:my_compute' is a valid input according to https://azuremlschemas.azureedge.net/latest/commandJob.schema.json

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

Extensions:
ml 2.0.1a5

```

**Comment by thomasoliveira** [comment]
The problem disappears if the YAML file is changed to:

$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: test
environment: azureml:my_env:1
compute:
  target: azureml:my_compute

**Comment by jsntcy** [comment]
Route to service team

**Comment by needuv** [comment]
Hi @thomasoliveira, the schema you linked is only valid with the latest release of the ml extension (2.0.3). There have been a few breaking changes since 2.0.1a5, so please update your ml extension to the latest version. You can do this by running

```
az extension remove -n ml
az extension add -n ml
```

**Comment by navba-MSFT** [comment]
@thomasoliveira Could you please let us know if you have tried the action plan suggested in the above comment and check if you are still facing this issue ? Awaiting your reply.
