### ISSUE TITLE
`az cloud-service create` - always gives error `(PackageUriForbidden) Error:AuthenticationFailed`

### ISSUE THREAD

**Issue by stick109** [Azure/azure-cli-extensions#4209]
However, SAS signature is correct, using the same URL I can access and download the package even from incognito browser session. My hunch is that the root cause is unrelated to `--package-url` parameter and the error message is incorrect. Also, documentation for this parameter is insufficient.

This is critical issue / blocker. Thank you.

**Comment by stick109** [comment]
@jiasli Thank you for moving it forward, but I think you mislabeled it. `az create-service` command creates [**azure cloud service (extended support)**](https://docs.microsoft.com/en-us/azure/cloud-services-extended-support). It has nothing to do with Analysis Services.

cc @athipp, @taiwu, @minghan

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@stick109 We sincerely regret the delay. can you confirm if you are still facing this issue?
