### ISSUE TITLE
Changes to `az ml environment` creation no longer allows for environment variables

### ISSUE THREAD

**Issue by dsandii** [Azure/azure-cli-extensions#4231]
### Extension name (the extension in question)
`ml`

### Description of issue (in as much detail as possible)
As of [this](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli#november-02-2021) update to the CLI, `az ml environment register` no longer exists and instead it seems `az ml environment create` is preferred.

However, in the [new schema](https://docs.microsoft.com/en-us/azure/machine-learning/reference-yaml-environment) it appears that the key `environmentVariables` is no longer supported (as it once did [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.machinelearningservices/2021-01-01/workspaces/services?tabs=json), for example).

Previously we used this to pass a DB connection string into our inference-related `python` modules so they could post inference results there.

As this is a pretty major breaking change, what is the preferred new approach to inserting environment variables into docker images created via v2 of the ML extension?

**Comment by jsntcy** [comment]
Route to service team.

**Comment by Mossaka** [comment]
We still maintain the v1 CLI [azure-cli-ml](https://docs.microsoft.com/en-us/azure/machine-learning/reference-azure-machine-learning-cli), which has the verb `az ml environment register` you can use to enable the workflow. At the current stage of the v2 CLI, I don't think we have the feature parity on environment to allow inserting environment variables to  Docker images.

**Comment by saachigopal** [comment]
Environment variables can be specified in the job schema
 https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-cli
