### ISSUE TITLE
az costmanagement query does not support paging

### ISSUE THREAD

**Issue by twitek** [Azure/azure-cli-extensions#4240]
**Describe the bug**
Executing a query using az costmanagement query returns at most 1000 rows

**To Reproduce**
Perform a query that would return more than 1000 rows (long period of time or have many resources) -> Only 1000 rows are fetched.

**Expected behavior**
All rows, or an option to paginate.

**Environment summary**
Latest Docker Image

**Comment by jiasli** [comment]
Routing to service team.

**Comment by jsntcy** [comment]
@mrlepat, could you please help take a look?

**Comment by mrlepat** [comment]
Hello @twitek, @jsntcy 
Query API does return a nextLink as part of the properties object.
It is not fully supported in our az bundle yet. To unblock, you can grab the nextLink from the response and call the api directly.

**Comment by twitek** [comment]
@mrlepat Thanks a lot for getting back to us!

Yes, that is what we are doing right now (via `az rest`), it was just unexpected & silent, so I though I'd raise it for awareness.

We were just wondering about the big difference in costs in our scripts vs. the Azure Cost Explorer, and it took us a while to figure that one out :)

**Comment by mrlepat** [comment]
my pleasure @twitek! this is great feedback... I will work with my team to update the documents and fix the az sdk.
