### ISSUE TITLE
Azure Front Door autogen content is missing information on classic vs premium

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli-extensions#4250]
We have two Azure Front Door modules in our autogenerated reference content:

[az network front-door](https://docs.microsoft.com/en-us/cli/azure/network/front-door/backend-pool)
[az afd](https://docs.microsoft.com/en-us/cli/azure/afd)

It is not clear which commands are for classic (az network front-door) and which module is for premium (az afd).

Can any of the reference commands be used in both classic and premium?  When is it best to use one or the other?  What is the current status of both command groups?  Is one intended to replace the other?

CCing @KatGreenSmith and @jdmartinez36.

**Comment by yonzhan** [comment]
route to service team

**Comment by dbradish-microsoft** [comment]
@yonzhan , @chasewilson , does `route to service team` mean this has been moved to another repo?  Do we have a MSFT or Git ID for the owner of this Issue?

**Comment by yonzhan** [comment]
It means this CLI module is owned by service team. cc @cdnfdsuppgithub

**Comment by t-bzhan** [comment]
Service team ACK, we are working on that.

**Comment by dbradish-microsoft** [comment]
@yonzhan  and @t-bzhan , I see new information in the `az afd` page, so I think this issue can be closed.

![image](https://user-images.githubusercontent.com/58762114/165765415-717c7fb4-f30f-40e5-a6d8-b19d978b2915.png)
