### ISSUE TITLE
Enhance azure-firewall extension to include explicit support for allocation and deallocation of firewalls

### ISSUE THREAD

**Issue by martinpeck** [Azure/azure-cli-extensions#4301]
### Extension name (the extension in question)
azure-firewall

### Description of issue (in as much detail as possible)

The Powershell commands for Azure Firewall include Allocate and Deallocate. This is useful if you're trying to save money in test/dev environments where you want to switch things off for a bit, and then turn them back on, without having to tear down and redeploy.

e.g.

``` PowerShell
$firewall=Get-AzFirewall -ResourceGroupName rgName -Name azFw
$firewall.Deallocate()
$firewall | Set-AzFirewall

$vnet = Get-AzVirtualNetwork -ResourceGroupName rgName -Name anotherVNetName
$pip = Get-AzPublicIpAddress -ResourceGroupName rgName -Name publicIpName
$firewall.Allocate($vnet, $pip)
$firewall | Set-AzFirewall
```

https://docs.microsoft.com/en-us/powershell/module/az.network/set-azfirewall?view=azps-7.1.0#4--deallocate-and-allocate-the-firewall

I suspect that all this does is remove the public IPs from the firewall when deallocating, and allow them to added back in to reallocate. 

It would be ideal if the azure-firewall extension made these two actions explicit first-class commands, so that engineers who are unable/unwilling to install PowerShell can then easily discover and execute commands that deallocate an Azure Firewall
-----

**Comment by yonzhan** [comment]
network

**Comment by ZengTaoxu** [comment]
Hi martinpeck. You can try using the command 'az network firewall ip-config delete' to remove the public IPs from the firewall, and you can try using the command 'az network firewall ip-config create' toallow them to added back in to reallocate.
For details, Please refer to the documentation:
https://docs.microsoft.com/en-us/cli/azure/network/firewall/ip-config?view=azure-cli-latest
