### ISSUE TITLE
PowerShell runtime is not supported for Arc by the appservice-kube extension.

### ISSUE THREAD

**Issue by v-shenoy** [Azure/azure-cli-extensions#4358]
### Extension name (the extension in question)

appservice-kube

### Description of issue (in as much detail as possible)

The  ```--runtime``` parameter does not allow for PowerShell when creating a function app on Arc using `az functionapp create`

```
 $ az functionapp create $rg --name $name \
   --custom-location $customLocation --storage-account $storageAccount \
   --functions-version 3 --runtime powershell
usage error: Currently supported runtimes (--runtime) in linux function apps are: dotnet, node, python, java.
```

**Comment by yonzhan** [comment]
route to service team

**Comment by v-shenoy** [comment]
> @v-shenoy it looks like in the core CLI, PowerShell is only supported on functions v4, but in your command you're using functions v3. Just to confirm, you're expecting to be able to create PowerShell v4 functionapps on arc, right?

Yes, @StrawnSC. We were just testing out various cases a user might try. We will be expecting it to work with v4 specifically.
