### ISSUE TITLE
`az desktopvirtualization hostpool show` fails with valid host pool names > 24 characters

### ISSUE THREAD

**Issue by dpolivy** [Azure/azure-cli-extensions#4379]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
desktopvirtualization

### Description of issue (in as much detail as possible)
The Azure portal and ARM templates allow creation of host pools that can have names up to 64 characters. However, the az CLI extension for desktop virtualization seems to have a limit of 24. This appears to be a bug that was fixed over a year ago here: 

https://github.com/Azure/azure-rest-api-specs/pull/11692

Is there any workaround to get this working via az cli?

Example:
````
az desktopvirtualization hostpool show --id /subscriptions/<sub id>/resourceGroups/<rg name>/providers/Microsoft.DesktopVirtualization/hostpools/<hostpool name that is more than 24 characters>

Command group 'desktopvirtualization hostpool' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Parameter 'host_pool_name' must have length less than 24.
````

Versions:

````
az --version
azure-cli                         2.32.0

core                              2.32.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.22.0
desktopvirtualization               0.1.1

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dan\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
````

**Comment by yonzhan** [comment]
route to service team

**Comment by wangzelin007** [comment]
Hi [dpolivy](https://github.com/dpolivy),
We are going to release a new version of [desktopvirtualization](https://github.com/Azure/azure-cli-extensions/pull/4526) at 2022/04/06.
It will use the latest stable version (2021-07-12) of desktopvirtualization sdk.
