### ISSUE TITLE
Possibly inadequate error message

### ISSUE THREAD

**Issue by thomasoliveira** [Azure/azure-cli-extensions#4390]
## Describe the bug

The command `az ml job create -f <path_to_folder>/jobs/train.yml --resource-group <resource-group-A> --workspace-name <workspace-name-A> --query name -o tsv` with `environment-A` and `compute-A` specified in train.yml works. However, if a change `resource-group`, `workspace-name`, `environment` and `compute` to a `B ` set, I receive the error below.

Importantly, this behaviour happens even if `jobs/train.yml` is the only file and `jobs` is the only folder in `<path_to_folder>`. In `train.yml`, `local_path` is `../`.

I do not understand where the error comes from, and the error message does not seem to be related to the situation at hand.

**Command Name**
`az ml job create
Extension Name: ml. Version: 2.0.3.`

**Errors:**
```
Error with code: (ValidationError) Multiple files with same name and parent: { Name = jobs, ParentId = 0 }
Code: ValidationError
Message: Multiple files with same name and parent: { Name = jobs, ParentId = 0 }
Exception Details:	(Invalid) Multiple files with same name and parent: { Name = jobs, ParentId = 0 }
	Code: Invalid
	Message: Multiple files with same name and parent: { Name = jobs, ParentId = 0 }
	Target: nodes
Additional Information:Type: ComponentName
Info: {
    "value": "managementfrontend"
}Type: Correlation
Info: {
    "value": {
        "operation": "3d00f1a1656a054d8f5ea0b4dabf4c9f",
        "request": "fcdcdcf44d80cd4c"
    }
}Type: Environment
Info: {
    "value": "eastus"
}Type: Location
Info: {
    "value": "eastus"
}Type: Time
Info: {
    "value": "2022-02-07T15:08:12.6107496+00:00"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az ml job create -f <path_to_folder>/jobs/train.yml --resource-group <resource-group-B> --workspace-name <workspace-name-B> --query name -o tsv` with `environment-B` and `compute-B` specified in `train.yml`

## Expected Behavior

An output similar to 
```
Uploading <path_to_folder>:   0%|                                                         | 0.00/313k [00:03<?, ?B/s]
d4069890-eb36-4846-8710-fe2bab29861d
```

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0 *

Extensions:
ml 2.0.3

```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by navba-MSFT** [comment]
@thomasoliveira Apologies for the late reply. I am doing some research on this issue. I will get back on this github issue thread once I have an update on this.

**Comment by navba-MSFT** [comment]
@thomasoliveira Could you please share the yml file which you had used along with the --debug output while you executed the above command ?

**Comment by thomasoliveira** [comment]
[debug_output.txt](https://github.com/Azure/azure-cli-extensions/files/8032975/debug_output.txt)

**Comment by thomasoliveira** [comment]
github gives an error when I try to attach train.yml. This is its content:

```
$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code:
  local_path: ../
command: >-
  python train.py
environment: azureml:<environment>:1
compute: azureml:<compute>
```

**Comment by thomasoliveira** [comment]
@navba-MSFT  The yml file and the --debug output contain some sensitive information. I have ommited then using placeholders within <>.

**Comment by navba-MSFT** [comment]
@thomasoliveira I am unable to download the debug_output.txt. This issue would require a deeper investigation to identity the root cause. So could you please share the below details over an email with the subject line “Attn: navba” to _AzCommunity[at]Microsoft[dot]com_ referencing this github thread ? 

1. Your Resource and Resource group name
2. Your subscription id
3. Debug output from the cli command
4. Time of the issue in UTC when you encountered this issue.

Awaiting your reply.

**Comment by thomasoliveira** [comment]
@navba-MSFT , thank you for your attention. I have just sent you an email with the two files attached.

**Comment by navba-MSFT** [comment]
@thomasoliveira Thanks for sharing the requested logs over email. I am adding an update here just to avoid the thread from going idle. Since we are troubleshooting this issue offline over email, I will share an update once I hear back from the Product Owners. We appreciate your patience on this.

**Comment by navba-MSFT** [comment]
@thomasoliveira Action plan to use with Azure Blob Storage instead of Azure Data Lake Storage account in the workspace has been shared now.

**Comment by navba-MSFT** [comment]
@thomasoliveira After investigation, we found that the workspace with the failed job had Azure Data Lake Storage Gen 2 enabled, which caused the snapshot service to find duplicate blob entries in blob storage. Our Product Group has released the fix for the snapshot service now. You should be able to use the Azure DataLake Storage for your workspace now. Please test the scenario and if you still face the issue, feel free to reopen this issue.
