### ISSUE TITLE
Only allow one `--mount-option` for `az vmware datastore disk-pool-volume create`

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-cli-extensions#4395]
This a bug that affects `vmware` extension `4.0.1`. 

[The API specification](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/vmware/resource-manager/Microsoft.AVS/stable/2021-12-01/vmware.json#L6240-L6246) expects a single `mountOption`:

``` json
        "mountOption": {
          "type": "string",
          "description": "Mode that describes whether the LUN has to be mounted as a datastore or attached as a LUN",
          "enum": [
            "MOUNT",
            "ATTACH"
          ],
 ```

In `4.0.1`, if `--mount-option attach`, is specified, it sent in the request as `"mountOption": "['attach']"`.

The bug is on this line:
https://github.com/Azure/azure-cli-extensions/blob/e43193d7e496e0d4857174adfca8e196ccc32b7f/src/vmware/azext_vmware/_params.py#L128

`nargs='*'` should be removed.

**Comment by yonzhan** [comment]
vmware

**Comment by cataggar** [comment]
Fixed by #4396

**Comment by cataggar** [comment]
Waiting on https://github.com/Azure/azure-cli-extensions/pull/4415 to be merged.

**Comment by cataggar** [comment]
#4415 was merged yesterday.
