### ISSUE TITLE
Unable to list index: Unable to get extension index. Please ensure you have network connection. Connection Aborted 

### ISSUE THREAD

**Issue by jakeatmsft** [Azure/azure-cli-extensions#4397]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Trying to list available extensions:  
$ az extension list-available

### Description of issue (in as much detail as possible)
I am working on an AzureML compute instance that is secured to managed vnet.  I am able to access packages.microsoft.com from the compute instance terminal, but any attempts to list-available cli extensions gives me error:

Unable to get extension index. Please ensure you have network connection. Connection Aborted. OSError(0, 'Error)

What other domains do I need to whitelist to be able to install the ml (cli v2) extension?
-----

<img width="412" alt="image" src="https://user-images.githubusercontent.com/47987698/153065551-207cdf3e-cd51-47ee-b600-a23fc79b88ef.png">

**Comment by jakeatmsft** [comment]
curl to packages.microsoft.com successful 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/47987698/153065276-a7c2c4e5-65ac-40cb-bbf1-3cb49759040b.png">

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by PramodValavala-MSFT** [comment]
@jakeatmsft It defaults to an [`aka.ms` endpoint](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/extension/_index.py#L11) which redirects to `https://azcliextensionsync.blob.core.windows.net/index1/index.json`. Could you try whitelisting both of these and give it a shot?

**Comment by PramodValavala-MSFT** [comment]
@jakeatmsft It would depend on the extensions that you need. There are quite a few domains used for the `downloadUrl` in the JSON. You would just have to whitelist the ones you need.

**Comment by PramodValavala-MSFT** [comment]
@jakeatmsft Just following up here... Hope my previous comment clears things up.

**Comment by jakeatmsft** [comment]
Thanks Pramod, is there a place I can check for specific domains needed?  For example if I'm targeting "ml" extension where can I reference for urls to whitelist?

**Comment by PramodValavala-MSFT** [comment]
@jakeatmsft You could check the domain of the `downloadUrl` in the [index file](https://azcliextensionsync.blob.core.windows.net/index1/index.json) for the extension you are using.

@yonzhan Do we have any official recommendation for using Azure CLI in an environment with restricted network?

**Comment by jakeatmsft** [comment]
Issue was solved by whitelisting the following urls:

•             https://aka.ms/azure-cli-extension-index-v1
•             https://azcliextensionsync.blob.core.windows.net/index1/index.json
-       https://azuremlsdktestpypi.blob.core.windows.net
