### ISSUE TITLE
`az account create` no longer works

### ISSUE THREAD

**Issue by lawrenae** [Azure/azure-cli-extensions#441]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
subscription

### Description of issue (in as much detail as possible)
Following the instructions in https://docs.microsoft.com/en-us/azure/azure-resource-manager/programmatically-create-subscription?tabs=azure-cli and https://docs.microsoft.com/en-us/azure/azure-resource-manager/grant-access-to-create-subscription?tabs=azure-cli

I've been able to create subscriptions in the past, but it stopped working this week. Specifically, I have a service principal that has "Owner" on the enrollment account (per the instructions above) and when I run:

```sh
az account create \
    --offer-type "MS-AZR-0017P" \
    --display-name "${SUBSCRIPTION_NAME}" \
    --enrollment-account-object-id "${ENROLLMENT_ID}" \
    --owner-object-id "${SP_OBJECT_ID}" \
    --output json
```

i get the following error:

```sh
AuthorizationFailed - The client 'c0d0715e-XXXX-4ee0-a985-6224c6df64e9' with object id 'c0d0715e-8506-XXXX-a985-6224c6df64e9' does not have authorization to perform action 'Microsoft.Billing/enrollmentAccounts/Microsoft.Billing/255c4999-XXXX-4a51-85f8-5a6f5b049ee2/Microsoft.Subscription/action' over scope '/providers/Microsoft.Billing/enrollmentAccounts/providers/Microsoft.Billing/enrollmentAccounts/255c4999-533a-XXXX-85f8-5a6f5b049ee2/providers/Microsoft.Subscription/createSubscription'.
```
I have the following installed

```sh
$ az --version
azure-cli (2.0.51)
...
Extensions:
subscription (0.1.1)
```

and I cant figure out why. It's clearly an authz error, but I dont know what role is needed, am not sure of the scope (notice that `/providers/Microsoft.Billing/enrollmentAccounts/` is repeated twice in the listed failure) or why this is coming up now. I am happy to help debug and submit patches, but help figuring out the right answers (on permissions, scopes, or even which REST APIs to call) will be needed.

I noticed that @wilcobmsft is the original author of this extension, but am not clear if he's still involved.

Thanks in advance -- any help or pointers would be appreciated.

-----

**Comment by luylimsft** [comment]
Hello,

could you let me know what is the enrollment account id you are using?

**Comment by luylimsft** [comment]
From our log seems like the account you are using doesn't exist in the tenant you specified. But we would like you to provide more information
