### ISSUE TITLE
AZ AKS Kollect failed with diagnostic settings property error.

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/azure-cli-extensions#4448]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
`aks-preview` 

### Description of issue (in as much detail as possible)

Upgrade to latest `az li` and run the kollect command, fyi to @FumingZhang , thank you for looking into this, I thought I will loop you in for any recent changes which triggered this error, seems like `some object value no longer flows through`

* It fails on this line of code https://github.com/Azure/azure-cli-extensions/blob/6d0ff505113ca853fea82e5f0573a8edb96b63a6/src/aks-preview/azext_aks_preview/custom.py#L2414

![image](https://user-images.githubusercontent.com/6233295/155032079-cd6c2f66-a38d-4bf4-b150-7f619b1b2cda.png)

-----

**Comment by yonzhan** [comment]
route to service team
