### ISSUE TITLE
Could not retrieve user token. Please run 'az login' Azure CLI 2.33.1

### ISSUE THREAD

**Issue by obiii** [Azure/azure-cli-extensions#4457]
Hi,

I have a CI pipeline which contains an Azure Cli Task to submit a python script. This is the inline script the task uses:

```
az logout 

az login --service-principal --username $servicePrincipalId --password $servicePrincipalKey --tenant $tenantId

az ml run submit-script -g myRG-w myWS -e ExpName --ct clusterName -d conda_dependencies.yml -t metadata/run.json ml_service/pipelines/build_pipeline_score.py 
```

It results in the error:

`{'code': ExecutionFailed, 'message': [{"exit_code":1,"error_message":"Execution failed with error: [stderr]  File \"/azureml-envs/azureml_d8ac72e9b124a7fe0100c9a94b37cf8b/lib/python3.8/site-packages/azureml/core/authentication.py\", line 899, in _get_arm_token\n[stderr]    return _get_arm_token_with_refresh(\n[stderr]  File \"/azureml-envs/azureml_d8ac72e9b124a7fe0100c9a94b37cf8b/lib/python3.8/site-packages/azureml/core/authentication.py\", line 426, in connection_aborted_wrapper\n[stderr]    return function(*args, **kwargs)\n[stderr]  File \"/azureml-envs/azureml_d8ac72e9b124a7fe0100c9a94b37cf8b/lib/python3.8/site-packages/azureml/core/authentication.py\", line 2293, in _get_arm_token_with_refresh\n[stderr]    raise AuthenticationException(\"Could not retrieve user token. Please run 'az login'\", inner_exception=e)\n[stderr]azureml.exceptions._azureml_exception.AuthenticationException: AuthenticationException:\n[stderr]\tMessage: Could not retrieve user token. Please run 'az login'\n[stderr]\tInnerException Please run 'az login' to setup account.\n[stderr]\tErrorResponse \n[stderr]{\n[stderr]    \"error\": {\n[stderr]        \"code\": \"UserError\",\n[stderr]        \"inner_error\": {\n[stderr]            \"code\": \"Authentication\"\n[stderr]        },\n[stderr]        \"message\": \"Could not retrieve user token. Please run 'az login'\"\n[stderr]    }\n[stderr]}\n[stderr]\n","process_name":"/azureml-envs/azureml_d8ac72e9b124a7fe0100c9a94b37cf8b/bin/python","error_file":"user_logs/std_log.txt"}], 'target': , 'category': UserError, 'error_details': [{'key': exit_codes, 'value': 1}, ], 'inner_error': null}`

I have tried downgrading the azure cli version to 2.29.2 (as stated in some old issues).

Here is the cli task configuration
![azlogin](https://user-images.githubusercontent.com/17766651/155348074-e734a1fd-77cf-44cb-80df-2d48bd683ed4.PNG)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@obiii The Azure CLI task should already be logged in using the service connection defined in the task. You don't really have to login in code like so.

Either way, is the `az login` command running without any errors? You could run `az account show` to double check.
