### ISSUE TITLE
Not able to access same dashboards via CLI as when using the portal

### ISSUE THREAD

**Issue by yo1-markenstein** [Azure/azure-cli-extensions#4476]
## Describe the bug

**Command Name**
`az portal dashboard list
Extension Name: portal. Version: 0.1.2.`

**Errors:**
```
(AuthorizationFailed) The client 'myemail@address' with object id 'xxxxxxxx-xxxx-etc' does not have authorization to perform action 'Microsoft.Portal/dashboards/read' over scope '/subscriptions/xxxxx/resourceGroups/shared-dev-02/providers/Microsoft.Portal' or the scope is invalid. If access was recently granted, please refresh your credentials.
Code: AuthorizationFailed
Message: The client 'myemail@address' with object id 'xxxxxxxx-xxxx-etc' does not have authorization to perform action 'Microsoft.Portal/dashboards/read' over scope '/subscriptions/xxxxx/resourceGroups/shared-dev-02/providers/Microsoft.Portal' or the scope is invalid. If access was recently granted, please refresh your credentials.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az portal dashboard list -g shared-dev-02 -o table`

## Expected Behavior

To see the same list of shared dashboards in the resourcegroup as I see when I use the portal UI.
Via the portal I am able to create, upload, etc dashboards, but I cannot use Azure CLI to manipulate dashboards.
Operations on other resources I have no such issue using Azure CLI.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0 *

Extensions:
azure-devops 0.22.0
portal 0.1.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by yo1-markenstein** [comment]
Hello team, I discovered the issue (confusion) is totally on my side. I need to explicitly set the subscription (`az account set --subscription bla`) prior to executing the command.

Sorry for bothering you.

Johan
