### ISSUE TITLE
IoT Hub connection string has missing property: HostName

### ISSUE THREAD

**Issue by lukasztomalczyk** [Azure/azure-cli-extensions#451]
A strange problem. I do that. I am logged in with the "az login" command and then open the browser in which I use my data. Return to CLI and I want to use the command "az iot device simulate -n mytesting --device-id 001".

At this point, he receives the error "IoT Hub connection string has missing property: HostName"

Debug log:

PS C:\Users\lukasz.tomalczyk&gt; az iot device simulate -n mytesting -l device -d 001 --debug
Command arguments: ['iot', 'device', 'simulate', '-n', 'mytesting', '-l', 'device', '-d', '001', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [&lt;function CLILogging.on_global_arguments at 0x036FE8E8&gt;, &lt;function OutputProducer.on_global_arguments at 0x03635738&gt;, &lt;function CLIQuery.on_global_arguments at 0x0369B390&gt;]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'servicebus', 'servicefabric', 'signalr', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.010 seconds.
Loaded module 'acs' in 0.006 seconds.
Loaded module 'advisor' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.012 seconds.
Loaded module 'appservice' in 0.010 seconds.
Loaded module 'backup' in 0.008 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.015 seconds.
Loaded module 'batchai' in 0.008 seconds.
Loaded module 'billing' in 0.007 seconds.
Loaded module 'botservice' in 0.008 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.010 seconds.
Loaded module 'cloud' in 0.004 seconds.
Loaded module 'cognitiveservices' in 0.006 seconds.
Loaded module 'configure' in 0.004 seconds.
Loaded module 'consumption' in 0.006 seconds.
Loaded module 'container' in 0.009 seconds.
Loaded module 'cosmosdb' in 0.007 seconds.
Loaded module 'dla' in 0.010 seconds.
Loaded module 'dls' in 0.007 seconds.
Loaded module 'dms' in 0.007 seconds.
Loaded module 'eventgrid' in 0.004 seconds.
Loaded module 'eventhubs' in 0.007 seconds.
Loaded module 'extension' in 0.003 seconds.
Loaded module 'feedback' in 0.003 seconds.
Loaded module 'find' in 0.003 seconds.
Loaded module 'hdinsight' in 0.006 seconds.
Loaded module 'interactive' in 0.002 seconds.
Loaded module 'iot' in 0.008 seconds.
Loaded module 'iotcentral' in 0.005 seconds.
Loaded module 'keyvault' in 0.010 seconds.
Loaded module 'lab' in 0.009 seconds.
Loaded module 'maps' in 0.006 seconds.
Loaded module 'monitor' in 0.012 seconds.
Loaded module 'network' in 0.034 seconds.
Loaded module 'policyinsights' in 0.004 seconds.
Loaded module 'profile' in 0.004 seconds.
Loaded module 'rdbms' in 0.009 seconds.
Loaded module 'redis' in 0.007 seconds.
Loaded module 'relay' in 0.007 seconds.
Loaded module 'reservations' in 0.006 seconds.
Loaded module 'resource' in 0.011 seconds.
Loaded module 'role' in 0.009 seconds.
Loaded module 'search' in 0.005 seconds.
Loaded module 'servicebus' in 0.008 seconds.
Loaded module 'servicefabric' in 0.005 seconds.
Loaded module 'signalr' in 0.004 seconds.
Loaded module 'sql' in 0.012 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.040 seconds.
Loaded module 'vm' in 0.018 seconds.
Loaded all modules in 0.417 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: 'C:\Users\lukasz.tomalczyk\.azure\cliextensions'
Found 1 extensions: ['azure-cli-iot-ext']
Extensions directory: 'C:\Users\lukasz.tomalczyk\.azure\cliextensions'
Loaded extension 'azure-cli-iot-ext' in 0.085 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandInvoker.OnPostCommandTableCreate [&lt;function register_global_subscription_argument.&lt;locals&gt;.add_subscription_parameter at 0x037542B8&gt;, &lt;function register_ids_argument.&lt;locals&gt;.add_ids_arguments at 0x03754270&gt;]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [&lt;function _documentdb_deprecate at 0x043F1660&gt;]
Event: CommandInvoker.OnPostParseArgs [&lt;function OutputProducer.handle_output_argument at 0x03635780&gt;, &lt;function CLIQuery.handle_query_parameter at 0x0369B3D8&gt;, &lt;function register_ids_argument.&lt;locals&gt;.parse_ids_arguments at 0x03754858&gt;, &lt;function handler at 0x0447D9C0&gt;]
Extensions directory: 'C:\Users\lukasz.tomalczyk\.azure\cliextensions'
Extensions directory: 'C:\Users\lukasz.tomalczyk\.azure\cliextensions'
Extensions directory: 'C:\Users\lukasz.tomalczyk\.azure\cliextensions'
IoT Hub connection string has missing property: HostName
telemetry.save : Save telemetry record of length 2525 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\lukasz.tomalczyk\.azure"
telemetry.process : Return from creating porcess
telemetry.main : Finish creating telemetry upload process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f065fd36-95ca-aac0-e476-2291ccb97f18
* Version Independent ID: e0cb4044-9686-405e-f9a9-2fa0c6e0c4d3
* Content: [az iot device](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/device?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-device-simulate)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/device.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/device.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by digimaun** [comment]
Hey @lukasztomalczyk thanks for submitting the issue. The root cause is because the `-l`/`--login` argument is expecting an IoT Hub connection string  (which is typically used when you want to skip `az login`).

From your debug log input `['iot', 'device', 'simulate', '-n', 'mytesting', '-l', 'device', '-d', '001', '--debug']` the `-l` argument has the value of "device". 

Just this should work `az iot device simulate -n mytesting -d 001`.
