### ISSUE TITLE
Create automation runbooks type Python by azure-cli

### ISSUE THREAD

**Issue by DuongThiNgocHoa** [Azure/azure-cli-extensions#4514]
In azure portal, I can create a automation runbook with Python type. But in azure-cli, i can't. How to do it ?

**Comment by jiasli** [comment]
According to https://docs.microsoft.com/en-us/cli/azure/automation/runbook?view=azure-cli-latest, this issue belongs to `automation` entension.

**Comment by navba-MSFT** [comment]
@DuongThiNgocHoa Apologies for the late reply. Thanks for reaching out to us and reporting this issue. 
The automation extension will help in achiveing your ask. This will automatically install the first time you run an `az automation runbook` command.

>az automation runbook create --automation-account-name "myAutomationAccount" --resource-group "rg" --name "myRunbook" --type "PowerShell" --location "East US 2"

The above CLI command Creates the runbook identified by runbook name.
More Info [here](https://docs.microsoft.com/en-us/cli/azure/automation/runbook?view=azure-cli-latest#az-automation-runbook-create). Hope this helps.

**Comment by navba-MSFT** [comment]
The PR has been filed for this already and it has been merged: Azure/azure-rest-api-specs#19367

**Comment by navba-MSFT** [comment]
@DuongThiNgocHoa Please track the SDK release request for the fix from this link https://github.com/Azure/sdk-release-request/projects/1230 Closing this GitHub issue for now. Please feel free to reopen this thread if you have any followup queries. We would be happy to help.
