### ISSUE TITLE
Can not generate SAS token using AZ CLI

### ISSUE THREAD

**Issue by nnh116** [Azure/azure-cli-extensions#453]
I can not generate sas token because in the az iot hub --help, there is no generate sas token commands. Can anyone help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0abf1-d0b9-d886-c106-ae056daa47ec
* Version Independent ID: 7534d5aa-8270-49e5-21d6-e9456969a60e
* Content: [az iot hub](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-hub-generate-sas-token)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by williexu** [comment]
@nnh116 `az storage account generate-sas` is what youre looking.
