### ISSUE TITLE
Extension only works with AZ CLI 2.0.52

### ISSUE THREAD

**Issue by Avalaxy** [Azure/azure-cli-extensions#454]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
botservice

### Description of issue (in as much detail as possible)
The botservice extension for the az cli only works with az version 2.0.52. I have 2.0.54 installed and it doesn't offer botservice as an available extension. See the debug output:

`Skipping 'botservice-0.4.3-py2.py3-none-any.whl' as not compatible with this version of the CLI. Extension compatibility result: is_compatible=False cli_core_version=2.0.54 min_required=2.0.52 max_required=2.0.52`

-----

**Comment by williexu** [comment]
@Avalaxy I believe this is because the botservice extension commands/fixes have been added into the core CLI.
You should have access to the commands previously within the extension in v2.0.54 of the CLI you have installed.

Feel free to remove the outdated extension you have installed.

**Comment by Avalaxy** [comment]
@williexu I cannot remove the outdated extension. When I run the remove command it says "The extension botservice is not installed.". However, in order to run the msbot clone service command, I need to be able to upgrade the botservice package.
