### ISSUE TITLE
Azure cli create container app not working after migration to Microsoft.App

### ISSUE THREAD

**Issue by ShafeerAli** [Azure/azure-cli-extensions#4548]
## Describe the bug

**Command Name**
`az containerapp env create
Extension Name: containerapp. Version: 0.2.4.`

**Errors:**
```
Creation or update of environments and container apps in Microsoft.Web namespace are no longer supported. Please use Microsoft.App namespace instead. More information available via aka.ms/microsoftappmigration.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp env create --name {} --resource-group {} --logs-workspace-id {} --logs-workspace-key {} --location {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

Extensions:
aro 1.0.0
containerapp 0.2.4

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by panchagnula** [comment]
@ShafeerAli CLI experience currently doesn't support Microsoft.App - use portal until CLI release happens in the next week or so. Sorry for the inconvenience. @anthonychu , @torosent FYI

**Comment by navba-MSFT** [comment]
@ShafeerAli Apologies for the late reply. Could you please check the above suggestion provided by @panchagnula and let me know if you see any issue ? Awaiting your reply.

**Comment by panchagnula** [comment]
@navba-MSFT Container APPs is not a GA feature yet, so hoping CXP can skip these issues for now.

**Comment by panchagnula** [comment]
@ShafeerAli we will update this issue when the Microsoft.App support for Container apps using CLI is ready, so you can re-try & confirm.

**Comment by anthonychu** [comment]
The Microsoft.App-compatible version of the extension is now ready. Please see this issue for more: https://github.com/microsoft/azure-container-apps/issues/152

**Comment by panchagnula** [comment]
Please try the new version & let us know.
