### ISSUE TITLE
Azure Spring Cloud app deployment create fails from pipeline as there is no prompt

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli-extensions#4592]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
spring-cloud extension fails from pipeline as there is no prompt
```sh
az spring-cloud app deployment create .............. 
```
```console
ERROR: The command requires the extension spring-cloud. Unable to prompt for extension install confirmation as no tty available. Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.
```

```sh
az spring-cloud app deployment create .............. --yes
```
```console
WARNING: The command requires the extension spring-cloud. It will be installed first.
ERROR: unrecognized arguments: --yes        
```

Indeed this is what is shown  running:
```sh
az spring-cloud app deployment create --help
```

workaround: 
```sh
az config set extension.use_dynamic_install=yes_without_prompt
az spring-cloud app deployment create ..............
```

```console
WARNING: Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: The command requires the extension spring-cloud. It will be installed first.
WARNING: No production deployment found, use --skip-clone-settings to skip copying settings from production deployment.
WARNING: [1/3] Requesting for upload URL.
WARNING: [2/3] Uploading package to blob.
WARNING: [3/3] Creating deployment in app "discovery-server" (this operation can take a while to complete)
```

### Description of issue (in as much detail as possible)

AZ_CLI_VERSION: 2.34.1
See the [GitHub action workflow](https://github.com/ezYakaEagle442/azure-spring-cloud-petclinic-mic-srv/blob/azure/.github/workflows/action.yml)
-----

**Comment by yonzhan** [comment]
route to spring cloud

**Comment by PramodValavala-MSFT** [comment]
@ezYakaEagle442 That is the expected behavior when running in a non-interactive environment like a CI/CD pipeline. [Setting the config value](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview#install-extensions-automatically) at the start of your pipeline once is required.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
