### ISSUE TITLE
AZ400 - lab 18 - az webapp create

### ISSUE THREAD

**Issue by piegre** [Azure/azure-cli-extensions#4609]
## Describe the bug

**Command Name**
`az webapp create
Extension Name: appservice-kube. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got multiple values for argument 'linux'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/pierre/.azure/cliextensions/appservice-kube/azext_appservice_kube/commands.py", line 42, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/pierre/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 505, in create_webapp
    helper = _StackRuntimeHelper(cmd, client, linux=(is_linux or is_kube))
TypeError: __init__() got multiple values for argument 'linux'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create -n {} -g {} -p {} -i {}`

## Environment Summary
```
Linux-5.4.0-1073-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.34.1

Extensions:
appservice-kube 0.2.2
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@piegre It looks like you're running an old version of the `appservice-kube `extension from private preview (since your version number is 0.2.2). You should uninstall the extension with az extension remove -n appservice-kube and install the latest version (public preview) with az extension add -n appservice-kube. After this you can test the command again. Awaiting your reply.

Similar issue https://github.com/Azure/azure-cli-extensions/issues/4490

**Comment by piegre** [comment]
I am just using the azure CLI (shell.azure.com)

**Comment by panchagnula** [comment]
@piegre shell.azure.com only upgrades the core-cli version & not the individual extensions, you seem to have this installed appservice-kube 0.2.2 - which overrides some behavior on webapp core-cli, so either delete this or upgrade this extension.
See following: https://docs.microsoft.com/en-us/cli/azure/extension?view=azure-cli-latest#az-extension-update

**Comment by navba-MSFT** [comment]
@piegre Could you please let me know if you had a chance to upgrade your `appservice-kube `extension. You can either uninstall and reinstall the extension as explained in my above comment. Or you can upgrade it using the command `az extension update --name appservice-kube`. Please let me know if you still face the same issue after following the above plan. Awaiting your reply.

**Comment by piegre** [comment]
Yes it worked, thanks.
It's a bummer to lose so much time during an intense training like az400,
just because the azure CLI doesn't include the latest packages.

**Comment by navba-MSFT** [comment]
@piegre Thanks for getting back. I am glad that the issue is resolved. As mentioned earlier in the above comment, the shell.azure.com only upgrades the core-cli version & not the individual extensions. Having CLI extensions, will override the behavior of webapp core-cli. We will now proceed with closure of this issue. Please free to reopen this thread if you have any further questions on this.
