### ISSUE TITLE
az arcdata dc update - failed to 1.5

### ISSUE THREAD

**Issue by rfsonders** [Azure/azure-cli-extensions#4655]
## Describe the bug

**Command Name**
`az arcdata dc update
Extension Name: arcdata. Version: 1.3.0.`

**Errors:**
```
Only one of '[--auto-upload-logs]' or '[--auto-upload-metrics]' can be specified.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az arcdata dc update --name {} --resource-group {} --auto-upload-logs {} --auto-upload-metrics {} --debug`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0

Extensions:
arcdata 1.3.0
connectedk8s 1.2.7
customlocation 0.1.3
k8s-configuration 1.5.0
k8s-extension 1.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```
## Additional Context

PS C:\Users\Rob\Documents\GitHub\Azure_Arc_DBaaS> az arcdata dc update --name pstoredc01 --resource-group arc-services-ns --auto-upload-logs true --debug
cli.knack.cli: Command arguments: ['arcdata', 'dc', 'update', '--name', 'pstoredc01', '--resource-group', 'arc-services-ns', '--auto-upload-logs', 'true', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x015E9BF8>, <function OutputProducer.on_global_arguments at 0x016AE538>, <function CLIQuery.on_global_arguments at 0x016CC190>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'arcdata': ['azext_arcdata']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: arcdata                   2.571        16        45  C:\Users\Rob\.azure\cliextensions\arcdata
cli.azure.cli.core: Total (1)                 2.571        16        45  
cli.azure.cli.core: Loaded 16 groups, 45 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : arcdata dc update
cli.azure.cli.core: Command table: arcdata dc update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03A46F58>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\Rob\.azure\commands\2022-04-08.09-29-33.arcdata_dc_update.14424.log'.
az_command_data_logger: command args: arcdata dc update --name {} --resource-group {} --auto-upload-logs {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03A98028>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03A98070>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03A98100>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x016AE580>, <function CLIQuery.handle_query_parameter at 0x016CC1D8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03A980B8>]
az_command_data_logger: extension name: arcdata
az_command_data_logger: extension version: 1.3.0
cli.azext_arcdata.core.cli_client: {'name': 'pstoredc01', 'resource_group_name': 'arc-services-ns', 'auto_upload_logs': 'true', 'auto_upload_metrics': None, 'use_k8s': None, 'namespace': None, 'desired_version': None, 'maintenance_start': None, 'maintenance_duration': None, 'maintenance_recurrence': None, 'maintenance_time_zone': None, 'maintenance_enabled': None, 'no_wait': False}
cli.azext_arcdata.core.services: Service dispatch key: 'arcdata dc'
cli.azext_arcdata.core.services: Using subscription: 047d5a79-16ab-4705-afe1-9139b0cbe512
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\Rob\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\Rob\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
cli.azure.cli.core: Current cloud config:
AzureCloud
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=(), kwargs={}
cli.azure.cli.core.auth.util: No scope is provided by the SDK, use the CLI-managed resource.
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: fb33b57d-3d0c-4860-9a2b-48e6668167f9
cli.azext_arcdata.core.arcdata_cli_credentials: ArcDataCliCredential.get_token succeeded
cli.azure.cli.core: Current cloud config:
AzureCloud
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=(), kwargs={}
cli.azure.cli.core.auth.util: No scope is provided by the SDK, use the CLI-managed resource.
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 01e44325-442c-4e0d-ac96-e01e617ca412
cli.azext_arcdata.core.arcdata_cli_credentials: ArcDataCliCredential.get_token succeeded
cli.azure.cli.core: Current cloud config:
AzureCloud
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=(), kwargs={}
cli.azure.cli.core.auth.util: No scope is provided by the SDK, use the CLI-managed resource.
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: b070e3c2-9199-4de9-a6a7-b9c398519608
cli.azext_arcdata.core.arcdata_cli_credentials: ArcDataCliCredential.get_token succeeded
cli.azext_arcdata.core.services: Runtime mode [--use-k8s]: None
cli.azext_arcdata.core.services: Service proxy type: ArmDataControllerServiceProxy
cli.azext_arcdata.core.services: Public service handle name: dc
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\dc\custom.py", line 167, in dc_update
    return client.services.dc.update(cvo)
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\core\services.py", line 383, in update
    return self._arm_client.update_dc(
TypeError: ArmClient.update_dc() takes 4 positional arguments but 6 were given

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: ArmClient.update_dc() takes 4 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\dc\custom.py", line 167, in dc_update
    return client.services.dc.update(cvo)
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\core\services.py", line 383, in update
    return self._arm_client.update_dc(
TypeError: ArmClient.update_dc() takes 4 positional arguments but 6 were given
az_command_data_logger: ArmClient.update_dc() takes 4 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\dc\custom.py", line 167, in dc_update
    return client.services.dc.update(cvo)
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\core\services.py", line 383, in update
    return self._arm_client.update_dc(
TypeError: ArmClient.update_dc() takes 4 positional arguments but 6 were given
To open an issue, please run: 'az feedback'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03A490B8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 3.586 seconds (init: 0.631, invoke: 2.955)
telemetry.save: Save telemetry record of length 6387 in cache
telemetry.check: Negative: The C:\Users\Rob\.azure\telemetry.txt was modified at 2022-04-08 09:22:52.949589, which in less than 600.000000 s
PS C:\Users\Rob\Documents\GitHub\Azure_Arc_DBaaS>

**Comment by rfsonders** [comment]
The upgrade of the data controller will work via the Azure portal. Does not work with PowerShell on-premises.
This fails.
az arcdata dc update --name pstoredc01 --resource-group arc-services-ns --auto-upload-logs true --debug

**Comment by SaurabhSharma-MSFT** [comment]
@rfsonders We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@rfsonders 
I believe you are trying to update the version of the dc, to do that.
you can use this command to list the available versions 
`az arcdata dc list-upgrades --k8s-namespace <your location>` and followed by this command to upgrade to specific versions
`az arcdata dc upgrade -v v1.5.0_2022-04-05 -n Issue4655 -g Issue4655` You may get this error "'int' object has no attribute 'get'" which you can ignore. 

then you can use this command again to check the updated version
`az arcdata dc list-upgrades --k8s-namespace <your location>`

Output 
Found 7 valid versions.  The current datacontroller version is v1.5.0_2022-04-05.
v1.5.0_2022-04-05 << current version
v1.4.1_2022-03-08
v1.4.0_2022-02-25
v1.3.0_2022-01-27
v1.2.0_2021-12-15
v1.1.0_2021-11-02
v1.0.0_2021-07-30

**Comment by RakeshMohanMSFT** [comment]
@rfsonders "Only one of '[--auto-upload-logs]' or '[--auto-upload-metrics]' can be specified." is as designed and we are getting the documented updated ASAP. Closing this issue now.
