### ISSUE TITLE
SQL MI create failure 

### ISSUE THREAD

**Issue by rfsonders** [Azure/azure-cli-extensions#4656]
## Describe the bug
Unable to create a SQL MI with PowerShell.

az sql mi-arc create --name sqlmi-02 --subscription $azSubId --resource-group PowerStoreAzureArc-RG  --location "East US" --custom-location "EdenPrairieNM"  --dev --replicas 1 `
    --cores-request "4" --cores-limit "4" --memory-request "8Gi" --memory-limit "10Gi" `
    --storage-class-backups "nfs-csi " --storage-class-data "powerstore-xfs " --storage-class-logs "powerstore-xfs "--storage-class-datalogs "powerstore-xfs " `
    --volume-size-backups "500Gi" --volume-size-data "500Gi" --volume-size-logs "100Gi"--volume-size-datalogs "200Gi" --debug

## Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\sqlmi\custom.py", line 569, in arc_sql_mi_create
    raise CLIError(e)
knack.util.CLIError: ArmClient.__init__() got an unexpected keyword argument 'subscription_id'

cli.azure.cli.core.azclierror: ArmClient.__init__() got an unexpected keyword argument 'subscription_id'
az_command_data_logger: ArmClient.__init__() got an unexpected keyword argument 'subscription_id'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03FBB0B8>]

## AZ version
{
"azure-cli": "2.35.0",
"azure-cli-core": "2.35.0",
"azure-cli-telemetry": "1.0.6",
"extensions": {
"arcdata": "1.3.0",
"connectedk8s": "1.2.7",
"customlocation": "0.1.3",
"k8s-configuration": "1.5.0",
"k8s-extension": "1.1.0"
}
}

**Command Name**
`az sql mi-arc create
Extension Name: arcdata. Version: 1.3.0.`

**Errors:**
```
ArmClient.__init__() got an unexpected keyword argument 'subscription_id'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql mi-arc create --name {} --subscription {} --resource-group {} --location {} --custom-location {} --dev --replicas {} --cores-request {} --cores-limit {} --memory-request {} --memory-limit {} --storage-class-backups {} --storage-class-data {} --storage-class-logs {} --storage-class-datalogs {} --volume-size-backups {} --volume-size-data {} --volume-size-logs {} --volume-size-datalogs {} --debug`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0

Extensions:
arcdata 1.3.0
connectedk8s 1.2.7
customlocation 0.1.3
k8s-configuration 1.5.0
k8s-extension 1.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by rfsonders** [comment]
I upgraded to the latest data controller. Same issue remains.

Found 7 valid versions.  The current datacontroller version is v1.5.0_2022-04-05.
v1.5.0_2022-04-05 << current version
v1.4.1_2022-03-08
v1.4.0_2022-02-25
v1.3.0_2022-01-27
v1.2.0_2021-12-15
v1.1.0_2021-11-02
v1.0.0_2021-07-30
PS C:\Users\Rob\Documents\GitHub\Azure_Arc_DBaaS>

**Comment by SaurabhSharma-MSFT** [comment]
@rfsonders We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@rfsonders I managed to get it to work with the same command and environment , the only difference is I used subscription name. Can you please try and let us know?
`az sql mi-arc create --name Issue4646PS --resource-group Issue4655 --location eastus --subscription "<**subscription name**>" --custom-location eastus --dev --replicas 1 --cores-request "4" --cores-limit "4" --memory-request "8Gi" --memory-limit "10Gi" --storage-class-backups "nfs-csi " --storage-class-data "powerstore-xfs" --storage-class-logs "powerstore-xfs" --storage-class-datalogs "powerstore-xfs" --volume-size-backups "500Gi" --volume-size-data "500Gi" --volume-size-logs "100Gi" --volume-size-datalogs "200Gi"`
