### ISSUE TITLE
Unable to set attestation policy

### ISSUE THREAD

**Issue by Rhipeus** [Azure/azure-cli-extensions#4658]
## Describe the bug

**Command Name**
`az attestation policy set
Extension Name: attestation. Version: 0.2.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\nwilkinson\.azure\cliextensions\attestation\azext_attestation\manual\custom.py", line 253, in set_policy
    ).decode('ascii')
AttributeError: 'str' object has no attribute 'decode'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az attestation policy set --name {} --resource-group {} --attestation-type {} --new-attestation-policy-file {}`

## Expected Behavior
Should be able to set attestation policy

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0

Extensions:
attestation 0.2.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Rhipeus I am working internally with the Product Owners. I will update this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@Rhipeus Apologies for the late reply. We are having an insistent repro at our end as it works for a few users and fails for others. So we are still doing some research on this. I will update this thread once I hear back from product owners. We appreciate your patience on this.

**Comment by navba-MSFT** [comment]
@Rhipeus I was able to test the Attestation Policy using Powershell. Could you please test the same and let us know if that serves your requirement until the cause in CLI is identified ?

>$policyFormat = "Text"
$policy=Get-Content -path "C:\test\policy.txt" -Raw
$teeType = "OpenEnclave"
Set-AzAttestationPolicy   -Name "navbaattest9" -ResourceGroupName "navbaattest9" -Tee $teeType -Policy $policy -PolicyFormat $policyFormat

More Info [here](https://docs.microsoft.com/en-us/azure/attestation/quickstart-powershell#policy-management).

**Comment by jsntcy** [comment]
@Rhipeus, we'll release the fix in next sprint (around mid of June) since we are fully occupied in this sprint by Microsoft Build event.
As a workaround, the customer can run “pip install pyjwt=1.7.1” to force downgrade to pyjwt 1.7.1 to see if it works (It can work on my local machine).

**Comment by jsntcy** [comment]
Link similar issues: #4120, #3937

**Comment by navba-MSFT** [comment]
@Rhipeus Could you please let us know if you had a chance to look at the above comment and try the suggested workaround ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Rhipeus As mentioned in the above comment this issue would be fixed tentatively in the mid-June. Until then you can follow the workaround suggested [here](https://github.com/Azure/azure-cli-extensions/issues/4658#issuecomment-1110580549) and [here](https://github.com/Azure/azure-cli-extensions/issues/4658#issuecomment-1111787842). With that we will proceed with the closure of this thread. If you have any queries or need any assistance feel free to reopen this thread. We would be happy to help.
