### ISSUE TITLE
AZ Image Copy between different subscription not working

### ISSUE THREAD

**Issue by jayaakshayan** [Azure/azure-cli-extensions#466]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Description of issue (in as much detail as possible)

We were trying to use the “AZ image copy “ command to move the images to all subscription. Just observed the command is not working now and the same command was working previous month.

Error :- 
Getting os disk id of the source vm/image
Creating source snapshot
Getting sas url for the source snapshot with timeout seconds: 3600
Creating resource group: image-copy-rg
Target location count: 1
Starting async process for all locations
southindia - Creating target storage account (can be slow sometimes)
southindia - Creating container in the target storage account
command failed: ['/opt/az/bin/python3', '-m', 'azure.cli', 'storage', 'container', 'create', '--name', 'snapshots', '--account-name', 'southindiav18u7ns372o3z8', '--output', 'json', '--subscription', '********]
output: usage: az storage container create [-h] [--verbose] [--debug]
                                   [--output {json,jsonc,table,tsv,yaml}]
                                   [--query JMESPATH]
                                   [--account-name ACCOUNT_NAME]
                                   [--account-key ACCOUNT_KEY]
                                   [--connection-string CONNECTION_STRING]
                                   [--sas-token SAS_TOKEN] --name
                                   CONTAINER_NAME
                                   [--metadata METADATA [METADATA ...]]
                                   [--public-access {off,blob,container}]
                                   [--fail-on-exist] [--timeout TIMEOUT]
                                   [--auth-mode {login,key}]
                                   [--subscription _SUBSCRIPTION]
az storage container create: error: Storage account 'southindiav18u7ns372o3z8' not found.

-----

**Comment by tamirkamara** [comment]
Hi @jayaakshayan,

1. Can you confirm that the storage account **_southindiav18u7ns372o3z8_** is created and present in the target subscription?
1. Can you run the failed command manually and see what happens? The command and constructed by concatenating all the strings in "command failed" section like so: python3 -m azure.cli storage container and so on.

**Comment by jayaakshayan** [comment]
updated my comment: 

Can you confirm that the storage account southindiav18u7ns372o3z8 is created and present in the target subscription? 
when i run the az image copy command, the storage account is created in the target subscription. We see error only on the step of container creation
Can you run the failed command manually and see what happens? The command and constructed by concatenating all the strings in "command failed" section like so: python3 -m azure.cli storage container and so on:
 i run this command manually and the error is same. ['/opt/az/bin/python3', '-m', 'azure.cli', 'storage', 'container', 'create', '--name', 'snapshots', '--account-name', 'southindiaxk5tn9ndf4lcs4', '--output', 'json', '--subscription', '359f292b-8fe1-45ba-8b0f-e1295e7eb9ef']
bash: [/opt/az/bin/python3,: No such file or directory

**Comment by tamirkamara** [comment]
Hi,

The error is different - the command doesn't run.
Please try to replace the first few string with **az** like so: az storage container create...

**Comment by rgordon100** [comment]
I am seeing the same problem with 2.0.53 in that it fails to create the container after creating the storage account with the error "az storage container create: error: Storage account 'westeurope582whqavskv4f4' not found"

Unfortunately I am not able to downgrade to 2.0.52 as we are using features within the our script that were introduced in 2.0.53.

**Comment by deancsmith** [comment]
We are also experiencing the same error when copying between subscriptions on the Azure CLI version 2.0.54 and 2.0.55. Downgrading to 2.0.52 as discussed aboves makes the copy work as expected.

**Comment by tamirkamara** [comment]
I've been able to confirm this and submitted a bug on the azure-cli project: github/azure-cli#8397
Until this is resolved you should use cli version 52 (or lower)

**Comment by tamirkamara** [comment]
Azure/azure-cli#8404 is the updated issue that should resolve this in an upcoming version of the CLI

**Comment by tamirkamara** [comment]
@zikalino Can you please close this issue?

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by yungezz** [comment]
hi @jayaakshayan could you pls check if the fixing work for you? it's merged a while back.

**Comment by yungezz** [comment]
cc @qwordy
