### ISSUE TITLE
Parameter for IoT Edge device

### ISSUE THREAD

**Issue by boiledeggs** [Azure/azure-cli-extensions#468]
How do I create an IoT Edge device from az cli? I do not see any parameter for declaring a device enrolment as an IoT Edge device [here.](https://docs.microsoft.com/en-gb/cli/azure/ext/azure-cli-iot-ext/iot/dps/enrollment?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-dps-enrollment-create)
Also, it will be of great help if you explain all the parameter in details instead of just listing it out, most of them are self explanatory but an example with an explanation nevertheless would be a good idea.

Regards.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6820ec95-fd0d-3959-41fd-25f50ed7abd8
* Version Independent ID: c3a688ac-b257-5994-b8a9-0022a6a7dca7
* Content: [az iot dps enrollment](https://docs.microsoft.com/en-gb/cli/azure/ext/azure-cli-iot-ext/iot/dps/enrollment?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-dps-enrollment-update)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/dps/enrollment.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/dps/enrollment.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by boiledeggs** [comment]
I do add this parameter
`bash
--initial-twin-properties '{"deviceId": "tpmTest","status": "enabled","capabilities": {"iotEdge": "true"}}'`

but I still have to manually open the enrollment page and change it to IoT Edge Device = True.


![enrollment_manual_selection](https://user-images.githubusercontent.com/43533940/50987648-75dd5e00-14c7-11e9-8507-c960cf0d8884.png)

**Comment by eXXL** [comment]
I have the same issue.

**Comment by trclancy** [comment]
Same issue here, can't figure out how to set IoT Edge Device to True/False programmatically or through the az cli.

**Comment by arrownj** [comment]
Hi @digimaun , could you please help with this ?

**Comment by digimaun** [comment]
This issue is on our radar. We will release a new version of the extension to resolve this problem as soon as we can.

**Comment by digimaun** [comment]
We've released a new version of the IoT extension that covers this capability. Please [go here](https://github.com/Azure/azure-iot-cli-extension/issues/131#issuecomment-592266064) for more info. One missing element is waiting on the [extension index PR](https://github.com/Azure/azure-cli-extensions/pull/1315).

**Comment by digimaun** [comment]
#please-close

**Comment by digimaun** [comment]
@jlian

**Comment by jlian** [comment]
I think you have to do the please close without the code blocks
