### ISSUE TITLE
Error attempting to use 'az monitor app-insights continues-export create' - cannot deserialize object

### ISSUE THREAD

**Issue by jfair9** [Azure/azure-cli-extensions#4696]
## Describe the bug

Attempting to use the az cli to create a continues-export for app-insights.

**Command Name**
`az monitor app-insights component continues-export create
Extension Name: application-insights. Version: 0.1.16.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot deserialize as [ApplicationInsightsComponentExportConfiguration] an object of type <class 'dict'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/jfair01/.azure/cliextensions/application-insights/azext_applicationinsights/custom.py", line 319, in create_export_configuration
    return client.create(resource_group_name, application, export_config_request)
  File "/Users/jfair01/.azure/cliextensions/application-insights/azext_applicationinsights/vendored_sdks/mgmt_applicationinsights/v2015_05_01/operations/_export_configurations_operations.py", line 166, in create
    deserialized = self._deserialize('[ApplicationInsightsComponentExportConfiguration]', pipeline_response)
  File "/usr/local/lib/python3.8/site-packages/msrest/serialization.py", line 1368, in __call__
    return self._deserialize(target_obj, data)
  File "/usr/local/lib/python3.8/site-packages/msrest/serialization.py", line 1407, in _deserialize
    return self.deserialize_data(data, response)
  File "/usr/local/lib/python3.8/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/local/lib/python3.8/site-packages/msrest/serialization.py", line 1645, in deserialize_iter
    raise DeserializationError("Cannot deserialize as [{}] an object of type {}".format(
msrest.exceptions.DeserializationError: Cannot deserialize as [ApplicationInsightsComponentExportConfiguration] an object of type <class 'dict'>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az monitor app-insights component continues-export create --resource-group {} --app {} --record-types {} {} {} {} {} {} {} {} {} {} --dest-account {} --dest-container {} --dest-sas {} --dest-sub-id {}`

## Expected Behavior

Continuous-Export is successfully created

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit, Darwin 19.6.0
Python 3.8.7
Installer: PIP

azure-cli 2.35.0

Extensions:
datafactory 0.5.0
aks-preview 0.5.61
azure-devops 0.25.0
eventgrid 0.4.9
application-insights 0.1.16

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by jfair9** [comment]
Seeing a similar error when using powershell commands New-AzApplicationInsightsContinuousExport

**Comment by yonzhan** [comment]
monitor

**Comment by jfair9** [comment]
Powershell command is showing the following error. Both commands successfully create the Continous-Export

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : ***
x-ms-correlation-request-id   : ***
x-ms-routing-request-id       : WESTUS:20220418T224856Z:***
Date                          : Mon, 18 Apr 2022 22:48:55 GMT

Body:
{
  "ExportId": "***",
  "InstrumentationKey": "***",
  "RecordTypes": "Requests, Event, Messages",
  "ApplicationName": "***",
  "SubscriptionId": "***",
  "ResourceGroup": "***",
  "DestinationStorageSubscriptionId": "***",
  "DestinationStorageLocationId": "southcentralus",
  "DestinationAccountId": "/subscriptions/.../resourceGroups/..../providers/Microsoft.Storage/storageAccounts/...",
  "DestinationType": "Blob",
  "IsUserEnabled": "True",
  "LastUserUpdate": "2022-04-18T22:48:56.7574722Z",
  "NotificationQueueEnabled": "False",
  "DestinationKustoCluster": null,
  "DestinationKustoDatabase": null,
  "TransformationType": "Default",
  "ExportStatus": "Preparing",
  "LastSuccessTime": null,
  "LastGapTime": null,
  "PermanentErrorReason": "None",
  "StorageName": "***",
  "ContainerName": "logs"
}


New-AzApplicationInsightsContinuousExport: Unable to deserialize the response.
```

**Comment by navba-MSFT** [comment]
@jfair9 Thanks for reaching out to us and sharing this feedback. I am looking into this issue. I will update this thread once I have more details. In the meantime, Could you please share the version of the module Az.ApplicationInsights ?

>Import-Module -Name Az.ApplicationInsights
Get-Module -Name Az.ApplicationInsights

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jfair9 Though the [New-AzApplicationInsightsContinuousExport ](https://docs.microsoft.com/en-us/powershell/module/az.applicationinsights/new-azapplicationinsightscontinuousexport?view=azps-7.4.0)command failed with the` Unable to deserialize the response` error it did execute and successfully create the continuous export configuration.

You can confirm the same by running the [get-azapplicationinsightscontinuousexport](https://docs.microsoft.com/en-us/powershell/module/az.applicationinsights/get-azapplicationinsightscontinuousexport?view=azps-7.4.0) PS cmd. Hope this helps.

**Comment by jfair9** [comment]
> 
New-AzApplicationInsightsContinuousExport: Unable to deserialize the response.
DEBUG: AzureQoSEvent: Module: Az.ApplicationInsights:1.2.0; CommandName: New-AzApplicationInsightsContinuousExport; PSVersion: 7.1.0; IsSuccess: False; Duration: 00:00:03.2547577; Exception: Unable to deserialize the response.;
DEBUG: Finish sending metric.
DEBUG: 8:38:55 AM - NewAzureApplicationInsightsContinuousExportCommand end processing.

**Comment by navba-MSFT** [comment]
@jfair9 Thanks for getting back. While we are investigating this, Could you please try the workaround of adding the switch  
`-ErrorAction SilentlyContinue ` and check if that helps to avoid the pipeline from getting aborted? Awaiting your reply.

**Comment by jfair9** [comment]
@navba-MSFT The -ErrorAction must be for powershell? Is there an equivalent version of ErrorAction for the AZ Cli that Im not seeing in the documentation?

**Comment by navba-MSFT** [comment]
@jfair9 A common scenario to redirect streams is when the symbol > is used to write the output of the CLI command in a file. It redirects the standard output - STDOUT - to the file added as a parameter.
If you would like to suppress the errors, you can redirect the output of the error stream — STDERR.
To do it you simply need to add 2>nul after the CLI command, which means that the second stream (STDERR) will be redirected to null.

>az monitor app-insights component continues-export create --resource-group {} --app {} --record-types {} {} {} {} {} {} {} {} {} {} --dest-account {} --dest-container {} --dest-sas {} --dest-sub-id {} **2>nul**

**Comment by navba-MSFT** [comment]
@jfair9 I had an internal discussion with our SME team regarding this issue. We recommend all of our customers to stop using Continuous Export and use Diagnostics Settings instead, as the former has already been deprecated. Please, refer to the following [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/export-telemetry). 

Note: Switching to Diagnostics Settings will require them to migrate their Application Insights resources from the classic to the workspace-based model. Please, refer to the following [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/convert-classic-resource). 

There are certain known issues/behavior you want to keep in mind when migrating, like
[Stream Analytics integration](https://docs.microsoft.com/en-us/azure/stream-analytics/app-insights-export-sql-stream-analytics)

![image](https://user-images.githubusercontent.com/57353862/165016232-52c5ab2b-e287-4963-8a6f-0e0e9bdea81e.png)

**Comment by navba-MSFT** [comment]
@jfair9 The fix for this issue has been released. I am able to run the CLI command just fine now. 

>az monitor app-insights component continues-export create --resource-group MyRGName --app MyApp --record-types Requests Event --dest-account MyStorage  --dest-container MyContainer --dest-sas "sv=2021-04-10&se=2072-04-19T10%3A44%3A36Z&sr=c&sp=w&sig=Xal38IIXV******************gvlM%3D" --dest-sub-id 7dXXXX24-XXXX-XXXX-a209-9fXXXXXe7d0 --debug

Please run your AzCLI command and test the functionality again. If you face any issues, please feel free to reopen this Github thread. We would be happy to assist you further.
