### ISSUE TITLE
Business Critical - Direct mode - az create fails

### ISSUE THREAD

**Issue by rfsonders** [Azure/azure-cli-extensions#4705]
## Describe the bug

Attempting to deploy a Business Critical tier SQL MI - Direct mode DC.

**Command Name**
`az sql mi-arc create
Extension Name: arcdata. Version: 1.3.1.`

**Errors:**
```
Deployment hangs with this message.

Current deployment state is 'Wait'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
SQL MI does list in the portal. No events are logged in the kubernetes cluster.

- _Put any pre-requisite steps here..._
    az sql mi-arc create --name bizcrtcl-01 --resource-group PowerStoreAzureArc-RG   --location "East US" --custom-location "EdenPrairieNM"   --replicas 3 `
    --cores-request "24" --cores-limit "24" --memory-request "128Gi" --memory-limit "128Gi" `
    --storage-class-backups "nfs-csi" --storage-class-data "powerstore-xfs" --storage-class-logs "powerstore-xfs" --storage-class-datalogs "powerstore-xfs" `
    --volume-size-backups "500Gi"  --volume-size-data "950Gi" --volume-size-logs "100Gi"--volume-size-datalogs "500Gi"  

## Expected Behavior
Business critical pod should deploy without issue.
## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0

Extensions:
arcdata 1.3.1
connectedk8s 1.2.8
customlocation 0.1.3
k8s-configuration 1.5.1
k8s-extension 1.2.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by rfsonders** [comment]
This ticket can be closed.  I neglected to add the --tier BusinessCritical switch
