### ISSUE TITLE
az ssh config crsh under wsl

### ISSUE THREAD

**Issue by vladimirkrasilev** [Azure/azure-cli-extensions#4743]
## Describe the bug

**Command Name**
`az ssh config
Extension Name: ssh. Version: 0.1.5.`

**Errors:**
```
'Profile' object has no attribute 'get_msal_token'
Traceback (most recent call last):
python3.8\site-packages\knack\cli.py, ln 231, in invoke
    cmd_result = self.invocation.execute(args)
cli\core\commands\__init__.py, ln 658, in execute
    raise ex
cli\core\commands\__init__.py, ln 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cliextensions\ssh\azext_ssh\custom.py, ln 48, in _do_ssh_op
    cert_file, username = _get_and_write_certificate(cmd, public_key_file, None)
cliextensions\ssh\azext_ssh\custom.py, ln 58, in _get_and_write_certificate
    _, certificate = profile.get_msal_token(scopes, data)
AttributeError: 'Profile' object has no attribute 'get_msal_token'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh config --ip {} --file {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: 

azure-cli 2.20.0 *

Extensions:
hcs 0.1.0
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@vladimirkrasilev Thanks for reaching out to us and sharing this feedback. We are looking into this issue and provide an update shortly.

**Comment by navba-MSFT** [comment]
@vladimirkrasilev I wasn't able to reproduce this issue on my box. You are using an older version of the `ssh` extension. Please update your `ssh` extension to the most recent version by running the below command:

>az extension update --name ssh

Also on a side note, you should also use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#install-or-update) of AzureCLI. Please let me know if you still face the same issue after following the above suggestion. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@vladimirkrasilev I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by vladimirkrasilev** [comment]
The az update failed as well.
The problem was specific for the hosts, where cygwin was installed and az started from wsl.
Fixed by removal cygwin from PATH.
