### ISSUE TITLE
azure cli does not yet support these options

### ISSUE THREAD

**Issue by fatal-exception** [Azure/azure-cli-extensions#476]
Trying to run "az network firewall" results in the following:
"""
az network firewall
az network: 'firewall' is not in the 'az network' command group. See 'az network --help'.
"""

This is the case with azure-cli 2.0.55 and the azure_mgmt_networking 2.4.0 library, the latest available today.

Your documentation implies this feature is currently released - but this is not correct. The official microsoft/azure-cli docker image (212ab6975164 at time of writing) also does not support this option. Can you say when the Azure CLI will be updated, so the commands on this page can be run?

Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc2adff3-2bac-3c0a-e31a-5c5c40716a47
* Version Independent ID: b6a4a504-0f37-eca9-3987-1fcf7162a696
* Content: [az network firewall](https://docs.microsoft.com/en-gb/cli/azure/ext/azure-firewall/network/firewall?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-firewall/network/firewall.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-firewall/network/firewall.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by mxplusb** [comment]
@tjprescott can we update the docs to include that step?

**Comment by tjprescott** [comment]
That document is automatically generated. If there were a blog post referencing these commands, it should note that the extension needs to be installed. I don't believe any of the extensions reference pages self-identify that they need to be installed first.

**Comment by fatal-exception** [comment]
thanks folks, but this still doesn't result in the documentation being usable. Can a dialogue box be added to the docs to say that an extension needs to be installed?
