### ISSUE TITLE
Update offer type in account create command

### ISSUE THREAD

**Issue by parthmsft** [Azure/azure-cli-extensions#4766]
### Extension name (the extension in question)
- **subscription**

### Description of issue (in as much detail as possible)

-----
We need to update the offer type for `az account create ...` command.

The `--offer-type` option of above mentioned command currently supports  **MS-AZR-0017P** and  **MS-AZR-0148P** offer types.

We need to support two more offer types **MS-AZR-USGOV-0017P** and  **MS-AZR-USGOV-0003P** to create subscription in Government Cloud(FairFax) .

**Comment by yonzhan** [comment]
@jiasli for awareness
