### ISSUE TITLE
Data Controller upgrade failure

### ISSUE THREAD

**Issue by rfsonders** [Azure/azure-cli-extensions#4783]
## Describe the bug

**Command Name**
`az arcdata dc update
Extension Name: arcdata. Version: 1.4.0.`

**Errors:**
```
(ResourceGroupNotFound) Resource group 'arc-services-ns' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'arc-services-ns' could not be found.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az arcdata dc update --name {} --resource-group {} --auto-upload-logs {} --debug`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0

Extensions:
arcdata 1.4.0
connectedk8s 1.2.8
customlocation 0.1.3
k8s-configuration 1.5.1
k8s-extension 1.2.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by rfsonders** [comment]
PS C:\Users\Rob> az arcdata dc update --name pstoredc01 --resource-group arc-services-ns --auto-upload-logs true --debug
cli.knack.cli: Command arguments: ['arcdata', 'dc', 'update', '--name', 'pstoredc01', '--resource-group', 'arc-services-ns', '--auto-upload-logs', 'true', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01C38BB0>, <function OutputProducer.on_global_arguments at 0x01CFD4F0>, <function CLIQuery.on_global_arguments at 0x01D1B148>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'arcdata': ['azext_arcdata']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: arcdata                   1.060        17        49  C:\Users\Rob\.azure\cliextensions\arcdata
cli.azure.cli.core: Total (1)                 1.060        17        49
cli.azure.cli.core: Loaded 17 groups, 49 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : arcdata dc update
cli.azure.cli.core: Command table: arcdata dc update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x040AB070>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\Rob\.azure\commands\2022-05-06.16-22-19.arcdata_dc_update.6712.log'.
az_command_data_logger: command args: arcdata dc update --name {} --resource-group {} --auto-upload-logs {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x040DDB20>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x040F7100>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x040F7190>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01CFD538>, <function CLIQuery.handle_query_parameter at 0x01D1B190>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x040F7148>]
az_command_data_logger: extension name: arcdata
az_command_data_logger: extension version: 1.4.0
cli.azext_arcdata.core.cli_client: {'name': 'pstoredc01', 'resource_group_name': 'arc-services-ns', 'auto_upload_logs': 'true', 'auto_upload_metrics': None, 'use_k8s': None, 'namespace': None, 'desired_version': None, 'maintenance_start': None, 'maintenance_duration': None, 'maintenance_recurrence': None, 'maintenance_time_zone': None, 'maintenance_enabled': None, 'no_wait': False}
cli.azext_arcdata.core.services: Service dispatch key: 'arcdata dc'
cli.azext_arcdata.core.services: Using subscription: 047d5a79-16ab-4705-afe1-9139b0cbe512
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\Rob\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\Rob\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
cli.azure.cli.core: Current cloud config:
AzureCloud
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=(), kwargs={}
cli.azure.cli.core.auth.util: No scope is provided by the SDK, use the CLI-managed resource.
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 79e3c357-089a-4b0e-ba83-d2acfe043662
cli.azext_arcdata.core.identity: ArcDataCliCredential.get_token succeeded
cli.azure.cli.core: Current cloud config:
AzureCloud
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=(), kwargs={}
cli.azure.cli.core.auth.util: No scope is provided by the SDK, use the CLI-managed resource.
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 9c37aac6-13c4-424c-8863-aebaeac5726a
cli.azext_arcdata.core.identity: ArcDataCliCredential.get_token succeeded
cli.azure.cli.core: Current cloud config:
AzureCloud
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=(), kwargs={}
cli.azure.cli.core.auth.util: No scope is provided by the SDK, use the CLI-managed resource.
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 7308408e-f43c-47b2-b3fe-c437effcf80d
cli.azext_arcdata.core.identity: ArcDataCliCredential.get_token succeeded
cli.azext_arcdata.core.services: Runtime mode [--use-k8s]: None
cli.azext_arcdata.core.services: Service proxy type: ArmDataControllerServiceProxy
cli.azext_arcdata.core.services: Public service handle name: dc
cli.azext_arcdata.arm_sdk.azure.azure_resource_client: Getting Azure resource: '/subscriptions/047d5a79-16ab-4705-afe1-9139b0cbe512/resourcegroups/arc-services-ns/providers/Microsoft.AzureArcData/dataControllers/pstoredc01', api version: '2022-03-01-preview'
cli.azure.cli.core: Current cloud config:
AzureCloud
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ba50e21e-fd37-434f-9c33-daf3ba071822/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.azure.com/.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.azure.com/.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 0f3f7fbf-8d62-4d0e-a6e8-b6f06ef8279c
cli.azext_arcdata.core.identity: ArcDataCliCredential.get_token succeeded
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/047d5a79-16ab-4705-afe1-9139b0cbe512/resourcegroups/arc-services-ns/providers/Microsoft.AzureArcData/dataControllers/pstoredc01?api-version=2022-03-01-preview HTTP/1.1" 404 107
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\dc\custom.py", line 150, in dc_update
    return client.services.dc.update(cvo)
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\core\services.py", line 396, in update
    return self._arm_client.update_dc(
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\arm_sdk\client.py", line 324, in update_dc
    return self._resource_client.update_dc_resource(
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\arm_sdk\azure\azure_resource_client.py", line 97, in update_dc_resource
    dc_resource = self.get_generic_azure_resource(
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\arm_sdk\azure\azure_resource_client.py", line 558, in get_generic_azure_resource
    resource = self.get_generic_azure_resource_by_id(arm_id, api_version)
  File "C:\Users\Rob\.azure\cliextensions\arcdata\azext_arcdata\arm_sdk\azure\azure_resource_client.py", line 591, in get_generic_azure_resource_by_id
    resource = resource_client.resources.get_by_id(
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/resources/v2021_04_01/operations/_resources_operations.py", line 1554, in get_by_id
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/exceptions.py", line 105, in map_error
azure.core.exceptions.ResourceNotFoundError: (ResourceGroupNotFound) Resource group 'arc-services-ns' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'arc-services-ns' could not be found.

cli.azure.cli.core.azclierror: (ResourceGroupNotFound) Resource group 'arc-services-ns' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'arc-services-ns' could not be found.
az_command_data_logger: (ResourceGroupNotFound) Resource group 'arc-services-ns' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'arc-services-ns' could not be found.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x040AB190>]
az_command_data_logger: exit code: 3
cli.__main__: Command ran in 2.611 seconds (init: 0.626, invoke: 1.985)
telemetry.save: Save telemetry record of length 3252 in cache
telemetry.check: Negative: The C:\Users\Rob\.azure\telemetry.txt was modified at 2022-05-06 16:21:42.009065, which in less than 600.000000 s
PS C:\Users\Rob> az feedback

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@rfsonders Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. I looked at the error message and I see the resource URI as below:

>Azure resource: '/subscriptions/**047d5a79-XXXXXXX-afe1-9139b0cbe512**/resourcegroups/**arc-services-ns**/providers/Microsoft.AzureArcData/dataControllers/pstoredc01', api version: '2022-03-01-preview'

It seems like **arc-services-ns** resource group is not present inside this **047d5a79-XXXXXXX-afe1-9139b0cbe512** subscription.

So please run the below AzCLI command to set your right subscription id and then run your CLI command. Hope this helps.

>az account set --subscription "123456-XXXX-XXXX-XXX-9101112131"

Please let me know if you have any queries on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@rfsonders I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by rfsonders** [comment]
We can close. I deleted the namespace and recreated with the 1.6 DC

Regards.


Robert F. Sonders
+1.720.530.0567

LinkedIn

@RobertSonders

**Comment by navba-MSFT** [comment]
@rfsonders  Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
