### ISSUE TITLE
Bad idea to remove : az costmanagement query

### ISSUE THREAD

**Issue by Maarc-D** [Azure/azure-cli-extensions#4795]
### Related command

`az costmanagement query`

### Extension name (the extension in question)

costmanagement

### Description of issue (in as much detail as possible)

`az costmanagement query` was removed in [0.2.1](https://github.com/Azure/azure-cli-extensions/blob/main/src/costmanagement/HISTORY.rst#021) but I think it was a bad idea. It is explain in the release note that it could be replace by `az costmanagement export` but it's really not the same usage. As for export you need a storage account, and not for query. And furrthermore for some automation scripts Query is more efficient than export.

-----

**Comment by yonzhan** [comment]
costmanagement

**Comment by jsntcy** [comment]
Query API is on the path to becoming a private api that is not exposed to external customers any longer.
