### ISSUE TITLE
document the default value of --first 

### ISSUE THREAD

**Issue by martgras** [Azure/azure-cli-extensions#482]
[Enter feedback here]
The default value of 100 results for azure graph query if --first is omitted should be documented 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75d1021b-9184-56de-3a65-4680868c9143
* Version Independent ID: f2fb2ab8-c0c6-5350-a99a-5a5b90e2b14b
* Content: [az graph](https://docs.microsoft.com/en-us/cli/azure/ext/resource-graph/graph?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/resource-graph/graph.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/resource-graph/graph.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by martgras** [comment]
it is already documented when running az graph query --help but not on https://docs.microsoft.com/en-us/cli/azure/ext/resource-graph/graph?view=azure-cli-latest

**Comment by yonzhan** [comment]
resource graph

**Comment by lilyjma** [comment]
@martgras are you still experiencing the issue?

**Comment by snaheth** [comment]
@martgras This has been updated on the [documentation page you shared above](https://docs.microsoft.com/en-us/cli/azure/ext/resource-graph/graph?view=azure-cli-latest#ext_resource_graph_az_graph_query-optional-parameters).
