### ISSUE TITLE
az aks create failed to create cluster with system assigned identity

### ISSUE THREAD

**Issue by aneran01** [Azure/azure-cli-extensions#4820]
## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.42.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
can't set attribute
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/aniket/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 971, in aks_create
    nat_gateway_models = AKSPreviewModels(cmd, CUSTOM_MGMT_AKS_PREVIEW).nat_gateway_models
  File "/home/aniket/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 101, in __init__
    self.init_nat_gateway_models()
  File "/home/aniket/.azure/cliextensions/aks-preview/azext_aks_preview/decorator.py", line 121, in init_nat_gateway_models
    self.nat_gateway_models = nat_gateway_models
AttributeError: can't set attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --network-plugin {} --service-cidr {} --dns-service-ip {} --docker-bridge-address {} --vnet-subnet-id {}`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

Extensions:
aks-preview 0.5.42

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@aneran01 Thanks for reaching out to us and sharing this feedback. We are looking into this issue. We will provide an update on this once we have more details on this.

**Comment by navba-MSFT** [comment]
@aneran01 I was able to run the same above command to create the AKS cluster and it worked just fine.

Could you please upgrade your `aks-preview` extension and try to run the below command and check if that helps ? Awaiting your reply.

>az extension update --name aks-preview         # command to upgrade your extension.

The command I used to create my AKS cluster:
>az aks create --resource-group MyRG --name MyAKSName --node-count 1 --network-plugin **azure** --service-cidr 10.2.0.0/24 --dns-service-ip 10.2.0.10 --docker-bridge-address 172.16.0.1/16 --vnet-subnet-id /subscriptions/XXXXXX/resourceGroups/MyRG/providers/Microsoft.Network/virtualNetworks/MyVNET/subnets/MySubnet --generate-ssh-keys

Hope this helps.

**Comment by navba-MSFT** [comment]
@aneran01 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@aneran01 The action is pending on you to test the above action plan. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by yeroc-sebrof** [comment]
Hi @navba-MSFT, just commenting to let you know I had the same error output as above but your solution solved it for me

> > az extension update --name aks-preview         # command to upgrade your extension.

Thank you!
