### ISSUE TITLE
az connectedk8s install appears to be looping and reinstalling

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli-extensions#4878]
Windows 11
PowerShell 7.2.4

When prompted to install the `connectedk8s` extension, the install appears to be looping.  Please see the below screen print where the customer is prompted to continually reinstall the extension.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/58762114/169865371-22b69d43-222b-49c0-9a5d-2829d6ad5063.png)

CCing @mikefrobbins who originally reported this issue

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@dbradish-microsoft Thanks for reaching out to us and sharing this feedback. 
As an isolation step, Could you please have the customer open the CMD prompt (not PS prompt) and then run the below command to install the extension separately ? 

>az extension add --name connectedk8s

Once the installation is done, then try running the below command and check if that works. Awaiting your reply.

>az connectedk8s enable-features -n clusterName -g resourceGroupName --features cluster-connect custom-locations

**Comment by dbradish-microsoft** [comment]
@mikefrobbins, this latest <reply> is for you.

**Comment by navba-MSFT** [comment]
@dbradish-microsoft @mikefrobbins Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
