### ISSUE TITLE
az monitor app-insights web-test create monitor url with query string ( & ) 

### ISSUE THREAD

**Issue by drimondi1** [Azure/azure-cli-extensions#4902]
## Describe the bug
I tried to create a web-test for url with query string but the "&"  not allow to complete the request.
no problem with url whitout parameters.
no problem using the portal (with query string as well). 

Thanks In advance for the support

**Command Name**
`az monitor app-insights web-test create
Extension Name: application-insights. Version: 0.1.16.`

**Errors:**
```
'test2' is not recognized as an internal or external command,
operable program or batch file.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

az monitor app-insights web-test create --location "west Europe" `
                    --description $desc --enabled true --frequency 900 `
                    --resource-group $rg --name $name `
                    --web-test-kind "standard" `
                    --locations Id="emea-nl-ams-azr" `
                    --locations Id="us-ca-sjc-azr" `
                    --locations Id="us-il-ch1-azr" `
                    --locations Id="us-va-ash-azr" `
                    --locations Id="us-tx-sn1-azr" `
                    --defined-web-test-name $name `
                    --parse-requests true `
					--http-verb "GET" `
					--tags hidden-link:/subscriptions/xxxxxx/resourceGroups/rg-websites/providers/microsoft.insights/components/ai name=Resource`
                    --request-url "https://www.google.com?test=test&test2=test2"

- _Put any pre-requisite steps here..._
- `az monitor app-insights web-test create --location {} --description {} --enabled {} --frequency {} --resource-group {} --name {} --web-test-kind {} --locations {} --locations {} --locations {} --locations {} --locations {} --defined-web-test-name {} --parse-requests {} --http-verb {} --tags {} {} {} --request-url {"https://www.google.com?test=test&test2=test2"}`

## Expected Behavior
The complete web site url ( & included ) been accepted
## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
application-insights 0.1.16
interactive 0.4.5

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
monitor

**Comment by YuanyuanNi** [comment]
Hi:
     @drimondi1 'az monitor app-insights web-test create' can create monitor url with & from myside, the command I use as below,FYI :
az monitor app-insights web-test create -n {name} -l {loc} -g {rg} --enabled true --frequency 900 --web-test-kind {kind} --locations Id={location_id1} --defined-web-test-name {name} --http-verb {http_verb} --request-body {request_body} --request-url "https://www.google.com?test=test&test2=test2" --retry-enabled true --synthetic-monitor-id {name} --timeout 120 --ssl-lifetime-check 100 --ssl-check true --tags {tag}=Resource
Best wishes.
