### ISSUE TITLE
Request for new release of DnsResolver extension

### ISSUE THREAD

**Issue by harmen-msft** [Azure/azure-cli-extensions#4908]
### Related command
N/A

### Extension name (the extension in question)
DnsResolver

### Description of issue (in as much detail as possible)
The initial extension was generated a while back here: https://github.com/Azure/azure-cli-extensions/pull/4676

The Swagger file for the service has been slightly updated and requires a new CLI extension to be generated and published: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dnsresolver/resource-manager/Microsoft.Network/preview/2020-04-01-preview/dnsresolver.json

Can you please generate the new release for the extension?

Edit: Please generate based on this newer Swagger spec: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dnsresolver/resource-manager/Microsoft.Network/stable/2022-07-01/dnsresolver.json

**Comment by yonzhan** [comment]
dnsResolver

**Comment by arpit-gagneja** [comment]
@yonzhan @necusjz: There is an update. We have merged the first stable API version for our GA.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dnsresolver/resource-manager/Microsoft.Network/stable/2022-07-01/dnsresolver.json

We would want the generated Azure CLI for this GA version now.

**Comment by harmen-msft** [comment]
@yonzhan @necusjz @arpit-gagneja We will have a new manifest around the first week of September. Can you create this release around mid-September? 

If you could specify a date, that would be appreciated.

**Comment by necusjz** [comment]
@harmen-msft, if the new manifest is deployed on time, we could deliver it on 16th Sept.

**Comment by harmen-msft** [comment]
@necusjz That works, let's go with Sept 16, 2022. Thanks.

**Comment by harmen-msft** [comment]
@necusjz on a side note, do you support Swagger version 3.0 for CLI generation and thus would auto generation work on it?

**Comment by necusjz** [comment]
> @necusjz on a side note, do you support Swagger version 3.0 for CLI generation and thus would auto generation work on it?

We only support Swagger 2.0 now.

**Comment by harmen-msft** [comment]
@necusjz It appears the manifest has been rolled out so you can move ahead with the new release for the DnsResolver extension. Thanks.
