### ISSUE TITLE
Broken link for AzureAutomationTutorial.ps1 in README.md

### ISSUE THREAD

**Issue by santaji1986** [Azure/azure-cli-extensions#4947]
Link is broken, url returns 404 for AzureAutomationTutorial.ps1 in [README.md](https://github.com/Azure/azure-cli-extensions/tree/main/src/automation#readme)
Please use Url checker in github actions to avoid such issues in future.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@santaji1986 Thanks for reaching out to us and sharing this feedback. We are looking into this. We will provide an update once we have more details.

**Comment by navba-MSFT** [comment]
PR has been filed to address this.

**Comment by navba-MSFT** [comment]
@santaji1986 The PR is under review. If you have any follow-up questions in the meantime, please feel free to ask.
