### ISSUE TITLE
az iot hub monitor-events hangs when binary data (non json)

### ISSUE THREAD

**Issue by ksaye** [Azure/azure-cli-extensions#4966]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command

az --version
azure-cli                         2.30.0 *

core                              2.30.0 *
telemetry                          1.0.6

Extensions:
azure-iot                         0.12.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/ksaye/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Oct 29 2021, 10:11:58)
[GCC 7.5.0]

### Extension name (the extension in question)
as iot hub monitor-events

### Description of issue (in as much detail as possible)

Using the command az iot hub monitor-events fails when the message contains binary content.

When monitoring a hub that receives both json and binary, the az iot hub monitor-events hangs when binary content comes across.

Using the following commands:
``
az iot hub monitor-events --login 'Ho******Y0=' --cg ksaye --props all
``

works fine with JSON UNTIL binary data and it hangs without any message.

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ksaye Thanks for reaching out to us and sharing this feedback. Could you Please test with the most recent version of azure-iot extension and [AzureCLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#install-or-update) and check if that helps ?

>az extension update -n azure-iot

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ksaye Could you please run the same command again with --debug switch and share the output with me ? If you are internal to Microsoft you can reach out to me offline with the details. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ksaye I had reached out to the Product Owners in the background and got an update from them. I am sharing this update here.

>We do not support binary data input for the _az iot hub commands_. Only **text** and **JSON** are supported.


However, it is a bad customer experience when the hub becomes unresponsive, hence they are adding a task on their side to fail graciously and display a proper error message when an un-supported input data type is encountered.

Also we have shared the feedback / idea of being able to view real-time binary data being sent to IoT Hub using monitor-events with them. They will prioritize the improvements (among our other IoT CLI priorities) to be included in a future release. So no ETA on when this would be included in future releases. Hope this answers.

Please let me know if you need any further assistance on this or we are good to proceed with archival of this issue for now.

**Comment by ksaye** [comment]
Thanks for such a thorough response.  Very happy to close this issue.

I agree it is a bad customer experience and displaying a 'non text / json' message is a fine answer.

While I have not seen this as a common pattern, technologies like Stream Analytics understand that the payload could be gzip or bzip, meaning binary content.
