### ISSUE TITLE
az graph query --first maximum value

### ISSUE THREAD

**Issue by MaxMelcher** [Azure/azure-cli-extensions#498]
The text states that the maximum is 5000 values if you specify --first 5000. 
I tested it today and only get 1000 results back.  

Could you please verify the maximum? 

Thanks,
Max

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75d1021b-9184-56de-3a65-4680868c9143
* Version Independent ID: f2fb2ab8-c0c6-5350-a99a-5a5b90e2b14b
* Content: [az graph](https://docs.microsoft.com/en-us/cli/azure/ext/resource-graph/graph?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/resource-graph/graph.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/resource-graph/graph.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
resource graph

**Comment by chiragg4u** [comment]
Thanks @MaxMelcher for the question the service only returns 1000 records at once; CLI has the logic to get 5 pages. Please connect directly with the product team through email @ resourcegraphsupport@microsoft.com.

**Comment by snaheth** [comment]
We've corrected the Azure CLI documentation to reflect a maximum `--first` value of 1000 when using the Azure CLI.

If you project `id` in your query and your result is greater than 1000 rows, you can use the `$skipToken` that's returned in the response body to retrieve the next page of results by passing it as the value for the `--skip-token` parameter in a new call to `az graph query`

**Comment by yangchengs** [comment]
The document https://docs.microsoft.com/en-us/azure/governance/resource-graph/concepts/work-with-data
did not correct the number 5000.
