### ISSUE TITLE
Unable to connect to Postgres flexible server - Database dump & restore using az-cli

### ISSUE THREAD

**Issue by azeem2020** [Azure/azure-cli-extensions#5016]
## Bug/Error

**Command Name**
`az postgres flexible-server connect
Extension Name: rdbms-connect. Version: 1.0.2.`

**Errors:**
```
Unable to connect to flexible server: could not translate host name "pgxxxx-001.postgres.database.azure.com" to address: Unknown host
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres flexible-server connect -n {} -u {} -d {} -p {}`

## Expected Behavior
The connection using CLI is essential so we can continue with dump & restore to Azure Storage. For Single Server, below is the guide and same behavior expecting for Azure PostgreSQL Flexible Server.

https://docs.microsoft.com/en-us/azure/postgresql/migrate/how-to-migrate-using-dump-and-restore

## Azure PostgreSQL Flexible Server Resource Overview
```
**Network connectivity:**
Connectivity method: Private access (VNet Integration)

**Connection Source:**
Corporate Network

**Destination:**
PostgreSQL Flexible Server (Private IP)
```

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
rdbms-connect 1.0.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by RakeshMohanMSFT** [comment]
@azeem2020 Thank you for reaching out we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@azeem2020 can you please go through these articles once? https://stackoverflow.com/questions/67982207/why-cant-i-connect-to-azure-postgresql-flexible-using-hostname and https://docs.microsoft.com/en-us/azure/dns/private-dns-overview

**Comment by azeem2020** [comment]
The workaround works fine. Thank you for the articles, can we rollout this change globally within Organizations instead to update individual's host file?

**Comment by RakeshMohanMSFT** [comment]
@azeem2020 Glad to know that the provided solution helped, I am not sure I quite understand your question, can you please elaborate?

**Comment by azeem2020** [comment]
The given solution in [article ](https://stackoverflow.com/questions/67982207/why-cant-i-connect-to-azure-postgresql-flexible-using-hostname) is to update Desktop/PC's Host file entries with PostgreSQL FQDN and Private IP address.

There are number of developers who will access the DB server(s) and instead to update individual's PC host file for each server, we want to make entry in organization's DNS server against private IP. What are the possibilities to make that change globally?

**Comment by teo113** [comment]
Also having this issue with host name not being recognised. I'm connecting from within our corporate VPN, to a PostrgeSQL flexible server (name.postgres.database.azure.com) created in an existing VNet & subnet, with a new private DNS zone (name.private.postgres.database.azure.com). Can we have an update on this issue?
Access to Azure from our network has been configured on the on-prem firewall and the Azure firewall.

**Comment by jorgelaranjo** [comment]
Use the name without `postgres.database.azure.com`

eg if your DB Is `my-db.postgres.database.azure.com` enter 

`az postgres flexible-server connect --name=my-db`

**Comment by nachoalonsoportillo** [comment]
For VNET integrated instances of Flexible Server you need to either use an Azure Private DNS zone or configure a custom DNS server so that the name can be resolved from the host from which you're initiating the request. More information can be found in the documentation https://learn.microsoft.com/azure/postgresql/flexible-server/concepts-networking-private
