### ISSUE TITLE
No matching extensions for 'webpubsub'

### ISSUE THREAD

**Issue by thomas3577** [Azure/azure-cli-extensions#5038]
When I run the command `az extension add --upgrade --name webpubsub`, I get the following error message:

_No matching extensions for 'webpubsub'. Use --debug for more information._

When I use the command `az extension list-available --output table` to output a list of all extensions, I cannot find **webpubsub** in the list.

It currently does not seem to be possible to add the extension **webpubsub** via this path.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by thomas3577** [comment]
@PramodValavala-MSFT Thanks, and sorry for wasting your time. I guess the reason was really that I had an older version of Azure CLI installed.
