### ISSUE TITLE
Issue with  k8s-extension

### ISSUE THREAD

**Issue by jereesh** [Azure/azure-cli-extensions#5039]
### Related command
az extension add --name k8s-extension

### Extension name (the extension in question)
k8s-extension

### Description of issue (in as much detail as possible)

When 'k8s-extension is being installed using az command error occurred

To Reproduce

Go to power shell where azure cli is installed
type az extension add --name k8s-extension
See error "No matching extensions for 'k8s-extension'. Use --debug for more information."
Expected behavior
The Extension is successfully installed

Environment (please complete the following information):

OS: Windows 10
Shell: powershell
Az CLI version: 2.0.80
Python version (if pip installed): 3.9.13

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@jereesh I can confirm this does work. Could you try upgrading to the latest Azure CLI version (2.37.0) and try again?
