### ISSUE TITLE
Document the list of properties settable for the "az iot edge deployment update --set"

### ISSUE THREAD

**Issue by hubez** [Azure/azure-cli-extensions#504]
What are the names of all the properties that can be given to set? It's a complex option so examples would be great!

What is the name of the property, and format to update the "context" of a deployment-id? It is useful to be able to set this via CLI. The Azure Portal lets you update context but that doesn't help a CI pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbcd4f3e-cbf7-49a6-55f4-8f1aa4bb9995
* Version Independent ID: 4ebb9187-5e18-49b5-85eb-1e9d7a6e57cc
* Content: [az iot edge deployment](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/edge/deployment?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-edge-deployment-update)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/edge/deployment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/edge/deployment.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
iot edge

**Comment by digimaun** [comment]
Edge deployment properties that can be updated have been reflected on the [reference docs](https://docs.microsoft.com/en-us/cli/azure/ext/azure-iot/iot/edge/deployment?view=azure-cli-latest#ext-azure-iot-az-iot-edge-deployment-update).

Copying here: 

> Note: IoT Edge deployment content is immutable. Deployment properties that can be updated are 'labels', 'metrics', 'priority' and 'targetCondition'.

Here is an example usage:

`az iot edge deployment update -d {deployment_name} -n {iothub_name} --set labels='{"purpose":"dev", "owners":"IoTEngineering"}' targetCondition='tags.building=9'`

For further discussion, feel free to drop an issue in the [IoT extension repo](https://github.com/Azure/azure-iot-cli-extension).
