### ISSUE TITLE
[containerapp] Being able to specify the Dockerfile name and the Docker build context in a containerapp up command

### ISSUE THREAD

**Issue by agoncal** [Azure/azure-cli-extensions#5041]
### Related command

```
az containerapp up \
  --name villains-app \
  --environment "$CONTAINERAPPS_ENV" \
  --repo https://github.com/agoncal/villains-app \
  --resource-group "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --context-path src/main/docker 
```

### Extension name (the extension in question)

containerapp

### Description of issue (in as much detail as possible)

Today we can pass the `context-path` parameter to the `up` command to run a docker build specifying the location of the `Dockerfile` (if not it uses the defaults "./"). But in Java projects it is common to have several Docker files (e.g., to build a project in Java 11 as well as Java 17 and GraalVM). 

Until 0.3.1 there was a `docker-file-path` parameter that got replaced with `context-path`. It would be great to have both attributes. So we could execute:

```
az containerapp up \
  --docker-file-path src/main/docker/Dockerfile.jvm11 
  --context-path . 
```

Or for consistency maybe prefix the attributes with ` docker`  so we could have:

```
az containerapp up \
  --docker-file-path src/main/docker/Dockerfile.jvm11 
  --docker-context-path . 
```

And of course, if no attribute is set, then the command goes back to the default `Dockerfile` name under ` ./`

**Comment by PramodValavala-MSFT** [comment]
@agoncal Looking at the code [here](https://github.com/Azure/azure-cli-extensions/blob/main/src/containerapp/azext_containerapp/custom.py#L2204), seems there is more to consider before supporting this. Transferring this to the concerning team.

**Comment by agoncal** [comment]
Oh, "GH actions API needs to be updated" ! Do you know if there is an issue related to this so we can keep track? #Thanks

**Comment by panchagnula** [comment]
Currently we have no plans to add special parameters to up command, Adding @anthonychu & @sanchitmehta for JAVA specific scenarios support.

**Comment by panchagnula** [comment]
> Oh, "GH actions API needs to be updated" ! Do you know if there is an issue related to this so we can keep track? #Thanks

@agoncal please report regarding GitHub actions API support here https://github.com/microsoft/azure-container-apps/issues

**Comment by agoncal** [comment]
Thanks
