### ISSUE TITLE
[containerapp] az containerapp update with --max-replicas 0 returns no error

### ISSUE THREAD

**Issue by snobu** [Azure/azure-cli-extensions#5067]
`az containerapp update -n ContainerAppName -g ResourceGroup --min-replicas 0 --max-replicas 0` finishes without throwing any error, however scaling configuration is not updated as max replicas cannot be zero.

```
$ az version
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "containerapp": "0.3.5",
  }
}
```

**Comment by navba-MSFT** [comment]
@snobu Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
