### ISSUE TITLE
az ssh vm trying private ip not working unless flag explicitly added

### ISSUE THREAD

**Issue by hannenijhuis** [Azure/azure-cli-extensions#5076]
## Describe the bug
Trying to connect to a VM by specifying resource group and vm name. VM doesn't have a public IP. Warning is shown that private IP will be attempted. 
```
No public IP detected, attempting private IP (you must bring your own connectivity).
Use --prefer-private-ip to avoid this message.
```
Connection **fails**. 

Attempting again with the proposed flag `--prefer-private-ip`, connection **successful**.

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 1.0.0.`

**Errors:**
None, just fails without feedback.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- vm without public IP
- P2S VPN with Azure VPN Client
- `az ssh vm --resource-group {} --name {}`

Warning about no public IP, says it will attempt private IP. Fails.

When using `--prefer-private-ip` flag it works.

## Expected Behavior
Automatically attempt private IP after warning no public IP available.

## Environment Summary
```
macOS-12.4-x86_64-i386-64bit, Darwin 21.5.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.33.1 *

Extensions:
ssh 1.0.0
account 0.2.3

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by hannenijhuis** [comment]
I tried upgrading my `azure-cli` to the latest version 2.37 through homebrew. Problem still exists.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@hannenijhuis Thanks for reaching out to us and sharing this feedback. I hope you had a chance to try the action plan suggested above to update your ssh extension. Awaiting your reply.

**Comment by hannenijhuis** [comment]
Thanks for your swift reply. I confirm that updating the ssh extension works!

**Comment by navba-MSFT** [comment]
@hannenijhuis Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by mmohamednazeer** [comment]
I am facing the same issue on version 1.1.5 as well. If we add `--prefer-private-ip` it works.

**Comment by vthiebaut10** [comment]
@mmohamednazeer Can you try updating to version 1.1.6?

**Comment by mmohamednazeer** [comment]
@vthiebaut10  thanks its working with version 1.1.6
