### ISSUE TITLE
Invalid command

### ISSUE THREAD

**Issue by smena** [Azure/azure-cli-extensions#508]
az cli command documentation is not versioned, and whatever version is documented here does not match my 2.0.37 az cli:

~$ az account create --enrollment-account-name EXAMPLE-ACCT --offer-type MS-AZR-0148P --display-name EXAMPLE-ACCT
az account: 'create' is not an az account command. See 'az account --help'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3bd98e-0952-10f0-1681-3477311936e3
* Version Independent ID: f1a03a16-c777-b7a7-b116-3cfb78d241bc
* Content: [az account](https://docs.microsoft.com/en-us/cli/azure/ext/subscription/account?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/subscription/account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/subscription/account.yml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
You would need to install the subscription extension with `az extension add -n subscription`. If you don't have the extension commands, you'd need to update your version of the CLI.

**Comment by AndyWu7623** [comment]
it would be nice if we provide this information in this page as it didn't provide in there. To increase the visibility and avoid confusion
