### ISSUE TITLE
az ml job create --set can not override inputs on pipelines

### ISSUE THREAD

**Issue by IsmaelGSerrano** [Azure/azure-cli-extensions#5091]
## Describe the bug

**Command Name**
`az ml job create
Extension Name: ml. Version: 2.4.1.`

**Errors:**
```
Met error <class 'marshmallow.exceptions.ValidationError'>:Validation for PipelineJobSchema failed:

 {
  "input": [
    "Unknown field."
  ]
} 

 If you are trying to configure a job that is not of type pipeline, please specify the correct job type in the 'type' property.
For a more detailed breakdown of the PipelineJob schema, please see: https://aka.ms/ml-cli-v2-job-pipeline-yaml-reference.
The easiest way to author a specification file is using IntelliSense and auto-completion Azure ML VS code extension provides: https://code.visualstudio.com/docs/datascience/azure-machine-learning
To set up: https://docs.microsoft.com/azure/machine-learning/how-to-setup-vs-code
Please check log in debug mode for more details.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Use any example in the azureml-examples. In the example: cli\jobs\pipelines-with-components\basics\4a_local_data_input
- `az ml job create --file .\pipeline.yml --set input.pipeline_sample_input_string="hello parameter string" --web`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0 *

Extensions:
account 0.2.3
ml 2.4.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by brynn-code** [comment]
Hi [IsmaelGSerrano](https://github.com/IsmaelGSerrano), seems the key following --set is wrong, should be `inputs` instead of `input`.

**Comment by IsmaelGSerrano** [comment]
> * az ml job create --file .\pipeline.yml --set input.pipeline_sample_input_string="hello parameter string" --web

Yes, you are right. 😳
