### ISSUE TITLE
"az aks addon list" always returns "enabled:false" for virtual-node addon even when the addon is actually enabled.

### ISSUE THREAD

**Issue by thiruma0203** [Azure/azure-cli-extensions#5098]
## Describe the bug

**Command Name**
`az aks addon list
Extension Name: aks-preview. Version: 0.5.63.`

**Errors:**
az aks addon list command always returns "enable:false" for virtual-node addon. REST API returns "enalble:", but CLI displays result as "enable:false"
```

> az aks addon list -g TestRG -n TestCluster --debug
# REST API returns the addon status to be "enabled:true" in debug trace.
   "addonProfiles": {
    "aciConnectorLinux": {
     "enabled": true,            <<<<<<<
     "config": {
      "SubnetName": "VirtualNodeSubnet"
     },


#However, CLI displays "enabled:false". It appears to be matching with "aciConnector" instead of "aciConnectorLinux".

  {
    "api_key": "aciConnector",
    "enabled": false,           <<<<<<<<<
    "name": "virtual-node"
  },

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Run `az aks addon enable --addon virtual-node -n TestCluster -g TestRG --subnet-name VirtualNodeSubnet` in advance to enable virtual-node addon.
- Run `az aks addon list -n TestCluster -g TestRG--debug` to check output.

## Expected Behavior
"enabled:true" is displayed when the addon is enabled.

## Environment Summary
```
Linux-5.4.0-1085-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
aks-preview 0.5.63
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by navba-MSFT** [comment]
@thiruma0203 Thanks for reaching out to us and reporting this issue. Could you please update your` aks-preview` extension and check if you still the same issue ? If you do, please share the debug output after upgrading.

>az extension update -n aks-preview

**Comment by yonzhan** [comment]
route to CXP team

**Comment by thiruma0203** [comment]
@navba-MSFT , I tried to update the extension, however no updates are available. Tried in CloudShell.

$ az extension update -n aks-preview
No updates available for 'aks-preview'. Use --debug for more information.

**Comment by navba-MSFT** [comment]
@thiruma0203 Yes that makes sense. I was able to repro this issue at my end too. So the above PR was filed as a fix. Currently it is under review. In the meantime, if you have any question, please feel free to ask.
