### ISSUE TITLE
Azure ML Online Endpoints on AKS compute no longer supported

### ISSUE THREAD

**Issue by tommyJimmy87** [Azure/azure-cli-extensions#5102]
### Related command

az ml online-endpoint create --name aks_endpoint -f endpoint_aks.yaml

endpoint_aks.yaml :

```
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineEndpoint.schema.json
name: my-endpoint
compute: azureml:aks
auth_mode: Key
tags:
  version: 1
```

### Extension name (the extension in question)
ml

### Description of issue (in as much detail as possible)

here listed all the versions: 
```azure-cli                         2.38.0
Please let us know how we are doing: https://aka.ms/azureclihats

and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
core                              2.38.0
telemetry                          1.0.6

Extensions:
ml                                 2.4.0
azure-devops                      0.25.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
```

Error I get is: 

``` 
ERROR: (BadRequest) The request is invalid.
Code: BadRequest
Message: The request is invalid.
Exception Details:	(NotSupported) Creation of Online Endpoints or deployments on AKS compute type is no longer supported. More details can be found here, https://aka.ms/troubleshoot-creating-aks-endpoint
	Code: NotSupported
	Message: Creation of Online Endpoints or deployments on AKS compute type is no longer supported. More details can be found here, https://aka.ms/troubleshoot-creating-aks-endpoint
Additional Information:Type: ComponentName
Info: {
    "value": "managementfrontend"
}Type: Correlation
Info: {
    "value": {
        "operation": "601471e2620e594291f18ff4c47fe660",
        "request": "24c163354cf5ef6a"
    }
}Type: Environment
Info: {
    "value": "westeurope"
}Type: Location
Info: {
    "value": "westeurope"
}Type: Time
Info: {
    "value": "2022-07-11T16:08:58.3790235+00:00"
}

```

I don't find any reference in the documentation, instead, it appears to me that it should be supported as per docs here: 
https://docs.microsoft.com/en-us/azure/machine-learning/reference-yaml-endpoint-online

Also in the troubleshooting mentioned in the error there's no evidence of dropping the support of aks.

thanks

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@tommyJimmy87 Thank you for reaching out, we are looking into it.

**Comment by tommyJimmy87** [comment]
Sorry I didn't have time to test this, will be back asap.

**Comment by RakeshMohanMSFT** [comment]
@tommyJimmy87 Thank you

**Comment by hanshasharma** [comment]
Hi - I am also experiencing the same issue with Azure CLI v2.39.0 * and ml extension v2.8.0. I am trying to run https://github.com/Azure/azureml-examples/tree/main/cli/endpoints/online/kubernetes. I am getting the following error.

Message: The request is invalid.
Exception Details:	(NotSupported) Creation of Online Endpoints or deployments on AKS compute type is no longer supported. More details can be found here, https://aka.ms/troubleshoot-creating-aks-endpoint
	Code: NotSupported
	Message: Creation of Online Endpoints or deployments on AKS compute type is no longer supported. More details can be found here, https://aka.ms/troubleshoot-creating-aks-endpoint
Additional Information:Type: ComponentName

**Comment by Bozhong68** [comment]
@hanshasharma Legacy AksCompute doesn't support online endpoint. For v2 online endpoint support, you can attach AKS cluster by following instruction here https://aka.ms/amlarc/doc
