### ISSUE TITLE
IoT-Hub-DPS "enrollment-group" with a "custom function"

### ISSUE THREAD

**Issue by ma-ha** [Azure/azure-cli-extensions#511]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
azure-cli-iot-ext

### Description of issue (in as much detail as possible)
We're missing an option to create a IoT-Hub-DPS "enrollment-group" with a "custom function" (as allocation-policy?). 
-----

**Comment by yonzhan** [comment]
iot

**Comment by digimaun** [comment]
This was resolved in IoT extension v0.9.7. Please update and you will see the option available. Note `azure-cli-iot-ext` is now deprecated please install `azure-iot` instead.
