### ISSUE TITLE
Currently 'az network bastion ssh' does not work on linux

### ISSUE THREAD

**Issue by aadhikary** [Azure/azure-cli-extensions#5126]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command

SSh extention for az bastian currently does not work on linux

$ az network bastion ssh 
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
**Platform is not supported for this command. Supported platforms: Windows**

### Description of issue (in as much detail as possible)
Azure bastian ssh command does not work on Linux

$ az --version
azure-cli                         2.30.0 *

core                              2.30.0 *
telemetry                          1.0.6

Extensions:
storage-preview                    0.8.3
**ssh                                1.1.2**

Python location '/home/aadhikary/lib/azure-cli/bin/python'
Extensions directory '/home/aadhikary/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@aadhikary Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by aadhikary** [comment]
> @aadhikary I hope you have gone through the below articles which explains about ssh to Linux VM using Azure Bastion.
> 
> Feature	Basic SKU	Standard SKU
> Connect to Linux VM using SSH	[Refer this](https://docs.microsoft.com/en-us/azure/bastion/bastion-connect-vm-ssh-linux)	[Refer This](https://docs.microsoft.com/en-us/azure/bastion/bastion-connect-vm-ssh-linux)
> I am using Az CLI 2.38.0 and ssh 1.1.2 in my machine. Could you please test using the same and run the below command ?
> 
> > az network bastion ssh --name MyBastionHost --resource-group MyResourceGroup --target-resource-id vmResourceId --auth-type password --username xyz
> 
> Hope this helps.

Hi @navba-MSFT, thanks for the update. 

The problem is bot regarding connecting to Linux VM. The issue is that my local machine is linux not windows and ssh extension does not support linux as on the description. Hope this helps

**Comment by navba-MSFT** [comment]
@aadhikary Thanks for clarifying your ask. The “Connect – other native clients” section of [Connect to a VM using a native client and Azure Bastion - Azure Bastion | Microsoft Docs](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows) might be useful. It suggests using az network bastion tunnel and then running a regular ssh command.

>Connect to a VM using the [az network bastion tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel). This lets you do the following:
>
> - Use native clients on non-Windows local computers (example: **_a Linux PC_**).
> - Use the native client of your choice. (This includes the Windows native client.)
> - Connect using SSH or RDP.
> - Set up concurrent VM sessions with Bastion.
> - [Upload files](https://docs.microsoft.com/en-us/azure/bastion/vm-upload-download-native#tunnel-command) to your target VM from your local computer. File download from the target VM to the local client is currently not supported for this command.

>Currently, this feature has the following limitation:

>
>Signing in using an SSH private key stored in Azure Key Vault isn’t supported with this feature. Before signing in to your Linux VM using an SSH key pair, download your private key to a file on your local machine.

**Comment by navba-MSFT** [comment]
@aadhikary I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  had a chance to follow the above suggestion. Awaiting your reply.

**Comment by aadhikary** [comment]
> @aadhikary I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had a chance to follow the above suggestion. Awaiting your reply.

@navba-MSFT we can use the tunneling which works fine but we had to write our own scripts to use ssh via bastian for running Ansible playbooks. Considering that there is already a CLI command that is suppose to do this could we get a timeline on when can we get this bastion ssh feature working on Linux. I am sure this will be useful for the whole Azure community.

**Comment by navba-MSFT** [comment]
@aadhikary Thanks for the feedback. Expanding the native client support is on our radar, but lower on the priority list compared to other features since the tunnel command is an effective solution. 

If you would like to provide more details about the your scenario and your use case, I can share this with the product owners. They can add it to our backlog and review the ask during future planning cycles.

**Comment by navba-MSFT** [comment]
@aadhikary Hope you had a chance to look at my above comment. With that we will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
