### ISSUE TITLE
load argument in "az aks create"

### ISSUE THREAD

**Issue by mendi40** [Azure/azure-cli-extensions#513]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
`az aks create` stop working for me after I add the extension.
the command works for me only after I comment this line:
https://github.com/Azure/azure-cli-extensions/blob/master/src/aks-preview/azext_aks_preview/__init__.py#L35
and uncomment the line above it.
(the supper function get arguments)
-----

**Comment by seanmck** [comment]
Closing for lack of a consistent repro. Let us know if you have one.
