### ISSUE TITLE
az  storage blob directory download fails with AttributeError

### ISSUE THREAD

**Issue by petergaultney** [Azure/azure-cli-extensions#5146]
## Describe the bug

**Command Name**
`az storage blob directory download
Extension Name: storage-preview. Version: None.`

**Errors:**
```
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
...
cliextensions/storage-preview/azext_storage_preview/_client_factory.py, ln 33, in get_data_service_client
    logger.debug('Getting data service client service_type=%s', service_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login -i`
- `az storage blob directory download -c {} -s {} -d {} --account-name {} --auth-mode {}`

## Environment Summary
```
Linux-5.4.0-1078-azure-x86_64-with-glibc2.31
Python 3.9.2
Installer: DEB

azure-cli 2.18.0 *

Extensions:
storage-preview Unknown
azure-devops 0.19.0

```
## Additional Context

I tried a bunch of other ways to download stuff, none of which worked, but they failed with meaningful errors. Then I tried this. :/

**Comment by yonzhan** [comment]
storage

**Comment by RakeshMohanMSFT** [comment]
@petergaultney Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@petergaultney You are using a pretty old version of azure cli, can you upgrade to latest version of azure cli [2.40.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) and retry?
