### ISSUE TITLE
az monitor app-insights query with start and end  time

### ISSUE THREAD

**Issue by marabesi** [Azure/azure-cli-extensions#5158]
### Related command
```
az monitor app-insights query --app myapp -g mygroup --analytics-query 'traces | where message contains "bla"' --start-time date "2022-07-21" time "09:18:00.0000Z" timezone "+02:00" -o table
```

### Extension name (the extension in question)

app-insights

### Description of issue (in as much detail as possible)

The documentation around the app-insights query is not that completed when referring to the field "--start-time", the command below is an attempt to make a query and filter by the start date, but when the command is executed I see the error:

```
Unable to parse: 'date 2022-07-21 time 09:18:00.0000Z timezone +02:00'. Expected format: Start-time of time range for which to retrieve data. Format: date (yyyy-mm-dd) time (hh:mm:ss.xxxxx) timezone (+/-hh:mm)
```

Which indicates that the format I am giving is not that clear, but the [docs](https://docs.microsoft.com/en-us/cli/azure/monitor/app-insights?view=azure-cli-latest#az-monitor-app-insights-query) says nothing about the format. After diving into the code (and [checking this file](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/tests/test_aaz_arg_fmt.py#L201) from cli core), I saw that the format should be something like:

```
az monitor app-insights query --app myapp -g mygroup --analytics-query 'traces | where message contains "bla"' --start-time 2022-07-10T09:10:00.000Z -o table
```

When I run this command, I see no errors, but it shows nothing in the console (if I execute the same in the azure portal, I can see the logs properly). The question that I have is: is the date format correct? If so, can I mitigate why I can't see the logs?

**Comment by yonzhan** [comment]
monitor

**Comment by AllyW** [comment]
Hello Marabesi, since your second try returns no error, the date format should be right. The reason nothing return in console might need to debugged. Could you please add `--debug` in your command (like below) to see what's returning in your console and see what's going on in the backend?
 ```
az monitor app-insights query --app myapp -g mygroup --analytics-query 'traces | where message contains "bla"' --start-time 2022-07-10T09:10:00.000Z -o table --debug
```
