### ISSUE TITLE
front-door extension can not find existing front door resources

### ISSUE THREAD

**Issue by petersladek** [Azure/azure-cli-extensions#5170]
### Related command

```
az network front-door list
basically all front-door commands
```
### Extension name (the extension in question)
front-door

### Description of issue (in as much detail as possible)
I was trying to use AZ cli to execute some command against existing front-door, but found out that front-door extension is unable to locate any FD resources by name or resource id for any command I tried. I was getting (ResourceNotFound) error. Then found out that executing "az network front-door list" returns empty array. I tried multiple subscriptions containing front door resource, access with different accounts, using AZ cli both on windows and linux, and the result was the same. 

Update: I am using latest version 1.0.16 of the front-door extension.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@petersladek Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@petersladek While I ran the command `az network front-door list` it was able to list the frontdoor resource details. I am using the front-door extension version 1.0.16 with AzCLi 2.38 version.

Could you please follow the below action plan and check if that helps ?

**Plan 1:** 
Run the below commands in order and check if that helps:
- az login
- az account set --subscription "XXXXXXX-XXXX-XXXX-XXXX"
- az network front-door list

**Plan 2:**
If you still face the same issue, please run the command with `--debug `switch and share the debug output here. Awaiting your reply.

**Comment by petersladek** [comment]
That is not working for me. However I found out the root cause. `az network front-door` can only be used on front door **classic**. For standard/premium you have to use new command [`az afd`](https://docs.microsoft.com/en-us/cli/azure/afd?view=azure-cli-latest) that I found only by accident when browsing available `az` commands. The problem is that if you google "az cli front door" all links refer to [`az network front-door`](https://docs.microsoft.com/en-us/cli/azure/network/front-door?view=azure-cli-latest) and in documentation it is not mentioned that it only works for front door classic. It should really be added, I wasted several hours because of that.

**Comment by navba-MSFT** [comment]
@petersladek Thanks for the update and sharing the feedback. I have created the above PR to update our documentation. It is currently under review. In the meantime if you have any questions, please feel free to ask.
