### ISSUE TITLE
azure-mgmt-monitor 4.0.1 might be causing azure ext repo PRs to fail validation in py3.6

### ISSUE THREAD

**Issue by swells** [Azure/azure-cli-extensions#5220]
Perhaps commit: https://github.com/Azure/azure-cli/commit/76c224121c05f77f6cf6f17130b6c8fde824e10a  is causing build issues in the azure-cli-extensions repo during ext PRs. This worked ok last week. 

Impact is that it is failing and preventing ext's from successfully merging PRs hence can not publish ATM.

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/1356351/183712226-e693d78c-6ff7-439f-bff1-0dd4a7c63653.png">

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by swells** [comment]
closing since this resolved it --> https://github.com/Azure/azure-cli-extensions/pull/5218

Thanks folks for fixing in a timely manner.
