### ISSUE TITLE
az ml 2.7.0 online-deployment update does not honour json output

### ISSUE THREAD

**Issue by mattmshell** [Azure/azure-cli-extensions#5232]
### Related command

```pwsh
$deployment = $(az ml online-deployment update --file deployment.yml --resource-group $ResourceGroupName --workspace-name $WorkspaceName --output json | ConvertFrom-Json)
```

### Extension name (the extension in question)

ml

### Description of issue (in as much detail as possible)

On Linux, under bash, `az ml online-deployment update` appears to print progress dots, despite `--output json`. These cannot be parsed as JSON causing an error in my PowerShell script:

```
ConvertFrom-Json : Conversion from JSON failed with error: Input string '...............................................................................................' is not a valid number. Path '', line 1, position 95.
```

Downgrading to 2.6.x mitigates this issue.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by mattmshell** [comment]
I'm not working this Azure ML at the moment. Closing.
