### ISSUE TITLE
Need az webapp up support --ServicePlanName

### ISSUE THREAD

**Issue by JackyChiou** [Azure/azure-cli-extensions#524]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az webapp up

### Description of issue (in as much detail as possible)
1.	Create and deploy existing local code to the web app.
az webapp up --name "jackywebappupdj1" --location "westus" --sku "S1"

2.	Move the webapp and **ServicePlan** to an existing resource group

3. 	Create and deploy existing local code to the **second** web app. 
az webapp up --name "jackywebappupdj2" --location "westus" --sku "S1"
Resource group 'appsvc_rg_Linux_westus' already exists.
Creating App service plan 'appsvc_asp_Linux_westus' ...
Server Farm with name 'appsvc_asp_Linux_westus' already exists for subscription '30365905-2ed4-410b-aa9f-3cc0bd354520'.

If we can't assign the Service Plan Name, can't use "az webapp up" to create the second web app.

**Comment by panchagnula** [comment]
this is complete & is available in core see https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-up
