### ISSUE TITLE
`containerapp-compose` extension not auto installing

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli-extensions#5246]
### Related command
`containerapp compose`

### Extension name (the extension in question)
containerapp-compose

### Description of issue (in as much detail as possible)
In the [az containerapp compose](https://docs.microsoft.com/en-us/cli/azure/containerapp/compose?view=azure-cli-latest) doc, it says: "This reference is part of the containerapp-compose extension for the Azure CLI (version 2.15.0 or higher). The extension will automatically install the first time you run an az containerapp compose command. [Learn more](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview) about extensions."

I am running Azure CLI version 2.39.0 and when I run `az containerapp compose` I get an error:
`'compose' is misspelled or not recognized by the system.`

![image](https://user-images.githubusercontent.com/74415662/185216954-3dce493a-f716-4e8a-9fed-95a378e4e3f0.png)

-----

**Comment by panchagnula** [comment]
@charris-msft please note that there is no compose sub group support for extension 'az containerapp'
'az containerapp-compose' is a separate extension so please use az container app-compose create as the command to run & use the extension. Thanks!

**Comment by charris-msft** [comment]
@panchagnula - It seems like the documentation should be updated then as it is referencing `az containerapp compose`:

![image](https://user-images.githubusercontent.com/74415662/185222381-d48a2c9d-13e4-46b0-af39-097e975c511b.png)

**Comment by panchagnula** [comment]
closed it by accident - the help docs should be updated accordingly.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@charris-msft Thanks for reaching out to us and reporting this issue. I can help in getting the docs updated.

@panchagnula Could you please confirm if the command is right ? Because I couldn't run it as the command wasn't recognized.

>naveen@Azure:~$ az extension add -n containerapp-compose
The installed extension 'containerapp-compose' is in preview.

>naveen@Azure:~$ az container app-compose create -e MyAppName -g MyRG
**'app-compose' is misspelled or not recognized by the system.**

Awaiting your reply.

**Comment by charris-msft** [comment]
@navba-MSFT - after some additional testing yesterday, the doc just need to be updated to include the action `create`.

If you don't have the containerapp-compose extension installed, and run the following it will prompt you to install the extension:

`az containerapp compose create`

**Comment by navba-MSFT** [comment]
Thanks @charris-msft . I will create the PR for the same tomorrow and update this thread.

**Comment by navba-MSFT** [comment]
@charris-msft Apologies for the delay in getting back.

I did some research on this and seems like the approach to file PR is not straight forward. 

![image](https://user-images.githubusercontent.com/57353862/186075959-599710c3-6d73-46fe-b56e-8f86344225e2.png)

The above message comes from [this](https://apidrop.visualstudio.com/Content%20CI/_build?definitionId=477) templated docs reference pipeline and all the CLI extensions use the same templated message. The CLI page is based on a command group. One page is for a group of commands. So, the page displays the note with the command group 'az containerapp compose' .

I had reached out to the CLi docs team and they said they need to change the docs pipeline to support customized template for each extension. They will inform PM to track this request.

cc: @panchagnula If you have aware of any quick process to get this updated, please feel free to help.

**Comment by navba-MSFT** [comment]
@charris-msft I hope you had a chance to look at my above comment they don't have any ETA on when this would be fixed. We will update this thread once it is addressed. 

@panchagnula Are you aware of any quick process to get this docs updated? please let me know.

**Comment by navba-MSFT** [comment]
@charris-msft I have looped you in an email thread with the PM team. That email has the workitem details to track the docs fix for this issue. Archiving this GitHub thread for now.
