### ISSUE TITLE
ContainerApp - Unauthenticated image pulls are broken in 0.3.9

### ISSUE THREAD

**Issue by smurawski** [Azure/azure-cli-extensions#5253]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command
Deploy the simple example ContainerApps demo container following https://docs.microsoft.com/en-us/azure/container-apps/get-started?tabs=bash

```
RESOURCE_GROUP="my-container-apps"
LOCATION="canadacentral"
CONTAINERAPPS_ENVIRONMENT="my-environment"

az group create \
  --name $RESOURCE_GROUP \
  --location $LOCATION

az containerapp env create \
  --name $CONTAINERAPPS_ENVIRONMENT \
  --resource-group $RESOURCE_GROUP \
  --location $LOCATION

az containerapp create \
  --name my-container-app \
  --resource-group $RESOURCE_GROUP \
  --environment $CONTAINERAPPS_ENVIRONMENT \
  --image mcr.microsoft.com/azuredocs/containerapps-helloworld:latest \
  --target-port 80 \
  --ingress 'external' \
  --query properties.configuration.ingress.fqdn
```

### Extension name (the extension in question)

containerapp version 0.3.9

### Description of issue (in as much detail as possible)

When an image is referenced from an unauthenticated public endpoint, an error is thrown specifying that a username and password are required.

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by StrawnSC** [comment]
A fix for this is in progress here: https://github.com/calvinsID/azure-cli-extensions/pull/144

**Comment by panchagnula** [comment]
this fix is released with our latest version  
"name": "containerapp",
    "preview": true,
    "summary": "Microsoft Azure Command-Line Tools Containerapp Extension",
    "version": "0.3.10"
