### ISSUE TITLE
Add coloring to the json output of az webapp new

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli-extensions#53]

**Comment by tjprescott** [comment]
There's already color output in the CLI.  -o jsonc

**Comment by ahmedelnably** [comment]
@tjprescott understood, this issue is not for the platform, the webapp new command doesn't use the color output of the CLI, this issue is used to track the addition of colors in the command

**Comment by derekbekoe** [comment]
> the webapp new command doesn't use the color output of the CLI

@ahmedelnably Can you clarify what you mean by this? The CLI infrastructure is what determines the output type of commands. As long as the user specifies `-o jsonc`, they would see json colored output.

**Comment by ahmedelnably** [comment]
I think I misspoke there, we want to use specific colors depending on the output we are showing to the user. This is mainly related on how the output of the command is formatted and colored.

**Comment by derekbekoe** [comment]
> we want to use specific colors depending on the output we are showing to the user

Would still like clarification on this before it is implemented.
As a core part of the CLI, commands do not / should not have control of changing outputs. This should be left up to the user.

> This is mainly related on how the output of the command is formatted and colored.

Still don't fully understand this.

**Comment by anthonychu** [comment]
Currently, this command prints progress and a JSON representation of the resources created. It does this only using `logger.warning` and doesn't return anything from the command, so there's nothing that can be formatted using `-o`. Example:

```
bash-4.3# az webapp new -n test-webapp-new
Creating Resource group 'appsvc_rg_Windows_CentralUS' ...
Resource group creation complete
Creating App service plan 'appsvc_asp_Windows_CentralUS' ...
App service plan creation complete
Creating app 'test-webapp-new' ....
Webapp creation complete
Updating app settings to enable build after deployment
Creating zip with contents of dir /app/foo ...
Deploying and building contents to app.This operation can take some time to finish...
All done. {
    "location": "Central US",
    "name": "test-webapp-new",
    "os": "Windows",
    "resourcegroup": "appsvc_rg_Windows_CentralUS ",
    "serverfarm": "appsvc_asp_Windows_CentralUS",
    "sku": "FREE",
    "src_path": "/app/foo ",
    "version_detected": "2.0",
    "version_to_create": "dotnetcore|2.0"
}
```

IMHO, if this command prints JSON, it should return it as an object so that the user can format it with `-o` and use `--query`, etc. If the goal is to output nothing that can be formatted and print all output with `logger.warning`, what is printed should be human readable, not JSON.
