### ISSUE TITLE
"az appservice kube create" throwing Internal server error

### ISSUE THREAD

**Issue by johnliu55-msft** [Azure/azure-cli-extensions#5313]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command

```
az appservice kube create
```

### Extension name (the extension in question)
appservice-kube

### Description of issue (in as much detail as possible)

I was following the doc [Set up an Azure Arc-enabled Kubernetes cluster to run App Service, Functions, and Logic Apps (Preview)](https://docs.microsoft.com/en-gb/azure/app-service/manage-create-arc-environment?tabs=powershell#add-azure-cli-extensions) to deploy App Service to my Arc-enabled Kubernetes cluster, but failed at the last step "Create the App Service Kubernetes environment":

```
Internal server error occurred. Couldn't confirm connectivity to Arc-enabled cluster: /subscriptions/4dd59660-430d-4771-835d-b17a17362e07/resourceGroups/AzureArcTest/providers/Microsoft.Kubernetes/connectedClusters/my-cluster-1. Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.40.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.Identity.Client, Version=4.40.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'
   at Microsoft.Web.Hosting.Administration.Kube.ArcClient.AcquirePoPTokenForCluster(String host, String tenantId, String clusterApiServerId, String subscriptionId)
   at Microsoft.Web.Hosting.Administration.Kube.K8SEHelper.GetRefreshedKubeConfig(String originalKubeConfig, String subscriptionId, String kubernetesEnvironmentName)
   at Microsoft.Web.Hosting.Administration.Kube.K8SEHelper.RefreshKubeConfigAccessTokenIfNeeded(String kubeconfig, String& refreshedKubeConfig, String kubernetesEnvironmentName, String subscriptionId, Boolean forceRefresh)
   at Microsoft.Web.Hosting.Administration.GeoScale.Csm.Controllers.KubeEnvironmentsCsmController.GetK8SEClient(AppServiceOnArcInfo info, KubeEnvironment newKubeEnvironment)
   at Microsoft.Web.Hosting.Administration.GeoScale.Csm.Controllers.KubeEnvironmentsCsmController.CheckAccessToArcCluster(AppServiceOnArcInfo info, KubeEnvironment newKubeEnvironment)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

All the steps before this one succeeded without any error messages, and I'm able to connect to my cluster using `az connectedk8s proxy` so I think it's connected to Azure.

My appservice-kube extension version is `0.1.7`.

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by apwestgarth** [comment]
This looks to indicate that the Kubernetes cluster is no longer connected to Azure Arc.  What is the status of the connected cluster?  This can be found either through cli - az connectedk8s -n <name of connected cluster> -g <Resource group> or via Azure Portal.

**Comment by johnliu55-msft** [comment]
The command `az connectedk8s show` shows that the cluster is connected:

![Screenshot 2022-09-07 124000](https://user-images.githubusercontent.com/107901166/188790860-449ca790-7746-44c1-8f1b-bddc2f47cc24.png)

**Comment by SaurabhSharma-MSFT** [comment]
@johnliu55-msft Are you still having issues?
@apwestgarth  Any suggestions on this.
