### ISSUE TITLE
az containerapp revision commands not working anymore and return "Internal server error occurred."

### ISSUE THREAD

**Issue by DavidErben** [Azure/azure-cli-extensions#5317]
## Describe the bug

Several az containerapp commands are not working anymore since yesterday. In the Azure Portal it does not work either, f.e. it is not possible to list the revisions of a container app. Creating new revisions is also not possible anymore on the CLI as well as Azure Portal. So right now we cannot update our apps anymore and development is blocked.

**Command Name**
`az containerapp revision list
Extension Name: containerapp. Version: 0.3.10.`
`az containerapp revision copy`

**Errors:**
```
Internal server error occurred. correlation ID: 9bb95ccf-a818-47cd-b767-3514cb14e3da

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp revision list -n {} -g {}`

## Expected Behavior

Revisions are correctly listed or can be created.

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
azure-devops 0.20.0
containerapp 0.3.10

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by navba-MSFT** [comment]
@DavidErben Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@DavidErben I am unable to reproduce this issue at my end. I am able to access the ContainerApp and check the revisions in Azure portal. Could you please let me know if you are still facing this issue ? If Yes, could you please share the `--debug `output of the above command. Awaiting your reply.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by DavidErben** [comment]
> 

**Thanks for the reply! Here is the error I get in the portal (session ID 5e2f5e41b4db4e369d4329754cfe3e6f):**

![grafik](https://user-images.githubusercontent.com/79685270/188850958-ddf8c508-247c-4dea-a3ef-06de352a236a.png)

**This is the CLI output with --debug enabled (only the exception part since the beginning contained sensitive information like the subscription ID):**

cli.azure.cli.core.util: {"code":"InternalServerError","message":"Internal server error occurred. correlation ID: 8da1ff47-3065-4ca9-8d06-a3e405337094","details":null,"target":null}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
File "C:\Users\David.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 1336, in list_revisions
revision_list = ContainerAppClient.list_revisions(cmd=cmd, resource_group_name=resource_group_name, name=name)
File "C:\Users\David.azure\cliextensions\containerapp\azext_containerapp_clients.py", line 273, in list_revisions
r = send_raw_request(cmd.cli_ctx, "GET", request_url)
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 993, in send_raw_request
azure.cli.core.azclierror.HTTPError: Internal Server Error({"code":"InternalServerError","message":"Internal server error occurred. correlation ID: 8da1ff47-3065-4ca9-8d06-a3e405337094","details":null,"target":null})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 663, in execute
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 726, in _run_jobs_serially
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 718, in _run_job
File "C:\Users\David.azure\cliextensions\containerapp\azext_containerapp_client_factory.py", line 28, in _polish_bad_errors
raise ex
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 697, in _run_job
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 333, in call
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
File "C:\Users\David.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 1341, in list_revisions
handle_raw_exception(e)
File "C:\Users\David.azure\cliextensions\containerapp\azext_containerapp_client_factory.py", line 53, in handle_raw_exception
raise CLIInternalError(message)
azure.cli.core.azclierror.CLIInternalError: Internal server error occurred. correlation ID: 8da1ff47-3065-4ca9-8d06-a3e405337094

cli.azure.cli.core.azclierror: Internal server error occurred. correlation ID: 8da1ff47-3065-4ca9-8d06-a3e405337094
az_command_data_logger: Internal server error occurred. correlation ID: 8da1ff47-3065-4ca9-8d06-a3e405337094
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x04505778>]
az_command_data_logger: exit code: 1
cli.main: Command ran in 3.805 seconds (init: 0.437, invoke: 3.368)

**Comment by panchagnula** [comment]
@haroonf could you take a look at this. Looking at the stack trace this seems like a timeout from the API end. We can share the correlationId with @sanchitmehta to help investigate. 
From the CLI perspective we should handle such exceptions gracefully. Thanks!

**Comment by panchagnula** [comment]
@sanchitmehta / @torosent this is not a cli specific issue but I cannot transfer this to the ACA github repo - could one of you take a look & comment please? Thanks!

**Comment by navba-MSFT** [comment]
@DavidErben While we wait for the reply from @sanchitmehta and @torosent, Could you please check if you are able to invoke the [ContainerAPp revision list REST API ](https://docs.microsoft.com/en-us/rest/api/containerapps/container-apps-revisions/list-revisions?tabs=HTTP#code-try-0)directly from the cloud shell and check if that returns a 200 status code ? Awaiting your reply.

**Comment by DavidErben** [comment]
> @DavidErben While we wait for the reply from @sanchitmehta and @torosent, Could you please check if you are able to invoke the [ContainerAPp revision list REST API ](https://docs.microsoft.com/en-us/rest/api/containerapps/container-apps-revisions/list-revisions?tabs=HTTP#code-try-0)directly using the TryIt option and check if that returns a 200 status code ?
> 
> Also please send an email to _navba @ microsoft . com_ with the below details:
> 
>     1. ContainerApp Name
> 
>     2. Subscription Id
> 
>     3. Region where the ContainerAPP is created.
> 
> 
> Awaiting your reply.

I have tried the REST API with the same result, it returns a 500 error.

`api-supported-versions: 2022-01-01-preview, 2022-03-01, 2022-05-01, 2022-06-01-preview
cache-control: no-cache
content-length: 156
content-type: application/json; charset=utf-8
date: Thu, 08 Sep 2022 05:10:12 GMT
expires: -1
pragma: no-cache
server: Microsoft-IIS/10.0
x-ms-correlation-request-id: 24b54ed5-5edd-4e5a-b047-2e68f1a1ce4c
x-ms-failure-cause: service
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-request-id: 24b54ed5-5edd-4e5a-b047-2e68f1a1ce4c
x-ms-routing-request-id: SWITZERLANDNORTH:20220908T051012Z:24b54ed5-5edd-4e5a-b047-2e68f1a1ce4c
x-powered-by: ASP.NET`

`{
  "code": "InternalServerError",
  "message": "Internal server error occurred. correlation ID: 24b54ed5-5edd-4e5a-b047-2e68f1a1ce4c",
  "details": null,
  "target": null
}`

I have sent you an email containing the further details you requested. Thanks!

**Comment by navba-MSFT** [comment]
@DavidErben I have shared these details with the Product Owners. They will look into this further and get back to you with an update.

**Comment by DavidErben** [comment]
It works again now, not sure if someone has fixed it or it was an issue with our subscription. Thanks for your help!

**Comment by torosent** [comment]
We didn't do anything but we can investigate what happened if you send me the subscription id and environment name `acasupport at microsoft dot com`

**Comment by navba-MSFT** [comment]
@torosent I have shared all the required details about the environment with you internally over email.
