### ISSUE TITLE
az sentinel alert-rule list resource not found

### ISSUE THREAD

**Issue by rezarms** [Azure/azure-cli-extensions#5318]
## Describe the bug

**Command Name**
`az sentinel alert-rule list`

`Extension Name: sentinel. Version: 0.1.2.`

**Errors:**
```
(ResourceNotFound) The Resource 'Microsoft.OperationalInsights/workspaces/law-xx' under resource group 'rg-xx' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.OperationalInsights/workspaces/law-xx' under resource group 'rg-xx' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

```

## To Reproduce:

- `az sentinel alert-rule list --resource-group {} --workspace-name {}`

## Expected Behavior
return list of alert
## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.2 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.34.1 *

Extensions:
sentinel 0.1.2
vm-repair 0.4.3
datafactory 0.5.0
datashare 0.1.1
log-analytics-solution 0.1.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context

I ran the command in debug mode and I see it's calling below url:
  https://management.azure.com/subscriptions/xxxxxxxxxxxx/resourceGroups/rg-xx/providers/Microsoft.OperationalInsights/workspaces/law-xx/providers/Microsoft.SecurityInsights/alertRules?api-version=2020-01-01

If I hit the url directly it will work but via cli I get the error _Resource Not Found_
I logged in via my own account for azure cli so it's not running under another sp account.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@rezarms Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@rezarms Please select the right subscription in AzureCLi before you run the alert-rule list command as shown below:


>az login
az account set --subscription "XXXXX-XXXXX-XXXXX-XXXX"
az sentinel alert-rule list --resource-group MyRGName --workspace-name MyWorkspaceName


Hope this helps.

**Comment by rezarms** [comment]
I'm sure I already selected proper subscription because I could see the resources there and in the debug mode the url contained  the correct subscription id  and also   running `az account show `  showed the proper subscription.
I did   
```
az logout
az login
az account set --subscription "XXXXX-XXXXX-XXXXX-XXXX"
```  
and it worked.
I have the same issue in powershell. 
` Get-AzSentinelAlertRule -ResourceGroupName rg-xx -WorkspaceName law-xx`
I can see the correct subscription using get-azcontext but I get the error _Resource not found ._
The powershell section was an example to show that the issue occured in both environment even though the proper subscription is selected.
Since the urls are the same I guess something is wrong with token during token acqusization.

**Comment by navba-MSFT** [comment]
@rezarms For Powershell, you can try to run the below command to select the right subscription:

>Connect-AzAccount
>Select-AzSubscription -SubscriptionId 'XXXXX-XXXX-XXXX-XXXX'

Once you run the above command, then you can run the `Get-AzSentinelAlertRule` command. If you face the same issue after running the above command you can share the debug traces obtained after running `$DebugPreference="Continue"` command. Awaiting your reply.

**Comment by rezarms** [comment]
The error still persists.It's the same error I had with cli.
I can see the resources using `get-azresource -resourcegroup  myrg `
`Get-AzContext ` shows the correct subscription.

**Comment by navba-MSFT** [comment]
@rezarms  If you face the same issue after running the above command you can share the debug traces obtained after running $DebugPreference="Continue" command. Awaiting your reply.

**Comment by rezarms** [comment]
This is the output in debug :
```

DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [09/08/2022 08:21:51 - ] === Token Acquisition (SilentRequest) started:
	
	Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [09/08/2022 08:21:51 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [09/08/2022 08:21:51 - ] Access token is not expired. Returning the found cache entry. [Current time (09/08/2022 08:21:51) - 
Expiration Time (09/08/2022 09:35:45 +00:00) - Extended Expiration Time (09/08/2022 09:35:45 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [09/08/2022 08:21:51 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [09/08/2022 08:21:51 - ] Fetched access token from host login.microsoftonline.com. 
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [09/08/2022 08:21:51 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 09/0
8/2022 09:35:45 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-09-08T09:35:45.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxx', UserId: 'xxx@xx'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xx/resourceGroups/rg-xx/providers/Microsoft.OperationalInsights/workspaces/law-xx/providers/Microsoft.SecurityInsights/alertRules?api-version=2020-01-01

Headers:
x-ms-client-request-id        : 93228ba2-xxxx
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 2044fe51-xxx
x-ms-correlation-request-id   : 2044fe51-xxxx
x-ms-routing-request-id       : UKSOUTH:20220908T082151Z:xxxx
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 08 Sep 2022 08:21:51 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.OperationalInsights/workspaces/law-xx' under resource group 'rg-xx' was not found. For more details please go
 to https://aka.ms/ARMResourceNotFoundFix"
  }
}


```

The absolute url is exactly what I expect. It contacis correct subscription Id, resource group and workspace .
If I hit the url it returns data.
```
$url = "https://management.azure.com/subscriptions/xx/resourceGroups/rg-xx/providers/Microsoft.OperationalInsights/workspaces/law-xx/providers/Microsoft.SecurityInsights
$method = "GET"
$context=Get-AzContext
$token = Get-AzAccessToken   -DefaultProfile $context 
$token = $token.Token
$headers = @{Authorization = "Bearer $token"}
$response = Invoke-RestMethod -Uri $url -Method $method -Headers $headers
$response.value.Count
```

**Comment by rezarms** [comment]
it seems stupid but I restarted my PC and it's working now.

**Comment by navba-MSFT** [comment]
@rezarms Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
