### ISSUE TITLE
The extension operation failed with the following error: Failed to resolve the extension version from the given values.

### ISSUE THREAD

**Issue by Remigijus-D** [Azure/azure-cli-extensions#5325]
### Related command

az k8s-extension create --cluster-type appliances --cluster-name $resource_name --resource-group $resource_group --name hci-vmoperator --extension-type Microsoft.AZStackHCI.Operator --scope cluster --release-namespace helm-operator2 --configuration-settings Microsoft.CustomLocation.ServiceAccount=hci-vmoperator --configuration-protected-settings-file $csv_path\ResourceBridge\hci-config.json --configuration-settings HCIClusterID=$hciClusterId --auto-upgrade true

(ExtensionOperationFailed) The extension operation failed with the following error: Failed to resolve the extension version from the given values.
Code: ExtensionOperationFailed
Message: The extension operation failed with the following error: Failed to resolve the extension version from the given values.

### Extension name (the extension in question)

az k8s-extension v1.3.3

### Description of issue (in as much detail as possible)

Changing --auto-upgrade true to --version 1.2.3, command works.

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@Remigijus-D Thank you for reaching out to us, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@Remigijus-D We are unable to reproduce this issue, see image below. Can you share your environment details as well please? if possible debug trace.
![image](https://user-images.githubusercontent.com/49954584/190180100-f9239014-3942-4136-b052-910a719808be.png)

**Comment by yashdhanore** [comment]
Hi @Remigijus-D did you find a fix for this?
