### ISSUE TITLE
MissingAzureKubernetesMapping: does not support resource type with api-version '2021-09-01-preview'

### ISSUE THREAD

**Issue by Remigijus-D** [Azure/azure-cli-extensions#5326]
### Related command

az azurestackhci virtualnetwork create --subscription $subscription --resource-group $resource_group --extended-location name="/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.ExtendedLocation/customLocations/$customloc_name" type="CustomLocation" --location $Location --network-type "Transparent" --name $vnetName

Command group 'azurestackhci' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus

MissingAzureKubernetesMapping: The custom location '/subscriptions/sub-id/resourceGroups/AzureStackHCI/providers/Microsoft.ExtendedLocation/customLocations/cl-name' does not support resource type 'Microsoft.AzureStackHCI/virtualnetworks' with api-version '2021-09-01-preview'. The currently enabled api-versions for the resource type 'Microsoft.AzureStackHCI/virtualnetworks' are [2020-11-01-preview,2021-07-01-preview]. Please select one of the enabled api-versions for this version of the 'Microsoft.AzureStackHCI' cluster extension.

### Extension name (the extension in question)

name": "azurestackhci"
version": "0.2.4"

### Description of issue (in as much detail as possible)

All commands were used inside Azure Stack HCI cluster node hosted inside Azure Stack HCI sandbox environment (Azure VM).

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@Remigijus-D Thank you for reaching out, we are looking into it.
