### ISSUE TITLE
ssh vm command is no longer handling additional ssh arguments

### ISSUE THREAD

**Issue by Zhaph** [Azure/azure-cli-extensions#5333]
### Related command

```
az ssh vm --hostname example.com -- -N -T -R 30124:localhost:7162
```

### Extension name (the extension in question)
ssh

### Description of issue (in as much detail as possible)

I'm attempting to pass the additional SSH arguments `-N -T -R 30124:localhost:7162` to the SSH connection, which has previously worked as expected (i.e. it's routing traffic from the VM on port 30124 to my local instance on port 7162, basically poor man's ngrok), as covered in the [examples - "Using additional ssh arguments"](https://docs.microsoft.com/en-us/cli/azure/ssh?view=azure-cli-latest#az-ssh-vm-examples).

Attempting to run the same command today results in:

```
unrecognized arguments: -N -T -R
```

Using lowercase arguments (which would fail if passed to the VM results in:

```
 az ssh vm --hostname example.com -- -n -t -r 30124:localhost:7162

argument --vm-name/--name/-n: expected one argument

Examples from AI knowledge base:
az ssh vm --ip 1.2.3.4 az ssh vm --hostname example.com
Give the public IP (or hostname) of a VM to SSH using AAD issued certificates
```

Output of `az --version`

```
azure-cli                         2.40.0

core                              2.40.0
telemetry                          1.0.8

Extensions:
ssh                                1.1.2

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\[usename]\.azure\cliextensions'
```

Not sure if this is an issue with the ssh extension or the core CLI to be honest.

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Zhaph** [comment]
Sorry @yonzhan is that a direction for me to do something? Should I raise this in a different repo?

**Comment by yonzhan** [comment]
ssh related commands are owned by service team

**Comment by vthiebaut10** [comment]
Hi @Zhaph - Thanks for reporting this issue. I wasn't able to repro this on my end, it works when I try this scenario. Can you try updating the extension version to the latest 1.1.3 and azure cli 2.41.0 and see if the problem continues? Also, are you running this commands on PowerShell? If yes, what version?

**Comment by Zhaph** [comment]
Will give that a go when I'm back at my machine.

I have to run this with standard Powershell not ps-core as the routing back to localhost doesn't seem to play ball otherwise.

**Comment by Zhaph** [comment]
@vthiebaut10 thanks for looking into this.

I've upgraded the CLI and extension as suggested:
```
azure-cli                         2.41.0

core                              2.41.0
telemetry                          1.0.8

Extensions:
ssh                                1.1.3

Dependencies:
msal                            1.20.0b1
azure-mgmt-resource             21.1.0b1
```

Output of $PSVersionTable:
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Attempting to connect to the VM with just the `hostname` argument now results in (without the additional arguments on `--`)
```
--resource-group and --vm-name/--name must be provided together
```

This should work according to the documents without requiring the Resource Group or VM Name arguments.

However, switching to the full arguments does indeed appear to connect as expected now:
```
> az ssh vm --name vm-name --resource-group vm-group
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-1073-azure x86_64)
```

And I'm able to successfully pass additional SSH arguments on the command line.
```
> az ssh vm --name vm-name --resource-group vm-group -- -N -T -R 30124:localhost:7162
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```

I guess we'd need a new ticket for why SSH 1.1.3 no longer works with the `--hostname` or `--ip` arguments?
