### ISSUE TITLE
`az containerapp create` mentiones --yaml argument, but ap spec doc says it isn't currently used for ACA

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli-extensions#5365]
### Related command
`containerapp`

### Extension name (the extension in question)
containerapp

### Description of issue (in as much detail as possible)
![image](https://user-images.githubusercontent.com/74415662/191053895-e766166b-b92f-4907-a5e0-115c69f88ec3.png)

The CLI help for `containerapp create` mentions using --yaml, but the [API spec doc mentioned in the argument help](https://learn.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml#examples) says YAML isn't currently used.

-----

**Comment by panchagnula** [comment]
Thanks for reporting @charris-msft .From CLI perspective this is supported, I am unsure who owns the other documentation. It might be a good idea to report this on the ACA Github repo directly. Tagging @anthonychu & @torosent as well for awareness / comments

**Comment by yonzhan** [comment]
route to CXP team

**Comment by charris-msft** [comment]
> Thanks for reporting @charris-msft .From CLI perspective this is supported, I am unsure who owns the other documentation. It might be a good idea to report this on the ACA Github repo directly. Tagging @anthonychu & @torosent as well for awareness / comments

Great - Is there somewhere I can find an example .yaml file?

**Comment by panchagnula** [comment]
> > Thanks for reporting @charris-msft .From CLI perspective this is supported, I am unsure who owns the other documentation. It might be a good idea to report this on the ACA Github repo directly. Tagging @anthonychu & @torosent as well for awareness / comments
> 
> Great - Is there somewhere I can find an example .yaml file?

oh its already part of the help - the one you have highlighted.   https://learn.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-create 
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/13839372/191138274-bdf1564a-35f1-4225-9aa4-757951d60adc.png">
 however I am unsure how updated this example file is with a whole bunch of new properties added.

**Comment by charris-msft** [comment]
I was a example of the contents of the .yaml file, but after you said that I found an example further down in that doc here: [Exmaples](https://learn.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml#container-app-examples)

**Comment by navba-MSFT** [comment]
@charris-msft Thanks for reporting this issue. The above PR has been filed to address this docs issue. It its currently under review. Please let us know if you need any further assistance on this.
