### ISSUE TITLE
Using preview API  within k8s-extension

### ISSUE THREAD

**Issue by t0rben** [Azure/azure-cli-extensions#5384]
## Describe the bug

**Command Name**
`az k8s-extension extension-types list
Extension Name: k8s-extension. Version: 1.3.4.`

**Errors:**
```
(NoRegisteredProviderFound) No registered resource provider found for location 'westeurope' and API version '2022-01-15-preview' for type 'connectedClusters'. The supported api-versions are '2020-01-01-preview, 2021-03-01, 2021-04-01-preview, 2021-10-01, 2022-05-01-preview'. The supported locations are 'westeurope, eastus, westcentralus, southcentralus, southeastasia, uksouth, eastus2, westus2, australiaeast, northeurope, francecentral, centralus, westus, northcentralus, koreacentral, japaneast, westus3, eastasia, canadacentral'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'westeurope' and API version '2022-01-15-preview' for type 'connectedClusters'. The supported api-versions are '2020-01-01-preview, 2021-03-01, 2021-04-01-preview, 2021-10-01, 2022-05-01-preview'. The supported locations are 'westeurope, eastus, westcentralus, southcentralus, southeastasia, uksouth, eastus2, westus2, australiaeast, northeurope, francecentral, centralus, westus, northcentralus, koreacentral, japaneast, westus3, eastasia, canadacentral'.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az k8s-extension extension-types list -g {} --cluster-name {} --cluster-type {}`

## Environment Summary
```
macOS-12.6-arm64-arm-64bit, Darwin 21.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.40.0

Extensions:
connectedk8s 1.3.3
k8s-extension 1.3.4

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@t0rben Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@t0rben Could you please update and run the below command and see if that helps ?

> az rest --method GET --uri https://management.azure.com/subscriptions/XXXXX-XXX-XXXX-XXX/resourceGroups/MyRGName/providers/Microsoft.ContainerService/**MyClusterType**/MyClusterName/providers/Microsoft.KubernetesConfiguration/extensions?api-version=2022-04-02-preview

**Note:** Please update the Subsciption ID, Resource Group Name, Cluster Name and Cluster Type in the above request URL.
MyClusterType : i.e. managedClusters, connectedClusters, provisionedClusters

Hope this helps.
