### ISSUE TITLE
Listing the alerts in azure monitor fails with error

### ISSUE THREAD

**Issue by radhakrishnan-chandarasikharan-kr** [Azure/azure-cli-extensions#5390]
## Describe the bug
Ran the command to list the alerts in azure monitor and got the following error.

**Command Name**
`az monitor alert-processing-rule list
Extension Name: alertsmanagement. Version: 0.2.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'"))
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1436, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1180, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/Users/rc45017/.azure/cliextensions/alertsmanagement/azext_alertsmanagement/vendored_sdks/alertsmanagement/operations/_alert_processing_rules_operations.py", line 177, in get_next
    error = self._deserialize(models.ErrorResponse, response)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1376, in __call__
    return self._deserialize(target_obj, data)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1454, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1436, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1180, in rest_key_extractor
    return working_data.get(key)
azure.core.exceptions.DeserializationError: ("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'"))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor alert-processing-rule list -g {}`

## Environment Summary
```
macOS-12.6-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.40.0

Extensions:
alertsmanagement 0.2.2
cosmosdb-preview 0.8.1
application-insights 0.1.16

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by navba-MSFT** [comment]
@radhakrishnan-chandarasikharan-kr Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@radhakrishnan-chandarasikharan-kr I used the same version of the AzCLI and the `alertsmanagement `extension as your environment. See below:

>az version
{
  **"azure-cli": "2.40.0",**
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    **"alertsmanagement": "0.2.2"**
  }
}

While I tried to run the same command at my end and it worked fine. I am unable to reproduce this issue. See below:

> **az monitor alert-processing-rule list --resource-group MYRGName**

**Output:**
[
  {
    "id": "/subscriptions/XXXX-XXX-XXXX-XXXX/resourceGroups/MYRGName/providers/Microsoft.AlertsManagement/actionRules/MyRuleName",
    "location": "Global",
    "name": "navbarule",
    "properties": {
      "actions": [
        {
          "actionGroupIds": [
            "/subscriptions/XXXX-XXXX-XXXXXX-XXX/resourcegroups/MYRGName/providers/microsoft.insights/actiongroups/application insights smart detection"
          ],
          "actionType": "AddActionGroups"
        }
      ],
      "conditions": null,
      "description": null,
      "enabled": true,
      "schedule": null,
      "scopes": [
        "/subscriptions/XXXXX-XXX-XXXX-XXXXX/resourceGroups/MYRGName"
      ]
    },
    "resourceGroup": "MYRGName",
    "systemData": {
      "createdAt": "2022-09-27T07:00:45.298962+00:00",
      "createdBy": "XXXXXX@microsoft.com",
      "createdByType": "User",
      "lastModifiedAt": "2022-09-27T07:00:45.298962+00:00",
      "lastModifiedBy": "XXXXXX@microsoft.com",
      "lastModifiedByType": "User"
    },
    "tags": {
      "blob": "data"
    },
    "type": "Microsoft.AlertsManagement/actionRules"
  }
]

As an alternative, could you please try **either** of the below commands and check if that helps ?

**Command 1:**

>az resource list --resource-group MYRGName --resource-type "Microsoft.AlertsManagement/actionRules"


**Command 2:**

>az rest --uri "https://management.azure.com/subscriptions/XXXXX-XXXX-XXXX-XXXX/resourceGroups/MyRGName/providers/Microsoft.AlertsManagement/actionRules?api-version=2021-08-08"

Hope this helps.

**Comment by radhakrishnan-chandarasikharan-kr** [comment]
The command

> az resource list --resource-group MYRGName --resource-type "Microsoft.AlertsManagement/actionRules"

did not work. However when I included the the subscription, it worked
> az resource list --resource-group MYRGName --subscription mySID --resource-type "Microsoft.AlertsManagement/actionRules"

But adding the subscription to the original command did not throw any error, but neither was there any response. I get back an empty array ([])
> az monitor alert-processing-rule list --subscription MYSID --resource-group MYRG

The command
> az rest --uri "https://management.azure.com/subscriptions/XXXXX-XXXX-XXXX-XXXX/resourceGroups/MyRGName/providers/Microsoft.AlertsManagement/actionRules?api-version=2021-08-08"
returns an empty array ([])

**Comment by navba-MSFT** [comment]
@radhakrishnan-chandarasikharan-kr Thanks for getting back.

- Could you please confirm if the resource group has any alert processing rules inside it ?
- Could you try to create a new processing rule and check if that lists by running either of the above 2 commands ?

I have tried the same 2 commands at my end and it shows the output. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@radhakrishnan-chandarasikharan-kr I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by radhakrishnan-chandarasikharan-kr** [comment]
@navba-MSFT The resource group has a list of alerts. These are working and firing!

Few things I want to do and hence trying to use the cli. (a) The name of the alert cannot be updated; so I have to recreate it with a new name. (b) I haven't been able to find how to create the alerts in Terraform;
I'm hoping to be able to accomplish these using the CLI

**Comment by navba-MSFT** [comment]
@radhakrishnan-chandarasikharan-kr Thanks for getting back. Could you please run the same command with `--debug` switch and share the output with me over email navba [@] microsoft [dot] com? Also in the meantime try to run the command from the [Azure Cloud Shell TryIt](https://learn.microsoft.com/en-us/cli/azure/monitor/alert-processing-rule?view=azure-cli-latest#code-try-10) option and check if that works fine ? Awaiting your reply.

**Comment by radhakrishnan-chandarasikharan-kr** [comment]
The cloud shell tryit requires me to have a storage account; don't have one in my resource group that I can use for this purpose.
Is there an option, along with --debug, to anonymize the data? (OR) do you need the resource/subscription details?

**Comment by navba-MSFT** [comment]
@radhakrishnan-chandarasikharan-kr Thanks for your reply. The --debug output itself will contain the resource / subscription details. But the goal here is to check the rest api calls being done along with the response received from the API call. So please run the same command with --debug switch and share the output with me over email navba [@] microsoft [dot] com?

**Comment by navba-MSFT** [comment]
@radhakrishnan-chandarasikharan-kr I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@radhakrishnan-chandarasikharan-kr The action is currently pending on you to share the debug details once you get a chance. Please feel free to reopen this thread, once you have the details. We would be happy to help.
