### ISSUE TITLE
Json Encoder MemoryError during job list

### ISSUE THREAD

**Issue by jjdharini22** [Azure/azure-cli-extensions#5412]
## Describe the bug
Az singularity job list cli failed with MemoryError when trying to list jobs in json format.

**Command Name**
`az singularity job list
Extension Name: singularity-cli. Version: 1.0.20472898.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 237, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 146, in out
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 37, in format_json
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 202, in encode
MemoryError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az singularity job list --resource-group {} --account-name {} --only-show-errors`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0 *

Extensions:
azure-devops 0.25.0
singularity-cli 1.0.20472898

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@jjdharini22 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@jjdharini22 Could you please run the same command with `--debug` argument and share the detailed debug logs here ? Awaiting your reply.

**Comment by jjdharini22** [comment]
No, this is Singularity which is a preview AI Infrastructure Azure service. https://singularitydocs.azurewebsites.net/

**Comment by jjdharini22** [comment]
Yes, I updated to the latest AzCli. That does not help. Still seeing the same error.

**Comment by navba-MSFT** [comment]
@jjdharini22 Please refer to our internal Teams group conversation and let us know if you have any follow-up questions.

**Comment by navba-MSFT** [comment]
@jjdharini22 Please track this issue in our internal Teams conversation with the CLI Product team.
