### ISSUE TITLE
Incorrect Scope for Data Factory Git Configuration

### ISSUE THREAD

**Issue by JP-Ellis-KPMG** [Azure/azure-cli-extensions#5419]
### Related command
`az datafactory configure-factory-repo`

### Extension name (the extension in question)
`datafactory`

### Description of issue (in as much detail as possible)

We have some users who have privileges restricted to specific resource groups and do not have access to the subscription as a whole. These users are able to configure their Data Factory in their resource group perfectly fine if done through the web interface, but the corresponding configuration through the `az datafactory configure-factory-repo` fails with the error:

```text
ERROR: (AuthorizationFailed) The client 'email@example.com' with object id '[redacted]' does not have authorization to perform action 'Microsoft.DataFactory/locations/configureFactoryRepo/action' over scope '/subscriptions/[redacted]' or the scope is invalid.
```

This issue has been raised separately in the main Azure CLI repo at Azure/azure-cli#18402, but I have opened one here as this is probably where the fix would need to be implemented.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
Already being investigated here https://github.com/Azure/azure-cli/issues/18402
