### ISSUE TITLE
azure lb disconnect from aks vmss

### ISSUE THREAD

**Issue by tehho** [Azure/azure-cli-extensions#544]
### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
When creating a aks with --enable-vmss and you expose your cluster with a loadbalancer the loadbalancer gets connected to the vmsscluster.
If you need to disconnect, lets say you by misstake didn't use the correct public ip, this is not posible as vmss needs lb once it got is.

----
Love the feature and scaleability

**Comment by yonzhan** [comment]
aks-preview

**Comment by navba-MSFT** [comment]
@tehho Apologies for the late reply. Refer [this](https://docs.microsoft.com/en-us/azure/load-balancer/update-load-balancer-with-vm-scale-set) article and check if that helps. This issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by tehho** [comment]
Thank you for the response and the walk down memory lane. 

This was an issue back when we used azure cli to create our aks cluster. 
We have moved on to terraform as this was a better fit for us.
