### ISSUE TITLE
 az ml environment archive fails with  error already registered and cannot be changed.

### ISSUE THREAD

**Issue by haranathvaranasisce** [Azure/azure-cli-extensions#5440]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command

 az ml environment 
### Description of issue (in as much detail as possible)
 az ml environment archive -n test_env -v 6 --resource-group testrg --workspace-name  testws

(UserError) Environment test_env with version 6 is already registered and cannot be changed.
Code: UserError
Message: Environment test_env with version 6 is already registered and cannot be changed.

What does the above error mean ? I have a few versions where build failed and remained in zombie state and would like to clean from our workspace.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@haranathvaranasisce Thank you for reaching out, we are looking into it.

**Comment by haranathvaranasisce** [comment]
will there be any update?

**Comment by banibrata** [comment]
Thanks for reaching out, could you please share the output of az  -v ?

**Comment by haranathvaranasisce** [comment]
azure-cli                         2.39.0 *

core                              2.39.0 *
telemetry                          1.0.6 *

Extensions:
ml                                 2.5.0

Dependencies:
msal                              1.18.0
azure-mgmt-resource               21.1.0

Python location '/anaconda/envs/azureml_py38/bin/python'
Extensions directory '/opt/az/extensions'

Python (Linux) 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by banibrata** [comment]
it shows you are using ml extension version 2.5.0, this is few months old, could you try using the latest one which should be 2.10.0. 

You can use this command to remove the current one and get the latest

1. az extension remove -n ml
2. az extension add -n ml
