### ISSUE TITLE
`az kusto script create` for a cluster scoped commands

### ISSUE THREAD

**Issue by JiriKovar** [Azure/azure-cli-extensions#5442]
### Related command

`az kusto script create` 

### Extension name (the extension in question)

kusto

### Description of issue (in as much detail as possible)

Hi, I'm trying to run a command:

`.alter cluster policy managed_identity ```
[
  {
    "ObjectId": "${cluster_principal_id}",
    "AllowedUsages": "ExternalTable"
  }
]`

as part of `az kusto script create` but it fails with `Reason: Not a database-scope command` even though the script succeeds in the portal even when scope is set to the database, not cluster.

Can this be fixed please?

Thank you very much!

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@JiriKovar Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@JiriKovar The command should ran on cluster, not as part of a script.
.alter cluster policy managed_identity ``` [ { "ObjectId": "${cluster_principal_id}", "AllowedUsages": "ExternalTable" } ].
