### ISSUE TITLE
Failed to resolve Dapr 1.9.0

### ISSUE THREAD

**Issue by jyama4ta** [Azure/azure-cli-extensions#5470]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command
Targeting a specific Dapr version (in this case, 1.9.0)  
https://learn.microsoft.com/en-us/azure/aks/dapr#targeting-a-specific-dapr-version

``` shell
az k8s-extension create --cluster-type managedClusters \
--cluster-name myAKSCluster \
--resource-group myResourceGroup \
--name myDaprExtension \
--extension-type Microsoft.Dapr \
--auto-upgrade-minor-version false \
--version 1.9.0
```

### Extension name (the extension in question)
k8s-extension

### Description of issue (in as much detail as possible)
Dapr 1.9.0 was released at Oct.13th and it is latest version.
https://docs.dapr.io/operations/support/support-release-policy/#supported-versions  
https://github.com/dapr/dapr/releases/tag/v1.9.0  

 I try to install it with specific version parameter, but I got following error message. Could you please advise me how to install the latest version?
_(ExtensionOperationFailed) The extension operation failed with the following error:  Failed to resolve the extension version from the given_

-----

**Comment by shubham1172** [comment]
@jyama4ta hello, Dapr 1.9.0 was released a few hours back, can you please try this command again?

**Comment by jyama4ta** [comment]
@shubham1172 Thank you for your help. I have checked it is successeded now. Thanks again!
