### ISSUE TITLE
Not able to enable feature "--enable-blob-driver" in AKS-Preview version 0.5.111 using Service Principal (SP)

### ISSUE THREAD

**Issue by edervaldonetoMS** [Azure/azure-cli-extensions#5488]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command
az aks update --enable-blob-driver -g labeddie -n testeddie

### Extension name (the extension in question)
aks-preview": "0.5.111

### Description of issue (in as much detail as possible)
Not able to enable feature "--enable-blob-driver" in **AKS-Preview version 0.5.111 latest version** using Service Principal (SP). 
Its only working if we re-install the old AKS-Preview version "0.5.105", then we can enable the feature.

Using MSI works perfectly, no issue so far.

Can we have this fixed please?

![image](https://user-images.githubusercontent.com/56553626/197995946-4d1a9757-6b10-4689-81f0-83e33e2ad51e.png)

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by andyzhangx** [comment]
cc @FumingZhang

**Comment by FumingZhang** [comment]
Will take a look

**Comment by edervaldonetoMS** [comment]
Hello All!

Do we have any update on this?

**Comment by FumingZhang** [comment]
Hi @edervaldonetoMS, could you please use the latest aks-preview release 0.5.113 to rerun the command? I think I've fixed the issue in PR #5490.

**Comment by edervaldonetoMS** [comment]
@FumingZhang 

Working perfectly. Thanks a lot.

We can close this thread.
