### ISSUE TITLE
[Kusto] Cannot create script/function when another cluster is referred (perms issue?)

### ISSUE THREAD

**Issue by sadatnfs** [Azure/azure-cli-extensions#5489]
## Problem
 I cannot deploy a script (with a function) to my ADX cluster using the CLI, where the function is referring to a different cluster/DB table compared to the one I'm pushing the script to.

### Related command
```bash
queryStr=""".create-or-alter function someFunk() {
  let data1 = cluster('CLUSTER_A').database('DB_A').someTable1;
  let data2 = cluster('CLUSTER_B').database('DB_b').someTable2;
  data 
  | join kind=inner (data2) on someColumn
}
"""
az kusto script create \
  -g $rgName --cluster-name CLUSTER_A --database-name DB_A --name somename \
  --script-content """$queryStr"""
```

### Extension name (the extension in question)
`kusto`

### Description of issue (in as much detail as possible)

**Problem**: I cannot deploy a script (with a function) to my ADX cluster using the CLI, where the function is referring to a different cluster/DB table compared to the one I'm pushing the script to.

**Example**: I made up a query in my related command example above. I'm trying to create a function in CLUSTER_A/DB_A, but the function itself pulls a table from CLUSTER_B/DB_B.

**Use case**: Our team uses data from multiple other teams, and therefore joining tables from different sources is a requirement for us. And it just so happens that the different sources/tables are in different ADX clusters.

**What happens**: I get an auth error that the client is not able to ping the other cluster (CLUSTER_B) in this case.

**Note**: If I create the function directly on Kusto Web Explorer, I am able to create the function. Both me (user) and the service principal (which I'll use to call the CLI extension) have access to the cluster/DBs of interest.

### Error (when pushing to CLUSTER_A)

```bash
...
Reason: Request is invalid and cannot be processed: Semantic error: SEM0056: Errors occurred while resolving remote entities. Cluster='https://CLUSTER_B.kusto.windows.net/': Authorization has been denied for this request.
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by sadatnfs** [comment]
@navba-MSFT  FYI I messaged some folks internally, and they concluded that this is not possible because ARM is not able to authenticate across multiple Kusto clusters in a single call.

The workaround I ended up using is to use Python SDK and then managing all the calls from that instead. Works perfectly then since the SPI auth just works.
