### ISSUE TITLE
upgrade CLI extension fails when --source is specified, but works while specifying --version

### ISSUE THREAD

**Issue by cheguv** [Azure/azure-cli-extensions#5491]
In the following i am using azurestackhci as example cli extension, the issue is not with the extension, its with cli command "add"
### Related command
**works** : az extension add --name azurestackhci --version "0.2.5"  --verbose --yes --upgrade
**fails**: az extension add --source "c:\versions\test\azurestackhci-0.2.5-py3-none-any.whl" --verbose --yes --update
**fails**: az extension add --source "c:\versions\azurestackhci-0.2.5-py3-none-any.whl" --verbose --yes --upgrade

### Extension name (the extension in question)
az extension add

### Description of issue (in as much detail as possible)
While upgrading a CLI extension, upgrade using version works, however upgrade using source fails.
Tried upgrade with source as local path or internet url, in both cases it fails.

Steps to repo:
eg: 
1) on a machine azurestackhci CLI extension version 0.2.1 is installed.
**az extension add --source "c:\versions\azurestackhci-0.2.1-py3-none-any.whl" --verbose --yes** 

2) try to upgrade the CLI extension using source path with newer version - **fails**
**az extension add --source "https://hybridaksstorage.z13.web.core.windows.net/SelfServiceVM/CLI/azurestackhci-0.2.5-py3-none-any.whl" --verbose --yes --upgrade**
![image](https://user-images.githubusercontent.com/21251550/198204721-0d0a332d-ebe9-461d-b2b7-907d965e5997.png)

3) download this whl file locally to a machine and try to upgrade from local path - **fails**
**az extension add --source "c:\versions\azurestackhci-0.2.5-py3-none-any.whl" --verbose --yes --upgrade**
![image](https://user-images.githubusercontent.com/21251550/198203334-cd5f07fb-d1c9-468e-8efc-81f34a5923b3.png)

4) try to do the same upgrade using version, it **succeeds**
**az extension add --name azurestackhci --version "0.2.5"  --verbose --yes --upgrade**
![image](https://user-images.githubusercontent.com/21251550/198203475-89e1fec8-7516-4e48-80f9-501f410ae9f7.png)
after this step, the extension is upgraded from 0.2.1 to 0.2.5.

notice the warning in step4, where as error in step 2 and 3.

Expected : upgrade using --source (whl file path) should succeed either from local or blob link.

-----

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by bebound** [comment]
I can reproduce this.
When use `--source`, the `--upgrade` param is ignored.

I'll fix this.
