### ISSUE TITLE
Dapr with outbound firewall - containers calling out to raw.githubusercontent.com and failing repeatedly if this is blocked

### ISSUE THREAD

**Issue by joshuadmatthews** [Azure/azure-cli-extensions#5493]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command
Installing the extension through Bicep

```
resource daprExtension 'Microsoft.KubernetesConfiguration/extensions@2022-04-02-preview' = if(daprAddon) {
  name: 'dapr'
  scope:aks
  properties: {
    extensionType: 'Microsoft.Dapr'
    autoUpgradeMinorVersion: true
    releaseTrain: 'Stable'
    configurationSettings: {
       'global.ha.enabled': '${daprAddonHA}'
    }
    scope: {
      cluster: {
        releaseNamespace: 'dapr-system'
      }
    }
    configurationProtectedSettings: {}
  }
} 
```

### Extension name (the extension in question)
Dapr

### Description of issue (in as much detail as possible)
Seemingly during the 1.9 upgrade Dapr was attempting to reach raw.githubusercontent.com repeatedly for CRDs. Container logs for the failing containers are attached. 
-----
[crd_logs.csv](https://github.com/Azure/azure-cli-extensions/files/9879427/crd_logs.csv)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by joshuadmatthews** [comment]
I did also have issue during the 1.9 upgrade and bicep deploys got stuck. I had to tear down and rebuild my cluster to get things unstuck.

**Comment by jsntcy** [comment]
@joshuadmatthews, could you please provide which azure cli extension you used? Actually there is no "Dapr" extension in Azure CLI.

**Comment by pravinpushkar** [comment]
Thanks @joshuadmatthews for sharing the logs.  It looks like it is trying execute initcontainer from pre upgrade hook.
One thing that is not clear is why it is executing endlessly and not timing out.

BTW, for your information the pre upgrade hook can be disabled during `az k8s-extension update ...` by passing `--configuration-settings "hooks.applyCrds=false"` this parameter.

**Comment by jsntcy** [comment]
@deeksha345, @bavneetsingh16, could you please help look at this issue?

**Comment by shubham1172** [comment]
@jsntcy you can assign me to this issue.

>What are the side effects to disabling CRDs hooks?

@joshuadmatthews, the CRD hooks are there in place to automatically upgrade your CRDs when Dapr is upgraded. You can disable it without any harm and use `kubectl apply -f` to manually upgrade Dapr CRDs for now, see https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/#helm

In the Bicep snippet, you can alter the `configurationSettings` to add `hooks.applyCrds=false` as Pravin suggested. This will shortly be updated in the [official docs](https://learn.microsoft.com/en-us/azure/aks/dapr) as well.

**Comment by shubham1172** [comment]
Hello @joshuadmatthews, Dapr extension for AKS v1.9.2 is available in the dev train. You can test it and the CRDs will be pulled from MCR directly (without having to allow-list raw.githubusercontent.com).

```bash
az k8s-extension create --cluster-type managedClusters \
--cluster-name $CLUSTER_NAME \
--resource-group $RESOURCE_GROUP \
--name dapr \
--extension-type Microsoft.Dapr \
--release-train dev
```

**Comment by joshuadmatthews** [comment]
@shubham1172 thanks! I’m having some issues installing the dapr extension at all right now, gets stuck in creating status, and deleting the extension eventually fails with timeout calling the agent. 

Once I get that worked out I can test this update. Sounds great that they come from MCR now.

**Comment by RakeshMohanMSFT** [comment]
@joshuadmatthews I see that your creating issue was fixed recently. Did you get a chance to test this issue after that?
