### ISSUE TITLE
DAPR Extension gets stuck in Creating status - Extension-Agent is failing - seems to have lost the configuration it needs for MSI authentication 

### ISSUE THREAD

**Issue by joshuadmatthews** [Azure/azure-cli-extensions#5501]
### Related command
az k8s-extension create --resource-group myrg--cluster-name mycluster --cluster-type managedClusters --name dapr --extension-type Microsoft.Dapr

### Extension name (the extension in question)
Microsoft.Dapr

### Description of issue (in as much detail as possible)
When installing the extension to a private AKS cluster, it gets stuck in creating status. 

If I try to uninstall it, it goes to Deleting status and eventually settles at Failed with

```
 "statuses": [
    {
      "code": "InstallationFailed",
      "displayStatus": null,
      "level": null,
      "message": "Unabled to get a response from the Agent in time",
      "time": null
    }
  ],
```
-----

I'm unsure how to get more information about this issue. I don't see any events in KubeEvents logs, and I also don't see anything in ContainerLogs that seems pertinent to the extension installation. 

When I setup the cluster initially the extension installs fine, but on subsequent deploys it gets stuck.

This also apparently started for me when Dapr 1.9 came down the stable train. I wasn't having any issues before then.

UPDATE:

I finally found the logs for the extension-agent, for some reason they don't show up in container insights, but I can view them from kubectl.

It appears the extension-agent container has somehow lost the env variable value it needs to do MSI auth. I still need some help figuring out how this may have happened and how to prevent. 

`{"Message":"2022/11/02 13:31:21 Error: in the getting the bearer token : {parameter 'userAssignedID' cannot be empty}",`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by joshuadmatthews** [comment]
I can see in the extension agent and operator logs that it is nonstop throwing errors 

`{"Message":"2022/11/02 13:31:21 Error: in the getting the bearer token : {parameter 'userAssignedID' cannot be empty}",`

Guessing this is related

**Comment by joshuadmatthews** [comment]
Also can see that the extension-agent container has an ENV variable AKS_USER_ASSIGNED_IDENTITY_CLIENT_ID:  with no value, could this also be related?
::

**Comment by joshuadmatthews** [comment]
Seems there is a ConfigMap extension-manager-config where this env variable is sourced from, and I have verified that the value is missing from it as well.

**Comment by joshuadmatthews** [comment]
My cluster does have a user assigned managed identity.

```
   "identity": {
                "type": "UserAssigned",
                "userAssignedIdentities": {
                    "/subscriptions/xxx/resourceGroups/myrg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myidentity": {}
                }
            },
```

**Comment by joshuadmatthews** [comment]
I managed to dig into the /etc/acs/azure.json file of the extension-manager container and userAssignedIdentityID there set to clientID of the kubelete identity, but based on the error message from extension-manager logs I'm thinking it's checking in the env variable AKS_USER_ASSIGNED_IDENTITY_CLIENT_ID and the value provided by azure.json userAssignedIdentityID which seems to be a different key.

**Comment by joshuadmatthews** [comment]
Seems that Microsoft did something to resolve this. Today the extension-manager-config AKS_USER_ASSIGNED_IDENTITY_CLIENT_ID no longer has no value; it has the value of the user assigned identity that gets setup on the vm scalesets for the extensionmanager.

Strangely, I tried the exact same thing by manually updating the config map to identity that while I was troubleshooting, and was seeing 401s in the log when it tried to use that Identity. This suggests to me that Azure did something behind the scenes to grant these identities the access they need to communicate the k8s api.

The error from extension-agent have stopped and extensions are now installing successfully again.

**Comment by RakeshMohanMSFT** [comment]
@joshuadmatthews Apologies for the delay in getting back. We are actively working on fixing any issue we observe. This could have been one such issue, If it resurfaces do reopen this issue
