### ISSUE TITLE
containerapp extension fails to install and update with "Pip failed with status code 2"

### ISSUE THREAD

**Issue by YuKogasaka** [Azure/azure-cli-extensions#5528]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command
az extension add --name containerapp

### Extension name (the extension in question)
containerapp

### Description of issue (in as much detail as possible)
Attempting to install the containerapp extension using the `az extension add` command fails with "An error occurred. Pip failed with status code 2. Use --debug for more information."

This problem is not only during installation, but also during updates.

Also, this problem occurs even if you specify a version other than the latest.

#### Environment  
```
> az version
{
  "azure-cli": "2.42.0",
  "azure-cli-core": "2.42.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-firewall": "0.14.4",
    "ssh": "1.1.3"
  }
}
```
-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@YuKogasaka Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by YuKogasaka** [comment]
@navba-MSFT, this issue was already remedied.
The log no longer exists, but when the phenomenon occurred, an error was recorded that the "pyexpat" module did not exist.

**Comment by navba-MSFT** [comment]
@YuKogasaka This might be hard to troubleshoot without knowing the _complete error message details_. If you happen to get the same error again, please feel free to share the `--debug` output and we would be happy to help.
