### ISSUE TITLE
These extensions are not compatible with latest azure-cli

### ISSUE THREAD

**Issue by bebound** [Azure/azure-cli-extensions#5533]
In https://github.com/Azure/azure-cli/pull/24582, I found the below extensions have dependency conflict with azure-cli.
Due to the cli load policy, azure-cli's dependency loads first. These extensions have already used the **incompatible** dependency in latest azure-cli.

### attestation
Needs `pyjwt==1.7.1`, but in https://github.com/Azure/azure-cli-extensions/pull/5081, it's compatible with pyjwt 2.0. I think it's safe to change to `PyJWT>=2.1.0`.

### cloud-service
Needs `azure-mgmt-compute~=20.0.0`, but azure-cli has updated to `azure-mgmt-compute~=29.0.0`.

### functionapp
Its dependency `azure-functions-devops-build~=0.0.22`->`vsts` needs ` msrest<0.7.0`, but azure-cli installs `msrest 0.7.1`.

### serial-console
Needs `websocket-client~=0.56.0`, but azure-cli installs `websocket-client~=1.3.1`.

### alias
Needs `jinja2~=2.10`, which is deprecated and raises `cannot import name 'soft_unicode' from 'markupsafe'`. Azure-cli is using `Jinja2==3.0.3`.

**Comment by yonzhan** [comment]
Do we plan to engage with different service teams to resolve them?

**Comment by bebound** [comment]
Sorry if I contact the wrong person.
I found you are the recent committer of these extensions, could you please take a look. Thanks a lot.

@ZengTaoxu 
@qwordy
@PramodValavala-MSFT
@rhkodiak

**Comment by navba-MSFT** [comment]
Removing CXP attention label since this is not `Customer-reported`
