### ISSUE TITLE
 az serial-console connect with log storage in other RG than VM give a not found error

### ISSUE THREAD

**Issue by Poil** [Azure/azure-cli-extensions#5535]
## Describe the bug

**Command Name**
`az serial-console connect
Extension Name: serial-console. Version: 0.1.3.`

**Errors:**
```
(ParentResourceNotFound) Can not perform requested operation on nested resource. Parent resource 'xxxxx-vm-1' not found.
Code: ParentResourceNotFound
Message: Can not perform requested operation on nested resource. Parent resource 'xxxxxt-vm-1' not found.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az serial-console connect --instance-id {} -n {} --resource-group {}`

## Environment Summary
```
Linux-5.15.0-52-generic-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.39.0 *

Extensions:
front-door 1.0.16
azure-firewall 0.12.0
serial-console 0.1.3
azure-devops 0.25.0
ip-group 0.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by RakeshMohanMSFT** [comment]
@Poil Thank you for reaching out, we are looking into it. In the meantime can you please upgrade to the lastest version azure cli 2.42.0 and retry?
