### ISSUE TITLE
az image copy breaking on location

### ISSUE THREAD

**Issue by bebattis** [Azure/azure-cli-extensions#555]
### Extension name (the extension in question)
image-copy-extension

### Description of issue (in as much detail as possible)
While running this through the CloudShell, I received a "Resource not found" error during the snapshot creation step. I believe this happens because the extension runs the command:
`az snapshot create --name <name of snapshot to create> --resource-group <rg> --source <rg id>` and does not include the location of the disk. I attempted to run this same line with the `--location` flag and the disk was found and snapshot created.

-----

For the time being I think the work around is to set the default az cli location to the location of the original VM/disk, but it seems like this could be easily fixed. Thanks!

**Comment by tamirkamara** [comment]
@bebattis please check #466 which I think might be the same as yours

**Comment by bebattis** [comment]
Seems like #466 is related to the `--subscription` flag and mine is related to the `--location` flag. I don't have a ton of experience with the CLI so maybe these things have a very similar fix, but I would assume they are distinct problems.

**Comment by bebattis** [comment]
This seems to be an issue surrounding default CLI parameters. Workaround is to set defaults with:
`az configure --defaults` 

Not necessarily specific to this extension. Going to close this issue.
