### ISSUE TITLE
preview flag `--kube-proxy-config` unrecognized on `az aks update`

### ISSUE THREAD

**Issue by mateuszdrab** [Azure/azure-cli-extensions#5551]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command
 `az aks update -n=clustername -g=clustergroup --kube-proxy-config=proxy.json`

### Extension name (the extension in question)
`aks-preview`

### Description of issue (in as much detail as possible)
`unrecognized arguments: --kube-proxy-config`

Customer raised a case asking for support on the in-preview IPVS feature in AKS documented [here](https://learn.microsoft.com/en-us/azure/aks/configure-kube-proxy)

I've realized that the article mentions that the command `az aks update` can be used with the new `--kube-proxy-config` flag to reconfigure and existing cluster; however, the flag is not recognized and upon inspecting the source code of the addon, I can see that indeed the flag is not defined for the `aks_update` command in the file https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azext_aks_preview/custom.py and is only present for 'az aks create'

Can this issue be addressed?

This issue was reproduced on az cli version:
`
{
  "azure-cli": "2.42.0",
  "azure-cli-core": "2.42.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "aks-preview": "0.5.115",
    "connectedk8s": "1.2.7",
    "interactive": "0.4.5"
  }
}
`

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@mateuszdrab Thank you for reaching out to us, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@mateuszdrab I believe its possible that the proxy settings are allowed only during cluster creation as mentioned [here](https://learn.microsoft.com/en-us/azure/aks/http-proxy), 

The following scenarios are **not** supported:
**Updating proxy settings post cluster creation**

**Comment by mateuszdrab** [comment]
Hi @RakeshMohanMSFT 

The documentation explicitly states that it is possible for existing clusters [here](https://learn.microsoft.com/en-us/azure/aks/configure-kube-proxy#update-an-existing-cluster)

Perhaps, the documentation needs to be corrected to explicitly state that it is not.

**Comment by mateuszdrab** [comment]
I've been able to enable the feature on my cluster using a direct API PUT request, so the above is definitely possible.

Can we involve someone from the right team to look into this?

**Comment by FumingZhang** [comment]
PR [#5545](https://github.com/Azure/azure-cli-extensions/pull/5545) will add this option.

**Comment by RakeshMohanMSFT** [comment]
Thank you @FumingZhang

**Comment by mateuszdrab** [comment]
> PR [#5545](https://github.com/Azure/azure-cli-extensions/pull/5545) will add this option.

Thanks for the update @FumingZhang
