### ISSUE TITLE
unable to launch vmware script with opensuse

### ISSUE THREAD

**Issue by max660x** [Azure/azure-cli-extensions#5554]
## Describe the bug

**Command Name**
`az arcappliance run vmware
Extension Name: arcappliance. Version: 0.2.23.`

**Errors:**
```
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/core/commands/client_factory.py, ln 176, in _get_mgmt_service_client
    logger.debug('Getting management service client client_type=%s', client_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az arcappliance run vmware --debug --tags {} {} {} {} --subscription {} --resource-group {} --name {} --location {}`

## Environment Summary
```
Linux-5.3.18-150300.59.68-default-x86_64-with-glibc2.3.4
Python 3.6.15
Installer: PIP

azure-cli 2.17.1 *

Extensions:
arcappliance 0.2.23
k8s-extension 0.4.1
customlocation 0.1.3
connectedvmware 0.1.8

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@max660x Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@max660x I see that you are running an older version of Azure CLI. Could you please update the Azure CLI to the [most recent version](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) and test again ? This might help in resolving your issue.

Also on a side note, You should also update your `arcappliance` extension to the most recent version.

> az extension update -n arcappliance
