### ISSUE TITLE
`postgres up` seems outdated

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli-extensions#5571]
### Related command
`postgres up`

### Extension name (the extension in question)
db-up

### Description of issue (in as much detail as possible)
I found a few things that don't seem right about the `postgres up` command.

1. It's creating a Postgres Single Server by default, and has no param to select Flexible Server
2. the default postgres version is 10

Is this extension going to be updated?

-----

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
This extension is out of development, we CLI team only maintain this extension to ensure it can work but no more new features or changes.

See if @DaeunYim and @alanenriqueo from service team would like to contribute : )

**Comment by nachoalonsoportillo** [comment]
db-up has been removed https://github.com/Azure/azure-cli-extensions/pull/8231
