### ISSUE TITLE
az create generate-ssh-keys failed

### ISSUE THREAD

**Issue by deviceonbi** [Azure/azure-cli-extensions#5577]
## Describe the bug
az create generate-ssh-keys failed, only show Internal server error

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.5.115.`

**Errors:**
```
(InternalOperationError) Internal server error
Code: InternalOperationError
Message: Internal server error

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create -g {} -n {} --generate-ssh-keys`

## Environment Summary
```
Linux-5.4.0-1067-azure-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.42.0

Extensions:
aks-preview 0.5.115

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@deviceonbi The issue is surfacing from the service (REST API), CLI is displaying the same to you. Can you please open a support request for further troubleshooting? Please add debug trace of the issue  `az aks create -g yourrg -n youraksclusterz --generate-ssh-keys --debug` because it contains information like 'x-ms-correlation-request-id': 'redacted' and 'x-ms-request-id': 'redacted' to troubleshoot the issue faster.

**Comment by deviceonbi** [comment]
@RakeshMohanMSFT 
Thanks for answer my question, I try --debug and it show logs 

'x-ms-correlation-request-id': 'b2e3969f-b330-4993-8882-8242c5c06ffc'
'x-ms-request-id': '3e352c0e-97ce-449d-8d96-aca4fd9d9e2f'

If you need more information in logs, please let me know

cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1544'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'dac32c95-6ebb-11ed-b116-002248599360'
cli.azure.cli.core.sdk.policies:     'CommandName': 'aks create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --generate-ssh-keys --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.42.0 (DEB) azsdk-python-azure-mgmt-containerservice/20.4.0b Python/3.10.8 (Linux-5.4.0-1067-azure-x86_64-with-glibc2.27)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "southeastasia", "identity": {"type": "SystemAssigned"}, "properties": {"kubernetesVersion": "", "dnsPrefix": "wise-xxx-69f730", "agentPoolProfiles": [{"count": 3, "vmSize": "Standard_DS2_v2", "osDiskSizeGB": 0, "workloadRuntime": "OCIContainer", "osType": "Linux", "enableAutoScaling": false, "type": "VirtualMachineScaleSets", "mode": "System", "orchestratorVersion": "", "upgradeSettings": {}, "enableNodePublicIP": false, "enableCustomCATrust": false, "scaleSetPriority": "Regular", "scaleSetEvictionPolicy": "Delete", "spotMaxPrice": -1.0, "nodeTaints": [], "enableEncryptionAtHost": false, "enableUltraSSD": false, "enableFIPS": false, "networkProfile": {}, "name": "nodepool1"}], "linuxProfile": {"adminUsername": "azureuser", "ssh": {"publicKeys": [{"keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5aT/53j4lelQ1yd1XzQ52n2Ct7h/NXSAJvPmK4vi690c0bGGbrDWiY/Yr8HbO9I2dPXx431Fy18n+2qJUyQFn9HdvFLm/ZbiXbhJqJkIHoBYLLmhLgUAS27VPR84bXCTiLipsjrMbQsyG+hcqeg4qWllVXRE/Ua8EgFJAPP5wjTjIiJPhnuDxRMPOMCgfiq3xIFuGYtuNFYtfRYTVd0hPEv+rkYvVVtCryfAkU2F6TMyy/UzGMWaozAs2YVY4MAyxynuUBqww7sCbZaoBCcHkvB8dATwx2rzE7NecIl0ntP1JY5BhVqpKDzIE6YA8gs5KOzLlsjVtx+MbZ5HLWQV/"}]}}, "addonProfiles": {}, "enableRBAC": true, "enablePodSecurityPolicy": false, "networkProfile": {"networkPlugin": "kubenet", "podCidr": "10.244.0.0/16", "serviceCidr": "10.0.0.0/16", "dnsServiceIP": "10.0.0.10", "dockerBridgeCidr": "172.17.0.1/16", "outboundType": "loadBalancer", "loadBalancerSku": "standard"}, "disableLocalAccounts": false, "storageProfile": {}}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/69f73015-802e-4476-8b7c-66419f371bd7/resourceGroups/xxx/providers/Microsoft.ContainerService/managedClusters/wise-xxx-cluster?api-version=2022-09-02-preview HTTP/1.1" 500 77
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '77'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'b2e3969f-b330-4993-8882-8242c5c06ffc'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '3e352c0e-97ce-449d-8d96-aca4fd9d9e2f'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'nginx'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20221128T012744Z:b2e3969f-b330-4993-8882-8242c5c06ffc'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 28 Nov 2022 01:27:43 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "code": "InternalOperationError",
  "message": "Internal server error"
 }

**Comment by RakeshMohanMSFT** [comment]
@deviceonbi Thank you for the information, but I was suggesting that you open a support ticket with the trace information for further troubleshooting, since the issue is with the service itself (REST API) and not client (CLI)

**Comment by deviceonbi** [comment]
@RakeshMohanMSFT 

I found another solution to create ssh key, thanks for your reply
