### ISSUE TITLE
Feature Request: Az Snapshot Copy

### ISSUE THREAD

**Issue by bebattis** [Azure/azure-cli-extensions#559]
### Extension name (the extension in question)
image-copy-extension

### Description of issue (in as much detail as possible)
Currently, 'Specialized' osStates aren't possible with Managed Images. It's not documented, but you will receive an error upon image creation or VM deployment from image. The known work around for this is to replicate a snapshot rather than an image, build and attach the disk.

I'm wondering if we could add a --export-as-snapshot switch which would essentially general a snapshot of the VM in each image. The code is nearly identical (so I'd rather not create a second extension), and the only change would be `.\create_target.py` lines 126 - 134 which currently does an image create, rather than a snapshot create.

-----

I scraped the CLI commands from the python and created a simple bash script for the time being, but the check that the python extension does are really clean and I'd much rather leverage what's already there.

**Comment by tamirkamara** [comment]
@bebattis the extension actually creates a snapshot just prior to the final image (lines you mentioned).
I don't really understand what are those special images you are referring to. but at any case, if a managed image can't be created, what would be the **source** of the copy?

**Comment by bebattis** [comment]
@tamirkamara I've submitted a PR.
Hoping you can take a look and provide feedback.

https://github.com/Azure/azure-cli-extensions/pull/583

**Comment by tamirkamara** [comment]
@williexu the PR is merged so this issue can be closed.

**Comment by deancsmith** [comment]
Is there going to be a new release of the `image-copy` extension soon? There's been several PRs merged recently that we would love to use, but we can currently only use the official tagged releases. 

Apologies if there is a better place to ask this, and I couldn't find any details on the release cadence of these extensions published anywhere.

**Comment by tamirkamara** [comment]
Yes - #669 
Sorry about the delay.
