### ISSUE TITLE
Any examples of match condition?

### ISSUE THREAD

**Issue by gsimoes** [Azure/azure-cli-extensions#561]
Couldn't find examples of usage for the parameter --match-condition when creating a custom rule. Is there a place I can find a few examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a306fac9-da1e-c9f7-58ad-239326bc03f6
* Version Independent ID: 2a9f796e-0f6d-7dff-d328-9c56bcfed646
* Content: [az network waf-policy custom-rule](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/waf-policy/custom-rule?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/waf-policy/custom-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/waf-policy/custom-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
front-door

**Comment by aramesh-msft** [comment]
@wurp for any follow-up.

This the latest doc - https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/waf-policy/rule/match-condition?view=azure-cli-latest
And here are various example test cases - https://github.com/Azure/azure-cli-extensions/blob/master/src/front-door/azext_front_door/tests/latest/test_waf_scenarios.py

**Comment by SaurabhSharma-MSFT** [comment]
@gsimoes I believe you have got the required information in the previous reply and this issue can be closed. Please let us know.

**Comment by gsimoes** [comment]
Yeap, this can be closed. Thank you!
