### ISSUE TITLE
"az monitor app-insights query" does not return anything for --output table

### ISSUE THREAD

**Issue by radhakrishnan-chandarasikharan-kr** [Azure/azure-cli-extensions#5626]
## Describe the bug

**Command Name**
`az monitor app-insights query
Extension Name: application-insights. Version: 0.1.16.`

**Errors:**
NONE

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
```
 az monitor app-insights query --app {{INSERT-APP-ID}} --analytics-query "let x=datatable(a:string,b:string)['alpha','beta','zeta','jones'];x" --output table
```
## Expected Behavior
```
a            b 
-------- ---------
alpha      beta
zeta        jones
```
but there is no output!
=======================
Without the --output option:
``` 
az monitor app-insights query --app {{INSERT-APP-ID}} --analytics-query "let x=datatable(a:string,b:string)['alpha','beta','zeta','jones'];x" 
{
  "tables": [
    {
      "columns": [
        {
          "name": "a",
          "type": "string"
        },
        {
          "name": "b",
          "type": "string"
        }
      ],
      "name": "PrimaryResult",
      "rows": [
        [
          "alpha",
          "beta"
        ],
        [
          "zeta",
          "jones"
        ]
      ]
    }
  ]
}
```
## Environment Summary
```
macOS-12.6.1-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.40.0 *

Extensions:
alertsmanagement 0.2.2
cosmosdb-preview 0.8.1
application-insights 0.1.16

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by AllyW** [comment]
Hi @radhakrishnan-chandarasikharan-kr, `table` output format in cli cmd converts object into key-value pairs. But the response in your query returned key-list pair whose list cannot be formatted into table header and table value.

**Comment by radhakrishnan-chandarasikharan-kr** [comment]
I can see how these are layered i.e. the extension outputs in a key-list but the cli only translates a key-value to tabular form. But I, as a end user, have no way to change either the cli behavior or the extension behavior. I have no control over the output of the extension. Hence this request (or feature request).

**Comment by SaurabhSharma-MSFT** [comment]
@AllyW Can you please provide your suggestions.

**Comment by AllyW** [comment]
Hi @SaurabhSharma-MSFT @radhakrishnan-chandarasikharan-kr , for now, using `--output table` in `az monitor app-insights query` only converts `<key, value>` pair into table columns and values. You can run this cmd and pipeline its output into some local shell formatter scripts for now. If specified output format needs to be applied to this command's output, user can also request a support from cli to add it customerizedly in future's development plan.

**Comment by SaurabhSharma-MSFT** [comment]
@AllyW  Thanks.
@radhakrishnan-chandarasikharan-kr Please let us know if you have any questions.  Thanks.
