### ISSUE TITLE
Docs to publish an extension update are confusing

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-extensions#563]
The current docs to publish an extension update are a little confusing. The basic process is:
1. Make a PR with the code changes
2. Build and publish the WHL file
3. Update the index and make a PR with the change.

Step 1 isn't mentioned (I couldn't point someone to it)
Step 2 is here: https://github.com/Azure/azure-cli/blob/dev/doc/extensions/authoring.md#building but it's in the middle of a lot of information. 
Step 2 is continued in a separate document: https://github.com/Azure/azure-cli/blob/dev/doc/extensions/publishing.md
but that doesn't actually tell you how to update the index. 
So for step 3, you have to go: https://github.com/Azure/azure-cli-extensions#about-indexjson

It would be ideal if we offered the simple, concise path in one place. I was trying to walk someone through the documentation and got confused, so there's room for improvement here.

**Comment by yonzhan** [comment]
add to S172

**Comment by haroldrandom** [comment]
Closed as release procedure of extension has updated. https://github.com/Azure/azure-cli-extensions#about-extension-publishing

User don't have to build, upload WHL file and update index.json manually if code is hosted inside.
