### ISSUE TITLE
az connectedk8s connect: FAILURE.

### ISSUE THREAD

**Issue by vitorafgomes** [Azure/azure-cli-extensions#5643]
## Describe the bug

**Command Name**
`az connectedk8s connect
Extension Name: connectedk8s. Version: 1.3.6.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 8] Exec format error: '/home/vitorafgomes/.azure/helm/v3.6.3/linux-amd64/helm'
Traceback (most recent call last):
  File "/home/vitorafgomes/.local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/vitorafgomes/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/vitorafgomes/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/vitorafgomes/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/vitorafgomes/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/vitorafgomes/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/vitorafgomes/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 199, in create_connectedk8s
    release_namespace = get_release_namespace(kube_config, kube_context, helm_client_location)
  File "/home/vitorafgomes/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 853, in get_release_namespace
    response_helm_release = Popen(cmd_helm_release, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/vitorafgomes/.azure/helm/v3.6.3/linux-amd64/helm'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {} --location {} --correlation-id {}`

## Environment Summary
```
Linux-5.15.0-1021-raspi-aarch64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.6
Installer: PIP

azure-cli 2.43.0

Extensions:
connectedk8s 1.3.6

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context

![image](https://user-images.githubusercontent.com/5174765/207738640-69cdbb14-765b-473b-b0ed-b8ec98c53cca.png)

![image](https://user-images.githubusercontent.com/5174765/207738448-4e6922f1-f19d-4332-86d4-35d5025f6d5f.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@vitorafgomes Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@vitorafgomes Could you please follow the below plan and let us know if that helps ?

1. Please use the most recent version of [Helm](https://helm.sh/docs/intro/install/) and check if that helps.
2. Could you please confirm if you are logged into AzCLI using Service Principal ?
3. Could you please try setting the HELM_CLIENT_PATH (PATH environment variable) for the HELM (download & Install path for HELM ? 
4. Could you try running the below command and check if that helps ?

> **az connectedk8s connect -g resourceGroupName -n connectedClusterName --kube-config /path/to/kubeconfig --kube-context kubeContextName**

Reference articles:
https://github.com/Azure/azure-cli-extensions/blob/816c8d2175d2310e044464853760006b8c55428b/src/connectedk8s/azext_connectedk8s/custom.py#L853
https://learn.microsoft.com/en-us/cli/azure/connectedk8s?view=azure-cli-latest#az-connectedk8s-connect
https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/troubleshooting
https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/quickstart-connect-cluster?tabs=azure-cli

**Comment by navba-MSFT** [comment]
@vitorafgomes I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@vitorafgomes The action plan is currently pending on you to provide an update on the above questions. Once you are ready to resume troubleshooting on this, please feel free to reopen this thread. We would be happy to help.

**Comment by vitorafgomes** [comment]
[navba-MSFT](https://github.com/navba-MSFT)

Sorry for the delay, could you tell me why I have this error below?

![image](https://user-images.githubusercontent.com/5174765/209856830-25befb03-6c43-4d6b-b328-461a2c453dd7.png)
