### ISSUE TITLE
image-copy-extension: No '--source-location' parameter  

### ISSUE THREAD

**Issue by poochwashere** [Azure/azure-cli-extensions#570]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
image-copy-extension

### Description of issue (in as much detail as possible)

There does not appear to be an option to specify the location of the source disk that you want to snap within the source resource group. In my case is that the VM is in a different location than the RG. 

-----

**Comment by bebattis** [comment]
As a workaround you might try setting the defaults of your Az Cli context to the location which the vm/disk lives in. I ran into this previously under here: https://github.com/Azure/azure-cli-extensions/issues/555

Worth a shot until this is explicitly called out as a parameter, or logic modified to identify the vm/disk location.

**Comment by yonzhan** [comment]
image copy

**Comment by navba-MSFT** [comment]
@poochwashere Apologies for the delayed response. This github issue has been open for quite sometime. Could you please let us know if you still need assistance on this issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@poochwashere This is a follow-up to check if you had a chance to look at my above comment. This issue is open for quite sometime. Please let us know if you need any further assistance on this.

**Comment by navba-MSFT** [comment]
@poochwashere We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
