### ISSUE TITLE
k8s-extension 1.3.8 no longer supports --configuration-protected-settings-file

### ISSUE THREAD

**Issue by darrendejaeger** [Azure/azure-cli-extensions#5810]
### Related command
az k8s-extension create 

### Extension name (the extension in question)
k8s-extension

### Description of issue (in as much detail as possible)
It appears that a change was introduced in 1.3.8 of k8s-extension wherein "--configuration-protected-settings-file" is no longer supported for passing protected config via a file. Rather, only "--config-protected-file" and "--protected-settings-file" work now. I browsed for release notes but didn't see a mention of this. Was the change intentional?

Noticed that: "--configuration-settings-file" is in the same boat.

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by mdrakiburrahman** [comment]
We hit the same issue as well - this is the PR:
https://github.com/Azure/azure-cli-extensions/pull/5798/files

![image](https://user-images.githubusercontent.com/46581776/215350586-38d64cb3-4f25-4b26-839a-983e1a5779e5.png)

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

Adding @deeksha345 who had filed the above PR to confirm if this change was intentional ? or if we are running into some regression?

**Comment by steveballs** [comment]
It appears --configuration-settings-file has been replaced with --config-settings-file.  
Please do not just reverse this change as some people will have started using the new name.  
You will have to support both versions going forward to fix this regression and avoid further regressions.

**Comment by ponatara** [comment]
Hi all, Update on this:  We are working on a change to mark the unsupported options as "deprecated" in Azure CLI ( which will warn users that the option is deprecated and suggest the new option to use instead). Users will still be able to use the unsupported options in this version of CLI release. This change is pending review and merge. Will update this thread once the change is merged.

**Comment by NarayanThiru** [comment]
We have fixed this - essentially brought back the removed parameters and added message that they will be deprecated in the future.  This fix is in version 1.3.9.

**Comment by navba-MSFT** [comment]
@NarayanThiru  @ponatara Thanks for your quick assistance.

@darrendejaeger Could you please update your extension to 1.3.9 version by running the below command and then let us know if you face the same issue ? Awaiting your reply.

> **az extension update -n k8s-extension**

**Comment by darrendejaeger** [comment]
@navba-MSFT: Confirmed working. Thank you ALL for the fast turnaround!
