### ISSUE TITLE
az k8s-extension create in 1.3.8 removes support for --configuration-protected-settings - breaks docs and automation

### ISSUE THREAD

**Issue by apwestgarth** [Azure/azure-cli-extensions#5817]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command

az k8s-extension create \
    --resource-group $GROUP_NAME \
    --name $EXTENSION_NAME \
    --cluster-type connectedClusters \
    --cluster-name $CLUSTER_NAME \
    --extension-type 'Microsoft.App.Environment' \
    --release-train stable \
    --auto-upgrade-minor-version true \
    --scope cluster \
    --release-namespace $NAMESPACE \
    --configuration-settings "Microsoft.CustomLocation.ServiceAccount=default" \
    --configuration-settings "appsNamespace=${NAMESPACE}" \
    --configuration-settings "CLUSTER_NAME=${CONNECTED_ENVIRONMENT_NAME}" \
    --configuration-settings "envoy.annotations.service.beta.kubernetes.io/azure-load-balancer-resource-group=${AKS_CLUSTER_GROUP_NAME}" \
    --configuration-settings "logProcessor.appLogs.destination=log-analytics" \
    --**configuration-protected-settings** "logProcessor.appLogs.logAnalyticsConfig.customerId=${LOG_ANALYTICS_WORKSPACE_ID_ENC}" \
    --**configuration-protected-settings** "logProcessor.appLogs.logAnalyticsConfig.sharedKey=${lOG_ANALYTICS_KEY_ENC}"

### Extension name (the extension in question)

k8s-extension (Arc enabled Kubernetes Extensions)

### Description of issue (in as much detail as possible)

As of k8s-extension CLI Extension v1.3.8 it appears the ability to pass protected configuration settings using --configuration-protected-settings has been dropped without warning.  All of the Application services (Web, Function, Logic Apps), Container Apps on Arc extension documentation uses this property.  This command is successful in 1.3.7 and there is no notification of removal of support in a future version.  This also breaks automation.

This is a breaking change and is causing issues.

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by ponatara** [comment]
Hi, ack this issue. This thread will contain  updates for this issue -  https://github.com/Azure/azure-cli-extensions/issues/5810

**Comment by navba-MSFT** [comment]
@apwestgarth Thanks for reaching out to us and reporting this issue. Could you please update your `k8s-extension `extension to `1.3.9` version by running the below command and then let us know if you face the same issue ? Awaiting your reply.

> **az extension update -n k8s-extension**

**Comment by apwestgarth** [comment]
Validated, works with 1.3.9.  May I ask why the term is being dropped? 

Also. it would appear inconsistent for readability to drop

config-settings in favour of configuration-settings 

and then drop

configuration-protected-settings in favour of config-protected-settings

If you're going to drop support for parameters I feel it should be done in a consistent manner

**Comment by tomkerkhove** [comment]
Agreed

**Comment by navba-MSFT** [comment]
> Validated, works with 1.3.9. **May I ask why the term is being dropped?**
> Also. it would appear inconsistent for readability to drop `config-settings` in favour of `configuration-settings`
> and then drop` configuration-protected-settings` in favour of `config-protected-settings`
> If you're going to drop support for parameters I feel it should be done in a consistent manner

Thanks @apwestgarth for getting back. I am glad that upgrading the extension works and you are unblocked. 

@ponatara @NarayanThiru Could you please help us in answering the above question ? Any help on this is much appreciated.

**Comment by NarayanThiru** [comment]
Sometime back we introduced multiple aliases for 4 parameters configuration-settings, configuration-settings-file, configuration-protected-settings and configuration-protected-settings-file.  With these long parameter names and multiple aliases, the help output ended up being single character wide.  We missed validating it fully and didn't realize it till much later. 
 We tried to keep them as is and manipulate the width of the output, but were not able to as it is controlled by the az CLI framework.  The only solution was to remove/replace the aliases, without which the help text is totally unusable.  This is why we are removing one of the aliases for each parameter and shortening one of the aliases.  Pl. note we are not removing any of the parameters, only their aliases.  We will follow the deprecation process to remove/rename the aliases in upcoming release of our extension.

**Comment by apwestgarth** [comment]
@NarayanThiru no problem with the deprecation of parameters, my feedback was more in terms of being consistent in the deprecation of phrasing.  IMO it would make sense to deprecate both the phrasing configuration-settings and configuration-protected-settings or config-settings and config-protected-settings rather than a mixture of the two combinations.
