### ISSUE TITLE
Azure CLI unable to create portal dashboards from templates

### ISSUE THREAD

**Issue by willdave865** [Azure/azure-cli-extensions#5824]
`az feedback` has auto-generated most of the information requested below

**Describe the bug**
When I run the az portal dashboard create command to create an Azure Portal Dashboard, it reports the following:

**Errors:**
```
<_io.TextIOWrapper name= ~\\test1.json' mode='r' encoding='cp1252'> does not contain the property 'location'

```
**Command Name**
`az portal dashboard import
Extension Name: portal. Version: 0.1.3.`

## To Reproduce:
- Use test1.json validated uploaded test file
- Run in same dir with command `az portal dashboard import --input-path test1.json  --name TestDash1  --resource-group xx`

Validated `json` code sample
```
{
    "properties": {
      "lenses": 
        {
          "order": 0,
          "parts": 
            {
              "position": {
                "x": 0,
                "y": 0,
                "rowSpan": 1,
                "colSpan": 2
              },
              "metadata": {
                "inputs": [
                  {},
                  {}
                ],
                "type": "Extension/AppInsightsExtension/PartType/AspNetOverviewPinnedPart"
              }
            }
          
        },
      
      "metadata": {
        "model": {
          "timeRange": {
            "value": {
              "relative": {
                "duration": 24,
                "timeUnit": 1
              }
            }
          }
        },
        "type": "MsPortalFx.Composition.Configuration.ValueTypes.TimeRange"
    },
    "name": "TestDashboard",
    "type": "Microsoft.Portal/dashboards",
    "location": "westus",
    "tags": {
    "hidden-title": "My Test Dashboard"
    },
    "apiVersion": "2015-08-01-preview"
    }
}
```

## Expected Behavior
- The template file `test1.json` contains the line `"location": "westus"` So it should work.
- Compare with `sample.json` https://github.com/Azure/azure-cli/issues/16356 which has similar file structure and works correctly

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0 *

Extensions:
portal 0.1.3

```
## Additional Context
It appears that command `az portal dashboard import` does not parse the location property with exported Azure Portal Dashboard template files. It will only parse this property with simple template files formatted like `sample.json` (see above) When the formatting becomes more complicated, as in when Application Insights has been used in conjunction with the Portal Dashboard, the command misses the reference line of the location property.

For additional information. Please see https://stackoverflow.com/questions/75304223/azure-cli-extensions-exported-dashboard-template-json-does-not-contain-the-pro

**Comment by yonzhan** [comment]
route to CXP team

**Comment by jsntcy** [comment]
@willdave865, from the example json you provided, it seems your json is not valid (you miss one layer, see highlighted part in snapshot below).
![image](https://user-images.githubusercontent.com/16348853/215974834-ac080b45-7acc-4a3d-b1a2-31259160e2e7.png)


You can see sample json in https://github.com/Azure/azure-cli-extensions/blob/main/src/portal/azext_portal/tests/latest/dashboard.json#L4

**Comment by willdave865** [comment]
@jsntcy the `json` line of code you have highlighted appears in the working/correct sample `sample.json` as well. So logically cannot be the reason why present `location` property cannot be found. I checked `json` files before creating report https://jsonlint.com/ & https://jsonformatter.org/

Please consider the json file `test1.json` I have provided as minimum reproducible examples. The error quoted in this report also occurs in a complete exported dashboard ARM. Please see my gist https://gist.github.com/willdave865/d0e00c974be4c203f6930d02919fffc4

**Comment by jsntcy** [comment]
Your json format should follow the json schema in https://github.com/Azure/azure-cli-extensions/blob/main/src/portal/azext_portal/tests/latest/dashboard.json#L4,

From https://gist.github.com/willdave865/d0e00c974be4c203f6930d02919fffc4 you provided, I still found it's not a valid json format (missing one layer) for `az portal dashboard import`

![image](https://user-images.githubusercontent.com/16348853/216221950-a7dc355d-a717-431a-8e36-b531194f61ad.png)

**Comment by willdave865** [comment]
@jsntcy I have just pasted my gist `JSON` code into https://portal.azure.com/#create/Microsoft.Template As per instructions in https://learn.microsoft.com/en-us/azure/azure-portal/azure-portal-dashboards-create-programmatically It was declared valid `JSON` and deployed successfully. I do not understand why you are describing it as "not valid json".

**Comment by achede22** [comment]
The .json file came from an exported dashboard, and as is.. it's not valid while uploading from terraform https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/portal_dashboard#dashboard_properties or azure cli

to make it work, you should modify the exported JSON, deleting the "properties" stage, so it can be uploaded from terraform and AzureCli

it's a bug, because if I export a .json template, I expect to be a working one, without any trick or modification. so I can upload it and recover my Azure Dashboard

**Comment by achede22** [comment]
handmade solution -> https://github.com/Azure/azure-cli/issues/16356#issuecomment-752348488

it's still a bug

**Comment by jsntcy** [comment]
> The .json file came from an exported dashboard, and as is.. it's not valid while uploading from terraform https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/portal_dashboard#dashboard_properties or azure cli
> 
> to make it work, you should modify the exported JSON, deleting the "properties" stage, so it can be uploaded from terraform and AzureCli
> 
> it's a bug, because if I export a .json template, I expect to be a working one, without any trick or modification. so I can upload it and recover my Azure Dashboard

Where is the json exported from?

**Comment by achede22** [comment]
It's just an exported Azure Dashboard.

(A Similar to Grafana)

https://learn.microsoft.com/en-us/azure/azure-portal/azure-portal-dashboards-create-programmatically#share-the-dashboard

**Comment by jsntcy** [comment]
@achede22, which command do you use with the exported Azure Dashboard to meet the issue? `az portal dashboard create` or `az portal dashboard import`?

**Comment by achede22** [comment]
I'm using a terraform resource called azure_portal_dashboards, take a loos at the templatefile (.json)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/portal_dashboard

**Comment by jsntcy** [comment]
@achede22, I'm confused with what you said.

- Did you use Terraform or Azure CLI?
  - If you used Terraform, please report issue to Terraform.
  - If you used Azure CLI, please share the sample json which you met issue with.

**Comment by achede22** [comment]
You are right, I opened a ticket for the terraform documentation, Thanks

https://github.com/hashicorp/terraform-provider-azurerm/issues/21427

**Comment by jsntcy** [comment]
Close this issue as it's related to TF.

**Comment by willdave865** [comment]
I opened this issue because there was/is a legitimate problem with Azure Portal Dashboard creation using Azure Command Line Interface. As far as I am concerned this issue has/had nothing to do with Terraform. I believe there is no sincere desire to fix this issue. This is shown by the last comment.

**Comment by achede22** [comment]
Yes, please do it, create another issue, this is a bug, you can solve it deleting the "properties" stage from the exported JSON file.
