### ISSUE TITLE
Feature Request: Provide ARM VM support for vm-repair extension

### ISSUE THREAD

**Issue by malachma** [Azure/azure-cli-extensions#5826]
### Extension name (the extension in question)
vm-repair

### Description of issue (in as much detail as possible)
In order to use the 'vm repair' extension to work with ARM based VMs the extension needs to create the right recovery VM.
At the moment ARM based VMS aren't supported. At creation time the following error is raised

**ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Cannot create a VM of size 'Standard_D2pls_v5' because this VM size only supports a CPU Architecture of 'Arm64', but an image or disk with CPU Architecture 'x64' was given. Please check that the CPU Architecture of the image or disk is compatible with that of the VM size.\"\r\n  }\r\n}"}]}}**
-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding service team to look into this ask.

 @Drewm3, @avirishuv, @Vaibhav-Agar, @amjads1 Could you please look into this once you get a chance ? Thanks in advance.

**Comment by Drewm3** [comment]
Moving this to myself to find the right current owner of the VM Repair tool.

**Comment by Drewm3** [comment]
Updating to the tool owner

**Comment by malachma** [comment]
What is the progress on this feature requests? ARM64 support is a feature which also benefits our self-service capabilities

**Comment by TravisCragg-MSFT** [comment]
@malachma We are currently assessing this as a feature request and will post an update when we can.

**Comment by Sandido** [comment]
This issue was previously resolved and should be available in recent versions of Azure CLI.

**Comment by haagha** [comment]
Hi @malachma this is a known issue in underlying CLI, we will create a bug to resolve this. https://github.com/Azure/azure-cli/issues/27975

**Comment by Sandido** [comment]
@malachma , you can ping Haider for more info about testing the current fix for this issue.

What is your repro? I tried to create a repair vm from an ARM64 vm and setting the repair vm explicitly to an arm64 image, but the repair vm was made successfully.
C:\Users\XXXXX\source\repos\XXXXX> az vm repair create -g $rgname -n $vmname --repair-username XXXXX --repair-password XXXXX --yes --verbose --distro "Canonical:0001-com-ubuntu-server-jammy:22_04-lts-arm64:latest"
Fetching architecture type of the source VM...
Checking if source VM is gen2
Generation 2 VM detected
A custom URN was provided , will be used as distro for the recovery VM
ARM64 VM detected
A custom URN was provided , will be used as distro for the recovery VM
Checking if source VM size is available...
Source VM size 'Standard_D2pls_v5' is available. Using it to create repair VM.

Checking for existing resource groups with identical name within subscription...
Pre-existing repair resource group with the same name is 'False'
Creating resource group for repair VM and its resources...
Source VM uses managed disks. Creating repair VM with managed disks.

Copying OS disk of source VM...
Creating repair VM with command: az vm create -g repair-vm64std-XXXXX -n repair-vm64std_ --tag repair_source=XXXXX/vm64std --image Canonical:0001-com-ubuntu-server-jammy:22_04-lts-arm64:latest --admin-username XXXXX --admin-password XXXXX --public-ip-address False --custom-data c:\users\XXXXX\source\repos\XXXXX\azure-cli-extensions\src\vm-repair\azext_vm_repair\scripts\linux-build_setup-cloud-init.txt --size Standard_D2pls_v5
copy_disk_id: /subscriptions/XXXXX/resourceGroups/XXXXX/providers/Microsoft.Compute/disks/vm64std-DiskCopy-XXXXX
repair_password: XXXXX
repair_username: XXXXX
fix_uuid: True
Validating VM template before continuing...
Creating repair VM...
Attaching copied disk to repair VM as data disk...

Your repair VM 'repair-vm64std_' has been created in the resource group 'repair-vm64std-XXXXX' with disk 'vm64std-DiskCopy-XXXXX' attached as data disk. Please use this VM to troubleshoot and repair. Once the repairs are complete use the command 'az vm repair restore -n vm64std -g XXXXX --verbose' to restore disk to the source VM. Note that the copied disk is created within the original resource group 'XXXXX'.

**Comment by malachma** [comment]
> Hi @malachma this is a known issue in underlying CLI, we will create a bug to resolve this. [Azure/azure-cli#27975](https://github.com/Azure/azure-cli/issues/27975)

Thanks Haider :-)
