### ISSUE TITLE
Extension type microsoft.azstackhci.operator is not registered in region australiaeast.

### ISSUE THREAD

**Issue by paullisto-insight** [Azure/azure-cli-extensions#5836]
### Related command
az k8s-extension create --cluster-type appliances --cluster-name $resource_name --resource-group $resource_group --name hci-vmoperator --extension-type Microsoft.AZStackHCI.Operator --scope cluster --release-namespace helm-operator2 --configuration-settings Microsoft.CustomLocation.ServiceAccount=hci-vmoperator --config-protected-file $csv_path\ResourceBridge\hci-config.json --configuration-settings HCIClusterID=$hciClusterId --auto-upgrade true

(ExtensionTypeRegistrationGetFailed) Extension type microsoft.azstackhci.operator is not registered in region australiaeast. Extension is available in eastus2euap,eastus,westeurope,southeastasia. Please try to install in these regions.

Code: ExtensionTypeRegistrationGetFailed

Message: Extension type microsoft.azstackhci.operator is not registered in region australiaeast. Extension is available in eastus2euap,eastus,westeurope,southeastasia. Please try to install in these regions.

### Extension name (the extension in question)
az k8s-extension v1.3.9

### Description of issue (in as much detail as possible)
Australia East is a supported region for Azure Stack HCI in all preview documentation, however cannot register this Kubernetes extension
-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@paullisto-insight Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by paullisto-insight** [comment]
@navba-MSFT, yes I can confirm that we used Register-AzureStackHCI or Windows Admin Center to register to Australia East.

**Comment by navba-MSFT** [comment]
@paullisto-insight Thanks for your reply. Could you please let me know if you can view the status of the cluster and Arc resources from Azure portal ?https://learn.microsoft.com/en-us/azure-stack/hci/deploy/register-with-azure#view-the-cluster-and-arc-resources-in-azure-portal

**Comment by paullisto-insight** [comment]
@navba-MSFT. Yes, I can and all show as connected.

**Comment by navba-MSFT** [comment]
@paullisto-insight From the error message it is pretty clear that, this extensionType is not actually registered in `australiaeast `region.  We only support [East US and West Europe at this point in time](https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-wac#set-up-arc-resource-bridge-and-create-custom-location).

**Comment by paullisto-insight** [comment]
I understand the error message is clear, however, my customer has made a purchasing decision based upon the advice in your documentation that Azure Stack HCI is supported in Australia East. There is no mention in this article (or the one posted in your comment): https://learn.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-vm-management-prerequisites, that the Arc VM management is restricted to the regions noted. Can you please advise of the appropriate documentation detailing the region restriction for me to pass on to the client AND when it will be available in Australia East?

**Comment by navba-MSFT** [comment]
@paullisto-insight Azure stack HCI exposes multiple Azure resources that may not all be available in the same regions. 
[This ](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/register-with-azure#region-availability)docs I mentioned applies to the Azure Stack HCI cluster resource, but doesn’t apply to the ARC enabled VMs resource. 

We haven’t decided on when Australia East will be available for ARC enabled VMs.

I am checking with the Product Team for Azure Stack HCI cluster details for Australia East region. Please give me sometime. I will keep you posted.

**Comment by paullisto-insight** [comment]
Thank you @navba-MSFT, I'll await your response.

**Comment by navba-MSFT** [comment]
@paullisto-insight A quick update I received from the Product owners. Arc VM management is a Preview functionality. Hence, its regional availability may not be at par with Azure Stack HCI service. That said, we will make sure that at GA, we have this parity. GA of Arc VM management is currently targeted towards the end of this calendar year. Please let me know if you have any follow-up questions on this.
