### ISSUE TITLE
az webapp ssh inside ASE resolves wrong DNS namespace for scm

### ISSUE THREAD

**Issue by sbyrnes-weblogix** [Azure/azure-cli-extensions#584]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

azure-cli (2.0.54)
[
  {
    "extensionType": "whl",
    "name": "webapp",
    "version": "0.2.16"
  }
]

### Description of issue (in as much detail as possible)
-----

Using the "az webapp ssh" or "az webapp remote-connection create" with a app that is deployed inside an ASE fails to connect to the correct dns namespace but tries to connect to "{myappname}.scm.azurewebsites.net" rather than {myappname}.scm.{customsslcertname} that the ASE uses.

We know DNS works as expected and have NSG locked down the VNET but are attempting this for a location where access is provided and DNS resolves correctly and internal deployed apps running https services pages can be reached.

**Comment by panchagnula** [comment]
this is fixed & the command is moved to core as well so please use that
