### ISSUE TITLE
This page is incorrect

### ISSUE THREAD

**Issue by KevinBrooke** [Azure/azure-cli-extensions#585]
The examples are different from the definitions.
Also, --group-name is now --name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f8fe72-48f6-2e30-0741-d83bafc5d438
* Version Independent ID: 32ed6908-2c71-3c17-683b-d07eb08d4590
* Content: [az account management-group](https://docs.microsoft.com/en-us/cli/azure/ext/managementgroups/account/management-group?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/managementgroups/account/management-group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/managementgroups/account/management-group.yml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bebattis** [comment]
Yeah, I see this too. Various commands are mixing up the az account management-group with the az cli extension for managementgroups.

**Comment by kylecweeks** [comment]
Please remove this page, or reference to the correct cli https://docs.microsoft.com/en-us/cli/azure/account/management-group?view=azure-cli-latest  -- this caused much confusion.

**Comment by jiasli** [comment]
Thank all for the findings. I will remove this extension from this repo.
