### ISSUE TITLE
az network bastion tunnel target_ip_address

### ISSUE THREAD

**Issue by lgranie** [Azure/azure-cli-extensions#5854]
## Describe the bug

**Command Name**
`az network bastion tunnel
Extension Name: bastion. Version: 0.2.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
_validate_and_generate_resourceid() missing 1 required positional argument: 'target_ip_address'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "${user.home}/.azure\cliextensions\bastion\azext_bastion\custom.py", line 153, in ssh_bastion_host
    _validate_and_generate_resourceid(cmd, bastion, target_resource_id, target_ip_address)
TypeError: _validate_and_generate_resourceid() missing 1 required positional argument: 'target_ip_address'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion tunnel --name {} --resource-group {} --target-resource-id {} --port {} --resource-port {}`

## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
bastion 0.2.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by bollicino** [comment]
Same issue, unable to access to VMs
## Environment Summary
```
macOS-13.1-x86_64-i386-64bit, Darwin 22.2.0
Python 3.10.9
Installer: HOMEBREW

azure-cli 2.45.0

Extensions:
front-door 1.0.17
azure-firewall 0.14.4
bastion 0.2.0
aks-preview 0.5.128
logic 0.1.6
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by bollicino** [comment]
@lgranie I've switched temporarily to the Azure Cloud Shell and it works (I know is not the same as using the local terminal)

**Comment by perttulaurila** [comment]
Workaround by downgrading to Azure CLI 2.40 resolved the issue. 
I get a warning "The 'bastion' extension version 0.2.0 is not compatible with your current CLI core version 2.40.0." but at least I can connect again.

**Comment by navba-MSFT** [comment]
@lgranie @bollicino @perttulaurila  The fix is being worked upon and should be made available in the 0.2.1 version of bastion extension. I will keep you posted.

**Comment by navba-MSFT** [comment]
@lgranie @bollicino @perttulaurila As mentioned in the above comment, Could you please try _updating_ your `bastion `extension (to 0.2.1) ? That should resolve this issue. Please run the below command to update your extension. 

> **az extension update -n bastion**

**Comment by bollicino** [comment]
> @lgranie @bollicino @perttulaurila As mentioned in the above comment, Could you please try _updating_ your `bastion `extension (to **0.2.1**) ? That should resolve this issue. Please run the below command to update your extension.
> 
> > **az extension update -n bastion**

ciao @navba-MSFT 
yes it works (sorry for late reply, I was on vacation ⛷️).
thank you!

**Comment by lgranie** [comment]
everything is ok
thk
