### ISSUE TITLE
--group-name is now --name

### ISSUE THREAD

**Issue by KevinBrooke** [Azure/azure-cli-extensions#586]
Please update as --group-name is no longer a valid parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dfd8921-1de0-c232-cdad-0e3a8a86113e
* Version Independent ID: 223008e8-07a9-d031-7591-39db960b47db
* Content: [az account management-group subscription](https://docs.microsoft.com/en-us/cli/azure/ext/managementgroups/account/management-group/subscription?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/managementgroups/account/management-group/subscription.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/managementgroups/account/management-group/subscription.yml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
management-group

**Comment by navba-MSFT** [comment]
@KevinBrooke Apologies for the late reply. This issue has been fixed now. Could you please refer to the updated documentation [here](https://docs.microsoft.com/en-us/cli/azure/account/management-group?view=azure-cli-latest)? If you need any further assistance on this, please get back to us. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@KevinBrooke Please let me know if you had a chance to look at my above comment. Awaiting your reply.

**Comment by KevinBrooke** [comment]
Yep, all good. Thanks!

**Comment by navba-MSFT** [comment]
@KevinBrooke Thanks for your reply. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
