### ISSUE TITLE
az connectedk8s connect, does not connect to ARO Azure (azure.cli.core.util.handle_exception is called with an exception:)

### ISSUE THREAD

**Issue by seilorjunior** [Azure/azure-cli-extensions#5883]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command
az connectedk8s connect --name mycluster --resource-group myrg --location eastus  --correlation-id c18ab9d0-685e-48e7-ab55-12588447b0ed --debug

### Extension name (the extension in question)
az connectedk8s 

### Description of issue (in as much detail as possible)
The debug info
cli.azext_connectedk8s.custom: The pre-check result logs logs have been saved at this path:/root/.azure/pre_onboarding_check_logs/mycluster-Wed-Feb-15-16.59.28-2023 .
These logs can be attached while filing a support ticket for further assistance.

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 198, in create_connectedk8s
    raise ValidationError("Execution of pre-onboarding checks failed and hence not proceeding with cluster onboarding. Please meet the prerequisites - 'https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/quickstart-connect-cluster?tabs=azure-cli%2Cazure-cloud#prerequisites' and try onboarding again.")
azure.cli.core.azclierror.ValidationError: Execution of pre-onboarding checks failed and hence not proceeding with cluster onboarding. Please meet the prerequisites - 'https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/quickstart-connect-cluster?tabs=azure-cli%2Cazure-cloud#prerequisites' and try onboarding again.

cli.azure.cli.core.azclierror: Execution of pre-onboarding checks failed and hence not proceeding with cluster onboarding. Please meet the prerequisites - 'https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/quickstart-connect-cluster?tabs=azure-cli%2Cazure-cloud#prerequisites' and try onboarding again.
az_command_data_logger: Execution of pre-onboarding checks failed and hence not proceeding with cluster onboarding. Please meet the prerequisites - 'https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/quickstart-connect-cluster?tabs=azure-cli%2Cazure-cloud#prerequisites' and try onboarding again.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f164bb8d990>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 74.470 seconds (init: 0.316, invoke: 74.154)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 10861 in cache
telemetry.check: Negative: The /root/.azure/telemetry.txt was modified at 2023-02-15 16:55:20.963878, which in less than 600.000000 s
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7ff541b05990>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 127.900 seconds (init: 0.324, invoke: 127.575)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3481 in cache
telemetry.check: Negative: The /root/.azure/telemetry.txt was modified at 2023-02-15 16:55:20.963878, which in less than 600.000000 s
/ #

**Comment by seilorjunior** [comment]
@navba-MSFT could you help me with that?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@seilorjunior Thanks for reaching out to us and reporting this issue. Please follow the below action plan in order:

**Plan 1:**
Please update your `connectedk8s `extension by running the below command:
> **az extension update -n connectedk8s**

**Plan 2:**
Please[ update your AzCLI](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) to the most recent version.

**Plan 3:**
Please follow the prerequisites article: 'https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/quickstart-connect-cluster?tabs=azure-cli%2Cazure-cloud#prerequisites' and then try again and check if you still encounter the same issue

Awaiting your reply.

**Comment by seilorjunior** [comment]
@navba-MSFT we have done that, do you know if there is anything special to run in a centos?

**Comment by navba-MSFT** [comment]
@seilorjunior Could you confirm if ALL the plans mentioned above have been followed ?

**Comment by navba-MSFT** [comment]
@seilorjunior Thanks for your reply. Could you please run the cmd `az connectedk8s troubleshoot -n clusterName -g resourceGroupName` which performs a diagnostic checks on an Arc enabled Kubernetes cluster ? and let me know the update.

In the meantime, I am doing some more research on your above error.  I will keep you posted.

**Comment by navba-MSFT** [comment]
@seilorjunior I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@seilorjunior I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@seilorjunior Could you please share an update on the above suggested action plans ? Awaiting your reply.

**Comment by seilorjunior** [comment]
@navba-MSFT hello seems an issue regarding cache, i dont have the logs of the machine anymore.
We ran the commands from a container az-cli and i installed all the extensions and it worked. please take a look of the cache.

**Comment by navba-MSFT** [comment]
@seilorjunior I tried to do some research and tried to reproduce this issue at my end. But I was able to get this to work without any errors. If you encounter this issue again at your end, please provide the[ above requested data](https://github.com/Azure/azure-cli-extensions/issues/5883#issuecomment-1434159012) and feel free to reopen this issue. We would be happy to help.

**Comment by seilorjunior** [comment]
@navba-MSFT i guess that was something related to cache. is good to see how this extension handle cache. do you know on which part of the code i can find this extension?

**Comment by navba-MSFT** [comment]
@seilorjunior Here is the code for this extension: https://github.com/Azure/azure-cli-extensions/blob/eedea68dbf9de743607021979233714175524bd0/src/connectedk8s/azext_connectedk8s/custom.py#L68
