### ISSUE TITLE
containerapp – error running az containerapp up with no Dockerfile

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli-extensions#5893]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command

az containerapp up

### Extension name (the extension in question)

containerapp 0.3.22

### Description of issue (in as much detail as possible)

```
git clone https://github.com/Azure-Samples/msdocs-python-flask-webapp-quickstart
cd msdocs-python-flask-webapp-quickstart
az containerapp up -g myrg -n myapp --ingress external --source .
```

Prints error:

```
Running ACR build...
Failed to automatically generate a docker container from your source.
See the ACR logs above for more error information.
Please check the supported langauges for autogenerating docker containers 
```

-----

**Comment by yonzhan** [comment]
route to CXP team
