### ISSUE TITLE
An exception has occured while trying to execute cluster diagnostic checks container on the cluster. Exception: [Errno 8] Exec format error:

### ISSUE THREAD

**Issue by vitorafgomes** [Azure/azure-cli-extensions#5906]
This k3s cluster is running on an "AMR64" architecture in an raspberry PI 4 , but there is a helm folder inside the azure folder that is on AMD64.

![image](https://user-images.githubusercontent.com/5174765/220479642-67fd1089-661f-46a6-aebe-95208c19bdad.png)

![image](https://user-images.githubusercontent.com/5174765/220478824-f692f19d-a94a-4f50-bb70-eaec81abe986.png)

![image](https://user-images.githubusercontent.com/5174765/220478961-50f48f08-df84-4a97-a583-84bfc1ff4740.png)

![image](https://user-images.githubusercontent.com/5174765/220479513-b260606b-0122-492f-84cb-6d3b89f6e5b0.png)

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
`connectedk8s` does not support arm64. See https://github.com/Azure/azure-cli-extensions/issues/2701

It hardcodes amd64
https://github.com/Azure/azure-cli-extensions/blob/87aebb4f369015fa83003885d4e193977c1331a0/src/connectedk8s/azext_connectedk8s/custom.py#L455-L458

**Comment by vitorafgomes** [comment]
Thank you very much @bebound 

I'll see if I create just one ControlP on an AMD machine I can solve this.

**Comment by SaurabhSharma-MSFT** [comment]
@vitorafgomes Please let us know if you need any further help on this issue.

**Comment by phoenixking25** [comment]
Are we planning to update this, because its still hardcoded.

**Comment by phoenixking25** [comment]
<img width="1728" alt="Screenshot 2024-05-05 at 3 48 22 PM" src="https://github.com/Azure/azure-cli-extensions/assets/22527880/bd117e9e-7b85-45db-b8a1-c215d8b3e046">

**Comment by phoenixking25** [comment]
@SaurabhSharma-MSFT Can you please help me here?
