### ISSUE TITLE
min_pro is used in the example of help in express-route-cross-connection

### ISSUE THREAD

**Issue by limingu** [Azure/azure-cli-extensions#591]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
express-route-cross-connection

### Description of issue (in as much detail as possible)
https://github.com/Azure/azure-cli-extensions/blob/bbefbe73a620c6407b522484d6b2ba848cb4f9f5/src/express-route-cross-connection/azext_expressroutecrossconnection/_help.py#L131

We shouldn't use min_profile in the help example. It needs to be updated to supportedprofile instead.
-----

**Comment by tjprescott** [comment]
In this case, the value can simply be removed. It serves no purpose.
