### ISSUE TITLE
k8s-extension: Update to same version gives runtime exception 

### ISSUE THREAD

**Issue by pravinpushkar** [Azure/azure-cli-extensions#5910]
### Related command

az k8s-extension update --cluster-type managedClusters --cluster-name rbac --resource-group aks-ext-e2e-rg --name myDaprExtension  --auto-upgrade false --version 1.10.1 --release-train dev --debug

### Extension name (the extension in question)

Dapr

### Description of issue (in as much detail as possible)

-----

When I use the above update command on a Dapr cluster having the same version, it gives exception on the stdout.
Ideally, It should have completed the update even if we are trying to update with the same version.

I am attaching the debug log below - 

[upgrade_debug.txt](https://github.com/Azure/azure-cli-extensions/files/10806139/upgrade_debug.txt)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@pravinpushkar Can you please try updating the extension version using `az extension update --name k8s-extension` cmdlet.
Also, if you are using `--auto-upgrade=false` then you don't need to pass `--release-train`, you only need `--version`. You can use `--release-train` when `--auto-upgrade` is true but need to remove `--version` in that case.

**Comment by pravinpushkar** [comment]
@SaurabhSharma-MSFT  Thanks for the reply. 
After updating `k8s-extension` via `az extension update --name k8s-extension` the error seems to go away.

Closing this now.
