### ISSUE TITLE
Updating data factory global parameters

### ISSUE THREAD

**Issue by fabiocarello** [Azure/azure-cli-extensions#5920]
### Related command
az datafactory update

### Extension name (the extension in question)
datafactory

### Description of issue (in as much detail as possible)
It seems not allowed to update global parameters against an existing factory. I'm trying using the update command but I'm not sure this is the right way.  In general, is this action possible on the CLI?

```
az datafactory update --factory-name adf-globalparam-demo  --resource-group rg-adfglobalparam-demo --global-parameters @params.json

unrecognized arguments: --global-parameters {"stringParam" : {"type" : "string", "value": "astring"}, "numParam" : {"type" : "int", "value": "99"}, "numParam2" : {"type" : "int", "value": "299"} }
```
-----

Thanks

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@fabiocarello Can you please share the debug results using `--debug` parameter ? Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@fabiocarello Please let us know if you need any help on this issue.

**Comment by SaurabhSharma-MSFT** [comment]
@fabiocarello We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
