### ISSUE TITLE
azure-cli-extensions adding aks_preview-0.5.92 wheel is failing with az-cli error

### ISSUE THREAD

**Issue by ThiraviamR** [Azure/azure-cli-extensions#5927]
Hi Team,
I need to create a wheel file with aks-preview with 0.5.92 version. For that updated the "VERSION = 0.5.92" in "setup.py" and ran "setup.py bdist_wheel" and got the wheel file. When i tried to use the file and tried to import using the following command "run az extension add --source <local path to wheel file>" getting the below error. Please do the needful.

"cli.azure.cli.core.azclierror: The 'None' extension version None is not compatible with your current CLI core version 2.40.0.
This extension requires a min of 2.44.0 CLI core.
Please run 'az upgrade' to upgrade to a compatible version.
az_command_data_logger: The 'None' extension version None is not compatible with your current CLI core version 2.40.0.
This extension requires a min of 2.44.0 CLI core.
Please run 'az upgrade' to upgrade to a compatible version."

Due to certain environment complications could not update CLI version currently.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ThiraviamR Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please upgrade your AzCLI to the [most recent version ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli)and test ?

**Comment by ThiraviamR** [comment]
No problem. Due to environment constraints upgrading the CLI is not viable for us. Luckily i have got the golden build (https://azcliprod.blob.core.windows.net/cli-extensions/aks_preview-0.5.92-py2.py3-none-any.whl ) wheel file from the following link and that worked fine on installation. Thanks

**Comment by navba-MSFT** [comment]
@ThiraviamR Thanks for getting back. I am glad that you are unblocked now. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
