### ISSUE TITLE
$KUBECONFIG is not used using `get-credentials`

### ISSUE THREAD

**Issue by mjnovice** [Azure/azure-cli-extensions#5930]
## Describe the bug
```
 ➜  cloudgen-operator git:(mj/gc) ✗  echo $KUBECONFIG                       
/var/folders/1l/xcf1g9d94sb_33ns8yck1n0c0000gr/T/kubectx.XXXXXX.r8h0g8za
(cloudgen-dev-mgmt/default) 
 ➜  cloudgen-operator git:(mj/gc) ✗  az aks get-credentials --resource-group ci-azure-sample-1 --name ci-azure-sample-1 --subscription DevTest-SL-EA


The behavior of this command has been altered by the following extension: aks-preview
Merged "ci-azure-sample-1" as current context in /Users/mayankjha/.kube/config
(cloudgen-dev-mgmt/default) 
```

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.5.129.`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `export KUBECONFIG=/tmp/yourkubeconfigfile`
- `az aks get-credentials --resource-group {} --name {} --subscription {}`

## Expected Behavior
az command should use `$KUBECONFIG` but it uses default file.

## Environment Summary
```
macOS-13.2.1-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.45.0

Extensions:
aks-preview 0.5.129
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
https://github.com/Azure/azure-cli/issues/16148

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@mjnovice This is expected since that is the [documented default file](https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials) to be used.

You may however use the `--file` parameter to modify the behavior.
