### ISSUE TITLE
Display `running` after `az spring app update` command completed

### ISSUE THREAD

**Issue by RuoyuWang-MS** [Azure/azure-cli-extensions#5943]
## Describe the bug
After the CLI command is executed, the message is returned with a word "| Running...".

**Command Name**
`az spring app update
Extension Name: spring. Version: 1.6.8.`

**Errors:**
No return error, only display error. The word "| running ..." is added to the return information.
![image](https://user-images.githubusercontent.com/86712051/223006185-8ce1072f-8a7b-4e6d-82dc-18f03f5ffac7.png)
![image](https://user-images.githubusercontent.com/86712051/223006764-e3f64671-454b-4383-b4f8-42c75841394b.png)

```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az spring app update -n {} -d {} -s {} -g {} --env {}`

## Expected Behavior
Execute successfully and return the app information.
## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
spring 1.6.8
spring-cloud 3.1.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Non customer reported thread. Adding Service team to look into this. 

@ShichaoQiu, @yuwzho, @yucwan Could you please look into this once you get a chance ? Thanks in advance.

**Comment by yuwzho** [comment]
This is already fixed. Let us close this issue
