### ISSUE TITLE
Authoring az cli extensions

### ISSUE THREAD

**Issue by rguptar** [Azure/azure-cli-extensions#5944]
We're trying to run tests for a given extension. Are these steps correct?

git clone https://www.github.com/azure/azure-cli
git clone https://www.github.com/azure/azure-cli-extensions
python3 -m venv azcli-extension-env
source azcli-extension-env/bin/activate
pip install azdev
azdev setup --cli ./azure-cli --repo ./azure-cli-extensions
cd azure-cli-extensions
azdev setup -r . -e aks-preview
azdev test aks-preview

The last command fails with:
```

=============
| Run Tests |
=============


test index found: /home/azureuser/.azdev/env_config/home/azureuser/azure-cli-extensions/env/test_index/latest.json

Test on modules: aks-preview

'aks-preview' not found. If newly added, re-run with --discover
No tests selected to run.
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@rguptar yes, the steps are correct.  Can you please try running `azdev test aks-preview --discover`.

**Comment by SaurabhSharma-MSFT** [comment]
@rguptar I believe you already got few suggestions from the CLI team on the Github issue linked above.  Please let me know if you still have questions otherwise, we will close this issue.

**Comment by rguptar** [comment]
Ideally, these steps would be added to documentation before closing out this issue but if that's not doable, then we can close this.

**Comment by SaurabhSharma-MSFT** [comment]
@rguptar I get you and as mentioned in the other issue the team will be working on combining and improving the existing in future which could help onboarding developers, I am proceeding with the closure of this issue. 
Please feel free to open an issue if you have any questions or any blockers using CLI or CLI extensions.  Thank you.
