### ISSUE TITLE
az ssh vm - 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by onepar** [Azure/azure-cli-extensions#5984]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 1.1.4.`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/user1/.azure/cliextensions/ssh/azext_ssh/custom.py", line 66, in ssh_vm
    _do_ssh_op(cmd, ssh_session, op_call)
  File "/home/user1/.azure/cliextensions/ssh/azext_ssh/custom.py", line 159, in _do_ssh_op
    op_info.ip = op_info.ip or ip_utils.get_ssh_ip(cmd, op_info.resource_group_name,
  File "/home/user1/.azure/cliextensions/ssh/azext_ssh/ip_utils.py", line 36, in get_ssh_ip
    if public_ip_ref and public_ip_ref.get("id", None):
AttributeError: 'str' object has no attribute 'get'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --local-user {} --private-key-file {} -n {} -g {}`

## Environment Summary
```
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.2 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.46.0

Extensions:
ssh 1.1.4

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by onepar** [comment]
It's not reproducible in ssh 1.1.3.

**Comment by tszalaj** [comment]
I just got the same error using:
`az ssh vm --name azure-vm-name --resource-group VM-RG-Name`

Az -v
azure-cli                         2.46.0
core                              2.46.0
telemetry                          1.0.8
Extensions:
ssh                                1.1.4
Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\t\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Error message is the same except paths to files - file names and line number match.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@onepar Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by vthiebaut10** [comment]
@kairu-ms @AllyW - can you take a look? This seems to have been introduced by this PR: https://github.com/Azure/azure-cli-extensions/pull/5945

**Comment by AllyW** [comment]
@vthiebaut10  sure, fix pr is https://github.com/Azure/azure-cli-extensions/pull/6004
