### ISSUE TITLE
Follow instructions to send email with azure cli, did not work on my mac

### ISSUE THREAD

**Issue by magom001** [Azure/azure-cli-extensions#5985]
Followed the instructions from https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/send-email?tabs=unix&pivots=platform-azcli&tryIt=true&source=docs#code-try-0

## Describe the bug

**Command Name**
`az communication email send
Extension Name: communication. Version: 1.5.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.communication'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/Users/***/.azure/cliextensions/communication/azext_communication/manual/_client_factory.py", line 85, in cf_communication_email
    from azure.communication.email import EmailClient
ModuleNotFoundError: No module named 'azure.communication'
```
Azure CLI version:

```
az --version
azure-cli                         2.46.0

core                              2.46.0
telemetry                          1.0.8

Extensions:
communication                      1.5.1

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/bin/python'
Extensions directory '/Users/***/.azure/cliextensions'

Python (Darwin) 3.10.10 (main, Feb 16 2023, 02:49:39) [Clang 14.0.0 (clang-1400.0.29.202)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az communication email send --connection-string {} --sender {} --to {} --subject {} --text {}`

## Environment Summary
```
macOS-13.2.1-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.46.0

Extensions:
communication 1.5.1

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@magom001 Thanks for reaching out to us and reporting this issue. Please follow the below action plan and check if that helps:

**Plan 1:**
Please update your `communication` extension by running the below command and then test your CLI command again:

> **az extension update -n communication**

**Plan 2:**
If the above plan doesn't work try running the below command and test again:

> **pip install azure-communication-email**

Hope this helps.

**Comment by navba-MSFT** [comment]
@magom001 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@magom001 The action is currently pending on you to try the above suggested action plan. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
