### ISSUE TITLE
Azure CLI task was failing with ERROR: An error occurred. Pip failed with status code 1.

### ISSUE THREAD

**Issue by Prudhvi1236** [Azure/azure-cli-extensions#6030]
We are using azure CLI task in our pipeline to connect to our azure postgres flexi server to run scripts. Below is the command we have used in our AZ CLI task.
 
                "  **az config set extension.use_dynamic_install=yes_without_prompt** "
                 
FYI : day before yesterday also the task works fine, but from yesterday onwards I am getting below error.

**_WARNING: The command requires the extension rdbms-connect. It will be installed first.
ERROR: An error occurred. Pip failed with status code 1. Use --debug for more information.
##[error]Script failed with exit code: 1_**

Seems issue with installing the extension, kindly help.

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by kairu-ms** [comment]
Hi @Prudhvi1236, could you provide the version of `rdbms-connect` and `azure-cli`. It seems caused by dependencies issues.

**Comment by bebound** [comment]
Please provide the output of `az extension add -n rdbms-connect --debug`

**Comment by Prudhvi1236** [comment]
@bebound 

Please find the log output file.
[Log.txt](https://github.com/Azure/azure-cli-extensions/files/10999411/Log.txt)

**Comment by thrsn-ur** [comment]
[tasklog_13.log](https://github.com/Azure/azure-cli-extensions/files/10999954/tasklog_13.log)
Hi, we are also experiencing this issue in an Azure DevOps Release pipeline running Ubuntu 20.04. I have attached the logs.

**Comment by bebound** [comment]
Workaround:
Update `setuptools` to latest version:
`/opt/az/bin/python3 -Im pip install -U setuptools`

I this is related to https://github.com/pypa/setuptools/issues/3589

**Comment by thrsn-ur** [comment]
We are able to get the Release pipeline working with this workaround, thanks!

**Comment by Prudhvi1236** [comment]
One more workaround I identified, using ubuntu 18.04 my pipeline works well.

**Comment by imranrazakhan** [comment]
I have to install rust and this error get resolved.
