### ISSUE TITLE
az aks get-credentials gives an error "string indices must be integers"

### ISSUE THREAD

**Issue by saisujithreddym** [Azure/azure-cli-extensions#6036]
![image](https://user-images.githubusercontent.com/6829181/226242596-13b137f4-0d7f-44c7-8bdd-9beb56477cb0.png)

## Describe the bug

**Command Name**
`az aks get-credentials
Extension Name: aks-preview. Version: 0.5.132.`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --name {} --resource-group {} --admin`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.10
Installer: 

azure-cli 2.46.0

Extensions:
aks-preview 0.5.132
azure-devops 0.26.0
azure-firewall 0.14.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by FumingZhang** [comment]
Hey @saisujithreddym, it looks like the problem happens with the format of the existing kubeconfig file. Could you please help check the content of the existing kubeconfig file (by default the file is located at `C:\Users\samankal\.kube\config` if you did not specify option `-f/--file` when running the command)? The file should look like [sample](https://github.com/zecke/Kubernetes/blob/master/docs/user-guide/kubeconfig-file.md#example-kubeconfig-file), which should be in yaml format and have the keys `clusters`, `users`, `contexts`.

Fom the error message, your existing file was not successfully parsed into a hierarchical object, but was parsed into a string. Please **delete** the **sensitive information** (e.g., cert data, key data, token) in the file and attach it here to help further debug.

Or a simple workaround is to delete the existing file and re-run the command.

**Comment by FumingZhang** [comment]
The default file path might be replaced by the path defined by the system variable `KUBECONFIG`. If you've set this variable, please remove the corresponding file.

You could run the command with an extra option `--verbose`
![image](https://user-images.githubusercontent.com/81607949/226506205-aa5adeee-e692-4497-8c40-f0b788f12129.png)

**Comment by navba-MSFT** [comment]
@saisujithreddym Thanks for reaching out to us and reporting this issue. I am unable to reproduce this issue at my end. I am using most recent version of `aks-preview` extension. As mentioned in the [above comment](https://github.com/Azure/azure-cli-extensions/issues/6036#issuecomment-1477202911), you could run the command with` --verbose` switch and identify where the config is being saved. Then try deleting that config and re-run the command.

**Comment by navba-MSFT** [comment]
@saisujithreddym I wanted to do quick follow-up to check if you had a chance to look at the action plan provided in the [above comment](https://github.com/Azure/azure-cli-extensions/issues/6036#issuecomment-1477202911). Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@saisujithreddym Please let me know if you had any update on this.

**Comment by saisujithreddym** [comment]
@navba-MSFT I had an issue with the WSL environment. It does not look like an issue with the CLI command. Closing this issue.
