### ISSUE TITLE
command not found on latest CLI

### ISSUE THREAD

**Issue by dbilleci-lightstream** [Azure/azure-cli-extensions#606]
$ az monitor app-insights events
az monitor: 'app-insights' is not in the 'az monitor' command group. See 'az monitor --help'.

$ az --version
azure-cli (2.0.61)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bce0dc5-da82-717a-70cf-e392c05904a3
* Version Independent ID: a5cb6492-d731-0c98-7691-64d1d7a14a5c
* Content: [az monitor app-insights](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by dbilleci-lightstream** [comment]
`az extension add --name application-insights`

**Comment by Rakatashii** [comment]
az: 'az' is not in the 'az' command group. See 'az --help'.
