### ISSUE TITLE
Can't create enrollment group from CLI

### ISSUE THREAD

**Issue by rsre** [Azure/azure-cli-extensions#609]
All I get as an answer is:

az iot dps: 'enrollment' is not in the 'az iot dps' command group. See'az iot dps --help'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6820ec95-fd0d-3959-41fd-25f50ed7abd8
* Version Independent ID: c3a688ac-b257-5994-b8a9-0022a6a7dca7
* Content: [az iot dps enrollment](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/dps/enrollment?view=azure-cli-latest#code-try-4)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/dps/enrollment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/dps/enrollment.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
You need to install the extension.
`az extension add -n azure-cli-iot-ext`
