### ISSUE TITLE
This does not exist anymore, but there is "az webapp ssh"

### ISSUE THREAD

**Issue by liranms** [Azure/azure-cli-extensions#613]
This does not exist anymore, but there is "az webapp ssh"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04a67a6a-b2b8-ed24-bb78-e9773fef6d86
* Version Independent ID: beeae428-5c77-4501-0ab5-a7301971f058
* Content: [az webapp remote-connection](https://docs.microsoft.com/en-us/cli/azure/ext/webapp/webapp/remote-connection?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/webapp/webapp/remote-connection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/webapp/webapp/remote-connection.yml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amitmawkin** [comment]
why there is no response to this issue - obviously the article is old and cli complains with the error

**Comment by tjprescott** [comment]
@panchagnula for comment

**Comment by panchagnula** [comment]
@amitmawkin this does exist in the extension & az webapp ssh exists on the core, & the new one works on Mac or Linux only & is recommended to be used in that scenario.

@rramachand21 & @patricklee2 & @yiliaomsft comment on the future of the command on extensions

**Comment by rramachand21** [comment]
@patricklee2 please move the remote connection to core as well. We should support this for remote debugging scenarios.

**Comment by patricklee2** [comment]
fixed in https://github.com/Azure/azure-cli/pull/9207
