### ISSUE TITLE
output: ERROR: Resource "ORIGINAL DISK FOR IMAGE" is not found.

### ISSUE THREAD

**Issue by johnwildes** [Azure/azure-cli-extensions#618]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

image-copy-extension

### Description of issue (in as much detail as possible)
When Attempting to copy an image to a new region, it ends up failing at the CREATE SOURCE SNAPSHOT step.

I have an image I just created.  It works when deploying a new VM from it.  I have cleaned up the resources that were used to create this image. I've deleted the original OS disk (**CreateImageVM-OSDisk**), as it's not needed nor is it usable anymore.

I've sanitized the information in this error messge, if you require the original source information please let me know.

**Original Command**
john@Azure:~$ az image copy --source-resource-group MySourceRG --source-object-name MyImageName --target-resource-group MyTargetRG --target-location westeurope --cleanup --verbose

**NOTE** - MyImageName is the name of the "Image" resource object that exists in the MySourceRG, it is not a DISK, or Snapshot. I also attempted this with the _--source-type image_ parameter

**Process starting**
Getting os disk id of the source vm/image
Creating source snapshot
command failed: ['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'MyImageName_os_disk_snapshot', '--resource-group', 'MySourceRG', '--source', '/subscriptions/SUBGUID/resourceGroups/RGWhereTheSourceVMDiskWasLocated/providers/Microsoft.Compute/disks/**CreateImageVM-OSDisk**', '--output', 'json', '--tags', 'created_by=image-copy-extension']

**>>>THIS REFERENCES THE ORIGINAL OSDISK WHICH HAS BEEN DELETED<<<<**

output: ERROR: Resource CreateImageVM-OSDisk is not found.

<<<<< REMAINING TRACE LOG >>>>>>>

The command failed with an unexpected error. Here is the traceback:

Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'MyImageName_os_disk_snapshot', '--resource-group', 'MySourceRG', '--source', '/subscriptions/SUBGUID/resourceGroups/RGWhereTheSourceVMDiskWasLocated/providers/Microsoft.Compute/disks/**CreateImageVM-OSDisk**', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 409, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 402, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/home/john/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 78, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/john/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 35, in run_cli_command
    raise ex
  File "/home/john/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/opt/az/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'MyImageName_os_disk_snapshot', '--resource-group', 'MySourceRG', '--source', '/subscriptions/SUBGUID/resourceGroups/RGWhereTheSourceVMDiskWasLocated/providers/Microsoft.Compute/disks/**CreateImageVM-OSDisk**', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.

-----

**Comment by tamirkamara** [comment]
Hi @johnwildes,

The experience you described is unfortunately by design as documented [here](https://github.com/Azure/azure-cli-extensions/blob/master/src/image-copy/readme.md) and in the command help. In short - the image-copy extension needs the disk of the vm used to create the image so don't clean it...
For a more robust solution I suggested looking at the [image gallery](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/shared-image-galleries) feature now offered natively on Azure. 

If you're ok with this information please close this issue.

**Comment by johnwildes** [comment]
I'll close it.  I didn't actually see the readme.  I found this extension through stackoverflow, is there some official docs.microsoft.com place where this would be documented?  The azure portal says the VM is unusable after you create this image using the capture function.  Which really leads a user to delete the resources afterwards. I mean why would I keep a source OS disk and incur cost for it, only to not be able to copy this image to somewhere else.  

I struggle with why there would be two options for images.  Shared Image gallery, and then captured images, that require you to have the OS disk, and other disk remain if necessary, to be able to make those images available in other regions.  Has it been recommended as a "feature" to NOT have the OS disk available to be able to copy this?  Seems like that's the more natural use case for this.

**Comment by johnwildes** [comment]
Closing "works as designed"

**Comment by tamirkamara** [comment]
@johnwildes
Well, the reason is timing - the image copy extension was created at a time that no native solution was available, and it needed to work with what was possible at the time. That's why it requires the disk to be there.
Shared image galleries are relatively new and if not mistaken still under preview.

**Comment by johnwildes** [comment]
@tamirkamara I completely understand, I'm just caught between the two at the moment.  Having never needed to use images until recently, and then having these two options. I still thing the experience is less than ideal, where you're not made aware of all these gotchas during the image creation and within the documentation (or lack thereof).  I'm onto the shared image galleries, I only had one image (that was critical).

**Comment by andycoderapptio** [comment]
https://docs.microsoft.com/en-us/azure/virtual-machines/azure-compute-gallery#regional-support

The documentation states you need to request access for certain regions and suggests Australia Central or Australia Central 2 as examples but doesn't say exactly which regions aren't supported and the fact that you have to make a request makes me doubt how well it will actually work once granted. 

Does anyone have a list as to which regions are actually supported and/or how well the compute gallery works once supported is granted. I'm just not going to burn another day finding a solution to what should be a very simple problem only to be blocked at the last step for some asinine reason.
