### ISSUE TITLE
"az ssh vm" error from WSL2

### ISSUE THREAD

**Issue by efremropelato** [Azure/azure-cli-extensions#6199]
## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 1.1.3.`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --prefer-private-ip -n {} -g {}`

## Environment Summary
```
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.6 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.47.0

Extensions:
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by SaurabhSharma-MSFT** [comment]
@efremropelato Can you provide the debug log of cmdlet you are using.

**Comment by SaurabhSharma-MSFT** [comment]
@efremropelato We are still waiting for your response.

**Comment by SaurabhSharma-MSFT** [comment]
@efremropelato We will now proceed to close this thread as we haven't heard back. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
