### ISSUE TITLE
--enable-rbac option is deprecated

### ISSUE THREAD

**Issue by bokse001** [Azure/azure-cli-extensions#621]
Argument 'enable_rbac' has been deprecated and will be removed in future release. Use '--disable-rbac' instead. RBAC is enabled by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea52f6a-7414-7aa2-3708-7b802f243a16
* Version Independent ID: cf003f17-b9f7-04d4-89c2-770273b40533
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/aks-preview/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/aks-preview/aks.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
I don't believe there is an ask or issue here, so I am closing this.
