### ISSUE TITLE
az iot hub monitor-events  returns almost immediately

### ISSUE THREAD

**Issue by scapri** [Azure/azure-cli-extensions#624]
**Describe the bug**
I run the command:
az iot hub monitor-events --hub-name nrf91-blemesh-firetruck-demo-hub
and the command line returns almost immediately (< 1 second, and no error messages) without waiting to give information about messages to the IoT hub.  

**To Reproduce**
Run the command described above in our Azure terminal window.  It reproduces this problem each time.

**Expected behavior**
The command should wait reading from the IoT hub, and not return until it has timed out (several minutes).

**Environment summary**
On Azure's portal, requested a cloud shell - here's the output in the cloud shell window:
****************** start of output ****************
Requesting a Cloud Shell.Succeeded.
Connecting terminal...

azure@Azure:~$ az iot hub monitor-events --hub-name nrf91-blemesh-firetruck-demo-hub
Starting event monitor, use ctrl-c to stop...
azure@Azure:~$ az extension remove --name azure-cli-iot-ext
azure@Azure:~$ az extension add --name azure-cli-iot-ext
azure@Azure:~$ az iot hub monitor-events --hub-name nrf91-blemesh-firetruck-demo-hub
Dependency update required for IoT extension version: 0.7.0.
Updated dependency must be compatible with uamqp 1.0.3. Continue? (y/n) -> y
Updating required dependency...
Update appears to have worked. Executing command...
Starting event monitor, use ctrl-c to stop...
azure@Azure:~$
******************** end of output ********************

That entire process took less than a minute, and I did not hit any ctrl-c's

**Additional context**
The command was working as expected, and then this behavior started in the last several weeks.  I tried removing and reinstalling the extension:
$ az extension remove --name azure-cli-iot-ext
$ az extension add --name azure-cli-iot-ext
And things started working, until the first message came in.  It then echoed that message, and exited.  Afterwards, it resumed the problem of returning almost immediately.  Subsequent removing and re-adding of the extension has not given any additional monitoring ability.

I ran the command again with the --debug option, and output stderr to a file.  I've attached the file here as "junkfile".  I tried looking through it, but it's a lot of things I don't grok.
[junkfile.txt](https://github.com/Azure/azure-cli/files/3044898/junkfile.txt)

**Comment by yonzhan** [comment]
iot

**Comment by yiyiguo** [comment]
@Azure/azure-iot-cli-triage

**Comment by digimaun** [comment]
Hi @scapri , I realize this is an old issue. Are you still having problems? There have been a number of improvements to the monitor-events command since the submission date of this issue and I would first recommend uninstalling the legacy extension `azure-cli-iot-ext`  and installing the latest IoT extension which is now called `azure-iot`. 

Then there are a couple common trouble shooting steps around event monitoring which were [commented here](https://github.com/Azure/azure-iot-cli-extension/issues/55#issuecomment-535625681). Looking at your logs, its similar characteristics of a consumer group conflict. I wonder if you had multiple clients connecting to the same `$default` consumer group during your runs?

**Comment by scapri** [comment]
Hi, thanks for the update!

We’re not working on that project anymore, but I’m glad to hear that the problem may have been resolved.  The next time we are working on Azure, I will uninstall the old extension, and try the new one.  Is there a quick cheatsheet for doing that? (I haven’t been doing anything in the cloud lately, and Azure skills are getting a bit rusty – I’ll use this email to do the uninstall/new install when the time comes).

As far as multiple clients – not as far as I could tell (at that time – we were 1-1 during testing – just me logging in, and communicating with our 1 device).

Thanks!
Sandra
---
Sandra Capri
[signature_569691942]
3380 W Americana Terrace #290
Boise, ID 83706
www.ambientsensors.com<http://www.ambientsensors.com/>

**Comment by digimaun** [comment]
Sounds good thank you. For a cheat sheet I'd recommend the IoT extension repo's [install guide](https://github.com/Azure/azure-iot-cli-extension#installation) - the uninstall legacy extension step (if it applies) is in the [news section](https://github.com/Azure/azure-iot-cli-extension#news).

But to be doubly sure here are the condensed steps
1. Install/update to the latest version of [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
2. **If it applies**, uninstall the legacy IoT extension with `az extension remove --name azure-cli-iot-ext`
    - You can check what extensions you have installed with `az extension list`.
3. Add, Update or Remove the IoT extension with the following commands:
    - Add:  `az extension add --name azure-iot`
    - Update: `az extension update --name azure-iot`
    - Remove: `az extension remove --name azure-iot`

I will go ahead and close this issue. If you run into this issue or others with the IoT extension commands feel free to submit an issue on the [IoT extension repo](https://github.com/Azure/azure-iot-cli-extension/issues).

**Comment by scapri** [comment]
Thanks so much!  You folks at Azure have been great to work with!

Sandra
---
Sandra Capri
[signature_1102706315]
3380 W Americana Terrace #290
Boise, ID 83706
www.ambientsensors.com<http://www.ambientsensors.com/>
