### ISSUE TITLE
Programmatically Alter Number of Paid 'Azure DevOps Services Users'

### ISSUE THREAD

**Issue by tightightight** [Azure/azure-cli-extensions#625]
We are looking for a way to increase/decrease the number of paid users through the marketplace.

A solution involving a cli command to take care of this would be great, and also something to assign those roles to an AD email.

An available api endpoint that can be hot to make these changes would also be hugely appreciated!

I have done a lot of searching through the documentation for cli commands and endpoints.  I realize these may not exist, because it is inadvisable to automate these aspects of AzDO, so I am open to that feedback as well.  It would be great to easily be able to add a user and assign subscriptions quickly during our on boarding process.  This will allow less downtime for new employees, as well as lighten the current load and confusion we are currently dealing with getting these things done.  Thank you for any help or feedback in advance!

**Comment by gauravsaralMs** [comment]
@tjprescott : I don't see the option to transfer issues, if you can then please transfer it to devops cli repo https://github.com/Microsoft/azure-devops-cli-extension
cc: @Azure/azure-devops-cli

**Comment by tjprescott** [comment]
Hi @gauravsaralMs the transfer option is a beta feature in Github, but I can't transfer to that repo because it is in "Microsoft" and not "Azure".  But I will try the Zenhub move feature and see if that works.

**Comment by gauravsaralMs** [comment]
@tightightight : can you please close this issue and open the same at https://github.com/Microsoft/azure-devops-cli-extension

**Comment by geverghe** [comment]
Since this has not surfaced in our repo, just providing a quick update here - we released the [user management commands](https://docs.microsoft.com/cli/azure/ext/azure-devops/devops/user?view=azure-cli-latest) that lets you add users to an organization and assign licenses. Feel free to reopen any follow ups in our repo - https://github.com/azure/azure-devops-cli-extension

**Comment by atbagga** [comment]
@tightightight Closing the issue as per comment from George. Please feel free to open a follow up in our [repo ](https://github.com/azure/azure-devops-cli-extension) if your issue is not resolved by the new commands.
