### ISSUE TITLE
`az group create` incorrectly requests `--rg-name` argument

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-cli-extensions#628]
**Describe the bug**
In some situations, the Azure CLI requres the use of the `--rg-name` argument with `az group create`. When this argument is required, `--name` does not work as an alias.

This argument only works when the `--name` argument is refused; otherwise the `--name` argument is reported as required, and `--rg-name` does not work.

**To Reproduce**
* Reproduction may require a fully clean install (removal of `.azure` cache, uninstall Azure CLI, reinstall Azure CLI)
```
az interactive

az>> group create -n 'Example2' --location westus2
az group create: error: the following arguments are required: --rg-name, --location/-l
usage: az group create [-h] [--verbose] [--debug]
[--output {json,jsonc,table,tsv,yaml,none}]
[--query JMESPATH] --rg-name RG_NAME --location
LOCATION [--tags TAGS] [--subscription _SUBSCRIPTION]

az>> /home/stramer/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py:136: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.         help_entry = yaml.load(help_yaml)
az>>
az>> group create -n 'Example2' --location westus2
{
"id": "/subscriptions/07a45d58-11b5-4fd3-8cb6-12ac232d1c3f/resourceGroups/Example2", 
"location": "westus2",
"managedBy": null,
"name": "Example2", 
"properties": {
"provisioningState": "Succeeded"
},
"tags": null,
"type": null
```

**Expected behavior**
`az group create` requires and works with the `--name` argument.

**Environment summary**
* Ubuntu LTS 18.04 running on WSL (Win 1809, Build 17763.379)
```
az --version
---
azure-cli                         2.0.61
...
extension                          0.2.4
...
resource                          2.1.12

Extensions:
interactive                        0.4.1
Python location '/opt/az/bin/python3'
Extensions directory '/home/stramer/.azure/cliextensions'
Python (Linux) 3.6.5 (default, Mar 22 2019, 17:43:37) [GCC 7.3.0]
```

**Additional context**
* The bug seems to be triggered only while running in `az interactive`, and remediated by the failed YAML load.
* If `--rg-name` is an allowable switch, it should be an alias for `--name` to avoid breaking compatibility.

**Comment by adewaleo** [comment]
Thanks @tjprescott. I doubt it is an issue with the help system as our help / documentation logic rarely ever, if not never, affects argument validation.

**Comment by yonzhan** [comment]
add to Backlog

**Comment by RakeshMohanMSFT** [comment]
This is fixed now.
