### ISSUE TITLE
Add test cover for "az containerapp service XX delete" commands

### ISSUE THREAD

**Issue by yash-nisar** [Azure/azure-cli-extensions#6302]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command

`az containerapp service redis delete`
`az containerapp service postgres delete`

### Extension name (the extension in question)
containerapp

### Description of issue (in as much detail as possible)
Add test cover for the following commands:
`az containerapp service redis delete`
`az containerapp service postgres delete`

-----

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yash-nisar** [comment]
@yonzhan Can you assign it to me ?
