### ISSUE TITLE
Unable to run az vm repair create -g {rg} -n {source-vm-name} --verbose, on a Virtual Machine encrypted using BEK "without AAD".

### ISSUE THREAD

**Issue by Diofe** [Azure/azure-cli-extensions#6325]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Vm-repair

### Description of issue (in as much detail as possible)

Unable to run az vm repair create -g {rg} -n {source-vm-name} --verbose --debug, on an Virtual Machine encrypted using BEK "without AAD".

We are getting the error:

cli.azure.cli.core.azclierror: Traceback (most recent call last):
File "/usr/lib64/az/lib/python3.9/site-packages/knack/invocation.py", line 111, in _validation
self._validate_cmd_level(parsed_ns, cmd_validator)
File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/init.py", line 849, in _validate_cmd_level
cmd_validator(**self._build_kwargs(cmd_validator, ns))
File "/home/divyam/.azure/cliextensions/vm-repair/azext_vm_repair/_validators.py", line 64, in validate_create
encryption_type, _, _, _ = _fetch_encryption_settings(source_vm)
File "/home/divyam/.azure/cliextensions/vm-repair/azext_vm_repair/repair_utils.py", line 355, in _fetch_encryption_settings
if enabled.tolower() == 'false':
AttributeError: 'bool' object has no attribute 'tolower'

I suspected that this problem is related to:
https://github.com/Azure/azure-cli-extensions/commit/f2096071c968406896fab1dd806c2ff6882449bf
https://github.com/Azure/azure-cli-extensions/pull/6238

Can you please check if this problem is related to da code change?

-----

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by haagha** [comment]
@Diofe Thanks for reporting. This bug has been addressed by PR https://github.com/Azure/azure-cli-extensions/pull/6326

Please check if it works for you now.
