### ISSUE TITLE
Add support for kafka in (az containerapp service create/delete)

### ISSUE THREAD

**Issue by yash-nisar** [Azure/azure-cli-extensions#6330]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command

`az containerapp service kafka create..`
`az containerapp service kafka delete..`

### Extension name (the extension in question)
containerapp

### Description of issue (in as much detail as possible)
Add support for `kafka` in (`az containerapp service create/delete`)

-----

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yash-nisar** [comment]
@yonzhan Can this be assigned to me please ?
