### ISSUE TITLE
Revision suffix validation logic prevents suffixes that start with number

### ISSUE THREAD

**Issue by ruslany** [Azure/azure-cli-extensions#6449]
### Describe the bug

Use the following command to create a new containerapp or a revision on existing app. Make sure that the revision-suffix starts with a number.

```bash
export BLUE_COMMIT_ID=0b699ef
az containerapp create --name $APP_NAME
--environment $APP_ENVIRONMENT_NAME
--resource-group $RESOURCE_GROUP
--image mcr.microsoft.com/k8se/samples/test-app:$BLUE_COMMIT_ID
--revision-suffix $BLUE_COMMIT_ID
--env-vars REVISION_COMMIT_ID=$BLUE_COMMIT_ID
--ingress external
--target-port 80
--revisions-mode multiple
```

This results in a validation error

### Related command

az containerapp create

### Errors

Invalid Container App revision name '{value}'. A revision name must consist of lower case alphanumeric characters or '-', start with a letter, end with an alphanumeric character and cannot have '--'.

### Issue script & Debug output

N/A

### Expected behavior

The command should allow revision suffix that starts with a number

### Environment Summary

Latest version

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ruslany** [comment]
PR: #6448

**Comment by Greedygre** [comment]
Hi @ruslany 
the revision suffix can not start with number:
![image](https://github.com/Azure/azure-cli-extensions/assets/46143499/0aa029ed-187a-4200-89e4-b1e2ab4816fd)

**Comment by navba-MSFT** [comment]
@ruslany Thanks for reaching out to us and reporting this issue. Since you have filed the PR already which includes the fix. I am assigning this issue to you.

**Comment by PramodValavala-MSFT** [comment]
@ruslany This PR has been merged. Closing.
