### ISSUE TITLE
az managementpartner show, python exception

### ISSUE THREAD

**Issue by Shr3ps** [Azure/azure-cli-extensions#647]
## Describe the bug

**Command Name**
`az managementpartner show
Extension Name: managementpartner. Version: 0.1.2.`

**Errors:**

:confused:

```The command failed with an unexpected error. Here is the traceback:

argument of type 'NoneType' is not iterableTraceback (most recent call last):
  File "/home/sh/work/azure/venv/local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/sh/work/azure/venv/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- Login to a tenant: `az login --tenant cceccecc-xxxx-xxxx-xxx`
- `Run: az managementpartner show`

## Expected Behavior

This should return the managementparter ID associated (or an explicit message saying there is no ID associated).

## Environment Summary
```
Linux-4.4.0-17763-Microsoft-x86_64-with-Ubuntu-18.04-bionic
Python 2.7.15rc1
Shell: bash

azure-cli                         2.0.62

Extensions:
managementpartner                  0.1.2

Python location '/home/sh/work/azure/venv/bin/python'
Extensions directory '/home/sh/.azure/cliextensions'

Python (Linux) 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0]

```

**Comment by yonzhan** [comment]
managementpartner

**Comment by navba-MSFT** [comment]
@Shr3ps Apologies for the late reply. Could you please update the Azure CLI version and the python libraries and test the same command again? 
Also since this issue has been open for quite some time, Could you please let us know if you still need assistance on this ? Awaiting your reply.

**Comment by Shr3ps** [comment]
No more issue with latest update
```
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "managementpartner": "0.1.3"
  }
}
```
