### ISSUE TITLE
On Windows, it adds C:/Program Files/Git' and then it's an invalid Container App Environment resource ID to create my Spring App on ACA (consumption plan)

### ISSUE THREAD

**Issue by SandraAhlgrimm** [Azure/azure-cli-extensions#6494]
### Describe the bug

`$ az spring create     --name ${AZURE_SPRING_APPS_INSTANCE}     --managed-environment ${MANAGED_ENV_RESOURCE_ID}     --sku standardGen2`
--managed-environment C:/Program Files/Git/subscriptions/111111117/resourceGroups/mySpringApp/providers/Microsoft.App/managedEnvironments/mySpringAppDev is not a valid Container App Environment resource ID

`$ echo ${MANAGED_ENV_RESOURCE_ID}
/subscriptions/111111117/resourceGroups/mySpringApp/providers/Microsoft.App/managedEnvironments/mySpringAppDev`

### Related command

` az spring create`

### Errors

--managed-environment C:/Program Files/Git/subscriptions/111111117/resourceGroups/mySpringApp/providers/Microsoft.App/managedEnvironments/mySpringAppDev is not a valid Container App Environment resource ID

### Issue script & Debug output

$ az spring create     --name ${AZURE_SPRING_APPS_INSTANCE}     --managed-environment ${MANAGED_ENV_RESOURCE_ID}     --sku standardGen2 --debug
cli.knack.cli: Command arguments: ['spring', 'create', '--name', 'mySpringAppInstance', '--managed-environment', 'C:/Program Files/Git/subscriptions/11111117/resourceGroups/mySpringApp/providers/Microsoft.App/managedEnvironments/mySpringAppDev', '--sku', 'standardGen2', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01E6B460>, <function OutputProducer.on_global_arguments at 0x01F39BF8>, <function CLIQuery.on_global_arguments at 0x01F58850>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'spring': ['azure.cli.command_modules.serviceconnector', 'azext_spring']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: serviceconnector          0.549        16       235
cli.azure.cli.core: Total (1)                 0.549        16       235
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: spring                    0.473        39       180  C:\Users\My Name\.azure\cliextensions\spring
cli.azure.cli.core: Total (1)                 0.473        39       180
cli.azure.cli.core: Loaded 54 groups, 415 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : spring create
cli.azure.cli.core: Command table: spring create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x042261D8>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\My Name\.azure\commands\2023-07-10.11-53-04.spring_create.38840.log'.
az_command_data_logger: command args: spring create --name {} --managed-environment {} --sku {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x04251730>]
cli.knack.commands: Configured default 'mySpringApp' for arg resource_group
cli.knack.commands: Configured default 'westeurope' for arg location
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0426D6A0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0426D898>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01F39C40>, <function CLIQuery.handle_query_parameter at 0x01F58898>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0426D850>]
az_command_data_logger: extension name: spring
az_command_data_logger: extension version: 1.14.0
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 651, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/invocation.py", line 113, in _validation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 859, in _validate_arg_level
  File "C:\Users\My Name\.azure\cliextensions\spring\azext_spring\_validators.py", line 754, in validate_managed_environment
    raise InvalidArgumentValueError('--managed-environment {0} is not a valid Container App Environment resource ID'.format(managed_environment_id))
azure.cli.core.azclierror.InvalidArgumentValueError: --managed-environment C:/Program Files/Git/subscriptions/1111177/resourceGroups/mySpringApp/providers/Microsoft.App/managedEnvironments/mySpringAppDev is not a valid Container App Environment resource ID

 

cli.azure.cli.core.azclierror: --managed-environment C:/Program Files/Git/subscriptions/111117/resourceGroups/mySpringApp/providers/Microsoft.App/managedEnvironments/mySpringAppDev is not a valid Container App Environment resource ID
az_command_data_logger: --managed-environment C:/Program Files/Git/subscriptions/1111117/resourceGroups/mySpringApp/providers/Microsoft.App/managedEnvironments/mySpringAppDev is not a valid Container App Environment resource ID
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x042262F8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.157 seconds (init: 0.514, invoke: 1.643)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3639 in cache
telemetry.check: Negative: The C:\Users\My Name\.azure\telemetry.txt was modified at 2023-07-10 11:50:13.221615, which in less than 600.000000 s

### Expected behavior

I want a new Spring App being created in the specified managed environment. (Azure Container Apps)

### Environment Summary

azure-cli                         2.46.0 *

 

core                              2.46.0 *
telemetry                          1.0.8

 

Extensions:
containerapp                      0.3.35
spring                            1.14.0

 

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

 

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\My Name\.azure\cliextensions'

 

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

 

Legal docs and information: aka.ms/AzureCliLegal

 

### Additional context

I did a pair programming session with @rajata07 who is experiencing the same.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by yuwzho** [comment]
@ShichaoQiu will look into this

**Comment by ShichaoQiu** [comment]
Thanks @SandraAhlgrimm . Did you run the CLI command in Git Bash? What's your terminal tool? Sometimes, in Git Bash env, it will try to help you to add file prefix (e.g. C:/Program Files/Git) into your file path. Would you pls have a try by using other tool? for example, PowerShell, WSL linux or other tools, thanks a lot.

**Comment by SandraAhlgrimm** [comment]
It works on Cloud Shell now. But I would love to see that working on Git Bash on Windows as well as it seems a common scenario for Java Developers.

**Comment by ShichaoQiu** [comment]
Hi @SandraAhlgrimm , you can try the following workaround solution in GitBash
- Use double slash, for example, `//` subscriptions/111111117/resourceGroups/mySpringApp/providers/Microsoft.App/managedEnvironments/mySpringAppDev
- Add `MSYS_NO_PATHCONV=1` before the CLI command, for example, `MSYS_NO_PATHCONV=1 az spring create xxxxx`
- export `MSYS_NO_PATHCONV=1`, for example, `export MSYS_NO_PATHCONV=1`, and then run CLI command.

Feel free to ping me if you hit any issue, thanks a lot.
