### ISSUE TITLE
"az stream-analytics" is under Experimental. 

### ISSUE THREAD

**Issue by alexlzx** [Azure/azure-cli-extensions#6499]
### Describe the bug

I'm a PM from Azure Stream Analytics. According to this doc (https://learn.microsoft.com/en-us/cli/azure/azure-cli-extensions-list), the "az stream-analytics" command is still under experimental. How can we move this command to GA?

### Related command

az stream-analytics

### Errors

Command group 'stream-analytics' is experimental and under development.

### Issue script & Debug output

N/A

### Expected behavior

No warnning messages shown

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Extensions:
stream-analytics                   0.1.2

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\zhenxilin\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@alexlzx, what's the status now? GA or public/private Preview?

**Comment by alexlzx** [comment]
The Azure Stream Analytics service has been GA for a long time.

**Comment by jsntcy** [comment]
We can help remove the warning message this sprint (ETA: early Aug).

**Comment by alexlzx** [comment]
Just to confirm, the "az stream-analytics" command will be in GA status by this August. Is there anything else we should do?

**Comment by alexlzx** [comment]
Hi @jsntcy, is there any additional work required from our end to make it GA? Why was the command marked as experimental before?

**Comment by jsntcy** [comment]
> Hi @jsntcy Yu Chen FTE, is there any additional work required from our end to make it GA? Why was the command marked as experimental before?

No. It was marked as experimental for the first release and forgot to remove the label later.

**Comment by alexlzx** [comment]
Looping in @enkrumah 

Hi @jsntcy , any update on this?

**Comment by jsntcy** [comment]
Will release in next couple of days.
