### ISSUE TITLE
generate.py now requires an extra variable that should not be required

### ISSUE THREAD

**Issue by vilit1** [Azure/azure-cli-extensions#6515]
### Describe the bug

https://github.com/Azure/azure-cli-extensions/pull/6507/files

This pr added a variable, dependent file, which was not present before. Since this is a required variable, it is failing to run the script and breaking our builds.

I can see why this would be needed for some wheels and extensions but it is not needed for others. I can get around this by adding `-d None` to the command but this should not be necessary.

### Related command

scripts\refdoc\generate.py -e path_to_wheel

### Errors

generate.py: error: the following arguments are required: -d/--dependent-file

### Issue script & Debug output

generate.py: error: the following arguments are required: -d/--dependent-file

### Expected behavior

-d/--dependent-file should not be required.

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Extensions:
azure-iot                         0.21.4

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\repo\venv38\Scripts\python.exe'
Extensions directory 'C:\repo\extensions'

Python (Windows) 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by wangzelin007** [comment]
Hi @vilit1,
I didn't anticipate that other users would directly use our CI scripts.
I will create a pull request to fix it.
