### ISSUE TITLE
accepted-protocols docs misleading

### ISSUE THREAD

**Issue by benjamingorman** [Azure/azure-cli-extensions#670]
The docs for the `accepted-protocols` option are misleading because they suggest the arguments should be "space separated".

I would thus have expected this to work (I've omitted all the other parameters):

  az network front-door create --accepted-protocols "Http Https"

However it does not. The error message is `BadRequest - "Value 'Http Https' is not allowed for property 'Frontdoor.RoutingRules.AcceptedProtocols'"`

To get it work I actually had to provide a *comma* separated list of values.

  az network front-door create --accepted-protocols "Http,Https"
  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1b5ddd-0054-0175-b689-d20a1349bedb
* Version Independent ID: 72ccc1b6-814f-b780-99cd-ab48dfdecb66
* Content: [az network front-door](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This is a usage error. You did not provide a space-separated list. You provided a string with spaces.

Space-separated: `--accepted-protocols Http Https`
Space-separated: `--accepted-protocols "Http" "Https"`
String with space: `--accepted-protocols "Http Https"`

Comma separated values are what the service accepts. The CLI accepts space-separated values and internally converts it.

**Comment by flyingUnderTheRadar** [comment]
Leaving this as an FYI - I was not able to get the cli to work with space-separated values. Through powershell I needed to provide  `--accepted-protocols "Http,Https"` for it to work. Notice the casing as well. All other attempts to make it work failed.
