### ISSUE TITLE
Creating project fails

### ISSUE THREAD

**Issue by rikribbers** [Azure/azure-cli-extensions#672]
## Describe the bug
creating project fails. However cause is probably mine due to first attempt. However I would not expect an stack trace but a more sophisticated failure message....

**Command Name**
`az devops project create
Extension Name: azure-devops. Version: 0.7.0.`

**Errors:**
```
list index out of range
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    raise ex
cli/core/commands/__init__.py, ln 581, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azext_devops/dev/common/_credentials.py, ln 76, in _get_service_name
    return 'azdevops-cli:' + normalize_url_for_key(organization)
azext_devops/dev/common/_credentials.py, ln 85, in normalize_url_for_key
    organization_name = organization_name.split('/')[1]
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops project create --organization {} --name {} --source-control {} --visibility {}`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.63

Extensions:
azure-devops 0.7.0

```

**Comment by rikribbers** [comment]
BTW: A working command in this setup is:
az devops project create --detect on --name=test

**Comment by gauravsaralMs** [comment]
Dup of https://github.com/Azure/azure-devops-cli-extension/issues/429

**Comment by rikribbers** [comment]
duplicate so closing my issue in favour of the other
