### ISSUE TITLE
Missing Parameters in az aks create 

### ISSUE THREAD

**Issue by kasunsjc** [Azure/azure-cli-extensions#673]
I created a cluster with NetworkPolicy and aks-autoscaler enabled but I found few parameters (--enable-vmss --enable-cluster-autoscaler --min-count {} --max-count {}) not documented in the [azure aks cli doc](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create). 

## Describe the bug

**Command Name**
`az aks create
Extension Name: aks-preview. Version: 0.2.3.`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --kubernetes-version {} --generate-ssh-keys --network-plugin {} --service-cidr {} --dns-service-ip {} --docker-bridge-address {} --vnet-subnet-id {} --service-principal {} --client-secret {} --network-policy {} --enable-vmss --enable-cluster-autoscaler --min-count {} --max-count {}`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.63 *

Extensions:
aks-preview 0.2.3
resource-graph 0.1.8
interactive 0.4.2

```

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
I believe this is patched in now, closing as a result
