### ISSUE TITLE
No argument in the `az aks update` command to disable network observability (azure-cli-extension/aks-preview)

### ISSUE THREAD

**Issue by ALexAl123** [Azure/azure-cli-extensions#6740]
### Describe the bug

For testing purposes, we enabled [network-observability](https://learn.microsoft.com/en-us/azure/aks/network-observability-managed-cli?tabs=non-cilium) for our clusters. At the moment we need to disable this feature for one of the AKS in the subscription, but we do not find the corresponding argument in the `az aks update` command . 
Only the [--enable-network-observability](https://github.com/Azure/azure-cli-extensions/blob/d5d894c78832d62be35f21e3f4186c09c2a0df54/src/aks-preview/azext_aks_preview/_help.py#L234) argument is present. 
I would expect the command : `az aks update` to provide a  --disable-network-observability argument.

### Related command

az aks update

### Errors

unrecognized arguments: --disable-network-observability

### Issue script & Debug output

az aks update \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --disable-network-observability 

### Expected behavior

I would expect that ability to disable network-observability is available.

### Environment Summary

azure-cli                         2.51.0 *

core                              2.51.0 *
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

### Additional context

This will prevent our organization from starting testing and preparing the CI/CD process to implement network observability in production environments.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@ALexAl123 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ALexAl123 Could you please run the `az aks update` command without specifying the [--enable-network-observability](https://github.com/Azure/azure-cli-extensions/blob/d5d894c78832d62be35f21e3f4186c09c2a0df54/src/aks-preview/azext_aks_preview/_help.py#L234) argument and check if that helps. Awaiting your reply.

**Comment by snguyen64** [comment]
Hi @ALexAl123 

Is there any feedback or reason for disabling kappie feature?

As of this moment, only –enable-network-observability is added to the aks preview cli. disable-network-observability is not added to the aks preview cli yet.
If we use helm to uninstall aks-managed-kappie, it will be reconciled by aks and installed again. To uninstall kappie at the moment, we would make an api call to the aks api to update the managed cluster and disable monitoring in the network profile
[Managed Clusters - Create Or Update - REST API (Azure AKS) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?tabs=HTTP)

This snippet only includes the relevant field for the payload when disabling network observability using the api. Also note the api version must atleast be 2023-05-02-preview
`
{
    “properties”: {
        “networkProfile”: {
            “monitoring”: {
                “enabled”: false
            }
        }
    }
}
`

**Comment by navba-MSFT** [comment]
@ALexAl123 Please let us know if you had a chance to look at the [above comment](https://github.com/Azure/azure-cli-extensions/issues/6740#issuecomment-1735675205). Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ALexAl123 I hope you had a chance to look at the [above comment](https://github.com/Azure/azure-cli-extensions/issues/6740#issuecomment-1735675205). If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by ALexAl123** [comment]
Hi @navba-MSFT 
I'm sorry to be late with the reply.
I tested the REST_API call you suggested.
Network observability has been successfully disabled.
Thanks for your support.
