### ISSUE TITLE
az interactive` fails with CLI 2.0.64

### ISSUE THREAD

**Issue by bonillajose** [Azure/azure-cli-extensions#677]
I am running into an issue with this interactive shell. I successfully updated it before running it and installed the most recent azure-cli version 2.0.64.

azure-cli 2.0.64
Extensions:
interactive 0.4.2

When I ran the az interactive command, the interactive shell shows briefly then it closes.

az>>
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x041AF738>, <function _x509_from_base64_to_hex_transform at 0x041AF780>]
Event: CommandInvoker.OnFilterResult []
Event: Cli.PostExecute []
az_command_data_logger : exit code: 0

**Comment by tjprescott** [comment]
I have repro'd this and it is indeed a bug. `--debug` does not provide much useful additional information.

**Comment by tjprescott** [comment]
Downgrading to knack 0.5.4 fixes the issue for me (`pip install knack==0.5.4`). @limingu please update the extension to work with the latest version of knack.

**Comment by bonillajose** [comment]
Tj what for Windows, I am having the same issue.

**Comment by tjprescott** [comment]
If you installed using a packaged installer, I don't believe there is a workaround (@marstr correct me if I'm wrong). @limingu is working on a fix which will be released ASAP.

**Comment by marstr** [comment]
@bonillajose, @tjprescott

It's a bit of a hack, but you could run the following:

``` PowerShell
"C:\Program Files\Microsoft SDKs\Azure\CLI2\Bin\python.exe" -m pip install --force-reinstall knack==0.5.4
```
