### ISSUE TITLE
Various resource create/update parameter bugs in 'virtual-network-manager' extension.

### ISSUE THREAD

**Issue by jago2136** [Azure/azure-cli-extensions#6786]
### Describe the bug

There are parameters which should be marked as required in the virtual-network-manager commands. There are also several update params being offered, which are not update-able. 

Also, our external documentation states some of the commands required parameters, but for many it does **not**. Can you make the documentation uniform for required params? https://learn.microsoft.com/en-us/cli/azure/network/manager?view=azure-cli-latest

### Related command

**az network manager scope-connection create** 
This command does not mark 'tenant-id' or 'resource-id' as required arguments. Please make them required and update the help message.

**az network manager scope-connection update**
Arguments --resource-id and --tenant-id are not updateable and should not be allowed in this update command. Please update the help message as well.

**az network manager connection subscription create** 
Argument --network manager is a required parameter. Please also update help message.

**az network manager connection subscription update**
Argument --network-manager is not update-able. Please remove from allowed params and update help message.

**az network manager connection management-group create**
Network manager id is a required property. Please also update help message.

**az network manager connection management-group update**
Argument --network-manager is not update-able. Please remove from allowed params and update help message.

**az network manager group static-member create**
Argument --resource-id is a required parameter. Please also update help message.

### Errors

N/A, well described above

### Issue script & Debug output

N/A, well described above

### Expected behavior

N/A, well described above

### Environment Summary

azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Extensions:
account                            0.2.5
azure-devops                      0.26.0
virtual-network-manager             1.0.0b2

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\jaredgorthy\.azure\cliextensions'
Development extension sources:
    C:\CLI_test\azure-cli-extensions

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
