### ISSUE TITLE
VM Developer image Artifact download

### ISSUE THREAD

**Issue by Acherreve** [Azure/azure-cli-extensions#679]
## Describe the bug

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.8.0.`

**Errors:**
```
_sigint_handler() takes 1 positional argument but 3 were given
Traceback (most recent call last):
pip-install-v1m4qsu_\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 560, in execute
cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
cli\core\commands\__init__.py, ln 609, in _run_job
...
azext_devops\dev\common\external_tool.py, ln 74, in run
    line = bline.decode('utf-8', 'ignore').strip()
TypeError: _sigint_handler() takes 1 positional argument but 3 were given
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --organization {} --feed {} --version {} --name {} --path {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.64

Extensions:
azure-devops 0.8.0

```

**Comment by gauravsaralMs** [comment]
@geverghe : Any idea how this can be routed to artifacts team?

cc: @snankani

**Comment by geverghe** [comment]
@elbatk - Could you guys have a look at this?

**Comment by atbagga** [comment]
Closing this issue in favor of tracking it in the azure-devops extension repo. 
Please see https://github.com/Azure/azure-devops-cli-extension/issues/831 for updates.
