### ISSUE TITLE
Should not import Wheel.Install in test_index.py

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-cli-extensions#6835]
### Describe the bug

There is an issue with PR checklist command `python scripts/ci/test_index.py -q`. The script should not import Wheel.Install in test_index.py as Wheel does not have a public API. There is a "regression" in newer Wheel versions after `0.30.0` where `test_index.py` breaks with the following error:
```
Traceback (most recent call last):
  File "C:\tasks\TheOnlyWei\azure-cli-extensions\scripts\ci\test_index.py", line 23, in <module>
    from wheel.install import WHEEL_INFO_RE
ModuleNotFoundError: No module named 'wheel.install'
```

Researched this issue, and here is the official Wheel team response:
> As wheel does not have a public API, the developers are not responsible for any breakage caused by internal refactoring. I suggest that you copy the regex to your own app.
https://github.com/pypa/wheel/issues/235

Code with the issue:
https://github.com/Azure/azure-cli-extensions/blob/17c726f5e2770597224a5e48700672f9f5888113/scripts/ci/test_index.py#L23C24-L23C24

### Related command

`python scripts/ci/test_index.py -q`

### Errors
```
Traceback (most recent call last):
  File "C:\tasks\TheOnlyWei\azure-cli-extensions\scripts\ci\test_index.py", line 23, in <module>
    from wheel.install import WHEEL_INFO_RE
ModuleNotFoundError: No module named 'wheel.install'
```
### Issue script & Debug output

No debug needed for this command

### Expected behavior

Should not throw an error.

### Environment Summary

```
azure-cli                         2.40.0 *

core                              2.40.0 *
telemetry                          1.0.8 *

Extensions:
account                            0.2.5
arca-extension                     0.0.1
azure-devops                      0.26.0
customlocation                     0.1.3
k8s-configuration                  1.7.0
k8s-extension                      1.4.5
sandbox                            0.0.1
connectedk8s                       1.5.2 (dev) C:\tasks\TheOnlyWei\azure-cli-extensions\src\connectedk8s
k8s-configuration                  1.5.1 (dev) C:\tasks\TheOnlyWei\azure-cli-extensions\src\k8s-configuration
k8s-extension                      1.3.5 (dev) C:\tasks\TheOnlyWei\azure-cli-extensions\src\k8s-extension
storage-blob-preview               0.6.1 (dev) C:\tasks\TheOnlyWei\azure-cli-extensions\src\storage-blob-preview

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\weshi1\.azure\cliextensions'
Development extension sources:
    C:\tasks\TheOnlyWei\azure-cli-extensions

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 3 update(s) available. Consider updating your CLI installation with 'az upgrade'
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by wangzelin007** [comment]
@TheOnlyWei,
Thank you for providing the information. We have permanently [pinned wheel to version 0.3.0](https://github.com/Azure/azure-cli-extensions/blob/d15ef627aa596879add5bc6624fcb8657946ffc5/azure-pipelines.yml#L96) due to another issue: [wheel no longer contains metadata.json after version 0.3.0](https://github.com/pypa/wheel/issues/195)

We do not recommend running tests on CI locally. 
If you really need to do this, please refer to the corresponding configuration in [azure-pipelines.yml](https://github.com/Azure/azure-cli-extensions/blob/d15ef627aa596879add5bc6624fcb8657946ffc5/azure-pipelines.yml).

**Comment by TheOnlyWei** [comment]
@wangzelin007 The PR template also ask developers to run `python scripts/ci/test_index.py -q`, but it doesn't tell them what version to use, which was the reason I created this issue.
