### ISSUE TITLE
 az login --mls Fails 

### ISSUE THREAD

**Issue by sqlshep** [Azure/azure-cli-extensions#684]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

No one is addressing this and it continues to happen, the instructions in the following git issue do not work.  i need a resolution.  I have a fresh install of ML Server 9.3 on four servers i am trying to setup in an Enterprise configuration, and this fails on all nodes. 

https://github.com/Azure/azure-cli-extensions/issues/125

### Extension name (the extension in question)
az login --mls

### Description of issue (in as much detail as possible)

PS C:\Users\adminuser> az login --mls
az : WARNING: The behavior of this command has been altered by the following extension: 
azure-ml-admin-cli

At line:1 char:1
 az login --mls
 ~~~~~~~~~~~~~~
 CategoryInfo          : NotSpecified: (WARNING: The be...re-ml-admin-cli:String) [], RemoteException
 FullyQualifiedErrorId : NativeCommandError
-----

**Comment by yonzhan** [comment]
ml

**Comment by SaurabhSharma-MSFT** [comment]
@sqlshep Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So, wanted to check if you are still looking for assistance on this query? Please let us know.

**Comment by sqlshep** [comment]
> @sqlshep Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So, wanted to check if you are still looking for assistance on this query? Please let us know.

Whatever the issue was I moved on.

**Comment by SaurabhSharma-MSFT** [comment]
@sqlshep Thanks for the confirmation. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
