### ISSUE TITLE
az artifacts universal download (ArtifactTool) fails on windows 10 pc with company proxy

### ISSUE THREAD

**Issue by clowtown** [Azure/azure-cli-extensions#686]
## Describe the bug
Attempting to download universal package times out and does not appear to be using environment variables. AZ can sucessfully add the extension and do other web requests, but when ArtifactTool is getting invoked it appears to be timing out. 
Various proxy environment variables are set for a variety of tooling requirements:
![image](https://user-images.githubusercontent.com/6283944/57715935-733d7180-763d-11e9-8574-636eb4701cf6.png)

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.8.0.`

**Errors:**
```
Encountered an unexpected error.
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

...
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 130
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --debug --organization {} --feed {} --name {} --version {} --path {}`

## Expected Behavior
Artifact is downloaded.

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.64

Extensions:
azure-devops 0.8.0

```

**Comment by gauravsaralMs** [comment]
@geverghe : Any idea how this can be routed to artifacts team?

cc: @snankani

**Comment by atbagga** [comment]
Closing this issue in favor of tracking it in the azure-devops extension repo. 
Please see https://github.com/Azure/azure-devops-cli-extension/issues/830 for updates.
