### ISSUE TITLE
az containerapp env certificate list fails with "ERROR: unrecognized arguments: --managed-certificates-only"

### ISSUE THREAD

**Issue by m42jbz** [Azure/azure-cli-extensions#6879]
### Describe the bug

The following powershell script is run right after updating a containerapp and fails on a Microsoft hosted agent, but runs fine locally, both on Linux and Windows:

```powershell
$containerapp = az containerapp list --query "[?name=='<CONTAINERAPP_NAME>']" `
  | ConvertFrom-Json `
  | Select-Object -First 1

$containerappenv = az containerapp env show --id $containerapp.properties.environmentId | ConvertFrom-Json

$customdomaincert = az containerapp env certificate list --managed-certificates-only --name $containerappenv.name --resource-group $containerappenv.resourceGroup `
  | ConvertFrom-Json `
  | Select-Object -First 1

az containerapp hostname bind `
  --hostname $customdomaincert.properties.subjectName `
  -g $customdomaincert.resourceGroup `
  -n $containerapp.name `
  --environment $containerappenv.name `
  --validation-method CNAME
```

The script is a workaround related to https://github.com/microsoft/azure-container-apps/issues/607

### Related command

az containerapp

### Errors

ERROR: unrecognized arguments: --managed-certificates-only

### Issue script & Debug output

omitted

### Expected behavior

The commands run successfully.

### Environment Summary

azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.10.10 (main, Sep 20 2023, 06:07:38) [GCC 11.4.0]

### Additional context

The script began failing sporadically around Oct 5th, and now is failing consistently since Oct 18th.
It is executed on a Microsoft hosted Azure DevOps build agent, running Ubuntu:

Current agent version: '3.227.2'
Operating System
Ubuntu
22.04.3
LTS
Runner Image
Image: ubuntu-22.04
Version: 20231016.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231016.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231016.1
Runner Image Provisioner
2.0.312.1
Current image version: '20231016.1.0'

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Greedygre** [comment]
Hi @m42jbz 

Argument `--managed-certificates-only` only support in `containerapp` extension.
You can use `az extension add -n containerapp` to install the extension.

**Comment by m42jbz** [comment]
@Greedygre Thank you very much! That solved it for me. I still wonder why it worked before without installing the extension. Was the extension auto-installed previously, which is not happening anymore for some reason?

Our logs show that this was happening up until Oct 18th (as mentioned above):

```log
2023-10-18T07:01:42.1304405Z WARNING: The command requires the extension containerapp. It will be installed first.
2023-10-18T07:01:51.9468839Z WARNING: The installed extension 'containerapp' is in preview.
2023-10-18T07:02:01.5397231Z WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
```
