### ISSUE TITLE
Unable to enable virtual node on existing cluster

### ISSUE THREAD

**Issue by ghost** [Azure/azure-cli-extensions#694]
## Describe the bug

**Command Name**
`az aks enable-addons
Extension Name: aks-preview. Version: 0.4.2.`

**Errors:**
```
'logAnalyticsWorkspaceResourceID'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 560, in execute
    raise ex
cli/core/commands/__init__.py, ln 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 611, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1274, in aks_enable_addons
    _ensure_container_insights_for_monitoring(cmd, instance.addon_profiles['omsagent'])
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 975, in _ensure_container_insights_for_monitoring
    workspace_resource_id = addon.config['logAnalyticsWorkspaceResourceID']
KeyError: 'logAnalyticsWorkspaceResourceID'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --resource-group {} --name {} --addons {} --subnet-name {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64

Extensions:
aks-preview 0.4.2

```

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
@accu-joeykarns can you post the exact command you ran with the full error output?

**Comment by navba-MSFT** [comment]
@ghost @accu-joeykarns Apologies for the late reply. If your ask is to enable the Virtual node in AKS cluster using Azure CLI you need to follow [this](https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli#before-you-begin) article. If you would like to enable the LogAnalytics addon to your AKS cluster then follow [this](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-enable-existing-clusters#enable-using-azure-cli) article. This github thread is open for quite sometime now. Please let us know if you need any further assistance on this. Awaiting your reply.
