### ISSUE TITLE
az build list fails

### ISSUE THREAD

**Issue by idjohnson** [Azure/azure-cli-extensions#697]
## Describe the bug

**Command Name**
`az pipelines build list
Extension Name: azure-devops. Version: 0.4.0.`

**Errors:**
```
list index out of range
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 560, in execute
    raise ex
cli/core/commands/__init__.py, ln 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 609, in _run_job
    cmd_copy.exception_handler(ex)
...
azext_devops/dev/common/_credentials.py, ln 24, in _get_credential
    key = _get_service_name(organization)
azext_devops/dev/common/_credentials.py, ln 76, in _get_service_name
    return 'azdevops-cli:' + normalize_url_for_key(organization)
azext_devops/dev/common/_credentials.py, ln 85, in normalize_url_for_key
    organization_name = organization_name.split('/')[1]
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az pipelines build list --org {} --project {}`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64 *

Extensions:
aks-preview 0.2.3
azure-devops 0.4.0

```

**Comment by idjohnson** [comment]
Note: specified org and project. Generated new full access token just in case it was security scoping.
updated to latest CLI first.

**Comment by gauravsaralMs** [comment]
Looks Dup of : https://github.com/Azure/azure-devops-cli-extension/issues/429

cc: @snankani  @geverghe

**Comment by idjohnson** [comment]
retried on windows 10 laptop; 

`H:\>az --version
azure-cli                         2.0.62 *

acr                                2.2.4 *
acs                               2.3.21 *
advisor                            2.0.0
ams                                0.4.4 *
appservice                        0.2.17 *
backup                             1.2.3 *
batch                              4.0.0 *
batchai                            0.4.8 *
billing                            0.2.1
botservice                        0.1.10 *
cdn                                0.2.2 *
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.21 *
consumption                        0.4.2 *
container                         0.3.16 *
core                              2.0.62 *
cosmosdb                           0.2.9 *
dla                                0.2.5
dls                                0.1.8 *
dms                                0.1.3
eventgrid                          0.2.2 *
eventhubs                          0.3.4 *
extension                          0.2.5
feedback                           2.2.0 *
find                               0.3.2 *
hdinsight                          0.3.3 *
interactive                        0.4.3 *
iot                                0.3.7 *
iotcentral                         0.1.6
keyvault                          2.2.14 *
kusto                              0.2.2
lab                                0.1.6 *
maps                               0.3.4
monitor                           0.2.12 *
network                            2.3.6 *
nspkg                              3.0.3
policyinsights                     0.1.2 *
privatedns                         1.0.0 *
profile                            2.1.5
rdbms                              0.3.9 *
redis                              0.4.2 *
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.13 *
role                               2.5.0 *
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4 *
servicefabric                     0.1.16 *
signalr                            1.0.0
sql                                2.2.1 *
sqlvm                              0.1.1
storage                            2.4.0 *
telemetry                          1.0.2
vm                                2.2.18 *

Extensions:
azure-devops                       0.4.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\johnsi10\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 38 updates available. Consider updating your CLI installation.`

az pipelines build list --organization https://dev.azure.com/mdtcrhf --project CRHFSoftware

command completes fine..

move to ubuntu instance. running 2.0.62, installed fresh extension 0.8.0
command completes fine.



updating to az cli 2.0.65 on windows 10.
Running 2.0.65 with azure-devops extension 0.4.0 -- succeeds

updated extension to 0.8.0 -- succeeds

I retraced my notes and indeed I was trying to invoke with a short name, not a URL:

az pipelines build list --org mdtcrhf --project "CRHFSoftware"

Please consider this resolved - pebkac error.
