### ISSUE TITLE
timespan parameter

### ISSUE THREAD

**Issue by MaameAJ** [Azure/azure-cli-extensions#699]
There's no information on this page as to how to format the string in order to specify the format. There's no mention of a standard or link to a page to breakdown ' P3DT12H' what it means or what it is. I tried to google to see if this is any specific standard but was unable to find any helpful documentation. Please clarify the formatting of this string and what formatting this parameter is looking for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0fd6a58-ac1a-fa45-8d96-579b4af36499
* Version Independent ID: 4098ca97-1b85-eb29-18e9-e6f0495fd030
* Content: [az monitor log-analytics](https://docs.microsoft.com/en-us/cli/azure/ext/log-analytics/monitor/log-analytics?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by alexeldeib** [comment]
The parameter is an ISO8601 duration (https://en.wikipedia.org/wiki/ISO_8601#Durations). `P3DT12H` would be querying the [p]ast 3 days and 12 hours of data from the current datetime. The format is effectively:
```
P[YYYY]-[MM]-[DD]T[hh]:[mm]:[ss]
```

@tjprescott I recall when doing the App Insights extension, this was called out as not following best practice. I think the preferred method was start/stop/offset, like we did [here](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights?view=azure-cli-latest#ext-application-insights-az-monitor-app-insights-query). Is that accurate? 

I can update the timespan implementation and bump the version + update docs. If this implementation is ok, I'll still PR a doc update.

**Comment by tjprescott** [comment]
@alexeldeib you could do something like start/stop/offset. It might also be just as adequate to use the `azure.cli.core.commands.parameters.get_datetime_type` helper, which will accept raw ISO 8601 or more user-friendly formats.

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
Closed this issue since it's a question and has been answered. Feel free to reopen it if you still encounter this issue.
