### ISSUE TITLE
Possible to edit?

### ISSUE THREAD

**Issue by johnwildes** [Azure/azure-cli-extensions#700]
I'm guessing because this is an in development extension of the CLI and not a root module, and that's why there's no ability to edit it?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9e855a-abc5-14d9-ba73-4ab527ffee16
* Version Independent ID: 85a46540-4b25-94f4-2c0e-29e1f8fefe35
* Content: [az devops](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops?view=azure-cli-latest#ext-azure-devops-az-devops-invoke)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by gauravsaralMs** [comment]
@johnwildes : DevOps extension is present at https://github.com/Azure/azure-devops-cli-extension
you contribute to the code there (and also examples, help text ect)., although documentation is self generated

cc: @snankani

**Comment by atbagga** [comment]
@tjprescott  this can be closed.
