### ISSUE TITLE
az monitor data-collection rule create with rule.json succeeds, but rule created is buggy.

### ISSUE THREAD

**Issue by peienluo** [Azure/azure-cli-extensions#7096]
### Describe the bug

In short, the created rule does not have the dataCollectionEndpointId passed in the json file.

### Related command

az monitor data-collection rule create

### Errors

The command succeeds, but the rule created is buggy (missing dataCollectionEndpointId)

### Issue script & Debug output

$ cat dcr_temp.json
{
  "location": "WestUS3",
  "properties": {
    "dataCollectionEndpointId": "/subscriptions/b09d4a2d-699b-4c76-8c7a-d97165a77a3b/resourceGroups/peluo_strato_test_rg1/providers/Microsoft.Insights/dataCollectionEndpoints/stratotmpdce",
    "streamDeclarations": {
      "Custom-peluotmptable_CL": {
        "columns": [
          {
            "name": "Body",
            "type": "string"
          },
          {
            "name": "TimeGenerated",
            "type": "datetime"
          },
          {
            "name": "SeverityText",
            "type": "string"
          }
        ]
      }
    },
    "dataSources": {},
    "destinations": {
      "logAnalytics": [
        {
          "workspaceResourceId": "/subscriptions/b09d4a2d-699b-4c76-8c7a-d97165a77a3b/resourcegroups/peluo_strato_test_rg1/providers/microsoft.operationalinsights/workspaces/peluotmplaw",
          "name": "peluotmplaw"
        }
      ]
    },
    "dataFlows": [
      {
        "streams": [
          "Custom-peluotmptable_CL"
        ],
        "destinations": [
          "peluotmplaw"
        ],
        "transformKql": "source",
        "outputStream": "Custom-peluotmptable_CL"
      }
    ]
  }
}

$ az monitor data-collection rule create --resource-group ${RESOURCE_GROUP} --location ${LOCATION} --name ${DCR_NAME} --rule-file ./dcr_temp.json
{
  "dataCollectionEndpointId": null,
  "dataFlows": [
    {
      "destinations": [
        "peluotmplaw"
      ],
      "outputStream": "Custom-peluotmptable_CL",
      "streams": [
        "Custom-peluotmptable_CL"
      ],
      "transformKql": "source"
    }
  ],
  "dataSources": {
    "extensions": null,
    "iisLogs": null,
    "logFiles": null,
    "performanceCounters": null,
    "syslog": null,
    "windowsEventLogs": null
  },
  "description": null,
  "destinations": {
    "azureMonitorMetrics": null,
    "logAnalytics": [
      {
        "name": "peluotmplaw",
        "workspaceId": "f60bfccb-1813-4d94-aa20-d60010c10def",
        "workspaceResourceId": "/subscriptions/b09d4a2d-699b-4c76-8c7a-d97165a77a3b/resourcegroups/peluo_strato_test_rg1/providers/microsoft.operationalinsights/workspaces/peluotmplaw"
      }
    ]
  },
  "etag": "\"00002713-0000-4d00-0000-658003ff0000\"",
  "id": "/subscriptions/b09d4a2d-699b-4c76-8c7a-d97165a77a3b/resourceGroups/peluo_strato_test_rg1/providers/Microsoft.Insights/dataCollectionRules/peluotmpdcr",
  "immutableId": "dcr-a7f02ae4c25c468abb34d4e62fbbb08e",
  "kind": null,
  "location": "WestUS3",
  "metadata": null,
  "name": "peluotmpdcr",
  "provisioningState": "Succeeded",
  "resourceGroup": "peluo_strato_test_rg1",
  "streamDeclarations": null,
  "systemData": {
    "createdAt": "2023-12-18T08:34:04.841708+00:00",
    "createdBy": "***",
    "createdByType": "User",
    "lastModifiedAt": "2023-12-18T08:34:04.841708+00:00",
    "lastModifiedBy": "***",
    "lastModifiedByType": "User"
  },
  "tags": null,
  "type": "Microsoft.Insights/dataCollectionRules"
}

### Expected behavior

The rule created having the data collection endpoint.

### Environment Summary

azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
connectedk8s                       1.5.2
k8s-extension                      1.5.2
monitor-control-service               0.4.1

**Comment by AllyW** [comment]
@peienluo for now, `az monitor data-collection rule create` does not support datacollectionendpointid now. and we are upgrading our code base to support it.

**Comment by hazcod** [comment]
@AllyW Sorry for commenting here, but i'm still unable to do so and ` az monitor data-collection rule association create` returns `Association cannot be created for resource of type Microsoft.Insights/dataCollectionEndpoints`.
