### ISSUE TITLE
Add support for VB and F# projects in az webapp up

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli-extensions#71]
### Extension name (the extension in question)
webapp

### Description of issue (in as much detail as possible)
`az webapp new` currently only looks for `*.csproj` to determine if it's a .NET project. It should also look for `*.vbproj` and `*.fsproj`.

**Comment by panchagnula** [comment]
@anthonychu  i am not closing this since these are languages that we are currently not planning on supporting
