### ISSUE TITLE
Attempt to copy image fails

### ISSUE THREAD

**Issue by scarolan** [Azure/azure-cli-extensions#733]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
image-copy-extension

### Description of issue (in as much detail as possible)
The command doesn't work at all.  I'm following your tutorial here:
https://www.microsoft.com/developerblog/2018/02/15/copy-custom-vm-images-on-azure/

Here's the command I ran:
az image copy --source-resource-group se-training-lab --source-object-name hc-training-workstation-2019-05-30 --target-location uksouth --target-resource-group "emea-training-lab" --cleanup

And here's the error message:

```
Getting os disk id of the source vm/image
Creating source snapshot
command failed: ['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'hc-training-workstation-2019-05-30_os_disk_snapshot', '--resource-group', 'se-training-lab', '--source', '/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/se-training-lab-newhcimage000-963909/providers/Microsoft.Compute/disks/newhcimage000_disk1_e20e8b03612a4a20ab199c5692c855fc', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ERROR: Resource newhcimage000_disk1_e20e8b03612a4a20ab199c5692c855fc is not found.

The command failed with an unexpected error. Here is the traceback:

Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'hc-training-workstation-2019-05-30_os_disk_snapshot', '--resource-group', 'se-training-lab', '--source', '/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/se-training-lab-newhcimage000-963909/providers/Microsoft.Compute/disks/newhcimage000_disk1_e20e8b03612a4a20ab199c5692c855fc', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 611, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 588, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 297, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 461, in default_command_handler
    return op(**command_args)
  File "/home/scarolan/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 82, in imagecopy
    run_cli_command(cli_cmd)
  File "/home/scarolan/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 35, in run_cli_command
    raise ex
  File "/home/scarolan/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/opt/az/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'hc-training-workstation-2019-05-30_os_disk_snapshot', '--resource-group', 'se-training-lab', '--source', '/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/se-training-lab-newhcimage000-963909/providers/Microsoft.Compute/disks/newhcimage000_disk1_e20e8b03612a4a20ab199c5692c855fc', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.

To open an issue, please run: 'az feedback'
```

**Comment by tamirkamara** [comment]
Hi @scarolan,
Is the disk of the VM used to create the image still exists? As documented in the post you linked in the issue and in the help text, this is essential for the copy operation to work...

**Comment by rdouyere** [comment]
Hi, 
I run into the same issue. The disk does not exists anymore because the image is created using "Azure Image Builder (Preview)" which deletes all the resources. Is there a way to have both tools working together ?
Thanks

**Comment by scarolan** [comment]
My goal is simply to be able to copy Dev/Test Custom Images from one region to another.  As far as I can tell these are just "regular" disk images, with some extra API scaffolding around them.

Please fix the image copy command so it works with images created in dev/test labs.

**Comment by tamirkamara** [comment]
@rdouyere - I don't know this tool, and it's on private preview. I'd suggest you check all options there and see if it is possible to retain the resources used to create the image.
@scarolan - as stated before, it is a requirement of the extension to access the disk (or other underlining resource). There's however, a newer "native" approach to copy images on azure - [Shared Image Gallery](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/shared-image-galleries). I think you should check it out.

**Comment by mreid-contrast** [comment]
I'll add to the mix though I'll need to find a quicker workaround than is probably available via this thread. I want to echo the original sentiment though in a constructive manner: "This command doesn't work at all". Or, at least, I don't see what the happy path is.

1. I have an image. 
2. I have the original, generalized VM. 
3. I have the OS disk.
4. This command does not work for me.

If there is subtle, additional requirement for this command to work correctly, it's not clear to me what that requirement is.

command failed: ['/usr/local/Cellar/azure-cli/2.0.72_1/libexec/bin/python', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'azdevdemo-image-20190924_os_disk_snapshot', '--resource-group', 'sales-engineering-demo', '--source', '/subscriptions/4352f0e7-67db-4001-8352-25147175ee02/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/disks/azdevdemo_disk1_ce217e1695df4615af8822334caf2799', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ERROR: Resource azdevdemo_disk1_ce217e1695df4615af8822334caf2799 is not found.


![Screen Shot 2019-09-25 at 8 15 51 AM](https://user-images.githubusercontent.com/54084761/65599880-dd134380-df6c-11e9-9611-7c6d6267ee2f.png)
![Screen Shot 2019-09-25 at 8 16 22 AM](https://user-images.githubusercontent.com/54084761/65599881-dd134380-df6c-11e9-93ee-69824f0e17b4.png)
![Screen Shot 2019-09-25 at 8 16 39 AM](https://user-images.githubusercontent.com/54084761/65599882-dd134380-df6c-11e9-9cc3-9b8c2df82198.png)

**Comment by tamirkamara** [comment]
@mreid-contrast can you please the command with the --debug flag and report back with the output? Make sure to remove secrets

**Comment by mreid-contrast** [comment]
Thanks for your response. Here you go:


az image copy --source-resource-group sales-engineering-demo --source-object-name azdevdemo-image-20190924             --target-location eastus --target-resource-group "sales-engineering-demo" --cleanup --debug > output.txt 2>&1


DEBUG: Command arguments: ['image', 'copy', '--source-resource-group', 'sales-engineering-demo', '--source-object-name', 'azdevdemo-image-20190924', '--target-location', 'eastus', '--target-resource-group', 'sales-engineering-demo', '--cleanup', '--debug']
DEBUG: Event: Cli.PreExecute []
DEBUG: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x105ccd560>, <function OutputProducer.on_global_arguments at 0x105d99170>, <function CLIQuery.on_global_arguments at 0x105dc6d40>]
DEBUG: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
DEBUG: Loaded module 'acr' in 0.003 seconds.
DEBUG: Loaded module 'acs' in 0.005 seconds.
DEBUG: Loaded module 'advisor' in 0.001 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'ams' in 0.011 seconds.
DEBUG: Loaded module 'apim' in 0.001 seconds.
DEBUG: Loaded module 'appconfig' in 0.002 seconds.
DEBUG: Loaded module 'appservice' in 0.006 seconds.
DEBUG: Loaded module 'backup' in 0.002 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'batch' in 0.007 seconds.
DEBUG: Loaded module 'batchai' in 0.002 seconds.
DEBUG: Loaded module 'billing' in 0.001 seconds.
DEBUG: Loaded module 'botservice' in 0.002 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'cdn' in 0.002 seconds.
DEBUG: Loaded module 'cloud' in 0.001 seconds.
DEBUG: Loaded module 'cognitiveservices' in 0.001 seconds.
DEBUG: Loaded module 'configure' in 0.001 seconds.
DEBUG: Loaded module 'consumption' in 0.002 seconds.
DEBUG: Loaded module 'container' in 0.001 seconds.
DEBUG: Loaded module 'cosmosdb' in 0.004 seconds.
DEBUG: Loaded module 'deploymentmanager' in 0.002 seconds.
DEBUG: Loaded module 'dla' in 0.004 seconds.
DEBUG: Loaded module 'dls' in 0.002 seconds.
DEBUG: Loaded module 'dms' in 0.001 seconds.
DEBUG: Loaded module 'eventgrid' in 0.002 seconds.
DEBUG: Loaded module 'eventhubs' in 0.002 seconds.
DEBUG: Loaded module 'extension' in 0.001 seconds.
DEBUG: Loaded module 'feedback' in 0.000 seconds.
DEBUG: Loaded module 'find' in 0.001 seconds.
DEBUG: Loaded module 'hdinsight' in 0.002 seconds.
DEBUG: Loaded module 'interactive' in 0.000 seconds.
DEBUG: Loaded module 'iot' in 0.003 seconds.
DEBUG: Loaded module 'iotcentral' in 0.001 seconds.
DEBUG: Loaded module 'keyvault' in 0.003 seconds.
DEBUG: Loaded module 'kusto' in 0.002 seconds.
DEBUG: Loaded module 'lab' in 0.002 seconds.
DEBUG: Loaded module 'managedservices' in 0.001 seconds.
DEBUG: Loaded module 'maps' in 0.001 seconds.
DEBUG: Loaded module 'monitor' in 0.004 seconds.
DEBUG: Loaded module 'natgateway' in 0.001 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'netappfiles' in 0.003 seconds.
DEBUG: Loaded module 'network' in 0.020 seconds.
DEBUG: Loaded module 'policyinsights' in 0.001 seconds.
DEBUG: Loaded module 'privatedns' in 0.003 seconds.
DEBUG: Loaded module 'profile' in 0.001 seconds.
DEBUG: Loaded module 'rdbms' in 0.004 seconds.
DEBUG: Loaded module 'redis' in 0.002 seconds.
DEBUG: Loaded module 'relay' in 0.002 seconds.
DEBUG: Loaded module 'reservations' in 0.001 seconds.
DEBUG: Loaded module 'resource' in 0.004 seconds.
DEBUG: Loaded module 'role' in 0.003 seconds.
DEBUG: Loaded module 'search' in 0.001 seconds.
DEBUG: Loaded module 'security' in 0.002 seconds.
DEBUG: Loaded module 'servicebus' in 0.004 seconds.
DEBUG: Loaded module 'servicefabric' in 0.001 seconds.
DEBUG: Loaded module 'signalr' in 0.001 seconds.
DEBUG: Loaded module 'sql' in 0.004 seconds.
DEBUG: Loaded module 'sqlvm' in 0.001 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'storage' in 0.020 seconds.
DEBUG: Loaded module 'vm' in 0.012 seconds.
DEBUG: Loaded all modules in 0.184 seconds. (note: there's always an overhead with the first module loaded)
DEBUG: Extensions directory: '<path_to>/.azure/cliextensions'
DEBUG: Found 2 extensions: ['azure-devops', 'image-copy-extension']
DEBUG: Extensions directory: '<path_to>/.azure/cliextensions'
DEBUG: Extension compatibility result: is_compatible=True cli_core_version=2.0.72 min_required=2.0.49 max_required=None
DEBUG: Extensions directory: '<path_to>/.azure/cliextensions'
DEBUG: Loaded extension 'azure-devops' in 0.018 seconds.
DEBUG: Extensions directory: '<path_to>/.azure/cliextensions'
DEBUG: Extension compatibility result: is_compatible=True cli_core_version=2.0.72 min_required=2.0.24 max_required=None
DEBUG: Extensions directory: '<path_to>/.azure/cliextensions'
DEBUG: Loaded extension 'image-copy-extension' in 0.001 seconds.
DEBUG: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x105df7200>]
INFO: az_command_data_logger : command args: image copy --source-resource-group {} --source-object-name {} --target-location {} --target-resource-group {} --cleanup --debug
DEBUG: metadata file logging enabled - writing logs to '<path_to>/.azure/commands'.
DEBUG: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x105e77c20>]
DEBUG: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x105eb1c20>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x105eb1e60>]
DEBUG: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x106df49e0>]
DEBUG: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x105d99200>, <function CLIQuery.handle_query_parameter at 0x105dc6dd0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x105eb1cb0>, <function handler at 0x106f618c0>, <function DevCommandsLoader.post_parse_args at 0x10790dd40>]
DEBUG: Extensions directory: '<path_to>/.azure/cliextensions'
DEBUG: Extensions directory: '<path_to>/.azure/cliextensions'
INFO: az_command_data_logger : extension name: image-copy-extension
INFO: az_command_data_logger : extension version: 0.2.1
WARNING: Getting os disk id of the source vm/image
DEBUG: command: ['/usr/local/Cellar/azure-cli/2.0.72_1/libexec/bin/python', '-m', 'azure.cli', 'image', 'show', '--name', 'azdevdemo-image-20190924', '--resource-group', 'sales-engineering-demo', '--output', 'json'] ended with output: {
  "hyperVgeneration": "V1",
  "id": "/subscriptions/<subscription_id>/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/images/azdevdemo-image-20190924",
  "location": "eastus2",
  "name": "azdevdemo-image-20190924",
  "provisioningState": "Succeeded",
  "resourceGroup": "sales-engineering-demo",
  "sourceVirtualMachine": {
    "id": "/subscriptions/<subscription_id>/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/virtualMachines/azdevdemo",
    "resourceGroup": "sales-engineering-demo"
  },
  "storageProfile": {
    "dataDisks": [],
    "osDisk": {
      "blobUri": null,
      "caching": "ReadWrite",
      "diskSizeGb": 127,
      "managedDisk": {
        "id": "/subscriptions/<subscription_id>/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/disks/azdevdemo_disk1_ce217e1695df4615af8822334caf2799",
        "resourceGroup": "sales-engineering-demo"
      },
      "osState": "Generalized",
      "osType": "Windows",
      "snapshot": null,
      "storageAccountType": "Standard_LRS"
    },
    "zoneResilient": true
  },
  "tags": null,
  "type": "Microsoft.Compute/images"
}

DEBUG: found DISK: /subscriptions/<subscription_id>/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/disks/azdevdemo_disk1_ce217e1695df4615af8822334caf2799
DEBUG: source_os_disk_type: DISK. source_os_disk_id: /subscriptions/<subscription_id>/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/disks/azdevdemo_disk1_ce217e1695df4615af8822334caf2799. source_os_type: Windows
WARNING: Creating source snapshot
ERROR: command failed: ['/usr/local/Cellar/azure-cli/2.0.72_1/libexec/bin/python', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'azdevdemo-image-20190924_os_disk_snapshot', '--resource-group', 'sales-engineering-demo', '--source', '/subscriptions/<subscription_id>/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/disks/azdevdemo_disk1_ce217e1695df4615af8822334caf2799', '--output', 'json', '--tags', 'created_by=image-copy-extension']
ERROR: output: ERROR: Resource azdevdemo_disk1_ce217e1695df4615af8822334caf2799 is not found.

ERROR: cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: cli.azure.cli.core.util : Command '['/usr/local/Cellar/azure-cli/2.0.72_1/libexec/bin/python', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'azdevdemo-image-20190924_os_disk_snapshot', '--resource-group', 'sales-engineering-demo', '--source', '/subscriptions/<subscription_id>/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/disks/azdevdemo_disk1_ce217e1695df4615af8822334caf2799', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "<path_to>/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 82, in imagecopy
    run_cli_command(cli_cmd)
  File "<path_to>/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 35, in run_cli_command
    raise ex
  File "<path_to>/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/Cellar/azure-cli/2.0.72_1/libexec/bin/python', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'azdevdemo-image-20190924_os_disk_snapshot', '--resource-group', 'sales-engineering-demo', '--source', '/subscriptions/<subscription_id>/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/disks/azdevdemo_disk1_ce217e1695df4615af8822334caf2799', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
ERROR: Command '['/usr/local/Cellar/azure-cli/2.0.72_1/libexec/bin/python', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'azdevdemo-image-20190924_os_disk_snapshot', '--resource-group', 'sales-engineering-demo', '--source', '/subscriptions/<subscription_id>/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/disks/azdevdemo_disk1_ce217e1695df4615af8822334caf2799', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "<path_to>/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 82, in imagecopy
    run_cli_command(cli_cmd)
  File "<path_to>/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 35, in run_cli_command
    raise ex
  File "<path_to>/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/Cellar/azure-cli/2.0.72_1/libexec/bin/python', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'azdevdemo-image-20190924_os_disk_snapshot', '--resource-group', 'sales-engineering-demo', '--source', '/subscriptions/<subscription_id>/resourceGroups/sales-engineering-demo/providers/Microsoft.Compute/disks/azdevdemo_disk1_ce217e1695df4615af8822334caf2799', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
WARNING: cli.azure.cli.core.util : 
To open an issue, please run: 'az feedback'
WARNING: 
To open an issue, please run: 'az feedback'
INFO: az_command_data_logger : exit code: 1
INFO: telemetry.save : Save telemetry record of length 2688 in cache
WARNING: telemetry.check : Negative: The <path_to>/.azure/telemetry.txt was modified at 2019-09-25 10:27:19.123617, which in less than 600.000000 s
INFO: command ran in 3.896 seconds.

**Comment by tamirkamara** [comment]
@mreid-contrast please confirm your cli version and extension version.

**Comment by mreid-contrast** [comment]
My installations of azure-cli and Image Copy are refreshed via a script every time that I run them, so the versions that I used are whatever were available on Wednesday, 9/25. An `az –version` shows:


azure-cli                         2.0.74



command-modules-nspkg              2.0.3

core                              2.0.74

nspkg                              3.0.4

telemetry                          1.0.3



Extensions:

azure-devops                      0.12.0

image-copy-extension               0.2.1

**Comment by JRodDynamite** [comment]
@mreid-contrast - I am facing a similar issue as you were. Did you get any resolution on this? Is there a workaround?

**Comment by prasannapad** [comment]
I am also running into the same issue as @mreid-contrast.  @tamirkamara do we have a resolution on this please?

**Comment by tamirkamara** [comment]
@prasannapad Can you post the output of the command with the --debug flag?

**Comment by yungezz** [comment]
hi @scarolan @prasannapad could you pls help to paste output of command with --debug to help investigating? thanks

**Comment by yungezz** [comment]
close since no response. Feel free to create new issue if met any error.
