### ISSUE TITLE
'automation' is misspelled or not recognized by the system

### ISSUE THREAD

**Issue by itzhakja** [Azure/azure-cli-extensions#7341]
### Describe the bug

Hi

I'm trying to run the `az automation runbook start` to start a Runbook but failed to do so with this error message:

##[error]ERROR: 'automation' is misspelled or not recognized by the system.

* The last time it worked was last Thursday (02/29/24)
* I tried to upgrade my AzureCLI tool on my workstation but nothing has changed.

### Related command

`az automation runbook start`

### Errors

##[error]ERROR: 'automation' is misspelled or not recognized by the system.

### Issue script & Debug output

##[error]ERROR: 'automation' is misspelled or not recognized by the system.

### Expected behavior

A runbook should be started

### Environment Summary

azure-cli                         2.25.0
core                              2.25.0
telemetry                          1.0.6
Extensions:
azure-devops                      0.21.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
