### ISSUE TITLE
Detect Options Values Mismatch

### ISSUE THREAD

**Issue by jklaus** [Azure/azure-cli-extensions#735]
At least as of version 2.0.65 the detect's values are true/false, not on/off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82177ae5-9144-27f7-47c0-5fa076636a69
* Version Independent ID: f89f4b34-692e-1b3f-0314-33ef141243c2
* Content: [az repos](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/repos.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/repos.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@jklaus Please verify, this was due to the delay in docs update for the extensions.  Docs are updated now to reflect the correct values. 

@tjprescott this is fixed.
