### ISSUE TITLE
Setting apiServerAuthorizedIPRanges is not allowed on old clusters. Please recreate one again

### ISSUE THREAD

**Issue by archmangler** [Azure/azure-cli-extensions#737]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

az aks update

### Description of issue (in as much detail as possible)

- On AKs clusters (all versions up to 1.14.0)

```
[me@mybox aks-deployment-devtest]$ az aks update -g lslz-AKS-CLUSTER1-AKS -n lslz--aks-cluster1-sg --api-server-authorized-ip-ranges "x.y.z.w"
Deployment failed. Correlation ID: 0e7e8a69-3572-46d2-bf48-448ff7ff5fd0. Setting apiServerAuthorizedIPRanges [x.y.z.w] is not allowed on old clusters. Please recreate one again.
```

This cryptic error message not only doesn't define what an "old" and "new" cluster is, but provides no indication as to how recreating the cluster will resolve the issue. 

-----

**Comment by archmangler** [comment]
Additional information:
===============

- Tested AKS cluster versions incrementally upgrading to these versions: 1.12.x, 1.13.5, 1.14.0
- same results with each version

**Comment by sauryadas** [comment]
@feiskyer Please take a look. 
@archmangler Have you filed a support ticket with Azure ?

**Comment by feiskyer** [comment]
@archmangler Is this a new cluster after enabling the feature flag `APIServerSecurityPreview`? apiServerAuthorizedIPRanges is only available for new clusters after feature flag is enabled.

**Comment by archmangler** [comment]
@feiskyer - Yes. We update the feature flag then deployed the cluster. Thereafter we tried point upgrades of the cluster. We repeated this across 2 deployments, each time destroying the cluster.

**Comment by feiskyer** [comment]
@archmangler thanks for the info. Have you filed a support ticket?

**Comment by archmangler** [comment]
Hi @feiskyer  - I'm in process of filing a support ticket.

**Comment by archmangler** [comment]
@feiskyer  - I've redeployed the AKS cluster with 1.14.0 Kubernetes version, this time the whitelisting command is successul. I have not tested other AKS versions.

**Comment by feiskyer** [comment]
@archmangler cool, thanks for the update. There's possible that the cluster is created just after the feature gate enabled, but it actually needs some time to replicate it.

**Comment by feiskyer** [comment]
@archmangler I think this can be closed now?

**Comment by archmangler** [comment]
Yes, thanks for the help.
