### ISSUE TITLE
This option does not exist in your cli

### ISSUE THREAD

**Issue by khandelwalankit04** [Azure/azure-cli-extensions#744]
az-cli version : 2.0.65 does not have az image copy!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1806a2fb-e007-03d5-ac2d-277da130d29b
* Version Independent ID: f8583594-0ed8-ff4d-33a8-2f7c9f41c288
* Content: [az image](https://docs.microsoft.com/en-us/cli/azure/ext/image-copy-extension/image?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/image-copy-extension/image.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/image-copy-extension/image.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
`az image copy` is an extension. You have to install it with `az extension add -n image-copy-extension`.
