### ISSUE TITLE
Availability Zones support for Azure Firewall

### ISSUE THREAD

**Issue by tejasshah7** [Azure/azure-cli-extensions#747]
**Resource Provider**
What is the Azure resource provider your feature is part of?
- Network (NRP)

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Support for Availability Zones for Azure Firewall.
https://docs.microsoft.com/en-us/azure/availability-zones/az-overview

We need CLI support for the following:
- Create Firewall with availability zones in one of the supported regions listed in the link above
- Letting users see all zones for the firewall

Example PowerShell documentation:
https://github.com/Azure/azure-powershell/blob/network-april/src/Network/Network/help/New-AzFirewall.md

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-04-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/azureFirewall.json

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
End of June

**Comment by tjprescott** [comment]
@tejasshah7 there are no supported regions listed for Azure Firewall in the linked documentation. 

```
(env) D:\github>az network firewall create -g tjp-rg -n af1 --zones 1 3
The resource type 'azureFirewalls' does not support availability zones at location 'westus' and api-version '2019-04-01'.
```

Please advise.

**Comment by tejasshah7** [comment]
Hello,

Zones are supported only in certain regions. Here are list of regions where zones are supported. Please use one of these.
https://docs.microsoft.com/en-us/azure/availability-zones/az-overview

Thanks,
Tejas

**Comment by tjprescott** [comment]
@tejasshah7 that link does not list any supported regions for Azure Firewall.

**Comment by tjprescott** [comment]
Eastus works.

**Comment by tejasshah7** [comment]
Yes that link is yet to be updated but the regions mentioned there will work for Firewall too.

Tejas
