### ISSUE TITLE
Please explain what --run-id is

### ISSUE THREAD

**Issue by RickKra** [Azure/azure-cli-extensions#749]
The --run-id parameter is required on all these commands, but nowhere do you explain what one is or give an example that shows what one would look like.

Please add those details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e1f25b5-397e-03b6-7d7f-75570d8649e5
* Version Independent ID: 962e2f0c-ce31-7de7-8222-17ceeac1dc98
* Content: [az pipelines runs artifact](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/runs/artifact?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines/runs/artifact.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines/runs/artifact.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@RickKra 

You will be able to better map these commands and inputs to UI if you have the preview feature enabled as below - 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/11888714/59325545-1c40c000-8d01-11e9-982c-f490408b0ed5.png">

> If above feature is NOT enabled on your account, you can think of --run-id as --build-id 

```az pipelines``` commands like list, show, create, delete help you manage the pipeline definitions.
```az pipelines runs``` commands help you manage pipeline runs for those definitions.

e.g. ```az pipelines list```
<img width="468" alt="image" src="https://user-images.githubusercontent.com/11888714/59325302-244c3000-8d00-11e9-878c-c198c04a96d8.png">

```az pipelines runs list```
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/11888714/59325316-3332e280-8d00-11e9-81b5-c0f91fa986a2.png">

Hence --run-id is the pipeline runs identifier which might be listed in your url as --build-id https://dev.azure.com/MyOrganization/MyProject/_build/results?buildId=984&view=results

Please let me know if this helps. 
We will try to fix the documentation for this in command help.

**Comment by atbagga** [comment]
@geverghe Please suggest how we can improve the help text to fix the issue.

**Comment by geverghe** [comment]
@RickKra - Would the following update work?
1. "ID of the run that the artifact is associated to. For example, --run-id 1"

**Comment by RickKra** [comment]
@atbagga your 1st comment where you explain that run-id and build-id (or release-id as well?) are equivalent and show where to find those values is what I was after.

@geverghe no that update wouldn't work, because it's a fabricated value. I wanted to understand what it is and where I'd find the values that I'd want to use with those commands.

**Comment by geverghe** [comment]
@RickKra 
Addressing feedback on "what it is"
Isn't "--run - ID of the run that the artifact is associated to." adequate for understanding what it is? Which part requires more clarity or is confusing? Would mentioning "ID of the pipeline run that the artifact is associated to."

Addressing feedback on "where I'd find the values to use with those commands"
Further, for all ID related parameters, the paradigm followed is that the list command gives the ID which is to be used in the show command. Therefore, `az pipelines runs show` would require the ID which is fetched from `az pipelines runs list`. This is a consistent paradigm followed in Azure CLI. To clarify, are you facing a challenge in this paradigm or only for this specific command? This helps us evaluate if the change required is widespread or limited to just this command.

In case you want to continue the conversation offline, you can reach me at geverghe at microsoft dot com.

**Comment by atbagga** [comment]
@RickKra Resolving the issue since it is a learning curve for using some of the commands and new terminology with the pipelines revamp. For any concerns/feedback please reach out to George as per his comment above and we will be happy to help.
