### ISSUE TITLE
Compute instance is not getting stopped even after configuring the 'Idle Shutdown Time'

### ISSUE THREAD

**Issue by TeslaRaghav** [Azure/azure-cli-extensions#7506]
### Describe the bug

The compute instance on Sandbox environment is not getting stopped automatically even after configuring the idle shutdown time. The instance is running idle without execution of any jobs since 45 days and has incurred cost to the customer.

### Related command

NA

### Errors

As the issue is not related to any code, providing Error is not valid option for this issue.

### Issue script & Debug output

NA

### Expected behavior

After configuring the ''Idle Shutdown time". the compute instance is supposed to stop after the prescribed time. However, this option is not working and the instance has been running since 45 days.
![image](https://github.com/Azure/azure-cli-extensions/assets/114466294/1cb64c50-8520-4757-821f-6b9fcbc27c02)
![image](https://github.com/Azure/azure-cli-extensions/assets/114466294/888f427e-f5f5-417c-a9fc-1fc6ba5b0a4f)

### Environment Summary

NA

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Not related to Azure CLI repo
