### ISSUE TITLE
Invalid resource_id provided when trying to attach ADF Compute Target

### ISSUE THREAD

**Issue by lehmus** [Azure/azure-cli-extensions#755]
Which resource id should be used when attaching an existing Data Factory instance to the AML Workspace? I am using the following command to attach an ADF instance:
`az ml computetarget attach datafactory --compute-resource-id adf_object_id --name adftarget --resource-group amlwsrg --workspace-name amlws`
This gives the following error message:
`Invalid resource_id provided: adf_object_id`
Where adf_object_id is the _Managed Identity Object ID_ of the Data Factory instance. The same error is given if I use the _Managed Identity Application ID_ of the ADF instance or the plain resource name of the ADF instance. How to get the resource id of the ADF instance? Also, why can't the ADF target be attached or created from the Azure Portal, like the other AML Compute targets?

---
#### Asiakirjan tiedot

⚠ *Älä muokkaa tätä osiota. Sitä tarvitaan kohteessa docs.microsoft.com GitHub-ongelmien linkityksessä.*

* ID: eb935bf4-2174-157f-ee48-e33a658aec89
* Version Independent ID: 3353cd79-30d4-90ce-9037-eb835d22dadd
* Content: [az ml computetarget attach](https://docs.microsoft.com/fi-fi/cli/azure/ext/azure-cli-ml/ml/computetarget/attach?view=azure-cli-latest#ext-azure-cli-ml-az-ml-computetarget-attach-datafactory)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-ml/ml/computetarget/attach.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-ml/ml/computetarget/attach.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@lehmus Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.

**Comment by lehmus** [comment]
It seems that Azure ML Output Datasets are superseding the DataTransferStep in AML Pipelines. Output Datasets do not require the Data Transfer compute attached, so this issue is not relevant anymore.
