### ISSUE TITLE
az image copy does not work with dev/test labs

### ISSUE THREAD

**Issue by scarolan** [Azure/azure-cli-extensions#763]
The az image copy command works, but the custom image never shows up in the target Azure dev/test lab, even though it is in the resource group alongside other images.  Please enable the ability to copy images between Azure Dev/Test labs.

-----

**Comment by yonzhan** [comment]
image copy.

**Comment by SaurabhSharma-MSFT** [comment]
@qwordy Do you have any updates on this issue.
