### ISSUE TITLE
[Artifacts] AttributeError: 'module' object has no attribute 'uuid4'

### ISSUE THREAD

**Issue by nagou** [Azure/azure-cli-extensions#772]
## Describe the bug

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.10.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'module' object has no attribute 'uuid4'
Traceback (most recent call last):
  File "knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
AttributeError: 'module' object has no attribute 'uuid4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --organization {} --feed {} --name {} --version {} --path {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-16.04-xenial
Python 2.7.12
Shell: bash

azure-cli 2.0.66

Extensions:
azure-devops 0.10.0

```

**Comment by Tmx10-50** [comment]
I am seeing the same thing and am unable to publish to a feed from RH 7.6

Extension Name: azure-devops. Version: 0.11.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'module' object has no attribute 'uuid4'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 566, in execute
    raise ex
AttributeError: 'module' object has no attribute 'uuid4'

Linux-3.10.0-957.21.2.el7.x86_64-x86_64-with-redhat-7.6-Maipo
Python 2.7.5
Shell: bash

azure-cli 2.0.67

Extensions:
azure-devops 0.11.0

**Comment by atbagga** [comment]
Closing this issue in favor of tracking it in the azure-devops extension repo. 
Please see https://github.com/Azure/azure-devops-cli-extension/issues/828 for updates.
