### ISSUE TITLE
Issues with AKS browse

### ISSUE THREAD

**Issue by sobi3ch** [Azure/azure-cli-extensions#773]
## Describe the bug

**Command Name**
`az aks browse
Extension Name: aks-preview. Version: 0.4.2.`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa06a3dad68>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
python3.6/site-packages/urllib3/connection.py, ln 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
...
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa06a3dad68>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --name {} --resource-group {} --listen-port {}`

## Environment Summary
```
Linux-4.15.0-51-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.65 *

Extensions:
aks-preview 0.4.2

```

**Comment by Stip13** [comment]
## Different environment, same issue

**Command Name**
`az aks browse
Extension Name: aks-preview. Version: 0.4.2.`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x050E5FF0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée',))
Traceback (most recent call last):
pip-install-izsysaz4\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az aks browse --name {} --resource-group {} --listen-port {}`
- wait for a moment without activity

## Expected Behavior

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.65 *

Extensions:
aks-preview 0.4.2

```
## Additional Context

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
This dashboard issue should be improved since original opening, please retry and if issue persists open a new issue and we will take another look. Thanks!
