### ISSUE TITLE
Dependencies missing for creating pipeline build

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [Azure/azure-cli-extensions#776]
Hello,

Here are a few dependencies that I found were missing;
1. In the example you specify "--type" as the parameter used to specify your type of source control. This does not work and I receive a "az: error: unrecognized arguments: --type" error. The parameter in the examples should instead be "--repository-type".
2. "--organization" is a mandatory parameter and should be in the examples as such.
3. "--project" is a mandatory parameter and should be in the examples as such.

Thank you :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2123ca-5408-8f93-6f5c-93fe74684523
* Version Independent ID: 7a03fe73-da7f-9b5a-38e7-ef51d85d49fd
* Content: [az pipelines](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@AdminTurnedDevOps 
1. I will be fixing 1 in the help text. It should be --repository-type. 

Regarding 2. and 3. Organization and Project not being mentioned in the example the reason is although they are required params but in most cases users use the configure command to set them one time. 

```
az devops configure --defaults organization=https://dev.azure.com/MyOrg project=MyProject 
```

Also if the command is being run from inside the git directory with remote url pointing to a Azure Devops    repository --org and --project fields are automatically picked up from the git remote. 

If that sounds reasonable to you, I will fix 1 and close the issue.

**Comment by AdminTurnedDevOps** [comment]
@atbagga 

I agree that most do that, but perhaps there can be a "side note" section for folks like me that don't typically do default profiles? This is important for say, folks that are trying to automate their pipelines, but need a job to run with specific metadata every time?

**Comment by atbagga** [comment]
@geverghe  This has come up a few times where organization and project are not shown as required params since they can be defaulted to config or detected from local git repo. 
Can't think of a good way to handle it. With reference to above comment.. `side note` could be `long summary`. Thoughts?

**Comment by geverghe** [comment]
Acknowledge the pain in figuring out what is required especially for the persona that @AdminTurnedDevOps mentioned. 

@AdminTurnedDevOps  - Would the following help text update close out this confusion?
--org --organization  : Azure Devops organization URL. You can configure the default organization using 
                                    az devops configure -d organization= ORG_URL. Required if not configured as 
                                    default. Example: https://dev.azure.com/MyOrganizationName/.
--project -p               : Name or ID of the project. You can configure the default project using 
                                    az devops configure -d project= NAME_OR_ID. Required if not configured as 
                                    default.

**Comment by AdminTurnedDevOps** [comment]
@geverghe 

That sounds great to me! Thank you.

**Comment by atbagga** [comment]
Fix in master. Release 0.12.0 ETA next week will have the change.
