### ISSUE TITLE
az monitor app-insights component delete	Create a new Application Insights resource.

### ISSUE THREAD

**Issue by dansemedo** [Azure/azure-cli-extensions#777]
doc error, it should be Delete an existing Application Insights resource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bce0dc5-da82-717a-70cf-e392c05904a3
* Version Independent ID: a5cb6492-d731-0c98-7691-64d1d7a14a5c
* Content: [az monitor app-insights](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S172
