### ISSUE TITLE
AKS App Routing Commands Fail with 2024-06-02-preview API

### ISSUE THREAD

**Issue by jaiveerk** [Azure/azure-cli-extensions#7921]
### Describe the bug

Customers using commands to update configuration for the App Routing add-on (`az aks approuting ...`) may run into the following error when updating (not creating) managed clusters running K8s version <1.30 via apiversion 2024-06-02-preview with CLI versions 7.0.0b7, 7.0.0b6, and 7.0.0b5:

```
Code: InvalidParameter
Message: Specific ingress controller types (AnnotationControlled, External, Internal, None) are only available on cluster version 1.30 or later.
```

This error is due to a known issue with the AKS service that has since been fixed, with a rollout coming in early September.

Customers that experience this issue can utilize the following workarounds, from least to greatest involvement:
- Submit their request using an apiversion older than 2024-06-02-preview, including 2024-06-01 (GA)
- Utilize a version of the CLI older than the ones mentioned above
- Most intensive option - Upgrade their K8s cluster to version 1.30.0 or greater

### Related command

`az aks approuting update`
`az aks approuting zone`

### Errors

```
Code: InvalidParameter
Message: Specific ingress controller types (AnnotationControlled, External, Internal, None) are only available on cluster version 1.30 or later.
```

### Issue script & Debug output

n/a, known issue

### Expected behavior

Expected behavior should be for customers' requests to pass using K8s version <1.30 and the latest preview APIversion when they aren't specifying a default nginx ingress controller type for their app routing configuration and/or when they are running app routing commands unrelated to configuring their nginx.

### Environment Summary

Customers affected are those attempting to update their app routing configuration via the 2024-06-02-preview API version via CLI versions 7.0.0b7, 7.0.0b6, and 7.0.0b5

### Additional context

This is a known issue with a fix that will begin rolling out in a week or so. See above for workarounds.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jaiveerk** [comment]
The fix for this bug is now rolling out and should reach all regions within the next few days. I'm accordingly closing this issue.
