### ISSUE TITLE
Instruct Users to Enable Front Door Extension

### ISSUE THREAD

**Issue by filmgirl** [Azure/azure-cli-extensions#793]
User needs to add 'az extension add --name front-door' before these commands work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1b5ddd-0054-0175-b689-d20a1349bedb
* Version Independent ID: 72ccc1b6-814f-b780-99cd-ab48dfdecb66
* Content: [az network front-door](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This is true, but there's nothing actionable that can be done in the extension to facilitate this. It's a chicken and egg problem.
