### ISSUE TITLE
Cannot override variables in az pipelines release create

### ISSUE THREAD

**Issue by davoodharun** [Azure/azure-cli-extensions#798]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

az pipelines release create

### Description of issue (in as much detail as possible)
I don't believe there is a way to override variables of a release that are pre-configured to be overridden. I can do at queue time when creating a release in the portal.  It would be great to see something similar to ```az pipelines build queue --variables``` but for releases

**Comment by geverghe** [comment]
Hey @davoodharun  - Thank you for providing feedback on the Azure DevOps extension. We are at present building the requested functionality - (https://github.com/Azure/azure-devops-cli-extension/issues/639, https://github.com/Azure/azure-devops-cli-extension/issues/479) for Multi stage YAML pipelines. Multi stage YAML pipelines should be able to take care of your release scenarios as well.

**Comment by atbagga** [comment]
@davoodharun Can you share your thoughts on above comment. We will close/edit/track the issue appropriately.

**Comment by atbagga** [comment]
We have the same issue in our repo so closing this one as duplicate since it will be easier to track the other one in our backlog. 

@davoodharun Please follow the other issue for updates.
