### ISSUE TITLE
Unable to load extension 'aks-preview'

### ISSUE THREAD

**Issue by ChristopheChirat** [Azure/azure-cli-extensions#811]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
After updating the Azure client I have the following message:

`az extension list
Unable to load extension 'aks-preview'. Use --debug for more information.
[
  {
    "extensionType": "whl",
    "name": "aks-preview",
    "version": "0.2.3"
  },
  {
    "extensionType": "whl",
    "name": "azure-devops",
    "version": "0.3.0"
  },
  {
    "extensionType": "whl",
    "name": "interactive",
    "version": "0.4.1"
  }`

-----

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-cli-extensions/issues/792

**Comment by tjprescott** [comment]
You need to update the extension.
