### ISSUE TITLE
db-up extension | Incorrect status information

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli-extensions#8132]
### Describe the bug

The db-up extension is deprecated but the following files are not providing correct status information:

1. [db-up extension README](https://github.com/azure/azure-cli-extensions/blob/main/src/db-up/README.md)
2. MicrosoftDocs/azure-docs-cli [Available Azure CLI extensions](https://learn.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest). This report is autogenerated by source code and will change automatically.
    ![Image](https://github.com/user-attachments/assets/525d82fc-bc57-4e7c-8abf-87bbb56ad59b)

### Related command

az sql up
az postgres up
az mysql up

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

Azure CLI 2.65.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
