### ISSUE TITLE
az devops login fails to access OSX keychain

### ISSUE THREAD

**Issue by brichins** [Azure/azure-cli-extensions#814]
## Describe the bug

When trying to login with `az devops login`, the command fails trying to access the OSX keyvault.

**Command Name**
`az devops login
Extension Name: azure-devops. Version: 0.11.0.`

**Errors:**
```
Can't get password from keychain: (-25293, 'Security Auth Failure: make sure python is signed with codesign util')
Traceback (most recent call last):
site-packages/keyring/backends/OS_X.py, ln 48, in get_password
    return api.find_generic_password(self.keychain, service, username)
site-packages/keyring/backends/_OS_X_API.py, ln 103, in find_generic_password
    Error.raise_for_status(status)
...

site-packages/keyring/backends/OS_X.py, ln 54, in get_password
    raise KeyringError("Can't get password from keychain: " "{}".format(e))
keyring.errors.KeyringError: Can't get password from keychain: (-25293, 'Security Auth Failure: make sure python is signed with codesign util')
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops login`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67

Extensions:
alias 0.5.2
azure-devops 0.11.0
subscription 0.1.3
image-copy-extension 0.2.1

```

**Comment by yonzhan** [comment]
devops

**Comment by SaurabhSharma-MSFT** [comment]
@brichins Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.
