### ISSUE TITLE
Equivalent functionality in Powershell?

### ISSUE THREAD

**Issue by johncrim** [Azure/azure-cli-extensions#815]
It's great to be able to manage Azure devops boards and pipelines from the CLI, but is there any thought to providing similar access via powershell (PS Core of course)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66873a24-f15b-c3b0-009d-96f9c6160d0c
* Version Independent ID: 915c9312-32c3-c23e-63c1-db33c6b578ce
* Content: [azure-devops](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/index.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/index.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by geverghe** [comment]
Hey @johncrim - At present there are no immediate plans to invest in a core PS module for Azure DevOps. Are you facing any challenges using the Azure CLI along with the DevOps extension on PowerShell? Or is it personal preference?

**Comment by Kroof** [comment]
@johncrim

**Comment by johncrim** [comment]
@geverghe - it's personal preference + productivity, along with being able to leverage the power of powershell and its ecosystem. 

IMO not having it is a glaring omission given the usefulness of powershell in everything else Azure. Though if I really need something I can write my own Cmdlets, I'm a big fan of the pretty well documented REST APIs and client libraries.

@Kroof  - thank you! I wasn't aware of that module, will take a look.

**Comment by geverghe** [comment]
@johncrim - you can still use Azure CLI along with the Azure DevOps extension on PowerShell. Can you provide a bit more context on where this fails for you? Is it the lack of PowerShell native commanding? We have been using the Azure DevOps CLI from PowerShell to create scripts. This allows you to work with the PowerShell ecosystem as well.

**Comment by san7hos** [comment]
@geverghe It is a bit cumbersome though to use the cli in powershell. Basically every call has to be followed by json deserialization and check for $LASTEXITCODE. Additionally, you have to build to parameters with a custom way and can't use powershell splatting.

**Comment by geverghe** [comment]
Got it - makes sense. Thank you providing context. As of now, there are no plans to invest in a PowerShell module. We will re-evaluate once we have bandwidth. I have raised a feature request on our repo so that we keep track of the request - https://github.com/Azure/azure-devops-cli-extension/issues/710

**Comment by JeffBor** [comment]
@johncrim  In the new-ish Az module, there are a handful of *-AzDo* commandlets available, but it's very rudimentary.  IMHO, I'm not counting on anything significant there (yet).  For now, it's az devops as @geverghe says.  ConvertFrom-Json is your friend 😜
