### ISSUE TITLE
az aks browse out of the sudden "lost connection to pod" and closes

### ISSUE THREAD

**Issue by cheoalfredo** [Azure/azure-cli-extensions#819]
## Describe the bug

**Command Name**
`az aks browse
Extension Name: aks-preview. Version: 0.4.4.`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04FB5BB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
pip-install-wuxrdt2n\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.64 *

Extensions:
aks-preview 0.4.4

```

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
This dashboard issue should be improved since original opening, please retry and if issue persists open a new issue and we will take another look. Thanks!
