### ISSUE TITLE
Create service connection with az devops service-endpoint create in an Azure DevOps release pipeline

### ISSUE THREAD

**Issue by ormikopo1988** [Azure/azure-cli-extensions#821]
Hello,

I have the following use case. I am creating a service principal with an azure cli script as part of an Azure DevOps Services release pipeline. I would like after the creation of the service principal to call the "az devops service-endpoint create" command and pass the service principal id and key in order to create the service endpoint in an automated way. I do not see a parameter that I can pass for the service principal key. Instead when I run the "az devops service-endpoint create", I can just pass the service principal id and then it prompts me for the service principal key twice and have to pass it manually. 

Is it possible somehow to achieve the same thing without any manual intervention?

Thank you very much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ecb62a2-f74c-a539-d3a8-c8fde7c2de06
* Version Independent ID: 5760936e-90a1-4129-6f6f-6dd4194bb73c
* Content: [az devops service-endpoint](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/service-endpoint?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/service-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
You can set the environment variable AZURE_DEVOPS_EXT_AZURE_RM_SERVICE_PRINCIPAL_KEY with the service principal key and you will not be prompted for it.

Please let us know if that solves your need.

This is shown in the error text when you try to run the command in a non interactive console. Given you had trouble finding it out we will take a look if we can put it out somewhere easier to discover.
cc: @geverghe

**Comment by geverghe** [comment]
Noted. @ormikopo1988 - Couple of clarification questions:
1. Did you try searching for this information? 
2. Do you have any recommendations on the common information destinations that you look up to find this information? 
3. Would command help with the link to documentation help?

**Comment by ormikopo1988** [comment]
Hello everyone! Thank you very much for your suggestions. I went to the service_endpoint.py in Github and saw the source code for creating the service connection and saw the condition that checked about the AZURE_DEVOPS_EXT_AZURE_RM_SERVICE_PRINCIPAL_KEY os environment variable. So I suppose based on your suggestion @atbagga my assumption was correct! 

@geverghe
1. Like I stated above I had to go to the source code of the azure devops cli extensions in order to find out about the possibility to solve this by setting an environment os variable
2. I am mostly referring to Microsoft Docs for things related to Azure DevOps Services
3. I did run the help command with the az devops service-endpoint --help, it stated all the variables that the docs also stated. For this specific need I suppose that it would be great if the docs included this possibility for providing the service endpoint service principal key as an environment variable, in order for it to be able to run in an automated way without a need for user prompt.

Thank you both of you very much for your time!

**Comment by geverghe** [comment]
@ormikopo1988  - Awesome - glad @atbagga's clarification helped. Created a new issue to track the documentation request - https://github.com/Azure/azure-devops-cli-extension/issues/698. Closing this and you can track the documentation request progress on the issue thread provided.

**Comment by mmisztal1980** [comment]
--service-endpoint-configuration is missing information on the structure/format/contents of the configuration file.

Examples would be nice, on how to add a k8s connection using kubeconfig for instance.
