### ISSUE TITLE
Error executing `az artifacts universal publish`

### ISSUE THREAD

**Issue by pjirsa** [Azure/azure-cli-extensions#824]
## Describe the bug

**Command Name**
`az artifacts universal publish
Extension Name: azure-devops. Version: 0.4.0.`

**Errors:**
```
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
pip-install-v1m4qsu_\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 560, in execute
cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
cli\core\commands\__init__.py, ln 609, in _run_job
azext_devops\dev\common\exception_handler.py, ln 22, in azure_devops_exception_handler
    reraise(*sys.exc_info())
Temp\pip-install-v1m4qsu_\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 588, in _run_job
...
Azure\CLI2\lib\subprocess.py, ln 709, in __init__
    restore_signals, start_new_session)
Azure\CLI2\lib\subprocess.py, ln 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal publish --organization {} --feed {} --name {} --version {} --path {}`

## Environment Summary
```
Windows-10-10.0.18912-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.64 *

Extensions:
azure-devops 0.4.0
dev-spaces-preview 0.1.6

```

**Comment by pjirsa** [comment]
I was able to resolve this issue by first running `az devops login`

The documentation page (https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops) does not specify running that step.

**Comment by atbagga** [comment]
@pjirsa I tried to run the publish command without login and I see this error - 
```Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.```

I see you are on an older version of the extension, you can update it via ```az extension update -n azure-devops``` command. May be this was fixed in some later version.

Also the documentation [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#log-in-to-azure-devops) points to ```az login```. 

If you have some feedback to improve error handling or documentation, please let us know.

cc: @geverghe

**Comment by geverghe** [comment]
@pjirsa - Sorry to hear about the trouble you faced. A few clarification questions
1. To confirm, you were looking for instruction indicating that the user should be logged in prior to running publish command? 
2. Can you help us understand where the current documentation (https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops) is failing which has the login step prior to publish?

Further, as an FYI, you can raise documentation issues directly on the page as well. 
Thanks,
George Verghese,

**Comment by atbagga** [comment]
@pjirsa Resolving as per above comments. Please raise another if you still have concerns or feedback to share.
