### ISSUE TITLE
dependencies cannot be displayed via cli in Azure AppInsight

### ISSUE THREAD

**Issue by gesada** [Azure/azure-cli-extensions#831]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
While using az cli version 2.0.67, we have found that using the command 
az monitor app-insights events show --app "xxxx-xxxxx-xxxxx-xxxx" --type dependencies --start-time <date> 
showing no information with relation to dependencies

**To Reproduce**
Using the command above to reproduce

**Expected behavior**
dependencies type should be displayed via Azure CLI

**Environment summary**
CLI version (`az --version`) 2.0.67

**Additional context**
n/a

**Comment by yonzhan** [comment]
add to S172

**Comment by jsntcy** [comment]
@gesada, I just ran the command you mentioned `az monitor app-insights events show --app "xxxx-xxxxx-xxxxx-xxxx" --type dependencies --start-time` and got the following result, could you tell me what is your expected result?
`{
  "aimessages": [
    {
      "additionalProperties": null,
      "code": "AddedLimitToQuery",
      "details": null,
      "innererror": null,
      "message": "The query was limited to 500 rows"
    }
  ],
  "odatacontext": "https://api.applicationinsights.io/v1/apps/47e2b1d2-b751-42c8-b159-39c3a27d6c61/events/$metadata#dependencies",
  "value": []
}`

**Comment by jsntcy** [comment]
@gesada, any update on this issue?

**Comment by jsntcy** [comment]
Close this now as no response from customer for a long time.
@gesada, if you think the issue still exists, please reopen this issue.
