### ISSUE TITLE
`az monitor log-analitics` does not longer exist in `az` cli

### ISSUE THREAD

**Issue by epierotto** [Azure/azure-cli-extensions#834]
```
az monitor log-analytics
az monitor: 'log-analytics' is not in the 'az monitor' command group. See 'az monitor --help'.
```

Can you please update the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0fd6a58-ac1a-fa45-8d96-579b4af36499
* Version Independent ID: 4098ca97-1b85-eb29-18e9-e6f0495fd030
* Content: [az monitor log-analytics](https://docs.microsoft.com/en-us/cli/azure/ext/log-analytics/monitor/log-analytics?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
You need to install the extension with `az extension add -n log-analytics`. This is true for any extension.

**Comment by epierotto** [comment]
Would be better if that is added to the top of each extension example docs, so it'd be explicit.

**Comment by will-beta** [comment]
Got the following error
```
AADSTS500011: The resource principal named https://api.loganalytics.io was not found in the tenant named 13fd5714-8447-4878-8f4c-38614c99fd2d. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 28e187f4-fb93-4039-b55a-6be1be4b1500 Correlation ID: 9fc1a15a-450d-453e-aca7-e66c4af1899d Timestamp: 2019-08-20 03:56:27Z
```
The url of loganalytics in china should be `api.loganalytics.azure.cn`.
How can I provide the right url?
Thanks!
