### ISSUE TITLE
Incorrect description for component delete command 

### ISSUE THREAD

**Issue by ahmad2x4** [Azure/azure-cli-extensions#836]
In the table of content and also in the main section following command is incorrectly described
```
az monitor app-insights component delete
```

it is described as 
```
Create a new Application Insights resource.
```

It should be 
```
Delete Application Insights resource.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 333d37d2-61e2-0184-d253-157ee236439c
* Version Independent ID: 9b0e976f-3cb5-e813-9f33-e9cea7a8df8c
* Content: [az monitor app-insights component](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor/app-insights/component?view=azure-cli-latest#ext-application-insights-az-monitor-app-insights-component-delete)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/component.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor/app-insights/component.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RajGogri** [comment]
Need a fix. Just a typo !

**Comment by yonzhan** [comment]
add to S172

**Comment by jsntcy** [comment]
@ahmad2x4, @RajGogri, this issue has already been fixed. Please upgrade to latest Azure CLI version to verify.
