### ISSUE TITLE
az pipelines should support setting pipeline.Path

### ISSUE THREAD

**Issue by IvanJosipovic** [Azure/azure-cli-extensions#839]
"az pipelines create" and "az pipelines update" should support setting the "Path" property. This is useful as we would like to have builds show up in a specific folder structure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2123ca-5408-8f93-6f5c-93fe74684523
* Version Independent ID: 7a03fe73-da7f-9b5a-38e7-ef51d85d49fd
* Content: [az pipelines](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@IvanJosipovic Thank you for reporting this. 

Closing this in favor of https://github.com/Azure/azure-devops-cli-extension/issues/715 which is filed in the extension repo for the same. 

You can track the progress in the above linked issue.
