### ISSUE TITLE
az artifacts universal download - fetch latest version

### ISSUE THREAD

**Issue by michael-ryan** [Azure/azure-cli-extensions#842]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
azure devops

### Description of issue (in as much detail as possible)
Feature request! It would be nice to have a way of fetching the latest build of an artifact and using that (perhaps with the --version argument?)

For example:
```
az artifacts universal download \
  --organization "https://dev.azure.com/someOrganisation/" \
  --feed "someFeed" \
  --name "someName" \
  --version "latest" \
  --path "${PWD}/test/resources"
```
would be great! Thanks!

-----

**Comment by joelbourbon** [comment]
This is actually supported. See [this](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#downloading-the-latest-version).

**Comment by michael-ryan** [comment]
@joelbourbon yeah thanks, I'll close this.

Bear in mind this feature didn't exist when I made the issue!

For future people who arrive here, proper documentation on the "grabbing latest version" feature is [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#downloading-the-latest-version)!
