### ISSUE TITLE
Parmeters listed as optional are actually required

### ISSUE THREAD

**Issue by rohancragg** [Azure/azure-cli-extensions#845]
e.g. in my testing (after running `az account set -s ...`) --model is clearly not an optional parameter, and neither are --resource-group and --workspace-name

```
az ml model profile -n testProfiling
{
    "Azure-cli-ml Version": "1.0.45.1",
    "Error": "Error, need to specify either --model or --model-metadata-file for model(s) to be profiled."
}
```

```
az ml model profile -n testProfiling --model mymodel:5
{
    "Azure-cli-ml Version": "1.0.45.1",
    "Error": "Please provide a resource group using --resource-group or -g and a workspace name using --workspace-name or -w."
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8825dded-3381-d6ed-3473-6cc67086b1b1
* Version Independent ID: 78430b7b-24a7-a0bf-c429-dc97a2c4f55a
* Content: [az ml model](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-ml/ml/model?view=azure-cli-latest#ext-azure-cli-ml-az-ml-model-profile)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-ml/ml/model.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-ml/ml/model.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ml

**Comment by SaurabhSharma-MSFT** [comment]
@rohancragg Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.

**Comment by rohancragg** [comment]
I no longer use this tool

**Comment by SaurabhSharma-MSFT** [comment]
@rohancragg Thanks for the confirmation. We are proceeding with the closure of this issue.
