### ISSUE TITLE
lost connection to pod using aks browse

### ISSUE THREAD

**Issue by bplasmeijer** [Azure/azure-cli-extensions#857]
The connection with Kubernetes dashboard will be lost unexpected. 

Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
Forwarding from 127.0.0.1:8001 -> 9090
Forwarding from [::1]:8001 -> 9090
Handling connection for 8001
Handling connection for 8001
Handling connection for 8001
Handling connection for 8001
E0719 09:30:09.603631   24760 portforward.go:178] lost connection to pod
The command failed with an unexpected error. Here is the traceback:

HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05AEEF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

## Describe the bug

**Command Name**
`az aks browse
Extension Name: aks-preview. Version: 0.4.5.`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0573EE30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
pip-install-55c8cd2o\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {} --subscription {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.68 *

Extensions:
aks-preview 0.4.5

```

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
Closing as this is almost a year old, if the tunnel connection still fails for you please open a new ticket and we can take a look.
