### ISSUE TITLE
Front-door extension missing in publicly available list

### ISSUE THREAD

**Issue by kaushik-hemant** [Azure/azure-cli-extensions#858]
Hi,

We were using **az extension add --name front-door** command for front-door extension to run the front-door related scripts in AZ CLI task for DevOps.
![AZ-CLI](https://user-images.githubusercontent.com/15911296/61553041-187a2900-aa77-11e9-8983-cc204fa2076e.PNG)

As of now its not there in the available extensions. Let us know if something has been changed as related document doesn't have any modifications.

Refer snapshot for more details:

![Front-Door-Error](https://user-images.githubusercontent.com/15911296/61552964-d7821480-aa76-11e9-8146-0896c7b5edd5.PNG)

Please respond asap.

**Comment by tjprescott** [comment]
What appears if you run `az extension list-available -otable`? What version of the CLI are you running?

**Comment by MyronFanQiu** [comment]
@kaushik-hemant Is this issue solved?

**Comment by MyronFanQiu** [comment]
closed this issue since no update. Feel free to open a new one  if you still encounter such issue.
