### ISSUE TITLE
[Front-Door] Routing rule creation needs improved error messages

### ISSUE THREAD

**Issue by DanoThom** [Azure/azure-cli-extensions#868]
I lost a fair bit of time trying and failing to create a simple Redirect routing rule because I kept receiving this generic catchall message : 

> "usage error: [--redirect-type {Moved,Found,TemporaryRedirect,PermanentRedirect}][--redirect-protocol {HttpOnly,HttpsOnly,MatchRequest}] [--custom-host CUSTOM_HOST] [--custom-path CUSTOM_PATH] [--custom-fragment CUSTOM_FRAGMENT] [--custom-query-string CUSTOM_QUERY_STRING]"

I had to dig into the code to find the below line with those specific rules which were preventing me from creating my rule (I had copy pasted a --backend-pool parameter and it couldn't communicate that that wasn't compatible with a redirect rule).

https://github.com/Azure/azure-cli-extensions/blob/6c38daed3de23239b94131a4268bd92448e1bfb3/src/front-door/azext_front_door/custom.py#L493

**Comment by yonzhan** [comment]
Front-Door

**Comment by johsun-msft** [comment]
A redirect routing rule means that frontdoor would return a 300 level status code directly to client, without forwarding the request to your backend. Thus, it is not possible to specify a backend pool for a redirect routing rule.

**Comment by SaurabhSharma-MSFT** [comment]
@DanoThom I believe you have received answers to your question, so checking in if this issue can be closed. Please let us know.
