### ISSUE TITLE
Add more references to the doc

### ISSUE THREAD

**Issue by diegoalb** [Azure/azure-cli-extensions#872]
The document does not mention how to install the vm repair scripts: "az extension add -n vm-repair"

It would be also interesting to add a more detailed description on what the script automates:
 - Stops the problem VM.
 - Takes a snapshot of the problem VM's OS disk.
 - Creates a new temporary VM ("rescue VM") on a new Resource Group.
 - Attaches the problem VM's OS disk as a data disk on the rescue VM.
 - You can then connect to the rescue VM to investigate and mitigate issues with the problem VM's OS disk.
 - Detaches the problem VM's OS disk from the rescue VM.
 - Performs a disk swap to swap the problem VM's OS disk from the rescue VM back to the problem VM.
 - Removes the resources that were created for the rescue VM, except the original OSDisk

And also the known limitations - It does not support:
 - Encrypted VMs
 - VMSS
 - Classic VMs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0c5cd11-36e0-b233-4f0c-3d432a9925a1
* Version Independent ID: 99b6e064-4f75-9cce-b6e0-0ad1943552b9
* Content: [az vm repair](https://docs.microsoft.com/en-us/cli/azure/ext/vm-repair/vm/repair?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/vm-repair/vm/repair.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/vm-repair/vm/repair.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jdickson289** [comment]
+1 on updating the document according to Diego
The document does not mention how to install the vm repair scripts: "az extension add -n vm-repair"

It would be also interesting to add a more detailed description on what the script automates:

Stops the problem VM.
Takes a snapshot of the problem VM's OS disk.
Creates a new temporary VM ("rescue VM") on a new Resource Group.
Attaches the problem VM's OS disk as a data disk on the rescue VM.
You can then connect to the rescue VM to investigate and mitigate issues with the problem VM's OS disk.
Detaches the problem VM's OS disk from the rescue VM.
Performs a disk swap to swap the problem VM's OS disk from the rescue VM back to the problem VM.
Removes the resources that were created for the rescue VM, except the original OSDisk
And also the known limitations - It does not support:

Encrypted VMs
VMSS
Classic VMs

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by yungezz** [comment]
hi @diegoalb could you pls share link of the doc you're talking about? it seems a conceptual doc,  not azure cli reference doc.
