### ISSUE TITLE
Azure Devops Release Pipeline task named 'Azure App Service Deploy' is skipping some .dll files

### ISSUE THREAD

**Issue by bhanush3** [Azure/azure-cli-extensions#875]
Describe the bug
Azure Devops Release Pipeline task named 'Azure App Service Deploy' is skipping some .dll files

To Reproduce
create new release in release pipeline

Expected behavior
should deploy all .dll in bin folder or subfolder

Environment summary
I am deploying a .net API App using task version 4.. Package or Folder option: "$(System.DefaultWorkingDirectory)/**/.zip"
All other option in this task is left blank. There are no other tasks in release pipeline. In content of .zip package I can see there are some folders under path 'Content\D_C\a\1\s\project\Api\app.Api\obj\Debug\Package\PackageTmp\bin' named de, es, fr, it, ja, ko, ru and these folders have some .dll files which needs to be isntalled or updated. When I run Release pipeline it shows that it has successfully deployed the API App but I see logs I find out that it is not installing .dlls in de, es, fr, it, ja, ko, ru folders and also skipping some .dlls in bin folder which is breaking the API app in result.

Additional context

**Comment by yonzhan** [comment]
Devops

**Comment by SaurabhSharma-MSFT** [comment]
@bhanush3 Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.
