### ISSUE TITLE
az monitor app-insights api-key show does not return applications insights key

### ISSUE THREAD

**Issue by ehuggz** [Azure/azure-cli-extensions#879]
## Describe the bug
az monitor app-insights api-key show returns a blank line instead of the application insights key

**Command Name**
**az monitor app-insights api-key show**
Extension Name: application-insights. Version: 0.1.1.`

**Errors:**
No errors are displayed

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor app-insights api-key show --app {} -g {}`

## Expected Behavior
Application Insights key for the defined application insights application and resource group is returned.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.67 *

Extensions:
application-insights 0.1.1
azure-devops 0.11.0

```

**Comment by yonzhan** [comment]
add to S172

**Comment by jsntcy** [comment]
@ehuggz, I guess you want to get instrumentation key for application insights, is it true?
- If yes, then you should use the command `az monitor app-insights component show -g {} -a {}` which will return the result containing that instrumentation key.
`{
  "appId": "",
  "applicationId": "",
  "applicationType": "web",
  "connectionString": "InstrumentationKey=xxxxxxxx",
  "id": "",
  "instrumentationKey": "xxxxxxx",
  "type": "microsoft.insights/components",
  "workspaceResourceId": null
}`
- The command `az monitor app-insights api-key show --app {} -g {}` will return the API key. By default, there is no API key for an Application Insights. So it's the correct behavior that returns empty as there is no API key for your Application Insights.

**Comment by jsntcy** [comment]
@ehuggz, any update on this issue?

**Comment by jsntcy** [comment]
Close this now as no response from customer for a long time.
@ehuggz, if you think the issue still exists, please reopen this issue.
