### ISSUE TITLE
'Get Work Items Between Builds' support?

### ISSUE THREAD

**Issue by johndowns** [Azure/azure-cli-extensions#880]
Is there a way to invoke the [*Get Work Items Between Builds* API](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get%20work%20items%20between%20builds?view=azure-devops-server-rest-5.0) using the `az devops` commands?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7077ac1-bb22-976f-77f3-9a40cfcbce81
* Version Independent ID: b3841ca2-43a1-1438-7907-0240d06b7502
* Content: [az pipelines build](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/build?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines/build.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines/build.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@johndowns Currently this is not supported. I have filed a tracking request in our extensions repository here - https://github.com/Azure/azure-devops-cli-extension/issues/744

Closing this issue. Please follow the above ticket for updates.
