### ISSUE TITLE
Cannot Use Existing Service Connection

### ISSUE THREAD

**Issue by deecoaccela** [Azure/azure-cli-extensions#881]
[--service-connection SERVICE_CONNECTION] does not pick up existing service connections, --service-connection myserviceconnect keeps returning 

"Could not create service hooks subscription. The repository does not reference a service connection."

If I remove --service-connection I can select the existing Service Connection in the list and build is created

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2123ca-5408-8f93-6f5c-93fe74684523
* Version Independent ID: 7a03fe73-da7f-9b5a-38e7-ef51d85d49fd
* Content: [az pipelines](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines?view=azure-cli-latest#ext-azure-devops-az-pipelines-create)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@deecoaccela Can you try using the service connection Id instead of name. The help text does mention this though. 

```
--service-connection : Id of the Service connection created for the repository for GitHub repository. Use command az devops service-endpoint -h for creating/listing service_connections. Not required for Azure Repos.
```

To get the id of the service connection you can use list command ```az devops service-endpoint list```.

**Comment by deecoaccela** [comment]
> @deecoaccela Can you try using the service connection Id instead of name. The help text does mention this though.
> 
> ```
> --service-connection : Id of the Service connection created for the repository for GitHub repository. Use command az devops service-endpoint -h for creating/listing service_connections. Not required for Azure Repos.
> ```
> 
> To get the id of the service connection you can use list command `az devops service-endpoint list`.

@atbagga I have tried with the --service-connection , I get returned 

> Could not create service hooks subscription. The repository does not reference a service connection.

**Comment by deecoaccela** [comment]
@atbagga thanks, how to switch between projects ? as service connections appearing for default or first project created. cannot list for other projects tried az devops project -h

**Comment by atbagga** [comment]
Each command takes --project as an input parameter and this has preference over auto select (from local git repo) or auto configured (az devops configure project=XYZ). 

If you want to list service connections of some project use ```az devops service-endpoint list --project XYZ```. 

You can also check/change your default configured project using -
- ```az devops configure -l```
- ```az devops configure -d project=XYZ```

**Comment by deecoaccela** [comment]
ok, now I get 
"The user doesn't have access to the service connection(s) added to this pipeline or they are not found. Names/IDs: 12345-d558-66e7-a669-4229c137d692"

--service-connection '12345-d558-66e7-a669-4229c137d692'

tried with and without quotes, what should the syntax look like ?

**Comment by atbagga** [comment]
Quotes should not matter. 
Please run the commands with --debug flag to confirm from the logs that you are creating the pipeline in the same project where the service connection exists.

**Comment by deecoaccela** [comment]
TF400813: The user '61f6d37b-59b3-46a3-8227-7a469ac62b95\username@domain.com' is not authorized to access this resource.

**Comment by deecoaccela** [comment]
turns out I was using the wrong ID , there are 2 defined one for the user who created the service connection , the second id is the actual id of the service connection

**Comment by atbagga** [comment]
Closing the issue since it looks like it worked for you as per your comment. 
Incase you still have any issue please tag me to reopen this or feel free to open a new issue.
