### ISSUE TITLE
Support tags for resources created by az ml commands

### ISSUE THREAD

**Issue by eXXL** [Azure/azure-cli-extensions#883]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az ml

### Description of issue (in as much detail as possible)
The current az ml commands to not support tags. Therefore I have to figure out the resources created by the ML Workspace (storage account, compute target like AKS etc.) and add the tags by myself with az resource tag.

I would apreciate if a --tag parameter would be supported that allows to pass tags to the resources.

-----

**Comment by yonzhan** [comment]
ml

**Comment by rastala** [comment]
@eXXL Thank you for your feedback! I added this feature to our product backlog.

**Comment by rastala** [comment]
#please-close
