### ISSUE TITLE
Image Copy Error in between resource groups

### ISSUE THREAD

**Issue by lasantha78** [Azure/azure-cli-extensions#890]
## Describe the bug

**Command Name**
`az image copy
Extension Name: image-copy-extension. Version: 0.2.1.`

**Errors:**
```
Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'ubuntu-18.04-docker-centralus_os_disk_snapshot', '--resource-group', 'USF', '--source', '/subscriptions/9bb91a56-0e54-49c3-80d9-1d4131f8d153/resourceGroups/image-copy-rg/providers/Microsoft.Compute/snapshots/ubuntu-18.04-docker_os_disk_snapshot-centralus', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image copy --source-resource-group {} --source-object-name {} --target-location {} --target-resource-group {}`

## Environment Summary
```
Linux-4.18.0-25-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.68 *

Extensions:
image-copy-extension 0.2.1

```

**Comment by haroldrandom** [comment]
@fengzhou-msft Please take a look

**Comment by qwordy** [comment]
I've opened a PR to fix this issue. It will fixed soon.
https://github.com/Azure/azure-cli-extensions/pull/1172
