### ISSUE TITLE
Error in copy image

### ISSUE THREAD

**Issue by juank1400** [Azure/azure-cli-extensions#892]
## Describe the bug

**Command Name**
`az image copy
Extension Name: image-copy-extension. Version: 0.2.1.`

**Errors:**
```
Command '['/usr/bin/python', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'rhel75ocpbase_os_disk_snapshot', '--resource-group', 'PoCAVAL', '--source', u'/subscriptions/ec222f6e-25e3-4b7b-a08e-875c1542c33c/resourceGroups/PoCAVAL/providers/Microsoft.Compute/disks/ocp-app-base_OsDisk_1_8d17f4ed4f1b4c6dbb23ccc493394689', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image copy --source-resource-group {} --source-object-name {} --target-location {} --target-resource-group {}`

## Environment Summary
```
Linux-5.1.20-300.fc30.x86_64-x86_64-with-fedora-30-Thirty
Python 2.7.16
Shell: bash

azure-cli 2.0.70

Extensions:
image-copy-extension 0.2.1

```

**Comment by tamirkamara** [comment]
@qwordy this issue lacks details and fairly old. On the face of it, this issue is similar to ones already resolved. can you close this?
