### ISSUE TITLE
Remove 1000 output cap

### ISSUE THREAD

**Issue by Jeremy-Busuttil** [Azure/azure-cli-extensions#893]
When I use this command only 1000 results are returned...is there a way to remove this 1000 object cap so that it returns everything at once?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d535510f-f15c-3c79-c44d-34b7742a1544
* Version Independent ID: 334f9fc5-2811-f125-4faa-3fb90ec19559
* Content: [az boards](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/boards.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/boards.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by geverghe** [comment]
Hey @Jeremy-Busuttil - thank you for raising this feature request. I have opened a corresponding ticket on our repo so that we can track this on our project board and prioritize accordingly.

Link to issue on our repo - https://github.com/Azure/azure-devops-cli-extension/issues/827

**Comment by atbagga** [comment]
I am closing this issue since this is now getting tracked in the corresponding extension repo as linked in above comment.
