### ISSUE TITLE
`--repository-id` required?

### ISSUE THREAD

**Issue by jessehouwing** [Azure/azure-cli-extensions#894]
The underlying API supports `null` to apply the policy for the whole project. Is this supported here as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbca5089-8114-54d1-a2e8-4c9c6bcf70db
* Version Independent ID: 534b73ff-aa41-2f53-75a7-dbc46e421325
* Content: [az repos policy work-item-linking](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/policy/work-item-linking?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/repos/policy/work-item-linking.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/repos/policy/work-item-linking.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by gauravsaralMs** [comment]
@jessehouwing .. not currently
you can explore https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/policy?view=azure-cli-latest#ext-azure-devops-az-repos-policy-create 
This allows every kind of policy creation which are not supported by specific commands
more details:
https://docs.microsoft.com/en-us/azure/devops/cli/policy-configuration-file?view=azure-devops 

Let me know if you run into any issues

**Comment by jessehouwing** [comment]
I figured that. Cause that's what I've been using previously.

**Comment by geverghe** [comment]
@jessehouwing - Hope the above clarification answers your query. I am closing this issue. Feel free to reopen the issue in case it does not answer your query. Would be super helpful for us if you could open any issue related to `az devops` | `az pipelines` | `az artifacts` | `az repos` | `az boards` on https://github.com/Azure/azure-devops-cli-extension/issues .
