### ISSUE TITLE
Front Door frontend-endpoint session-affinity-enabled param not working, and inconsistent accepted values compared to other params

### ISSUE THREAD

**Issue by philliproux** [Azure/azure-cli-extensions#895]
Extension: Front Door
Setting **--session-affinity-enabled** param with "az network front-door frontend-endpoint" gives the following error:

BadRequest - Property FrontdoorEntity.FrontendEndpoints[0].Properties.SessionAffinityEnabledState' cannot be set to 'False'. Acceptable values are: Enabled, Disabled

Repo Example:
az network front-door frontend-endpoint create --front-door-name "pr-active-frontdoor-demo-2" --host-name "pr-active-frontdoor-demo-2.azurefd.net" --name "DefaultFrontendEndpoint" --resource-group "pr-active-frontdoor-demo-2" --session-affinity-enabled false

Change the session affinity param to Enabled or Disabled gives the following:
az network front-door frontend-endpoint create: 'Enabled' is not a valid value for '--session-affinity-enabled'. See 'az network front-door frontend-endpoint create --help'.

CLI help states the following:
az network front-door frontend-endpoint create --help
--session-affinity-enabled      : Whether to allow session affinity on this host.  Allowed values: **false, true.**

Sample JSON extract of Session Affnity from resource:
"sessionAffinityEnabledState": "Disabled",

Recommend to also change accepted values of --session-affinity-enabled param to be "Enabled, Disabled" to be in line with resource json representation and other params eg --caching 

https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/routing-rule?view=azure-cli-latest#ext-front-door-az-network-front-door-routing-rule-create
-----

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172
