### ISSUE TITLE
Azure Firewall extension docs do not match CLI - subnet vs vnet-name

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-cli-extensions#900]
### Extension name (the extension in question)
azure-firewall

### Description of issue (in as much detail as possible)
Similar issue to #479 has resurfaced, the docs and usage messages do not appear to line up anymore with regards to the usage of `--subnet`.

The `az network firewall ip-config create` [here](https://docs.microsoft.com/en-us/cli/azure/ext/azure-firewall/network/firewall/ip-config?view=azure-cli-latest#ext-azure-firewall-az-network-firewall-ip-config-create) make no reference to `--subnet` nor do the help docs (screenshot below):

![image](https://user-images.githubusercontent.com/77808/62978132-67488380-bdd5-11e9-860c-254b38f35542.png)

However, if you run a command it will tell you the use of `--subnet` (with either an ID or name) is mandatory:
```
az network firewall ip-config create     --resource-group $FIREWALL_RG     --name "${FIREWALL_NAME}-public"     --vnet-name "${AKS_VNET_NAME}"     --subnet "${AKS_SUBNET_ID}"     --firewall-name "${FIREWALL_NAME}"     --public-ip-address "${FIREWALL_PUBLIC_IP_NAME}"
usage: az network firewall ip-config create [-h] [--verbose] [--debug]
                                            [--output {json,jsonc,table,tsv,yaml,none}]
                                            [--query JMESPATH]
                                            [--subscription _SUBSCRIPTION]
                                            --resource-group
                                            RESOURCE_GROUP_NAME
                                            --firewall-name NAME --name
                                            ITEM_NAME --public-ip-address
                                            PUBLIC_IP_ADDRESS --vnet-name NAME
                                            [--private-ip-address PRIVATE_IP_ADDRESS]
az network firewall ip-config create: error: incorrect usage: ( --subnet ID | --subnet NAME --vnet-name NAME)
```

That's fine then, let's run it with a subnet ID and without `--vnet-name`:
```
az network firewall ip-config create     --resource-group $FIREWALL_RG     --name "${FIREWALL_NAME}-public"      --subnet "${AKS_SUBNET_ID}"     --firewall-name "${FIREWALL_NAME}"     --public-ip-address "${FIREWALL_PUBLIC_IP_NAME}"
az network firewall ip-config create: error: the following arguments are required: --vnet-name
```

Okay, let's add `--vnet-name` and change `--subnet` to a vnet name instead of resource ID:

```
az network firewall ip-config create     --resource-group $FIREWALL_RG     --name "${FIREWALL_NAME}-public"  --vnet-name ${AKS_VNET_NAME}     --subnet "${AKS_SUBNET_NAME}"     --firewall-name "${FIREWALL_NAME}"     --public-ip-address "${FIREWALL_PUBLIC_IP_NAME}"
Subnet name /subscriptions/30036f7b-f3de-4a39-ba48-75bd34cf0782/resourceGroups/aksdemo/providers/Microsoft.Network/virtualNetworks/aksdemo-vnet/subnets/aksdemo-cni-cp is invalid for Azure Firewall. Azure Firewall can only be created in subnet with name 'AzureFirewallSubnet'.
```
(Silly restriction imo, but this isn't the place for that feedback). Once I re-created the subnet with name `AzureFirewallSubnet`, running the command without `--subnet` altogether worked:
```
az network firewall ip-config create \
    --resource-group $FIREWALL_RG \
    --name "${FIREWALL_NAME}-public" \
    --vnet-name "${AKS_VNET_NAME}" \
    --firewall-name "${FIREWALL_NAME}" \
    --public-ip-address "${FIREWALL_PUBLIC_IP_NAME}"
```

**Comment by haroldrandom** [comment]
@MyronFanQiu Please take a look

**Comment by MyronFanQiu** [comment]
@stewartadam Hello. This issue should be fixed now. Please uninstall the extension by `az extension remote -n azure-firewall` and install it again `az extension add -n azure-firewall`.

**Comment by yonzhan** [comment]
add to S171

**Comment by MyronFanQiu** [comment]
This should be already fixed.
