### ISSUE TITLE
Additional team features

### ISSUE THREAD

**Issue by jessehouwing** [Azure/azure-cli-extensions#903]
In the past the ALLM Rangers have built the Tfs Team Tools. These have some additional features that would be great for this set of commands:

https://github.com/jessehouwing/TfsTeamTools

* ListTeams
* GetDefaultTeam
* SetDefaultTeam
* CreateTeam
* DeleteTeam
* RenameTeam
* ListTeamMembers
* AddUser
* RemoveUser
* Set/Clear User/Team profile image
* Convert Group to Team
* ListTeamAdministrators 
* AddTeamAdministrator
* RemoveTeamAdministrator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aab5af2c-7c87-d5a7-e52a-d56b902eb44a
* Version Independent ID: c58f9b5a-db21-61e3-7512-e346c678ac56
* Content: [az devops team](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/team?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/team.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/team.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by geverghe** [comment]
Thank you for the feedback @jessehouwing
