### ISSUE TITLE
Criteria for scaling down

### ISSUE THREAD

**Issue by asc-adean** [Azure/azure-cli-extensions#912]
What is the criteria for specifying a node to be removed from a nodepool?

In my instance, I had a node that was no longer responding to `port-forward`, so I scaled up to a second node in that nodepool, migrated the resources over to the new node, cordoned the old node and drained it.

When I scaled back down to 1 node, it removed the new node rather than the old one.  This is not expected behavior -- why would the old, cordoned, drained node have any precedence over the new, in-use node?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92444562-0540-adf6-3c3e-33b181bd10d4
* Version Independent ID: 3267c97e-819b-d945-fc28-2b75e35f2647
* Content: [az aks nodepool](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks/nodepool?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jluk** [comment]
@asc-adean assuming you are using VMSS, the manual scaling will abide by the below best efforts. We will be updating our AKS documentation to discuss this a bit and include some of this info for help, thanks for the report.

https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#if-i-reduce-my-scale-set-capacity-from-20-to-15-which-vms-are-removed
