### ISSUE TITLE
--Include parameter is not available in az graph query. 

### ISSUE THREAD

**Issue by ChendrayanV** [Azure/azure-cli-extensions#915]
az graph query --help - Returns no include parameter. Docs needs to be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75d1021b-9184-56de-3a65-4680868c9143
* Version Independent ID: f2fb2ab8-c0c6-5350-a99a-5a5b90e2b14b
* Content: [az graph](https://docs.microsoft.com/en-us/cli/azure/ext/resource-graph/graph?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/resource-graph/graph.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/resource-graph/graph.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
Have you try the latest azure-cli/ auzre-cli-extension? This could be changed.

Looking forward to your reply.

**Comment by yonzhan** [comment]
resource graph

**Comment by snaheth** [comment]
+1 to what @haroldrandom said above. The ``--include`` parameter shows up now:

![image](https://user-images.githubusercontent.com/8368618/94728765-92fa3600-0315-11eb-92a0-b57cf81d86e3.png)
