### ISSUE TITLE
Build List Not showing all Builds

### ISSUE THREAD

**Issue by svelango** [Azure/azure-cli-extensions#917]
I trying to pull list of builds filtering by definition from the start of project but the number is very less. The analytics dashboard for 30 days is 150 and for 1 year project I get 183. Can you please with this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7077ac1-bb22-976f-77f3-9a40cfcbce81
* Version Independent ID: b3841ca2-43a1-1438-7907-0240d06b7502
* Content: [az pipelines build](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/build?view=azure-cli-latest#ext-azure-devops-az-pipelines-build-list)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines/build.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines/build.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
devops

**Comment by SaurabhSharma-MSFT** [comment]
@svelango Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.

**Comment by svelango** [comment]
We can close this. 
    On Tuesday, February 15, 2022, 06:24:27 PM CST, SaurabhSharma-MSFT ***@***.***> wrote:  
 
 


@svelango Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
