### ISSUE TITLE
az extension add --name aks-preview fails to install

### ISSUE THREAD

**Issue by dapolloxp** [Azure/azure-cli-extensions#919]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)

Cannot update or install the aks-preview extension

Debug error shows issue for checksum

Downloaded to /var/folders/4y/p5llxl6d2x5gwhdnfbjzxr0w0000gn/T/tmpwkxks6xm/aks_preview-0.4.10-py2.py3-none-any.whl
Validating the extension /var/folders/4y/p5llxl6d2x5gwhdnfbjzxr0w0000gn/T/tmpwkxks6xm/aks_preview-0.4.10-py2.py3-none-any.whl
Invalid checksum for /var/folders/4y/p5llxl6d2x5gwhdnfbjzxr0w0000gn/T/tmpwkxks6xm/aks_preview-0.4.10-py2.py3-none-any.whl. Expected '412e936f0505550e1f2130ec45e412dcfbff61b6f2b0443295ab15c313341cfe', computed '156174affc440ebe2373007166b737e7807cf59719a51fed917129ff3be377ca'.
-----

**Comment by jkucan-nlight** [comment]
This appears to have been resolved. I was able to install the extension.
```
azure-cli                         2.0.71 *

command-modules-nspkg               2.0.3
core                              2.0.71 *
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
aks-preview                       0.4.12

Python location '/usr/local/Cellar/azure-cli/2.0.71/libexec/bin/python'
Extensions directory '/Users/jkucan/.azure/cliextensions'

Python (Darwin) 3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by yonzhan** [comment]
It seemed that this issue was resolved. I will close it right now.

**Comment by yonzhan** [comment]
Please let us know if any further question, thanks.
