### ISSUE TITLE
az aks get-versions --location northeurope fails with unavailable API version (2019-08-01) when aks-preview is installed

### ISSUE THREAD

**Issue by hallgeirl** [Azure/azure-cli-extensions#924]
## Describe the bug
Using the latest azure cli (2.0.72) on Windows 10, I installed the aks-preview extension through: az extension add --name aks-preview
Afterwards, I tried: 
az aks get-versions --location northeurope
This crashes with the error below: APIVersion 2019-08-01 is not available. 
When I tried this BEFORE I installed aks-preview 0.4.11, the command worked as expected.

**Command Name**
`az aks get-versions
Extension Name: aks-preview. Version: 0.4.11.`

**Errors:**
```
APIVersion 2019-08-01 is not available
Traceback (most recent call last):
pip-install-qxmmnr17\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 654, in _run_job
Temp\pip-install-qxmmnr17\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
cli\core\commands\__init__.py, ln 305, in __call__
azure\cli\core\__init__.py, ln 476, in default_command_handler
cliextensions\aks-preview\azext_aks_preview\_client_factory.py, ln 21, in cf_container_services
    return get_container_service_client(cli_ctx).container_services
azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\container_service_client.py, ln 169, in container_services
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-08-01 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
1. Install azure cli 2.0.72
2. Install aks-preview 0.4.11
3. Log in
4. Run az aks get-versions --location northeurope

- _Put any pre-requisite steps here..._
- `az aks get-versions --location {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.72

Extensions:
aks-preview 0.4.11

```

**Comment by seanmck** [comment]
Fixed in 0.4.12.
