### ISSUE TITLE
az aks create unrecognized argument: --enable-vmss

### ISSUE THREAD

**Issue by stumueller** [Azure/azure-cli-extensions#927]
When creating an AKS cluster, I connot specify --enable-vmss

To reproduce:
register features
az feature register --name MultiAgentpoolPreview --namespace Microsoft.ContainerService
az feature register --name VMSSPreview --namespace Microsoft.ContainerService
I have also registered 
az feature register --name WindowsPreview --namespace Microsoft.ContainerService

when registered
az provider register --namespace Microsoft.ContainerService

ran command to create new AKS cluster:
az aks create \
    --resource-group s8st00aksrsg \
    --name s8st00aks \
    --network-plugin azure \
    --vnet-subnet-id /subscriptions/5ab19b7d-0edc-442d-aabc-9a7819194ee5/resourceGroups/ib-ess-enterprise-stag01-sql/providers/Microsoft.Network/virtualNetworks/VNet1/subnets/Cluster \
    --docker-bridge-address 172.17.0.1/16 \
    --dns-service-ip 10.5.0.10 \
    --service-cidr 10.5.0.0/24 \
	--enable-vmss \
    --generate-ssh-keys \
	--kubernetes-version 1.14.6 \
	--windows-admin-password xxxxxxxxx \
    --windows-admin-username xxxxxxxxx \
	--enable-addons monitoring \
	--location northeurope \
	--admin-username xxxxxxxxx \
	--node-vm-size Standard_b2ms \
	--nodepool-name lnxnp \
	--node-resource-group s8st00aksresrsg

this results in error
az: error: unrecognized arguments: --enable-vmss
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {aks} ...

Environment:
azure-cli                         2.0.72

command-modules-nspkg               2.0.3
core                              2.0.72
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
aks-preview                       0.4.11

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\p10164185\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
-----

**Comment by stsaid** [comment]
Have "they" changed the arguments? `az aks create --help` shows....

>   --vm-set-type   : Agent pool vm set type. VirtualMachineScaleSets or AvailabilitySet.

**Comment by palma21** [comment]
Yes there are 2 new arguments that will be used moving forward and from GA on the main CLI, but the latest version of the extension should support both.

Could you try with the latest and confirm if you can repro?

**Comment by jluk** [comment]
Closing this issue for user feedback requested on 9/23. As Jorge mentioned we have support for the vm-set-type now in both core and extension which supports choosing vmss/vmas.
