### ISSUE TITLE
Listing Application Insights components throws an error

### ISSUE THREAD

**Issue by deckerbd** [Azure/azure-cli-extensions#928]
## Describe the bug

After installing the Application Insights extension, I'm unable to get a list of components in my current subscription.

**Command Name**
`az monitor app-insights component show`
`Extension Name: application-insights. Version: 0.1.1.`

**Errors:**
```
Unable to deserialize to object: ApplicationInsightsComponentPaged, AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
pip-install-qxmmnr17\msrest\msrest\serialization.py, ln 1291, in _deserialize
pip-install-qxmmnr17\msrest\msrest\serialization.py, ln 1065, in rest_key_extractor
AttributeError: 'list' object has no attribute 'get'

...

pip-install-qxmmnr17\msrest\msrest\serialization.py, ln 1291, in _deserialize
pip-install-qxmmnr17\msrest\msrest\serialization.py, ln 1065, in rest_key_extractor
msrest.exceptions.DeserializationError: Unable to deserialize to object: ApplicationInsightsComponentPaged, AttributeError: 'list' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Install the Application Insights module (`az extension add --name application-insights`)
- Run `az monitor app-insights component show`

## Expected Behavior

A list of all components with no exception thrown.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.72

Extensions:
application-insights 0.1.1

```

**Comment by yonzhan** [comment]
app-insights

**Comment by navba-MSFT** [comment]
@deckerbd Apologies for the late reply. I was able to run [this](https://docs.microsoft.com/en-us/cli/azure/monitor/app-insights/component?view=azure-cli-latest#az-monitor-app-insights-component-show) command without any issues. Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the Az CLI and test the behavior again? Awaiting your reply.

**Comment by deckerbd** [comment]
@navba-MSFT No worries. Looks to be working for me now, closing. :)
