### ISSUE TITLE
tsv and table outputs won't work with az monitor log-analytics query

### ISSUE THREAD

**Issue by paratz** [Azure/azure-cli-extensions#936]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

az monitor log-analytics query
### Description of issue (in as much detail as possible)

-----
While querying a workspace, the json and yaml output work fine.

But if I changed to tsv, I obtain a number "1" and the table output will show nothing:

C:\windows\system32>az monitor log-analytics query -w 57ebcc86-e39d-4183-947e-5e2aa377e569 --analytics-query "Heartbeat"  --output tsv
1

C:\windows\system32>az monitor log-analytics query -w 57ebcc86-e39d-4183-947e-5e2aa377e569 --analytics-query "Heartbeat"  --output table

C:\windows\system32>

Thanks,
<img width="817" alt="Anotación 2019-09-04 135750" src="https://user-images.githubusercontent.com/22793342/64278978-0582c180-cf1c-11e9-9ff1-7b89bc47ed24.png">

**Comment by alexeldeib** [comment]
Taking a look

**Comment by alexeldeib** [comment]
@jiasli I see you added service attention, but typically output processing is done centrally by CLI or SDK. I'm able to reproduce this and confirmed via debug that the SDK and API output is correct, and contains quite a bit more JSON than is shown here. 

Could you please take a look at this from CLI side, or assign the appropriate person from CLI to look at the output logic? cc @lmazuel in case you have context (I realize this is CLI not SDK, but you seem quite familiar with all the `az` python goodies 😄)

**Comment by alexeldeib** [comment]
@paratz thanks for reporting, is there a scenario you'd like to use this for that is blocked, or you just prefer the more human-readable output? 

I tend to use TSV when doing automation because it strips quotes unlike JSON. If this is your use, might be nice to pair `az` output with `jq -r` as a workaround.

**Comment by paratz** [comment]
One of our customer is looking to automate a script using Az Script that generates a report from a Log Analytics query. This query produces more than 10k results, and they need this report in csv/tsv to be processed by some other system....

**Comment by lgodmer** [comment]
@paratz Has the customer tried the workaround that @alexeldeib mentioned? 

> I tend to use TSV when doing automation because it strips quotes unlike JSON. If this is your use, might be nice to pair `az` output with `jq -r` as a workaround.

@jiasli @lmazuel can you investigate this from the CLI side?

**Comment by paratz** [comment]
@alexeldeib I'm using Windows, I've just tried the windows version of jq with -r and I don't get a "human" readable format like tsv or table.... attaching an example
![Anotación 2019-09-24 182158](https://user-images.githubusercontent.com/22793342/65551401-4442e080-def8-11e9-8090-1a4432b4ec80.png)

**Comment by alexeldeib** [comment]
jq won't be able to help you with readable output, only stripping quotes/indexing fields to clean and extract what you want. For the readability issue, we need the CLI team to fix this properly. Discussed with them offline but TBD on fix 🙁

**Comment by yonzhan** [comment]
@MyronFanQiu  please take a look and comment.

**Comment by MyronFanQiu** [comment]
@paratz Hello. I'm working on it.

**Comment by MyronFanQiu** [comment]
@alexeldeib Looks like the server just changed the structure of the response recently. Am I right? I just want to confirm so that I can change my codes.

**Comment by ristoponni-qoco** [comment]
Unfortunately does not seem to work. Tested on 2024-05-20, up-to-date Windows 11, Azure CLI versions both 2.59 and 2.60, application-insights extension version 1.21.
Without specifying the output format I get the expected results in JSON. If I specify TSV I get the number 1 and if table, I get nothing.
