### ISSUE TITLE
Fatal error running az postgres up overriding default location

### ISSUE THREAD

**Issue by duncanjw** [Azure/azure-cli-extensions#941]
## Describe the bug

**Command Name**
`az postgres up
Extension Name: db-up. Version: 0.1.13.`

**Errors:**
```
FATAL:  no pg_hba.conf entry for host "31.154.209.122", user "shockedRelish9", database "sampledb", SSL on
FATAL:  no pg_hba.conf entry for host "31.154.209.122", user "shockedRelish9", database "sampledb", SSL on
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
...
cliextensions/db-up/psycopg2/__init__.py, ln 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  no pg_hba.conf entry for host "31.154.209.122", user "shockedRelish9", database "sampledb", SSL on
FATAL:  no pg_hba.conf entry for host "31.154.209.122", user "shockedRelish9", database "sampledb", SSL on
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Trying out the Quickstart but overriding defaults
- `az postgres up -g myPostgreSQLGroup -l centralus`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.72

Extensions:
db-up 0.1.13

```

**Comment by rachel-msft** [comment]
Thank you for your feedback @duncanjw.

Adding @yugangw-msft @achandmsft to review.

**Comment by rachel-msft** [comment]
@achandmsft and Lomis for follow up

**Comment by yonzhan** [comment]
add to S173

**Comment by rachel-msft** [comment]
I believe this is still on-track for yonzhan's team's s173

**Comment by Juliehzl** [comment]
Hi @duncanjw , it should be fixed in latest version. could you upgrade version with `az extension update -n db-up` and try again?
