### ISSUE TITLE
Error when trying to enable ingress

### ISSUE THREAD

**Issue by tndinh200292** [Azure/azure-cli-extensions#943]
## Describe the bug

**Command Name**
`az aks enable-addons
Extension Name: aks-preview. Version: 0.4.14.`

**Errors:**
```
'ingress'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1703, in aks_enable_addons
    workspace_resource_id=workspace_resource_id, subnet_name=subnet_name, no_wait=no_wait)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1739, in _update_addons
    addon = ADDONS[addon_arg]
KeyError: 'ingress'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --addons {} --name {} --resource-group {}`

## Environment Summary
```
Darwin-18.0.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.71 *

Extensions:
aks-preview 0.4.14

```

**Comment by palma21** [comment]
???

**Comment by jluk** [comment]
@tndinh200292 it looks like you're trying to register the preview extension, which is not the same as an AKS add-on.

Follow instructions here to install the CLI extension for aks-preview.
https://github.com/Azure/azure-cli-extensions/tree/master/src/aks-preview
