### ISSUE TITLE
Azure Firewall: add threat intel mode

### ISSUE THREAD

**Issue by number213** [Azure/azure-cli-extensions#950]
**Extension name (the extension in question)**
azure-firewall

**Resource Provider**
`Microsoft.Network`

**Description of Feature or Work Requested**
Add parameter to set mode of Threat Intelligence (three modes: `Alert`, `Deny`, `Off`)

**Minimum API Version Required**
2018-12-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/5143

**Target Date**
No specific target date

**Comment by MyronFanQiu** [comment]
Sorry. I just saw this issue. I will take a look at it recently.

**Comment by yonzhan** [comment]
add to S171
