### ISSUE TITLE
Support on GovCloud

### ISSUE THREAD

**Issue by mjannapureddy07** [Azure/azure-cli-extensions#959]
Hello, 

We know this feature is in preview and is not yet generally available. I see the Log Analytics API URL is used in the extension module is https://api.loganalytics.io. But as we use Gov Cloud (Azure US Government) we hit a different URL https://api.loganalytics.us . Does this command support for Log Analytics in Gov Cloud, if yes how? If No is there any roadmap for implemetation? and where can I check the status of it ? 

Also it would be great to add the extension installation info in the documentation too. We wasted atleast an hour searching information about it and can find only from the Comments discussion that it need to be added as am extension. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0fd6a58-ac1a-fa45-8d96-579b4af36499
* Version Independent ID: 4098ca97-1b85-eb29-18e9-e6f0495fd030
* Content: [az monitor log-analytics](https://docs.microsoft.com/en-us/cli/azure/ext/log-analytics/monitor/log-analytics?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/log-analytics/monitor/log-analytics.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rloutlaw** [comment]
Extension install documentation is on the Docs feature roadmap and in planning for Azure CLI reference. 

I can't answer the question about the Log Analytics API but did want to thank you for taking the time to report the problem you had with the docs.

**Comment by MyronFanQiu** [comment]
@mjannapureddy07 Hello. I will take a look at this issue.  I'm the new person maintain monitor related commands and may need some time. Thanks.

**Comment by hemsh** [comment]
@MyronFanQiu Two changes are required for Azure Government Cloud. I guess you need to make cloud name as an optional parameter and based on that End Point needs to be changed in those two places. I have tested in my govcloud and is working as expected.

```
$:~/.azure/cliextensions# diff ./log-analytics/azext_loganalytics/_client_factory.py*
13c13
<         resource="https://api.loganalytics.us")
---
>         resource="https://api.loganalytics.io")

$:~/.azure/cliextensions# diff ./log-analytics/azext_loganalytics/vendored_sdks/loganalytics/log_analytics_data_client.py*
36c36
<             base_url = 'https://api.loganalytics.us/v1'
---
>             base_url = 'https://api.loganalytics.io/v1'

$:~/.azure/cliextensions# az cloud show | jq '.name'
"AzureUSGovernment"
```

**Comment by yonzhan** [comment]
add to S171

**Comment by haroldrandom** [comment]
@mjannapureddy07 Could you have a test the patched PR I submit? Can it work?

**Comment by haroldrandom** [comment]
@mjannapureddy07 The fix has been merged. You could try to upgrade to 0.2.0 to have a try.
