### ISSUE TITLE
I get an error downloading universal packages from the command line

### ISSUE THREAD

**Issue by Miles-Davies-HORIBA** [Azure/azure-cli-extensions#964]
I get an error when downloading the packages using the command line provided by Azure DevOps web UI. The package seems to be in the appropriate universal artifact store.
I uploaded some new packages without any obvious error but there seems to be an issue downloading any package, including ones I had previously been able to download.

The 
**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.9.0.`

**Errors:**
```
sequence item 16: expected str instance, NoneType found
Traceback (most recent call last):
pip-install-dsvrkf2x\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 560, in execute
cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
cli\core\commands\__init__.py, ln 609, in _run_job
azext_devops\dev\common\exception_handler.py, ln 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
Temp\pip-install-dsvrkf2x\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 588, in _run_job
...
azext_devops\dev\common\external_tool.py, ln 71, in run
    self.start(command_args, env)
azext_devops\dev\common\external_tool.py, ln 29, in start
    logger.debug("Running external command: %s", ' '.join(command_args))
TypeError: sequence item 16: expected str instance, NoneType found
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az artifacts universal download --organization "https://dev.azure.com/my-org/" --feed "testing-artifacts-private" --name "dev-express" --version "6.3.2" --path .`

## Expected Behavior
I get the package downloaded
## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.65 *

Extensions:
azure-devops 0.9.0

```
## Additional Context
I have recently updated to the latest Visual Studio 2019 with .Net Core 3.0. Running the command in PowerShell 5

**Comment by maggiepint** [comment]
Hi! Thanks for the feedback. I have routed to the appropriate team for feedback.

**Comment by Miles-Davies-HORIBA** [comment]
This seems to be this issue #724 as I added the --file-filter '*' and it worked. I am clean installing the latest release.

**Comment by elbatk** [comment]
Closing this as it looks like it's already been fixed, please let us know if you have the same issue after installing latest @Miles-Davies-HORIBA

**Comment by Miles-Davies-HORIBA** [comment]
Hi @elbatk, installing the latest released version did not fix this issue. I haven't tried getting an un-released one from github. If I copy/paste the instructions to download from Azure DevOps it doesn't work because of this issue.
Not sure of the release cycle or when #724 should ship or even if this is the same issue.
