### ISSUE TITLE
how to `monitor-events` on azure portal?

### ISSUE THREAD

**Issue by chinmaychhajed** [Azure/azure-cli-extensions#968]
Hello,

I want to know how do I monitor events of my device on Azure Portal([IoT Hub](https://portal.azure.com)) which can be done in command line through `az iot hub monitor-events -n <name> --login <connection string>`.

Thanks in advance.

**Comment by jlian** [comment]
Hi, we don't have the equivalent of `az iot hub monitor-events` on the Azure portal AFAIK. @iluican correct me if something changed.

**Comment by chinmaychhajed** [comment]
Feel free to close the issue if you are sure we cannot monitor events online on Azure portal and it can only be done through CLI.
