### ISSUE TITLE
JMESPath query not working..!!

### ISSUE THREAD

**Issue by ngregistrations** [Azure/azure-cli-extensions#969]
Hi,

Trying to understand why this is not working..!!

az devops security group list --query "[?displayName=='PROPS'].descriptor" --org $org --project $prj

Using MS VSCode, with the JMESPath for VSCode EXTENSION.  I create a json with the information of 2 groups, then run the same query [?displayName=='PROPS'].descriptor and I get the data I need.

![image](https://user-images.githubusercontent.com/53952877/65794858-dd067580-e11d-11e9-804b-09e87747cfda.png)

But.. when I use the query in AZ, does not get me anything..

![image](https://user-images.githubusercontent.com/53952877/65794960-0f17d780-e11e-11e9-83c6-387ffa5f2264.png)

Any help would be appreciated.

Thanks
Norman.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5348dfb5-d361-4857-1459-6d7f3cbf5d6c
* Version Independent ID: 50319cc5-540d-6689-e5e7-748281d7d9ee
* Content: [az devops security group](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/security/group?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/security/group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/security/group.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
This is because the security group array is in propery `graphGroups`:

```jsonc
{
  "continuationToken": null,
  "graphGroups": [
    {
      "description": "The default project team.",
      "descriptor": "",
      "displayName": "public Team",
      // ...
    },
    // ...
  ]
}
```

Thus the query needs to be 

```
az devops security group list --organization https://dev.azure.com/{}/ --project {} \
--query "graphGroups[?displayName=='{}'].descriptor" -o tsv

vssgp.Uy0x...
```

**Comment by ngregistrations** [comment]
Hi Jiasli,

Thank you very much, it worked.  I know this is pretty basic, but I am having so much difficulty trying to wrap my head around this JSEMPath, have not been able to find real examples on the web.

Either way, thank you very much.

**Comment by ngregistrations** [comment]
Hi,
Sorry to keep bugging with this... but tried to follow your example... but in another list, and still keep getting nothing..  this time is with devops users.

![image](https://user-images.githubusercontent.com/53952877/66067567-b4f18a80-e500-11e9-9b08-ec704f1d4cac.png)

I captured the object, to see what is the property name is... in this case show "items"  so I tried and keep getting nothing...

What am I doing wrong?

**Comment by ngregistrations** [comment]
ran the same exersice, in MS Code, and the query worked, so just needed to add the property name "items"

![image](https://user-images.githubusercontent.com/53952877/66067897-6c869c80-e501-11e9-864b-4c40b5a9a309.png)

**Comment by atbagga** [comment]
This http://jmespath.org/ has tutorials and examples on pretty much all different things. There might be some things you will be able to figure out just playing with it as you did above. 

Closing this issue because it seems like you were able to get it working. 
Please file a new issue if you face any issues.
