### ISSUE TITLE
Sample configuration file to create service-endpoint from CLI

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Azure/azure-cli-extensions#971]
`az devops service-endpoint create`  creates a service-endpoint from configuration file. If a sample configuration file is provided then it's helpful.

I am referring to documentation here - https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/service-endpoint?view=azure-cli-latest#ext-azure-devops-az-devops-service-endpoint-create

**Comment by maggiepint** [comment]
Hi! Thanks for the feedback. I have routed to the appropriate team for follow up.

**Comment by atbagga** [comment]
@prabhakarreddy1234 Documentation is already there - https://docs.microsoft.com/en-us/azure/devops/cli/service_endpoint?view=azure-devops#create-service-endpoint-using-configuration-file

We will work on putting out a link to this in the doc in the command help. 

Let us know if this helps.

**Comment by prabhakarreddy1234** [comment]
@atbagga  Thanks. Do we have to pass only file path or can we also pass raw json object to `az devops service-endpoint create` ?

If we can't pass raw json object then it's not useful in automating this process.

**Comment by atbagga** [comment]
It only accepts file path.. You can still automate file creation.. e.g. how i am doing here - https://github.com/atbagga/PsSamples/blob/master/DevopsVarGroup/VarGroupUpdate.ps1

Regarding the stdin input there is recent issue filed here which you can vote on OR follow for updates - https://github.com/Azure/azure-devops-cli-extension/issues/816

**Comment by geverghe** [comment]
@prabhakarreddy1234 - I am closing this issue. Feel free to re-open in case the guidance is not clear. Would be super useful for us next time if you could directly open an issue on our repo - Azure/azure-devops-cli-extension in case there are any issues in the pipelines command group.
