### ISSUE TITLE
.github/PULL_REQUEST_TEMPLATE.md inconsistency

### ISSUE THREAD

**Issue by chewong** [Azure/azure-cli-extensions#98]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Description of issue (in as much detail as possible)
-----
`scripts/ci/test_integration.py` no longer exists but it is still referenced in https://github.com/Azure/azure-cli-extensions/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by derekbekoe** [comment]
@chewong If possible, create a PR for this small change.
