### ISSUE TITLE
Invalid Colon Separator

### ISSUE THREAD

**Issue by deploymentking** [Azure/azure-cli-extensions#985]
The cli command says the following are allowed values
```Allowed values: ,, -, ., /, ;, _, __.``` 
Yet the documentation above says 
```Supported values: '.', ',', ';', '-', '_', '__', '/', ':', ''.```
When I try to use the CLI with a colon : separator I get errors. Is this documentation incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb3ec9f2-e5cd-d79e-ebd7-8d726f3d90df
* Version Independent ID: 287f4d1d-00c5-1686-8aa4-e198ff196a05
* Content: [az appconfig kv](https://docs.microsoft.com/en-us/cli/azure/ext/appconfig/appconfig/kv?view=azure-cli-latest#ext-appconfig-az-appconfig-kv-import)
* Content Source: [latest/docs-ref-autogen/ext/appconfig/appconfig/kv.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/appconfig/appconfig/kv.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by maggiepint** [comment]
@jamesc can someone from your team help out here?

**Comment by yonzhan** [comment]
@haroldrandom  please take a look.

**Comment by haroldrandom** [comment]
please paste your original command without confidential and what it returns.

BTW, which SHELL are you using?

**Comment by haroldrandom** [comment]
Closed as long time no response. Feel free to reopen.
