### ISSUE TITLE
Importing Key Values from YAML

### ISSUE THREAD

**Issue by deploymentking** [Azure/azure-cli-extensions#986]
If I import via JSON with 
```az appconfig kv import --name mystore --label mylabel --source file --format json --separator . --path ./import.json --verbose```
I get no errors.
If I convert the JSON to YAML and run the same import with
```az appconfig kv import --name mystore --label mylabel --source file --format yaml --separator . --path ./import.yml --verbose```
I get the following warning...
```
/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appconfig/keyvalue.py:512: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for yaml_data in list(yaml.load_all(config_file)):
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb3ec9f2-e5cd-d79e-ebd7-8d726f3d90df
* Version Independent ID: 287f4d1d-00c5-1686-8aa4-e198ff196a05
* Content: [az appconfig kv](https://docs.microsoft.com/en-us/cli/azure/ext/appconfig/appconfig/kv?view=azure-cli-latest#ext-appconfig-az-appconfig-kv-import)
* Content Source: [latest/docs-ref-autogen/ext/appconfig/appconfig/kv.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/appconfig/appconfig/kv.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by maggiepint** [comment]
@jamesc this as well

**Comment by yonzhan** [comment]
@maggiepint appconfig command has been moved to azure cli core. Please tryout the core azure cli command. If you still have question, please open an issue on azure cli repo.
