### ISSUE TITLE
az pipelines variable create not workign for Release Definition

### ISSUE THREAD

**Issue by abhiramani-iptiq** [Azure/azure-cli-extensions#989]
Hi
i am running this command  for my release definition
az pipelines variable create --name "Hello" --value "world" --pipeline-name "Helm 02 All Release"
i am getting error "There were no build definitions matching name Helm 02 All Release"
does this mean variable can be created just for build definitions? how do i create variable on my release definition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ec3d76-5307-77a2-939f-652eeb882690
* Version Independent ID: 333295b9-ae38-40c8-2b00-8246312b4bd6
* Content: [az pipelines variable](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/variable?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines/variable.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines/variable.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by maggiepint** [comment]
I have routed this to the appropriate team for follow-up.

**Comment by atbagga** [comment]
> does this mean variable can be created just for build definitions?

Yes, The API will look for yaml pipelines which includes old (non yaml) build definitions but not release definitions. 

If you want to manage variables in release definitions you will have to use ```az devops invoke``` command and refer this [API](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/definitions/update?view=azure-devops-rest-5.0).

**Comment by geverghe** [comment]
@abhiramani-iptiq - I hope the above clarification solves your issue and I am closing this. Feel free to re-open the issue in case it is not clear. Further, next time, would be great if you could open an issue directly on Azure/azure-devops-cli-extension if you run into any problems with pipelines commands.
