### ISSUE TITLE
--List would return only 100 objects

### ISSUE THREAD

**Issue by Apholisha** [Azure/azure-cli-extensions#991]
List would return only 100 objects unless explicitly forced to return more using the --top parameter.  That should be mentioned in the documentation. Expectation would be that will return all and --top is to limit the number.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28af5781-4e9b-df81-6074-3de40adbe141
* Version Independent ID: fd6a9352-05f9-d121-dbca-fbf41be19ecb
* Content: [az devops project](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/project?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/project.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/project.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by zikalino** [comment]
this issues shuld be probably reported to Azure CLI repo, as it's not only related to extensions.

**Comment by atbagga** [comment]
@Apholisha This is API behavior - https://docs.microsoft.com/en-us/rest/api/azure/devops/core/projects/list?view=azure-devops-rest-5.0

Any listing API generally returns a fixed set of results (upto a MAX limit) appended by the continuation token to query more results in the next call if available. That is how the project list API also works. 

The above linked PR fixes the continuation token issue on project list command. 
Expectation to get all results from API is top is not specified is wrong. Generally it is the value of continuation token that will help you know if more results are available after your call response.

**Comment by Apholisha** [comment]
Ok, this might be a question of semantics, but when the documentation states "Get **all** projects in the organization that the authenticated user has access to."  one would expect "all projects" 

Also .. I'm using the CLI not the API so.. would you tell me where to see that token value?

**Comment by atbagga** [comment]
> Also .. I'm using the CLI not the API so.. would you tell me where to see that token value?

@Apholisha There was a generic issue in the CLI for handling of continuation tokens which is being handled in the PR link I added above (Not yet released. Expected ETA - End of this week)

In the new release later this week you will be able to get the continuation token in the json output and input it to the command in params. Help text for the command will look like this -

![image](https://user-images.githubusercontent.com/11888714/68102960-f3f96e00-fefa-11e9-8c71-b63b4c9e5d8b.png)

**Comment by Apholisha** [comment]
Thanks for the pointer.  Will check it out once the update is released.

and.. sorry to say so but.. I get that it makes sense form technical perspective, but not from users. Might be just me but this logic really doesn't come intuitive. Not to mention that the documentation it really misleading.  
Please look at it from users logic. You ask the system a question.. and you expect an answer. Not a half  answer .. and to have to explicitly ask weather you received the whole answer?
If this is the logic you will stick with, please at least have it proactively tell me if more entries are available.

**Comment by atbagga** [comment]
Adding @geverghe to see if we can do something about this. 

The top limits are generally set for each API independently depending on factors like resource consumption, data size etc. Since limits can be altered at the backend we cannot document them in the CLI command documentation.

**Comment by geverghe** [comment]
@Apholisha - could you point me to the documentation that is setting up the **all** project listing in list command expectation; specifically the line _"Get **all** projects in the organization that the authenticated user has access to"_

If we are setting that expectation, then yes, we need to update the text to ensure **all* is knocked off. 

Further, could you tell me about your scenario? If the objective is about fetching all projects, wouldn't the presence of a continuation token help  you loop through till you finish fetching all projects programmatically?

**Comment by Apholisha** [comment]
Hello  geverghe,
That particular line is from the API documentation: https://docs.microsoft.com/en-us/rest/api/azure/devops/core/projects/list?view=azure-devops-rest-5.0

The document that I first commented on is : https://docs.microsoft.com/en-gb/cli/azure/ext/azure-devops/devops/project?view=azure-cli-latest#ext-azure-devops-az-devops-project-list

This one doesn't say "all" explicitly, but it does not mention any sort of limitation either.  

As for my scenario, I wanted to generate a bunch of data for analyses.  The company I work for currently has 173 projects. I never checked all the entries returned - name by name. Nor did we know how many projects were there in the first place (most of them have not been active for years).. so it took a while to notice that some projects were not reported. 

 If developers are used to APIs giving them partial answers.. others are not.  Yes - with the token I can keep looping until the token tells me I'm done... now that I know that I have to.

**Comment by geverghe** [comment]
Ah I see. Looks like you can't open an issue for the API document. Let me follow up on this one internally.

Our expectation is that continuation token would help set up an understanding that a user needs to watch out for the token to evaluate if there are more results. Since this is a recent release, I will wait for some more feedback before we act on this. 

As it looks like we have clarified your issue, I am closing this issue. Feel free to reopen in case you feel there is some more clarification that you need.
