### ISSUE TITLE
az devops team list-member --team fails with  --project must be specified.

### ISSUE THREAD

**Issue by Apholisha** [Azure/azure-cli-extensions#992]
--project is listed as optional while in reality it is not.
Either the documentation is incorrect or the cli is not behaving as expected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aab5af2c-7c87-d5a7-e52a-d56b902eb44a
* Version Independent ID: c58f9b5a-db21-61e3-7512-e346c678ac56
* Content: [az devops team](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/team?view=azure-cli-latest#ext-azure-devops-az-devops-team-list-member)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/team.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/team.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@Apholisha The help text points out that it is required if default project is not set or you need to run the command from the context of a Azure Repos repo in which case the command will auto detect the repo from the git remote url.

> Name or ID of the project. You can configure the default project using az devops configure -d project=NAME_OR_ID. Required if not configured as default or picked up via git config.

You can learn more about using default settings and git repo auto detect in the docs [here](https://docs.microsoft.com/en-us/azure/devops/cli/?toc=%2Fazure%2Fdevops%2Fdev-resources%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fdev-resources%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
