### ISSUE TITLE
example

### ISSUE THREAD

**Issue by Zaniar0** [Azure/azure-cli-extensions#994]
Can you give one example of how to update permissions please. The documentation does not explain it very well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a283a450-7f6b-ceef-6fbd-f4e1d5129383
* Version Independent ID: 7361dfa6-28ed-1074-783e-baa233c3a308
* Content: [az devops security permission](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/security/permission?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops/security/permission.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops/security/permission.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@Zaniar0 Please check the updates on the linked issue where we are tracking this - https://github.com/Azure/azure-devops-cli-extension/issues/824

Closing this one since it is now being tracked in our extension repo.
