### ISSUE TITLE
az repos policy merge-strategy create

### ISSUE THREAD

**Issue by SebRosander** [Azure/azure-cli-extensions#999]
Lots of the parameters is set as optional, but is required for atleast "az repos policy merge-strategy create". Please update documentation.

Recreation of issue:

Step 1: 
az repos policy merge-strategy create --blocking true --branch master --enabled true --repository-id XXXXXXXX-XXXX-XXXX-XXXXX-XXXXXXXXXXXX

Generates ---&gt; az repos policy merge-strategy create: error: the following arguments are required: --use-squash-merge

Step 2: 
az repos policy merge-strategy create --blocking true --branch master --enabled true --repository-id XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX --use-squash-merge false

Generates --&gt; --organization must be specified. The value should be the URI of your Azure DevOps organization, for example: https://dev.azure.com/MyOrganization/ or your Azure DevOps Server organization. You can set a default value by running: az devops configure --defaults organization=https://dev.azure.com/MyOrganization/. For auto detection to work (--detect true), you must be in a local Git directory that has a "remote" referencing a Azure DevOps or Azure DevOps Server repository.

Step 3: 
 az repos policy merge-strategy create --blocking true --branch master --enabled true --repository-id XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX --use-squash-merge false --org https://dev.azure.com/XXXXXXXXXXX/

Generates --&gt; --project must be specified. The value should be the ID or name of a team project. You can set a default value by running: az devops configure --defaults project=&lt;ProjectName&gt;.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c80258ce-e599-1da0-f8f3-ffdbb3f8a5e2
* Version Independent ID: 1d34ada0-f8ef-9a31-c6fc-8c40a1d34488
* Content: [az repos policy merge-strategy](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/policy/merge-strategy?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/repos/policy/merge-strategy.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/repos/policy/merge-strategy.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by maggiepint** [comment]
@geverghe

**Comment by geverghe** [comment]
@SebRosander  I will look into Step 1. However, the rationale for 2 and 3 is that the values can be provided via any of the following and therefore are not "required" for the command. 

Users can configure org and project values in
1. Defaults using az devops configure -d organization=https://dev.azure.com/<org> project=<project name>
2. The values can be picked up from git context -> if you run this command from a local checkout of an azure repo, we default to the context which is available in git context.

Only if the above two are not available do the values of org and project become mandatory in the command. I am open to suggestions on conveying the above message.

@gauravsaralMs - do you know why we don't have --use-squash-merge marked as required/mandatory (in versions prior to the latest update where this schema has changed to --allow-<strategy-name>?

**Comment by atbagga** [comment]
@geverghe 
> do you know why we don't have --use-squash-merge marked as required/mandatory (in versions prior to the latest update where this schema has changed to --allow-[strategy-name]?
![image](https://user-images.githubusercontent.com/11888714/67268763-ec859e00-f4d2-11e9-8e1c-88fc48b5aa31.png)

It was marked as required in previous versions.

**Comment by atbagga** [comment]
@SebRosander As explained in the above comments there is a rationale behind marking the org and project param as not required. This is true for all commands in the extension.  And the help text is updated to reflect the same.
![image](https://user-images.githubusercontent.com/11888714/67268960-6027ab00-f4d3-11e9-87e5-853c951bf143.png)

Step 1 seems to be wrong. Can you check which version of the extension you are using? 

From what I checked.. till version 0.12.0 the parameter --use-squash-merge was marked as required and post that we introduced multiple policy options so each of those policy options is not required but atleast one needs to be mentioned hence none of them will be marked as required param. 

I will be closing the issue since this does not require any changes from our side.
